### ISSUE TITLE
XPointer schemes may not nest, but see ch. 16

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1049]
Please verify:

1\. this is XPointer syntax: http://www.w3.org/TR/xptr-framework/\#syntax
2\. the TEI schemes defined in chapter 16 are meant to be well-behaved XPointer schemes
3\. XPointer schemes may be chained, but may not be nested \[everything depends on this assumption, so please attack or confirm\]
4\. In ch. 16, we have examples such as:

a. string-range\(element\(/1\), 84,109\)
b. range\(xpath1\(id\(par1\)//emph\),xpath1\(id\(par2\)//emph\)\)

with TEI-defined schemes containing W3C-defined schemes in \(a\), and TEI-defined schemes containing third-party-registered schemes in \(b\).

Original comment by: @bansp

**Comment by hcayless** [comment]
I'm pretty certain these are all gone, and have been since the XPointers revision.
