### ISSUE TITLE
update ODD documentation on www.tei-c.org and in Guidelines

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1082]
Martin will update and improve http://www.tei-c.org/Guidelines/Customization/odds.xml\#body.1\_div.2 .  Brett offered to read the revised text as a novice reader and offer suggestions if necessary.

Then Kevin will incorporate any points from http://www.tei-c.org/Guidelines/Customization/odds.xml\#body.1\_div.2 into http://www.tei-c.org/release/doc/tei-p5-doc/en/html/USE.html\#MD that are not clearly tutorial points but belong in the Guidelines.

Original comment by: @kshawkin

**Comment by martindholmes** [comment]
I think this should be amber until PureODD work and all associated Stylesheets work has been completed.

**Comment by lb42** [comment]
Pure ODD has now been completed; the need to update the website document remains.

**Comment by lb42** [comment]
Furthermore, there seem to be two variants of this tutorial on the website:
http://www.tei-c.org/Guidelines/Customization/odds.xml is not quite the same as 
http://www.tei-c.org/Support/Learn/odds.xml  (the graphics dont work in the latter)

The revision should integrate the material from Documents/pureOdd/pureODDtutorial.xml as well as adding discussion of features not currently mentioned e.g. use of @include and @except on &lt;classRef>

**Comment by kshawkin** [comment]
Huh.  The version at http://www.tei-c.org/Guidelines/Customization/odds.xml is newer and derived from the other one (as shown in the revisionDesc), but I'm not sure why it was moved without fixing the relative links to the images without removing the original.

**Comment by lb42** [comment]
By  "the other one" do you mean the same as "the original"? Maybe you could remove the older version, replacing it by a link perhaps. The version in github should be the source we update in any case.

**Comment by kshawkin** [comment]
I've edited my original comment to clarify.  I'll figure out how to replace http://www.tei-c.org/Support/Learn/odds.xml with a link to http://www.tei-c.org/Guidelines/Customization/odds.xml .

**Comment by sydb** [comment]
@lb42 with prods & assistance from @martinascholger to update said documentation.

**Comment by lb42** [comment]
Neither of the links in Kevin's comment above is currently working.

**Comment by martinascholger** [comment]
I've updated the ODD documentation in wordpress (https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/) according to @lb42's document, see #1813
