### ISSUE TITLE
Bibliography: use of <idno> needs checking 

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1088]
The bibliography should reflect best practice as we describe it elsewhere in the Guidelines. This means that in the section using &lt;biblStruct&gt;,  it should not use &lt;idno&gt; as a direct child of &lt;biblStruct&gt;. It probably also means examples where &lt;idno type="URL"&gt; is used to provide a URL for an article etc should be changed to &lt;ref&gt; -- an &lt;idno&gt; should be an identifier, not a pointer. 

Original comment by: @lb42

**Comment by kshawkin** [comment]
As you can see, @sydb implemented this in June 2013 before I had the chance, and the ticket in SourceForge was then closed.  For the record, though, he has now implemented the deprecation: https://github.com/TEIC/TEI/commit/c9279125b98c125502be42ed740c546409927c32
