### ISSUE TITLE
consistency in "the Guidelines" vs. "these Guidelines"

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1165]
In the thread at http://lists.village.virginia.edu/pipermail/tei-council/2013/017200.html , there was slight support for using "these Guidelines" to refer to the current version of the Guidelines and reserving "the Guidelines" only for cases where you're talking about the history of the TEI Guidelines—that is, for it as a work.  We should sort through instances and adjust as needed.

Original comment by: @kshawkin

**Comment by hcayless** [comment]
This was marked green, but assigned to Council. I've made a stab at implementing it.

**Comment by kshawkin** [comment]
That has been hanging out on http://wiki.tei-c.org/index.php/User:Kshawkin/My_Council_obligations for a long time, but it looks like it got unassigned from me during the migration from SourceForge.  Thanks for taking care of it!
