### ISSUE TITLE
partial and recursive segmentation of s-units

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1193]
The content model of `<s>` allows for this element to nest inside itself.  However, the definition has a note that says, "For segmentation which is partial or recursive, the seg should be used instead."  In this case, it seems that `<s>` should not be allowed to nest inside itself, or we should drop that note.

Original comment by: @kshawkin

**Comment by martindholmes** [comment]
Reversed the original content model change to make it macro.phraseSeq again in commit 47c7157. I believe this should now be closed, but Council can confirm at the FtF.

**Comment by lb42** [comment]
Definitely done. Closing.
