### ISSUE TITLE
which part of TEI Guidelines takes precedence

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1230]
James and Lou said on 2013-11-11 during the Council meeting that the Guidelines prose takes precedence over the specifications.  I can't find this stated in the Guidelines but believe it should be added.  When doing so, be sure not to call the Guidelines prose "the prose" because it could lead someone to think we are referring to text appearing within a spec as opposed to the content model specified therein.

Original comment by: @kshawkin

**Comment by lb42** [comment]
We do actually say something like what Fabio suggests above already in #CFAMsc but I've made it more explicit by adding he following para:
  <p>As noted above, the notion of semantic conformance cannot be completely enforced in a
          formal way. The TEI conceptual model is expressed  by means of formal specification
          in a customization file, by means of descriptive prose in the body of the Guidelines,
          and implicitly by examples of usage. Any inconsistency between, for example, the text
          of the Guidelines and a part of a specification should be considered an error and reported
          to the TEI Council for correction. </p>
