### ISSUE TITLE
use of <listRef> in specs

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1239]
Our use of `<listRef>` in specs is inconsistent.  We should decide our preferred approach, document it in tcw20, and then fix any existing specs that don't match this practice.

For definitions of elements, we generally refer to one or more chapters in which the element is discussed.  For definitions of element or attribute classes, though, we seem to refer to the chapter documenting the module that defines this element or attribute.

This, however, leads to some strange situations.  For example, the spec for `att.transcriptional` has a `<listRef>` pointing to `#ST`, which discusses the TEI infrastructure and happens to define `att.transcriptional`, rather than to `#PH`, where these attributes are actually discussed.  I think this problem is unique to `#ST`, which contains all sorts of things not actually explained in that chapter.  But in the user interface it sends the user to a chapter irrelevant to the class.

In cases like this, perhaps we should add a second `<listRef>` to point to the chapter where the elements or attributes in the class are actually discussed.  Or perhaps we should just remove the reference to `#ST`.

Original comment by: @kshawkin

**Comment by lb42** [comment]
On inspection, this has already been done. At least, all the @target values currently in use point to specific  sections of the GL, rather than to #ST
