### ISSUE TITLE
Pointing between terms and glosses

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1272]
In the main Guidelines example for `<term>`, we see:

~~~~~
We may define <term xml:id="TDPV" rend="sc">discoursal point of view</term> as
<gloss target="#TDPV">the relationship, expressed
through discourse structure, between the implied author or some other addresser, and the
fiction.</gloss>
~~~~~

Surely it is much more likely that there will be a single central gloss or definition for a term, and that each usage of the term will point to that central definition? In other words, the pointing relationship should be inverted for the most common case:

~~~~~
We may define <term corresp="#TDPV" rend="sc">discoursal point of view</term> as
<gloss xml:id="TDPV">the relationship, expressed
through discourse structure, between the implied author or some other addresser, and the
fiction.</gloss>
~~~~~

Original comment by: @martindholmes

**Comment by lb42** [comment]
Added new example and clarificatory discussion
