### ISSUE TITLE
revisionDesc suggesting order of changes

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1281]
the note on revisionDesc says "Conventionally change elements should be given in reverse date order, with the most recent change at the start of the list". I suggest this is over prescriptive and misleading. Either it should be a descriptive "Conventionally change elements are", which I can take or leave, or prescriptive "Change elements should be given". The combination of "conventionally" and "should" is not right.

Given that change elements should be dated, I suggest the whole notion of recommending an order isn't needed anyway. This should be regarded as structured metadata, not a human-readable narrative.

So my suggestion to drop this sentence from revisionDesc, and change a related one in `<change>` to read "it is strongly recommended that changes are dated".

Original comment by: @sebastianrahtz

**Comment by raffazizzi** [comment]
The only example that doesn't have latest-first in the P5 directory is this test from 2012: https://github.com/TEIC/TEI/blob/master/P5/Test/torture.xml
Should I fix it or leave it alone?

**Comment by lb42** [comment]
Fix it!
