### ISSUE TITLE
xml:lang/langUsage

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1284]
CH-LanguagesCharacterSets.xml
/div/div[1]/p[1]/list[1]/item[2]

The value of the attribute &#x3c;att&#x3e;xml:lang&#x3c;/att&#x3e; identifies the language using a coded value. For maximal compatibility with existing processes, modelling this value in the following way is recommended (this parallels the modelling of &#x3c;att&#x3e;xml:lang&#x3c;/att&#x3e;):

Comment: This is circular: &#x22;this value&#x22; should probably refer to &#x3c;langUsage&#x3e;.

Original comment by: @jensopetersen

**Comment by sydb** [comment]
Fixed in f606e3b —I think the section can be improved further, but at least the completely circular and erroneous bits have been fixed.
