### ISSUE TITLE
dated info on XML processors

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1290]
CH-LanguagesCharacterSets.xml
/div/div[2]/div[6]/div[1]/head[1]

&#x3c;head&#x3e;&#x3c;!--4.5.1 --&#x3e;Non-Unicode Character Sets  and XML Processors&#x3c;/head&#x3e;

Comment: This section is so dated that it is bound to confuse more than enlighten.

Original comment by: @jensopetersen

**Comment by martindholmes** [comment]
Link with #1298.

**Comment by lb42** [comment]
syd and stefan to propose revisions to the chapter

**Comment by sydb** [comment]
@smjwsk is no longer on Council, so @hcayless just volunteered to take his place. @sydb will send comments so far to @hcayless, and the two of them will meet on Wed 02-15 10:00 ET to discuss moving forward.

**Comment by hcayless** [comment]
We corrected a lot of things and removed outdated advice. Closing
