### ISSUE TITLE
dated XML processor info

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1298]
CH-LanguagesCharacterSets.xml
/div/div[2]/div[6]/p[1]

Indeed, such projects are not obliged by their choice of XML to use Unicode in their documents. Provided they correctly declare at the requisite points any non-Unicode coded character set they may use, ensure that all their XML processors support their declared encoding, and then consistently employ that encoding in strict conformity with their declarations, they need not consciously concern themselves with Unicode unless and until they feel it is appropriate to do so.

Delete as dated and confusing.

Original comment by: @jensopetersen

**Comment by martindholmes** [comment]
Link with #1290.
