### ISSUE TITLE
lamenting the passing of SGML SDATA

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1299]
CH-LanguagesCharacterSets.xml
/div/div[2]/div[6]/div[2]/head[1]

Non-Unicode Characters in XML Documents

I think everything in this section is correct, but it will not help much, only mystify. Much of the section is given to a lamentation of the passing of SGML SDATA type (&#x22;a transparent use of a CER&#x22; at the end echoes this), but this will mean nothing to most TEI users (indeed, it meant nothing to me until I looked it up). That parsed entity references disappear as references when resolved (and that the result of this may be both pure character data and markup/PIs) needs to be said, but not in a section dealing with the problem of non-Unicode characters.

Original comment by: @jensopetersen

**Comment by hcayless** [comment]
HC, PFS, and SM recommend just deleting this section.
