### ISSUE TITLE
Updating Roma/eXist on release day: improve the process

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1317]
This is a placeholder bug to remind Council that there is an open issue with the reliability of, and instructions for, updating the eXist database on which Roma runs; see point 8 in the step-by-step section of the release instructions, TCW 22:

http://www.tei-c.org/Activities/Council/Working/tcw22.xml#d429477e345

Original comment by: @martindholmes

**Comment by peterstadler** [comment]
left a note in `~/etc/tei-exist.conf` to watch out for specical characters in the password.
The script is working (cf. releases 2.8 and 2.9.1), closing now
