### ISSUE TITLE
Need for a standard way to warn of class changes affecting ODDs

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1323]
The recent restructuring which caused `@rend`, `@style` and `@rendition` to be moved from att.global to att.global.rendition has inevitably caused some confusion as previously-working ODDs generate invalid schemas when processed against the latest P5 source.

Since this is a scenario that is likely to happen again, it would be a good idea to devise and document a standard method of warning against this; obviously Schematron would be useful, but it's not clear where the best place to put it might be, and there are probably other mitigating actions we can carry out leading up to and following such a change which would warn people.

Original comment by: @martindholmes

**Comment by martindholmes** [comment]
Council 2015-10-26: Close this ticket, and Syd will create a new ticket based on his suggestion above.
