### ISSUE TITLE
XSL(T?) as a value for @scheme on constraintSpec

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1326]
Per Council discussion 2015-05-28: The value "XSL" is (we presume) not handled by the Stylesheets, so it should be removed.

Original comment by: @martindholmes

**Comment by martindholmes** [comment]
Council subgroup 2015-10-25: The list should be semi, not closed, and it should contain only those things our current ODD p,rocessing supports (i.e. the two Schematrons). If someone writes their own ODD processor and devises a way to write and process constraints in XSLT, then they should add it in their own schema.

**Comment by martindholmes** [comment]
Council agrees with the suggestion above. SB to carry out.

**Comment by sydb** [comment]
(Not sure why I didn’t close this back in March.)
