### ISSUE TITLE
Guidelines processing should show inheritance of overridden atts

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1328]
Arising out of <https://sourceforge.net/p/tei/bugs/738/>:

When an element overrides the definition of one or more attributes in a class which is a member of a class of which the element is a member, it should still show on the spec page that it is a member of that bottom level class. Example: `<media>` is a member of att.media, from which it inherits att.internetMedia/`@mimetype`; it overrides this, which somehow causes the list of classes in the Spec page to include att.media but not att.internetMedia.

Original comment by: @martindholmes

**Comment by hcayless** [comment]
Should this be kicked over to the Stylesheets issues?

**Comment by martindholmes** [comment]
Council subgroup 2015-10-25: This is definitely a slight inconsistency in our display, but fixing it might be horrendously difficult. Either close and walk away, or move it to the Stylesheets and make it low priority.

**Comment by martindholmes** [comment]
Council decision: Find out whether this only occurs if there is a single attribute in the nested class. If that is the case, it's less urgent. If it also occurs with classes where there are multiple attributes, then it is more significant and must be addressed more quickly.

**Comment by peterstadler** [comment]
> Should this be kicked over to the Stylesheets issues?

Yes!

**Comment by hcayless** [comment]
Moved to TEIC/Stylesheets#150
