### ISSUE TITLE
Intended use of <distinct> attributes

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1329]
Examples use `@type` only. It's not clear whether the other three attributes (`@status`, `@time` etc) are alternatives or what.

Original comment by: @lb42

**Comment by hcayless** [comment]
<http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COHQHD> gives parallel examples using `@type` and the other attributes. Is that insufficient?

**Comment by lb42** [comment]
We should include examples of all three attributes in the tagdoc itself, and then close ticket
