### ISSUE TITLE
Link checking in Examples

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1333]
Followup from [bugs:#744]. 

See Martin's comment from that bug:

> Just did it as a test:
> 119 links checked. 22 warnings found. 43 errors found.
> There are over 400 links, but most are duplicates; many are not intended to work (www.example.com etc.).
> Should be possible to add this into the system, filtering out the example.com ones. I'm going to re-open this bug and assign it to myself to do that.

Original comment by: @hcayless

**Comment by jamescummings** [comment]
Council agreed it is low priority, leaving open.

**Comment by ebeshero** [comment]
F2F subgroup suggests that we do a specific link check.

**Comment by smjwsk** [comment]
Will check the list.

**Comment by peterstadler** [comment]
Probably better look at http://jenkins-paderborn.tei-c.org/job/Guidelines-Link-Check/ws/checkResults/linkchecker-out.xml and ping me if you want an update.

The job looks like 
```
VERSIONFILE=$JENKINS_HOME/jobs/TEIP5/workspace/P5/VERSION
VERSION=`cat ${VERSIONFILE}`
TARGET=$JENKINS_HOME/jobs/TEIP5/lastSuccessful/archive/P5/release/doc/tei-p5-doc/en/html/index.html


echo "Running link checking for P5 version $VERSION."

if [[ $VERSION =~ [a-z]+$ ]]; then
	echo "Using configuration for pre-release version."
	linkchecker --config=$WORKSPACE/../linkcheckerrcalphabeta $TARGET

else
	echo "Using configuration for release version."
	linkchecker --config=$WORKSPACE/../linkcheckerrcrelease $TARGET
fi

echo "Transforming checker report ..."
saxon -s:checkResults/linkchecker-out.xml -xsl:$WORKSPACE/../linkchecker.xsl
echo "Done!"
exit
```

and the config

```
[checking]
anchors=1
recursionlevel=6

[output]
#log=xml
fileoutput=xml
quiet=1
status=0

[xml]
filename=checkResults/linkchecker-out.xml

[filtering]

#This is a multiline thing; each line is a regex specifying something to be ignored.
#In pre-release mode, we ignore the missing readme file for the next release.

ignore=readme-\d\.\d\.\d\.html
  Guidelines\.mobi
  tei-c.org/$
  google\.com/search
  #xpointer(id('chum'))
```

**Comment by peterstadler** [comment]
just ran a link check on the Paderborn Jenkins with no complaint

**Comment by peterstadler** [comment]
Since the Jenkins job is not run regularly we'll have to keep that in mind when going for a release. Will add an extra step to http://www.tei-c.org/Activities/Council/Working/tcw22.xml

**Comment by martindholmes** [comment]
The link check is run once a week on my Jenkins server.
