### ISSUE TITLE
wording tweak for @ref

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1334]
`@ref` reads http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.canonical.html

(reference) provides an explicit means of locating a full definition for the entity being named by means of one or more URIs.

change to

(reference) provides an explicit means of locating a full definition or identity for the entity being named by means of one or more URIs.

The example given is a URL to VIAF, which doesn't provide a definition, it provides an identity, as do all authority control systems, which appear to be a common use case for this attribute. 

    

Original comment by: @stuartyeates

**Comment by hcayless** [comment]
I think this is clearly right, and amounts to correcting a typo.
