### ISSUE TITLE
Sourceforge Guidance doc out of date

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1335]
I notce that the document [Using the TEI Sourceforge Repository](http://www.tei-c.org/Guidelines/P5/get.xml) is well out of date already, and set to become even more so with the impending migration. It needs a pretty thorough rewrite.

Original comment by: @hcayless

**Comment by martindholmes** [comment]
Actually I reworked this a couple of weeks ago for the change to github, but it could certainly use some fresh eyes.

**Comment by hcayless** [comment]
@hcayless will review and add the link back to the Guidelines. We will need to make changes to reflect the new git workflow.

**Comment by hcayless** [comment]
Fixed, but I noticed the make target for "html" is wrong. Should be "html-web". I can't edit these things anymore since I upgraded my local Java. Reopening and reassigning to Martin in the hopes that he can!

**Comment by martindholmes** [comment]
I can, and I will, as soon as I have access to my work desktop. I'm away at the moment.

**Comment by hcayless** [comment]
Fixed. I can edit, just not upload.
