### ISSUE TITLE
Disappearing source in Ch. 11

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1336]
Chapter 11 uses this example:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#Note77_return

from Géométrie pratique by Bovelles, and credits it to this source:

http://ancilla.unice.fr/Illustr.html

The source is an ancient page which keeps disappearing from the web, breaking our link. We need to discover whether this particular page image has been published by the original copyright holders in some other location where it's more stable, or failing that, either link to the last Wayback machine version of the page (from Feb 2013):

https://web.archive.org/web/20130211170317/http://ancilla.unice.fr/Illustr.html

or remove the link altogether.

Original comment by: @martindholmes

**Comment by lb42** [comment]
Took the Easy Way Out and removed the reference.

**Comment by stefaniegehrke** [comment]
could we use this image available via the BVH ? taken from an incunabula kept at Orléans but unfortunately not a representative for the same publication of which the Lyon item is an exemplar : http://www.bvh.univ-tours.fr/Consult/consult.asp?numtable=B452346101_C2619&numfiche=779&mode=1&index=102&ecran=0 ?
