### ISSUE TITLE
Notes missing in Guidelines translations

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1339]
Notes within element definition pages (e.g. http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cb.html) disappear when switching to another language (e.g. http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-cb.html). This is a serious problem and I suggest to disable the entire translated Guidelines versions until this is fixed.

Original comment by: @Martin-de-la-Iglesia

**Comment by peterstadler** [comment]
will translate

**Comment by martindholmes** [comment]
For the display issues, I've created a bug on the Stylesheets:

https://github.com/TEIC/Stylesheets/issues/123
