### ISSUE TITLE
state definition wrong in Guidelines translations

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1340]
It looks like somehow the definition text of `<refState>` ended up in `<state>` in the translated versions of the Guidelines.

English: `<state>` contains a description of some status or quality attributed to a person, place, or organization often at some specific time or for a specific date range.

German: `<state>` beschreibt einen Bestandteil einer Standardreferenz mittels der Milestone-Methode.

cf.:

English: `<refState>` (reference state) specifies one component of a canonical reference defined by the milestone method.

German: `<refState>` (reference state) specifies one component of a canonical reference defined by the milestone method.

Original comment by: @Martin-de-la-Iglesia

**Comment by martindholmes** [comment]
Council subgroup 2015-10-25: We suggest setting to green, asking Peter to a) check previous states of the repo to see if there ever were versions of the original definitions in these languages, and reinstate them if they are there; or b) fix the German translations and try to find Portuguese and Spanish speakers to provide the others.

**Comment by jamescummings** [comment]
Council agreed with subgroup.

**Comment by peterstadler** [comment]
Did some digging:
* found some old Italian description (svn rev 2532) which seems to make sense: "contiene la descrizione di uno stato o qualità durature di una persona".
*  The German (svn rev 3750)  as well as the Spanish (svn rev 2593)  translation seem to have been introduced wrong from the start …

Will remove the wrong translations and add a new German translation.

**Comment by fabio-ciotti** [comment]
I will give you an updated Italian translation
