### ISSUE TITLE
@cause in att.transcriptional probably doesn't belong

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1342]
The ``@cause`` attribute, defined in <http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.transcriptional.html>, is constrained by a value list that only applies to `<retrace>`, and it is only discussed in the guidelines under that element, even though its membership makes it available on, e.g. `<add>`. It would actually be nice to be able to note a reason for an addition, but this doesn't permit it. ``@cause`` should probably only be available on `<retrace>`.

Original comment by: @hcayless

**Comment by martindholmes** [comment]
Another approach would be to make the valList semi-open, and expand it to provide values suitable for the other elements in the class.

**Comment by lb42** [comment]
Some thought is clearly needed as to whether this attribute is genuinely applicable across all members of this class.If it is, there really ought to be more examples demonstrating its usefulness. At present the class definition does not include *any* examples at all, which cannot be right.

**Comment by jamescummings** [comment]
Even on retrace this is a bizarrely closed list ...  It works with all the other elements.  It should be semi- and more examples provided.

**Comment by lb42** [comment]
I've made it a semi closed list, but am changing status of ticket back to amber, as it really needs some thought

**Comment by hcayless** [comment]
I'm also not clear on what the distinction is between this attribute and `@reason`, which appears on several other elements, but doesn't have a model class (perhaps because there's no possibility of a consistent value list?)

**Comment by hcayless** [comment]
`<add place="margin" cause="missing">` or `<del cause="correction">` seem perfectly plausible to me. It's just that there'll be a different list for every member.

**Comment by raffazizzi** [comment]
F2F subgroup suggests to remove suggested values from the schema and only keep them in the Guidelines, possibly with new examples on add and del (currently only on retrace).
