### ISSUE TITLE
@rend="gloss" is misused in examples

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1343]
As reported by SC to SB, the list of examples of `<list>` includes at least two instances of @type="glossary" on lists which are clearly not glossaries at all. I believe is a by-product of the old setup whereby rendition/form was confused with typology. The definition of "glossary" in the OED does not seem in any way to support this as a descriptor for a school report, or the "list of Celia's charms" from chapter CO.

**Comment by lb42** [comment]
So what @type value is being suggested? Both of these examples look more  like "glossaries" than anything else.

**Comment by lb42** [comment]
Agreed that it's not a gloss; suggest @type="property"

**Comment by jamescummings** [comment]
JC will implement.

**Comment by jamescummings** [comment]
At Council F2F in Lyon rest of Council agrees to this.

**Comment by jamescummings** [comment]
Fixed in revision 76f993c
