### ISSUE TITLE
Content model of <app> 

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1345]
The current content model of &lt;app> allows model.global elements anywhere between its other children. Since &lt;app> is itself a member of model.global, this permits a meaningless recursion. Since the function of &lt;app> is purely to group together &lt;lem> &lt;rdg> and &lt;rdgGrp elements, it's hard to see any justification for any other child elements : if they are needed, they should be given within the &lt;lem> (etc.) concerned. It might however conceivably be useful to permit a &lt;note> within an apparatus (for example, one commenting on the selection of readings made). The proposal is therefore to replace model.global by model.noteLike within the content model.

**Comment by hcayless** [comment]
Couldn’t have said it better myself. Notes are actually very important. Apparatus entries may consist only of notes, in fact. I know something like `<note type"app">` might substitute for that case, but being able to put everything apparatus-related in an `<app>` is very convenient. As an aside, I’d consider a `<note>` directly inside `<app>` as a different thing than a `<note>` inside a `<lem>` or `<rdg>`. The latter would represent a note occurring in the variant—it’s quite common to have, e.g., a Renaissance edition with handwritten notes that have info you’d want to record in an apparatus.

Something like:

lem?, ( rdg | rdgGrp | wit | model.noteLike )*

as a content model?

**Comment by lb42** [comment]
Looks good to me. Let's do it.

**Comment by MarjorieBurghart** [comment]
I concur!

**Comment by jamescummings** [comment]
I concur

**Comment by lb42** [comment]
subgroup agrees : do it

**Comment by lb42** [comment]
Implemented at commit 97ffae421e2be458460e6dee408ae36573c465b7
