### ISSUE TITLE
Attributes for <xenoData>

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1346]
The `<xenoData>` element (see #453) was added in release 2.9.0, but there was some disagreement over whether new attributes would be needed for it. Suggestions included:

 * `@scope`, intended to indicate what the data inside `<xenoData>` is aimed at was strongly advocated for
 * a mechanism for describing the format of `<xenoData>`'s content was mooted, possibly containing the MIME type

**Comment by lb42** [comment]
General agreement in council subgroup A:
-  xenodata shd describe itself so it's not for TEI to do so; 
- where xenodata is repeated association between a piece of xenodata and sub part of document should be handled by @decls  (and fix that if necessary)

**Comment by martindholmes** [comment]
Council decision: Action on HC to elaborate the intro to the RDF example to specify that the empty @rdf:about specifies that the RDF applies to the current document, and show how you can point from xenoData content to parts of the TEI file if you need to.
