### ISSUE TITLE
Translations: indicate when they are out of date with the English version

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/TEI#1348]
A sizable chunk of the text in the reference pages is translated to other languages (mostly French). It would be useful to indicate *on the ref pages* whether the English text has outdated the translation. It would be possible to determine this based on `@versionDate` on `<desc>` and `<remarks>`.

**Comment by peterstadler** [comment]
Very true and good point. But should probably be moved to the Stylesheets repo?!
Might also be related to https://github.com/TEIC/Stylesheets/issues/123

**Comment by lb42** [comment]
I agree that this is a stylesheet issue. How do you envisage the status of the translation  being indicated though?

**Comment by hcayless** [comment]
Moved to TEIC/Stylesheets#138
