### ISSUE TITLE
odd4odds should be in Exemplars

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1349]
The odd4odds schema should be available in ./P5/Exemplars.
However, generating odd4odds.odd is non-trivial, so we can't just pop it in. The build process will have to be modified to accommodate it.
See http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise/schemas/odd4odds.odd for an example of a somewhat outdated odd4odds.odd file.

**Comment by hcayless** [comment]
Seems reasonable, but no idea how to do it, so assigning Syd to either do it or find someone else and explain it to them.

**Comment by sydb** [comment]
OK, ’tis on my list of things to do.

**Comment by ebeshero** [comment]
@sydb Just a nudge about this, since you asked for periodic nudges to get this posted somehow! And can you point us to an up-to-date version of your odd4odds?

**Comment by sydb** [comment]
Paper proposal for [TEI 2017](http://hcmc.uvic.ca/tei2017/index.php) on the topic has been submitted. @ebeshero: the current version, still called `odd4odds`, is available as a WWP seminar handout, but because of new security rules at Northeastern you can’t see the list of them until I get around to making an index page:

- [HTML custom documentation](http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise/schemas/odd4odds.html)
 - [extracted Schematron rules](http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise/schemas/odd4odds.isosch)
- [ODD file itself](http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise/schemas/odd4odds.odd)
- [RELAX NG, compact syntax](http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise/schemas/odd4odds.rnc)
- [RELAX NG, XML syntax](http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise/schemas/odd4odds.rng) 

The [XSLT that generates the ODD](http://www.wwp.neu.edu/outreach/seminars/_current/handouts/ODD_exercise_support/toctoc_generation/TEI_to_odd4odds.xslt) is in a different directory.

**Comment by sydb** [comment]
Done at c293b6275365b5eefc60399fbec60c7879bc7ee8, although a few tweaks and bug fixes were made after that. (And more are probably on the way.) It is called tei_customization at the moment, but Council is considering better names, at least for when it shows up in oXygen framework.
