### ISSUE TITLE
Use of comments in egXML

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1351]
Follow-up from Issue #576 : Editing the Guidelines should be updated to include instructions that plain ellipses in comments should be used to signify missing elements, while ellipses in square brackets should be used to signify PC Data ellided. The existing Guidelines egXMLs should be brought into conformity with this.

**Comment by hcayless** [comment]
Guidance added to [TCW 24](http://www.tei-c.org/Activities/Council/Working/tcw24.xml).
