### ISSUE TITLE
taxonomy should be a child of category

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1356]
This ticket is a fork of #496 , which has two distinct proposals, one of which is uncontroversial and green to go ahead, and one of which is still controversial. This ticket is for the second issue:

Consider a taxonomy of literary forms (this arises out of a different project). You might characterize literary work in many different ways:

~~~~~
<taxonomy xml:id="literaryForms">
  <category xml:id="lfProse">
    <category xml:id="lfShortStory"/>
    <category xml:id="lfNovella"/>
    <category xml:id="lfNovel"/>
  </category>
  <category xml:id="verse">
[...]
  </category>
</taxonomy>
~~~~~

Now, inside the "verse" category we need to characterize different features of the verse, including foot type, line-length and stanza type:

~~~~~
<category xml:id="verse">
  <category xml:id="lfFootAmphibrach"/>
  <category xml:id="lfFootAnapaest">
    [...more foot types...]
  <category xml:id="lfLineMonometer"/>
  <category xml:id="lfLineDimeter"/>
    [...more line lengths...]
  <category xml:id="lfStanzaCouplet"/>
  <category xml:id="lfStanzaTercet"/>
    [...more stanza types...]
</category>
~~~~~

It's clear here that we have three distinct types of category; they don't belong as siblings. What we really have are three distinct taxonomies, that should be marked up as such:

~~~~~
<category xml:id="verse">
  <taxonomy xml:id="lfFoot">
    <category xml:id="lfFootAmphibrach"/>
    <category xml:id="lfFootAnapaest">
    [...more foot types...]
  </taxonomy>
  <taxonomy xml:id="lfLine">
    <category xml:id="lfLineMonometer"/>
    <category xml:id="lfLineDimeter"/>
    [...more line lengths...]
  </taxonomy>
  <taxonomy xml:id="lfStanza">
    <category xml:id="lfStanzaCouplet"/>
    <category xml:id="lfStanzaTercet"/>
    [...more stanza types...]
  </taxonomy>
</category>
~~~~~

It makes no sense to use nested categories for this; these are sub-taxonomies within the overall taxonomy of literary forms. On this basis, I argue that `<taxonomy>` should be available inside `<category>`.

**Comment by martindholmes** [comment]
See this discussion on the ontology sig list:

http://sourceforge.net/p/tei/mailman/message/34584645/

**Comment by jamescummings** [comment]
I think I've already lost this battle on the previous ticket. While I disagree I believe council has already accepted the notion of nesting taxonomies whether in category or not. Make green and go for it. *sigh*

**Comment by sydb** [comment]
Council is unconvinced; the discussion on the ontology list is indecisive; thus closed-won’t fix.
