### ISSUE TITLE
Period missing

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1360]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L666

Rather, they should be regarded as a base which can be elaborated if necessary by different scholars in different disciplines 

=>

Rather, they should be regarded as a base which can be elaborated if necessary by different scholars in different disciplines.

**Comment by lb42** [comment]
Fixed.
