### ISSUE TITLE
Wording tweak in PH-PrimarySources

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1361]
https://github.com/TEIC/TEI/blob/master/P5/Source/Guidelines/en/PH-PrimarySources.xml#L18
elements for the encoding of digital facsimiles or images of such materials
=>
elements for the encoding images of such materials
alternatively:
elements for the encoding of digital facsimiles i.e. images of such materials

**Comment by brettttt** [comment]
The phrasing here is confusing, I'd argue, since it comes before the term digital facsimile is defined as being "composed of digital images of the original source, typically one per page, or other written surface." Also, the "or" before "images of such materials" is very likely to be read as joining two things in a series rather than as introducing an appositive.

**Comment by lb42** [comment]
"elements for handling  encoded images of such materials" seems a better choice, possibly with a forward reference to <soCalled>digital facsimiles". We don't describe how to *make* digital images of pages.

**Comment by brettttt** [comment]
I'm OK with that. Does the word "encoded" do any important work? If not, "elements for handling images of such materials" would suffice, no?

**Comment by lb42** [comment]
I would suggest that it does. We don't say anything about how to organize your analogue slide collection.

**Comment by lb42** [comment]
So reworded.
