### ISSUE TITLE
Tweak of sentence about the facsimile element in ch. 11

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1363]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L126

The <gi>facsimile</gi>
         element is designed for the case where the digital facsimile contains only images, whereas
         the <gi>sourceDoc</gi> element is for use in the case where such images are complemented by
         a documentary transcription.

The first part of this sentence (up to the comma) seems sloppily worded, especially given the way that "digital facsimile" has been characterized just above this. 

Suggested revision:  The facsimile element is designed for the case where the images of the digital facsimile constitute the entire edition, whereas <gi>the sourceDoc</gi> element is for use in the case where such images are complemented by a documentary transcription.

**Comment by lb42** [comment]
The real problem with this is that a "digital facsimile" can contain more than a &lt;facsimile element. A better rewording might be "The facsimile
element may be used alone in  the case where the digital facsimile contains only images, or it may be complemented by a sourceDoc element  in the case where such images are complemented by
a documentary transcription"

**Comment by raffazizzi** [comment]
If a "digital facsimile" may contain more than one `<facsimile>` element, then maybe "alone" is not the best word. What about flipping the sentences around:

"A sourceDoc element is necessary when a digital facsimile is complemented by a documentary transcription. When the digital facsimile pertains solely to images, however, only facsimile elements should be used."

This also connects better with the following section by clarifying what is meant by "simple case":

"In this section, we first discuss **this** simpler case, returning to the use of the sourceDoc element..."
(text should not be in bold in the guidelines, I'm simply indicating a proposed change).

**Comment by lb42** [comment]
How about "The sourceDoc element is used when a digital facsimile contains a documentary transcription; the text element when it contains a textual transcription. When the digital facsimile contains only images, however, only facsimile elements should be used."

**Comment by raffazizzi** [comment]
+1 from me, @lb42.

**Comment by hcayless** [comment]
Assigning to Martina to implement, as @lb42's suggestion seems good.

**Comment by martinascholger** [comment]
+1 from me too. Are there any objections or can I go for it?

**Comment by brettttt** [comment]
Since Mr. Cayless gave the go-ahead, I don't think you need any more authorization. But FWIW, Lou's suggested wording is fine by me, too.
