### ISSUE TITLE
Make mention of facsimile in ch. 11 a <gi>

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1364]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L145

<p>In the simplest case, a facsimile just contains a series of <gi>graphic</gi> elements, each
         of which identifies an image file:

=>

<p>In the simplest case, <gi>facsimile</gi> just contains a series of <gi>graphic</gi> elements, each
         of which identifies an image file:

**Comment by lb42** [comment]
Agreed.
