### ISSUE TITLE
Typo (?) in ch. 11: "embedding" for "embedded"

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1365]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L404

It's possible that I'm missing some nuance that's intended, but it seems to me that in the phrase 

         it may be preferable to present it as an embedding transcription

"embedding" is an error for "embedded."

**Comment by lb42** [comment]
Fixed
