### ISSUE TITLE
Incorrect @target in <ptr> in ch. 11

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1367]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L633

In

&lt;item>methods of recording editorial or other alterations to the text, such as expansion of abbreviations, corrections, conjectures, etc. (section &lt;ptr target="#PHCH"/>)&lt;/item>

I'm puzzled about the presence of "unusual spaces, lines, page and line breaks" in this &lt;item>. It looks to me like all of those things are discussed in 11.5, not 11.3.2.

**Comment by lb42** [comment]
Section PHCH ("Altered corrected or erroneous text") does what it says on the tin. If however you're questioning the reference to "unusual spaces etc." in the *next* item, which refers to PHPH, I agree that the emphasis is a bit odd. Have tried to improve it by a small rewording.
