### ISSUE TITLE
wording tweak in description of att.global.responsibility

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1368]
At https://github.com/TEIC/TEI/blob/master/P5/Source/Specs/att.global.responsibility.xml#L12

In 

<desc versionDate="2014-12-10" xml:lang="en">provides attributes indicating the agency 
    responsible for some aspect of the text, the markup or 
    something asserted by the markup, and the degree of certainty 
    associated with it.</desc>

"agency" should be "agent" (shouldn't it?)

**Comment by lb42** [comment]
Why? An "agent" is a human being (for me at least), whereas @resp may well be used to assert a non-human agency such as a piece of software,

**Comment by raffazizzi** [comment]
As far as I know (and you know I'm not a native speaker), an "agent" is a person (it could be a company). An "agency" acts on behalf of a person. If we agree that a piece of software acts on behalf of a person (I like to think so), then "agency" is a better term for this.

**Comment by lb42** [comment]
Closing for now, since we seem to be agreed the word is appropriate.
