### ISSUE TITLE
Another sentence tweak for ch. 11 (sentence spans example)

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1369]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1168

Continuing the sentence that begins "Assuming that we have previously . . . " across the example is awkward. I suggest changing "Assuming" to "Assume," removing the comma immediately following the example, and capitalizing "this" (viz., "This extract might now . . . ").

**Comment by lb42** [comment]
Accepted
