### ISSUE TITLE
"deleatur or dele" instead of "delta"

### ISSUE THREAD

**Issue by gerritbruening** [TEIC/TEI#1370]
https://github.com/TEIC/TEI/blob/master/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2129

and by the metamarks resembling the &lt;q>delta&lt;/q> deletion symbol
=>
and by the proofreading mark resembling the &lt;term>deleatur&lt;/term> or &lt;term>dele&lt;/term> symbol

**Comment by brettttt** [comment]
Note also the singular (proofreading mark)--there's only one deletion symbol that applies to the section marked by the horizontal and vertical lines.

**Comment by raffazizzi** [comment]
Thanks for noticing this - it seems to be an easy fix. Any objections from anyone before I proceed and fix it?

**Comment by lb42** [comment]
I've never come across these terms for a deletion symbol before. Maybecthey need a bit of explanstio? And the symbol concerned does look a bit like a delta

**Comment by lb42** [comment]
OK ignore that. I have now looked it up on Wikipedia and am much better informed!

**Comment by gerritbruening** [comment]
OK, thanks!
But what about
>metamarks resembling
=>
proofreading mark resembling

(see above, see also Brett's comment)
