### ISSUE TITLE
Yet another sentence tweak in ch. 11 (re: <add> and <del> containment)

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1371]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1243

The &lt;gi>add&lt;/gi> and &lt;gi>del&lt;/gi> elements defined in the core module suffice only
               for the description of additions and deletions which fit within the structure of the
               text being transcribed, that is, which each deletion or addition is completely
               contained by the structural element (paragraph, line, division) within which it
               occurs.

The last part of this sentence does not clarify what it's supposed to and is, in fact, nonsensical, since "within which it occurs" *means* that it is "completely contained." Also, the second "which" has no clear referent. 

Suggested revision: The &lt;gi>add&lt;/gi> and &lt;gi>del&lt;/gi> elements defined in the core module suffice only for the description of additions and deletions which fit within the structure of the text being transcribed, that is, for cases in which each deletion or addition is completely contained by a structural element (e.g., paragraph, line, division).

**Comment by lb42** [comment]
Agreed
