### ISSUE TITLE
Wording in description of use cases for <delSpan/> in ch. 11

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1372]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1277

&lt;q>
An authorial manuscript will often contain  several occasions where sequences of whole lines are marked for deletion, either by boxes or by being struck out.
&lt;/q>

Removing the reference to the specific Eliot typescript has made the specificity of the last half of the sentence confusing: Why "several"? Why "by boxes"? The words "will" and "occasions" obscure a bit, too, I think.

Suggested revision: Authorial manuscripts often contain sequences of whole lines that are marked for deletion.

**Comment by lb42** [comment]
Fixed
