### ISSUE TITLE
Oddity in reference to <app> (ch. 11)

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1374]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1404

&lt;q>
The &lt;gi>app&lt;/gi> element presented in chapter &lt;ptr target="#TC"/> provides similar
               facilities, by treating each state of the text as a distinct reading.
&lt;/q>

This seems to be a non sequitur. "Similar facilities" to what?

**Comment by lb42** [comment]
Similar facilities to the mechanisms discussed in the preceding sections. I see no need to remove the comment.

**Comment by gerritbruening** [comment]
So maybe =>
similar facilities to the ones discussed here

**Comment by raffazizzi** [comment]
I like @gerritbruening's suggestion, or "discussed previously" if we want to be more precise.

**Comment by lb42** [comment]
Agreed. So implemented.
