### ISSUE TITLE
Placement/accuracy of information about transposition

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1376]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1435

&lt;q>
&lt;p>Another feature commonly encountered in manuscripts is the use of circles, lines, or
               arrows to indicate transposition of material from one point in the text to another.
               No specific markup for this phenomenon is proposed at this time. Such cases are most
               simply encoded as additions at the point of insertion and deletions at the point of
               encirclement or other marking. &lt;/p>
&lt;/q>

This paragraph seems to me out of place under its current heading ("Cancellation of Deletions and Other Markings"). I would simply delete, since these sentences also seem to be obsolete. If it is thought that something needs to be said about such marks in this place, I would substitute a reference to 11.3.4.5 (and perhaps move the current sentences under that heading).

**Comment by lb42** [comment]
Agreed. Commented this paragraph out for the confusion of posterity,
