### ISSUE TITLE
Make discussion of <hand> consistent in ch. 11

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1377]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1571

&lt;q>
For many text-critical purposes it is important to signal the person responsible (the <term>hand</term>) for the writing of a whole document, a stretch of text within a document, or a particular feature within the document.
&lt;/q>

As the very next sentence explains, "hand" does not equal "person responsible."

Suggested revision:

For many text-critical purposes it is important to signal the &lt;term>hand&lt;/term> responsible for the writing of a whole document, a stretch of text within a document, or a particular feature within the document.

**Comment by lb42** [comment]
Fixed
