### ISSUE TITLE
Typo in PHHR (plural/singular)

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1378]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1699

The value of the &lt;att>hand&lt;/att> attribute should be a pointer to a hand identifiers 

=>

The value of the &lt;att>hand&lt;/att> attribute should be a pointer to a hand identifier

**Comment by lb42** [comment]
Fixed
