### ISSUE TITLE
Typos in PHDA (example from Omar Khayam)

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1380]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1861

<q>
<l> The Moving Finger wri<damage agent="water" group="1">es; and</damage> having writ,</l>
<l>Moves <damage agent="water" group="1">on: nor all your</damage> Piety nor Wit</l>
<l><damageSpan agent="water" group="1" spanTo="#washOut"/>Shall lure it back to cancel half a Line,</l>
<l>Nor all your Tears wash <anchor xml:id="washOut"/> out a Word of it</l>
</q>

The transcription has a couple of errors (missing the "t" in "writes"; substitutes "your" for "thy" twice). 
Should be: 

<l> The Moving Finger writ<damage agent="water" group="1">es; and</damage> having writ,</l>
<l>Moves <damage agent="water" group="1">on: nor all thy</damage> Piety nor Wit</l>
<l><damageSpan agent="water" group="1" spanTo="#washOut"/>Shall lure it back to cancel half a Line,</l>
<l>Nor all thy Tears wash <anchor xml:id="washOut"/> out a Word of it</l>

**Comment by lb42** [comment]
fixed
