### ISSUE TITLE
Problem with organization/reference in PHDA

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1381]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1872

<q>
Here, several phenomena of illegibility and conjecture all result from a single cause: an area of damage to the text caused by rubbing at various points.
</q>

This refers not to the most recent example but the one before it. The best fix, I think, is to make it refer to the immediately preceding example: 

Here, several phenomena of illegibility and conjecture all result from a single cause: water has damaged the text at various points.

**Comment by lb42** [comment]
Fixed
