### ISSUE TITLE
Make mention of join in ch. 11 a <gi>

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1382]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L1875

<q>
In cases such as this, the join element may be used to indicate which tagged features are part of the same physical phenomenon.
</q>

=>

<q>
In cases such as this, the <gi>join</gi> element may be used to indicate which tagged features are part of the same physical phenomenon.
</q>

**Comment by lb42** [comment]
fixed
