### ISSUE TITLE
Clarify description of @target in spec for metamark

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1383]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/metamark.xml#L35

<q>
<desc versionDate="2013-04-16" xml:lang="en">identifies one or more elements to which the function indicated by the metamark applies.</desc>
</q>
	 
The function is indicated by @function rather than by <gi>metamark</gi> itself, right? 
Suggested revision: 

<desc versionDate="2013-04-16" xml:lang="en">identifies one or more elements to which the function indicated applies.</desc>

**Comment by lb42** [comment]
But the object of the function is indicated by the metamark. Changed to ”to which the metamark applies”
