### ISSUE TITLE
description of metamark in PH-meta

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1384]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2069

<q>
Unlike marginal notes or other additions to the text, metamarks are used by the writer to indicate a deliberate alteration of the writing itself,
</q>

A couple of things about this sentence are problematic, I think. "Marginal notes" are very frequently not "additions to the text." Also, the phrase "deliberate alteration of the writing itself" doesn't really get at the distinction between additions and meta-writing; compared to meta-writing, additions are no less deliberate, probably more "alterations," and have just as much to do with "the writing itself." 

Suggested revision: Unlike textual additions or marginal notes intended to be read as part of the text, metamarks are used by the writer to indicate <emph>how</emph> the text is to be read.

**Comment by lb42** [comment]
Revised wording as suggested
