### ISSUE TITLE
Small tweaks to a sentence in PH-meta

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1385]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2090

<q>
The following example is taken from an 15th century legal book from the city of Göttingen, containing regulations of everyday life issued by the city council
</q>

This sentence is missing a period and "an" should be "a."

Revision:
The following example is taken from a 15th century legal book from the city of Göttingen, containing regulations of everyday life issued by the city council.

**Comment by lb42** [comment]
Fixed
