### ISSUE TITLE
One further correction to the sentence discussed in ticket #1370

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1386]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2128

<q>
In this example, the whole of what was originally the 14th section of the poem . . . .
</q>

This wasn't the 14th (or any other named) section of the poem, so I suggest:
In this example, a block of seven lines . . . .

**Comment by lb42** [comment]
No idea where we would have got this idea, if not from you, but fixed as you suggest,
