### ISSUE TITLE
The address given for Brasserie Georges in the guidelines is wrong

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1387]
The address given in the guidelines for brasserie Georges is wrong see attached image from their menu. 

![20151031_194815](https://cloud.githubusercontent.com/assets/296651/10866466/b3b03a52-802f-11e5-87a6-68e9274a5c7a.jpg)

**Comment by lb42** [comment]
You're quite right. Blame Mr Google's inaccurate Street Map. Or my misreading of it. I leave you the pleasure of correcting the location.xml

**Comment by jamescummings** [comment]
Checked in ND and corrected in location.xml in ca3318e, added a modified version using postCode and street as an example address example in cafff85. 

Closing issue.
