### ISSUE TITLE
fragmentary sentence in PH-PrimarySources/#undo

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1388]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2289

<q>
using two <gi>undo</gi> elements, each with a <att>spanTo</att> attribute,
               to delimit the two parts of the deletion which were reverted at change s3.
</q>

The beginning of this sentence seems to have gone missing.

**Comment by lb42** [comment]
The beginning of the sentence precedes the example. Reworded.
