### ISSUE TITLE
Oddities in description of <transposition> in PH-PrimarySources/#transpo

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1389]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2312

<q>
A <term>transposition</term> occurs when metamarks are found in a document indicating
               that passages should be moved to a different position. Typically this may be done
               using arrows, asterisks or numbers, or other means. By definition the result of a
               transposition is not present in the document, and should not therefore be encoded, if
               the intention is to represent the actual appearance of the document. Instead, the
               following elements may be used to indicate the intended reordering:
</q>

This passage is awkward and misleading in several ways. The first sentence approaches transposition as an event that "occurs" when found rather than as a textual phenomenon. The third sentence's assertion that "the result of a transcription . . . should not . . . be encoded" confuses transcription and encoding. As the next sentence explains, one of the main purposes of the elements <gi>transpose</gi> and <gi>listTranspose</gi> is to allow one to encode "the intended reordering." 

Suggested revision:

Documents sometimes contain a metamark or metamarks indicating that a passage should be moved to a different position in the textual flow. Such <term>transpositions</term> may use arrows, asterisks or numbers, or other means. If the encoder's intention is to represent the actual appearance of the document, the following elements may be used to indicate the intended reordering:

**Comment by lb42** [comment]
I agree that the passage needs improvement, but  I am reluctant to lose the original sentence "By definition... document" since without it it's not clear why transposition is such a peculiar phenomenon.

**Comment by raffazizzi** [comment]
What about:

Documents sometimes contain a metamark or metamarks indicating that a passage should be moved to a different position in the textual flow. Such transpositions are often indicated with arrows, asterisks or numbers, or other means. By definition the result of a transposition is not present in the document. Therefore, when the encoder's intention is to represent the actual appearance of the document, the result **should not be placed in the intended textual flow**. Instead, the following elements may be used to indicate the intended reordering:

(text in bold not to be included in the guidelines)

**Comment by lb42** [comment]
I substituted "in the encoding" for "in the intended textual flow" but otherwise this rewording seems fine.
