### ISSUE TITLE
Heading of PH-changes

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1391]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2798

~~~~~
<q>
<head>Changes</head>
</q>
~~~~~

This heading seems excessively broad, as many of the other parts of this chapter (and, indeed, parts of other chapters) deal with various sorts of changes. Suggested revision: 

<head>Groups of Changes</head>

**Comment by lb42** [comment]
Or "Identified Changes" maybe?

**Comment by raffazizzi** [comment]
A longer title may be clearer, perhaps? "Identifying sets of authorial changes". (Struggling to avoid the word "stages" here...)

**Comment by lb42** [comment]
"Identifying changes" seems good enough to me

**Comment by emylonas** [comment]
I'd like to change this the "Identifying Changes and Revisions" The word revision is used right away in the descriptive paragraphs and incorporates the meaning of "authorial changes" as well. Will do later today unless I hear otherwise.

**Comment by emylonas** [comment]
implemented with text "Identifying Charges and Revisions" at ebec981
