### ISSUE TITLE
One more wording tweak in PH-changes

### ISSUE THREAD

**Issue by brettttt** [TEIC/TEI#1394]
At https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2892

<q>
. . . allow each stage to be dated as exactly or inexactly as necessary, in the same way as is
         currently possible for the TEI <gi>date</gi> element.
</q>

The word "currently" is weird and superfluous. Suggested revision:

. . . allow each stage to be dated as exactly or inexactly as necessary, in the same way as is
         possible for the TEI <gi>date</gi> element.

**Comment by lb42** [comment]
Fixed
