### ISSUE TITLE
desc - Element

### ISSUE THREAD

**Issue by mariecurie** [TEIC/TEI#1396]
Hello,

Why is it not possible to use an s-tag in a desc-tag?

An example: 

&lt;div&gt;
&lt;head&gt;my header&lt;/head&gt;
&lt;desc&gt;&lt;s&gt;description of folowing text&lt;/s&gt;&lt;/desc&gt;
&lt;p&gt;main text&lt;/p&gt;
&lt;/div&gt;

best wishes, and thanks in advance for your reply,
Alexandra

**Comment by bansp** [comment]
Hi Alexandra. 
This doesn't seem to be a typical use case -- please tell us what you would hope to achieve with this structure. This is not supposed to be an example of corpus encoding, is it?
Thanks and best,
  Piotr

**Comment by mariecurie** [comment]
Hi Piotr,

thank you for your quick response.

We are using TEI for medival latin texts. Maybe it works better with a small example:

&lt;div&gt;
  &lt;head type="h2"&gt;CAP. V.&lt;/head&gt;
&lt;p&gt;Constitutiones decretorum singularibus sunt opinionibus praeferendae.&lt;/p&gt;
&lt;div&gt;
&lt;head type="h3"&gt;Hieronymus in Parabolas.&lt;/head&gt;
&lt;p&gt;
“Ne innitaris prudentiae tuae.” Prudentiae suae inititur, qui ea, quae sibi agenda vel dicenda videntur, Patrum decretis praeponit.
&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;

The first p-Elemente is a kind of description of the following div-Element. Is there any way to encode this p-Element as description? We can not use the type-attribute of p-Element. 

Thanks & best wisches,
Alexandra

**Comment by bansp** [comment]
Dear Alexandra, 
I believe that there are many options open here for you, maybe even the second use of the &lt;head> element with a different @type, but I would suggest to take this question to the TEI-L list -- it is much easier to get help there than here, from a whole range of people who have faced similar issues and can point you to many examples.
Cheers,
  Piotr

**Comment by ebeshero** [comment]
Dear Alexandra, 
I've been following this thread with some interest, as I am working on a similar project. Would you consider using the TEI element <argument> to hold your descriptive passage? That's what we're using for something similar--a short summary of content to follow in a chapter. Here's the explanation of <argument> in the Guidelines:

 http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-argument.html

Hope this helps!
Elisa Beshero-Bondar

**Comment by mariecurie** [comment]
Hi Elisa,

thank you for response. This seems to be the perfect match.


Cheers,
Alexandra
