### ISSUE TITLE
@extent on <pron> and  <orth> a) should be a class, and b) should not have defaultVal

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1397]
a) `@extent` is independently specified on `<pron>` and `<orth>`; they are identical and should be a class.

b) The values for `@extent` (full, pref, suff, part) may not suitable for all language and dictionary types, and therefore the defaultVal of "full" is inappropriate; if there should be a defaultVal, it should be something like "unspecified", but that's the same as having no defaultVal, so we contend that the prose should assert that the default assumption is unspecified, and that there should be no defaultVal.

**Comment by sydb** [comment]
I submit that assertion in (b) holds even if the suggested value list *were* appropriate for all languages and dictionary types.

**Comment by martindholmes** [comment]
This is a sort of test case for the ticket which deals with defaultVals.

**Comment by hcayless** [comment]
Assigning @emylonas to look at this.

**Comment by emylonas** [comment]
Martin - your reasoning makes sense, and I think I can identify examples of dictionary types where this wouldn't make sense - but could you give an example of a language where this doesn't apply? 

There are two issues
S

1. Several people agree that if a default attribute value from an enumerated list is "undefined" then there should be no defaultVal. This seems reasonable.

1.  Martin is bringing up  `<orth>` and `<pron>` specifically and recommending that they not have a defaultVal. Examples would help.

**Comment by martindholmes** [comment]
There are lots of languages with infixes; Mandarin is often said to be lacking affixes, although I don't know enough about it to say whether that's true or not.

**Comment by bansp** [comment]
I'm not sure I understand the reasoning behind Martin's (b). Indeed, I can imagine e.g. distinctions among what would be referred to as "suff" or "pref" [1]. Infix is a difficult category, often redefined in other terms, but nevertheless some descriptive dictionaries could/should mention "infix" here. I understand that "part" tries to be a cover-all for non-"full". Still, I can't see why "full" shouldn't be the default, if that saves you using the @extent attribute in, I would imagine, most cases (_a tergo_ indexes are special, root-based dictionaries are specialist, and when you have a mixed one, in most cases you would want to have a distiction between full and non-full, by marking the non-full forms with @extent, and leaving the full ones be. I'm not really sure why this would be considered bad or wrong(?)

[1] 'internal'/'external', with various definitions; 'derivational' vs. 'inflectional', etc. Similarly with prefixes. And maybe these distinctions could be captured by @type, but maybe not always (@type could be reserved for _kinds of derivational suffixes_ as opposed to inflectional endings). But all of this means you want to have a specialized ODD, ergo the initial problem gets handled in the customization.

**Comment by emylonas** [comment]
yes, make class, 
yes, get rid of default
add infix as sample value
post this to the list

**Comment by emylonas** [comment]
Made new class att.partial, put @extent definition into it with minor wording chages. added ref to Guidelines. fixed in dfafd4b..3ab493d

**Comment by lb42** [comment]
The element orth claims membershi[p in class "att.partials" though the discussion above calls it "att.partial". But no file att.partial(s).xml is in the repo, and no class att.partial(s) has been declared.

**Comment by emylonas** [comment]
working on it

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]
