### ISSUE TITLE
att.global.analytic reference points to wrong Guidelines section

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#1398]
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.analytic.html refers to 17.3 Spans and Interpretations, but the @ana attribute isn't mentioned there. It should point to 17.2 instead.

**Comment by martindholmes** [comment]
Fixed in #59c389f..8eebc53. I've added 17.2 preceding 17.3; the former introduces the attribute but the latter provides detailed usage examples (and it does actually mention @ana).
