### ISSUE TITLE
Revise to avoid redefinition of attributes at first level

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1399]
The definition of macro.anyXML generates occasionally a clash with xml: attributes in customization. In the attached ODD specification for instance, removing xenoData from @exclude (and thus making macro.anyXML appear in the resulting schema) makes the RelaxNG (attached) invalid, with the error: 
System ID: /Users/romary/Desktop/Tempo/Tempomacro-anyXML/TBXinTEI.rnc
Main validation file: /Users/romary/Desktop/Tempo/Tempomacro-anyXML/TBXinTEI.rnc
Engine name: Jing
Severity: error
Description: conflicting ID-types for attribute "id" from namespace "http://www.w3.org/XML/1998/namespace" of element "descripGrp" from namespace "http://www.tbx.org"
Start location: 38:3

Note that you need to make sure that under preferences in Oxygen "check ID/IDREF" is on to see this.

The solution could be to have a two level definition for macro.anyXML, the first level without attribute constraint and using macro.anyXML2, this time with the attribute constraint (attribute \* { text }*)

PS: it seems I need permission to attach file to the repository. Tell me when it is possible.

**Comment by hcayless** [comment]
Hi Laurent, the Council discussed this issue extensively at our last meeting. The solution we settled on was to recommend excluding any extra namespaces from macro.anyXML. See, e.g. <https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_svg.odd#L79> (especially <https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_svg.odd#L90>). But maybe you have a better solution?

I think the problem with attachments is that GitHub only permits certain types: <https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/>. You might need to make your attachment a .txt file.

**Comment by laurentromary** [comment]
There is a good analysis in http://blog.jclark.com/2009/01/relax-ng-and-xmlid.html

**Comment by sydb** [comment]
Laurent — 
Glad you mentioned James Clark’s thoughts on this issue. I think given that it has been almost exactly 6 years and we have not heard much more about it, it is not likely he will actually be changing jing or the _RELAX NG DTD Compatability_ spec. (But I would **love** to be wrong about that.) Therefore it is obvious (to me) that the correct solutions are either
a) turn off DTD compatability mode (and check for `@xml:id` uniqueness some other way, e.g. Schematron)
b) change the definition of `@xml:id` to `NCName` (and check for `@xml:id` uniqueness some other way, e.g. Schematron)
I have argued (pretty strongly) for (a) in the past (see, e.g. [this post](http://lists.lists.tei-c.org/pipermail/tei-council/2015/022060.html), and in particular follow note [5](http://wiki.tei-c.org/index.php/Xmlid_uniqueness.sch) to see how easy it is to check `@xml:id` uniqueness), pretty unsuccessfully. So I’m now leaning towards (b), but need to think it through a bit more before I commit whole-heartedly.

FWIW, I think the current TEI solution (recommend that various namespaces be excluded from the definition of macro.anyXML) is _terrible_. (Yes, it works perfectly well in certain cases; but it is hard for users to do, and it will not work the day a user wants to represent something from one of those namespaces.)

**Comment by lb42** [comment]
Well, the proposed &lt;anyXML> solution at least makes representing the least-worst solution we currently use a lot easier, and doesn't preclude us finding another better one one day.

**Comment by sydb** [comment]
Yes, @lb42 ; I haven’t wrapped my mind around it completely, but my instinct is that the proposed `<anyXML>` will not hurt, and might help.
<hr/>
For those wondering what we’re talking about, @lb42 has recommended that in PureODD the concept “any well-balanced snippet of XML can go here” that is currently represented by `<macroRef name="macro.anyXML"/>` instead be represented by a new element, i.e. `<anyXML exclude="[namespaces-that-cause-problems]"/>`

**Comment by lb42** [comment]
I think this can be closed now that we have anyElement.xml
