### ISSUE TITLE
Note on <sp> is weird

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1401]
The `<sp>` element has this:

~~~~~
  <remarks versionDate="2008-04-05" xml:lang="en">
    <p>The <att>who</att> attribute on this element may be used either in addition to the
        <gi>speaker</gi> element or as an alternative.</p>
  </remarks>
  <remarks xml:lang="fr" versionDate="2007-06-12">
    <p>L'attribut <att>who</att> peut être utilisé soit en complément de l'élément <gi>speaker</gi>,
      soit comme une alternative à cet élément.</p>
  </remarks>
  <remarks versionDate="2005-01-14" xml:lang="en">
    <p rend="dataDesc">Lines or paragraphs, stage directions, and phrase-level elements.</p>
    <p>The <att>who</att> attribute on this element may be used either in addition to the
        <gi>speaker</gi> element or as an alternative.</p>
  </remarks>
~~~~~

The 2005 `<remarks>` has an initial paragraph with `@rend="dataDesc"`; that presumably had some significance at some point, but now it comes out simply as a note, and it makes no sense in the spec page. The second part of that `<remarks>` reiterates what's in the 2008 one. Recommend deleting the 2005 one completely.

**Comment by lb42** [comment]
As you surmise this is a surviving data Desc which should simple have been deleted.

**Comment by lb42** [comment]
Removed redundant &lt;remarks> elements at commit a20732437a087ee2e51df63b8edd8106e3063ac7
