### ISSUE TITLE
<sp> should allow multiple <speaker> elements

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1402]
As it stands, the `<speaker>` element may only occur at the beginning of `<sp>`. However, a speech is often split by a stage direction, and in that case, the original text may show a second speaker name within the same speech. An example can be seen in the 1594 quarto of Friar Bacon and Friar Bungay, as shown [here in EEBO](http://eebo.chadwyck.com/search/full_rec?EeboId=99841693&ACTION=ByID&SOURCE=pgimages.cfg&ID=99841693&FILE=..%2Fsession%2F1447182133_11244&SEARCHSCREEN=CITATIONS&VID=6291&PAGENO=11&ZOOM=100&VIEWPORT=&CENTREPOS=&RESULTCLICK=&GOTOPAGENO=11&ZOOMLIST=100&ZOOMTEXTBOX=&SEARCHCONFIG=var_spell.cfg&DISPLAY=AUTHOR).

At the bottom of the recto, a speech by Bacon is interrupted by a stage direction, but the speech is clearly continuous (the first line ends with a comma, and the subsequent line continues it). This is clearly a single speech, but it contains two `<speaker>`s. I would say that this should be encodable without ugly workarounds such as `@prev`/`@next`.

**Comment by lb42** [comment]
This seems implausible to me but I can't see the example because it's behind a paywall. Could you may be add a screenshot?

**Comment by PFSchaffner** [comment]
1. I'm thinking this (like several issues recently raised) might belong on TEI-L, rather than that subset that watches github.
2. I'm not sure I see the point of this suggestion. If the speech is indeed one speech (and I'll agree for argument's sake that it is), then simply make it one speech (one sp element). The fact that a stage direction appears within it is neither here nor there; stage directions frequently appear within speeches. There seems nothing different about this one except possibly its relative prominence. 
3. So the real question is what to do with the 'recapitulative' speaker indicator; your assumption is that its presence 'forces' a new sp element. I'd say rather that the sp element should be left intact and the otiose speaker indicator reduced to something less than speaker.  I'd be inclined either to treat it as we do a running head (i.e., mostly, omit it), or relegate it to some other sort of reduced status, whether fw or note or (probably best) label or stage. Hence:  (do I have to escape my angle brackets? let's see:)

<sp>
<speaker>Bacon.</speaker>
<l>Stand there and looke directly in the glasse,</l>
<stage>Enter Margret and Frier Bungay.</stage>
<l><stage>Bacon.</stage> What sees my lord.</l>
</sp>

Assuming, of course, that the second speaker designation is actually not a
mistake.

**Comment by PFSchaffner** [comment]
Apparently I do have to escape my angle brackets. Remind me how, please?

**Comment by PFSchaffner** [comment]
http://www-personal.umich.edu/~pfs/tcp/recap_speaker.jpg

**Comment by lb42** [comment]
Now that I have seen the example, I think I would treat it as two sp elements. Do you have other examples ?

**Comment by martindholmes** [comment]
Paul, I couldn't disagree more. The second instance of "Bacon" is identical to the first, and serving exactly the same purpose. If you feel it's acceptable to edit it out completely because you don't believe it belongs there, then your editorial principles are rather different from those of most people whose TEI project I work on. It seems even odder to posit that it's a stage direction.

It's a speaker label, and it should be tagged as one. The content model of `<sp>` arbitrarily prevents this, at the moment, meaning that you have to do nasty things like this:

~~~~~
<sp xml:id="d2e3646_1" next="d2e3646_2" who="sp:FriarBacon">
               <speaker>B<hi rendition="simple:italic">acon</hi>.</speaker>
               <l> Stand there and looke dire{ct}ly in the gla{{s}{s}}e,</l>
<lb/>
                  <stage type="entrance">
                     <hi rendition="simple:centre">E<hi rendition="simple:italic">nter Margret and Frier Bungay.</hi></hi>
                  </stage>
                  <lb/>
               </ab>
            </sp>
            <sp xml:id="d2e3646_2" prev="d2e3646_1" who="sp:FriarBacon">
               <speaker>B<hi rendition="simple:italic">acon</hi>.</speaker>
               <l> What {s}ees my lord.</l>
            </sp>
~~~~~

**Comment by martindholmes** [comment]
Paul, to escape stuff, either use a backtick before and after (if it's short), or five tildes before and after (for blocks).

**Comment by lb42** [comment]
Why can't we have two consecutive sppeches by the same e speake?especially when, as here, there is a fair bit of stage business between them?

**Comment by PFSchaffner** [comment]
Thx. I got the backtick thing, couldn't remember how many tildes for the long stuff.
I think I'd still plump for the 'recapitulative' classification (bearing in mind that speaker
designations tended to be used very loosely and inconsistently). I.e., I'd see it as very
much like recapitulative headings that serve only to remind the reader what the current
head is, whether true running heads or head-like things that serve a similar purpose (not
uncommon -- and usu tagged not as head but as label, a sort of reduced head. Hence
my suggestion to reduce the sp here.  

In practice, however, I'm sure we would have just treated it as two sp's, as Lou says.
There's no reason an sp should not continue a previous sp, and no reason it shouldn't
end in a comma for that matter. No need for linking the two bits any more than when 
a single sentence spoken by one character is interrupted by another. It's just that in
this case there is no interruption except the arrival action. So yes, I'd go with the two
sp approach and no @prev/@next.  My original response was explicitly on the assumption
that there was only one speech.

**Comment by PFSchaffner** [comment]
And indeed, it seems that we did treat it as two `<sp>`s , in encoding both the 1594 and the 1630 edition.

**Comment by martindholmes** [comment]
I haven't seen any other examples so far. But my question would be: if the TEI schema hadn't prevented you from putting in a second `<speaker>` element, would you still have encoded it as two speeches? 

I'm converting this from some old SGML encoding where the editor tagged it as a single speech with two speaker elements. That interpretation seemed reasonable to me, and it still does. There are obviously ways around it as you suggest, but I'm not sure I see the point of them other than to wriggle out of an arbitrary schema constraint.

**Comment by PFSchaffner** [comment]
`<sp>``<speaker>`old bore`</speaker>``<p>`When I was your age, you know,`</p>``</sp>`
  `<sp>``<speaker>`young git`</speaker>``<stage>`aside`</stage>``<p>`How he natters on.`</p>``</sp>`
 `<sp>``<speaker>`old bore`</speaker>``<p>`we decided not to allow speakers to float`</p>``</sp>`
  `<sp>``<speaker>`young git`</speaker>``<p>`Float? Does he even know what that means?`</p>``</sp>`
 `<sp>``<speaker>`old bore`</speaker>``<p>`about in speeches, only to head them`</p>``</sp>`
  `<sp>``<speaker>`young git`</speaker>``<p>``<stage>`contemptuously`</stage>`In P3, I'd wager.`</p>``</sp>`
 `<sp>``<speaker>`old bore`</speaker>``<p>`And that was true even in P3! So...`</p>``</sp>`
   `<stage>`Mad rush to the exit`</stage>`
 `<sp>``<speaker>`old bore`</speaker>``<p>`I see no reason to change it now.`</p>``
    `<stage>`Pulls out the green books and reads`</stage>`
    `<q>``<!ELEMENT sp            - O  (speaker?, (p | l | lg | seg | stage)+)>``</q`>`</sp>`

**Comment by ebeshero** [comment]
Dear Council,
I'm writing quickly here, but in my experience with reading, teaching, and encoding plays and radio scripts, I have seen examples of two characters speaking simultaneously, sharing a speech. The example that sticks out to me is that passage in Shaw's Pygmalion with Professor Higgins and Col. Pickering speaking excitedly over each other to Mrs. Higgins about Eliza Doolittle, such that their individual speeches are indistinguishable. I may find when I look at the play that we can distinguish their parts, but there are certainly other cases involving two characters speaking slowly together (now thinking of the two children reading their prepared letter to their father in Mary Poppins. 

Yes, there will occasionally be occasion to mark two speakers sharing a speech. I've seen it and I think we ought to have the capacity to use more than one speaker in a given sp element.

Best,
Elisa

**Comment by ebeshero** [comment]
PS How do people encode the witches' incantations in Macbeth? Shakespeare's plays will include some precedent...with a hey nonny nonny (eg shared singing parts...)

Elisa

**Comment by martindholmes** [comment]
@ebeshero , there's nothing to prevent you from putting multiple speakers in one `<speaker>` tag (with e.g. `<name>` tags to distinguish them if necessary). The issue in this example is a re-iteration of the same speaker label, with intervening content, which I think is a bit different.
@PFSchaffner , you can't seriously be labelling me "young"? :-)

**Comment by PFSchaffner** [comment]
Just to be clear: my only points in my little piece of dialogue were that Martin's SGML could not have been P3 because even there, speakers appeared only at the head of a speech; and that a single speech interrupted by an entrance is as reasonably tagged as two speeches as a single speech interrupted by another speaker's speech. Those were what I was trying to demonstrate.

As for the witches and Professor Higgins, I *think* this is a different use case. There are certainly overlapping speeches, and shared speeches with what you might call a corporate or composite speaker (just because two people are speaking doesn't mean more than one `<speaker>`).  Overlapping and shared speeches are quite common, for example, in songs and especially in musical drama, like this:

http://www-personal.umich.edu/~pfs/tcp/playford.pdf

How they are tagged will depend on how they are printed: I think one should bear in mind that the drama tags are not primarily a way to capture performance instructions but a way to capture that style of print formatting called 'drama.' 

And sorry Martin, I would never ever think of you as 'git'. Young, eternally so, of course. It does cast a new light on the meaning of 'git hub' however.

**Comment by PFSchaffner** [comment]
More abstractly, `<speaker>` currently might be thought of as a kind of speech-`<head>`; turning it into a floating instruction makes it more like a kind of specialized `<stage>`. In fact, when interwoven speeches are particularly complicated with lots of (Jill joins in ...) and so one, I think we occasionally treat all the speaker designations as `<stage>`. or `<stage type="speaker">`.

**Comment by PFSchaffner** [comment]
The witches BTW are quite easy, I think, as usually formatted. The speakers
are "1 WITCH" "2 WITCH" etc. and "ALL" or "CHORUS." 

  1 WITCH.  Thrice the brinded cat hath mew'd.
       2 WITCH.  Thrice and once, the hedge-pig whin'd.
       3 WITCH.  Harpier cries:—'tis time! 'tis time!
       1 WITCH.  Round about the caldron go;
    In the poison'd entrails throw.—
    Toad, that under cold stone,
    Days and nights has thirty-one;
    Swelter'd venom sleeping got,
    Boil thou first i' the charmed pot!
       ALL.  Double, double toil and trouble;
    Fire burn, and caldron bubble.
       2 WITCH.  Fillet of a fenny snake,
    In the caldron boil and bake;
    Eye of newt, and toe of frog,
    Wool of bat, and tongue of dog,
    Adder's fork, and blind-worm's sting,
    Lizard's leg, and owlet's wing,—
    For a charm of powerful trouble,
    Like a hell-broth boil and bubble.
       ALL.  Double, double toil and trouble;
    Fire burn, and caldron bubble.

**Comment by martindholmes** [comment]
Indeed, my SGML is definitely not P3. In fact it's not actually well-formed SGML, but it can be bullied into being so, and thence to some-sort-of-XML, and thence to TEI. It's legacy data with some value, but in a rather unlovable format.

**Comment by jamescummings** [comment]
Just to chime in:
- As we know `<speaker>` gives "contains a specialized form of heading or label, giving the name of one or more speakers in a dramatic text or fragment".  So to answer @ebeshero I'd say to put both speakers in one speaker element.  The real power comes from having two URI-pointing values in the `@who` attribute on the sp.
- In Martin's original case I'd certainly mark this up as two speeches. I see no problem with having multiple speeches by the same character one after another, if there is a reason for them to be considered separate speeches. (For example, entrance of a new character.)  
- I'd also encode the stage direction separate, in between the two speeches.

So far I don't think I've seen an example which suggests that we should allow multiple speaker elements inside an sp, but I'm open to persuasion.

**Comment by hcayless** [comment]
The thing that worries me about making it two speeches is the comma after "glasse," which signals to me that the speech is not over (or even interrupted), just that this is the cue for the two other characters to come in. There's no pause, so it's not a new speech. The second *Bacon.* is there to show that there's no change in speaker. Assigning to @ebeshero to push this forward, maybe raising it on the TEI-List.

**Comment by ebeshero** [comment]
F2F subgroup thinks we shouldn't have to change the content model of `<sp>`, but I will call for examples and discussion on the TEI list.

**Comment by sydb** [comment]
While Council has differing views on whether or not this can or should be considered two separate speeches, none of us believes that the proper solution is to allow `<speaker>` to float inside `<sp>`.

**Comment by gerritbruening** [comment]
I think that I can serve with an example where the `<speaker>` element should float inside `<sp>`:
http://beta.faustedition.net/print/faust2.3#l5150
the “Rosenknospen” (rosebuds) being the speaker of a speech that begins with line 5144 (entitled “Ausforderung”, challenge). My favourite encoding would be:

    <sp>
        <head n="before_5144">Ausforderung.</head>
        <lg>
            <l n="5144">Mögen bunte Phantasien</l>
            <l n="5145">Für des Tages Mode blühen,</l>
            <l n="5146">Wunderseltsam seyn gestaltet</l>
            <l n="5147">Wie Natur sich nie entfaltet;</l>
            <l n="5148">Grüne Stiele, goldne Glocken</l>
            <l n="5149">Blickt hervor aus reichen Locken! –</l>
            <l n="5150" part="I">Doch wir</l>
            <speaker n="before_5150f">Rosenknospen.</speaker>
            <l n="5150" part="F">halten uns versteckt,</l>
            <l n="5151">Glücklich wer uns frisch entdeckt!</l>
        </lg>
        <lg>
            <l n="5152">Wenn der Sommer sich entzündet</l>
            <l n="5153">Rosenknospe sich verkündet,</l>
            <l n="5154">Wer mag solches Glück entbehren?</l>
            <l n="5155">Das Versprechen, das Gewähren!</l>
            <l n="5156">Das beherrscht, in Florens Reich,</l>
            <l n="5157">Blick und Sinn und Herz zugleich.</l>
        </lg>
    </sp>
