### ISSUE TITLE
Note on <egXML> incorrect

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1409]
The `<remarks>` in the spec file for `<egXML>` says “The content must however be a well-formed XML fragment or document”. But this is not, in fact, the case. The content need not be well-formed, a well-balanced XML fragment is sufficient.
The reason this is a ticket and not just a corrigible typo fix is that the concept of a well-balanced is not discussed in the Gentle Introduction, so it’s not clear whether or not we should use that jargon here. And if we don’t use that jargon, how do we describe it?

**Comment by PFSchaffner** [comment]
Perhaps by paraphrasing what Michael Kay said when inventing it? 
Viz.,

"The XPath tree model can represent every well-formed XML document, 
but it can also represent structures that are not well-formed according
to the XML definition. Specifically, in well-formed XML,
there must be a single outermost element containing all the 
other elements and text nodes. This element ... cannot be
preceded or followed by other elements or text nodes.  The
XPath tree model does not enforce this constraint--the document
node can have any children than an element might have, including
having no children at all. THis corresponds to the XML rules
for the content of an external general parsed entity, which
is <b>a free-standing fragment of XML that can be incorporated into
a well-formed document by means of an entity reference.</b> I
shall sometimes use the term "well balanced" to refer to such
an entity. This term is not in the XPath specification; rather I
have borrowed it from the rarely mentioned XML fragment 
exchange proposal (http://www.w3.org/TR/xml-fragment-html). <b>The
essential feature of a well-balanced XML fragment is that every element
start tag is balanced by a corresponding element end tag.</b>
Following is an example of an XML fragment that is well
balanced but not well formed, as there is no enclosing
element:

The `<noun>`cat`</noun>` `<verb>`sat`</verb>` on the `<noun>`mat`</noun>.`

https://goo.gl/76p0iC

**Comment by lb42** [comment]
So far as onvdl is concerned, the &lt;teix:egXML> element is the root element, so I am not convinced that it's actually wrong to say that a case like &lt;egXML> stuff &lt;foo/> more stuff &lt;/egXML> is  well formed, though I agree the current text could perhaps be clarified. But I don't think we need to introduce the rather recondite concept of "well balanced" to do that.

**Comment by lb42** [comment]
Modified desc accordingly
