### ISSUE TITLE
Simplify exclusion of one or more elements from a complex content model

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1412]
We occasionally want to exclude a specific element or group of elements from a content model, despite the fact that their class memberships would otherwise allow it there. A classic case is &lt;s> which cannot be permitted within &lt;s> , even though it contains model.segLike elements (of which &lt;s> is one). Another case is &lt;egXML>, which cannot contain &lt;egXML>. 

In a DTD this would be handled by an exclusion exception. In RELAXNG there is no obvious way that I am aware of. Instead we have to implement the constraint as an additional schematron rule.

This proposal is to make this more explicit by adding an attribute @exclude to the element &lt;content> in pure ODD. So (simplifying somewhat) the content model for &lt;s> might look like this
~~~~
<content exclude="s">
  <classRef key="model.segLike" maxOccurs="unlimited"/>
</content>
~~~~

**Comment by hcayless** [comment]
Is this better/different than using `@except` on the classRef? DTD exclusions went away with SGML, I believe, so we're left with no way but schematron anyhow. I don't believe `@except` *does* anything at the moment, stylesheets-wise, but it could generate a schematron rule.

**Comment by lb42** [comment]
You're right: there's no need for this on &lt;content, assuming that @except on a classRef works. Leaving this open to remind us to check!

**Comment by hcayless** [comment]
As a followup, what is `@include` on a `<classRef>` meant to do? Does it mean "Put back an element that's been excluded from an imported module, in this particular content model?" The documentation doesn't really make it clear. I think both attribute defs were copied over from `<moduleRef>`, but they must mean something a bit different on a `<classRef>`, no?

**Comment by lb42** [comment]
No, it ought to mean the same as on moduleRef, i.e. if the members of the class are x, y, z, @include="x y" ought to mean the same as @except="z"

**Comment by hcayless** [comment]
Ah, ok, but they're not excluded from the *schema*, only from the given content model, so I find the language a little confusing. I think we definitely need a Stylesheets ticket for implementing this. I'll go ahead and file one.

**Comment by lb42** [comment]
Putting this together with @expand, things get quite complicated! Supposing a class with members x y and z....

@except| @include| @except| result
----------  |------------|------------|--------
alternate    |  -  |              -|           `x|y|z`
alternate   |x y |          -|           `x|y`
alternate    | -            |    z    |       `x|y`
sequence   |-            |     -     |      x,y,z
sequence   |x z        |     -       |     x,z
sequence  | -          |     x z      |    ERROR (cant have a sequence of one component)

There probably should be a schematron rule to say you cannot supply both @include and @except.

**Comment by hcayless** [comment]
For that matter, I'm not confident that `@expand` is implemented either...

/me cries

**Comment by lb42** [comment]
Actually, after checking, it seems that this all works more or less as it should. So closing this.
