### ISSUE TITLE
ogrophy elements should be in att.canonical

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1414]
It is simple hubris for us to presume that any given project's TEI contextual information is the be-all and end-all of data about the places with information is stored therein. An entry in a placeography, personography, bibliography, or whatever should be able to refer (using `@ref` or `@key`) to some other data structure that has further information about the same entity.

I may well want to refer to a gazeteer elsewhere in addition to storing local information about the places in my corpus. At the moment, the only intelligent way I can do that (presuming I have structured data, not a sequence of paragraphs — why can't I have both?) is to develop some local convention like using `@ref` of a `<placeName>` child of `<place>`, or to put something like a `<ptr>` in a `<note>`. (Why can I have a `<link>` in a `<place>`, but not a `<ptr>`?)

Imagine a project that wants to keep track of the people mentioned in a set of mid-20th century American texts. The project wants to do two things with each contributing author’s name: a) to disambiguate it, so the reader can know exactly who is being referred to, and b) to annotate it with his rank within the Salvation Army, or her status as a practitioner of rheumatology (e.g. in med school, in residency, in fellowship, member of the American college of Rheumatology, faculty of the American college of Rheumatology) or whatever.

So, the project wants a TEI personography where each entry `<person>` has both a)  a reference to the persons entry in the Library of Congress name authority file, and b) their rank or status or whatever. My point is we provide no consistent way to do (a), and we should. I think the best way to do this is by allowing `@ref` (and `@key` for the web-impaired) on `<person>` and `<place>` (and I suppose `<org>`, `<bibl>`, and `<biblStruct>`, too).

**Comment by duncdrum** [comment]
+1 linking personographies to external authorities isn't as elegant as it could be. What would be the best way then of dealing with multiple external authorities?

**Comment by jamescummings** [comment]
I would have used the corresponding attribute on place or person and private uri schemes. corresp="loc:abc123 status:foo24"

Or something.

**Comment by bansp** [comment]
But then, James, you'd need a schema/grammar for link sequences, especially if you have more than one private URI of the same scheme there. Tricky tricky.

**Comment by jamescummings** [comment]
@bansp You mean if I have corresp="loc:abc123 loc:bcd234 loc:xyz789" then in addition to my listPrefixDef with a prefixDef for 'loc' I'd need some machine-processable way to say what it means when there are multiple values like this? (Are they all applicable, alternates, etc?)  Is that what you mean?

In practice I have no objection to having <ptr/> directly inside person/place/org just saying what I'd do now. Currently, I'd use corresp and point using private URIs and not worry about link sequences or multiple values because my needs and uses are not so sophisticated other than to say "here is some information that corresponds to this in some way".  But I'm careless and slapdash like that.

**Comment by duncdrum** [comment]
I just realised that ````@ref```` can hold multiple URIs separated by white-space. I think that @sydb is spot on. Having to go Jame's route struck me as very "tricky" in my last project dealing with 7000 Chinese person records, and no single external authority to match them all.

**Comment by StefanDumont** [comment]
We're using `<idno type="uri">http://lccn.loc.gov/n80051862</uri>` as a child of (structured) `<place>`, `<person>` etc. For us it is useful and clear enough, but @sydb idea is in fact a little shorter.

**Comment by lb42** [comment]
I was about to suggest doing exactly what Stefan suggests above. This seems to me to have several advantages: firstly and most obviously it allows you to represent multiple links in a more precise and scaleable way than does simply providing multiple URI values for a single attribute. It doesn't seem to be tag abuse: the reason you are supplying this URI is precisely because it is another way of identifying the object concerned.

**Comment by sydb** [comment]
Council sub-group thinks conceptually the requirement for a single TEI Guidelines endorsed mechanism for this purpose is a "Go" (no longer "needs discussion"). The details of implementation do require discussion. We lean towards permitting <idno> as a direct (probably 1st) child of <person>, <place>, etc. just for this purpose. In which case this issue should get folded into the “rationalize content models of ography elements” issue.

**Comment by ebeshero** [comment]
See https://github.com/TEIC/TEI/issues/1442

**Comment by sydb** [comment]
Add `<idno>` to content of `<event>` and `<nym>`, then add prose to 13.3.1 (or thereabouts) describing the use of <idno> for this purpose.

**Comment by sydb** [comment]
Council sub-group also notes that the issue of “where can `<relation>` and `<lisRelation>` go should be wrapped into this thorny problem of the content models of ogrophies. (See #567.)

**Comment by tuurma** [comment]
To summarize the discussion: short-term solution is to add `<idno>` as a first child for ogrophy elements, which should not cause problems in future rationalizations of their content models.

**Comment by tuurma** [comment]
As things stand atm `person`, `place`, `org` and `bibl` all allow for `idno`. Missing from `event` and `nym`

**Comment by jamescummings** [comment]
event will get idno as a result of #1756

**Comment by martinascholger** [comment]
@tuurma can we close this? You added idno to event and nym on May 7 (see reference in #1440)

**Comment by tuurma** [comment]
I think we can close it, unless we think a passage about this use of `idno` should be added into GL? E.g. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERS
