### ISSUE TITLE
<valItem> should allow <remarks>, too

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1420]
It may be useful at a project level to provide significant prose description of the value of an attribute. Seems to me the TEI way to do this would be to permit `<remarks>` as an optional child of `<valItem>`.

**Comment by lb42** [comment]
Can you provide an example of "significant prose description" which wont fit within &lt;gloss> or &lt;desc> (both of which are of course already available) ?

**Comment by martinascholger** [comment]
Since `<remarks>` is allowed as child of `<elementSpec>`, `<attDef>`, etc. wouldn't it be consistent to permit `<remarks>` as an optional child of `<valItem>` as well? 

Although I'm not sure, if there is really the need to allow `<desc>`, `<gloss>` AND `<remarks>` on this level. Syd, do you have a use case where a series of `<remarks>` wasn't enough to describe the values within `<attDef>`?

**Comment by emylonas** [comment]
prod Syd for examples.

**Comment by martinascholger** [comment]
Council decided to leave the issue as it is.

**Comment by sydb** [comment]
Green for Syd (or anyone else) to "go" come up with a real world example

**Comment by ebeshero** [comment]
Suggestion by Council discussion: `<remarks>` should not be permitted interchangeably with `<desc>`, but should only be permitted where `<desc>` is present.

**Comment by sydb** [comment]
@lb points out concern that folks would use `<remarks>` where they should be using `<desc>`. This is a valid concern, IMHO, and should be addressed by not allowing `<remarks>` unless `<desc>` is present.

**Comment by martinascholger** [comment]
I think the consensus is to allow `<remarks>` within `<valItem>`, but `<remarks>` should only be allowed if `<desc>` is present as well.

We still need an example for this. I thought of something like this, any other ideas?
 
```
<valItem ident="simple:doublestrikethrough">
   <desc versionDate="2017-06-18" xml:lang="en">strikethrough with double line</desc>
   <remarks versionDate="2017-06-18" xml:lang="en">
      <p>this value is derived from TEI Simple <ref target="http://www.tei-c.org/release/xml/tei/custom/odd/tei_simplePrint.odd"></ref>
      </p>
   </remarks>
</valItem>
```

**Comment by sydb** [comment]
Spurred on by @martinascholger , I have an example:
~~~~~xml
        <valList type="closed">
          <valItem ident="border">
            <desc>used to signify that there is border around a page.</desc>
          </valItem>
          <valItem ident="border-rule">
            <desc>used to signify that there is a border made of ruled lines.</desc>
          </valItem>
          <valItem ident="border-ornamental">
            <desc>used to signify that there is an ornamental border.</desc>
          </valItem>
          <valItem ident="catch">
            <gloss>catchword</gloss>
            <desc>for catch words.</desc>
          </valItem>
          <valItem ident="lineNum">
            <gloss>line number</gloss>
            <desc>for printed line numbers (usually in poetry)</desc>
          </valItem>
          <valItem ident="listHead">
            <gloss>list heading</gloss>
            <desc>for headings of lists or similar constructs; often used in tables of contents for the <q>page</q> heading.</desc>
          </valItem>
          <valItem ident="pageNum">
            <gloss>page number</gloss>
            <desc>for page numbers.</desc>
          </valItem>
          <valItem ident="pressFig">
            <gloss>press figure</gloss>
            <desc>for press figures. These are usually numbers, but are not sequential or regularly printed like signatures.</desc>
          </valItem>
          <valItem ident="sig">
            <gloss>signature</gloss>
            <desc>for printed signatures.</desc>
          </valItem>
          <valItem ident="unknown">
            <desc>for a metawork whose function you do not know.</desc>
          </valItem>
          <valItem ident="vol">
            <gloss>volume number</gloss>
            <desc>for printed volume numbers.</desc>
          </valItem>
          <valItem ident="other">
            <desc>anything not covered by the above values.</desc>
            <remarks>
              <p>Used for an ornament, decorated tool line, or symbol(s)
                that is not officially a delimiter (and thus there is
                no element on which to put <val>pre()</val> or
                <val>post()</val>) but is used to fill space at the
                bottom of a page so that a <gi>floatingText</gi> or
                similar can start at the top of the next.</p>
            </remarks>
          </valItem>
        </valList>
~~~~~

**Comment by martinascholger** [comment]
We agreed that `<remarks>` should only be allowed within `<valItem>` if <desc> is present as well.
I'd suggest adding @sydb's example to the `<valItem>` specs with the following note: "The element `<valItem>` can only contain `<remarks>` if the `<desc>` element is also present."

**Comment by sydb** [comment]
Content model (but nothing else: no prose, examples, or remarks) committed at a320093.
