### ISSUE TITLE
listChange should be repeatable inside revisionDesc

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1423]
It occurs to me that it might be useful to allow `<listChange>` to be repeatable inside `<revisionDesc>`. My reason for suggesting this is the use-case of collaborative editing where different aspects of the TEI file are being revised by different parties.  e.g. One person is proofreading the transcription of the text simultaneously to the person who is doing the encoding further up the document. While it may be true that in most collaborative editing systems technically one person completes their revisions and then the next person saves theirs, this isn't necessarily the case. Moreover, it would be useful to be able to group these by different aspects (here are all the changes to do with the proofreading, here are the ones to do with the encoding, here are the ones to do with copy-editing, etc.)  If this was made repeatable inside revisionDesc then it should also become a member of att.typed to enable this form of classification.

**Comment by martindholmes** [comment]
Since `<listChange>` can be nested, wouldn't it be easier for people to do:

~~~~~
<listChange>
  <listChange resp="#fred">
    [...]
  </listChange>
  <listChange resp="#ada">
    [...]
  </listChange>
</listChange>
~~~~~

**Comment by jamescummings** [comment]
That is a possibility, I'm just not sure what nested listChange elements really mean. But also there where you have `@resp` one really needs `@type`.  So at least the request of membership in att.typed.

**Comment by lb42** [comment]
I think Martin's suggestion is a good one and I don't see why @resp implies @type.

**Comment by lb42** [comment]
Added to att.typed since the nesting permits repetition and therefore multiple resps.
