### ISSUE TITLE
Allow <bibl> in <witDetail>

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1425]
The content model of `<witDetail>`, which is supposed to be a special kind of `<note>` is `macro.phraseSeq` (= ( text | model.gLike | model.phrase | model.global )*), meaning you can't have bibliographic citations inside a `<witDetail>`. This seems a strange omission. 

`<note>` gets `<bibl>` via [model.inter](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.inter.html), which includes other stuff we might not want in `<witDetail>`, but adding at least [model.biblLike](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.biblLike.html) to its content model would be a good idea.

**Comment by lb42** [comment]
Long term it seems to me we should apply Occam's razor, and move to deprecating &lt;witDetail> in favour of &lt;note>. In the short term, sure why not add the kitchen sink here.

**Comment by raffazizzi** [comment]
I second this - recently came across the same problem

**Comment by hcayless** [comment]
Sounds like we have agreement then. Assigning to Magdalena to implement.
