### ISSUE TITLE
Space needed in rendering of gloss in spec pages

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1426]
The rendering of @type values here:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-fw.html

appears like this:

Sample values include: 1] header; 2] footer; 3] pageNum(page number) ; 4] lineNum(line number) ; 5] sig(signature) ; 6] catch(catchword) 

There should be a space between the ident/value and the gloss content in parentheses.

Not sure if this belongs in Stylesheets or here.

**Comment by lb42** [comment]
Still present in 2.9.1. Belongs in Stylesheets, but I don't know how to move an issue to another repo.

**Comment by martindholmes** [comment]
Moved it to:

https://github.com/TEIC/Stylesheets/issues/137
