### ISSUE TITLE
Allow <hi> within <locus>

### ISSUE THREAD

**Issue by adunning** [TEIC/TEI#1429]
There is a practice of writing recto/verso folio indicators with a superscript in combination with Roman numerals, since 'fol. iv<sup>v</sup>' is clearer than 'fol. ivv'. This is blocked in TEI by disallowing `<hi>` within `<locus>`.

**Comment by lb42** [comment]
You could  represent your superscripts with &lt;g> elements which would surely be semantically more appropriate?  And would allow you to represent other funny glyphs appearing within folio indicators.

**Comment by adunning** [comment]
Fortunately there are ʳ and ᵛ characters in Unicode already, so `<g>` isn't even necessary. I would consider this a presentational thing, but it *does* occur to me that folio references also need to be able to fit in attributes, so that's an argument against allowing it.
