### ISSUE TITLE
¶ 16.2.4.7 string-range(): example typos in  `<lb n="3">`

### ISSUE THREAD

**Issue by indvstry** [TEIC/TEI#1432]
[16.2.4.7 string-range()](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSSRl) examples:

`@n=4` should be `@n=3` in the second and third examples

Example 2: `#string-range(//lb[@n='4'],7,8)` indicates the sequence ‘in mente’.
should be
Example 2: `#string-range(//lb[@n='3'],7,8)` indicates the sequence ‘in mente’.

Example 3: `#string-range(//lb[@n='4'],7,3,15,6)`
should be
Example 3: `#string-range(//lb[@n='3'],7,3,15,6)`

**Comment by hcayless** [comment]
Thanks for pointing that out!
