### ISSUE TITLE
Encoding the various possible readings of an unclear word

### ISSUE THREAD

**Issue by MarjorieBurghart** [TEIC/TEI#1434]
Description of the issue: when an unclear word appears in a written document, the editor may need to supply this word. In some cases there might be different possibilities, some of which might be offered by different editors or transcribers. Currently, we lack a mechanism that would let us offer several alternative possibilities, we can only have something like: 
`<unclear><supplied>unitas</supplied></unclear`

Suggestion: let the 'choice' element contain multiple 'supplied' elements; used like this, choice would mean that the transcribers have thought of those various alternative possible readings for the unclear word. The advantage is that, thanks to the `@resp` it's possible to attache each supplied reading to a different editor if necessary, and thanks to the `@cert` it's possible to order the suggestions by certainty. 

```
                <unclear>
                   <choice>
                      <supplied>unitas</supplied>
                      <supplied>uincas</supplied>
                   </choice>
                </unclear>
```

**Comment by raffazizzi** [comment]
What about:

```xml
<choice>
   <orig><unclear extent="6" unit="chars"/></orig>
   <reg>unitas</reg>
   <reg>unicas</reg>
</choice>
```

`reg` has useful `@cert` and `@confidence`, and could even contain `supplied` if you'd rather use that.

**Comment by MarjorieBurghart** [comment]
OK, it would certainly work, but isn't it a distorsion of the meaning of "reg", which is supposed to "contain a reading which has been regularized or normalized in some sense"?

**Comment by raffazizzi** [comment]
You're right I would be a stretch. It may be done with `<alt mode="excl" target="#sup1 #sup2"/>` for the time being. Need to look more into whether it'd be possible to bundle `unclear` and `supplied` within `choice` like other choice pairs.

**Comment by tuurma** [comment]
Dunno, wouldn't just nesting `<app>` inside `<unclear>` do the trick?
```
<unclear extent="6" unit="chars">
<app>
   <rdg cert="high" resp="MB">unitas</rdg>
   <rdg cert="low" resp="MT">unicas</rdg>
</app>
</unclear>
```

**Comment by MarjorieBurghart** [comment]
@tuurma, nah, that would be too much of a distortion of app and rdg

**Comment by hcayless** [comment]
It's not really a distortion of app is it? You'd be happy with it if one of
the suggestions came from a previous editor I think.

**Comment by tuurma** [comment]
I was thinking along the lines: if it was abbreviation with two possible solutions, app/rdg would be perfectly acceptable. It's not much of a stretch to treat deciphering of unclear text as 'readings', is it?

**Comment by jsbien** [comment]
Two real life examples:

**Comment by tuurma** [comment]
@jsbien looks like examples didn't make it, care to amend your comment?

**Comment by jsbien** [comment]
Sorry for splitting my comment, no experience with github.

![parkosz0010_2r-1fragment](https://cloud.githubusercontent.com/assets/8024702/13009776/aeebd574-d19e-11e5-8625-9908742d4d8c.png)

There is a consensus that the abbreviations should be expanded as "Iesus Christus", but there is no agreement what is actually written and in what script, Latin or Greek, cf.
[https://bitbucket.org/jsbien/parkosz-traktat/wiki/Home](https://bitbucket.org/jsbien/parkosz-traktat/wiki/Home)

A second example is a 19th century Cyrillic birth certificate which contain a word which can be either весмъ or всемъ, both are correct in the context. As there no other samples of this handwriting, it's impossible to select the right one.

So how does fir the proposed solutions?

**Comment by hcayless** [comment]
Looks like Ιη͡ϲ χρ͡ϲ to me (i.e. Greek letters with maybe a lunate sigma) :-). I think in both cases I'd present the alternatives using `<app>`. Papyri.info does this with `<app type="alternative">`. See http://papyri.info/ddbdp/o.did;;84 line 2 (and the app.crit.) for an example.

**Comment by jsbien** [comment]
Thanks, I will look into it.

FYI, Transkribus ( https://transkribus.eu/) offers a pseudo-TEI 'unclear' element with the 'alternative' attribute.

**Comment by lb42** [comment]
What's "pseudo" about tei:unclear ?

**Comment by jsbien** [comment]
The Transkribus specific attribute.

**Comment by lb42** [comment]
Supplying content as an attribute value (if that's what this @alternative does) is definitely not tei conformant though ... You're stuck if the content might have eg a g element in it

**Comment by jsbien** [comment]
That's of course a dirty trick, but Transkribus handles it in a quite convenient way. I'm going to use it for the time being.

**Comment by raffazizzi** [comment]
A note before the F2F: It seems that there is some agreement on adopting an `<app>` based solution, but I have a sense that outside of the classical philology use cases, `<rdg>` tends to be used exclusively with reading from sources rather than readings from editors. Also, it may make sense to distinguish between recording a previous editor's decision (with an `<rdg>`, like @hcayless suggested) from the current editor or transcriber's interpretation. In the latter case we have tools like orig, reg, sic, and corr that qualify editorial "readings" in a more apt manner than `<rdg>`.

I would still recommend a solution with `<alt>`, maybe something like this:
```xml
<p>Some text <unclear/> 
<supplied xml:id="sup1">added</supplied> 
<supplied  xml:id="sup2">padded</supplied> 
<alt mode="excl" target="#sup1 #sup2"/> here.</p>
```

Othewise, we should talk about making `<supplied>` part of `model.choicePart`, which I don't think should break anything.

**Comment by gerritbruening** [comment]
Is the use of `rdg` with `@resp` really a stretch?
The Guideles seem to exactly propose this: See 
https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/TC-CriticalApparatus.xml#L208
and the following line.

But I also felt that the content `rdg` is normally based on witnesses. BTW, `alt` has the same problem: The Guidelines propose to use it for [alternatives on the encoder's side](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SAAT)
  **and** for alternatives left open by an author:
https://github.com/TEIC/TEI/blob/dev/P5/Source/Guidelines/en/PH-PrimarySources.xml#L2391.

**Comment by raffazizzi** [comment]
Council actions:

1. Add supplied to `model.choicePart`.
2. The short definition of `<choice>` is: "groups a number of alternative encodings for the same point in a text", so choice should deal with a *single* phenomenon (i.e. one act of supplying, not two acts of supplying). For example a reasonable solution could be (suggested by @lb42):
```xml
<supplied>
    <choice>
        <seg>unitas<seg>
        <seg>uincas</seg>
    </choice>
</supplied>
```
Will add some prose to the guidelines to clarify role of choice.
