### ISSUE TITLE
consider adding @xml:space as global attribute in Tite

### ISSUE THREAD

**Issue by kshawkin** [TEIC/TEI#1436]
See discussion on [this thread on TEI-L](https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;93add70d.1602).

**Comment by hcayless** [comment]
If we're talking about dumping un-marked-up data into an element like `<ab>` then is `@xml:space` necessary? Is there a worry that it might get reformatted by some process? I've no objection to this in principle.

**Comment by kshawkin** [comment]
Maybe you don't want an XML editor to mess with the line breaks in the OCR because it would make later OCR correction, done by comparing against the scans, more difficult.

**Comment by tuurma** [comment]
In a workgroup session we say go; will present it to the Council in a few minutes and follow up implementing if noone objects.
