### ISSUE TITLE
add @notation on u

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1437]
A recent discussion between @lb42 Thomas Schmidt and myself showed that there is a real use case fro indicating the actual notation used in a transcription, which may change from one `<u>` to another. This would of course be complementary to any indication present in `<transcriptionDesc>` (preferred when the transcription uses a stable notation). This has also been the object of a discussion with the French IRCOM group (network of scholars having to do with oral data) and I quote Thomas:
"This happens frequently, for instance, in child language transcription where some
utterances are better transcribed orthographically, some phonetically. If you want to process such a document you have to know which is which. You can't tell from the character data alone. Orthography, IPA and SAMPA overlap in their character sets."
@type is not is not a good candidate here since these are not sub kinds of <u>
@rend is also sub-optimal since it has nothing with layout (and the transcription is somehow born-digital, i.e. generated by annotation softwares)
we do have @notation which works well in dictionaries and which we would suggest to add to `<u>` for the described purpose.

**Comment by lb42** [comment]
Easy enough to do. @notation is locally defined on formula  pVar  pron : probably it would be better as a new class @att.notated unless anyone can think of a better name. All in favour?

**Comment by bansp** [comment]
I can see all hands raised.

**Comment by laurentromary** [comment]
Yes! (no prejudice for the name)

**Comment by lb42** [comment]
Implemented at commit cf9a6355a2a7360fbf51e30fedeeff4bf796edfd
