### ISSUE TITLE
screwy Schematron?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1440]
The example of ISO Schematron with `@ident` “subclauses” (which is in chapter TD) seems unduly complex. The main test is
~~~~~xml
<assert test="not(tei:div) or count(tei:div)&gt;1">
~~~~~
Which says, essentially, “it’s OK if there are either 0 `<div>`s OR if there are greater than 1 `<div>`” — i.e., the only condition which is **not** OK is 1 `<div>`. So why not just
~~~~~xml
<report test="count( tei:div ) eq 1">
~~~~~
?

**Comment by bansp** [comment]
I think it might even be slightly more didactic the way you suggest, showing the contrast between the human-readable explanation ("a division must contain at least two subdivisions") and the quick'n'easy check.

**Comment by hcayless** [comment]
I think that's what Lou would call a "corrigible error." I'd say just do it.

**Comment by sydb** [comment]
OK. fixed in my local repository, and I *think* I pushed it up properly.
