### ISSUE TITLE
Solve base-uri problem in Stylesheets before next release

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1446]
There is an issue in the Stylesheets, when deployed in context of oxgarage, that means that the base-uri of the source isn't provided properly causing oxgarage and hence roma to be non-functional.  This is documented on an issue in the Roma repo https://github.com/TEIC/Roma/issues/12 but I put an issue here so that I can mark it as release-blocking for the next release.

**Comment by jamescummings** [comment]
(Adding Hugh and Lou to this so that *someone* will remember before the next time we create a release that we have to fix this first.)

**Comment by hcayless** [comment]
I think this is highly likely to be a bug in OxGarage...need to look at whether it sets a localsource/defaultSource parameter when it calls the stylesheet. My guess is it's trying to find a local copy of p5subset.xml and failing.

**Comment by raffazizzi** [comment]
I *think* this was solved here: https://github.com/TEIC/Stylesheets/commit/f3044b9e37520fd034b27dc792f948a8cb172538

Can someone double check? If it seems like we're good I'll merge the branch to dev.

**Comment by raffazizzi** [comment]
Marking as resolved (see https://github.com/TEIC/Stylesheets/commit/a7a4edb86ca697e5753fb87fe7ea0d9a79fd48d8)
