### ISSUE TITLE
Add <teiCorpus> to att.typed

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1448]
A typical use case of TEI Corpus is to have a multi-level description of a complex corpus structure, which may correspond to various logics (corpus origin, workflow etc.). Typical application are the Laudatio project (see biblio under: http://www.laudatio-repository.org/laudatio/publikationen-und-konferenzen/) or the management of patent corpora where you have for instance an organisation in patent families (multiple filling in Europe, Japan and the US for instance) and patent stages (registration, further iteration, publications). 
A type/subtype attribute on teiCorpus would easily fulfill such requirements at a low conceptual price for the TEI (even less than having added TEI to att.typed)

**Comment by bansp** [comment]
Yes please. I have had to abuse @n for the purpose of typing corpora (and sub-corpora) so far.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.

**Comment by lb42** [comment]
It makes no sense for TEI to be typed but not teiCorpus, so I regard this as a corrigible error, and have corrected it accordingly.
