### ISSUE TITLE
listRef can't contain ref?

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1449]
Just noticed this when looking at an ODD "expanded" via the Stylesheets. Surely `<ref>` as well as `<ptr>` should be legal? Current content model is
```xml
<content>
 <elementRef key="ptr" minOccurs="1"
  maxOccurs="unbounded"/>
</content>
```

**Comment by emylonas** [comment]
Group A thinks this is reasonable so the list of pointers could become a list of pointers with notes or glosses. However, adding `<ref>` would open the floodgates to including many other types of element, even `<listRef>`. So maybe exclude all put the gloss?

Also, this would require modifying the stylesheets.

**Comment by smjwsk** [comment]
@lb42 fixed this @sydb disagrees
