### ISSUE TITLE
Content model of content

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1450]
`<content>` can be empty, as it is in many elements that contain no content. But the content model doesn't actually permit this:
```xml
<content>
 <alternate maxOccurs="unbounded">
  <macroRef key="macro.anyXML"/>
  <classRef key="model.contentPart"/>
 </alternate>
</content>
```

**Comment by lb42** [comment]
Presumably itscthe macro.anyxml part w hi CH permits no content

**Comment by hcayless** [comment]
I'm getting the following error message with 3.0.0:

> [Jing] element "content" incomplete; expected element "alternate", "classRef", "dataRef", "elementRef", "macroRef", "sequence", "textNode" or "valList" or an element from another namespace

This wasn't the case before. Maybe because of changes to macro.anyXML? Should be easy to fix though, no? just add `@minOccurs="0"`. I'll do that unless you think it's stupid.

**Comment by lb42** [comment]
What is puzzling me is why our test suite didn't catch this.

**Comment by hcayless** [comment]
I'm not sure we ever bother to validate fully-expanded ODDs, and for some reason, the NVDL validation on the ODD specs doesn't care about it. You only see it when you load up p5subset.xml or something like that. I happened to notice it because I built a full ODD to give to a group working on TEI visualization stuff. But it's an intermediate step normally, on the way to generating a schema.

**Comment by lb42** [comment]
It's the NVDL validation that's letting us down ? Makes no sense.

**Comment by lb42** [comment]
This seems like a mistake I introduced at https://github.com/TEIC/TEI/commit/df4fce32817c4e3a4b6b4c35473849c47192caa2
I made what I think is a fix : please test!

**Comment by sydb** [comment]
Works for me, so closing.
(I both eyeballed and tested my local build and the [latest Jenkins build](http://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/custom/schema/relaxng/tei_all.rnc/*view*/).)
