### ISSUE TITLE
wording discussing eol hyphen resolution too strong

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1451]
In [3.2.2 Hyphenation](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU-2) the futility of trying to disambiguate “tei-pot” from “teapot” when the hyphen occurs at the end-of-line is discussed. The phrasing is “there is simply no way of deciding which of the two spellings was intended”. I think that is too strong, and that what was intended (or should be stated) is “there is no simple way of deciding which of the two spellings was intended”.
I think this because what is being discussed is “any case”, not a particular case. In **some** cases, one could ascertain the intended or “correct” spelling by searching the rest of the text for both spellings (not at end-of-line).
**ALSO**, the next sentence starts with “As elsewhere, therefore, the encoder has a range of choices”. I think this should be written in the plural (“As elsewhere, therefore, encoders have a range of choices”) to better match the content of the bulletted list that follows. (Because we are too afraid to say “his or her” or “her” or lord forbid “his”.)

**Comment by PFSchaffner** [comment]
Syd, I love your neologism "tei-pot". As in, "a tempest in a"
(And the burden of your suggestion seems uncontroversial, too.)

**Comment by lb42** [comment]
ROFL

**Comment by sydb** [comment]
@PFSchaffner Oh dear! Must mean the 3rd definition of “neologism” at [wiktionary](https://en.wiktionary.org/wiki/neologism) (I had to look up “ROFL”). If it’s not just a place for a tempest, I dare say we should stay away from what it might mean!

**Comment by sydb** [comment]
As no one has raised any objection, I've gone ahead and made this change in e3a5f03..612a678.
