### ISSUE TITLE
@class attribute on <msContents>, <msItem>, and <msItemStruct> should all be added to an attribute class.

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1452]
`@class` attribute on `<msContents>`, `<msItem>`, and `<msItemStruct>` should all be added to an attribute class.

`<attRef>` shouldn't be since this is a different data type. (though that could be investigated).

**Comment by emylonas** [comment]
Most likely done,  need to proofread

**Comment by emylonas** [comment]
Closed with  commit 80ff2c4
