### ISSUE TITLE
Allowing att.typed for <msPart>

### ISSUE THREAD

**Issue by jakub-simek** [TEIC/TEI#1454]
Would it be possible to allow the att.typed attributes (`@type` and `@subtype`) for `<msPart>`? We use `<msPart>` in library-oriented manuscript descriptions for distinguishing different parts of composite manuscripts, including fragments found in the bindings, single leaves pasted later into the original gatherings and the like. We would like to use `@type` to distinguish some categories like „fascicle“ or „binding_fragment“.

**Comment by jamescummings** [comment]
Hi @jakub-simek 

Our default question when someone asks for att.typed membership for an element is to ask two questions:
1) Is the element repeatable?
2) Can we think of some reasonable examples of how someone might want to classify this element (both generally (`@type`) and specifically (`@subtype)` 

This seems completely obvious that msPart is both repeatable and you've provided some examples.  (If you could provide some more examples, and examples of both type and subtype... that might be helpful.)

I'll draw the TEI Council's attention to this issue number and assume that if we don't get anyone arguing about it in a week or so, that it is ok for me to implement.

A secondary question:  Should the new msFrag element be a member of att.typed as well? http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msFrag.html

**Comment by jakub-simek** [comment]
Dear @jamescummings,

I needed a few days for answering because several people were involved in the answer. My librarian colleagues now tried to come up with a more systematic approach to possible `@type` and `@subtype` categories they expect to need while describing manuscripts. Here are the categories we were able to think of so far:

**Simple differentiation:**

- `type=“fascicle“` (part of a composite codex, originally an independent codex; usually there will be at least one other `<msPart type=“fascicle“>` in the manuscript description)
- `type=”fragment”` (fragments that are bound with/enclosed, separated, partially loosened – binding, reinforcing strips, loose leaves etc.)
- `type=”print”` (printed items bound in)
- `type=”addendum”` (texts inserted later – they need to be separately described regarding dating, localization, scribe, script; this would be an alternative way to do so beside `<msItem>`)

**Further specification with `@subtype`:**

`@type=”fascicle”`: possible `@subtype` value: print

`@type=”fragment”`: possible `@subtype` values: binding; maculature; strip; reinforcing_strip; guard; parchment_strip; palimpsest; single_leaf; leaves; bifolium; pastedown; spine; integrated; loose; disconnected

The two lists are certainly not exhaustive, but I think they should do as evidence why the att.typed attributes are needed.

To your second question: Yes, I think that these categories similarly apply for `msFrag` as well and should be introduced there.

My colleagues and me would be very grateful if the attributes could be allowed for `msPart` and `msFrag`.

Best wishes,
Jakub

**Comment by jamescummings** [comment]
@jakub-simek 

Personally, I find these examples very convincing, especially the `@subtype` for fragments.

I'll draw council's attention to this and suggest they comment before 1 June if they disagree.

**Comment by jamescummings** [comment]
Council informed at this date by email: http://lists.tei-c.org/pipermail/tei-council/2016/022959.html

**Comment by jamescummings** [comment]
Implemented by adding msPart and msFrag both to be members of att.typed.
