### ISSUE TITLE
bug in pure odd ?

### ISSUE THREAD

**Issue by bgaiffe** [TEIC/TEI#1455]
I think there is a problem with the implementation of classRef when the class refered to is modified in the specification. I join a  perhaps not minimal enough example where I define  "listAnnotation" in pure odd (via  a classRef) and "listAnnotation2" in old fashioned relaxNG. 
Tha result is that listAnnotation2 may contain "index" (the sole member of model.global.meta in my setting) wheras listAnnotation may not.
[minimalClassRefBug.txt](https://github.com/TEIC/TEI/files/263310/minimalClassRefBug.txt)

**Comment by lb42** [comment]
Interesting. I fear  the current generation of ODD processors is not as clever as you think. Firstly, you are not allowed to just invent module names without supplying a moduleSpec (and there is now a schematron rule to enforce that) . Your new non-TEI-namespace elements will always be put into a special module anyway, but there is no way to put new class specifications there, and then modify them. The way to do what you are trying to do here is to make the content model of &lt;listAnnotation> explicitly reference the two classes concerned (as my attached revision). 
[cantDefineClassesMoreThanOnce.txt](https://github.com/TEIC/TEI/files/263710/cantDefineClassesMoreThanOnce.txt)

**Comment by bgaiffe** [comment]
Thank you Lou. Sorry for having too much minimalized the example...
