### ISSUE TITLE
<defaultVal>s of "unknown" should be removed

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1456]
An example is `@aloud`:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-said.html

which has a defaultVal of "unknown", which contributes nothing other than unexpected attributes that materialize during processing. It should go. We'll add other similar candidates to this ticket as we find them.

**Comment by sydb** [comment]
The list of "unknown" cases is:

- `@status` of `<availability>`
- `@status` of `<correction>`
- `@aloud` of `<said>`
- `@discrete` of `<sound>`

(According to:
~~~~~
$ xsel -t -m "//t:defaultVal[.='unknown']" -v "concat( '@', ancestor::t:attDef/@ident, ' of ', ancestor::t:elementSpec/@ident | ancestor::t:classSpec/@ident | ancestor::t:macroSpec/@ident )" -n p5subset.xml 
~~~~~

**Comment by sydb** [comment]
I can see **no** reason to keep `<defaultVal>unknown</defaultVal>`, although I’m willing to listen if anyone presents an argument in favor of keeping them. The big question in my mind is should they just be removed, or should the go through some sort of deprecation process first?

**Comment by jamescummings** [comment]
I think they could just be removed. I suppose we could do schematron warning of their removal.

**Comment by sydb** [comment]
(See also #1457.)

**Comment by sydb** [comment]
Well, given that what deprecation boils down to *is* a Schematron warning, I’d say we now have 2 votes for deprecation (and MH, too). I don’t think we have to go the normal full 2 years, though, because after all, the attribute value is meaningless.

**Comment by martindholmes** [comment]
Confirmed: There is no handling in the Stylesheets for `@validUntil` on `<defaultVal>`.

**Comment by martindholmes** [comment]
These defaultVals have now been deprecated in 

https://github.com/TEIC/TEI/commit/4543bb0c742c140c988f2c4ef06f65de8a432e83

and handling for the deprecation added to the Stylesheets in commit 

https://github.com/TEIC/Stylesheets/commit/6d80c743ecbaed689d7f212536da2e1382f8ef4e

If all the products build correctly (HTML, PDF, ePubs) we can close this ticket.

**Comment by martindholmes** [comment]
The HTML build is working OK, although it may need minor tweaks. Other output is not yet functioning correctly, but that is being tracked in Stylesheets issue https://github.com/TEIC/Stylesheets/issues/158. I'm going to close this ticket.
