### ISSUE TITLE
<defaultVal> of "false" for @defective is misleading

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1457]
The defaultVal of `@defective` is "false":

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.msExcerpt.html

This means that every time you use a `<quote>`, even if you explicitly remove part of it and insert an ellipsis, you are asserting without your knowledge that the quote is not "defective". This is wrong.

**Comment by jamescummings** [comment]
I agree. Remove the defaultVal.  I don't like defaultVals though, so maybe I'm biased.

**Comment by sydb** [comment]
(See also #1456.)

**Comment by sydb** [comment]
I agree completely with Martin that this is wrong, but the question is — is it a *corrigible* error we should just fix, or should it be deprecated?
MH and SB both lean towards deprecation, but we could ask on TEI-L and see if anyone would be adversely affected by just fixing it.

**Comment by sydb** [comment]
MH points out that the `@full` attr of att.personal has exactly the same problem.

**Comment by sydb** [comment]
Works for me, so closing.
(I both eyeballed and tested my local build and the [latest Jenkins build](http://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/custom/schema/relaxng/tei_all.rnc/*view*/).)

**Comment by sydb** [comment]
Oh dear. Completely ignore my comment (and closing) of 2 hours ago — that was for a different ticket.

**Comment by martindholmes** [comment]
On 2016-08-26 I posted a message to TEI-L to see if anyone might be adversely affected by removing these defaultVals, and the sparse response suggests not:

https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1608&L=tei-l&F=&S=&P=29008

I think we can go ahead with this.

**Comment by sydb** [comment]
Since no one has objected either here, on Council list, or even on TEI-L, I’m declaring the discussion period over, setting status to green, setting the `@validUntil` of `<defaultVal>` of `@defective` of `att.msExcerpt` to 2017-09-05 (to match those that were depricated per #1456), and closing ticket.

Change pushed in commit 5a82d76.
