### ISSUE TITLE
Empty <content> not allowed

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/TEI#1458]
Empty `<content/>` is not valid, [but should be](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-content.html#index-egXML-d51e145914). See current definition:
```xml
<content>
    <alternate>
	<macroRef key="macro.anyXML" />
	<classRef minOccurs="0" maxOccurs="unbounded" key="model.contentPart" />
    </alternate>
</content>
```

I suspect that `<alternate>` should have a `@minOccurs="0"`

**Comment by hcayless** [comment]
Is this a dupe of #1450?

**Comment by raffazizzi** [comment]
It is. Sorry! Closing
