### ISSUE TITLE
Description of <textNode> is insufficient

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1459]
In the old days (i.e., a few months ago) we created content models in RELAX NG, and so the definition of various bits of a content model was left to the RELAX NG spec. Said spec is very explicit when it comes to `<rng:text>`: “A string consists of a sequence of zero or more characters” and “a text element matches zero or more strings”. But we do not say, precisely, what `<tei:textNode>` matches. AFAIK, a `<textNode>` is converted directly to an `<rng:text>`, so nothing has changed. Except now it is incumbent upon us to make this clear in the prose of [TD](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#DEFCON) that discusses `<textNode>`.

**Comment by lb42** [comment]
Not sure what you're getting at here, but I've amplified the current prose a little so that it now reads
"<p>An element may contain nothing but strings of Unicode characters. This is indicated by supplying the
        element <gi>textNode</gi> within the <gi>content</gi> element. An element containing a 
        sequence of zero or more Unicode characters would match an element with this content model.       </p>
   
will that do?

**Comment by sydb** [comment]
That is a whole lot better.

That said, I think the whole section could use some more work. Here is a first crack at an improvement. Let me know what you think.
~~~~~
    <p>In the simplest case, the content model of an element being
    defined using TEI elements may be expressed using an empty
    <gi>content</gi>. This describes the element being defined as
    <term>empty</term>, meaning a valid instance of said element can
    not have any content.</p>
    <p>More commonly, one or more of the following elements are used
    to define a content model:
    <specList>
      <specDesc key="elementRef"/>
      <specDesc key="classRef"/>
      <specDesc key="macroRef"/>
      <specDesc key="textNode"/>
    </specList>
    </p>
    <p>An <gi>elementRef</gi> provides the name of an element which may
    appear at a certain point in a content model. A <gi>classRef</gi>
    provides the name of a class, members of which may appear at a
    certain point in content model. A <gi>macroRef</gi> provides the
    name of a predefined macro, the expansion of which may be inserted
    at a certain point in a content model.</p>
    <p>These three elements are all members of an attribute class
    which provides attributes that further modify their significance
    as follows:
    <specList>
      <specDesc key="att.repeatable" atts="minOccurs maxOccurs context"/>
    </specList>
    </p>
    <p>In addition to expressing where certain elements, members of a
    class of elements, or constructs matching a predefined macro may
    occur inside an element, a content model expressed in TEI may
    permit a string of zero or more Unicode characters to occur at a
    certain point in the content model. This is indicated by supplying
    the element <gi>textNode</gi> within the <gi>content</gi> element.
    If nothing but a <gi>textNode</gi> element is present inside a
    <gi>content</gi> element, valid instances of the element being
    defined may contain a sequence of zero or more Unicode characters,
    but may not contain any elements. (As with any XML element, it
    would still be allowed to contain comments or processing
    instructions, as these are not part of the content model.)</p>
    <p>Finally, two wrapper elements are provided to indicate whether
    the components contained within form a sequence or an alternation:
    <specList>
      <specDesc key="sequence"/>
      <specDesc key="alternate"/>
    </specList>
    </p>
~~~~~

**Comment by lb42** [comment]
I like my version better because it's less verbose. The parenthetical comment (As with any XML element...) seems entirely redundant here, for example. And I don't like the phrase "the content model of an element being defined using TEI elements", since it suggests that the use of TEI elements is a special case, whereas the whole point of this section is to show that that is just how we do it. "the components contained within form " could more simply say "the components specified form"

**Comment by sydb** [comment]
In reverse order:

>  “the components contained within form” could more simply say “the components specified form”

The point, I think, is to avoid any ambiguity about *which* components we are talking about. I.e., to make perfectly clear that `<sequence>` and `<alternate>` talk about their children, not about something pointed to by some attribute or elsewhere in the current content model. (And not even about other descendants, but that doesn’t seem like it is necessary to mention.)

So in truth, I don’t like my “contained within” anymore. I prefer your “the components specified form” to the current “the components of a content model form”, but would like “the components listed as its children form” or some such even better.

> I don't like the phrase “the content model of an element being defined using TEI elements”, since …

Good point. Should be just “the content model of an element” then, eh?

> The parenthetical comment …

I could certainly live without it, but it is not clear to me that it is technically redundant. Where else is it said that a TEI content model describes only the valid element and textual content, not the attributes, namespaces, processing instructions, or comments thereof? While perhaps stupid, it would have been perfectly feasible for TEI to create a `<pi name="PI_target_name_here">` element for use in `<content>`.
Personally, I’d demote it to a footnote, though.

Overall I like mine better because I like the approach of discussing empty first, then elements, then text. That said, I have no doubt it could be improved further.

**Comment by ebeshero** [comment]
Taking stock of open tickets, I'm assigning this one a milestone Release 3.1.0 marker to indicate partial completion, but leaving it open because I need to work on more revisions.

**Comment by hcayless** [comment]
If this isn't done and isn't going to be before 3.1.0, it should be taken out.

**Comment by sydb** [comment]
Sorry, Hugh; I’m missing something. Surely you’re not suggesting that `<textNode>` should be removed. Are you suggesting that we revert @lb’s change of 05-17? AFAIK, we all think his change is an improvement over the currently released version. I, for one, think we can and should do a lot better. But that doesn’t mean we should back out the marginal improvement we have.

Perhaps you just mean this ticket should not be flagged as "Guidelines 3.1.0"? Sure. Not sure why it ever was. (EB’s analysis of the situation on 10-30 is, IMHO, spot on, but the conclusion that the ticket should be flagged with a particular milestone doesn’t follow.)

**Comment by lb42** [comment]
I am pretty sure Hugh just meant remove it from the Milestone. Which he just did. I also think my prose change is an improvement. Maybe we should close this ticket?

**Comment by hcayless** [comment]
That's all I meant, no need to panic. If you think it's done, @lb42 , you can close it and put it back in the milestone. I'm just housecleaning.

**Comment by sydb** [comment]
No, this ticket is not ready to be closed. Yes, Lou’s prose change is an improvement, but it is insufficient. We can, and should, do better.

**Comment by ebeshero** [comment]
Just a nudge as I'm reviewing my open tickets: We need to discuss/work on this in a meeting (perhaps at face-to-face) because @sydb has recommended extensive revision to http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#DEFCON . But it's probably not a high priority immediately before the July 2017 release...

**Comment by sydb** [comment]
Per discussion on [Stylesheets 247](https://github.com/TEIC/Stylesheets/issues/247), it’s not just the prose whot needs updating, but the content model of `<content>`, too!

The current content model, besides incorrectly permitting multiple children from model.contentPart, allows them to be intermingled with RELAX NG elements. I’m not sure whether we want to continue that practice or not. It is certainly a lot easier to say not — a content model is defined by putting one of the following inside your `<content>`:

1. nothing (i.e., empty)
2. a PureODD element (including, possibly, `<empty>`)
3. one or more RELAX NG elements

In which case the content model should be `( anyElement-content+ | model.contentPart? )`, no?[1] I.e.,
~~~~~xml
  <content>
    <alternate>
      <anyElement minOccurs="1" maxOccurs="unbounded"
		  require="http://relaxng.org/ns/structure/1.0"/>
      <classRef key="model.contentPart" minOccurs="1" maxOccurs="1"/>
    </alternate>
  </content>
~~~~~
Likewise the prose of TD needs to be updated to match, and the `<remarks>` in the tagdoc needs to be updated, as it still refers to macro.schemaPattern.

**Note**
[1] Note that this is exactly equivalent to `( anyElement-content* | model.contentPart )`, but implies that being empty is part of the PureODD definition, not the RELAX NG definition, which makes sense. But this is only an implication, there is no formal difference between what `<content>`s would be valid or actual semantics.

**Comment by raffazizzi** [comment]
F2F subgroup: this ticket was closed, but if @sydb is not happy with the prose, we suggest he revisits it again. Regarding the last suggestion we agree that the content model of `<content>` should be changed as suggested, but we should create a different ticket for that.

**Comment by raffazizzi** [comment]
# ATTRIBUTE CLASSES
                        
## tei                
                
* att.ascribed
* att.canonical
* att.ranging
* att.dimensions
* att.written
* att.damaged
* att.breaking
* att.cReferencing
* att.datable.w3c
* att.datable
* att.datcat
* att.declarable
* att.declaring
* att.fragmentable
* att.divLike
* att.docStatus
* att.duration.w3c
* att.duration.iso
* att.global.responsibility
* att.editLike
* att.global.rendition
* att.global.source
* att.global
* att.handFeatures
* att.internetMedia
* att.media
* att.resourced
* att.interpLike
* att.measurement
* att.naming
* att.notated
* att.placement
* att.typed
* att.pointing
* att.pointing.group
* att.scoping
* att.segLike
* att.sortable
* att.edition
* att.spanning
* att.styleDef
* att.tableDecoration
* att.timed
* att.transcriptional
* att.translatable
* att.citing
* att.partials
* att.personal
                
## namesdates                
                
* att.datable.custom
* att.datable.iso
                
## spoken                
                
* att.duration
                
## core                
                
* att.milestoneUnit
                
## header                
                
* att.patternReplacement
                
## verse                
                
* att.metrical
* att.enjamb
                
## dictionaries                
                
* att.entryLike
* att.lexicographic
                
## msdescription                
                
* att.msExcerpt
* att.msClass
                
## transcr                
                
* att.global.facs
* att.global.change
* att.coordinated
                
## textcrit                
                
* att.rdgPart
* att.witnessed
* att.textCritical
                
## linking                
                
* att.global.linking
                
## analysis                
                
* att.global.analytic
                
## tagdocs                
                
* att.repeatable
* att.combinable
* att.identified
* att.deprecated
* att.namespaceable

# MODEL CLASSES
                        
## tei
                
model.nameLike.agent
model.segLike
model.hiLike
model.emphLike
model.highlighted
model.dateLike
model.dimLike
model.measureLike
model.egLike
model.graphicLike
model.offsetLike
model.pPart.msdesc
model.pPart.editorial
model.pPart.transcriptional
model.pPart.edit
model.linePart
model.ptrLike
model.lPart
model.global.meta
model.milestoneLike
model.gLike
model.oddDecl
model.oddRef
model.phrase.xml
model.specDescLike
model.biblLike
model.headLike
model.labelLike
model.listLike
model.noteLike
model.lLike
model.pLike
model.stageLike
model.featureVal.complex
model.featureVal.single
model.entryPart
model.entryPart.top
model.eventLike
model.global.edit
model.divPart
model.persStateLike
model.personLike
model.personPart
model.placeNamePart
model.placeStateLike
model.orgPart
model.publicationStmtPart.agency
model.publicationStmtPart.detail
model.availabilityPart
model.certLike
model.descLike
model.glossLike
model.quoteLike
model.qLike
model.respLike
model.divWrapper
model.divTopPart
model.divTop
model.frontPart.drama
model.pLike.front
model.divBottomPart
model.divBottom
model.titlepagePart
model.msQuoteLike
model.msItemPart
model.choicePart
model.imprintPart
model.catDescPart
model.settingPart
model.textDescPart
model.castItemPart
model.physDescPart
model.addressLike
model.nameLike
model.global
model.featureVal
model.biblPart
model.frontPart
model.addrPart
model.pPart.data
model.inter
model.common
model.phrase
model.limitedPhrase
model.divLike
model.divGenLike
model.div1Like
model.div2Like
model.div3Like
model.div4Like
model.div5Like
model.div6Like
model.div7Like
model.applicationLike
model.teiHeaderPart
model.sourceDescPart
model.encodingDescPart
model.editorialDeclPart
model.profileDescPart
model.correspActionPart
model.correspContextPart
model.correspDescPart
model.resourceLike
model.orgStateLike
model.placeLike
model.segLike
model.segLike
model.segLike
                
## spoken
                
model.global.spoken
model.recordingPart
model.divPart.spoken
                
## textcrit
                
model.rdgLike
model.rdgPart
                
## namesdates
                
model.persNamePart
                
## dictionaries
                
model.entryLike
model.morphLike
model.lexicalRefinement
model.gramPart
model.formPart
model.ptrLike.form
                
## tagdocs
                
model.contentPart

# DATATYPES
                        
## tei
                
* att.ascribed
* att.canonical
* att.ranging
* att.dimensions
* att.written
* att.damaged
* att.breaking
* att.cReferencing
* att.datable.w3c
* att.datable
* att.datcat
* att.declarable
* att.declaring
* att.fragmentable
* att.divLike
* att.docStatus
* att.duration.w3c
* att.duration.iso
* att.global.responsibility
* att.editLike
* att.global.rendition
* att.global.source
* att.global
* att.handFeatures
* att.internetMedia
* att.media
* att.resourced
* att.interpLike
* att.measurement
* att.naming
* att.notated
* att.placement
* att.typed
* att.pointing
* att.pointing.group
* att.scoping
* att.segLike
* att.sortable
* att.edition
* att.spanning
* att.styleDef
* att.tableDecoration
* att.timed
* att.transcriptional
* att.translatable
* att.citing
* att.partials
* att.personal
                
## namesdates
                
* att.datable.custom
* att.datable.iso
                
## spoken
                
* att.duration
                
## core
                
* att.milestoneUnit
                
## header
                
* att.patternReplacement
                
## verse
                
* att.metrical
* att.enjamb
                
## dictionaries
                
* att.entryLike
* att.lexicographic
                
## msdescription
                
* att.msExcerpt
* att.msClass
                
## transcr
                
* att.global.facs
* att.global.change
* att.coordinated
                
## textcrit
                
* att.rdgPart
* att.witnessed
* att.textCritical
                
## linking
                
* att.global.linking
                
## analysis
                
* att.global.analytic
                
## tagdocs
                
* att.repeatable
* att.combinable
* att.identified
* att.deprecated
* att.namespaceable

# MACROS
                        
## tei
                
* att.ascribed
* att.canonical
* att.ranging
* att.dimensions
* att.written
* att.damaged
* att.breaking
* att.cReferencing
* att.datable.w3c
* att.datable
* att.datcat
* att.declarable
* att.declaring
* att.fragmentable
* att.divLike
* att.docStatus
* att.duration.w3c
* att.duration.iso
* att.global.responsibility
* att.editLike
* att.global.rendition
* att.global.source
* att.global
* att.handFeatures
* att.internetMedia
* att.media
* att.resourced
* att.interpLike
* att.measurement
* att.naming
* att.notated
* att.placement
* att.typed
* att.pointing
* att.pointing.group
* att.scoping
* att.segLike
* att.sortable
* att.edition
* att.spanning
* att.styleDef
* att.tableDecoration
* att.timed
* att.transcriptional
* att.translatable
* att.citing
* att.partials
* att.personal
                
## namesdates
                
* att.datable.custom
* att.datable.iso
                
## spoken
                
* att.duration
                
## core
                
* att.milestoneUnit
                
## header
                
* att.patternReplacement
                
## verse
                
* att.metrical
* att.enjamb
                
## dictionaries
                
* att.entryLike
* att.lexicographic
                
## msdescription
                
* att.msExcerpt
* att.msClass
                
## transcr
                
* att.global.facs
* att.global.change
* att.coordinated
                
## textcrit
                
* att.rdgPart
* att.witnessed
* att.textCritical
                
## linking
                
* att.global.linking
                
## analysis
                
* att.global.analytic
                
## tagdocs
                
* att.repeatable
* att.combinable
* att.identified
* att.deprecated
* att.namespaceable

**Comment by ebeshero** [comment]
I will make sure that @sydb continues with this.
