### ISSUE TITLE
Is PureODD <sequence> expressive enough?

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/TEI#1462]
Currently, a PureODD datatype defined like this:

```xml
<dataSpec ident="meidata.twoDecimals">
   <content>
      <sequence>
         <dataRef name="decimal"/>
         <dataRef name="decimal"/>
      </sequence>
   </content>
<dataSpec>
```
results in the invalid RNG:
```xml
<group>
    <data type="decimal"/>
    <data type="decimal"/>
</group>
```
There should be an `rng:list` instead of 'rng:group`.

Is it the case that we need a different element for this kind of "sequence"? Or is it just a Stylesheet issue? (In which case see https://github.com/TEIC/Stylesheets/issues/152)

**Comment by jamescummings** [comment]
I think this is just a Stylesheets issue. I would resist invent new elements where we don't need them. ;-)

**Comment by raffazizzi** [comment]
Fixed in stylesheets https://github.com/TEIC/Stylesheets/issues/152
