### ISSUE TITLE
Relation of @style and @rendition needs clarifying

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1463]
The Guidelines make it clear that if `@rend` and `@rendition` are both present, the latter "overrides or complements" the other. Presumably meaning that style definitions that collide will be replaced by those of `@rendition`, but ones that don't will be preserved. The Guidelines don't specify a similar relationship between `@rendition` and `@style`. 

`@rendition` is said to be analogous to HTML's `@class` attribute, so presumably `@style` and `@rendition` should cascade just like HTML's `@style` and `@class` (so `@style` always overrides or complements `@rendition` too). And `@style` would override `@rend` just like `@rendition` does.

I think this is all relatively straightforward, but we should make it clearer.

**Comment by lb42** [comment]
I agree that we need to specify the relationship between @rendition and @style more exactly : if both are using CSS (which seems to be our default assumption) doing so is relatively painless. However, I am less convinced that we can say anything sensible if @rendition is pointing at some stylage defined in MyFunnyFormattingLanguage , which is also therefore the case (in spades) for @rend. Hence the wonderful weasel wording "overrides or complements", which I interpret as meaning "dunno what happens here".

**Comment by hcayless** [comment]
I'll propose some language for this.

**Comment by hcayless** [comment]
> If `@rendition` and `@style` are both present on an element, then the latter overrides or complements the other.

...

> If `@rend` and `@style` are both present on an element, then the latter overrides or complements the other.

**Comment by sydb** [comment]
> If `@rendition` and `@style` are both present on an element, then `@style` overrides or complements `@rendition`

or

> If `@rendition` and `@style` are both present on an element, then the latter overrides or complements the former

AND

> If `@rend` and `@style` are both present on an element, then `@style` overrides or complements `@rend`

or

> If `@rend` and `@style` are both present on an element, then the latter overrides or complements the former

**Comment by lb42** [comment]
I (continue to) think that the presence of @rend and (@rendition or @style) on the same instance is potentially chaotic and should not be permitted. @rendition and @style can be combined properly, IFF both are expressed in a suitable language such as CSS. There are no constraints on the way @rend is expressed.

**Comment by hcayless** [comment]
Added clarifying language in c553ddb42c8531f6b808c1f269a25389f809e692.
