### ISSUE TITLE
<content> examples need pure content

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1468]
James & I just discovered that quite a few examples of `<content>` still have RELAX NG. While it is possible some should in fact be RELAX NG, someone needs to look through the list, as many should probably be expressed in PureODD.
See [the list](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-content.html)

**Comment by martinascholger** [comment]
I can go through the examples. At first glance the first ones seem to be obvious: the examples in the  specs needs to be changed, the examples under 22.5.2 RELAX NG Content Models should remain unchanged. At the end of the list there are some examples which need a closer look, since they interrelate with the text in the guidelines...

**Comment by martinascholger** [comment]
I went through the examples and some questions arose: 

(1) In the specification for [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-content.html](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-content.html) we have two examples expressing the same thing, the first one is in Pure ODD, the second one contains rng. Is there a reason for that? Do we keep it like that or can I remove the rng example and adjust the first sentence in the remark: "As the example shows, content models may be expressed using the RELAX NG syntax directly."  

(2) Can anyone help me in "purifying" this example? I don't know how I should handle <rng:define>

```
<moduleRef url="svg11.rng">
 <content>
  <rng:define name="TEI_model.graphicLike"
   combine="choice">
   <rng:ref name="svg"/>
  </rng:define>
 </content>
</moduleRef>

```
(3) There are several examples in chapter 23, which have to be modified. If we touch the examples, the prose in the Guidelines has to be changed as well. Before I get to it, I just wanted to make sure, that I should proceed with that. See [example list (23 Using the TEI)](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-content.html).

**Comment by lb42** [comment]
(1) Yes, I think this correct. we are not so far proposing to withdraw support for rng content models atre we? so we should indclude at least one example!

(2) This  is a bit weird. The use of &lt;content> within moduleRef is  counterintuitive, and extremely under documented. i suggest we leave it as it is for now but  take time to ponder whether this is still the right way to go about modifying a TEI class to include a non-tei element.  

(3) Yes, I apologise for having entirely forgottem about this chapter when implementing purification of the GL. I can have a look later this week if you need help.

**Comment by martinascholger** [comment]
(1) and (2) agreed.
(3) we want purified examples in chapter 23, right? Should we keep the first example [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/USE.html#MDMDCM](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/USE.html#MDMDCM) in both versions (RELAX NG and pure) and reference to the respective chapters in 22 and then continue with pure content only? It would be great if you could have a look at the changes and complement them where necessary.

**Comment by lb42** [comment]
I added a remark to the spec for moduleRef to address your [2] above. I've just checked in revised version of USE.xml to address [3].
