### ISSUE TITLE
Cross reference for att.spanning is incorrect

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1469]
While teaching Syd and I noticed that the att.spanning reference page
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.spanning.html
points to 1.3.1 Attribute Classes at 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ST.html#STECAT
when it should probably point elsewhere.

Perhaps it should go here?
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHAD

**Comment by martindholmes** [comment]
Looks like a straightforward corrigible error to me.

**Comment by lb42** [comment]
By all means add a reference to #PHAD, but the reference to #STECAT is not wrong, since it is in ST that this class is declared.

**Comment by lb42** [comment]
Added a reference to #PHAD. Closing.
