### ISSUE TITLE
Example from address spec file is weird

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1470]
The first exemplum in address.xml looks like this:

```
<exemplum xml:lang="en">
    <egXML xmlns="http://www.tei-c.org/ns/Examples">
      <address>
        <street>via Marsala 24</street>
        <postCode>40126</postCode>
        <name>Bologna</name>
        <name n="I">Italy</name>
      </address>
    </egXML>
  </exemplum>
```

This is a very weird blend of specific and generic elements. `<street>` and `<postCode>` are highly specific, but then the city of Bologna and the country Italy are in generic `<name>`s. I can't imagine any real project tagging this way. I think `<settlement>` and `<country>` should be used. 

And what is that @n="I" doing?

**Comment by lb42** [comment]
It's not completely inexplicable but I agree this is not as good an example as the ones provided in the chapter (see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONAAD). I guess if all you have available from model.nameLike is name, that's what you have to do. The @n is being (mis)used presumably to supply the country code for Italy. Ingenious but, as you say, weird. I dont think it's a bug though I agree it would be better to use one of the chapter examples instead.

**Comment by raffazizzi** [comment]
F2F subgroup: @peterstadler observes that `street` and `postCode` are in the core module, while `settlement` and `country` are in the Names, Number, etc. module. Also `address` is in TEI Lite. 

The example makes sense when that module is not included. We suggest removing the ingenious but weird use of `@n` instead.

Note also that an example with `country` is also given on the element, and it specifies that it only makes sense when the Names, Number, etc. module is available.
