### ISSUE TITLE
new section on deprecated datatype macros

### ISSUE THREAD

**Issue by kshawkin** [TEIC/TEI#1471]
I see that chapter ST recently acquired a new section (currently 1.6) called "Decprecated datatype macros": http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ST.html#index-body.1_div.1_div.6 .  A few issues with it:

a) According to http://www.tei-c.org/Activities/Council/Working/tcw24.xml#house-style-capitalization , we use "title case" for headings.  Thus, it should be "Deprecated Datatype Macros".

b) I would have expected this section to have a four-letter `@xml:id` beginning with "ST" like other sections.  Perhaps "STDD".

c) I assume there's supposed to be a list in that section, but nothing displays in the HTML (and possibly in other formats: I haven't checked).

**Comment by lb42** [comment]
Council has yet to decide what to do with these legacy data macros. In the mean time, I've modified this section so that it doesn't call attention to the invisible list you comment on.  Leaving ticket open to remind us to decide how long to deprecate them for, and how.

**Comment by sydb** [comment]
LB to update the heading, `@xml:id`, and prose; SB to deprecate the datatypes themselves, with a `@validUntil` of approximately a year in the future.

**Comment by sydb** [comment]
This was finished on 201-05-06 with 56125fa, I think.
