### ISSUE TITLE
"Feature requests and bug reports" SF-->GH URL change

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1472]
Hi Council,

I've just discovered links to SourceForge bug and FR trackers on the ["TEI Support" page](http://www.tei-c.org/Support/index.xml#tei-bugs). They don't do any great harm, because users eventually get nicely redirected from SF to GitHub, but it might be a good idea to simply cut down on this extra hop and refer people directly to GitHub. And good ideas are worth sharing, so that's what I hereby do :-)

Cheers,

Piotr

**Comment by martindholmes** [comment]
Thanks Piotr; we must have missed that page when we updated the rest of the site. Now fixed. Closing the bug.
