### ISSUE TITLE
idno should be a member of att.typed

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1480]
The idno element should be a member of att.typed.

It currently defines its own local type attribute.  However, I've encountered a number of projects who are basically providing type and subtype through other means. (e.g. they create two-part type attribute values  foo_blort .... uri_main uri_legacy classmark_system1 classmark_system2  or similar).

Our test is usually 'is the element it is on repeatable (<idno> is), and is it able to classified in multiple ways (<idno>s certainly can be).

So I suggest that we add idno to att.typed.

**Comment by laurentromary** [comment]
Since idno is used for qualifying a wide variety of possible objects, I would definitely support this.

**Comment by ebeshero** [comment]
In addressing #1442 by providing a list of suggested values for (the currently local)`@type` on `<idno>`, I noticed in the examples list a couple that suggested to me we ought to be able to use `@subtype`: in the table of example uses we provide two different idno elements with made of a URI: one points to an OCLC record in URI form and the other points to a URI in the New Zealand Electronic Text Collection. Currently our recommended way of handling these is to set `@type` to "URI" and specify nothing more, though with `@subtype` we could indicate "OCLC" or "NZETC". 

I am in favor of the proposed change, but I wonder how we ought to handle the suggested value list on `@type`? I have placed OCLC on the current list and glossed it only as the distinct record number in WorldCat, but I imagine the URI (or URL) form would be typically more useful to people.

**Comment by jamescummings** [comment]
I would keep the suggested value list as you it is now, by providing local modification of `@type`, but also provide an additional example that used subtype something like:

`<idno type="URI" subtype="OCLC">the URI here</idno>`  

But of course with some useful URI.

**Comment by martindholmes** [comment]
Agree absolutely. I'm surprised we haven't done this before.

**Comment by peterstadler** [comment]
👍

**Comment by jamescummings** [comment]
Seems like a consensus is emerging so changing status to go but will wait some length of time before implementing and remind council of the existence of this (and #1481 since I'd probably do them at the same time).

**Comment by jamescummings** [comment]
Implemented at 2bad779
