### ISSUE TITLE
Error in autogenerated table in Infrastructure Chapter

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1482]
The Guidelines Chapter on Infrastructure includes an autogenerated table. 

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ST.html#tab-content-models

The values in it are '0', which is clearly wrong.  I suspect that this is fall out from Pure ODD and specifically renaming of TEI data types and macros.

We probably just need to find the bit in the XSLT that generates this and change it to use the new names.

**Comment by martindholmes** [comment]
This is done with a PI; I remember setting it up years ago.

**Comment by lb42** [comment]
The source says 
~~~~
<p>The present version of the TEI Guidelines includes some <?insert totalElements?> different
        elements. <ptr target="#tab-content-models"/> shows, in descending order of frequency, the
        seven most commonly used content models.<?insert tab-content-models?></p>
~~~~
Where are PIs documented? Nowhere. How on earth is one supposed to know how  this magic works?
Not really very satisfactory.  I did a grep for the string tab-content-models in the Stylesheets directory which led me to a probably irrelevant line in profiles/iso/latex and no further. 

Please enlighten us further Martin!

**Comment by martindholmes** [comment]
I think it's the template starting on line 82 of P5/Utilities/expand.xsl. Looking at it now...

**Comment by martindholmes** [comment]
The broken one is this template:

~~~~~
<xsl:template name="tab-content-models">
    <table xml:id="tab-content-models" rend="display">
      
      <row role="label">
        <cell>Content model</cell>
        <cell>Number of elements using this</cell>
        <cell>Description</cell>
      </row>
      
      <xsl:variable name="rows">
        <xsl:for-each select="//macroSpec[@type='pe']">
          <xsl:variable name="ident" select="@ident"/>
          
          <row>
            <cell><xsl:value-of select="@ident"/></cell>
            <cell><xsl:value-of select="count(distinct-values(//elementSpec[descendant::rng:ref[@name=$ident]]/@ident))"/></cell>
            <cell><xsl:apply-templates select="desc[1]"/></cell>
          </row>
          
        </xsl:for-each>
      </xsl:variable>
      
      <xsl:for-each select="$rows/row">
        <xsl:sort select="cell[2] cast as xs:integer" order="descending"/>
        <xsl:if test="position() lt 8"><xsl:copy-of select="."/> 
        </xsl:if>
      </xsl:for-each>
    </table>
  </xsl:template>
~~~~~

and this is what fails, for obvious reasons:

`count(distinct-values(//elementSpec[descendant::rng:ref[@name=$ident]]/@ident))`

I think it should be:

`count(distinct-values(//elementSpec[descendant::macroRef[@key=$ident]]/@ident))`

Should I fix it?

**Comment by martindholmes** [comment]
The comment in the source of the chapter does point at a ticket:

~~~~~
<!-- MDH 2013-04-25: Processing instructions to insert content per 
      https://sourceforge.net/p/tei/bugs/512/. -->
~~~~~

and that ticket points out that the thing is documented in TCW20:

http://www.tei-c.org/Activities/Council/Working/tcw20.xml#body.1_div.3

However, TCW20 tells you how to invoke these things, not where they're processed. I agree that documentation should be added to both the chapter source and expand.xsl.

**Comment by lb42** [comment]
Thanks Martin. I think adding a comment to TCW20 about where/how these things get processed would be very helpful. And yes, please do fix it!

**Comment by martindholmes** [comment]
Committed what I believe to be the fix to the expand.xsl, along with a line of comment documentation in the ST chapter, at commit 8d5e60b..c0ed680. We won't know if it's worked until the build is working again.

**Comment by martindholmes** [comment]
Added a sentence to TCW20 to explain that processing happens in expand.xsl.

**Comment by martindholmes** [comment]
I confirm that this works when I build the Guidelines locally using the current version of the Stylesheets that is distributed with Oxygen. I think we can now close this ticket. I'll assign it to me so we know who to blame if it turns out not to work in Jenkins.
