### ISSUE TITLE
person and place elements should allow 'name' child similar to org.

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1484]
The org element allows nameLike elements as content, and in order to rationalise the named entity elements it would be useful if the name element was allowed in person and place. (Although when available it makes sense to use persName, placeName, and orgName in some customisations these may not be available.)

This would also benefit the TEI Simple customisation by allowing name instead of persName/placeName/orgName in person/place/org.

**Comment by lb42** [comment]
I think the original rationale for this disparity may have been that an org might use any or all of persName, placeName, or orgName to identify it. Hence it allows model.nameLike. But a person must have a persName, and a place must have a placeName (tho of course either may contain the other, as in "Robert of Gloucester" or "Cummings Castle") . There are lots of things in model.nameLike which really need to be disentangled. For example, a person could plausibly contain any model.nameLike.agent elements but not the other members of model.nameLike.  

If the intention is just to permit name within person, place, or org as an alternative to persName, etc. maybe the answer is toexplicitly provide it as an alternative to idno? A name is a sort of identifier, after all. This will require some revision to org to avoid ambiguity, however.

**Comment by martindholmes** [comment]
I've always assumed persName etc. were syntactic sugar for name type="person", so to me it makes no sense to have any of the syntactic sugar elements available without the name element itself.

**Comment by jamescummings** [comment]
@lb42: Yes, to be clear, my proposal is only to add `<name>` not model.nameLike fully. I'm not sure of the need for complicated alternation with idno in specific (what if my place has a name and an idno?). Can you explain why that is desirable? ...unless I'm misunderstanding you (highly likely).  I was suggesting just adding name to person/place without any class in the alternation group where yes idno resides.  Namely (from place):

````
 <alternate minOccurs="0"
   maxOccurs="unbounded">
   <classRef key="model.noteLike"/>
   <classRef key="model.biblLike"/>
   <elementRef key="idno"/>
   <elementRef key="linkGrp"/>
   <elementRef key="link"/>
<!-- add in: -->
   <elementRef key="name"/>
  </alternate>
````

@martindholmes Indeed that is how I've always explained them.  This change would enable more parallelism between them (though with org still having model.nameLike) which would then make rationalising them easier.

**Comment by lb42** [comment]
Unfortunately just adding  name would make the content model for org ambiguous wouldn't it?. I think we should defer this to a complete revision of the content models rather than simply tinkering.

**Comment by lb42** [comment]
And @martindholmes do you disagree  that there might be cases where a particular flavour of name is required rather than the generic one?

**Comment by jamescummings** [comment]
@lb42 I'm really confused now I am not suggesting adding name to org. It *already* has it! (via nameLike).

I'm just suggesting adding name to org/place which don't currently have it, and adding just name (rather than nameLike) introduces no ambiguity than I can discover.

**Comment by lb42** [comment]
Ah ok I see. Apologies for misunderstanding. I thought you were trying to homogenise the content models. However whether or not we make this change I am not convinced it makes sense to allow anything other than p or ab for theselementse in simple.

**Comment by martindholmes** [comment]
@lb42 I'm not sure I get the point; we're talking about a minor step forward which would help with Simple and would also go some way towards rationalizing and aligning the content models. This doesn't preclude a broader effort to rework them completely, but that's a huge task and not likely to be completed soon. The timeline for Simple is already stretched.

**Comment by jamescummings** [comment]
@lb42 Sure, we need to homogenise the content models (separating things that are specific to places or orgs and dont' appear in people) out in a separate class. I would expect that this would end up with a superset of the current elements (i.e. some added to make it more consistent across the named entities) and maybe some deprecated. However, it doesn't matter if person/place get name individually now and then later get it as part of a class when we reform things.  I think the only question here is "Does having name inside person/place/org in addition to persName/placeName/orgName make sense? And I think we all seem to agree that it does. Whether that is used for simple or not.

**Comment by lb42** [comment]
The intention seems to be to loosen the content model for person and place, so that they can contain generic name in addition to the more specialised child elements they currently do. This makes stupid tagging slightly simpler. Subgroup agreed with very small majority in favour: add name to model.personPart and to model.placePart.

**Comment by jamescummings** [comment]
@tuurma I'm guessing name will have to go in the content model of place directly or I believe adding it to model.placeNamePart (which is a member of model.placeStateLike) would get it in the right place.
