### ISSUE TITLE
Location of ODD validation file for spec development

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1486]
Right now, all our TEI P5/Source files point here for their validation:

http://jenkins.tei-c.org/job/TEIP5/lastSuccessfulBuild/artifact/P5/release/xml/tei/odd/p5.nvdl

However, that currently means that some are invalid, because Syd and I have enacted the change that allows `@validUntil` on `<defaultVal>`. That change shows up on the P5-dev job on Jenkins, but not on the P5 job, unless we run it. There are two options:
1. We build the P5 job whenever a schema-changing edit is made that will affect the P5 source; or 
2. We change the pointers to point here:

http://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/odd/p5.nvdl

I don't know which makes the most sense.

**Comment by hcayless** [comment]
I think dev's validation should depend on the p5-dev nvdl. Building P5 really implies a release.

**Comment by ebeshero** [comment]
Council subgroup agrees with Hugh.
