### ISSUE TITLE
example values for correspAction/@type are inconsistent with the suggested values

### ISSUE THREAD

**Issue by rvdb** [TEIC/TEI#1488]
There's an inconsistency between the list of suggested values for `correspAction/@type` in http://www.tei-c.org/Vault/P5/2.8.0/doc/tei-p5-doc/en/html/ref-correspAction.html#tei_att.type, and the values used in the code examples.

While the documentation suggests "sent", "received", "transmitted", "redirected", and "forwarded", other values ("sentBy", "deliveredTo", "sending", "receiving"), are used in the examples: see http://www.tei-c.org/Vault/P5/2.8.0/doc/tei-p5-doc/en/html/examples-correspAction.html.

**Comment by peterstadler** [comment]
That was addressed (twice) with #1350 and is fixed by now. Current dev branch looks good, see 
http://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/examples-correspAction.html
