### ISSUE TITLE
[jTEI] add support for cross-references to notes

### ISSUE THREAD

**Issue by rvdb** [TEIC/TEI#1490]
The jTEI ODD file describes how cross-references can be made to `<div>`, `<figure>`, and `<table>` elements. Another (as yet unsupported) common target for cross-references are footnotes in `<note>` elements. Support can be added easily by

- modifying the documentation prose for cross-references
- extending the ISO Schematron rule checking for valid cross-reference targets

These changes complement the changes required to the TEI Stylesheets reported in https://github.com/TEIC/Stylesheets/issues/165.

I'll issue a pull request suggesting the necessary changes.

**Comment by hcayless** [comment]
Done
