### ISSUE TITLE
Allow note in rdgGrp

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1492]
It's a bit inconvenient that I can't have notes inside a rdgGrp. For example, I have an apparatus entry:

_an_ iunctis (_cf. Vitr. 10.2.14_) _uel_ adiunctis (_cf. 27.7 et Gel. 20.1.28_)

which I'd like to encode as something like:

``` xml
<rdgGrp type="choice">
  <rdg>iunctis</rdg>
  <note>cf. Vitr. 10.2.14</note>
  <rdg>adiunctis</rdg>
  <note>cf. 27.7 et Gel. 20.1.28</note>
</rdgGrp
```

but I can't because notes aren't allowed in rdgGrps. I think the content model of rdgGrp should permit note (and maybe witDetail too).

**Comment by martindholmes** [comment]
In your example, it looks like simple contiguity is what associates your notes with their referent. Wouldn't you rather put the note inside the `<rdg>`?

**Comment by hcayless** [comment]
I don't like putting apparatus notes in rdg because that says to me the note is part of the reading (which is totally possible) rather than commenting on it.

**Comment by jamescummings** [comment]
I would also have put the note inside the rdg and differentiated types of notes (source vs editorial, whatever) by the type attribute as we are forced to do everywhere else.

**Comment by raffazizzi** [comment]
But the notes refer respectively to the first and second reading, right? Having them in rdgGrp doesn't seem to reflect that. I take your point that mixing editorial notes and notes belonging to a reading is a bad idea, but I'm not convinced by having them float in rdgGrp either.

**Comment by jamescummings** [comment]
In that case I'd have them somewhere outside the rdgGrp and point at the two rdgs in question.

**Comment by hcayless** [comment]
@raffazizzi, just like notes inside an `<app>`, the ones in the example aren't "floating", they're where I want them to be, following the first and second readings respectively. Putting them elsewhere complicates processing—which would be fine if *all* my notes were standoff, but they aren't. @jamescummings, I'm very much opposed to putting things in readings that aren't part of those readings, and I also think you should be able to lay out an apparatus entry the way it's meant to be read, without having to resort to moving information around.

**Comment by martindholmes** [comment]
Is this one of those situations where a digital representation is in tension with the sequence of items in an original print source?

**Comment by hcayless** [comment]
@martindholmes sort of. The work in question is not in print yet and will have its first publication in TEI, but is right now a bunch of Word docs. There's this app entry that conjectures "either *iunctis* (for which compare Vitruvius 10.2.14) or *adiunctis* (compare 27.7 and Gellius 20.1.28)". Since this is a related pair of conjectures, I'd kind of like to group them together, but I don't want to strip the notes out in doing so.

**Comment by hcayless** [comment]
If this ends up being accepted, I'd like to see `<witDetail>` allowed in `<rdgGrp>` too.

**Comment by peterstadler** [comment]
To me, putting a ```<note>``` into some structural unit such as ```*Grp``` or ```list*``` (what have you) more or less comments on this unit, rather than the actual point of text. If you want to comment on the text, use it on the phrase level, i.e. some child element. Hence, my feeling is that these notes belong into ```<rdg>```, not ```<rdgGrp>```

**Comment by lb42** [comment]
Council feels that a note should not go in rdg unless it’s a part of the reading itself. Hugh's proposed solution (relying on sequence) but this is always the case when note is used, e.g. a note in the middle of a paragraph. If it matters, use a pointer. Recommendation: introduce model.noteLike into the content model of rdgGrp.

**Comment by peterstadler** [comment]
Ok, here's my first shot at implementing (simply adding the ```<classRef>``` at the end of the ```<alternate>```): 

```xml
<alternate minOccurs="1" maxOccurs="unbounded">
  <sequence>
    <elementRef key="rdgGrp"/>
    <elementRef key="wit" minOccurs="0"/>
  </sequence>

  <sequence minOccurs="0" maxOccurs="unbounded">
    <sequence minOccurs="0">
      <elementRef key="lem"/>
      <elementRef key="wit" minOccurs="0"/>
    </sequence>

    <sequence>
      <classRef key="model.rdgLike"/>
      <elementRef key="wit" minOccurs="0"/>
    </sequence>
  </sequence>
  
  <classRef key="model.noteLike" minOccurs="0" maxOccurs="unbounded"/>

</alternate>
```

Does that make sense?
