### ISSUE TITLE
Confusing note on modelSequence

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1495]
On http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-modelSequence.html 

> All of the child elements of a modelSequence element are to be processed together, for example in sequence, rather than independently of one another. 

How else might they be processed? In parallel? Out of sequence? We should pick one and mandate it. I vote in the order in which they appear inside modelSequence.

**Comment by lb42** [comment]
I made the same comment. But I was told that we shouldn't constrain implementors. They might decide to do the last one first, or the one with the longest nose, or whatever. The only constraint is that they all have to be acted on, I think, i.e. they are not alternatives.

**Comment by hcayless** [comment]
I think it's very unkind not to constrain implementors. Do we not *want* consistent implementations?

**Comment by lb42** [comment]
Apparently, that's not the view taken by the designers of the processing model spec. But they should speak for themselves!

**Comment by hcayless** [comment]
But if they can be processed in parallel or in any other order, then aren't they independent of one another? I'm still confused.

**Comment by lb42** [comment]
"independent" is probably not the right word here. They mean "as alternatives" I think.

**Comment by hcayless** [comment]
What about
```xml
<p>All of the <gi>model</gi> elements inside a <gi>modelSequence</gi> 
element must be processed. The operations indicated by each <gi>model</gi> 
child are assumed to be independent and may be executed in any order.</p>
```

**Comment by tuurma** [comment]
My understanding is that while `<model>`s in a `<modelSequence>` are independent and may be potentially concurrently processed, the results of that processing need to be linearized in the end and that should follow the ordering of `<model>s` in a `<modelSequence>`

**Comment by hcayless** [comment]
Council agrees. Need to combine the text of @tuurma's and my comments.

**Comment by hcayless** [comment]
@jamescummings is correcting the example, I will expand on the explanatory language.
