### ISSUE TITLE
sanity check on model was: Don't punt on model semantics

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1496]
In http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDPMIP we find:

> Consequently, if there are two or more model elements provided for an elementSpec, and none of them has a predicate or an `<output>` attribute, then an implementation may either choose to regard this as an error, or apply their own algorithm to determine the priorities; the nature of that algorithm (first found, last found, etc.) should form part of the implementation's documentation.

I think it's a mistake to punt to the implementation here. TEI ought to take responsibility for defining the semantics of TEI elements wherever possible. My recommendation would be that the first matching model wins, always.

**Comment by jamescummings** [comment]
This all seems to be the same issue really -- where TEI PM has said it is up to the implementation and you think that we should tighten it and choose one method.  I'm up for making it more specific but can see different arguments for it should be specific one way or another.  There are real problems with the concept of 'first' in some cases (though I agree that these are edge cases).

**Comment by hcayless** [comment]
What are those cases? Because I'm not sure that's true...

**Comment by tuurma** [comment]
Problem of choosing which one is first only arises when chaining ODDs where both contain `<elementSpec>` for a given element and, furthermore, the mode on chained ODD is 'change'. As discussed in #1498 what happens then is that only `model`s from chained ODD survive, thus there is never a problem of determining which one is first.

My recommendation thus (as in #1497) is to clearly formulate 'first one that matches' rule and, as a result of discussion above and in #1498 add a note that `mode='change'` means in fact `replace` in regard to `<model>s`.

**Comment by lb42** [comment]
The meaning of mode=change doesn't change though --  components of the chained elementSpec other than model will behave in the same way as usual i.e. depending on *their* mode (if they have one).

Of course we could mess this all up by deciding to give models a mode attribute.. but I'm not suggesting that just yet

**Comment by jamescummings** [comment]
Council Face to Face in Vienna asks @sydb to write a schematron rule to stop this happening.

**Comment by hcayless** [comment]
@sydb will add a Schematron rule forbidding 2 models with no predicate and no output defined

**Comment by tuurma** [comment]
Does it still need discussion then? #1497 covers selecting one true match for the element so this ticket is left for @sydb's and Schematron magic...

**Comment by hcayless** [comment]
Presumably also models in a modelSequence should not have `@predicate`s and `@output`s because the modelSequence should take care of that? @sydb, if you don't have time to handle this before release branching, I can knock it out.

**Comment by sydb** [comment]
I’m happy to do this, but I am not entirely convinced it is correct. My instinct is that it is, and the sentence “`<modelSequence>`  is provided for the case where a sequence of models is to be processed, functioning as a single unit” certainly implies that. But I could not find this explicitly stated anywhere. And the juxtaposition of the descriptions of `<modelGrp>` and `<modelSequence>` (at the beginning of 22.5.5) sort of gives one pause:

`<modelGrp>` any grouping of model or modelSequence elements with a common output method
`<modelSequence>` any sequence of model or modelSequence elements which is to be processed as a single set of actions

The former explicitly says a common output method; so if the latter was also to imply a common output method (and also a common set of conditions, i.e. predicate), wouldn’t it say that?

My plan is to pop this constraint in (to branch sydb-modelAttrChecks) and issue a pull request, and let someone else be the final arbiter of whether it belongs or not.

**Comment by sydb** [comment]
Done in ff0c4be. Pull request number 195.

**Comment by hcayless** [comment]
Looks like a parent modelSequence should *not* rule our child model `@predicate`s, so I'm reverting that bit.

**Comment by hcayless** [comment]
All green in Jenkins, so closing.

**Comment by tuurma** [comment]
I've just reviewed Syd's PR (even if a bit late) and just for the record, I too think @predicates on models within modelSequence make perfect sense. Many thanks @sydb and @hcayless
