### ISSUE TITLE
Specify how model* combines when an elementSpec is changed

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1498]
Since model lacks any hooks that would permit one model to replace another, we need to specify what happens when an elementSpec with mode="change" and model* children is combined with an existing elementSpec with model* children. Choices are:

1. new model* elements are inserted before existing ones
2. new model* elements are inserted after existing ones
3. new model* elements replace existing ones.

If, as I recommend in #1497, we adopt a rule that processing happens on the first matching model, then 1) would exhibit the most logical behavior, with the new model*s overriding the existing one when they are better matches, but not otherwise.

**Comment by jamescummings** [comment]
Isn't 3 more consistent with what happens already with other bits of ODD?  If I put in a new exemplum, all others are replaced with what I put in.

**Comment by hcayless** [comment]
You're right, models aren't [combinable](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.combinable.html), so changes to the elementSpec involving them just mean they get overwritten.
