### ISSUE TITLE
Misuse of @extent in an example

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1499]
The Galilean example at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COEDADD should either use  @extent to supply a  "descriptive" characterisation of the size of the image (e.g. extent="restOfPage") or use @quantity and @line to indicate it. In context, since there is no other example of how to use @extent, the former seems preferable.

**Comment by martinascholger** [comment]
Changed 2 examples in [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COEDADD](url) and 1 example in [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html](url)

**Comment by martinascholger** [comment]
4d914ef
