### ISSUE TITLE
A plea for behaviourSpec

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1500]
I'm looking again at how behaviours are defined, and it makes me sad. I asked for a better way to define behaviours while the Processing Model was under development, but I think things were already too far progressed for it to change. My vague discomfort at the time has only increased though. I'll try to enumerate the problems ! have with it:
1. Am I correct that if you want to change behaviours (add, delete, modify), your ODD must include `<model>`? So you have to include an element you don't plan to use? Presumably that also means including the tagdocs module?
2. I'm not very happy that the TEI Simple processing model is defined in the main TEI ODD, rather than in Simple. 
3. I'm not very happy that we added paramList to valItem. Presumably it's only ever ok to use this in the valItems in the valList on model? That's a "bad code smell" right there.

Adding a behaviourSpec element would mean it would be easy to add/remove/redefine behaviours in an ODD.  There would be an obvious place for implementors to look for the definition or a behaviour. They could easily disable behaviours they didn't plan to implement in an ODD. 

The only downside I see is that we'd have to add a step in ODD compilation that built the value list for `@behaviour` from the set of available behaviourSpecs. I don't think that would be horribly difficult.

**Comment by jamescummings** [comment]
1) I'm confused by what you say here, your ODD doesn't have to include model into your customisation, the ODD itself needs to have models in it.  I'm probably just misunderstanding.
2) You are right that the TEI Simple implementation of the processing model should be defined in the TEI Simple ODD not in the model Spec.  Currently the behaviours are listed in the model element because they are a customisation of the behaviour attribute. Are you suggesting that main TEI should provide no suggestions as to values for the behaviour attribute?
3) At the moment the only use we have for it is for use in the behaviour attribute...  I'm not against a behaviourSpec though.

**Comment by hcayless** [comment]
Re `#1`, I mean if you wanted to add or redefine a behaviour, say `standoff(content)`. Or change the number of parameters an existing one takes...How would I do this without including model?

**Comment by jamescummings** [comment]
I think we're talking at cross purposes here. If you had your behaviourSpec availble in ODD then you'd change that without including model as an element valid in your document instance. I agree with the idea of behaviourSpec.

**Comment by tuurma** [comment]
What kind of timeline do we have for this? I don't think this necessarily needs to be addressed before next release.

**Comment by tuurma** [comment]
I remember we did discuss it during previous telco, this is a reminder to dig out any notes that might've been taken and put them here.

**Comment by ebeshero** [comment]
@hcayless I wonder if your thoughts on this have changed with the recent atop group activity?

**Comment by hcayless** [comment]
Not really, but I also wonder whether this ship has sailed. I still regard it as a fundamental flaw in the Processing Model, but I worry that changing the spec at this point might break, e.g. TEI Publisher. At this point, it's just one more thing I'm sad about, but I don't use the Processing Model anyway, so maybe we should just close it.

**Comment by tuurma** [comment]
@hcayless I would suggest indeed we close this ticket. Meanwhile we have an extension mechanism in TEI Publisher for specifying new behaviours, cf. https://teipublisher.com/exist/apps/tei-publisher/doc/documentation.xml?odd=docbook&view=div#pb-behaviour which is something that could be perhaps backported into TEI if Council agrees.
