### ISSUE TITLE
Cannot generate valid DTD within oXygen

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1501]
The introduction of pure ODD content models made necessary an additional step in the processing of an ODD to generate DTD. The TEI P5 Makefile includes this step (it consists basically of generating and then using a different version of the p5subset.xml file, imaginatively named p5subsetDoctored.xml) but the ant task used by oXygen apparently does not. The consequence is that almost any DTD generated within Oxygen will be flagged as erroneous, with missing parentheses in its content models. Someone who understands the oXygen framework better than me needs to modify the ANT task, I think.

**Comment by peterstadler** [comment]
May I suggest that we remove the extra fiddle from the Makefile and put generally into some ANT task? That way it should be picked up by our build process as well as some transformation started within oXygen – or am I missing something?

**Comment by hcayless** [comment]
Should be fixed with TEIC/Stylesheets@96a82d6232b731496e100d7badee801440136f0e
