### ISSUE TITLE
<desc> and remark in TEI Guidelines

### ISSUE THREAD

**Issue by laurannebp** [TEIC/TEI#1502]
Seems to me that this note, regarding the `<desc>` element, is maybe deprecated

> TEI convention requires that this be expressed as a finite clause, begining with an active verb.

I think it's often the case when it goes with graphic elements (like in `<facsimile>`), or in documentation but not all the time, like in many example in the guidelines here : [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-desc.html](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-desc.html)

```
<vocal who="#mar">
<desc>meows</desc>
</vocal>
```
or

```
<state type="nationality"
 notBefore="2002-01-15">
 <label>Nationality</label>
 <desc>American citizen from 15 January 2002.</desc>
</state>
```

Furthermore, the description (the `<desc>` of the `<desc>` ....) links to the usage regarding documentation. Maybe the definition needs a little improvement to be less specific, like "defines or describes the object documented by its parent element". It's just an idea. 

(Sorry for the frenglish and the horrible syntax)

**Comment by lb42** [comment]
The note you quote is indeed a bit out of date : it comes from a time when only specification elements (&lt;elementDesc> vel sim) contained &lt;desc>. When we expanded its usage beyond that we forgot to review the documentation. Your suggested rewording seems reasonable to me.

**Comment by lb42** [comment]
Revised wording accordingly
