### ISSUE TITLE
Broken pointer to #DTYPES

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1503]
In several places, there are pointers to this id: `DTYPES`.

It doesn't currently exist in the Guidelines; one result of this can be seen here:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-datatype.html

I believe these should be pointing here:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TD-datatypes

in other words, to `TD-datatypes`, but I think Lou should probably confirm that.

**Comment by lb42** [comment]
Mystifying. In fact they should be pointing to a section in ST which unaccountably got a new id at some point in the past. I've corrected its ID back to "DTYPES" so links should now all work. Thanks for noticing and reporting this !

**Comment by martindholmes** [comment]
The id you changed had a pointer pointing to it as well, so I changed that pointer in commit bed29c3..280e6ea.

**Comment by lb42** [comment]
Thanks Martin. You beat me to it!
