### ISSUE TITLE
Typo in FM1 - Martina Scholger

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1507]
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/FM1.html

Has: 

2002–2007: Laurent Romary (Inria / CNRS / Max Planck Digital Library)
2008–2009, 2012–2015: Paul Schaffner (University of Michigan)
2016–2017: Marina Scholger
2003–2007: Susan Schreibman (University of Maryland)
2008–2009: David Sewell (University of Virginia)

Could I point out that @martinascholger's name has a 't' in it, and that she has an institutional affiliation?

**Comment by emylonas** [comment]
well, if you are looking at the list, there is no year for Stefan

Stefan Majewski (Austian National Library)

Also, the last few f2f meetings aren't in the list.

**Comment by ebeshero** [comment]
And further down on the page, in the "Character Set Workgroup" section, David Birnbaum is listed as from "Pittsburgh University"--that should be corrected to University of Pittsburgh.

**Comment by ebeshero** [comment]
Repaired lots of typos with https://github.com/TEIC/TEI/commit/d4c51b083a45c0ceab5e71ef771f21be29223995
