### ISSUE TITLE
Make orth member of att.notated

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1510]
Orthographic representations in a dictionary may be expressed in a variety of ways, especially when one is using a transliteration system. It would be very useful to have the @notation attribute to indicate which transliteration system has been used, but also, depending on editorial practices in the dictionary, to indicate specific methods of representing the orthographic forms (accented/not accented in Arabic, level of kanji use in Japanese, etc.). One of the issues here is also to keep xml:lang light in order to facilitate unified search for the same language.

**Comment by iljackb** [comment]
Examples of such use are as follows:

i) Japanese:
`<entry xml:id="taxi" xml:lang="jpn">
	<form type="lemma">
		<orth type="transliterated" notation="rōmaji">takushī</orth>
		<orth notation="katakana">タクシー</orth>
		<pron notation="ipa">takushi:</pron>
	</form>
....
</entry>`

2) Hebrew: (example applies also to parallel Arabic conventions)
         `<entry xml:id="courage-heb" xml:lang="heb">                 
            <form type="lemma">
               <orth notation="menukad">אֹמֶץ</orth>
               <orth notation="male">אומץ</orth>
               <pron notation="ipa">ˈomet͜s</pron>
            </form>
          ...
         </entry> `

**Comment by martindholmes** [comment]
Nice examples, although I think the `@xml:lang` attribute on the first example should be "ja" (see http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), and "he" on the second.

**Comment by iljackb** [comment]
> Nice examples, although I think the @xml:lang attribute on the first example should be "ja" (see http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), and "he" on the second.

Thanks, changes made.

(_Though the ones I used are just from different serialization of the ISO 639-2/3 codes_)

**Comment by ebeshero** [comment]
@iljackb Thanks for the very helpful examples for the Guidelines! That's a good point about your use of a different ISO serialization pointing to alternate language codes--it's hard to know which to use. I had a look at our P5 recommendations for `@xml:lang` here: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.html and they're pointing to the www.iana.org site which does simplify and standardize things for us--so our examples in the Guidelines should be consistent in pointing to that set.

**Comment by martindholmes** [comment]
This is the relevant section of the Guidelines on language identification:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CH.html#CHSH

and it cites BCP 47, which is very clear on this issue: where a two-character code exists, it should always be used in preference to a three-character code; this is precisely in order to avoid the confusion that arises due to the three-character codes introduced in ISO 639. The IANA Language Subtag Registry is the bible in this respect. :-)

**Comment by laurentromary** [comment]
I see it is not implemented yet and we need it! :-} While doing this, do not forget to add `<hyph>`, `<stress>` and `<syll>`. This may prevent another ticket on the same subject. Thanks!

**Comment by duncdrum** [comment]
I don't quite see what ``@notation`` would offer that is not covered by ``@xml:lang`` and ``<langUsage>:``
```xml
<language ident="zh-Latn-alalc97">pinyin transliteration of Chinese characters without tonal diacrits</language>
```

Transliteration seem well covered within the spec, with further room for customisation via the prose in the ``<profileDesc>``

**Comment by laurentromary** [comment]
Typically to avoid overloading `@xml:lang` like in your example and maintain the possibility to search for language samples of a given language uniformly. What you write is not wrong from the point of view of BCP 47 but may not be the editorial choice of all projects.

**Comment by duncdrum** [comment]
How do IANA lang tags prevent uniform search though? You can both have a joined search of all lang variants(zh, ja, en, …), or of specific ones (based on e.g. unicode ranges) where that makes more sense.

**Comment by laurentromary** [comment]
I meant: I would avoid combining language sub tags with transliteration notations. This is why we have a `@notation` attribute. Again, a matter of editorial preference. Remember that this ticket os waiting for implementation (and this will not impact on the way you work, just offer more expressive possibilities). I was just reminding 3 elements which could be batch-added to att.notated by the same token.

**Comment by iljackb** [comment]
@duncdrum also, there are other features such as ISO geo tags that may need to be included in @xml:lang which would become messy if you needed to include both the script info and the geo info in the same tag. Specifying stuff like this in the header is not appropriate nor desirable for all cases. @notation is specifically used to specify notation in <pron> and the use of it to specify orthographic scripts is the exact same concept.

**Comment by sydb** [comment]
1) TEI has already decided to implement this, Council just hasn’t gotten around to it yet. I see no reason why it would not be in the next release (due out in Nov, I think).

2) But to be fair, @laurentromary, TEI is an *interchange* format, not an internal-use-in-my-project format, and my instinct is that it whatever you do internally, it is perfectly reasonable to use `@xml:lang` as it was intended for interchange. (It is, after all, the IETF’s best practice.) Seems to me it is not particularly difficult to search for a given language (`starts-with( $lang, 'zh' )`) or script (`contains( $lang, '-Latn' )`).

**Comment by laurentromary** [comment]
1.: probably not the place to debate here, but I would consider that a simplified and systematic `@xml:lang` is more interchangeable
2.: exactly the kind of extra hurdles I would avoid linguists to have to acquire right from the onset

So yes, let's have this implemented.

**Comment by scstanley7** [comment]
Hi all, I am going to implement the `<orth>` portion of this, but I'm going to leave `<hyph>`, `<stress>` and `<syll>` for the time being (referenced in [a comment above](https://github.com/TEIC/TEI/issues/1510#issuecomment-331879152). They were requested after the ticket was marked go, so we never got a chance to discuss. I'd rather not push my luck so close to a release! It would be nice to get some examples for those as well. :) 

I will open a separate ticket that right now, so that we can make those changes.
