### ISSUE TITLE
Italics example not italicized

### ISSUE THREAD

**Issue by davidfarmer** [TEIC/TEI#1511]
On this page:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COHQHEG

the example beginning

    A pretty common case, I believe; in all vehement debatings.

is supposed to contain italicized words.  The source marks them as spans with class "it",
but there does not seem to be any CSS for that class.  So those words are not italicized
(but they are italicized in the following paragraph, explaining the different reasons for
using italics).

Checked in Firefox and Safari on a MacBook Pro.

**Comment by martindholmes** [comment]
Found and fixed in commit 171b237..06e5509. The problem was that they were tagged with @rend="it" instead of @rend="italic".

**Comment by davidfarmer** [comment]
Thanks.  That was fast!

**Comment by ebeshero** [comment]
Yep--sometimes we can process these tickets quickly, but we don't always see all the little errors in the Guidelines and their examples, so we rely on the community to poke us sometimes! :-)

**Comment by martindholmes** [comment]
Evidence of fix:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/CO.html#COHQHEG
