### ISSUE TITLE
Adapt <etym> to allow for encoding of typed and complex etymological processes: (i) add to att.typed class; (ii) allow recursion;

### ISSUE THREAD

**Issue by iljackb** [TEIC/TEI#1512]
(i) add to att.typed class;
 In any analysis or representation of the etymology of a lexical item, it is normal and necessary practice to describe this in terms of etymological processes. The <etym> element currently lacks any practical means of labeling this information, thus a natural solution for this would be using `@type` so that users may have the means to make typological distinctions in etymology, analogously to the way it is done in the synchronic section of an entry, e.g. `<form type="lemma">`.  Typical types of etymological processes that can occur on one or more lexical levels are: borrowing, inheritance (_from "parent language"_), metaphor, metonymy, compounding, various phonological, morpho-syntactic, processes as desired by the encoder. A simple example is as follows from a French entry for the loanword "week-end":
```xml
    <etym type="borrowing">
      <lbl>source:</lbl> <lang>English</lang>
      <cit type="etymon" xml:lang="en">
        <oRef>weekend</oRef>
      </cit>
    </etym>
```
(ii) allow recursion of `<etym>`;
Given that etymological processes can co-occur with one another, and that the occurence of one process may provide the necessary basis or circumstance for another to occur, it should be possible to encode such interdependent relationships recursively within the TEI. An example of this is from an entry for the German compound 'Handschuh', meaning 'glove', which is composed of the German cognates of the English 'hand' and 'shoe' ('Hand'+'Schuh'). The process of word formation is compounding. Additionally, in this etymology, the use of 'shoe' is metaphorical since it involves a change in domain from FOOT to HAND (see: Lakoff and Johnson, 1980; Lakoff, 1987; Lakoff, 1993). The `<etym type="metaphor">` is nested within the `<etym type="compounding">` due to the fact that it is a sub-process which occured as a part of the larger process of lexical innovation in the formation of the compound word form 'Handschuh'.
```xml
    <etym type="compounding">
      <cit type="etymon" xml:lang="de">
        <oRef>Hand</oRef>
        <pRef notation="ipa">ˈhant</pRef>
        <gloss>hand</gloss>
      </cit>
      <etym type="metaphor">
        <cit type="etymon">
          <oRef>Schuh</oRef>
          <pRef notation="ipa">ʃuː</pRef>
          <gloss>shoe</gloss>
        </cit>
      </etym>
    </etym>
```
Note: These examples show the use of `<oRef>` and `<pRef>` being placed inside `<cit>` to contain etymological forms, which of course is not established practice. This usage is described as part of a larger effort to overhaul and refine the markup of etymology in TEI. (see the working draft of the paper here:  https://hal.inria.fr/hal-01296498 )

**Comment by raffazizzi** [comment]
F2F subgroup: these requests sound reasonable and we suggest to green light.

**Comment by laurentromary** [comment]
I don't see this one implemented in the last release. Could someone take care to it?

**Comment by hcayless** [comment]
I've pushed the suggested changes. I modified the examples above so that they don't use not-yet-valid oRef and pRef in cit. Will close if Jenkins is happy.
