### ISSUE TITLE
Guidelines chapter 2.2.4: additional example with link to published resource?

### ISSUE THREAD

**Issue by hennyu** [TEIC/TEI#1513]
Currently, the examples for publication statements in the Guidelines do not include a case where a URI is given for a published resource, indicating where the resource is published on the Web, e.g.
`<pubPlace>
     <ref target="https://raw.githubusercontent.com/cligs/textbox/master/es/novela-hispanoamericana/tei/nl0002.xml">nl0002</ref>
</pubPlace>`
or 
`<pubPlace>
       <ptr type="purl" target="http://diglib.hab.de/[object]/start.htm"/>
   </pubPlace>`
I suppose that there are many cases where someone wants to give a link to the published file, so it would be nice to have something like this or similar in the Guidelines in addition to the more traditional publication statements.

**Comment by hcayless** [comment]
Wouldn't this normally be taken care of by a link in the sourceDesc? Can you give us a more fully worked out example?

**Comment by ebeshero** [comment]
Permit model.ptrLike as member of publicationStmt.part.detail. Need examples. (Hacks include address/ addrLine and idno — these are not ideal)
