### ISSUE TITLE
Expand att.notated to all elements commonly used in linguistic markup: <quote>, <s>, <cl>, <phr>, <w>, <m>, <c>, <seg>

### ISSUE THREAD

**Issue by iljackb** [TEIC/TEI#1514]
Given that a major use of the TEI is for linguistic data, and currently, there are inconsistancies in the ability to specify the type of notation used. This proposal is related to work already begun in Issue (https://github.com/TEIC/TEI/issues/545) leading to the creation of the att.notated class to which currently (`<formula>`,`<oRef>`,`<pRef>`,`<pron>`,`<pVar>` and `<u>` are members). Issue (https://github.com/TEIC/TEI/issues/1437)  added <u> to the aformentioned group, I propose to allow the `@notation` attribute to occur within the following elements: `<quote>, <s>, <cl>, <phr>, <w>, <m>, <c>, and <seg>`

In most of the major elements in which users are likely to encode non-orthographic, the only option for encoding where there is a phonetic notation being used is to include it within `@xml:lang` as per RFC 3066. However, this is not consistent with the widely accepted use of `@notation` on such prototypical elements as `<pron>` within the TEI; in the case in which a user has a dictionary in which some elements have `@notation`, and some that don't, this would mean that they would have to use different versions of a language tag, to tag the same language in the same script.
  e.g. (in a single dictionary entry)

```
 <form type="lemma">
    <pron xml:lang="mix" notation="ipa">jàʧí</pron>
  </form>
```

```
  <cit type="example">
    <quote xml:lang="mix-fonipa">jàʧí ŋk̬àà tijùtsá</quote>
  </cit>
```

Thus, since it is very common to have examples of a form in contextual usage from a phonetically transcribed utterance, we should be able to have the following on `<quote>`:

```
  <cit type="example">
    <quote notation="ipa">jàʧí ŋk̬àà tijùtsá</quote>
  </cit>
```

Additionally, the guidelines define `<w>` as follows but do not allow for any way to specify the notation used (other than using the RFC @xml:lang method) [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-w.html]

>  (word) represents a grammatical (not necessarily orthographic) word" they do not provide a means to specify when the contained text is or isn't orthographic or to specify what the notation used is.

So we should be able to have:   

```
<w type="verb" notation="ipa" lemma="hit"
 lemmaRef="http://www.example.com/lexicon/hitvb.xml">hɪɾ<m notation="ipa" type="suffix">ŋ</m>
</w>
```

Also, given that a user may conceivably wish to specify notation at a higher level such as on: `<s>` `<cl>` or `<phr>` , an example of the former:
`<s notation="ipa">hi hɪt̚ mi</s>`

Or it may be needed on the lowest level, e.g. `<c>`, the following is a common case in which `@notation` is needed:
`<note>"sch" pronounced as <c notation="ipa">ʃ</c></note>
`

Finally, given that in the field of Linguistics some of the aforementioned terms from 'analysis' (namely `<s>, <w>`, & `<m>`) are considered theoretically loaded and therefore are not used by some (myself included), and that the alternative commonly used is the neutral `<seg>`, it would therefore be useful to allow `@notation` to occur on this element as well that would mirror the uses for the former items.
e.g.
`<seg type="lexItem" notation="ipa" xml:lang="mix">jàʧí</seg>`

**Comment by bansp** [comment]
Seems very coherent to me. 
(BTW: your `<pron>` example looks incomplete, maybe the XML tag isn't escaped)

**Comment by iljackb** [comment]
> Seems very coherent to me. 
(BTW: your <pron> example looks incomplete, maybe the XML tag isn't escaped)

Ahh, thanks Piotr. I've fixed it

**Comment by ebeshero** [comment]
F2F subgroup thinks this should be green!

**Comment by peterstadler** [comment]
See also #1510

**Comment by raffazizzi** [comment]
F2F subgroup reminds @alex-bia to implement this soon, as well as #1510

**Comment by martinascholger** [comment]
Implemented att.notated to elements for linguistic markup, commit b96e1b1
