### ISSUE TITLE
Add glyphList element for documents in multiple scripts

### ISSUE THREAD

**Issue by D-K-E** [TEIC/TEI#1518]
Under the charDecl it would be very handy to add something like glyphList for organizing documents with multiple scripts such as Rosetta Stone, or Aramaic papyri from egypt with demotic signitures, some of the royal inscriptions of the achaemenid empire, etc. This would allow encoder to organize the glyphs for different scripts under their respective glyphList.

**Comment by martindholmes** [comment]
You can have multiple charDecls, each with its own desc. Would that do the job?

**Comment by D-K-E** [comment]
Though I am not really comfortable with having multiple character declarations in the encoding. Your suggestion would solve the problem of organizing different scripts, and thus would answer my question. I shall proceed the way you suggested.
