### ISSUE TITLE
Sort out TEI@version please

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1519]
The note on TEI@version says "The major version number is historically prefixed by a P (for Proposal), and is distinct from the version number used for individual releases of the Guidelines, as used by (for example) the source of the <schemaSpec> element. The current version is P5."  This provokes the following questions:
- what does "historically prefixed" mean? If it means that the version number used to be prefixed by a P, but is no longer, why does it say "the current version is P5"?
- why in any case do both examples have @version="5.0" (rather than either "5" or "P5")?
- why do we have two @version numbers in different formats?

If the intent is just to say that this document conforms to (some version of) TEI P5, this seems to overlap with the desire to say e.g. this document conforms to (some version of) TEI Simple. We should settle on some sensible way of doing that, and retire this vague attribute. Or at least clarify its use better in the note!

**Comment by raffazizzi** [comment]
F2F subgroup argues that P5 is, at this point, a code name rather than a major version name. 
So we suggests to do this:

1) drop the word "major" from the description
2) remove the confusing remark
3) change example to a real version such as "2.9.1".

**Comment by hcayless** [comment]
Looking at this to see if it can quickly be resolved pre-release 3.3.0, and I find it horribly confusing. I'm not really sure what `@version` is supposed to do. "P5" isn't really the major version number as we do versions. This seems like one of those things that might have seemed like a good idea at the outset of the P5 era, but really doesn't do anything. Doesn't the schema tell you what version of the TEI the document works with? What use is it? Should we think about deprecating `TEI/@version`?

**Comment by martindholmes** [comment]
I want it there as a constant reminder that we should be working on P6. :-)

**Comment by duncdrum** [comment]
@raffazizzi makes sense. i would change the note to explain how the decision to name the current era `P5` came about and start thinking about a better name then `P6` for the next era.

**Comment by lb42** [comment]
I suggest

(a) revise the note as follows "Versions of the Guidelines  have long been informally referred to by a name made up of the letter P (for Proposal) followed by a digit. The current release is one of the many releases of the fifth major version of the Guidelines, known as P5. This attribute may be used to associate a TEI document with a specific release of the P5 Guidelines, in the absence of a more precise association provided by the  @source attribute on the associated schemaSpec."

(b) Make the wording of the desc for this attribute consistent on TEI and teiCorpus

(c) change all examples to use kosher release numbers

**Comment by hcayless** [comment]
I don't think we should use "major version" to describe P5, since that's what we call the first number in "3.3.0" (<major version>.<minor version>.<patch>). Would "series" work?

Am I understanding right that `@version` would become something like "5.3.3.0"? Or should we follow @raffazizzi's suggestion and just use the version number as we generally use it? If we ever attain the mythical P6, will we restart our version numbers at 0.1.0 or just keep them going?

**Comment by hcayless** [comment]
I should say that, other than the phrase "major version", I like @lb42's suggestion.

**Comment by lb42** [comment]
OK, how about "major edition" ? I don't think "series" works. 
I think we should use the version number as currently: indeed, that;s what the datatype for the attribute requires: 3 digits.
What happens when/if there is a P6, I'd consider to be a P6 question, but in principal, it should probably restart at 0.1.1 . Assuming we even have version control considerations then.

**Comment by hcayless** [comment]
Yeah, "major edition" or maybe "major revision" works better. If there are no objections, I will make this so later today, so we can close this issue.
