### ISSUE TITLE
otiose remarks on abbr

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1520]
"The &lt;abbr> tag is not required; if appropriate, the encoder may transcribe abbreviations in the source text silently, without tagging them. If abbreviations are not transcribed directly but expanded silently, then the TEI header should so indicate."
1. this seems to be saying that you dont _have_ to tag abbreviations with abbr, which is true, but could equally well be said of almost any phrase level element, e.g. you don't _have_ to tag foreign words or highlights etc. So the first part of this remark is redundant.
2. How exactly should the TEI header "so indicate"? Shouldnt expanded abbreviations be tagged with &lt;expan> ? 

I suggest we remove these remarks.

**Comment by raffazizzi** [comment]
F2F: We agree to drop this remark and a new remark should be added to `<expan>`:

"If abbreviations are expanded silently, this should be indicated in the TEI header, under `<encodingDesc>`"

Probably a similar sentence should be added to the Guidelines CO 3.5.5

**Comment by jamescummings** [comment]
You mean `<editorialDecl>` not `<encodingDesc>`

**Comment by jamescummings** [comment]
Council subgroup suggests to delete first sentence and replace the second sentence with some more clarifying prose. This could also be changed on 'expan' as well.

**Comment by sydb** [comment]
Done at 136088a. I don’t claim the result is perfect, but it’s much better.

I did not notice @jamescummings’s last comment (about `<expan>`) until after I had checked this in; so I will open another ticket for that.
