### ISSUE TITLE
actor should be member of att.canonical

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1521]
The element actor "should be used only to mark the name of the actor as given in the source". Fair enough, but how do we associate it with a &lt;person> describing the actor in question? Since this is a specialised kind of &lt;persName> it would make good  sense to supply a @ref or @key ... but actor is not a member of att.canonical so we can't

**Comment by peterstadler** [comment]
Well, in the remark it says:

> This element should be used only to mark the name of the actor as given in the source. Chapter 13 Names, Dates, People, and Places discusses ways of marking the components of names, and also of associating names with biographical information about a person.

Hence, I believe that ```<actor>``` is *not*  a specialised kind of ```<persName>``` but current best practice would be to encode:

```xml
<actor><persName>Mr. Henry Irving</persName></actor>
```

**Comment by ebeshero** [comment]
@peterstadler That seems kind of unnecessarily bloated to me. Is there any reason *not* to assign `<actor>` to att.canonical and rewrite the prose of the Guidelines accordingly?

**Comment by martindholmes** [comment]
I think if Peter is right, then some (perhaps all) of the existing examples need to be rewritten to clarify this. The sheer number of examples of `<actor>` without any additional encoding inside them suggest that the original intent was for `<actor>` to function like `<name>` or `<persName>`, and the structure of `<castItem>` looks very much like that of `<respStmt>` to me.

**Comment by lb42** [comment]
I made this suggestion precisely because I do think of &lt;actor> as a specialisation of &lt;persName, equivalent to &lt:persName role="actor">. I dont see any text in the GL to the contrary.  A persuasive case against this would be to point to an example where &lt;actor might plausibly contain something which was *not* a name. Otherwise Peter's suggestion seems like unnecessary tag-bloat to me too.

**Comment by peterstadler** [comment]
I'm not feeling strong about that, I was just trying to point out that the current Guidelines – for some reason – explicitly refer to chapter 13 for Lou's proposal. Actually, I was hoping for some voice of history to explain that remark ;)

**Comment by lb42** [comment]
The chap13 passage quoted above to my mind supports my proposal which is precisely to make use of the mechanisms discussed in that chapter for "associating names with biographical information about a person" to wit  @ref or @key ...

**Comment by ebeshero** [comment]
F2F subgroup agrees with @lb42 . `<actor>` should be a member of att.canonical .

**Comment by lb42** [comment]
Done.
