### ISSUE TITLE
otiose remarks on argument

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1522]
"Often contains either a list or a paragraph" is really not very helpful, though undeniably true. If not deleted entirely, wouldn't be better to provide a note suggesting that an argument containing a sequence of disjointed words or phrases (like that in the example) might be better tagged as a list or a paragraph of terms rather than (as in the example) as a single paragraph ?

**Comment by hcayless** [comment]
Group at F2F thinks just get rid of the note.

**Comment by hcayless** [comment]
Resolved with 8c2f895  (which referenced the wrong ticket)
