### ISSUE TITLE
is an illustrator an  <editor> ?

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1523]
The second (of 2) example in the spec for &lt;editor> is

```
<editor role="illustrator">John Tenniel</editor>
```

This seems a bit weird. Why isn't it 

```
<respStmt>
<resp>illustrator</resp>
<name>John Tenniel</name>
</respStmt>
```

?

**Comment by ebeshero** [comment]
Note: the `<editor type="illustrator">` example pointing to John Tenniel has been around at least since P2.

**Comment by ebeshero** [comment]
Council subgroup finds that the `@role` on `<editor>` is the question. Should we change? An illustrator is only an editor when it's a comic book and images are the main vehicle of writing. Note: no examples of editor at all in 3.11.2.2. Recommendation: Needs discussion, and examples.

**Comment by peterstadler** [comment]
Please note that the French version example still uses an illustrator example!

**Comment by ebeshero** [comment]
Reopening because we also want to add some examples to 3.11.2.2.

**Comment by duncdrum** [comment]
``<editor role="illustrator">`` doesn't just apply to comic books. East Asian woodblocks illustrators  can figure more prominently then authors on title pages, since their work was the defining feature of a new edition.  I d suggest to keep the old example around for cases, such as these, where council seems to agree that it applies.

**Comment by peterstadler** [comment]
I think, @ebeshero's comment was a little bit misleading in that we do _not_ think an illustrator as editor to be problematic but only the example in the Guidelines. The examples should best reflect the most common usage first – but in fact there is no 'simple' example of a 'standard' editor anywhere in the Guidelines.
