### ISSUE TITLE
Schematron inside ODD files should be more precisely specified

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1524]
In this message to the Council list:

http://lists.tei-c.org/pipermail/tei-council/2016/023379.html

Syd points out that one of the problems with handling Schematron reliably in the processing of ODD files is that when it's embedded in various contexts, 
1. there is no requirement for `<sch:rule>`, so sometimes it's provided (e.g. in the spec for `<list>`) and sometimes it's not (in the spec for `<relatedItem>`).
2. there is no requirement for `@context`, so that has to be derived mechanically -- not difficult, but a possible source of ambiguity.

I would like to suggest that:
1. `<sch:rule>` be added to every existing piece of Schematron in the Guidelines, with a clear `@context`;
2. The tagdocs be updated to make this an explicit recommendation; and
3. following a standard deprecation period and process, the use of  `<sch:rule>` and `@context` be made mandatory.

**Comment by ebeshero** [comment]
@sydb opposes this ticket having reconsidered it.
