### ISSUE TITLE
Missing documentation for att.canonical

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1525]
Looking for precise information concerning the use of @ref and @key I had to  search for a while until I came across: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDATTS
I suggest this page be referenced from the documentation for att.canonical (namely: http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-att.canonical.html). 
In this page by the way, there is a very useless reference "As discussed elsewhere": could this be linked to the appropriate place?

**Comment by hcayless** [comment]
Presumably "elsewhere" is here: <http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONARS>. Agreed that the reference should be made explicit with a link.

**Comment by hcayless** [comment]
Resolved in https://github.com/TEIC/TEI/commit/38cc05261ab4298105a2e5ebd8aabd8e524caa99
