### ISSUE TITLE
examples need to be split up

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1526]
Per [Philipp Vanscheidt’s post to TEI-L](https://listserv.brown.edu/?A2=ind1610&L=TEI-L&D=0&P=31913) (and subsequent discussion) several examples show multiple occurrences of an element which can occur a maximum of once. E.g., several `<additions>` or `<musicNotation>` elements in a row in a single `<egXML>`. These should be broken up into multiple `<egXML>`s.

I see two tasks here. The first is for someone to go in and fix the two we already know about. THIS IS WHAT THIS TICKET IS ABOUT.

The second is to write software that a) reads in the Guidelines (or perhaps, the schema generated therefrom), and generate a list of elements that may occur a maximum of once in a particular context, and b) searches for any case of two or more of any of those elements within an `<egXML>` that either are in that context or have no context. This might be a good idea, but this ticket does **not** cover it. If we ever do create a ticket for it, it may well belong in the Stylesheets repo.

**Comment by ebeshero** [comment]
How are such elements signaled in the Guidelines? The part 2 of this sounds like a task for the Stylesheets group that might not be terribly difficult. I imagine that the most consistent way these elements are signaled would be in the schema, not the prose. Is there any reason not to create a ticket for this part 2 on the Stylesheets repo?

**Comment by ebeshero** [comment]
This also looks like a good ticket to be sure to complete before the next release...

**Comment by lb42** [comment]
I've fixed the example in #mspham and added a comment to the prose for those who fail to read the specification carefully

**Comment by lb42** [comment]
Ditto for the musicNotation example. It would be nice to add an example with multiple notations however, so leaving this ticket open.

**Comment by ebeshero** [comment]
Well, I guess I didn't do this ticket fast enough! Thanks, Lou. Unassigning myself and recommending @raffazizzi !

**Comment by lb42** [comment]
Sorry Elisa, I thought you were volunteering for the second part of the ticket.

**Comment by ebeshero** [comment]
No worries--looked like an easy one, and glad you got it done quickly! And I'm happy to post the second part as a ticket on Stylesheets--shall I just do that? I think if we want multiple musicNotations, Raff will likely have good material.

**Comment by ebeshero** [comment]
Opened a new ticket on Stylesheets repo: https://github.com/TEIC/Stylesheets/issues/181

**Comment by ebeshero** [comment]
Note to all on this ticket and @hcayless , @jamescummings, and @tuurma : I'm setting the Guidelines 3.1.0 milestone on this ONLY for the first half of the ticket: Lou corrected a couple of known cases in the Guidelines where the egXML shows multiple occurrences of an element only really permitted once. 

The ticket is unfinished, however, because we need to work on the second half of the ticket and systematically locate more cases like the ones just corrected for this release.

**Comment by hcayless** [comment]
Removing from milestone because unfinished.

**Comment by lb42** [comment]
I am closing this since the second part, which is all that was opoen,  has been moved to the stylesheets repo.
