### ISSUE TITLE
Attribute classes in 'tei' when they shouldn't be?

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1528]
While debugging an ODD-chaining issue, I noticed that att.tableDecoration is in the 'tei' module instead of the 'figures' module where the elements it provides attributes for live. 
1. Would changing its module break anything?
2. If not, I notice it's not alone in being placed in 'tei' when it might have a better home. We might want to look through the attribute classes and make sure they live where they're supposed to.

**Comment by martindholmes** [comment]
Changing its module would break any odd which explicitly references its module, presumably:

~~~~~
<classSpec ident="att.tableDecoration" module="tei" type="atts" mode="delete"/>
~~~~~

Unless the Stylesheets ignore `@module`, in which case why does it have `@module`?

**Comment by lb42** [comment]
A good question. I think sometimes they do, and sometimes they don't. For example, an &lt;elementRef may not reference a module, but an &lt;elementSpec must. And it must be correct too.

**Comment by hcayless** [comment]
`make test` runs fine if I make the change. You probably wouldn't bother referencing it if you were going to remove tables, as removing row and cell would result in the automatic removal of att.tableDecoration (only they reference it).

It doesn't seem to make any difference if `@module` is not present on classSpec (if you're altering an existing spec of course). Modules aren't namespaces, so the Stylesheets can still figure out where classSpecs are supposed to be from their `@ident`s.

**Comment by lb42** [comment]
In principle, if  the members of a class are found in more than one module, or if they are all provided by the core module, then the class should be defined in the tei module. If all  the members of the class are defined by a single module, and other elements are unlikely to want to join the class, there's no reason not to put the class declaration in that module too.

**Comment by raffazizzi** [comment]
F2F gorup: Would moving classes to different modules break backwards compatibility with existing ODDs that change classes?
Also what's the harm of having classes defined in the tei module even if they are not used (ie because the element using them is not included)?

**Comment by ebeshero** [comment]
@sydb  will review lists of attributes in the TEI module, and note which are associated with which modules. Write a list of attributes to be moved to classes

**Comment by raffazizzi** [comment]
F2F: Would it be possible to just move this class and close this ticket WHILE we do proper inventory of classes in the tei module?

**Comment by raffazizzi** [comment]
# ATTRIBUTE CLASSES
                        
## tei                
                
* att.ascribed
* att.canonical
* att.ranging
* att.dimensions
* att.written
* att.damaged
* att.breaking
* att.cReferencing
* att.datable.w3c
* att.datable
* att.datcat
* att.declarable
* att.declaring
* att.fragmentable
* att.divLike
* att.docStatus
* att.duration.w3c
* att.duration.iso
* att.global.responsibility
* att.editLike
* att.global.rendition
* att.global.source
* att.global
* att.handFeatures
* att.internetMedia
* att.media
* att.resourced
* att.interpLike
* att.measurement
* att.naming
* att.notated
* att.placement
* att.typed
* att.pointing
* att.pointing.group
* att.scoping
* att.segLike
* att.sortable
* att.edition
* att.spanning
* att.styleDef
* att.tableDecoration
* att.timed
* att.transcriptional
* att.translatable
* att.citing
* att.partials
* att.personal
                
## namesdates                
                
* att.datable.custom
* att.datable.iso
                
## spoken                
                
* att.duration
                
## core                
                
* att.milestoneUnit
                
## header                
                
* att.patternReplacement
                
## verse                
                
* att.metrical
* att.enjamb
                
## dictionaries                
                
* att.entryLike
* att.lexicographic
                
## msdescription                
                
* att.msExcerpt
* att.msClass
                
## transcr                
                
* att.global.facs
* att.global.change
* att.coordinated
                
## textcrit                
                
* att.rdgPart
* att.witnessed
* att.textCritical
                
## linking                
                
* att.global.linking
                
## analysis                
                
* att.global.analytic
                
## tagdocs                
                
* att.repeatable
* att.combinable
* att.identified
* att.deprecated
* att.namespaceable

# MODEL CLASSES
                        
## tei
                
model.nameLike.agent
model.segLike
model.hiLike
model.emphLike
model.highlighted
model.dateLike
model.dimLike
model.measureLike
model.egLike
model.graphicLike
model.offsetLike
model.pPart.msdesc
model.pPart.editorial
model.pPart.transcriptional
model.pPart.edit
model.linePart
model.ptrLike
model.lPart
model.global.meta
model.milestoneLike
model.gLike
model.oddDecl
model.oddRef
model.phrase.xml
model.specDescLike
model.biblLike
model.headLike
model.labelLike
model.listLike
model.noteLike
model.lLike
model.pLike
model.stageLike
model.featureVal.complex
model.featureVal.single
model.entryPart
model.entryPart.top
model.eventLike
model.global.edit
model.divPart
model.persStateLike
model.personLike
model.personPart
model.placeNamePart
model.placeStateLike
model.orgPart
model.publicationStmtPart.agency
model.publicationStmtPart.detail
model.availabilityPart
model.certLike
model.descLike
model.glossLike
model.quoteLike
model.qLike
model.respLike
model.divWrapper
model.divTopPart
model.divTop
model.frontPart.drama
model.pLike.front
model.divBottomPart
model.divBottom
model.titlepagePart
model.msQuoteLike
model.msItemPart
model.choicePart
model.imprintPart
model.catDescPart
model.settingPart
model.textDescPart
model.castItemPart
model.physDescPart
model.addressLike
model.nameLike
model.global
model.featureVal
model.biblPart
model.frontPart
model.addrPart
model.pPart.data
model.inter
model.common
model.phrase
model.limitedPhrase
model.divLike
model.divGenLike
model.div1Like
model.div2Like
model.div3Like
model.div4Like
model.div5Like
model.div6Like
model.div7Like
model.applicationLike
model.teiHeaderPart
model.sourceDescPart
model.encodingDescPart
model.editorialDeclPart
model.profileDescPart
model.correspActionPart
model.correspContextPart
model.correspDescPart
model.resourceLike
model.orgStateLike
model.placeLike
model.segLike
model.segLike
model.segLike
                
## spoken
                
model.global.spoken
model.recordingPart
model.divPart.spoken
                
## textcrit
                
model.rdgLike
model.rdgPart
                
## namesdates
                
model.persNamePart
                
## dictionaries
                
model.entryLike
model.morphLike
model.lexicalRefinement
model.gramPart
model.formPart
model.ptrLike.form
                
## tagdocs
                
model.contentPart

# DATATYPES
                        
## tei
                
* att.ascribed
* att.canonical
* att.ranging
* att.dimensions
* att.written
* att.damaged
* att.breaking
* att.cReferencing
* att.datable.w3c
* att.datable
* att.datcat
* att.declarable
* att.declaring
* att.fragmentable
* att.divLike
* att.docStatus
* att.duration.w3c
* att.duration.iso
* att.global.responsibility
* att.editLike
* att.global.rendition
* att.global.source
* att.global
* att.handFeatures
* att.internetMedia
* att.media
* att.resourced
* att.interpLike
* att.measurement
* att.naming
* att.notated
* att.placement
* att.typed
* att.pointing
* att.pointing.group
* att.scoping
* att.segLike
* att.sortable
* att.edition
* att.spanning
* att.styleDef
* att.tableDecoration
* att.timed
* att.transcriptional
* att.translatable
* att.citing
* att.partials
* att.personal
                
## namesdates
                
* att.datable.custom
* att.datable.iso
                
## spoken
                
* att.duration
                
## core
                
* att.milestoneUnit
                
## header
                
* att.patternReplacement
                
## verse
                
* att.metrical
* att.enjamb
                
## dictionaries
                
* att.entryLike
* att.lexicographic
                
## msdescription
                
* att.msExcerpt
* att.msClass
                
## transcr
                
* att.global.facs
* att.global.change
* att.coordinated
                
## textcrit
                
* att.rdgPart
* att.witnessed
* att.textCritical
                
## linking
                
* att.global.linking
                
## analysis
                
* att.global.analytic
                
## tagdocs
                
* att.repeatable
* att.combinable
* att.identified
* att.deprecated
* att.namespaceable

# MACROS
                        
## tei
                
* att.ascribed
* att.canonical
* att.ranging
* att.dimensions
* att.written
* att.damaged
* att.breaking
* att.cReferencing
* att.datable.w3c
* att.datable
* att.datcat
* att.declarable
* att.declaring
* att.fragmentable
* att.divLike
* att.docStatus
* att.duration.w3c
* att.duration.iso
* att.global.responsibility
* att.editLike
* att.global.rendition
* att.global.source
* att.global
* att.handFeatures
* att.internetMedia
* att.media
* att.resourced
* att.interpLike
* att.measurement
* att.naming
* att.notated
* att.placement
* att.typed
* att.pointing
* att.pointing.group
* att.scoping
* att.segLike
* att.sortable
* att.edition
* att.spanning
* att.styleDef
* att.tableDecoration
* att.timed
* att.transcriptional
* att.translatable
* att.citing
* att.partials
* att.personal
                
## namesdates
                
* att.datable.custom
* att.datable.iso
                
## spoken
                
* att.duration
                
## core
                
* att.milestoneUnit
                
## header
                
* att.patternReplacement
                
## verse
                
* att.metrical
* att.enjamb
                
## dictionaries
                
* att.entryLike
* att.lexicographic
                
## msdescription
                
* att.msExcerpt
* att.msClass
                
## transcr
                
* att.global.facs
* att.global.change
* att.coordinated
                
## textcrit
                
* att.rdgPart
* att.witnessed
* att.textCritical
                
## linking
                
* att.global.linking
                
## analysis
                
* att.global.analytic
                
## tagdocs
                
* att.repeatable
* att.combinable
* att.identified
* att.deprecated
* att.namespaceable

**Comment by hcayless** [comment]
Hugh to move att.tableDecoration to the figures module.

**Comment by hcayless** [comment]
Not sure why this didn't get done, but it is now.
