### ISSUE TITLE
Add <postscript> to att.written, add <handShift/> to global

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1530]
As discussed [on the TEI list](https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1610&L=TEI-L&P=R11698&1=TEI-L&9=A&J=on&d=No+Match%3BMatch%3BMatches&z=4), the content model of `<postscript>` seems too limited. For example, right now we can't put `@hand` on `<postscript>` to indicate a change in hands in a letter when a second person writes something in the space remaining after a first writer has finished and signed a letter. Proposed: that we add `<postscript>` to att.written so that it's like `<salute>` and other similar elements.

It would also be useful to indicate a change in hands that covers more than a phrase, so to expand the usage of `<handShift/>` so that it can sit above the paragraph letter, but still be contained by some textual division, be it a `<div>` or a `<postScript>`, etc.

**Comment by peterstadler** [comment]
I think that's actually two FRs. One for ```@hand``` on ```<postscript>``` – which I think could be implemented easily.  Changing class memberships for ```<handShift/>``` would be the second and much more difficult FR (I suppose). 

So, my approach would be to focus on the first issue here and only tackle the second issue when there's a dedicated FR.

**Comment by raffazizzi** [comment]
F2F subgroup: Allow `@hand` on `postscript`. Agree with @peterstadler that there should be another ticket for moving `handshift` up a level.
