### ISSUE TITLE
Standard Content Models table is now incorrect

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1532]
The table at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ST.html#STECST now is incorrect because the code generating it is based on Relax NG Content models, I suspect. Code needs to be updated to generate the table properly from Pure ODD. 

This should be a simple fix, but should be a release blocker IMHO.

**Comment by lb42** [comment]
This seems to be fixed in my local copy of Utilities/expand.xsl : maybe it hasn't been checked in.

**Comment by jamescummings** [comment]
Apologies. I only checked the released copy of TEI Guidelines before submitting the issue.

(Thought it was better to submit it than forget I'd noticed it later.)

Indeed, checking Jenkins: 
http://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ST.html#STECST it is indeed fixed.

Closing bug.
