### ISSUE TITLE
rhyme example

### ISSUE THREAD

**Issue by davidfarmer** [TEIC/TEI#1533]
I have three comments about the page describing the rhyme element:
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-rhyme.html

1) I think you could find a less sexist sample poem.

2) In that example (if you continue to use it) the rhyme scheme is initially described as
abababcc
but if you read line-by-line, the final "c" is written as "a"

3) Could that page include information (or link to information) to how to mark up
a poem where the rhyme scheme is violated when the words in the poem are
given their usual pronunciation?  An example of what I mean is the poem "The Tyger"
by William Blake.  The rhyme scheme in each stanza is aabb, but the 4th line
in the 1st stanza does not rhyme if you pronounce "symmetry" in the usual way.

**Comment by martindholmes** [comment]
On #2 I agree completely: I've made a fix in commit 2cabf99..693a1c6.
On #3, in our projects we use the `@type` attribute to characterize rhymes according to an ontology; we might use rhymeHalf or rhymeSlant or something like that, depending on the researcher's views on rhymes. 
I'll leave #1 for others to address. It's Byron; pretty much the incarnation of sexism. :-)

**Comment by jamescummings** [comment]
I agree with @martindholmes's comments. 

On 1, I agree there could be much better poems to choose. I'm assuming this one is used to show that it isn't necessarily full orthographic words which are marked with the rhyme element. I'd rather _add_ more examples than necessarily get rid of this one (but wouldn't vote against that if we'd found some others to replace it... I have no love of Byron), just I always prefer to have more examples rather than less. ;-)

If we were make a list of criteria for a poem or poems which we wanted to have to exemplify the many things one can do with the rhyme element, what are those criteria?  (e.g. a poem which shows standard rhyme schemes, a mistake or variance from it, masculine/feminine rhymes, fragmentary rhymes, so-called 'eye rhymes', etc.)    What else?  Can we find that all in one poem short enough to act as an example?

**Comment by ebeshero** [comment]
Well, I for one, would love to see more Blake examples in the Guidelines, and second the call for "The Tyger" and its fearfully eye-rhyming symmetry! 

Elisa

--
Elisa Beshero-Bondar, PhD 
Director, Center for the Digital Text
Associate Professor of English 
University of Pittsburgh at Greensburg
150 Finoli Drive, Greensburg, PA 15601 USA
E-mail: ebb8@pitt.edu | Development site: http://newtfire.org

Typeset by hand on my iPad

**Comment by jamescummings** [comment]
Could I suggest that if finding new poems as examples which exemplify these kinds of things, we should be including those from outside the Western Anglo canon?

**Comment by ebeshero** [comment]
I think we should start small with the current suggestion. Blake is more canonical now than Byron, but the question of inclusion of an example should have less to do with cultural canonicity and more to do with whether the example models a complexity that our community is likely to encounter in their encoding. We are not producing an anthology, though the Guidelines do important cultural work.

I work on projects on Western texts outside 'the canon' (an impossibly monolithic term when we look at the lives of texts over centuries and across cultures), and the issues of doing sustained digital work on noncanonical texts beyond the survey scale are complicated by funding structures that support the canonical texts of one's nation first. I think it would be a powerful statement for the TEI to systematically overhaul its examples and make a point of encouraging in-depth work on texts that have not yet received a lot of attention in large and well-endowed digital edition projects. The goal is laudable and would take serious advocacy and effort working with our community. 

But we should pause and consider why we choose a particular text for an example in the Guidelines, and its shortness combined with its recognizability for a poem like "The Tyger" might be an argument in its favor.

**Comment by jamescummings** [comment]
Sure... and that was my thought with listing `<rhyme>` types etc. We should probably compile a list of things we'd want to see in that example. I agree entirely that we should have good examples whose point is to show the types of things the community might encounter in their encoding. Just thinking that if it happened to be in South African English, or French, or Spanish (or whatever) we shouldn't necessarily not use it.  (And while I'd like to have more Japanese examples, say, I think these are less helpful to non-Japanese speakers than a French example is to a non-French speaker given the nature of the writing system... one can still _see_ a rhyme in French or Spanish even if one doesn't know that language. But maybe I'm wrong, I don't know.)

I'm not familiar enough with a wide enough range of poetry (Blake seems horribly late to me in my personal canon... I'm more of a Chaucer kind of person... ;-) ) to suggest good examples.  Sure, add that Blake poem as an example... I'd rather have 10 examples than one.   Examples work more clearly on the mind than precepts.

**Comment by martindholmes** [comment]
There's something about judging a piece of literature an encoding example by the ethical standards of our time that makes me a bit nervous. I'm no Byron fan either, but I can think of an awful lot of great literature that would end up being excluded on this basis. 

I have a couple of hundred examples of Victorian periodical poetry that has rhyme encoded. Mostly it's not great poetry, though.

**Comment by jamescummings** [comment]
@martindholmes Sure.  I think the guiding principle should be whether the poetry shows interesting and useful encoding for the end user (and in a way that helps the user understand the markup).  If that happens to be great poetry (by the judgement of whoever is adding the example), then fine.  But I'd rather have a boring poem which showed complex encoding examples, than no example of that complex encoding.  ;-)

**Comment by davidfarmer** [comment]
How about using the first stanza of the first canto of Don Juan?

That way it is still Byron, it gives an example of a rhyme
that requires altering the usual pronunciation, and it
includes a multi-word rhyming part ("new one", "true one",
"Juan") as illustrated in the current example.

I also want to encourage the suggestion of having multiple
examples.  When I look at that web page, I find it quite
impenetrable, except for what I can puzzle out by looking
at the example.

(Apologies if Don Juan is even less appropriate than the
current example.  Maybe by having several, there is less
reason to criticize any particular example.)

**Comment by ebeshero** [comment]
The more examples the better--we should add all of these, and a better snippet of Byron too.

**Comment by lb42** [comment]
1. I like this example because of the audacity of its rhyme. I think removing it on the grounds of its sexism would be daft. 
2. Thanks for the correction.
3. Clicking on "show all" displays quite a variety of examples.. have you checked that? But by all means let's add more.

**Comment by jamescummings** [comment]
Yes, there is lots in the guidelines, but the point is particularly to add more to the examples pages (where these are good exempla of different encoding)

**Comment by davidfarmer** [comment]
Somehow I missed the "Show all" link, or didn't realize
it gave more examples.  (In Firefox on my Mac the 'Show all'
overlaps the border around the example.  And it is off to
the right, while all the other action is on the left.)

Maybe it would help to be more blatant:  flush left with the
example, have the link say "Show more examples".  That would be
a global change on all pages.

Obviously I now know about that link, so it is too late to
help me, but future users might appreciate it.

(The markup has a div with style float: right, so you have
to change the code that generates the page, instead of just
changing the CSS.)

**Comment by lb42** [comment]
James, when you say "example pages" do you mean the spec pages? And why do you think the examples in the body of the Guidelines are somehow inferior? I would have thought they generally are much better, since they are chosen and contextualised to explain thoroughly the full range of intended applications of an element (etc.)

**Comment by jamescummings** [comment]
Apologies, was answering quickly via my phone while watching a presentation.  I do indeed mean specification / element reference pages, since there are many people who look at these and never go and read the Guidelines proper. (I'm not saying that is a good thing...)  And yes, the examples in the prose of the Guidelines are better contextualised.  I'm just saying having more examples (of different types of encoding usage) on these pages in Appendix C would be beneficial.  There are a number of pages with only one example, which show only the most basic usage of the element.  Where possible these should be supplemented.  (But obviously this is a low priority desire along with other improvements in our provision of examples....)

**Comment by hcayless** [comment]
Add at least one example (Tyger, Tyger) to the spec using `@type` on `<rhyme>` to illustrate "eye-rhyme", e.g.. @jamescummings will add an example from another canon.

**Comment by ebeshero** [comment]
Council F2F agrees: @jamescummings  should add at least one example (Tyger, Tyger) to the spec using @type on <rhyme> to illustrate "eye-rhyme" (and possibly others for "slant rhyme" etc). Maybe add a few sentences more of explanation. @jamescummings will also add an example from another canon.

**Comment by jamescummings** [comment]
Added a couple more examples at https://github.com/TEIC/TEI/commit/c02f46a6ef66366f727aa5bd467fccf2297609df

**Comment by speters33w** [comment]
> On 3, in our projects we use the `@type` attribute to characterize rhymes according to an ontology; we might use rhymeHalf or rhymeSlant or something like that, depending on the researcher's views on rhymes.

Are there any standard tags for slant rhymes at this point?
