### ISSUE TITLE
description of <constraintSpec> is too narrow

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1535]
The description of `<constraintSpec>` is:
~~~~~xml
  <desc versionDate="2009-06-10" xml:lang="en">contains  a constraint, expressed in some formal syntax,
  which cannot be expressed in the structural content model</desc>
~~~~~
Why would a `<constraintSpec>` be limited to things that **cannot** be expressed in the grammar-based schema? There are lots of things that would be **possible** to express in a RELAX NG or Pure ODD content model that might just be easier to express in Schematron.

How about something like “contains a formal constraint, typically expressed in a rule-based schema language, to which the construct being defined must conform in order to be considered valid”?

**Comment by sydb** [comment]
E.g., the example of `<constraint>` in the GLs includes
~~~~~xml
<sch:assert test="tei:fileDesc/tei:titleStmt/tei:title[@type='main']"> a main title must be supplied</assert>
~~~~~
Surely this test **could** be done in the structural content model:
~~~~~~xml
<elementSpec ident="mainTitle" mode="add">
  <altIdent>title</altIdent>
  <desc>a main title</desc>
  <classes>
    <memberOf key="att.global"/>
    <memberOf key="att.canonical"/>
    <memberOf key="att.typed"/>
    <memberOf key="att.datable"/>
  </classes>
  <content>
    <macroRef key="macro.paraContent"/>
  </content>
  <attList>
    <attDef ident="type" mode="replace" usage="req">
      <datatype minOccurs="1" maxOccurs="1">
        <dataRef key="teidata.enumerated"/>
      </datatype>
      <valList type="closed">
        <valItem ident="main"/>
      </valList>
    </attDef>
  </attList>
  <remarks>
    <p>see the description of <gi>title</gi> for details</p>
  </remarks>
</elementSpec>

<elementSpec ident="titleStmt" module="header" mode="change">
  <content>
    <sequence>        
      <elementRef key="mainTitle" minOccurs="1" maxOccurs="1"/>
      <classRef key="model.respLike" minOccurs="0" maxOccurs="unbounded"/>            
    </sequence>
  </content>
</elementSpec>
~~~~~
Now, I’m not suggesting the above is the better way to do this; only that to say it “cannot be expressed” in RELAX NG or Pure ODD is incorrect.

**Comment by lb42** [comment]
But these are not the same. The schematron one says that a main title must be present. The other one says that only main titles are permitted.

**Comment by sydb** [comment]
Good catch, Lou, they are slightly different. But that has nothing to do with the point, which is that they need not be. The description of `<constraintSpec>` should not say “cannot be expressed”.

**Comment by ebeshero** [comment]
Council F2F agrees this is Go.

**Comment by ebeshero** [comment]
Modified the description as discussed, with this commit: https://github.com/TEIC/TEI/commit/4cbbb6a54ccffb930991eb069a64f84b97791ba7
