### ISSUE TITLE
example for <att>@xml:base</att> irelevant in the French version of the GL

### ISSUE THREAD

**Issue by emmamorlock** [TEIC/TEI#1538]
The example in the French version of the GL doesn't contain any @xml:base attribute... 
The english example should be duplicated, or the french one completed...
Compare:
* http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-att.global.html
* http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.html

**Comment by lb42** [comment]
Oops. Can you suggest an appropriate URL to insert?

**Comment by tuurma** [comment]
@emmamorlock would you be willing to provide an example illustrating the use of @xml:base in French version or should we just duplicate the English one?

**Comment by lb42** [comment]
Looking at the French example again, I see that it is also has other errors (author detail included within title, publisher name given as author etc.) . Rather than fix them all, I have just commented it out, pending a better example. This means that the EN example will be used instead.
