### ISSUE TITLE
example of <attList> is lame

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1539]
The example(s) of `<attList>` in the tagdoc for same shows an attribute list that

1. has only 1 attribute
1. does not every make use of `@org` (which may be a good thing, as IIRC it does not work)
1. the one attr defined has `<rng:ref>` instead of `<dataRef>` — FIXED at 456cadc
1. that one attr defined does not have a `<valList>` (which is not required, but is good practice that we should exemplify)

**Comment by lb42** [comment]
I think we have several examples using @org=choice which work in the sense that the generated schema permits either one of the alternatives; the problem is that the schema also permits both, which is wrong. That should probably be a different, stylesheets, issue.

**Comment by hcayless** [comment]
Group at F2F thinks we do need more/better examples. Will open a ticket in Stylesheets to generate a test for mutually exclusive attributes.

**Comment by emylonas** [comment]
@hcayless is this a Status:GO? I thought it was but it's marked Status:Needs Discussion

**Comment by emylonas** [comment]
added an example from `<relation>` which uses `@org`. Didn't add translations, but could either by including all the languages or by making several more translated examples. Comments?

**Comment by emylonas** [comment]
closed with a1da1d4

can re-open if multilingual examples should be added. - can be generated from the same example
