### ISSUE TITLE
lots of little documentation errors

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1546]
I don’t have time to make a separate ticket for each of these, let alone fix them, right now.

1. `<remarks>` of teidata.count are silly (0 is not a positive integer value)
1. `<remarks>` of teidata.certainty need to say “teidata.”; except is this even true?
1. `<remarks>` of teidata.enumerated could explain the constraints a lot better (e.g., why make reader go to definition of teidata.word?)

**Comment by lb42** [comment]
Fixed
