### ISSUE TITLE
description of egXML too restrictive

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1550]
The description of `<egXML>` says “XML element or attribute” where it should say something more inclusive, as processing instructions, bare text nodes, or comments may be exemplified as well. (XML declarations can not be exemplified, nor do I think can DOCTYPE declarations or internal DTD subsets.)

**Comment by raffazizzi** [comment]
From F2F meeting: sounds good. Proposed change:
"a single XML fragment demonstrating the use of some XML node, such as element, attribute, processing instruction, etc."

**Comment by sydb** [comment]
I like it, but would prefer the plural: “a single XML fragment demonstrating the use of some XML, such as elements, attributes, or processing instructions, etc.”

**Comment by raffazizzi** [comment]
F2F follow Syd's wording above
