### ISSUE TITLE
Allow <fs> as a child of <textClass>

### ISSUE THREAD

**Issue by mccaskey** [TEIC/TEI#1553]
Allowing &lt;fs> under &lt;textClass> would provide a lightweight way to add project-specific classifications to a text. 

A chemical research report might have 
~~~~
<fs> 
<f name="chemical">diazepam</f>
<f name="facility">Lab 23.7a</f>
<f name="project">Funded<f>
</fs>
~~~~
A legal charter from the middle ages might have
~~~~
<fs>
<f name="authority">papal</f>
<f name="territory">Venice</f>
<f name="type">deed</f>
</fs>
~~~~
Currently, &lt;fs> can be added under &lt;classCode>, but it makes more sense as a peer to &lt;classCode>.

**Comment by emylonas** [comment]
Council discussed this and thinks that `<fs>` may not be the best option for describing structured information in `<textClass>`. The more conventional way to do it is to define a `<taxonomy>` in `<classDecl>`, which would identify the terms that are being recorded. The references will be listed in `<textClass>`, as suggested in the initial posting. This will work best if the set of of values in the key-value pairs is a closed or semi-closed list. An example of how this could be encoded is: 

>   <encodingDesc>
        <classDecl>
           <taxonomy xml:id="Chemical">
              <category xml:id="diazepam">
                 <catDesc>Diazepam</catDesc>
              </category>
              <category xml:id="midazolan">
                 <catDesc>Midazolan</catDesc>
              </category>
              <category xml:id="lorazepam">
                 <catDesc>Lorazepam</catDesc>
              </category>
           </taxonomy>
           <taxonomy xml:id="Facility">
              <category xml:id="Lab23.7a">
                 <catDesc>Lab 23.7a</catDesc>
              </category>
              <category xml:id="Lab01.14b">
                 <catDesc>Lab 1.14.b</catDesc>
              </category>
           </taxonomy>
           <taxonomy xml:id="Project">
              <category xml:id="funded">
                 <catDesc>Funded</catDesc>
              </category>
              <category xml:id="notFunded">
                 <catDesc>Not Funded</catDesc>
              </category>
              <category xml:id="completed">
                 <catDesc>Completed</catDesc>
              </category>
           </taxonomy>
        </classDecl>
        
     </encodingDesc>
     <profileDesc>
        <textClass>
           <catRef target="#Lab01.14b #funded #clonazepam"/>
        </textClass>
     </profileDesc>
>

You can use the following schematron code to ensure that there is exactly one value from each taxonomy in the `@target` 

<?xml version="1.0" encoding="UTF-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2">
  <sch:ns uri="http://www.tei-c.org/ns/1.0" prefix="tei"/>
  <sch:pattern>
    <sch:rule context="tei:textClass">
      <sch:assert test="tei:catRef">The text classification should have a category reference</sch:assert>
    </sch:rule>
  </sch:pattern>
  <sch:pattern>
    <sch:rule context="tei:catRef">
      <sch:let name="cats" value="tokenize( normalize-space( @target ),' ')"/>
      <sch:let name="categories" value="for $c in $cats return id( substring( $c, 2 ) )"/>
      <sch:let name="taxonomies" value="for $c in $categories return $c/parent::tei:taxonomy/@xml:id"/>
      <sch:assert test="count( $cats ) eq 3">The category reference should refer to 3 categories</sch:assert>
      <sch:assert test="$taxonomies = 'Chemical'
                    and $taxonomies = 'Facility'
                    and $taxonomies = 'Project'">The category reference should refer to a chemical, a facility, and a project (in any order)</sch:assert>
    </sch:rule>
  </sch:pattern>
</sch:schema>

There are other ways of doing this using `<classCode>` and `<keywords>`, but they might not be as easy to control as a taxonomy.

**Comment by mccaskey** [comment]
> This will work best if the set of of values in the key-value pairs is a closed or semi-closed list.

Exactly. What about when the list is open ended?

I too like the discipline of taxonomies of canonical classifications, but sometimes they just aren’t apt for a project. (Keywords serve a different purpose.)

Key-value pairs provide a lightweight way to add a little structure to small projects that can’t justify the overhead of developing a comprehensive canonical classification system.

**Comment by bansp** [comment]
Upon reading the title of this ticket, I was sure that `<fs>` are suggested because the existing system can be too light-weight for some uses, so I was surprised when I read that `<fs>` are treated as a lightweight solution. 

The feature structure instances offered at the top are not more lightweight than the corresponding `<taxonomy>`, they are merely less verbose in this very example, which is missing all the extras that feature structures usually require (let's not forget that they theoretically also require separate schema definitions encoded as FSDecl). In fact, feature structures can be a heavy can of worms that one would expect justification for (and I opened this ticket hoping to learn about how introducing them can be justified).

I also don't see why `<taxonomy>` should be treated as describing an inherently delimited system. I have used it, and seen it used, for open-ended systems (and I can't see how `<fs>`s could help here, other than by their _perceived_ but not real non-verbosity). To be sure, I vaguely recall having some issues with `<taxonomy>`, but that was because it seemed _too_ lightweight for what I wanted.

**Comment by martindholmes** [comment]
I second Piotr's view. `<taxonomy>` is easy to understand and easy to use; `<fsDecl>`s tend to make your brain hurt, especially when you're trying to do something relatively simple. Our standard approach is to use nested taxonomies and process them into the ODD and then into the schema as valLists for `<catRef>/@target`. Non-specialists can edit the taxonomy easily, and see their changes carried through into the schema.

**Comment by mccaskey** [comment]
How would you encode this case?

We are encoding an archive of medieval military orders, often instructing a soldier to go kill or capture a named enemy thought to be residing in a particular town. Names of cities might recur but names of soldiers and enemy targets rarely do. We do not yet have access to all such orders; we are encoding them as we find them. So we don't know a priori all possible values. 

We want to record names of soldier, target, and town. Eventually these will be search criteria in some web app. Where in teiHeader would you record these three values? 

(The people on this project are academic historians, not technically savvy. Omeka and WordPress are at the edge of their comfort zone. They won't invest the time learning to “customize a schema.” They've asked me for advice. I'll give it then be gone. Part-time history undergraduates who will change semester to semester will carry on the work. They'll record 15-20 documents a year for 2-3 years, put up an Omeka or WordPress site, and be done. Whatever I suggest has to be maintenance-free.)

**Comment by lb42** [comment]
I wouldnt record them in the header at all. Id get the grunt work of  identifying and distinguidjing the names done first, by marking up the text with persName etc. Then id write xslt to extract names into a free standing documen containing a listPerson which could be edited by someone ab l e to decide whether this john doe is the same soldier as that one.

**Comment by mccaskey** [comment]
Extracting from the text hasn’t proven promising. Sometimes the needed information doesn’t actually appear in the text. We infer it from the context in which the document was found.

**Comment by mccaskey** [comment]
I hadn’t thought of using `@type` on `<term>`s. That really does what I wanted. It creates a lightweight key-value structure under `<textClass>`. 

I’m open to closing out the request.
