### ISSUE TITLE
Permit note within respStmt

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1557]
_From @lb42 on June 5, 2016 9:54_

Consider the following example (in the tagdoc for &lt;recording>)

```
  <bibl>
            <title>Questions sur la souffrance et la santé au travail : pénibilité, stress,
              dépression, harcèlement, maladies et accidents...</title>
            <author>France Inter</author>
            <respStmt>
              <resp>Présentateur</resp>
              <name>Alain Bédouet</name>
            </respStmt>
            <respStmt>
              <resp>Personne interrogée</resp>
              <name>Marie Pezé</name>
            </respStmt>
            <series>
              <title>Le Téléphone sonne</title>
            </series>
             <note>Marie Pezé est Docteur en psychologie, psychanalyste, expert judiciaire ; dirige
                la consultation « souffrance et travail » à l’Hôpital de Nanterre (92), auteure de
                  <title>ils ne mourraient pas tous mais tous étaient frappés</title>, Editions
                Pearson.</note>
            <note>Première diffusion le <date when="2008-09-24"> mercredi 24 septembre
            2008</date>
                  </note>
          </bibl>
```

The information about Dr Pezé really belongs (and was originally) within the &lt;respStmt> since it isn't about the recording itself.  Yes in an ideal world she'd be described in a person in a particDesc pointed to from the name here. But. 

_Copied from original issue: TEIC/Stylesheets#155_

**Comment by lb42** [comment]
Amusingly enough, you can of course insert the &lt;note> *within* the &lt;name> which looks a bit strange,
~~~~
 <respStmt>
  <resp>Personne interrogée</resp>
   <name>Marie Pezé   
            <note>Marie Pezé est Docteur en psychologie, psychanalyste, expert judiciaire ...   </note>
</name>
</respStmt>
~~~~
However, this is not a stylesheet issue. Moving it to the right queue.

**Comment by martindholmes** [comment]
Isn't it the case that the note either annotates the person (in which case it could go in `<name>`) or the responsibility description (in which case it could go in `<resp>`)?

**Comment by lb42** [comment]
Yes : it's true that adding note within respStmt leaves ambiguous whether we are annotating the responsibility or the person responsible, though I suppose a note might well cover both aspects. The real reason I dont like putting it inside the name element is that the name itself is no longer  reliably accessible by a simple xPath  whether it's annotated or not.

**Comment by raffazizzi** [comment]
F2F subgroup: We think that @lb42 should either describe the person elsewhere (as he said), or use the note within `name`. Suggested XPath: `//respStmt/name/node()[not(self::note)]`

**Comment by sydb** [comment]
~~~~~
<respStmt xml:id="rS1">
   <resp>demonstrated another mechanism</resp>
  <persName ref="#sbauman.emt"/>
</respStmt>
<!-- ... -->
<note target="#rS1">The <gi>respStmt</gi> example <emph>is</emph> the example of annotating a <gi>respStmt</gi>.</note>
~~~~~

**Comment by raffazizzi** [comment]
F2F - Group discussion decides in favor of adding `note` to `respStmt`'s content model. 

Notes: 

a) `note/@target` can already refer to a respStmt, so addition to the content model is plausible (see @sydb's comment above

b) the note should about the *statement* as opposed to the `resp` or the `name` (in which case it makes more sense to include it in `resp` or `name`). So the short bio about Marie Pezé above should still go inside `name`.

**Comment by sydb** [comment]
Council has decided to permit `<note>*` as a final clause in the content of `<respStmt>`.
