### ISSUE TITLE
wrong reference to dcr xsd in http://www.tei-c.org/Vault/P5/3.1.0/xml/tei/custom/schema/xsd/tei_all_teix.xsd

### ISSUE THREAD

**Issue by jfriviere** [TEIC/TEI#1558]
In http://www.tei-c.org/Vault/P5/3.1.0/xml/tei/custom/schema/xsd/tei_all_teix.xsd
the namespace `http://www.isocat.org/ns/dcr` reference should be `tei_all_dcr.xsd` rather then `dcr.xsd`
Actual :
```xml
<xs:import namespace="http://www.isocat.org/ns/dcr" schemaLocation="dcr.xsd"/>
```
Sould be :
```xml
<xs:import namespace="http://www.isocat.org/ns/dcr" schemaLocation="tei_all_dcr.xsd"/>
```

Thanks

**Comment by hcayless** [comment]
Should be fixed in 	30cf918.

**Comment by michel-jacobson** [comment]
The schema (http://www.tei-c.org/Vault/P5/current/xml/tei/custom/schema/xsd/tei_all_teix.xsd) is still unchanged. Where can we find the correct set of xsd files ?

**Comment by martindholmes** [comment]
If you're looking for a development build incorporating changes made since the last release, you can find it here:

http://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/custom/schema/xsd/
