### ISSUE TITLE
Mysterious maven stuff in the build

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1561]
I found this in release notes:

~~~~~
2014-02-10  Sebastian Rahtz <sebastian.rahtz@gmail.com>
	Changed paths:
	   A /trunk/P5/Exemplars/pom.xml

	maven setup for testing XSD
~~~~~

If you look at Exemplars/pom.xml, you'll see a completely uncommented maven pom file, which is pointing at this hard-coded obsolete URL:

http://tei.oucs.ox.ac.uk/jenkins/job/TEIP5/lastSuccessfulBuild/artifact/release/xml/tei/custom/schema/xsd/tei_all.xsd

There's nothing there, so it can't be doing much. There's no reference to the pom.xml file anywhere I can find, and I don't believe maven is actually being used. I THINK we could remove the pom.xml file. It's possible that would obviate the need for some of the jars in Utilities/lib, but I'm not sure; most of those are I think used in epubcheck.

**Comment by hcayless** [comment]
I poked at it a bit, and I don't think it works, or probably ever did. The comment on the commit (c70da0b) that added it is a bit cryptic, but I guess this was meant to be a starting point for something that never got off the ground. It doesn't *seem* to work. I vote we just kill it off, and unless there are any objections, I will do so.

**Comment by hcayless** [comment]
Removed in 3e7b0f7
