### ISSUE TITLE
Processing of datatype nonNegativeInteger is broken

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1562]
Looking at this page:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-language.html

you see that there's no output at all from the processing of the datatype of `@usage`. I discovered this while working on TEIC/Stylesheets#205. Posting it on TEI because the main urgency would appear to be in Guidelines generation, since we have a release with a missing datatype and possibly others, but it may be a Stylesheets issue.

**Comment by lb42** [comment]
This is the same as https://github.com/TEIC/Stylesheets/issues/203 which incidentally lists the other places where attention is needed to circumvent it

**Comment by martindholmes** [comment]
Sorry, I'd even commented on that but forgotten all about it. Closing this one.
