### ISSUE TITLE
TEI simplePrint HTML file title link

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1565]
The title and creation date of:

http://www.tei-c.org/release/doc/tei-p5-exemplars/html/tei_simplePrint.doc.html

links to 

http://www.tei-c.org/release/doc/tei-p5-exemplars/html/index.html

Which doesn't exist.  (But reasonably could do...)

Possible solutions:

a) investigate stylesheet generating this and make it not create this link
b) compare the header/front of TEI simplePrint to the other exemplars provided at http://www.tei-c.org/release/doc/tei-p5-exemplars/html/ to have much nicer title information in the same way that jTEI, tite and lite do
c) make http://www.tei-c.org/release/doc/tei-p5-exemplars/html/index.html be generated on each build of exemplars and have it list the title etc. and give a link to the exemplars, regardless of whether they link back here

I think b) and c) are the right answers but posting an issue to remind us to do it. (happy to do so and will tentatively assign to myself but if I've not done it before next release, then feel free to steal it.)

**Comment by lb42** [comment]
This is because I forgot to put a &lt;titlePage> in the document. I  have just added a minimal one, which you may wish to amplify/modify further so I am leaving the ticket open.

**Comment by jamescummings** [comment]
That might fix it. I'll leave this open for now to remind me to update the titlePage (if needed).

**Comment by jamescummings** [comment]
Added some docAuthors to this since other exemplars sometimes have these.
