### ISSUE TITLE
Add @origLang to textLang

### ISSUE THREAD

**Issue by nathangibson** [TEIC/TEI#1566]
I'm modeling abstract/conceptual works for the New Handbook of Syriac Literature (http://syriaca.org/nhsl). I use `<bibl>` for this purpose, and I include a `<textLang mainLang="syr"/>` for Syriac works. Note that these are not manuscripts, but the works which the manuscripts embody. 

I sometimes want to indicate that the Syriac work is a translation of a Greek work, but I don't see a simple way to do this. My thought is to allow an `@origLang` on the `<textLang>` element. 

Or is there already some other good way to do this?

**Comment by lb42** [comment]
Wild speculation follows. You could consider that "Syriac translated from Greek" is a variation of "Syriac" and give it a distinct language code, using the "private tag" option described in BCP47  (something like xml:lang="syr-x-he"?) . If however you want to include a reference to the Greek original in your description, I suggest using &lt;relatedItem> to point to it.

**Comment by nathangibson** [comment]
Well, your comment makes me think about what it is I'm actually trying to assert--which is *not* about the language of the Syriac work per se but about the language of its ancestor. Thus a private tag doesn't really cut it. (Plus we are using private tags already to indicate transliteration systems.)

On the other hand, ideally I was hoping for something not so fancy as `<relatedItem>` because I would rather not have to always model the original work. In many cases, the original work is not extant and there may be no URI to point to (in our system or anyone else's).

But if I need to go down the track of putting in a bibl for the original work, I would lean toward tying the two works together using a relation, simply because we are using relations for everything else. Does relatedItem have any huge advantage over this approach? 

Here's a stab at modeling this in a real work record we are drafting:
```
<bibl xml:id="work-9502" type="lawd:ConceptualWork">
            <title xml:id="name9502-1" xml:lang="en" syriaca-tags="#syriaca-headword">1 John (Harklensian Version)</title>
            <idno type="URI">http://syriaca.org/work/9502</idno>
            <textLang mainLang="syr"/>
            <bibl type="lawd:ConceptualWork" xml:id="bib9502-1">
               <title>1 John</title>
               <textLang mainLang="grc">Greek</textLang>
               <listRelation>
                  <relation type="translationSource" active="http://syriaca.org/work/9502" ref="dct:source" passive="#bib9502-1"/>
               </listRelation>
            </bibl>            
         </bibl>
```
If a URI is available for the Greek work, this could go in a `ptr/@target`. On the other extreme, if there is too little information to even give a title, it would simply be a bibl with a textLang and listRelation, but this seems to be allowed.

**Comment by sydb** [comment]
~~~~~
        <bibl xml:id="work-9502" type="lawd:ConceptualWork">
          <title xml:id="name9502-1" xml:lang="en" ng:syriaca-tags="#syriaca-headword">1 John
            (Harklensian Version)</title>
          <idno type="URI">http://syriaca.org/work/9502</idno>
          <textLang mainLang="syr"/>
          <relatedItem type="lawd:ConceptualWorkInOriginalLanguage" xml:id="bib9502-1">
            <bibl>
              <textLang mainLang="grc"/>
              <title>1 John</title>
            </bibl>
          </relatedItem>
        </bibl>

**Comment by sydb** [comment]
Council addressed this issue and thinks that the semantics of `<textLang>` do not really support an attribute about the language of something else (the source or original), so is not in favor of adding a new `@origLang` attribute.
We think OPs idea of expressing this as a relation is the right idea, but prefer `<relatedItem>` (since that’s what it was designed for, sort of, no?).
The above comment is intended as one such example.

**Comment by nathangibson** [comment]
Thanks @sydb and @lb42 . These suggestions help and we are satisfied now that we don't need an `@origLang`.
