### ISSUE TITLE
Exemplars should not worry about Sanity Check

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1567]
Several of the exemplar ODDs still contain lines like the following
~~~~
 <!-- required to avoid Sanity Checker complaint -->
<elementSpec ident="handNote" mode="delete" module="header"/>
~~~~
This was introduced as an unsavoury kludge  when we noticed that the "Sanity Checker" in Roma wasn't smart enough to deal with an element (handNote) defined by one module (header) but used in another (msdescription)  unless that module was included in the schema. Since then the Sanity Checker has been removed from Roma for other reasons (it can't handle pure ODD). If we ever restore it we can probably fix this problem at the same time. So, I  respectfully suggest that the above two lines should be simply deleted from all the affected exemplar ODDs, which are: tei_corpus, tei_drama, tei_math, tei_minimal, tei_odds, tei_speech, tei_svg and tei_xinclude.

**Comment by hcayless** [comment]
Agree, and think this amount to the removal of cruft, and so should be green.

**Comment by scstanley7** [comment]
I'm about to check in these changes for all but tei_math. That ODD includes two additional `<elementRef>`s deleting scriptNote and typeNote. The comment also refers to "Sanity Checker complaints" in the plural. Are those lines supposed to be removed as well?

**Comment by hcayless** [comment]
I'd remove everything between the two comments.
