### ISSUE TITLE
typeNote is member of header module but only useable in typeDesc (msDescription module)

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1568]
typeNote is member of header module but only useable in typeDesc (msDescription module)

Proposal: move typeNote to be in msDescription module.

**Comment by lb42** [comment]
Is this related to issue 1567 ?

**Comment by jamescummings** [comment]
I suppose in that it would produce the same error in Roma's sanity checker.  Do you have any recollection why typeNote is in the header module, but is only usable inside the typeDesc element that is only available when you have the msdescription module loaded?  Is there any bad side effect you can imagine from moving typeNote to msdescription (aside from potentially breaking a very few existing odds)?

**Comment by hcayless** [comment]
Corrigible error. We will fix it.
