### ISSUE TITLE
notatedMusic remarks should mention MEI

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1569]
The note on notatedMusic http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-notatedMusic.html should mention standards like MEI. (i.e. that we approve of people embedding MEI in a container element like notatedMusic.

**Comment by hcayless** [comment]
@raffazizzi probably knows how best what to put here, and we should certainly do it.

**Comment by raffazizzi** [comment]
What about something like this? (To be added both as a remark and to the guidelines)

```It is also recommended, when useful, to embed XML-based music notation formats, such as the <ref target="http://music-encoding.org">Music Encoding Initiative</ref> format as content of <gi>notatedMusic</gi>. This must be done by means of customization.```
