### ISSUE TITLE
tei_dictionaries.odd should be removed from Exemplars

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1572]
@sydb and I noticed:

- P5/Exemplars/tei_dictionaries.odd is not functional (it does not include the textstructure module)
- It lacks accompanying tei_dictionaries.tei and tei_dictionaries.template files
- It doesn't appear on the Customizations page on the website
- Its log history (below) suggests that it was intended to be removed

~~~~~
commit fae41d5f4dca78b310e304d60747483c28ba54b9
Author: lb42 <lou.burnard@retired.ox.ac.uk>
Date:   Sun Feb 28 11:36:17 2016 +0000

    class tweaking per issue #937

commit 5c2b4928aaaefd484d240077ea1b5709c2613b00
Author: Sebastian Rahtz <sebastian.rahtz@it.ox.ac.uk>
Date:   Sat Oct 6 14:09:59 2012 +0000

    more templates, dont use dictionaries any more

commit fc65e585df3af1f6ccf99638b76dfb87f3b2a154
Author: Sebastian Rahtz <sebastian.rahtz@it.ox.ac.uk>
Date:   Tue Jun 3 08:44:41 2008 +0000

    remove Laurent's extensions

commit 60230be5df73a9f97f3492e01f939fc331d4bb05
Author: Sebastian Rahtz <sebastian.rahtz@it.ox.ac.uk>
Date:   Tue Jun 3 08:39:48 2008 +0000

    remove duplicate ID

~~~~~

**Comment by lb42** [comment]
It would however surely be a good idea to provide a sample ODD for encoding dictionaries. I bet @bansp could suggest one...

**Comment by martindholmes** [comment]
I have a feeling this was going to be done following a rewrite of the Dictionaries chapter, which has been on the agenda since Laurent's time as Council chair.

**Comment by laurentromary** [comment]
Well, a sample odd would just be adding the dictionary module. The ENeL project has organized a meeting in November to design tighter guidelines for legacy dictionary and the group moves ahead with document. The ODD should follow. The TEI LingSIG also put dictionaries high up on the agenda (see minutes from last meeting in Vienna).

**Comment by lb42** [comment]
An ODD that just includes the dictionary module wouldn't get you very far though. You need tei and some (but not all) of the core elements too, surely? I think we need to look at existing projects and see if we can suggest something analogous to simplePrint.

**Comment by martindholmes** [comment]
We could fix the existing ODD by adding the textstructure module, create a template and a sample file, and make this an official customization. But I think that wouldn't be all that useful for people, and it would be one more customization for people to wade through, and one more option in the Oxygen plugin; my vote would be to ask LingSIG to work directly on a proposal for this (assuming their current objectives don't already include it).

**Comment by laurentromary** [comment]
@lb42 well, I meant the dict module on top of the baseline of course. Sorry for the short cuts.
What you call the analogous to simplePrint is what the ENeL group is planning to do. 
@martindholmes you're right in all your assumptions ;-)

**Comment by bansp** [comment]
And may I add that we're meeting again, a month from now, and before we do, we want to have a readable deliverable of the November meeting (not comprehensive yet, mind you, but with the main points clearly motivated, identified and illustrated).

**Comment by hcayless** [comment]
Can we remove it then, and if LingSIG wants to create an updated version, they can?

**Comment by hcayless** [comment]
@alex-bia unless there are objections within the next week or so, I think this can be made green and done.

**Comment by jamescummings** [comment]
I agree with @hcayless that we should remove it until such time as a replacement is created. To do this do we just remove the ODD, or are there unforeseen side-effects? Is there a copy of it in the oxygen framework?

**Comment by sydb** [comment]
No, @jamescummings , there is not a copy in the oXygen framework precisely because it does not have an associated template file (I think). Either way, I agree; this can just be green to go IMHO.
LingSIG can provide a better one if and when they want ...

**Comment by jamescummings** [comment]
@laurentromary  Sounds great! Adding back in a new ODD should be just as simple, if it appears before we've got around to removing it, that is good as well. (We're planning a release before your meeting, so it may disappear for that release and back in the next with your upgraded documentation and examples.)

**Comment by laurentromary** [comment]
No problem with this. I acknowledge the current one is not very helpful.

**Comment by martinascholger** [comment]
@laurentromary: did you get a chance to discuss this in your meeting?

**Comment by laurentromary** [comment]
@ttasovac and I are maintaining two ODDs now under: [https://github.com/DARIAH-ERIC/lexicalresources](url). They correspond to the work carried out in the TEI Lex 0 group (very restrictive two act as a reference target format) and the ODD corresponding to the TEI serialization of LMF (aka ISO 24613-4; mapping precisely all components of parts 1, 2 and 3)

**Comment by martindholmes** [comment]
This ticket has become two things: a simple decision to remove tei_dictionaries.odd from the Exemplars, which anyone could do in ten seconds, and a tracker for progress on the creation of its successor, which will be a long process, I think. Can we just go ahead with the removal and open a new ticket for the replacement issue?
