### ISSUE TITLE
WD Chapter: references to Unicode BIDI algorithm need a little attention

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1573]
Deborah Anderson pointed me at an upcoming (not yet approved) revision to the Unicode BIDI algorithm (http://www.unicode.org/reports/tr9/tr9-36.html); we refer to it in Ch 5 Characters, Glyphs and Writing Modes (WD), particularly in Writing Modes (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html#WDWM), so we should take a look at the revisions and see whether they require an update to our advice. I suspect not -- the changes appear to be in the direction of stressing the use of CSS over markup for HTML5 (which lacks mechanisms previously used in HTML4), and I think this approach aligns pretty well with what we were recommending for P5 XML.

**Comment by hcayless** [comment]
Not much to change, really. Updated a couple of references.
