### ISSUE TITLE
ref attribute of dataRef element mis-defined

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1575]
`@ref` of `<dataRef>` is defined as 'teidata.xmlName' instead of 'teidata.pointer'. Smells like a copy-and-paste error.
I am considering this a corrigible bug, and will be fixing it almost immediately.

**Comment by sydb** [comment]
Fixed in b52e97f, presuming Mr. Jenkins is happy. (Or at least, as happy as he was before this.)

**Comment by lb42** [comment]
Not a cut and paste error imho. Its deliberate. The attribute supplies a name, not a pointer.

**Comment by lb42** [comment]
Not a cut and paste error imho. Its deliberate. The attribute supplies a name, not a pointer.

**Comment by sydb** [comment]
What? The `<desc>`s of both the attribute and its parent element (`<dataRef>`) say it is a pointer, and I could swear on a ton of copies of P3 that you yourself told me that the system was to be:

- `@key` = named reference to datatype defined within the ODD
- `@name` = a namespaced name that refers to a datatype defined outside the ODD (typically W3C)
- `@ref` = a pointer (i.e., URI) to a datatype

I even recall having a discussion (w/ you? w/ Hugh?) about whether we could get away with rolling `@ref` and `@name` into one, because a namespace prefix is sorta like a local URI scheme.

But, perhaps most importantly, that's exactly what 22.4.5.1 says (“by referencing its URI within some other datatype library”).

**Comment by lb42** [comment]
Ooops, sorry, my bad. I read too hastily and thought you were talking about @name, not @ref.
Ignore me.

**Comment by sydb** [comment]
Ignored
