### ISSUE TITLE
floatingText being ignored inside p: abstract model violation

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1578]
When `<floatingText>` is set inside a `<p>`, higher-level text structure inside the `<floatingText>` fires an abstract model violation. Here is an example:

````
<p>Have my readers any wish to see this billet-doux? I can show them (but in strict
                    confidence) a literal copy. It was addressed,
      <floatingText>
              <body>
                  <opener>
                    <address>
                          <addrLine>“For mistur jem browne</addrLine> 
                         <addrLine>“blaxmith by</addrLine> 
                         <addrLine>“S.”</addrLine>
                   </address>
                  </opener>
             </body>
        </floatingText>
</p>
 <p>The inside ran thus:—</p>
<floatingText>
             <body>
                  <p>“Mistur browne this is to Inform yew that oure parish playes
                        bramley men next monday is a week, i think we shall lose without yew. 
                       from your humbell servant to command</p> 
                <closer><signed>“Mary Allen.”</signed></closer>
          </body>
</floatingText>
</p>
```` 

This is an example which demonstrates a nesting of floatingText within body paragraphs: the pieces of a letter embedded in a prose narrative. The schematron error that fires indicates "Abstract model violation: p and ab may not contain higher-level structural elements such as div", where floatingText is not being recognized as fundamentally exceptional to the abstract model.

**Comment by lb42** [comment]
Why wouldn't you use `<quote>` for these? the chunks are hardly complete in themselves.
