### ISSUE TITLE
The <ref> element should allow model.biblPart in its content model

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1579]
With reaction to https://github.com/TEIC/TEI/issues/1431 we should allow model.biblPart inside the `<ref>` element. This would, amongst other things, allow `<citedRange>` inside `<ref>` and thus encourage use of `<ref>` for bibliographic references in running prose pointing to the full `<bibl>` in the bibliography.

**Comment by jamescummings** [comment]
The current members of model.biblPart are:

model.imprintPart [biblScope distributor pubPlace publisher] model.respLike [author editor funder meeting principal respStmt sponsor] availability bibl citedRange edition extent listRelation msIdentifier relatedItem series textLang

Currently inside ref element we are able to have lots of things but from that list the things ref has in common with model.biblPart is bibl itself.  It may be argued that all of these are not needed but I would suggest that it should have:

- biblScope (and maybe pubPlace/publisher.... but less certain about that)
- author editor
- citedRange
- edition
- extent
- msIdentifier
- series

which all plausibly occur in short form references in some systems and use cases. If doing this, the argument then is whether to add just these elements or all of model.biblPart to the content model of the ref element. It is probably easier to do the latter, hence why I suggest it.

**Comment by paregorios** [comment]
Yes, I'd like to be able to encode things like:

```xml
<p>The encoding approach outlined in the <bibl><title level="m">TEI
       Guidelines</title>, chapters <ref
       target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHFAX"
       ><biblScope unit="chapter">11.1</biblScope> "Digital Fascimiles"</ref> and
       <ref
       target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PH-transcr"
       ><biblScope unit="chapter">11.2</biblScope> "Combining Transcription with
       Facsimile"</ref></bibl> and should be followed by EpiDoc projects where
       appropriate.</p>
```

**Comment by hcayless** [comment]
Council has decided the when something is a bibliographic citation, then `<bibl>` is warranted. Closing.

**Comment by paregorios** [comment]
So, now I'm unsure how to deal with the case I offered above. @hcayless should I take the query to the TEI list?

**Comment by hcayless** [comment]
The substance of our conclusion was that `<bibl>` and `<ref>` represent two different kinds of thing which happen to overlap a little—that is, there's a set of cases where you could legitimately use either, but neither element is a sub-class of the other. I see what you want to do in the example above, but I'm not sure what you've got there is really a single `<bibl>`. I think it's a series of references, where the referent of first happens to contain the following two. 

To encode your example, you could do something like:

````xml
<p>The encoding approach outlined in the <bibl corresp="#TEI"><title level="m">TEI
      Guidelines</title></bibl>, chapters <ref
    target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHFAX"><bibl
      corresp="#TEI"><biblScope unit="chapter">11.1</biblScope>
      <title level="a">"Digital Fascimiles"</title></bibl></ref> and <ref
    target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PH-transcr"
      ><bibl corresp="#TEI"><biblScope unit="chapter">11.2</biblScope>
      <title>"Combining Transcription with Facsimile"</title></bibl></ref> and
  should be followed by EpiDoc projects where appropriate.</p>
````
assuming there's a proper bibliographic citation elsewhere for the TEI Guidelines with the `@xml:id` "TEI". This all depends on what you want to get out of the encoded document, of course. I don't think I'd bother with this level of precision.

The problem with putting bibl-stuff in ref, is that we'd be saying thereby that a ref is a kind of bibliographic reference, and while it can serve the perfectly legitimate use of linking mentioned works to works cited in a bibliography, it has all sorts of potential non-bibliographic uses as well.
