### ISSUE TITLE
teidata.xxx.xml files need minor cosmetic change

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1581]
The files containing specifications for TEI datatypes were all generated from a script which inserted as a side effect a namespace declaration on each child element for RELAXNG even though this is never used. Mea culpa. 

It would be a kindness if all those redundant xmlns:rng="http://relaxng.org/ns/structure/1.0" strings could be removed : they needlessly confuse the reader. (I use the singular advisedly, since the number of people reading TEI source code is not large. But neither is it non existent)

**Comment by peterstadler** [comment]
seems like a no-brainer and could be something for someone new to the world of editing spec files ;)
