### ISSUE TITLE
msDesc not member of att.docStatus

### ISSUE THREAD

**Issue by schassan** [TEIC/TEI#1583]
<msDesc> is a member of model.biblLike and therefore should be a member of att.docStatus

**Comment by peterstadler** [comment]
initiated by https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;e16dd761.1702

**Comment by hcayless** [comment]
@jamescummings and @martindholmes Seem to think this is a good idea in the referenced discussions. I'm assigning @scstanley7 as it should be a good learning experience. There's been no discussion so far, and if there is none in a week or two, I'd say this can be made green and done. 

Personally, I find it slightly odd, but unlikely to do any harm.

**Comment by scstanley7** [comment]
I'm going to mark this as go, since no one has voiced any negative opinions about this! @schassan, do you have a specific example that would be useful to include in the specs?
