### ISSUE TITLE
www.tei-c.org webserver serves XML files with wrong content-type

### ISSUE THREAD

**Issue by Conal-Tuohy** [TEIC/TEI#1584]
e.g. http://www.tei-c.org/release/xml/tei/odd/p5subset.xml is served as `text/plain` rather than `application/xml`, or even better, `application/tei+xml` as recommended by the Guidelines:

> [23.1 Serving TEI files with the TEI Media Type](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/USE.html#MEDIATYPE)
> 
> In February 2011, the media type application/tei+xml was registered with IANA for ‘markup languages defined in accordance with the Text Encoding and Interchange guidelines’ ([RFC 6129](https://www.rfc-editor.org/info/rfc6129)). We recommend that any XML file whose root element is in the TEI namespace be served with the media type application/tei+xml to enable and encourage automated recognition and processing of TEI files by external applications.

This has caused some minor problems for me with software which refuses to parse XML documents which claim to be plain text.

**Comment by raffazizzi** [comment]
@Conal-Tuohy it is now served as `text/xml`. Does this solve the issue?
CURL output:
```
$ curl --head https://www.tei-c.org/release/xml/tei/odd/p5subset.xml
HTTP/2 200 
server: nginx/1.10.3
date: Thu, 30 Jan 2020 20:23:56 GMT
content-type: text/xml
content-length: 3830765
last-modified: Wed, 17 Jul 2019 03:45:24 GMT
etag: "5d2e99d4-3a73ed"
accept-ranges: bytes

```

**Comment by Conal-Tuohy** [comment]
To be honest I have forgotten the actual problem I was having, so I can't be absolutely sure if this would fix it. But "text/xml" certainly _should_ be OK.
