### ISSUE TITLE
time to retire macro.anyXML

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1585]
Now that we have `<anyElement>`, we don’t have any use for `macro.anyXML`; and, in fact, we do not use it. (It occurs once in p5subset: its definition.)

On the other hand, users may have ODD files that make use of this quite handy construct. So perhaps we want to deprecate it rather than just yank it out.

**Comment by lb42** [comment]
Or add it to the list of things you change when you update your ODD to use pure ODD constructs.

**Comment by hcayless** [comment]
I think deprecation is the way to go.

**Comment by lb42** [comment]
Deprecate away, by all means. I'd give it a max period of a month. People don't revisit their ODDs very often, so whatever period you give it someone is going to fall over the problem some day. I'll add it to the checklist in my purifyODD tutorial anyway.

**Comment by sydb** [comment]
Done. (Commit 2084b6d.) I gave it until 2018-06-12. (And added a reminder to my calendar to remove it. :-)
