### ISSUE TITLE
Chapter 23 keeps using the word "disjoint"

### ISSUE THREAD

**Issue by cmsmcq** [TEIC/TEI#1587]
Chapter 23 uses the term "disjoint" several times.  I do not think it
means what the chapter currently thinks it means.

Section 23.3.1.2 Renaming of Elements says in part

>   Although [renaming using altIdent] is an inherently unclean
    modification (because the set of documents matched by the
    resulting schema is disjoint with the set matched by its
    unmodified equivalent), ...

The parenthetical clause entails the proposition

>   Given two schemas A and B, where A selects some modules and
    elements from the TEI and makes no other changes, and B selects
    the same modules and elements, and additionally renames some
    elements using altIdent, the set of documents valid against A and
    the set valid against B are disjoint.

This is not true.  Consider (A) a selection of the TEI including only
the four basic modules, and (B) the same selection with additionally a
renaming of 'hi' as 'italic'.  Every document valid against A which
contains no instances of 'hi' is valid against B.  It follows that the
two sets of valid documents defined by the two schemas are not
disjoint.

I think what is meant is that documents valid against the modified
schema B are not guaranteed to be valid against the unmodified schema
A, or equivalently that B is not guaranteed to (almost certainly will not)
define a subset of A.

In 23.3.1 Kinds of Modification, the text says

>   Alternatively, the set of documents considered valid by the
    original schema might be disjoint from the set of documents
    considered valid by the modified schema, with neither being
    properly contained by the other.

In 3.3.1.3 Modification of Content Models, the text says

>   The set of documents matching the schema which results from such
    changes is likely to be disjoint with the set of documents
    matching the unmodified schema, and such changes are therefore
    regarded as unclean.

Two sets A and B are disjoint if their intersection is the empty set,
i.e. no element is a member of both A and B.  Being disjoint is not
the same as not being in a subset/superset relation.  Any textbook
covering the basics of set theory should allow you to confirm this
usage; I'll limit myself to pointing you to
http://mathworld.wolfram.com/DisjointSets.html

**Comment by lb42** [comment]
Guilty as charged, The word "disjoint" should be stricken/extirpated/beaten to a pulp wherever it appears in this chapter. It's trying to be clever about what is basically a very simple issue: what kind of modifications are considered to  be extensions of the TEI rather than simple subsetting, It's not entirely obvious what counts as a subset, but neither is it as complicated as all that. For example, a change from @type = any string to @type="a" or "b" is a subset, since the latter is still valid in a schema which uses the former definition. A change to @type= at least three integers probably isn't (depending on your definition of "any string").

**Comment by cmsmcq** [comment]
Good point about the subset relation.

I think there are two plausible, intellectually coherent answers to the question about how to define the subset relation.  We can define the subset relation on serialized XML documents (sequences of characters), or on the typed structures we can get by parsing them and validating them against the schema.  

(1) If every serialized document instance D valid against schema A is also valid against schema B, then L(A) is a subset of L(B).

(2) If every typed tree structure produced by validating some document D against schema A could also be produced by validating some document D' against schema B, then L(A) is a subset of L(B).

One can vary (2) by insisting that D and D' be the same document, not potentially different documents, or by allowing some variations of type.  If L(A) contains trees with sequences of three xs:positiveInteger values, and the corresponding bits of trees in L(B) have sequences of three xs:integer or xs:decimal values, for example, then we might want to call L(A) a subset of L(B) because positiveInteger is a subtype of integer and decimal.  Or not.

In case (1), restriction of an element or attribute from xs:string to lists of three or more integers would produce a subset (since every serialized element or attribute parseable as containing three or more integers can also be parsed as a string).  In case (2), no subset relation would hold.

For a vocabulary that wants to use Relax NG as a schema language, however, approach (2) has the drawback that RNG doesn't define validation as producing typed structures; it's one of the ways in which RNG differs from XSD.  XSD does define typed structures, so in an XSD world one could express (2) in terms of the PSVI.  One could define an analogous body of information as the output of validation against an RNG schema, but (apart from the danger of thunderbolts emanating from James Clark and Murata Makoto) it might be tricky to define a good subset relation on those trees, since RNG is non-deterministic.  There is no guarantee that a given element will have only one type, and also no guarantee that an RNG validator will find all applicable types.  

So I don't think (2) is really a possibility, if TEI wishes to be either a Relax NG vocabulary or to be schema-language neutral.

(That said:  I don't think the problem with the word "disjoint" here is that it's trying to be clever.  The problem is that it doesn't have the required meaning.  The word "disjoint" is perfectly fine, when one is talking about disjoint sets.)

**Comment by lb42** [comment]
There are 3 occurrences of "disjoint" in this chapter. Here are my proposed revisions for each paragraph. 

(1) second paragraph in div[@xml:id="MDMD"] "Kinds of modification"

In the first case, I've taken the opportunity to clarify that a TEI schema is built from any collection of TEI declarations, not just from whole modules and revised the wording quite a bit too. 

Currently reads:
~~~~
<p>Each kind of modification changes the set of documents that will be considered valid
according to the resulting schema. Any combination of unchanged TEI modules may be
thought of as defining a certain set of documents. Each schema resulting from a modified 
combination of TEI modules will define a different set of documents. The set of documents
 valid according to the unmodified schema may or may not be properly contained in the set 
of documents considered to be valid according to the modified schema. We use the term
<term>clean modification</term> to describe a modification which regards as valid a 
subset of the documents considered valid by the same combination of TEI modules 
unmodified. Alternatively, the set of documents considered valid by the original schema
might be disjoint from the set of documents considered valid by the modified schema, with
 neither  being properly contained by the other. Modifications that have this result are called
 <term>unclean modifications</term>. Despite this terminology, unclean modifications
are not particularly deprecated, and their use may often be vital to the success of a project. 
The concept is introduced solely to distinguish the effects of different kinds of modification.</p>
~~~~

Proposed revision:
~~~~
<p>Each kind of modification changes the set of documents that will be
considered valid according to the resulting schema. A schema derived
from any combination of unmodified TEI declarations (an "unmodified
schema") may be thought of as defining a certain set of documents.  A
schema deriving from a combination of modified TEI declarations (a
"modified schema") will define a different set of documents. The set
of documents valid according to the modified schema may or may not be
properly contained by the set of documents considered to be valid
according to the unmodified schema. We use the term <term>clean
modification</term> for the former case, where the set of documents
defined by the modified schema is a proper subset of the set of
documents defined by the unmodified schema.  Where this is not the
case, that is, where the modified schema considers valid some
documents which the unmodified schema does not, or the reverse, we use
the term <term>unclean modification</term>. Despite this terminology,
unclean modifications are not particularly deprecated, and their use
may often be vital to the success of a project.  The concept is
introduced solely to distinguish the effects of different kinds of
modification.</p>
~~~~

For the other two cases, I've contented myself with a minor correction:

(2) penultimate paragraph in div[@xml:id="MDMDNM"] "Renaming of elements"
In the second sentence, change "disjoint with" to "not contained by"

(3) last paragraph in div[@xml:id="MDMDCM"] "Modification of Content Models"
In the second sentence, change "likely to be disjoint with" to "unlikely to be contained by"

**Comment by ebeshero** [comment]
I just read over your revisions, and though I hope one or two instances of "disjointedness" remain because I like the quirky word, I think these revisions are clear and precise.

**Comment by cmsmcq** [comment]
Changes (2) and (3) look good to me.  

In change (1), the reference to a set of unmodified modules has been replaced by a reference to unmodified declarations; to this reader, that seems an unhelpful change.  An ODD with a list of module references is a very simple way to specify a TEI-based schema; specifying 'include' or 'exclude' attributes will feel like a distinct and more difficult step to many users (or so it says  here).  If the schema made from a set of unqualified module references is not mentioned as a point of reference, the following discussion of the effect of excluding elements from the schema seems to lost much of its point.  So this change strikes me as an non-improvement.  But it does not render any statements in the paragraph false, and if the observations in this paragraph do not persuade you, I don't expect to pursue the matter.

Also in change (1), in the sentence

> Where this is not the case, that is, where the modified schema considers valid some
documents which the unmodified schema does not, or the reverse, we use the term <term>unclean modification</term>.

the phrase "or the reverse" seems to me problematic.   I take "the reverse" to denote cases where the modified schema considers invalid some documents which the unmodified schema considers valid.  But those cases will inevitably arise when a clean modification accepts a proper subset of the documents accepted by the unmodified schema, instead of accepting exactly the same set of documents.  I think the fix is to delete the phrase "or the reverse,".

**Comment by lb42** [comment]
Happy to remove "the reverse" and thanks for spotting the error which introduced it. Not so happy about your other proposal though: while simply supplying a list of moduleRefs is indeed one simple way of specifying a schema, so is simply supplying a bunch of elementRefs. Indeed, it's arguably simpler. And where is the "here" which claims that include/exclude attributes are too difficult?  The "following discussion of the effect" you mention probably also needs some attention in light of my proposed change, but I still think it's a necessary change. We need to cure people of this module-obsession.

**Comment by cmsmcq** [comment]
> On Mar 15, 2017, at 10:58 AM, Lou <notifications@github.com> wrote:
> 
> … And where is the "here" which claims that include/exclude attributes are too difficult? 

Sorry for my lack of clarity.  In my idiolect, “it says here” is a more polite way of saying “I am telling you now once and for all”; it’s the rough equivelent of “imho”.

Only I didn’t say “too difficult”.  I said “distinct [from] and more difficult” than just a series of moduleRef elements.  Since for some (including me) an ODD that just has some module refs is an important first step (which may be the only step, for some time), I think it’s worth identifying the class of ODDs of that description, and the class of schemas they generate, as a class.  Some users will be thinking about those classes of ODD and schemas, whether you want them to or not; why pass up an opportunity to help the reader find their way?

> The "following discussion of the effect" you mention probably also needs some attention in light of my proposed change, but I still think it's a necessary change. We need to cure people of this module-obsession.

Well, that would be the reason I was looking for.  If you believe that thinking about modules is an illness of which people need to be cured, it is not surprising you don’t want to retain the current text’s apparent distinction between ODDs that select some modules and ODDs that make a finer-grained selection.  I don’t see it at the moment.  But that’s a topic for another time, perhaps.

**Comment by lb42** [comment]
There is a class of users for whom defining an ODD initially as just a handful of elementRefs is a lot more attractive than figuring out which modules they will need to specify in order to get them. Fair enough, they do need to know that they will always need the tei and (some of) the header module, but that's it. How nice to be able to say I want body, ab, and seg please, without working out which modules they are in.

**Comment by jamescummings** [comment]
@lb42 Does that work with our current processing? I thought you always had to specify module in getting them. 

The proposed rewordings above looked fine to me.

**Comment by lb42** [comment]
@jamescummings Yes. I do it all the time.

**Comment by lb42** [comment]
Proposed wording changes have been implemented.

**Comment by lb42** [comment]
Closing after changes at 2123dd554c0c166421d550e571a619c6783f9406
