### ISSUE TITLE
schemaSpec/@source example missing

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#1593]
While the Note prose in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-schemaSpec.html explains how to build @source values, no example is provided except for @source="tei:current". An example with a version number should be added.

**Comment by lb42** [comment]
There are examples in the class spec for att.global.source from which this attribute is derived. But no harm in duplicating them here, I agree.

**Comment by raffazizzi** [comment]
@TEITechnicalCouncil ok with duplicating the example?

**Comment by sydb** [comment]
Well, no objection, but I think we can do better. First off, the example that is already there is a little confusing, no? What is the difference between the “current version” (used for drama & core) and the “current release version” (used for header)?

In any case, seems to me a somewhat realistic example is in order. Except for testing, has anyone actually used a different `@source` on a single `<moduleRef>` or `<elementRef>`? Personally I only use `@source` on `<schemaSpec>`, and think that’s what an example should show.

**Comment by lb42** [comment]
There's some examples of using @source on a variety of elements in my ODD chaining tutorial ( Documents/pureODD/howtoChain.xml ) : feel free.

**Comment by jamescummings** [comment]
Council F2F subgroup marks it as green to go. Repurpose Lou's example.

**Comment by martindholmes** [comment]
The example from the end of Lou's tutorial on ODD chaining would probably be good, with a little explanation:

http://teic.github.io/PDF/howtoChain.pdf
