### ISSUE TITLE
Decidability of subset relations on schema-defined languages (error in 23.4.5)

### ISSUE THREAD

**Issue by cmsmcq** [TEIC/TEI#1595]
In P5, 23.4.5 Documentation Constraint reads in part:

> A schema can constructed simply by combining the predefined schema language fragments corresponding with the required set of TEI modules and other statements in the relevant schema language. The status of such a schema with respect to the tei_all schema cannot however be determined, in general; it may therefore be impossible to determine whether such a schema represents a clean modification or an extension.

This appears to be claiming that the subset relation on schema-defined languages is undecidable; I think that's correct for schema languages which include constraints expressed with arbitrary XPath expressions (Schematron, XSD 1.1), but not for other languages.  For languages with sufficiently expressive referential integrity constraints (ID/IDREF in DTDs or extended RNG, uniqueness, key, and keyref constraints in XSD), not just the subset relation but the satisfiability of the schema (the existence of valid instances) can be difficult.  But for schema languages like pure Relax NG, DTDs without #FIXED values for ID and IDREF attributes, or XSD without referential integrity constraints, I think the subset relation is clearly decidable, since it amounts to starting from the intended root elements and recursively testing the subset relation on content models (which are, in RNG, XSD, and DTDs, regular languages).

I think the quoted paragraph would be less misleading and equally persuasive if:
* The word _easily_ were inserted between _however_ and _be determined_.
* The word _impossible_ were changed to _impractical_.

**Comment by lb42** [comment]
The proposed changes are anodyne enough. However,  note that this whole section is about the "predefined schema fragments" which I am not sure the TEI will continue to support.  The recommended way of customizing is not to grab core.rng and header.rng and munge them together with your own RNG code, but rather to write an ODD.

**Comment by lb42** [comment]
I've made this green and will apply the proposed wording changes this weekend

**Comment by lb42** [comment]
Revised sentence to " However, the status of such a  schema with respect to the &lt;ident type="schema">tei_all</ident> schema cannot in general be  easily determined; it may therefore be impractical to ...."  at 6d4ab95..d6ca3d4
