### ISSUE TITLE
msName should allow name and rs in content model

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1597]
Currently msName http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msName.html  has a content model of macro.xtext This allows text and gLike elements. However some manuscript names contain referring strings such as names of people or places which it would be useful to mark up. This especially occurs in names of manuscripts in legal settings where the manuscript is given the same name as the court case.  For example:

````
<msIdentifier>
    <settlement>Kew</settlement>
    <repository>The National Archives</repository>
    <idno type="shelfmark">STAC 8/20/24</idno>
    <msName>Bill of Complaint in <rs
            ref="http://ereed.library.utoronto.ca/eats/entity/7513/"
            type="Person_Male">Gillam</rs> v. <rs
            ref="http://ereed.library.utoronto.ca/eats/entity/7631/"
            type="Person_Male">Church</rs></msName>
</msIdentifier>
````

In this case the manuscript is known as "Bill of Complaint in Gillam v. Church" While the text itself could be recorded as such it is very useful in digital resource creation to be able to link the names to further information about them.  This is especially useful in situations like this where 'Church' might be confused with an organisation rather than an individual. ;-)  Manuscript names are not, and should not be, as locked down as `<idno>`.

Proposal: I propose to add `<name>` and `<rs>` to the content model of msName in alternation with macro.xtext.  I'm specifically not suggesting adding model.nameLike since that will allow all these elements: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.nameLike.html which seems like overkill.  I'd rather respect the desire for purity in such manuscript names but simultaneously give some way to have an element which points out to other resources from its mixed content.

**Comment by lb42** [comment]
If you consider that an msName is just a fancy kind of name, then it would be plausible for it have the same content model as other kinds of name. But you seem to wanting to make a special case of it. Why not g o the whole hogge?

**Comment by jamescummings** [comment]
Hi @lb42.  You are right that is what I'm doing.  I guess I'm just afraid of fallacious slippery slopes.  The manuscript identifier is quite tightly controlled metadata, rather than transcription, and so I feel it would be doing a disservice to those who designed it (including you, matthew, and others) to just allow anything here. i.e. macro.phraseSeq here seems wrong to me because of all the editorial markup that would allow. My only need here is to be able to mark people's names inside it, I guess I could imagine uses for other model.nameLike content or dateLike elements, but I find it hard to believe people want to use model.graphic, model.pPart.transcriptional, model.lPart, model.pPart.editorial, model.phrase.xml, etc. etc. Since none of those really belong in the name of a manuscript in a metadata setting. I don't want to open the floodgates but am not sure precisely what the limitations should be.

**Comment by jamescummings** [comment]
Any other comments by others, other than that I'm being too conservative?  (I'd say let's let in name/rs and if other people come asking for more things there then add those at that point.)

**Comment by jamescummings** [comment]
Having left 2 months for comments I'm marking Status: Go and will implement just `<rs>` for now. If subsequent requests come in for other elements then we should re-examine msName content model as a whole.
