### ISSUE TITLE
P5 Makefile no longer works offline

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1602]
It used to be possible to build P5 using locally installed versions of the ODDs and Stylesheets and the supplied Makefile. This is no longer possible: the process falls over when trying to do odd2odd on the p5examples-odd file, apparently because it is looking for the p5subset.xml generated by the previous step not locally but in the current release. I tried to work out why, but lost heart amongst the intricacies of Syd's code superimposed on Sebastian's. 

Being able to build offline is quite important for two (largely orthogonal) sets of users: those on airplanes, and those in remote French villages where the Internet has been blown away by high wind or other disruptions.

**Comment by jamescummings** [comment]
Have you tested that the defaultSource parameter doesn't fix this? (i.e. if you point to a local source?)  I'm assuming so, just double-checking before looking at it further.  (And shouldn't this really be a Stylesheets bug?)

**Comment by lb42** [comment]
The defaultSource parameter is set to the current input directory by the P5 Makefile. I think. 

The Makefile isn't in the Stylesheet directory, so I assumed that this isn't a Stylesheet issue.

**Comment by jamescummings** [comment]
I think that is what I'd test first at least, but you are probably right.  And good point, I guess the Makefile questions do below here.

**Comment by hcayless** [comment]
What are you trying to build? I can build the HTML documentation offline, for example, but there do seem to be some hard dependencies on web resources that we should probably fix. What make command are you issuing? Or is it just 'make'?

**Comment by lb42** [comment]
Just make ... preceded by make clean the next time roind

**Comment by hcayless** [comment]
Mine fails too, though not at that spot. There are several exemplars that make direct reference to remote RNG schemas (probably solvable if you set up a catalog), and there's at least one test that tries to curl the p5subset.xml from the tei-c site (!?). I agree it would be nice to be able to run the build offline. And I'm quite sure it used to work too.

**Comment by lb42** [comment]
Are you saying that you succeeded in building the p5odd-exemples.odd schema when offline? If so, you are either using black magic or maybe not using the same set up as me.

**Comment by hcayless** [comment]
Removed absolute refs to www.tei-c.org in exemplars and wrapped the one test that insists on fetching stuff from the site in a condition that checks if the site is reachable. Make runs to completion while I'm offline now.
