### ISSUE TITLE
TextNode should not be a child of dataype

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1603]
Re discussion in TEIC/Stylesheets#236. The content model of dataype should not include textNode. The only question is whether a deprecation period is necessary. It's a recent error, and there's a straightforward fix: change `<textNode/>` to `<dataRef key="teidata.text"/>`.

**Comment by raffazizzi** [comment]
I don't think a deprecation period is necessary since it's a recent error. I would be keen on acting soon, however.
@TEIC/tei-technical-council  any objections?

**Comment by sydb** [comment]
Once released, I don’t think recentness pulls much weight.

If I understand correctly, there is no syntactic difference (both `<textNode>` and `<dataRef key="teidata.text"/>` permit a string of 0 or more Unicode characters), only the semantic difference that the former incorrectly implies the existence of a text node in a place where there cannot be one. So I am in favor of considering this a corrigible error and fixing immediately without further ado. (I.e., w/o deprecation, w/o comment or notification on the list.)

**Comment by sydb** [comment]
Done. (I.e., as of commit 9560f59, `<datatype>` is no longer allowed to have a `<textNode>` child.)

I checked for `//datatype/textNode` in the _Guidelines_, and did not find any. I would hope Mr. Jenkins agrees, but he’s too busy being upset about building PDF right now. (See #1598.)
