### ISSUE TITLE
dataRef should not permit @restriction and @key 

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1606]
It appears that a restriction can only be applied to a datatype defined using  @name on dataRef. This is presumably because a dataSpec (indicated by @key) might itself have a restriction. The documentation needs to clarify this, and maybe a constraint needs to be added to the spec for dataRef

**Comment by sydb** [comment]
@lb42: We (a Council subgroup looking at this ticket) are not quite sure what you are saying, here. We **think** it is that `@restriction` should not be allowed in combination with `@key`. That leads to two questions:
* Why not? Is there a reason to prevent an ODD from saying “this datatype is just like teidata.duck, except restricted as indicated”? Or are you saying it doesn’t work in current ODD processing, and we’re not about to make it work anytime soon, so it should not be allowed?
* Should `@restriction` be allowed with `@ref`?

**Comment by lb42** [comment]
The documentation should make clearer that @restriction is only allowed in combination with @name, i.e. it's not permitted in combination with either @ref or @key. There is already a comment to that effect about the use of &lt;dataFacet> which could usefully be amplified to clarify that the datatype specified by @name or @ref can be further modified either by @restriction or by a child  &lt;dataFacet> but not both. (We should also provide guidance as to when dataFacet is preferable to @restriction and vice versa)

The reason for this, and the reason for not permitting any modification on &lt;dataSpec, is to simplify processing : my thinking was that a dataSpec should contain only a dataRef expression customized to your needs: and if you want to modify the meaning of a dataSpec you need to make a new dataSpec. Otherwise you have a potential chain of constraints (possibly mutually contradictory) to apply.

**Comment by sydb** [comment]
@lb42 : In the 1st sentence above you say that `@restriction` is not allowed in combination with either `@ref` or `@key`. But in the second you say that “…the datatype specified by `@name` or `@ref` can be further modified … by `@restriction`…”. Which is it for `@ref`, then?

**Comment by ebeshero** [comment]
Council F2F agrees with the recommendation to not permit `@restriction` with `@key`.
