### ISSUE TITLE
sequence has no listRef

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1608]
The definition of `<sequence>` does not contain a `<listRef>`.

**Comment by sydb** [comment]
And for that matter, the `@preserveOrder` attribute is **never** mentioned anywhere in the _Guidelines_.

**Comment by lb42** [comment]
Hardly surprising that it doesn't work then! My guess is that this is one of those gestures (like the late lamented &lt;interweave> element) put into the pure ODD spec in the hope that one day we'd have schema languages able to implement them.

**Comment by hcayless** [comment]
Can we quietly lose `@preserveOrder` then? It's confusingly documented too. I assume it's to allow "these elements can occur in any order"? The description sounds like the opposite.

**Comment by lb42** [comment]
I dont have any problem with the description myself, but that's probably because I wrote it.

**Comment by lb42** [comment]
Anyway, I've now added references to the appropriate section of TD both for this element and for &lt;alternate>, which was the original point of this ticket, so I think it should be closed.

**Comment by hcayless** [comment]
As written, it sounds like setting it to true means `<sequence>` is doing something different than normal, but surely the default behavior is that order matters? I'm in favor of losing it for now, and thinking further about whether we need a construct for non-ordered content models. I can imagine that might be useful, and I guess you could check it with Schematron.

**Comment by lb42** [comment]
I dont see what's wrong with "if true, indicates that the order in which component elements of a sequence appear in a document must correspond to the order in which they are given in the content model.". Would you be less confused by "if false, indicates that the order in which component elements of a sequence appear in a document may not correspond to the order in which they are given in the content model." ?
I think it would be a shame if ODD did not provide a way of doing what we used to do in DTDland with the ampersand connector.Maybe we need to raise a separate ticket for "things we'd like to do in ODD which haven't been implemented yet" (which could include &lt;interleave> for example)

**Comment by hcayless** [comment]
There are two things I don't like about it: 1) if absent, it means the same thing, 2) "sequence" implies order. If we're going to have an un-ordered construct, I'd prefer it have a different name. "Set" maybe?

**Comment by lb42** [comment]
If absent it means whatever the default value is, but that's a function of using default values. I agree that "sequence" usually implies order though; maybe we should have named this element "allOf" or summat, since it's meant to contrast with "alternate". 

"set" is already taken, I fear.

**Comment by sydb** [comment]
I’m completely w/ Hugh:
1) I do not like building reliance on a default value here while simultaneously trying to rid ourselves of such things in the rest of the _Guidelines_, and
2) I do not like using the GI `sequence` to indicate an unordered set.

**Comment by lb42** [comment]
I'm not (I hope) particulary "w/out" Hugh. But I do think this discussion should be going on on a different ticket, since the purpose for which this one was raised has been disposed of.

**Comment by sydb** [comment]
Fixed Thu 2017-05-18 by @lb42 in #48597130671315b63e83053116eca3534c5c7b84
