### ISSUE TITLE
pure exemplars

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1609]
At some point we should purify the ODD files in P5/Exemplars/. Many still have elements from the RELAX NG namespace.

All, in order of # of RELAX NG elements:
~~~~~
P5/Exemplars/isofs.odd:            0
P5/Exemplars/tei_all.odd:          0
P5/Exemplars/tei_bare.odd:         0
P5/Exemplars/tei_corpus.odd:       0
P5/Exemplars/tei_dictionaries.odd: 0
P5/Exemplars/tei_docs.odd:         0
P5/Exemplars/tei_drama.odd:        0
P5/Exemplars/tei_lite_fr.odd:      0
P5/Exemplars/tei_minimal.odd:      0
P5/Exemplars/tei_ms.odd:           0
P5/Exemplars/tei_simplePrint.odd:  0
P5/Exemplars/tei_speech.odd:       0
P5/Exemplars/tei_math.odd:         1
P5/Exemplars/tei_svg.odd:          2
P5/Exemplars/tei_lite.odd:         3
P5/Exemplars/tei_allPlus.odd:      4
P5/Exemplars/tei_its.odd:          4
P5/Exemplars/tei_tite.odd:         8
P5/Exemplars/tei_xinclude.odd:    12
P5/Exemplars/tei_enrich.odd:      17
P5/Exemplars/tei_odds.odd:        32
P5/Exemplars/tei_jtei.odd:        53
~~~~~
Only those w/ RELAX NG elements, in alphabetical order:
~~~~~
P5/Exemplars/tei_allPlus.odd:   4
P5/Exemplars/tei_enrich.odd:   17
P5/Exemplars/tei_its.odd:       4
P5/Exemplars/tei_jtei.odd:     53
P5/Exemplars/tei_lite.odd:      3
P5/Exemplars/tei_math.odd:      1
P5/Exemplars/tei_odds.odd:     32
P5/Exemplars/tei_svg.odd:       2
P5/Exemplars/tei_tite.odd:      8
P5/Exemplars/tei_xinclude.odd: 12
~~~~~

**Comment by rvdb** [comment]
(as of https://github.com/TEIC/TEI/commit/4a4cc532a80730bdb7f4f273f26f0be01a4a698f, tei_jtei.odd (which appeared to have been the Relax NG champion) has been purified)

**Comment by ebeshero** [comment]
See line 76 here: https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_svg.odd @lb42 Council asks: Have you worked out a clever way to do this in Pure ODD?

**Comment by martinascholger** [comment]
@hcayless, @sydb is there need for discussion, or can I mark this green?

**Comment by hcayless** [comment]
I think it’s not the highest priority, but no reason it shouldn’t be green.

**Comment by sydb** [comment]
This has mostly been done. Only tei_its.odd and tei_svg.odd have any elements from the RelaxNG namespace, and seems to me they need them.
The only remaining question is should we delete the "rng:" namespace declaration on the root element? It serves no purpose as the ODD sits there, but would be mildly useful to someone who needed to add some RelaxNG, saving them a step.
The following files have the rng: namespace declared, but never used:
~~~
isofs.odd
tei_all.odd
tei_allPlus.odd
tei_corpus.odd
tei_customization.odd
tei_dictionaries.odd
tei_docs.odd
tei_drama.odd
tei_enrich.odd
tei_its.odd
tei_jtei.odd
tei_lite.odd
tei_ms.odd
tei_odds.odd
tei_speech.odd
tei_svg.odd
tei_tite.odd
tei_xinclude.odd
~~~
(tei_tite.odd has it declared twice; tei_customization has it declared 353 times, but it is a generated file, so we don’t care about those declarations.)

I lean towards removing extraneous declarations, but don’t care much.

**Comment by lb42** [comment]
Remove redundant declarations.

**Comment by sydb** [comment]
Re-examination shows that (as mentioned above) only tei_its.odd and tei_svg.odd still actually _use_ the RNG namespace. tei_jtei.odd still _mentions_ it. 
About to remove the declarations from the others.

**Comment by sydb** [comment]
Should be closed as soon as Mr. Jenkins approves.
