### ISSUE TITLE
make get.xml more visible

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1610]
Among the various cool help files is get.xml, "Using the TEI GitHub Repository". In my blindness, I can only reach it by going to http://www.tei-c.org/Guidelines/P5/ and looking for the highlighted word "instructions". Would it not be nice if the file were linked at least from the side panel of that page, and potentially also under http://www.tei-c.org/Support/Learn/ ? 
I have just added the link to the TEIC/TEI README (commit 6c0756c2a56d1e49640b4894da0e6ea3c63f830e).

**Comment by hcayless** [comment]
This is a good idea. Think it may have to wait until the new site is available, which I'm told is back on track. So I'm going to mark it blocked for now.
