### ISSUE TITLE
Documents/Git-README.md: master or dev?

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1611]
This might require only a trivial fix, but I feel lost among the various branches of this repo and I'm afraid I can mess up. I find Hugh's "[Notes on using Git to edit the Guidelines](https://github.com/TEIC/TEI/blob/master/Documents/Git-README.md)" very useful, but I'm wondering if `master` is really the branch that should be mentioned there (isn't it `dev`)? I dare not attempt any fix by myself...  TiA!

**Comment by hcayless** [comment]
Change made. That document predates the switch to working primarily in dev.
