### ISSUE TITLE
Guidelines claim "element renamings into languages other than english" are provided

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1613]
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/USE.html#MDMDNM says:

"The TEI provides a systematic set of renamings into languages other than English. These all use a language-specific namespace."

I don't think this has ever been true.

I think this is a corrigible error and if no dissent is forthcoming, I'm happy to change it.

**Comment by lb42** [comment]
Unfortunately though, there is no way of modifying an element to put it into a different namespace : if you say, e.g. 
~~~~
<elementSpec ident="div" ns="http://mydiv.org" mode="change">
~~~~
you are saying you want to change the div element in the mydiv.org namespace. Or so I believe: certainly it has no effect.

**Comment by lb42** [comment]
It's untrue in the sense that there are no &lt;altIdent> elements in the current elementSpecs, and it's not clear whether we provide element name translations elsewhere. Maybe we did once?

**Comment by lb42** [comment]
Ah, I've remembered now what this passage must be vaguely talking about. In TEI P3 the names of all elements (and, I think, attributes) were supplied indirectly using parameter entities in the form %n.foo  and a file containing declarations of all those p.e.s was loaded first within the DTD subset. So you could change all your element names into say Japanese or Spanish simply by changing the file of p.e. declarations. I think when we moved to P4 someone (probably me or Sebastian) decided that doing something equivalent for XML would be too much work for too little demonstratable advantage (particularly as neither the Spanish nor the Japanese proofs of concept had been much used so far we could see).
However, we should still think about how to provide something like this facility properly. Multiple altIdents and some way to decide when to use them would seem the way to go for a future release of the stylesheets.

**Comment by jamescummings** [comment]
When I got there it looks like @lb42 had already commented this out. I believe at https://github.com/TEIC/TEI/commit/2123dd554c0c166421d550e571a619c6783f9406#diff-a83012fcead9f0a27418820a78090035L289 (for the record).  So I went in and removed commented out bit entirely at 5dda375a8ef47ff9d8fbed47ec2c8159956be934
