### ISSUE TITLE
the child of xenoData is apparently illegitimate...

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1614]
I am trying to use xenoData to record fragments of non-TEI markup. Can someone please tell me what gives, in the following?
  ```xml
  <xenoData>
    <query xmlns="http://ucnk.korpus.cz/intercorp/">
      <item>Query: word,[lc="haßt"|lemma_lc="haßt"] (243)</item>
      <item>Switch KWIC: -intercorp_v8_en (243)</item>
      <item>Positive filter: 0 0 1 [] (57)</item>
      <item>Switch KWIC: -intercorp_v8_de (57)</item>
      <item>Switch KWIC: -intercorp_v8_pl (57)</item>
      <item>Positive filter: 0 0 1 [] (36)</item>
      <item>Switch KWIC: -intercorp_v8_de (36)</item>
      <item>Shuffle: enabled ()</item>
      <item>Positive filter: 0 0 0 [#80840865]|[#83769651] (2)</item>
    </query>
  </xenoData>
```
I understood that the trick was to put these elements into a non-TEI namespace, which I believe I did (?). Jing tells me, "element "query" not allowed anywhere; expected the element end-tag or text". I've tried predeclaring prefixes, or declaring the foreign namespace at the level of `xenoData` and then predeclaring `tei:` and going `tei:xenoData`, but I just keep seing those red wavy snakes under `<query`, no matter what.
And I keep getting the impression that it's the `<query>` element _alone_ that poses problems. The `<item>` elements are marked as errors only if I put them into the TEI namespace, otherwise jing is fine with them.

**Comment by lb42** [comment]
Works fine for me -- validating in latest oXygen against tei_all -- what schema are you using? also can you post the complete document exhibiting the problem?

**Comment by bansp** [comment]
Thank you :-(
I'm chaining the ODD for this via the standoff customization, let me check if it does some macro-related magic or something like that (sigh). If I can't find anything then I will try with some TEI-blessed ODD and will be sure to post here or close this ticket. Thanks again for the quick verification!

**Comment by bansp** [comment]
A quickie, if I may. The following is a snippet from the standoff ODD:

```xml
                <!-- Need to exclude our namespace from egXML to prevent "conflicting ID-types for attribute" errors -->
                <macroSpec ident="macro.anyXML" mode="change" module="tagdocs">
                    <content>
                        <rng:element>
                            <rng:anyName>
                                <rng:except>
                                    <rng:nsName ns="http://www.tei-c.org/ns/1.0"/>
                                    <rng:name ns="http://www.tei-c.org/ns/Examples">egXML</rng:name>
                                    <rng:nsName ns="http://standoff.proposal"/>
                                </rng:except>
                            </rng:anyName>
                            <rng:zeroOrMore>
                                <rng:attribute>
                                    <rng:anyName/>
                                </rng:attribute>
                            </rng:zeroOrMore>
                            <rng:zeroOrMore>
                                <rng:choice>
                                    <rng:text/>
                                    <rng:ref name="macro.anyXML"/>
                                </rng:choice>
                            </rng:zeroOrMore>
                        </rng:element>
                    </content>
                </macroSpec>
```
Can this be the root of my problem?

**Comment by lb42** [comment]
Yes. You don't wanna do that. The TEI is about to remove macro.anyXML in favour of the all singing all dancing &lt;anyXML> element provided as of two releases ago.

**Comment by bansp** [comment]
Hah, so let me notify poor @peterstadler about this. Thanks so much, Lou! :-)

**Comment by bansp** [comment]
OK, so I'll be closing this issue, having cross-referenced it from the standoff repository.

**Comment by bansp** [comment]
PS. I hope you meant [anyElement](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-anyElement.html), @lb42. Can't see anyXML in the list of elements.

**Comment by lb42** [comment]
Oops yes. I did. Sorry. Was typing too fast.

**Comment by bansp** [comment]
Update: it seems that the redeclaration above isn't even noticed during ODD processing. When I compiled an ODD with the macroSpec above commented out, there was no change. And consequently there was no change in the RNG compiled from the ODD that chains from the (compiled) standoff ODD. Which rather takes me back to square 1... Will investigate.

**Comment by bansp** [comment]
Actually, it seems a real problem caused by compilation/chaining. I have posted an [issue](https://github.com/TEIC/Stylesheets/issues/245) to the Stylesheets tracker, with a test suite.
