### ISSUE TITLE
chapter 23: notTEI vs. nonTEI

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1615]
In ch. 23 (could be elsewhere as well), the namespace for the addition of "foreign" objects to a customization varies freely between "...nonTEI" and "...notTEI". Not a biggie, of course, but deciding on a single value here might be appreciated by a careful reader.

**Comment by lb42** [comment]
There are four occurrences of "notTEI" which I propose to change to "nonTEI" in the interests of both consistency and euphony.

**Comment by bansp** [comment]
+1 from me :-)

**Comment by martinascholger** [comment]
+1 from me, there is also an example in chapter 22

**Comment by lb42** [comment]
Sorry, Martina, I didn't notice you had taken this ticket, and I already fixed it. There are no occurrences of "notTEI" in the current text.

**Comment by martinascholger** [comment]
That's fine, thanks :-)
