### ISSUE TITLE
dealing with multiple publication places

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1617]
Quite often (see even the TEI example under [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-publicationStmt.html](url)), a document is published at more than one place. In one of my use cases, I have patents typically published (or valid) un Europe, Japan,  the US etc. 
Therefore, it would be nice to have:
- `<pubPlace>` be part of the content model of  `<listPlace>`
- `<listPlace>` to be allowed wherever `<pubPlace>` is allowed (in particular in `publicationStmt)`
One may argue that you can just iterate over `pubPlace`, but in complex cases, this mechanisms would allow to structure publication places in groups (says EU countries, other countries, etc.) and type `<listPlace>` accordingly.

**Comment by lb42** [comment]
This wrecks the fragile semantics of the TEI distinction between name and referent. A pubPlace is  a kind of placeName, not a kind of place. A listPlace is a list of places, not a list of placeNames.

**Comment by laurentromary** [comment]
So which list would you use there? In many of my use cases, publication places happen to be .... places.

**Comment by lb42** [comment]
I would say that they happen to be *placeName*s, not places. What's wrong with 
~~~~
<list><item><placeName></item></list>
~~~~

**Comment by laurentromary** [comment]
But in the case they are places, could we at least have `listPlace` in `publicationStmt`. The discussion may be a little more complex then making a "distinction" between a name and a referent. When one annotates a text where you have strings you want to identify as names, this is quite a crystal clear situation. In metadata descriptions, hence in the header, you're not necessary marking up an existing string, but at times providing a precise description of an entity (referent) associated to the text. This is typically the tension we have for author in the header of a scholarly paper. For such element, I would argue for polymorphism rather than forcing a choice in one or the other direction.

**Comment by lb42** [comment]
Sorry, I hadn't fully grasped that you were talking about metadata. But I'm still not sure I agree. I am pretty sure you will have plenty of occurrences of the string "London" as a publication place across several documents. Would you tag them all as `<place>`? In which case what happened to the idea that the `<place>` is unique? Do you really want to imply that  the "london" of document x not the same as the "london" of document y?

**Comment by laurentromary** [comment]
Désolé pour anglais désastreux.
Well, in Metadata, especially when provided by publishers themselves, or central libraries, you do have some certainties.Even if you can think of some use cases where you would not, there are some use cases (I am not saying they are better of course ;-)) where you want to treat pubPlace as a a real place. If at least we could have some flexibility to have publicationStmt/listPlace/pubPlace we could make some progress for the corresponding applications.

**Comment by lb42** [comment]
Tu peux t'exprimer en francais si tu le preferes! Aber nicht in deutsch,  désolé. But I still don't understand what's wrong with the current model of publicationStmt : it does permit you to repeat pubPlace, provided each repetition is associated with an authority. Could you give an example where this is not suitable?

**Comment by jamescummings** [comment]
I'm still unclear why the following is not precisely what you want and is the recommended way for doing so:
```xml
         <publicationStmt>
          <publisher>Foolscap Publications</publisher>
            <pubPlace>London</pubPlace>
            <pubPlace>New York</pubPlace>
            <pubPlace>Hogwarts</pubPlace>
         </publicationStmt>
```

**Comment by peterstadler** [comment]
Council decides during f2f at Tokyo *not* to implement the requested changes for the reasons given. 

a) not to "wreck the fragile semantics of the TEI distinction between name and referent."
b) `<pubPlace>` is repeatable (without any list* wrapper)
