### ISSUE TITLE
chap23 : terminology

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1619]
Trying to define and deploy a consistent terminology for this chapter has been the subject of much effort in the past, and continues to haunt our discussion of it. This ticket is just to note a few very small changes I propose to make for consistency as regards the terms "modification", "personalisation", and "customization" (and syntactic variations thereon). 
The second two seem less problematic:  we actually imply that they are synonymous ("....impossible to use the TEI scheme without customizing or personalizing it in some way"); furthermore "personaliz*" only appears on two other occasions : "In the absence of any other kind of personalization..." and  "The TEI personalization mechanisms allow the user to control this behaviour".  I think both of these should be "customization" rather than "modification". We talk about the TEI "customization mechanism" and "an ODD customization"; and we use "modification" in a more technical context  where we are talking about or defining the effect that a customization has.

**Comment by martinascholger** [comment]
I agree with your arguments. Getting rid of the ambigious vocabulary by using "customization" would be an improvement.

**Comment by emylonas** [comment]
Agreed, for clarity that comes out of consistency and fewer terms. "Personalization" isn't defined, so best not to cause confusion. Is "modification" used loosely as well?

**Comment by lb42** [comment]
I have changed personaliz* to customiz* and will look at "modification" when we've decided what to do about clean/unclean.
