### ISSUE TITLE
xmp uses <ref> inappropriately?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1622]
In the tagdoc for att.global.linking ([3.1.0](http://www.tei-c.org/Vault/P5/3.1.0/doc/tei-p5-doc/en/html/ref-att.global.linking.html), [current](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.linking.html)), the 2nd example of `@corresp` uses `<ref>` (with an odd `@target`) where it should have `<placeName>` or nothing, no?

**Comment by bansp** [comment]
A stylistic issue (using the most generic referring element while others are possible) rather than error, surely? I could imagine that someone could argue that in the phrase "the city of London", "London" is a label that is part of the phrasal reference, so `<ref>` is a kind of non-committal approach.

**Comment by sydb** [comment]
Absolutely, @bansp , it is not outright **wrong** to encode with the most generic referring element, but I am a lot less confident that we should be exemplifying such inconsistent encoding. This is, after all, in a placeography that already uses `<placeName>` to encode the names of places elsewhere.

Besides, it still does’t explain the bizarre `@target` on that `<ref>`.

**Comment by martindholmes** [comment]
That's my example from our MoEML project, adapted from our documentation, and it absolutely is confusing. In the original source, the ref element is a straight link to a document called LOND1.xml (actually LOND5.xml, but I simplified the ids here). I should have changed that construct when using this as an example to point to a placeography. Feel free to fix. In MoEML there's no "placeography" document; every place has its own TEI file, with its id on the root TEI element. We can point to a "place" in various ways, depending on whether we're linking a placename in a primary source document to its corresponding place file, or referring in a bibliographical sense to the article someone wrote about the place.

**Comment by sydb** [comment]
Check, thanks @martindholmes

**Comment by sydb** [comment]
Fixed, or at least changed to what _I_ think it oughta be, at 2af0e9e. Feel free to let me know if I’ve missed the spirit of it, Martin.

**Comment by martindholmes** [comment]
Looks good to me!
