### ISSUE TITLE
<code> vs <att> (or <gi>, <tag>, <val>, <name>, or <ident>) 

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1623]
I noticed that in the tagdoc for att.global.linking ([3.1.0](http://www.tei-c.org/Vault/P5/3.1.0/doc/tei-p5-doc/en/html/ref-att.global.linking.html), [current](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.linking.html)), in the paragraph between the two examples of `@corresp` (which is the first `<tei:p>` in that file) the string “xml:lang” is encoded as `<code>` where I would have thought `<att>` was more appropriate.

There are _lots_ of cases where the content of `<code>` is the same as the value of an `@ident`; e.g. `<code>fileDesc</code>`. I only spot-checked, but it seems most of these are quite reasonable: they are in places where `<gi>` or `<att>` do not make sense, and `<code>` does. But a few, like this one, and all of the occurrences of “incl” and “excl” inside `<code>` in the tagdoc for `<alt>` (which should all be `<val>`) look wrong to me.

**Comment by peterstadler** [comment]
we've come across that sort of inconsistencies when translating the Guidelines, as well. So, yes, there's probably a lot more that could be normalized and streamlined …

**Comment by lb42** [comment]
There are 679 uses of `<code>` in the Guidelines, the overwhelming majority of which seem to be correct on a quick glance. But there are certainly are a few that might be better tagged `<ident>` or `<code>`. Looks like a good job for a new Council member wishing to get familiar with the  code!
