### ISSUE TITLE
some XS datatypes cause errors when tested for, in `make validate`

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1627]
I have a piece of Schematron, with the following fragment:
```xml
<sch:rule context="*[@referringMode = ('character','icp','byte')]">
   <sch:assert test="@from castable as xsd:nonNegativeInteger">When @referringMode is
	'<sch:value-of select="@referringMode"/>', @from must be a non-negative integer</sch:assert>
   <sch:assert test="@to castable as xsd:nonNegativeInteger">When @referringMode is
	'<sch:value-of select="@referringMode"/>', @to must be a non-negative integer</sch:assert>
</sch:rule>
```

The offending bit turns out to be `castable as xsd:nonNegativeInteger`. If I test for `xsd:anyURI`, `xsd:integer`, `xsd:gYearMonth`, it's all good. When I test for, e.g. `xsd:unsignedLong`, `xsd:normalizedString`, or `xsd:int` (as well as `xsd:nonNegativeInteger` and probably many other derived types), it fails, but only if you do `make validate`. The following is a fragment of the error message, followed by a long trace that I skipped:

```
BUILD: Check validity with special-purpose XSL code, looking for bad links etc
ANT_OPTS="-Xss2m -Xmx752m -Djava.awt.headless=true" ant -q -lib Utilities/lib/saxon9he.jar -f antbuilder.xml -DXSL=/usr/share/xml/tei/stylesheet validators
     [echo] Run Schematron script (normal part of Guidelines)
     [echo] Run Schematron script (Examples in Guidelines marked as valid)

BUILD FAILED
/home/piotr/projects/LingSIG/TEI/P5/antbuilder.xml:190: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
```
Let me stress that you won't see any problems if you just `make schemas`, and the resulting schemas are good: instances get flagged as errors if I do `from="-5"` or `from="#bing"`, with an appropriate error message. 

So it kind of works, but it also kind of fails... could something be wrong with that particular `ant` invocation, or the Saxon version?

**Comment by hcayless** [comment]
@bansp, can you post the files that cause this error? Thanks!

**Comment by bansp** [comment]
Ah, now I realised that the report was not fully clear, gosh, sorry. I may be able to restore the files, not sure at this moment. 

Let me expand on the context, first: the Schematron fragment was a part of a constraint inside a classSpec that defined `@from` and `@to`, which could contain several datatypes, and `@referringMode` controlled that, together with the Schematron check.

So, potentially, it should produce the message above if you modify any classSpec to
1. assign the datatype xsd:nonNegativeInteger to some attribute, and
2. put the modified Schematron fragment into a constraintSpec (inside the classSpec that defines the test attribute); essentially you need the `castable as xsd:nonNegativeInteger` fragment there, because this is where problems occurred.

**Comment by hcayless** [comment]
Can't really do anything with this one without an example of breakage, so I'm closing it. Feel free to reopen it if this recurs in future.
