### ISSUE TITLE
request: allow <hi> in <locus>

### ISSUE THREAD

**Issue by holfordm** [TEIC/TEI#1628]
Manuscript catalogues often put the "r(ecto)" or "v(erso)" parts of locations in superscript. This is particularly helpful when the location is a roman numeral, e.g. `fol. i<hi rend="superscript">v</hi>`rather than "fol. iv" which is easily misread as "fol. iv". `<hi>` is not allowed in `<locus>`, although it is the easiest way to encode superscript characters.

**Comment by lb42** [comment]
Wouldn't `<g>` be both more appropriate (it's not really highlighting) and shorter? Alternatively, dare I suggest `<abbr>`?

**Comment by holfordm** [comment]
I think it is difficult to define highlighting, especially perhaps in the case of superscript where there may be acceptable variants with/without superscript. It is a "typographical feature" which "distinguishes some passage of a text from its surroundings" often perhaps to be "set apart from the text in some other way" (Guidelines 3.3.1). It seems more natural to me to label characters as superscript using @rend, than to label them as nonstandard characters using <g>. 

<abbr> does make sense -- at least for v(erso) and r(ecto). Would it also make sense for references like fol. 2<su>ra</su> where a, b, (etc.) denote the column?

**Comment by scstanley7** [comment]
I think it would be more appropriate to use `<abbr>` for the original example than the one with the column indicators. One problem with the `<abbr>` solution is that it does not appear that it is allowed within `<locus>` either at the moment. Additionally, we do have [instances in our examples](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-hi.html#index-egXML-d39e37316) where superscripted characters are encoded with `<hi rend="sup">`, and I know that this is an established practice for certain projects. If our definition of `<hi>` is that constrained, we should probably revisit that example.

**Comment by martindholmes** [comment]
Aren't there two distinct things here? There's the issue that r and v have a semantic significance (in other words that the contents of the `<locus>` consist of two components, a folio number and a recto/verso signifier), and secondarily that this distinction is signalled in the original by textual formatting (superscript). I'd be more inclined to find a way to encode the semantics with appropriate tags, and then add the style information with `@style` or `@rendition`.

**Comment by holfordm** [comment]
Would it be excessively ugly / confusing to have something like `<locus>fol. 24<locus rend="sup">va</locus></locus>`?

**Comment by jamescummings** [comment]
It might be a bit ugly but wouldn't that make more sense semantically? (and even moreso if you wrapped a locus around the v and the a separately?

Another option, of course, is that new elements could be created here to denote the thing that means side-of-surface and the thing that means column.

**Comment by martindholmes** [comment]
I like the idea of nesting locus. The outer locus is the place in the sequence of folios, and the inner one is the place within the identified folio.

**Comment by lb42** [comment]
Seems to me that most people (i.e. not computer scientists) would think that the locus is a single concept com[prising two parts, a page number, and a qualifier. So I'd go for the slightly simpler tagging:
`<locus><num>iv</num><abbr>v</abbr></locus>`

**Comment by martindholmes** [comment]
There are I guess three levels of tagging that are plausible here:

Bibliographic (it's a superscript)
Semantic (it's an abbreviation)
Functional (it's a sub-pointer to a part of the folio identified in the preceding bit)

Assuming it can be tagged at all, the first requirement can be handled with attributes (`@style='superscript'`). Which of the other two domains are most relevant depends on the objectives of the encoder, surely.

**Comment by holfordm** [comment]
@lb42, what would you suggest for column locations like the "a" in fol. 2ra?

Mailing list question of 2 Feb 17:   "[what is the best way to define the location of a text which starts at a certain line of a folio and ends at a certain line of another like from line 10 of folio 1r to line 5 of folio 3v](http://tei-l.970651.n3.nabble.com/locus-from-line-10-of-folio-1r-to-line-5-of-folio-3v-td4029314.html)". As the replies noted it's not really possible to do this in an unambiguous / machine readable way at the moment. 
It is not directly relevant to this discussion, but this user need might also be borne in mind.

**Comment by holfordm** [comment]
I'll try to summarize discussion so far. We agree that some kind of semantic markup would be preferable, but there is no agreement what form that should take. If that is so, then perhaps general text highlighting markup (i.e. `<hi>`) should be permitted. There is an analogy with collation formulae where markup like `1-8<hi rend="super">8</hi>` is common - in that case too it would be better to mark up the number of leaves in a quire semantically, but there is as yet no agreed way of doing this, so non-specific highlighting is used.

**Comment by lb42** [comment]
well, nutty or not, I suppose the "fol 2 r a" case is a good argument for hierarchically organized locus elements.  so 
~~~~
<locus type="fol">2<locus type="side">r<locus type="col">v</locus></locus></locus>
~~~~
Sheesh.

To which you can attach your rendition attributes ad lib.

**Comment by martindholmes** [comment]
I like Lou's approach too. It keeps the semantic stuff distinct from the rendering stuff, while allowing both, and it requires only that locus be nestable.

**Comment by holfordm** [comment]
This makes sense to me. 
To anticipate some potential objections to Lou's example:
-fiddly to encode and/or convert (in a source document the text would probably just be marked as superscript)
-unnecessary from a semantic point of view since the `@from` and `@to` of the main `<locus>` can already capture the location of a `<msItem>` information in a semi-standardized form (albeit that I don't think there is a canonical way of doing this at the moment.
So a half-way approach such as `<locus from"1ra1" to "2vb30">fol. 1<locus type="sub" rend="super">ra</locus> line 1 - fol. 2<locus type="sub" rend="super">vb</locus> line 30</locus>` ought to be permissible.
We are all assuming, I think, that `<locus>` would become part of `att.typed`.

**Comment by martindholmes** [comment]
I don't know whether `<locus>` should be part of att.typed, but I don't see that the need arises out of this particular case; if a `<locus>` is nested inside another one, can't it simply be assumed to be "sub"?

**Comment by jamescummings** [comment]
My proposal then (since this is assigned to me) is that: 

The content model of `<locus>` be extended so that it may have just macro.xtext, or a nested `<locus>` or `<hi>` (for the simplest method). That is one could have both locus and hi but that either one is marking highlighting (e.g. in an original catalogue) or one is providing a semantic encoding (so use `<locus>`). This allows for the simple 'I just want to put something in superscript' method using `<hi>` and the 'I want to deeply reference sub-loci' method.

**Comment by jamescummings** [comment]
Believe this is fixed with https://github.com/TEIC/TEI/commit/21d124b16d8759ce5720250364122e7f1cf25335 closing issue.
