### ISSUE TITLE
examples and suggested values of unit= don’t match 

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1630]
The “suggested values include” for `@unit` of `att.citing` includes the values `volume` and `page`. But I just found that there are 11 instances of `unit="pp"` and 11 instances of `unit="vol"` on `//egXML//biblScope | //egXML//citedRange`.

My instinct is that the examples are wrong, the “suggested values include” list is correct, and the examples should just be fixed without further ado.

**Comment by lb42** [comment]
*my* instinct otoh is that pp and vol.are pretty widely used and recognised in the world of bibliography and that "suggested" shouldnot ean "compulsory"

**Comment by sydb** [comment]
So your suggestion, then (I hope) is to change the suggested values list to have `"pp"` and `"vol"`. While I mildly prefer `"page"` and `"volume"`, I really don’t care much. But I think it is a very bad idea to suggest A and exemplify B. (While TEI is specifically **not** asserting that use of `"page"` as opposed to `"pp"` is cumpulsory for TEI conformance, we **are** suggesting that “if you want to express that a cited range is measured in pages, you should use `"page"` so that everyone (pardon the pun) is on the same page”.)

**Comment by martindholmes** [comment]
I think that once we have propagated a suggested values list, we should think very carefully before undermining it. We should fix the examples to be consistent with our suggested list, unless we can find in the history that our intention was in fact the reverse. There could be Stylesheet implications for changing a suggested valList too.

**Comment by lb42** [comment]
I stand by the assertion that "vol" and "pp" are widely used and appropriate. Is it not possible that they were mistakenly removed from the valList when it was closed ?

**Comment by hcayless** [comment]
Council subgroup agrees with @sydb. Nothing prevents TEI users from using 'vol' or 'pp', but we should keep the suggested values simple, and make our examples consistent where practical.

**Comment by ebeshero** [comment]
closing with this commit: https://github.com/TEIC/TEI/commit/95811217d19e4dbddb7f17ef556fb7db6ffc0d27
