### ISSUE TITLE
Erroneous claim in 23.3.1.1 (USE.xml#MDMDSU)

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1633]
Second para of section  #MDMDSU says
~~~~
For example, if the <gi>note</gi> element is not to be used in a particular application,
 the schema specification concerned will contain a declaration like the following:
 <egXML
            xml:lang="und" xmlns="http://www.tei-c.org/ns/Examples">
<elementSpec ident="note"   module="core" mode="delete"/>
</egXML> 
The <att>ident</att> attribute here supplies the   canonical name of the element to be deleted, the <att>module</att> attribute identifies   the module in which this element is declared, and the <att>mode</att> attribute specifies what is to be done with it. Note that the module name must be supplied explicitly,  and  that the schema specification in which this declaration appears must also contain a reference to the module itself. 
~~~~
This isn't the case. There is no need to specify a module, provided that a spec for the element being deleted is available in the source being processed.

**Comment by martindholmes** [comment]
It's not necessary to specify the module, but it's a good idea IMHO. More clarity and specificity helps.

**Comment by lb42** [comment]
I fail to see in what respect it add clarity to specify the module name: it's not as if the element might be in some other module. But in any case, the claim in the text that supplying the module name is mandatory is just wrong, and should be changed.

**Comment by raffazizzi** [comment]
I also don't see why it's necessary to specify the module. It's not like a namespace, so there won't be two elements with the same name across modules.

And the rest of the sentence "the schema specification in which this declaration appears must also contain a reference to the module itself" is also not true, right? Because one could write an ODD without modules.

**Comment by lb42** [comment]
My current understanding of how modules work is as follows. An ODD derived from the TEI must reference the tei module, since this defines most of the model classes and macros which other declarations depend on. If you want to *modify* a TEI elementSpec that spec must be dragged into your ODD declaration space first. But you can drag it in by just providing an elementRef. So `<moduleSpec ident="foo" mode="change">` won't work unless one of `<moduleRef include="foo" key="fooModule">`  or `<elementRef key="foo"/>` is present. But `<elementSpec key="foo" mode="delete"/> deletes any spec for `<foo>` which is present, however it got there. Of course, if you never included fooModule nor any element referencing it, then it won't be there in the first place, and an ODD processor won't flag an error if you try to delete something that isn't there.

**Comment by martindholmes** [comment]
But there's some magic in the fact that the processor "knows about" TEI elements whose modules have not even been referenced, no? That happens for TEI-based ODDs because p5subset is always there, but if you were writing a non-TEI ODD, presumably you would have to reference all modules explicitly?

**Comment by laurentromary** [comment]
Indeed. Maybe we should recommend, if not more, to have such references made explicit.

**Comment by lb42** [comment]
Not sure what magic there is here. A processor will try to resolve the content of the odd file with respect to whatever the @source attribute specifies, which might well be a non tei set pf declaratipns.  Or is it the use of a default value which you consider magical?

**Comment by martindholmes** [comment]
No, you're right, it's not magical; it's just that I forget (and many people I would guess never even know) that there's a default assumption that `@source` is p5subset.xml.

**Comment by raffazizzi** [comment]
In the case of MEI, the [ODD source](https://github.com/music-encoding/music-encoding/blob/develop/source/specs/mei-source.xml) is basically the same as p5subset.xml. That is, in order to generate an MEI schema, you will always need two files, a source one and [a customization one](https://github.com/music-encoding/music-encoding/blob/develop/customizations/mei-all.xml#L67). I think this is just how ODD is set up to work, you can't generate a schema without a source (itself specified in ODD). Obviously, non-TEI ODDs need to set `--localsource` when using TEI XSLTs.

**Comment by lb42** [comment]
Much of this discussion is beside the point. The @source attribute only determines which TEi components are *available* for inclusion  in a customization. It's the &lt;moduleRef or &lt;elemenRef which determines whether they are included. The point here is that (assuming an element has been included by whatever means), you don't need to repeat which module it came from when deleting it because TEI element names are global in scope, i.e. you can't have two elements with the same name.

Revised the para as follows:
~~~~
 <p>For example, if the <gi>note</gi> element is not to be used in a particular application,
          but has been included via one of the supplied modules, then the schema specification
          concerned will contain a declaration like the following: <egXML xml:lang="und"
            xmlns="http://www.tei-c.org/ns/Examples"><elementSpec ident="note" mode="delete"
            /></egXML> The <att>ident</att> attribute here supplies the canonical name of the
          element to be deleted and the <att>mode</att> attribute specifies what is to be done with
          it. There is no need to specify the module concerned, since element names are unique
          across all TEI modules. The full specification for a schema in which this modification is
          applied would thus be something like the following: <egXML
            xmlns="http://www.tei-c.org/ns/Examples"><schemaSpec ident="mySchema">
              <moduleRef key="core"/>
              <!-- other modules used by this customization -->
              <elementSpec ident="note" mode="delete"/>
            </schemaSpec></egXML>
        </p>
~~~~
