### ISSUE TITLE
Adding new valid item to semi-closed valList loses old descs

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1635]
Consider the following fragment of ODD source
~~~~
 <elementSpec ident="idno" mode="change">
            <attList>
               <attDef ident="type" mode="change">
                  <valList mode="change">
                     <valItem ident="ARK" mode="add">
                          <desc>identifiant établi par le Bibliothèque Nationale de France</desc>
</valItem>
                  </valList>
               </attDef>               
            </attList>            
            </elementSpec>
~~~~
which is intended to add a new value to the list of suggested values for idno@type. As indeed it does, but with the curious side effect of suppressing the descriptions (but not the values!) for all the other suggested values.

**Comment by hcayless** [comment]
This is probably a Stylesheets bug. I'll look into it.

**Comment by lb42** [comment]
I think it may be the same as/related to https://github.com/TEIC/Stylesheets/issues/254

**Comment by lb42** [comment]
Closing and resubmitting as Stylesheets bug.
