### ISSUE TITLE
description of classDecl needs revision, perhaps examples

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1640]
Per [discussion of 4-5 May 2017 on the TEI listserv](https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;c497bd0.1705), the description of `<classDecl>` at the start of [2.3.7](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/HD.html#HD55) needs a small change to be consistent with its actual usage. 

````
In <div type="div3" xml:id="HD55"><head>The Classification Declaration</head>
<p>The <gi>classDecl</gi> element is used to group
together definitions or sources for any descriptive classification
schemes used by other parts of the header.  Each such scheme is
represented by a <gi>taxonomy</gi> element...
````
We should add "or elsewhere in the document" at the end of the first sentence.

**Comment by ebeshero** [comment]
The same discussion called for perhaps a wider range of examples to indicate common practice with pointing references from within the `<text>` of documents into a `<taxonomy>` in `<classDecl>`.

**Comment by ebeshero** [comment]
Language revised per @lb42 's suggestion with https://github.com/TEIC/TEI/commit/9fc499f1c440fd94fd52b168109792282da91bdd

**Comment by raffazizzi** [comment]
Here's how we use `classDecl` in S-GA: 
`classDecl`: https://github.com/umd-mith/sga/blob/master/data/tei/shared/classDecl.xml
gets used within `msDesc`: https://github.com/umd-mith/sga/blob/master/data/tei/ox/ox-ms_abinger_c56.xml#L44

I can produce a simplified example; would that be enough to close the ticket?

**Comment by raffazizzi** [comment]
@martindholmes could also provide one or more concise examples?

**Comment by ebeshero** [comment]
@raffazizzi I think this looks good! Yes, please simplify.

**Comment by ebeshero** [comment]
@sydb Also mentioned an example from a 5th grade textbook that would be easy to understand. Please share!

**Comment by ebeshero** [comment]
Adding "go" just to speed this along, patching in examples.

**Comment by vjuloux** [comment]
For my doctoral thesis research, I'm using a lot of taxonomies to set up a hermeneutics of action. Afterward, I'm using them for statistics in R.

**Comment by raffazizzi** [comment]
(self assigned just so I remember to provide example soon)

**Comment by jamescummings** [comment]
c.f. the second example on the taxonomy reference page http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-taxonomy.html in case that is helpful.

**Comment by ebeshero** [comment]
I wanted to keep the example fairly simple and straightforward so I "boiled down" the one @jamescummings pointed us to to feature in the classDecl section. I think this (https://github.com/TEIC/TEI/commit/d36eb446ab601962ec5382bd251c5df1d9faab63 ) should be enough to resolve the ticket.
