### ISSUE TITLE
rubric, finalRubric, colophon should have att.msExcerpt

### ISSUE THREAD

**Issue by holfordm** [TEIC/TEI#1642]
These items are part of model.msQuoteLike but unlike `incipit` and `explicit` they cannot have the `@defective` attribute, although obviously they may be defective in practice. 
One of the uses of `@defective` in these contexts is that that text such as '||' or '...' can be generated at processing rather than appearing in the text of the element and interfering with sorting, if an alphabetical index of incipits, etc., is required.  The same considerations apply to rubrics (cf. the index of rubrics on the Parker Library on the Web site) although admittedly less obviously to colophons which are not usually indexing.

**Comment by lb42** [comment]
Adding these elements to att.msExcerpt seems like a good idea to me: probably they were left out by oversight.
