### ISSUE TITLE
Alter Guidelines re “phrase-level”

### ISSUE THREAD

**Issue by mccaskey** [TEIC/TEI#1645]
The Guidelines 3.1 has “We distinguish phrase-level elements, which must be entirely contained within a paragraph and _cannot appear except within one_ . . . .”

The part I have italicized is not correct. Phrase-level elements frequently appear outside `p` elements.

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPA   [Update by JC to add URL]

**Comment by lb42** [comment]
In context it's clear that this passage is not defining "phrase-level elements" but talking about the various types of components which may appear within a paragraph, some of which are "phrase level" and others of which are not. Quoting it out of context gives a misleading impression. I don't think there is anything wrong here.

**Comment by ebeshero** [comment]
@lb42 Granted, 3.1 is a section *about* paragraphs, and Ch. 3 confines itself to discussing elements available in all TEI documents, treating prose text as a fundamental commonality. However, @mccaskey is right, I think, to point out that phrase-level elements can and do appear outside of paragraphs, and when they do, they appear in elements analogous to the paragraph.  I do think there's potential for beginners with TEI to be confused by this, if those beginners are, say, encoding phrase-level elements in lines of poetry, etc., and a pretty simple repair would be just to drop the phrase "cannot appear except within one". The surrounding sentences make the basic idea clear, I think, about the hierarchical position of phrase-level elements, and that phrase seems to be misleading overkill.

**Comment by mccaskey** [comment]
I came across this when I read “phrase-level element” elsewhere in the Guidelines and needed to know exactly what would qualify. But then that phrase “cannot appear except within one” confused me. It was only after reading and thinking about this much more than I wanted that I realized I shouldn’t take “cannot appear except within one” as literally as I was.

With enough background and context, I figured out what was going on. But that phrase needlessly delayed me.

**Comment by ebeshero** [comment]
Can we green-light me to revise the phrasing of the [Guidelines 3.1](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPA) to trim this bulky/slightly misleading phrasing:
 “We distinguish phrase-level elements, which must be entirely contained within a paragraph and cannot appear except within one . . . .”
to simply:
“We distinguish phrase-level elements, which must be entirely contained within a paragraph . . . .” 
?

**Comment by ebeshero** [comment]
Revisiting this ticket, I think there's no reason we shouldn't resolve this and apply it toward the next release--evidently it just hasn't come up for discussion and I'm sorry for not following up sooner. I would like to make sure Council is okay with the simple proposed change first.

**Comment by ebeshero** [comment]
The current phrasing as of the July 2018 release is this, and Council (at Face-to-Face meeting) now thinks this phrasing resolves the issue. Closing. 

````
Paragraphs can contain any of the other elements described within this chapter, as well as some other elements which are specific to individual text types. We distinguish phrase-level elements, which must be entirely contained within a paragraph or similar structure and cannot appear except within one, from chunks, which can appear between, but not within, paragraphs, and from inter-level elements, which can appear either within a single paragraph or between paragraphs.
```
