### ISSUE TITLE
No more production of compiled ODD in Roma?

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1646]
I have discovered with worry that one cannot generate a compiled ODD under Roma. It was under the documentation tab/TEI ODD, which now regenerates the simple version (same as "Save customization", which is a duplicate). Could this be re-installed (by using ODD4ODDS) quickly. This is really essential for those chaining ODDs in particular. 
Note: yes, one can do this on one's own under Oxygen etc., but this is not th topic of the ticket.

**Comment by peterstadler** [comment]
This should actually be posted at https://github.com/TEIC/Roma/issues; and those issues are not going to be resolved quickly, I fear :( 
Good news is, @raffazizzi is working on a replacement for Roma and is making impressive progress, so I hope you can in the meantime resort to oXygen or [OxGarage](http://www.tei-c.org/oxgarage/) for creating a compiled ODD.

**Comment by laurentromary** [comment]
The point is that someone touched this recently, which is really a shame, because it did work. If it is just a matter of reverting to the situation a couple of months ago, that would be great.

**Comment by peterstadler** [comment]
Nothing obvious from the commits at https://github.com/TEIC/Roma/commits/master – maybe @jamescummings knows more?!

**Comment by bansp** [comment]
The answer may be hiding in the Stylesheets, maybe the handling of some parameter has changed.

**Comment by jamescummings** [comment]
I **cannot** duplicate this.

Steps:
1) I go to http://www.tei-c.org/Roma
2) I select 'Build Up' or another template ODD
3) I click on the 'Documentation' tab
4) I select 'TEI ODD' from the dropdown menu
5) I click 'Generate'
6) I open the downloaded file in editor of my choice
7) I notice that it is a full ODD with all the elementSpecs, etc. what @laurentromary is referring to as a Compiled ODD.  It is not the input ODD which doesn't have those elementSpecs and classSpecs

If someone can give me an ODD where this does not work, I'll test that. But at the moment there appears to be no error.

**Comment by lb42** [comment]
I can confirm that this works fine. It's not the most obvious place to look for it, but this is definitely a very effective and useful place to go if you want to make a compiled ODD.

**Comment by laurentromary** [comment]
Look. The is really weird, but maybe it's just me. I have done that a zillion time before and yesterday it just did not work... And yes, it works perfectly for me now.
Sorry for disturbing everyone with this. Sigh.

**Comment by peterstadler** [comment]
Seems like a temporary quirk …  closing the issue.
