### ISSUE TITLE
model.physDescPart is declared in the wrong module

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1650]
The class model.physDescPart is used to define the content model for &lt;physDesc> which is supplied by the msdescription module  but is itself declared in the tei module. This can have unexpected and undesirable consequences in some circumstances (e.g. the chaining scenario described in https://github.com/TEIC/Stylesheets/issues/271) and doesn't make a lot of sense anyway. There may be other similar cases, but this one seems egregious.

**Comment by eduarddrenth** [comment]
When model.physDescPart will be moved to msdescription can this cause problems for existing chaining scenarios? Perhaps in a scenario that does not reference the msdescription model but does use the physDesc element? Though I would not expect such a scenario to work.

**Comment by jamescummings** [comment]
I can't picture a scenario where you would have a **working** ODD with model.physDescPart and not also be including the msdescription module.

I also think the number of people doing ODD chaining is fairly small and fairly technical and we'd be able to do this as a corrigible error rather than go through deprecation processes, etc. I would expect minimal side-effects from a change like this.

**Comment by lb42** [comment]
You could use physDesc in an ODD without also invoking the module it comes from. If you did, you'd hit the same problem Eduard did: your &lt;physDesc> content model would permit only model.pLike elements. It's nothing to do with chaining.

**Comment by jamescummings** [comment]
Sure, I just can't picture _why_ you'd want to do that.  But nevermind.... still seems like a corrigible error to me. Let's just move it to msdescription and be done with it. ;-)

**Comment by ebeshero** [comment]
Let's discuss this at the next Council meeting, shall we? Is this something we can agree to greenlight, or should we talk more, do a standard deprecation period, etc?

**Comment by sydb** [comment]
My instinct is we can just greenlight it and do it, but someone may have an argument that convinces me otherwise.

**Comment by jamescummings** [comment]
Contrary to every thing I've said on this ticket so far, if we are going to be creating an `<object>` element, decoupling model.physDescPart from msDescription seems more reasonable.

**Comment by ebeshero** [comment]
Council agrees to implement the change.

**Comment by ebeshero** [comment]
resolved with https://github.com/TEIC/TEI/commit/6c931789491bf6d3fb09f3ab5247e1f1d0be07be

**Comment by ebeshero** [comment]
Reopening because evidently I did this wrong...

**Comment by ebeshero** [comment]
...and all is well now.
