### ISSUE TITLE
typo in "Getting Started With P5 ODDs" documentation

### ISSUE THREAD

**Issue by paulbroyles** [TEIC/TEI#1652]
I've discovered a typo in "Getting Started With P5 ODDs." It's in the Writing ODD Specifications section, in the Key Concepts subsection. The paragraph giving examples of attribute classes relating to dating attributes includes the following example:

> **att.database.w3c** (providing attributes for dates in W3C format)

This should read "att.datable.w3c."

**Comment by martindholmes** [comment]
Thanks for finding this. It's now fixed.
