### ISSUE TITLE
mis-used attrs in example of <affiliation>?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1653]
The tagdoc for `<affiliatoin>` has the following example:
~~~~~xml
<affiliation notAfter="1960-01-01" notBefore="1957-02-28">
  Paid up member of the <orgName>Australian Journalists Association</orgName>
</affiliation>
~~~~~
I read this as implying this person was a member of the AJA for some period of time, which (because `@dur` is not specified) is not known, but could be anywhere from 1 second to 1,038 days; and further that that duration of time started on or after 28 Feb 1957, and ended on or before 01 Jan 1960.

I suspect the intended semantics are “was a member for the entire period from 28 Feb 1957 (or perhaps 01 Mar 1957) to 01 Jan 1960 (or perhaps 31 Dec 1959)”. In which case the attributes should be `@from` and `@to`.

**Comment by martindholmes** [comment]
Looks like a simple corrigible error, assuming the intent was a duration. The same thing occurs in examples in other languages too.

**Comment by lb42** [comment]
It's only an error if you assume something about the "intended semantics". Its meaning is clear: membership started at some time before the @notBefore date and did not extend beyond the @notAfter date. One might postulate for example the existence of documents attesting membership on the @notBefore date, and demonstrating non membership at the @notAfter date. There's no reasn to assume that a precise span was intended. So perhaps a better solution would be to add a second example using @from and @to and then discuss the difference more explicitly.

**Comment by scstanley7** [comment]
I have definitely used `@notBefore` and `@notAfter` on `<affiliation>` to specify that an affiliation existed *at some point* within a given date range. I like the idea of providing another example and expanding upon the difference, though. Happy to take this one over, if this seems like a reasonable solution!

**Comment by jamescummings** [comment]
Yes, I think that is what the example is trying to convey and it should be `@from` and `@to`.  Why not have two very similar examples to highlight the difference in meaning? One with the `@notBefore/@notAfter` and another with `@from/@to`?

**Comment by martindholmes** [comment]
@jamescummings I don't think you're right. What @scstanley7 describes (an affiliation existed at some point within a given range) is surely `@notBefore/@notAfter`, not `@from/@to`. But I do like the idea of both examples side-by-side as an illustration of the difference.

**Comment by scstanley7** [comment]
I assumed that James was responding to the original post rather than to mine. If that's the case, it seems we do have a consensus. I'm going to assign myself to this one and:

* write a new example using`@from` and `@to`
* write some language describing the difference

If no one expresses any serious qualms between now and Monday, I'll do it then.
