### ISSUE TITLE
some mix-ups expanding upon examples in specs

### ISSUE THREAD

**Issue by scstanley7** [TEIC/TEI#1654]
I was looking through the specs for best practices on annotating and remarking on exempla in the guidelines, and I came across two errors:

* The section on `@given` in the `<certainty>` spec refers to a nonexistent (or at least incomplete) example - the bit about Essex as a person vs. place name is there, but the bit about the scribe "msm" is missing
* `<paramSpec>` refers to "the example above" - the example is rendered below the notes in the web guidelines, although `<exemplum>` appears *above* `<remarks>` in the specs file

These are easy enough to fix, but I was also wondering if there is a specific recommendation for *how* to expand upon examples. I've seen both `<remarks>` and a `<p>` within `<exemplum>` used to do this, although I wasn't sure which one is most correct, or if there was a meaningful distinction. Sorry if this has already been addressed; I couldn't find any references to this in TCW 20 or 24.

**Comment by martindholmes** [comment]
Also the `<desc>` for `@given` is a shambles:

"indicates one or more element(s) characterizing the conditions which are assumed in the assignment of a degree of confidenceconditions assumed in the assignment of a degree of confidence."

**Comment by raffazizzi** [comment]
@scstanley7 my guess is that `<remarks>` is used for a note that applies to attribute / element; it may refer an example, but it doesn't need one. Using references like "the first example" and "above" should probably be avoided because renderings can shift and examples can change order.
I would use a `<p>` within `<exemplum>` only if the note is specific to the example.

**Comment by ebeshero** [comment]
I'm not sure where we are with this ticket, as @raffazizzi just assigned me to it. I *think* this was actually resolved back in 2017, and perhaps I should just close it? @martinascholger and @raffazizzi , can you take a look?

**Comment by ebeshero** [comment]
Also, does it really take this release milestone, or wouldn't the change have been made back in a release of 2017?

**Comment by martinascholger** [comment]
@ebeshero maybe the reason why it is still open is that we wanted to add some documentation to TCW 20 on "where to put a specific note for an example"?

**Comment by ebeshero** [comment]
@martinascholger Thanks for that insight...I'll see if I can patch in something, following the discussion on the ticket later today so it's really wrapped up for this release...

**Comment by ebeshero** [comment]
Added guidance to TCW20 on how to refer to exempla and to avoid positional language in referring to exempla, following advice in this ticket with https://github.com/TEIC/Documentation/commit/88a67088d61b6e475dc7b4f6ccc6d22b925954bd
