### ISSUE TITLE
request: allow `@key` and `@ref` on `msItem`

### ISSUE THREAD

**Issue by holfordm** [TEIC/TEI#1659]
In an example like
```
<msItem>
<author>Virgil</author>
<title>Aeneid</title><textLang>Latin</textLang>
</msItem>
```
or
`<msItem><title>Old Testament</title><textLang>Greek</msItem>`
it should be possible to link the item to an internal or external authority file:
```
<msItem ref="http://data.perseus.org/catalog/urn:cts:latinLit:phi0690.phi003">
<msItem ref="http://data.perseus.org/catalog/urn:cts:greekLit:tlg0527">
```

**Comment by emylonas** [comment]
These attributes can appear on the `<title>` element which is a child of `<msItem>`. They are intended for exactly this purpose.

**Comment by holfordm** [comment]
I am not convinced that `<title>` is equivalant to the FRBR type work or expression which is what is being referenced in the URIs.  Does an example like the following not seem odd?
`<msItem><author>Plato</author><title ref="http://www.mirabileweb.it/title/crito-title/3620">Crito</title><respStmt><resp>translator</resp><persName>Leonardo Bruni</persName><textLang>Latin</textLang></msItem>`

**Comment by holfordm** [comment]
It may also be the case that an `msItem` does not contain a title but some identifier may be desired for it.
e.g. Bodl MS Lyell 37 part F item i `<msItem><rubric>Tabula ad sciendum mensem diem et horam introitus solis in quodlibet signum</rubric></msItem>`
