### ISSUE TITLE
Full name of tag lb should be "line begins"

### ISSUE THREAD

**Issue by MarjorieBurghart** [TEIC/TEI#1660]
Dear all, 

As you certainly know, the practice of putting the `<lb/>` tag at the *beginning* of a line in the source document goes against the age-old practice (of medievalists at least) to put a sign (usually a "/") at the *end* of a line in their transcription. This requires a lot of pedagogy and reminding when teaching a TEI workshop. 
In this respect, the full name of the tag, "line break", does not help much. The fact that there's a line break does not tell the user whether it should be encoded at the beginning or end of a line. 

I would propose to develop the name of `<lb/>` as "line begins" instead. That would help the memory of our users in a much more efficient way. It would, also, follow the model of the `<gb/>` tag, which is developed as "gathering begins" in the Guidelines. 
Of course, it would make sense to rename `<pb/>` and `<cb/>` too, but they are less crucial, because the TEI practice does not go against the practice the users have been trained to apply.

**Comment by jamescummings** [comment]
Already Fixed for https://github.com/TEIC/TEI/issues/1529 at https://github.com/TEIC/TEI/commit/5386faec1ef08f6b7803e9161e9af4a5b12a2ca6

**Comment by MarjorieBurghart** [comment]
Wow, that was quick :)
