### ISSUE TITLE
Need <surplus> in <subst>

### ISSUE THREAD

**Issue by cmm2209** [TEIC/TEI#1661]
I have a manuscript in which the scribe abandons a word partway through (without indicating it should be deleted) when there's an error, and then writes the correct word immediately after.  It would be great to have the surplus element be available within the subst element.

**Comment by lb42** [comment]
I am not sure I understand this. A subst element is defined as combining something signalled as a deletion with something signalled as an addition. What you seem to be describing is something that you think should be deleted but which is not signalled as such -- which is what surplus is for. Why not just use surplus (as in the example in the Glines)?

**Comment by hcayless** [comment]
Because the correction is there. The error has been abandoned, but not erased. The implication is that the two are connected, as a deletion and correction are, but there's no deletion.

**Comment by lb42** [comment]
OK. I suppose I'm reluctant to consider the word that follows the surplus as an addition, rather than just part of the text flow. If I am dealing with text like ths "something wib wibble something" I am quite comfortable marking the "wib" as a  "surplus" because it makes no sense to leave it there unmarked, but I am less comfortable marking the "wibble" as anything special. If I want to show that "wib" has been *corrected* to "wibble" why not use <corr> and <orig> ?

**Comment by ebeshero** [comment]
Council F2F agrees after extensive discussion that we should permit one or more `<surplus>` or `del>` together with `<add>` in `<subst>`.

**Comment by peterstadler** [comment]
@cmm2209 if you could provide an illustration for your example that would make a great addition to the Guidelines.

**Comment by ebeshero** [comment]
I'm just reopening this ticket so it's more visible for developing an example.

**Comment by peterstadler** [comment]
… and I purposely left it closed 😬

**Comment by ebeshero** [comment]
Well, we can reopen if we get an example posted later. I guess we should close it ahead of the Guidelines release right now. Sorry.

**Comment by cmm2209** [comment]
Thanks for working on this tweak, and sorry for the delayed response!  The real-world cases I’m working with are all in medieval Latin, which I presume wouldn’t be so helpful as an English one.  Here’s a possible example that I created:
Madness has in our age 
<subst>
<surplus>beca</surplus> 
<add>become</add>
</subst> 
some sort of lost truth.

**Comment by sydb** [comment]
@cmm2209: Medieval Latin is fine, but this is even better. Do you have a source citation for it, or is it made up?

**Comment by sydb** [comment]
(Because if it is just made up, shouldn’t it be
~~~xml
Truth has, in our age, 
<subst>
<surplus>beca</surplus> 
<add>become</add>
</subst> 
some sort of <soCalled>fake news</soCalled>.
~~~
instead?)

**Comment by lb42** [comment]
A Real example, even in medieval Latin, would be better though. It could be glossed in the surrounding text.

Reluctantly using Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by cmm2209** [comment]
Real example it is!  The author I'm working with favors long sentences, so this is one of the more manageable cases:
Enim armonicum causant, sed eum non percipimus. dicunt propter quod in auribus nostris a principio natiuitatis est complantatus, ut in eris apparet malleatoribus strepitum suum uix percipientibus 
<subst>
<surplus>consuebus</surplus>
<add>consuetudine</add>
</subst>.
A rough translation, with approximation of the error: The celestial orbs cause a harmonic sound, but we do not perceive it. They say this is because it has been in our ears from our birth, just as the sound of coppersmiths' hammers scarcely appears to those who <subst>
<surplus>custama</surplus>
<add>customarily</add>
</subst>
perceive it.

Source: Pietro d'Abano, Commentary on the Pseudo-Aristotelian Problems.
Paris, Bibliotheque Nationale man. lat. 6540, f. 154v.
