### ISSUE TITLE
Things we'd like to do in ODD which haven't been implemented yet

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1663]
@lb42 commented in #1608 that we should have a place to discuss desired functionality for ODD. This is that ticket. Quoth Lou:

> I think it would be a shame if ODD did not provide a way of doing what we used to do in DTDland with the ampersand connector.Maybe we need to raise a separate ticket for "things we'd like to do in ODD which haven't been implemented yet" (which could include <interleave> for example)

Presumably this will end up being multiple tickets.

**Comment by ebeshero** [comment]
We need to extend the range of Schematron in ODD. For example, in Schematron files we can apply XSLT instructions (e.g. xsl:number) to assist in constructing tests (e.g. on reading and comparing values of Roman numerals). Embedded Schematron rules in ODD constraints don't respond to XSLT (even if the XSLT namespace is invoked in the ODD).  (See extended discussion in this related ticket: https://github.com/TEIC/TEI/issues/1607 )

**Comment by bansp** [comment]
It would be great if attribute classes had a way of knowing which elements belong to them (and expose them via a constant or function, see #1417).

And even more on Schematron: #1625 (more structure to constraints). This may be a simple mapping issue between Schematron and ODD (which flattens the Schematron constraint structure).

**Comment by hcayless** [comment]
See also #1536, which we killed off.

**Comment by sydb** [comment]
Since this is an über-ticket, for recording desires rather than actually acting on them, I am deliberately leaving it unassigned.

**Comment by sydb** [comment]
> it would be a shame if ODD did not provide a way of doing what we used to do in DTDland with the ampersand connector.

Remember that that was in SGML DTD-land. You can do no such thing in XML DTD-land, nor with RELAX NG. While it is a loss, seems to me it is a minor loss that most of the document-centered XML community has already learned to deal with.

**Comment by sydb** [comment]
Per Council F2F, closing as no one has taken advantage of this place to discuss ODD aspirations for a year.
