### ISSUE TITLE
Bug report: @source not allowed in <personGrp>?

### ISSUE THREAD

**Issue by ChristianGriesinger** [TEIC/TEI#1668]
For me the following minimal example won't validate with Oxygen.
Is it a bug or am I doing something wrong?

Error message:
 attribute "source" not allowed here; expected attribute "age", 
          "ana", "cert", "change", "copyOf", "corresp", "exclude", "facs", 
          "n", "next", "prev", "rend", "rendition", "resp", "role", "sameAs", 
          "select", "sex", "size", "sortKey", "style", "synch", "xml:base", 
          "xml:id", "xml:lang" or "xml:space"

Text example:
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Title</title>
         </titleStmt>
         <publicationStmt>
            <p>Publication Information</p>
         </publicationStmt>
         <sourceDesc>
            <p>Information about the source</p>
         </sourceDesc>
      </fileDesc>
  </teiHeader>
  <text>
      <body>
         <listPerson>
            <personGrp source="#test">
               <persName>Test</persName>
            </personGrp>
         </listPerson>
      </body>
  </text>
</TEI>

**Comment by laurentromary** [comment]
On Oxygen, with a TEI ALL basis, it does work for me. Have you updated your environment with the latest release?

**Comment by ChristianGriesinger** [comment]
After Updating the TEI framework in my Oxygen it validated. Thanks for the advice!
