### ISSUE TITLE
Hapsburg

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/TEI#1672]
as an example in ND.html#NDPER
This is a real world problem and TEI does not exclude fiction works, but no one seems to ever have had Hapsburg as a surname (maybe even in fiction). On the contrary a Rudolf II von Habsburg is well known.
(One could add the von, but nameLink is introduced only later.)

**Comment by sydb** [comment]
Sorry, @Dominique-M, I just want to check that I understand the issue you are raising here correctly — this is an objection to the example of `<genName>` that includes `<surname type="dynasty">Hapsburg</surname>`, as “Hapsburg” does not occur in the real world as a surname on its own, only as “von Hapsburg”?

If I have that correct, my instinct would be to just nuke the example, after all, there are 3 others right there. **However**, this is the only example of `type="dynasty"` in the _Guidelines_, so the solution is not as simple as it seems. However, it is considered perfectly valid TEI to encode “von” as part of the `<surname>` as opposed to in a separate `<nameLink>`. So perhaps just inserting “von” is the way to go.

(But I still think one of the examples should be “Major Charles Emerson Winchester III”. :-)

**Comment by martinascholger** [comment]
I think this is acutally about the spelling. The correct way is "Habsburg", but "Hapsburg" is a fairly commonly used spelling in English sources (i think). How about this:
```
<persName>
 <forename>Rudolf</forename>
 <genName>II</genName>
 <nameLink>von</nameLink>
 <surname type="dynasty">Habsburg</surname>
</persName>
```

**Comment by Dominique-M** [comment]
My fault: I only wanted to raise a problem of spelling (to me Hapsburg 
obviously looks like a typo for the well known Habsburg family), but I 
made my story too complicated by my scruple over the fact that the 
Guidelines are about TEI, not about History. A misspelled name or a 
fictional name make just as good TEI as a real name. Furthermore, I 
discover at this very moment that Habsburg was sometimes also spelled 
Hapsburg in texts in English. So there was ultimately no problem after 
all. Really sorry for this.


Syd Bauman a écrit le 27/07/17 à 15:10 :

**Comment by sydb** [comment]
OK. So not a big problem, but no reason not to update & improve example, either, eh?

The only problem with @martinascholger’s example above seems to be `<nameLink>` would be exemplified before being introduced. How about

~~~~~xml
<persName>
 <forename>Rudolf</forename>
 <genName>II</genName>
 <surname type="dynasty">von Habsburg</surname>
</persName>
~~~~~

I.e., does it still make sense to consider “von Habsburg” a dynastic surname?

**Comment by Dominique-M** [comment]
OK to me, but my advice is unimportant. I am no digital humanist, only 
an amateur heavy user of TEI.

Syd Bauman a écrit le 27/07/17 à 15:36 :

**Comment by martinascholger** [comment]
Or, we can move the example to right after the next prose paragraph (which introduces nameLink)?

**Comment by PFSchaffner** [comment]
For the curious, google shows 6.9 million hits with spelling 'habsburg' and 1.5 million with 'hapsburg.' The GoogleBooks ngram viewer, if restricted to 'English' sources shows the two spellings competing on more or less equal footing till the 1940s, when 'habsburg' took over but faded over time, with the two currently running neck and neck. If confined to 'American English,' the same search gives the overall predominance to 'hapsburg' and the two currently exactly tied.  So it would *appear* that the -p- spelling is a chiefly American phenomenon, but whether it arose from the voiceless sound of the consonant, from a sheer accident, or from an older orthography preserved in the German of North America I have no idea. Curious minds want to know.

**Comment by Dominique-M** [comment]
Looking for "Hapsburg site:de" gives poor results (mostly in English). 
It may be North American, but I do not see an older German spelling with 
p. The page https://en.wikipedia.org/wiki/House_of_Habsburg cites the NY 
Times manual of style for the p variant. Still it may be that the 
spelling was less strict in the past and that the Habsburg themselves 
would happily write Hasburg, Hapsburg, Habsburg…

Paul Schaffner a écrit le 27/07/17 à 16:25 :

**Comment by pfeiffeltower** [comment]
Perhaps this may clarify your questions regarding the spelling of the name "Habsburg": Hapsburg with a "p" is the historical spelling in English for that dynasty.  To this day, British newspapers generally bide by the spelling as do major North American newspapers, foremost among them the New York Times.  For all intents and purposes, "Hapsburg" is the official English spelling, though a member of that family would not spell his name that way, if even referred to in the English press with the "p" spelling.  In French, the name is spelled "Habsbourg"; in Italian "Asburgo"; in Spanish "Habsburgo".  The name has been referred to in history books since the 13th century, so nearly every European language has its own spelling for it.  It just so happens that the English spelling with a "p" is so close to the original name in German that it appears to be a misspelling; it is not--it is merely the historical English variant.

**Comment by lb42** [comment]
So; just to continue guilding this particular lily, maybe we want
~~~~
<surname xml:lang="de">Habsburg</surname>
<surname xml:lang="en">Hapsburg</surname>
<surname xml:lang="fr">Habsbourg</surname>
<surname xml:lang="it">Asburgo</surname>
~~~~
und so weiter...

**Comment by martinascholger** [comment]
Good point, but since the forenames in French and Italian also differ from the German and English ones, we ought to consider them (and the namelinks) as well. What about adding `@xml:lang` to `<persName>`? 
```
<persName xml:lang="de">
  <forename>Rudolf</forename>
  <genName>II</genName>
  <surname>von Habsburg</surname>
</persName>
```

**Comment by emylonas** [comment]
I think xml:lang is on everything by default, isn't it? but it's more of
what we should recommend

[Elli Mylonas
 Senior Digital Humanities Librarian
 and
 Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

On Wed, Oct 25, 2017 at 10:09 AM, Martina Scholger <notifications@github.com

**Comment by ebeshero** [comment]
F2F thinks Martina has a good solution for what should be in the Guidelines.
