### ISSUE TITLE
improve documentation re oXygen updates of TEI

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1673]
Currently we think only @jamescummings [blog site](http://blogs.it.ox.ac.uk/jamesc/2014/04/02/auto-update-your-tei-framework-in-oxygen/) is telling people how to update oXygen with the latest TEI implementation. We should improve that documentation.

**Comment by jamescummings** [comment]
Any where that URL to my IT Services blog exists should be changed to https://faqingperplxd.wordpress.com/2014/04/02/auto-update-your-tei-framework-in-oxygen/ in any case. (Where I moved my posts to owing to  my departure.)

**Comment by ebeshero** [comment]
I think @raffazizzi and I made  slide on this when we gave that presentation introducing What the Technical Council does in Vienna: http://bit.ly/TEICouncil

Maybe we can put this stuff somewhere useful on the TEI website.

**Comment by lb42** [comment]
I made some corrections to James' article on this topic for my French version a while back. See http://lb42.github.io/oxyMaj.html
Happy to translate it back into English if necessary!

**Comment by martinascholger** [comment]
As discussed in Council call on 2019-06-17 we need to document updating the TEI framework in oXygen and link it from the TEI website and I saw that we already have a ticket for this. 
Add new item at the top of this page (https://tei-c.org/guidelines/p5/#section-3) “oXygen Plugin” and fill in documentation for how to get the plugin, what versions of oXygen it works with and how to update. The documentation should be based on @jamescummings [blog site](http://blogs.it.ox.ac.uk/jamesc/2014/04/02/auto-update-your-tei-framework-in-oxygen/)). Write this in the TEIC/Documentation repo. Make a new folder rather than use the TCW/ folder: exDoc/ (for “external documentation”) or end_user_doc/ or some such; or put it in a TEI wiki which is backed up in GitHub.

**Comment by ebeshero** [comment]
Having walked @lujessica through installing the plugin we note that we really need to write new documentation (w/ new screen captures) b/c the method for adding and installing plugins has changed since @jamescummings 's blog post. Here's a new ticket on the Documentation repo for us to work on this: https://github.com/TEIC/Documentation/issues/5

**Comment by ebeshero** [comment]
@hcayless @martinascholger With this commit to the Documentation repo, https://github.com/TEIC/Documentation/commit/26ec92ded0b8f83aca38df2cb8019f7cdd58efd0  I have pushed a new oxygen-tei-plugin tutorial with new screen captures tooled to oXygen 21.1. I didn't create this in TCW, but in a new directory that I called `exDoc/` (which is one of the options we discussed on this ticket that made sense to me). The file is oxygen-tei-plugin.xml. What would we need to do to see it rendered?

**Comment by martinascholger** [comment]
@ebeshero I read through the documentation and think this is very clear - thanks for that! Last year I tested different oxygen versions. In 19.1. and 21.1. (I think I also tested it in 20.1) the first step (options > preferences) is not necessary; It also works when I install it from the help menu. Do you want to mention this in the documentation?

**Comment by ebeshero** [comment]
@martinascholger I was meaning to do that. I'm more immediately concerned though about where to put it so that we're sharing it. We might have talked about this at the last meeting (and I need to look it up), but I think we decided I should move it to the oXygen-TEI repo? And make this part of the ReadME there? I'd salso hope that we can send visitors to that with some announcements over the list, and a prominent  ink from the TEI website, as I think a lot of us (me included) are used to looking for this information on @jamescummings 's old blog site! Speaking of which, perhaps we can ask @jamescummings to just post a link from there to the new documentation on our site?

**Comment by ebeshero** [comment]
I have added the comment as @martinascholger advised with this commit: https://github.com/TEIC/Documentation/commit/71a49d2c7e6b1efd1ea579d276e1db9fdc0fc323, but I will also redo the document as a markdown Readme on the oXygen-TEI repo.

**Comment by ebeshero** [comment]
WIth [this commit to the oXygen-tei repo](https://github.com/TEIC/oxygen-tei/commit/be79a682c16146bb29ec89623dc6fc546c05af73), I've prepared [a markdown file with up-to-date steps on how to add the oXygen TEI plugin](https://github.com/TEIC/oxygen-tei/blob/master/oxygen-tei-plugin.md), and I've updated [the main README file](https://github.com/TEIC/oxygen-tei/blob/master/README.md) to point to it.

**Comment by lb42** [comment]
Good stuff, tho the last para is not up to your normally pellucid standard : I had to read "you could point to the plugin to oxygen-tei-stable or oxygen-tei-bleeding jobs" several times. And there will be readers for whom the threatened presence of dragons is merely bewildering.  Just saying!

**Comment by ebeshero** [comment]
Thanks @lb42 ! That last bit was copied over from the README pointing to the old tutorial. I shall send the dragons flying... :-)

**Comment by ebeshero** [comment]
I hope this is an improvement on that last paragraph: https://github.com/TEIC/oxygen-tei/commit/07e09d5616b4adf68b8d593a975d527943f3e156
