### ISSUE TITLE
Loosen content model of listRef

### ISSUE THREAD

**Issue by cmsmcq** [TEIC/TEI#1674]
The listRef element is currently declared (ptr+ | ref+).  Why?  

Is there any reason to suppose that because one wants some of one's pointers to be ptr elements, one will never want ref elements?  Perhaps.  It is imaginable that a given project might determine that it will always use ptr elements (or, less likely perhaps, always ref elements), but such a project is not well served by a content model which offers it the opportunity to get things wrong with every new elementSpec.

I think the element would be more usable with a content model of (model.ptrLike+).

**Comment by laurentromary** [comment]
I would concur with this. This could be implemented together with the other ticket about listRef: https://github.com/TEIC/TEI/issues/1667

**Comment by sydb** [comment]
I agree. Although to be fair, it has been this way for a **long** time, and now one has complained until now. (And even now, it sounds like it is a theoretical complaint, rather than actual work @cmsmcq is not able to do with the current content model.)

So I agree it should be changed, but would say it is a low priority.

**Comment by hcayless** [comment]
The content model hasn't been around long at all. I believe ref was first permitted as a child of listRef in 3.1.0 in response to my whining about it in #1449. I don't in principle see any reason why both should not be allowed as children.

**Comment by cmsmcq** [comment]
> On Jul 26, 2017, at 5:40 PM, Syd Bauman <notifications@github.com> wrote:
> 
> I agree. Although to be fair, it has been this way for a long time, and now one has complained until now.

Well, for some sense of ‘this way’, it has.  

I see that in P3, the tagDoc element (ancestor of the current
elementSpec) allows a sequence of ptr elements, but no ref elements.
I don’t know when ref elements were added, but it can’t have been all
that long ago:  the TEI framework that shipped with Oxygen 17.1 only
accepts ptr, not ref, in listRef.

> (And even now, it sounds like it is a theoretical complaint, rather than actual work @cmsmcq is not able to do with the current content model.)

Not quite true.

When I use tei:elementSpec etc. to define a customization of TEI, 
the locations to which I wish to refer in the listRef are typically within
the same document, and there is no particular difficulty retrieving
the title of the relevant section from the source, so I am as happy
as the next ODD user with ‘ptr’ in that context.

I noticed the restriction because I have been developing a customization
of TEI for the specialized purpose of documenting part-of-speech tag
sets used in corpus linguistics; the ‘posTag’ element added by this 
customization shares a number of children with tei:elementSpec, including
tei:listRef.

Unlike a TEI ODD file, however, the POS tag set documentation file
will not necessarily be the authoritative defining document for the
tag set it documents.  My XML documents listing the POS tags for
the Brown Corpus or documenting other POS tag sets are not 
authoritative, and any document-internal references will need to be
supplemented by references to external documents, which
are not guaranteed suitable for processing by an XSLT stylesheet
in order to extract suitable link text (a distressing number of them
are available on the Web only in PDF, Postscript, DVI, word-processor,
or spreadsheet formats).  So I want to use ‘ref’ for them, not ‘ptr’.  
But for internal links I want ‘ptr’.

Syd is right, I suppose, that none of this is “work [I am] not able to
do with the current content model” — I could certainly create a
dummy section in my POS tag set document which contains ‘ref’
elements pointing to external documents and providing appropriate
link text, and make the ptr elements in linkRef point to those pointers.
Chained pointers have been part of the conceptual apparatus of
hyperlinking for a long time.  (In fact, now that I describe this solution,
I am tempted to implement it just to show that it can be done, and so
that the world will have at least one document in which there are
tei:ptr elements with evaluate=“all” and an XSLT stylesheet that
does the right thing with them.)  And yet, when I faced this problem,
I preferred just to modify the content model of listRef to allow
(model.ptrLike+), rather than to implement evaluate=“all” or
evaluate=“one”.  So while I agree that what I want to do is not 
made impossible by the current content model of listRef, it seems
to me that it is made unnecessarily cumbersome.

**Comment by sydb** [comment]
I stand corrected: content of `<listRef>` has **not** been `( ptr+ | ref+ )` for a long time. (I still think making it `model.ptrLike+` is a good idea; and I appreciate @cmsmcq’s use case mostly because it convinces me #1449 wasn’t such a bad idea after all.)

**Comment by scstanley7** [comment]
Hi all, sorry for the delay in addressing this ticket! I'm still trying to parse the related issues in #1667 to a) address the original issue and b) create a proposed action plan for separating out the subsequent issues raised in the discussion, but that shouldn't keep me from just making this quick fix. 

Are we all still in agreement that the content should be changed to `model.ptrLike+`? Thanks for your patience!

**Comment by laurentromary** [comment]
Well if we have a consensus on the conclusions of #1667 , we may deprecate listRef, which would make the change useless.

**Comment by scstanley7** [comment]
That's true, but I'm assuming that it will require more discussion before we have an adequate consensus (I'm going to make sure this gets on a council agenda). I'm happy to make the change in the interim, in the event that people don't like the idea of deprecating `<listRef>`

**Comment by laurentromary** [comment]
That's reasonable in any case.
