### ISSUE TITLE
Check teidata.pointer attribute values starting with # to ensure they are proper xml:id's

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1675]
Currently teidata.pointer attributes (often a whitespace-separated list of them) are used for many attributes however we never check that these: 
a) point to something
b) are well-formed xml:id NCNames

For example this is completely valid:
````
<sp who="#123">
  <l>
    <app>
      <lem wit="#345 foo.xml#345 foo2.xml http://www.example.com/foo.xml#abc123">Test</lem>
      <rdg wit="#12345">test</rdg>
    </app>
  </l>
</sp>
````
However, the sp's who attribute can't point to an xml:id called 123 because that is illegal, similar with '345' in the document and in a foo.xml file, or with the rdg's wit attribute.

Proposal:
a) Have a general schematron rule which checks tokens inside all teidata.pointer datatype attributes to check that if they start with '#' (and are not an Xpointer or similar) that there are an NCName and have it raise a _warning_ if it is not.

b) Produce a _warning_ if any token points to something that does not exist e.g. an in-document reference if there is nothing with an xml:id that matches that (possibly if easy, an external file if that file doesn't at least exist (using doc-available() in schematron to test I'd assume), a private URI syntax if there is no prefixDef describing it, etc.  I wouldn't recommend testing URLs or other forms of URI to see if they exist, since we might be offline, but just the low-hanging fruit.

**Comment by martindholmes** [comment]
We've been writing code like this here:

https://github.com/projectEndings/diagnostics

and we'll be presenting it at DH. There is an issue with doc-available(): it only works for XML resources, so any pointer that targets an image, or another type of binary, or non-X-HTML can't be checked. Text files can be checked with unparsed-text().

**Comment by sydb** [comment]
I think I am in general in favor. (a), of course, is a lot easier to do than (b), but even there it is a bit of a pain as you have to deal with sequences. And writing 1 chunk of code that does this for all the pointing attrs either
1) results in undesirably vague msgs
2) requires features of Schematron I don’t yet understand
3) requires jumping through hoops

E.g., see “persName-refers-to-person” in [the WWP ODD](http://www.wwp.neu.edu/wwo/source/schema/wwp-store.odd)

**Comment by hcayless** [comment]
...URLs beginning with '#' might also be XPointers, so restricting them to NCNames is problematic. See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSin

**Comment by sydb** [comment]
Right, @hcayless. The question is whether it is sufficient to check for “NCName or NCName followed by open paren followed by stuff that is not checked followed by a final close paren”? Because if we have to actually parse XPointers …

And (as @martindholmes points out) it is awesomely difficult to find out if a pointer to a generic external document is resolvable or not.

This is beginning to strike me as something that the TEI should exemplify how a project might run such checks, but not actually try to include them in the _Guidelines_.

**Comment by jamescummings** [comment]
We should be able to tell the difference between an xpointer and an idref ... so check that first?

**Comment by ebeshero** [comment]
Council thinks @sydb should make an exemplar ODD that shows how to include pointer checking--to check various features of pointers and discusses them instead of trying to be a complete pointer-checking system.

**Comment by hcayless** [comment]
One note: checking for pointer resolvability might mean you don't need to check for lexical validity. If a pointer correctly indicates an element with an xml:id, then it must be a hash + an NCName.

**Comment by sydb** [comment]
I am perhaps 80% done with a first crack at a _Checking Pointers using your TEI ODD Customization_ document. Questions:

1. Are we going to assign it an official document number? (It would probably get TCWxx for now, then become TCUzz as a published document. W is for a working draft, U is for user documentation.)
2. Where do we want to store it while we work on it? My instinct is to put it into the **TEIC/Documentation** GitHub repo in the TCW/ directory (as tcw31.xml or whatever), at least for now. 
3. If it goes in that repo, does it automatically get reflected in TEIC/teic.github.io, and if so, what process is used to generate the HTML? (I have been using Stylesheets/bin/teitohtml5, and it needs the $numberBackFigures parameter be set to "true".) 
3. Do we want to try to have it published along with the release later this month? My instinct is “yes” if we are willing to work on it during the refridge & freeze periods, “no” if we are not.

**Comment by HelenaSabel** [comment]
I think it should get a number, and the GitHub repo seems a convenient place to work on it.
I am available to read draft versions of the document before the release.

**Comment by sydb** [comment]
It is checked in as [TCW32](https://github.com/TEIC/Documentation/blob/master/TCW/tcw32.xml).
(As I am not entirely sure where the other sources for TCWs are, I am not 100% sure there is not already a TCW31. :-)

**Comment by sydb** [comment]
Published as [Customizing TEI to Check Pointers](https://www.wwp.neu.edu/research/publications/documentation/other/checking_pointers_in_ODD.html).
