### ISSUE TITLE
shouldn't the presence of @target or @cRef be made mandatory on <ref>?

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1676]
In the documentation for `<xr>`, a bare `<ref>` is used in an example, with no comment on the semantic anomaly that it introduces: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-xr.html

```<xr type="syn">SYN. see <ref>legal</ref></xr>```

It worries me that this is shown in green, and with no discussion, which in official documentation should suggest a pattern to follow, while most certainly it is nonsense rather than a pattern to follow... (?)

In case someone offers an answer along the lines of "potential reference", I would retort that around 80% of words used in dictionary definitions are "potential references", and yet we don't tag them with `<ref>`, just because someone, some day, might have the whim to supply a `@target` for them.

**Comment by laurentromary** [comment]
I would not put any kind of obligation on the corresponding attribute  because this seems to be an acceptable use case to mark up any kind of reference (e.g. bibliographic) without resolving it fully.

**Comment by bansp** [comment]
So you're saying that the example in the documentation of `<xr>` is the recommended way to go? Empty `<ref>`s all around the place? 
("`<ref>`  defines a reference to another location, possibly modified by additional text or comment")

**Comment by laurentromary** [comment]
No, no, I am saying this a possible use (there is x). From a logical point of view, it does mean I would recommend for all usages (for all x).

**Comment by bansp** [comment]
Except we may be looking at an inductive context whereby one may interpret that "attested" means "not discouraged in general", and I have a problem with this interpretation of `<ref>`, especially in dictionary contexts, and especially with the view that "if something _may_ be a reference, it may be tagged with `<ref>`", known to the two of us and the Berlin group in a bit more dangerous (in my personal view) incarnation whereby when something, in some contexts, for some uses, may be considered a functional reference, it is recommended to mark it up as a formal reference.

Coming back to the case at hand: what's your opinion on the example quoted above, please? In both examples in the documentation of `<xr>`, bare `<ref>` is used. No other examples are provided.

(Aside: the definition of `<ref>` treats the "additional text or comment" as optional, which is also weird, and may suggest nonsense such as `<ref/>` -- no referential attribute needed, because "there is x" which doesn't use it, and no text, because the definition treats it as optional. In case someone wondered, here's the breaking news: `<ref/>` validates... I guess such markup should be interpreted as "this spot, just like any other spot, might become a reference, some day"...)

**Comment by jamescummings** [comment]
Hi @bansp and @laurentromary, 

`<ref>` is used plenty of places where it doesn't necessarily make sense to have a `@target` on it. i.e. marking up that something is a bibliographic reference without necessarily having a full bibliography entry (`<bibl>`) to point at.  Or other forms of textual reference for which you don't want to create some system of pointers that you aren't going to use.  It is important to remember that tei:ref is not necessarily equivalent to html:a. 

However, having a bare `<ref>` in that example seems a bit strange to me, so maybe we should change that?

**Comment by jamescummings** [comment]
F2F agrees that it is wrong to insist that `<ref>` have a target or cRef attribute. There are plenty of prose references that have nothing pointable. But people can do this in their customisations if they wish. If you want to fix the example, submit a patch on a new issue.
