### ISSUE TITLE
<gb/> should have @ed and @edRef

### ISSUE THREAD

**Issue by MarjorieBurghart** [TEIC/TEI#1677]
Hi guys! 
I've just realised that `<gb/>` does not have the @ed and @edRef attributes, while `<pb/>, <cb/> and <lb/>` all do. 
I'm guessing that the reasoning was that if you're using `<gb/>` you're doing a transcription of a single document / documentary edition. 
But I can't see why you wouldn't want to mark up the quires in several manuscripts when doing a critical edition. And in this case you'll need the @ed / @edRef attributes to differentiate between the quires of each ms.

**Comment by lb42** [comment]
I think you mean @ed rather than @ref, no?

**Comment by MarjorieBurghart** [comment]
Ooops, yes, obviously. Edited my initial post accordingly. Thanks!
