### ISSUE TITLE
Update prose for 3.5.1 Referring Strings (rs@type)

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#1684]
As per #1035 rs was added to att.typed, but http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONARS still says: "The name element is a member of the att.typed class [...]. The rs element defines the type attribute locally."

**Comment by sydb** [comment]
Good catch. Fixed in 59847e63590d815a96df0558f3cecc3856b3b25b
