### ISSUE TITLE
gloss on value "OCLC" for idno@type

### ISSUE THREAD

**Issue by kshawkin** [TEIC/TEI#1685]
The gloss for the value "OCLC" on `idno@type` currently says:

> union catalog number in WorldCat representing a resource held by one or more of the member libraries in the global cooperative Online Computer Library Center.

I recommend the following instead:

> OCLC control number (record number) for the union catalog record in WorldCat, a union catalog for member libraries in the global cooperative OCLC.

It's known as the "OCLC control number" or "OCLC record number", so we should stick with that terminology.

**Comment by scstanley7** [comment]
Happy to make this change in an hour or so, if no one objects between now and then. Should we keep some reference to the full "Online Computer Library Center" or has OCLC done the trendy thing where they dropped the full name and initialism doesn't *technically* stand for anything anymore?

**Comment by kshawkin** [comment]
They are doing business as "OCLC Online Computer Library Center, Inc.", but that's kind of ridiculous.  Perhaps write this instead:

> OCLC control number (record number) for the union catalog record in WorldCat, a union catalog for member libraries in the Online Computer Library Center global cooperative.

**Comment by sydb** [comment]
That last phrasing looks good to me. I would say go for it. Then again, I don’t know what I’m talking about.
