### ISSUE TITLE
add <form> to att.typed

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1688]
Please consider adding `<form>` to att.typed. It currently has the `@type` attribute defined internally, which creates an expectation that it is coherent with most of the other elements that feature `@type`, that is, that it also has `@subtype` at its disposal.

The immediate use case comes from work on TEI Lex0, an exchange format for retrodigitized dictionaries, but I hesitate to bring in the details because it seems to me that the general argument suffices: there is nothing that would a priori preclude `@subtype` on `<form>`  (this is a modelling decision that the toolkit should not hinder), but quite on the contrary, the existence of `@type` creates an expectation for `@subtype` also being available.

Handling this request would speed up the process of addressing issue #386 (whose status is "Go!")

**Comment by laurentromary** [comment]
A very opportune proposal which I fully support! ;-)

**Comment by jamescummings** [comment]
Seems reasonable to me.

**Comment by bansp** [comment]
Thanks for the prompt action on this! :-)
