### ISSUE TITLE
jTEI: <placeName> in <affiliation> 

### ISSUE THREAD

**Issue by FrederikeNeuber** [TEIC/TEI#1692]
The Institute for Documentology and Editing is currently using an customized TEI scheme for the contributions in the digital journal RIDE (ride.i-d-e.de). In the future, we would like to switch to the jTEI scheme, but information that our scheme currently covers should not disappear. 
We already tested new ways to represent the current information in jTEI. However, one information that the jTEI schema does not cover and that we currently provide is a `<placeName>` within `<affiliation>`. 
Right now, we're encoding the affiliation of an author as follows: 
```
          <affiliation>
            <orgName>Royal Irish Academy</orgName>
            <placeName>Dublin, Ireland</placeName>
          </affiliation>
```
With jTEI it would only be possible to encode it as follows::
```
          <affiliation>
            <orgName>Royal Irish Academy</orgName>
          </affiliation>

```
I think the inclusion of `<placeName>` in `<affiliation>` would make sense. What do you think?

**Comment by jamescummings** [comment]
I think this is a completely reasonable. It is available in full TEI and seems a reasonable use of affiliation (rather than using it as a full bio c.f. #1686) 

The only other option I could see would be to do something like the following if that is allowed in jTEI:

````
         <affiliation>
            <orgName>Royal Irish Academy 
                 <placeName>Dublin, Ireland</placeName>
            </orgName>
          </affiliation>
````

Which seems less desirable.

**Comment by FrederikeNeuber** [comment]
It is not allowed. I tried a few things but I could not find any workaround.

**Comment by lb42** [comment]
Allowed or not it would be silly in this case since "Dublin, Ireland" isn't part of the name of the organization. Though it's not hard to think of other organizations which do include placenames, e.g. `<orgName><placeName>Oxford</placeName>University Computing Services</orgName>`.

**Comment by jamescummings** [comment]
It seems like loosening jTEI to allow placeName inside affiliation would be an easy fix.

**Comment by martindholmes** [comment]
Added placeName to the tei_jtei.odd file in commit #60abc2f66.
