### ISSUE TITLE
example of <roleName> other than in <persName>?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1695]
In P5 the `<roleName>` element is permitted outside of `<persName>`. But not one single example of its use is outside of `<persName>`. Is it bad practice to use `<roleName>` other than inside `<persName>` (or similar)? If not, then we should probably have an example of this usage.

My first instinct is that in the following, “princess” is *not* a role name:
~~~~~xml
         <sp who="#han">
            <p>Transport, this is Solo. Better take off — I can’t get to you. I’ll get <rs
                  ref="#leia">the princess</rs> out on the Falcon.</p>
         </sp>
~~~~~
but that in the following, it *is*:
~~~~~xml
         <p>On <date when="1981-11-05">5 November 1981</date>, the <roleName ref="#diana"
               >Princess</roleName>’s pregnancy was officially announced.</p>
~~~~~
Thoughts?

**Comment by ebeshero** [comment]
@sydb I think it would be difficult to **parse** the difference between the two usages in a way that will make universal sense to everyone using the Guidelines. I like these examples, and in fact I was recently consulted about how to use `<roleName>` in inline markup--and my advice was, basically, "Do you really need to do that? and if so, can you save it for a separate personography file, and find something simpler to use for inline markup?"  

My worry about this kind of fine-grained encoding is that it's hard to get everyone to agree on when a roleName is appropriate and when it's just a nickname or a some other kind of name.

**Comment by sydb** [comment]
I agree with you, @ebeshero, but is that sufficient for TEI to say `<roleName>` should **not** occur outside `<persName>`? I am not sure. Certainly P4 never permitted a `<roleName>` anywhere other than inside a `<persName>`, and I do not recall ever hearing a convincing argument for why it should be allowed to float about on its own. But it is allowed, so shouldn’t we show an example?

**Comment by ebeshero** [comment]
@sydb In order to figure out a *good* example, it would be helpful to review any conversations we've had about this, on the TEI-list and in Council...I'd like to understand the reasoning. I don't think it's wrong to use it outside of persName, but I wonder if it ought to be advisable only in circumstances where role names are being investigated specifically--like say in a text encoding of an anthropological survey or typology of leadership roles in chieftain-level societies. Imagine a list of roleNames associated with medicinal practices, temple-building, or (ha!) codicology...?

**Comment by ebeshero** [comment]
That is to say, perhaps we'd present examples wherein roles are discussed **separately** from particular named individuals who occupied those roles.

**Comment by ebeshero** [comment]
What about an encoding of a passage of a Constitution or treaty? (Of course, I'll work on investigating the discussions we've had of this, too...)

**Comment by martindholmes** [comment]
Isn't `<persName>` syntactic sugar for `<name type="person">? If so, shouldn't `<roleName>` be allowed in `<name>` too?

**Comment by ebeshero** [comment]
presumably it should be allowed in `<rs>` as well...

**Comment by ebeshero** [comment]
...as in <rs type="person">He who was the <roleName>King of England</roleName></rs> was so no longer.

**Comment by ebeshero** [comment]
@martindholmes Actually, it's already permitted inside `<name>` and `<rs>` apparently: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-roleName.html

**Comment by JonPrag** [comment]
Can I ask if this conversation went any further? I've been wanting to ask this question for some time: I'm encoding ancient Greek and Latin inscriptions, and while officials are regularly named, they are also regularly not named and `<roleName>` looks ideal for capturing when e.g. an official or priest is referenced but not named. There seems a reluctance in the EpiDoc TEI community to embrace this, but I'm not clear why beyond the absence of use this way so far.

**Comment by ebeshero** [comment]
@JonPrag We didn't continue discussing it, but I think my "role" on this (ahem!) is to collect some good examples and write some explanation of when it's appropriate for `<roleName>` to be used on its own. If you'd like to submit some examples from your inscriptions, that would be really helpful! I'll be working this ticket soon (I promise) and that'll mean, I hope, that by the next release, we'll have some better explanation and examples for this element to appear on its own.

**Comment by ebeshero** [comment]
Example: the Attorney General (rolename that is not limited to a particular individual).

**Comment by emylonas** [comment]
Possible example: 

"THE S.[olicitor] G.[eneral] is traditionally called the “tenth justice,” though it’s obvious the Court has only nine justices."  
citation: 
Caplan, Lincoln, "The Political Solicitor General. The 'Tenth Justice' and the polarization of the Supreme Court" Harvard Magazine. September-October, 2018.  [https://harvardmagazine.com/2018/09/the-political-solicitor-general](https://harvardmagazine.com/2018/09/the-political-solicitor-general)

**Comment by tuurma** [comment]
Thanks @emylonas and @ebeshero for good examples, I will follow up on incorporating these in the guidelines.

**Comment by tuurma** [comment]
Used the article mentioned by @emylonas to find passages illustrating two different usages of `roleName` - as a form of referencing a person and a reference to the office itself. If we agree I will follow up and add these to the guidelines.

```xml
The <roleName role="#solicitor_general">S.G.</roleName> is the only national public official, including the Supreme Court justices, required by statute to be “learned in the law.”
```

```xml
<persName ref="#NJF"><roleName role="#solicitor_general">Solicitor General</roleName> Noel J. Francisco</persName>, representing the administration, asserted in rebuttal that there was nothing to disavow (...) 
<persName ref="#NJF">Francisco</persName> had violated the scrupulous standard of candor about the facts and the law that <roleName role="#solicitor_general">S.G.s</roleName>, in Republican and Democratic administrations alike, have repeatedly said they must honor.
```

**Comment by ebeshero** [comment]
@tuurma I think we can add these examples in time for the release, right? (I just added it to the July release milestone...)
