### ISSUE TITLE
model.entryPart.top for <pc> and <lbl>

### ISSUE THREAD

**Issue by iljackb** [TEIC/TEI#1702]
## Introduction

In this issue it is requested that we make a change to right an existing glaring gap in the dictionary module by allowing `<pc>` and `<lbl>` to occur directly as a child of `<entry>`, specifically by making each a member of: [model.entryPart.top](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.entryPart.top.html). Despite the ubiquitous presence of punctuation to delimit fields and labels to delimit sections of an entry in print dictionaries, there is no consistent or valid way to encode this within `<entry>`. Thus this forces the user to use `<entryFree>` or some various form of tag abuse or customization to accommodate this very basic need. Changing the use of the top level tag from `<entry>` to `<entryFree>` just in order to encode non-primary content such as section labels and punctuation is extremely non-optimal as `<entryFree>` is meant to be, and generally is used as a secondary option for reserved for cases where the structure of a dictionary is too irregular for `<entry>` to handle. To have to change such a major element for such a minor issue is ultimately detrimental to the mission of standardization, causing needless divergence in the use of the TEI. Examples demonstrating the issues at hand are given below. 

## Discussion

In marking up print dictionaries it is extremely common to have: 

 a) Punctuation separating certain data fields:

	 e.g.
		feiern, sw.Vb

 b) Labels officially delimiting sections of the entry:

     e.g.
	Lautung:
		 fawrik
		 fawrikh
		 fawrikx

	Bedeutung: 
		Herstellungsbetrieb, -gebäude 

	Komposita: 
		(Aláun)fabrík
		(Augengleser)fabrík
		(Drëck)fabrík

	Verweise: 
		(Fabrík)kutscher
		(Fabrik)loden
		(Fabrik)ross
		(Fabrik)schneider
		(Fabrík)tischler

For a) the desired and natural TEI encoding would be:
```
		<entry>
                  <form type=“hauptlemma”>
                    <orth>feiern</orth>
                  </form><pc>,</pc>	    
                  <gramGrp>
                    <iType>sw.</iType><pos>Vb.</pos>
                  </gramGrp>
       		   ……
                </entry>
```
The reason that we need to encode it this way is that to include the `<pc>` inside the `<form>` or `<pron>` would falsely imply that the punctuation has something to do with the form rather than delimiting one form from the other.

Currently the only option to do this (without abusing various tags such as `<metamark>`) is to use `<entryFree>`, instead of `<entry>`, which is a disproportionately large necessary change in the data structure just to accommodate a `<pc>`.

  
For b) the desired and natural encoding would be:

```
     <entry>
       .....
       <lbl>Lautung:</lbl>
         <form type="lautung" xml:lang="bar">
           <orth>fawrik</orth> 
          </form>
          <form type="lautung" xml:lang="bar">
             <orth>fawrikh</orth> 
           </form>
           <form type="lautung" xml:lang="bar">
             <orth>fawrikx</orth> 
           </form>

	<lbl>Bedeutung:</lbl>
           <sense> 
             <def>Herstellungsbetrieb, -gebäude</def>
           </sense>

       <lbl>Komposita:</lbl>
           <re><form type="compound"><orth>(Aláun)fabrík</orth></form></re>
           <re><form type="compound"><orth>(Augengleser)fabrík</orth></form></re>
           <re><form type="compound"><orth>(Drëck)fabrík</orth></form></re>

       <lbl>Verweise:</lbl>
          <re><form type="compound"><orth>(Fabrík)kutscher</orth></form></re>
          <re><form type="compound"><orth>(Fabrik)loden</orth></form></re>
          <re><form type="compound"><orth>(Fabrik)ross</orth></form></re>
          <re><form type="compound"><orth>(Fabrik)schneider</orth></form></re>
          <re><form type="compound"><orth>(Fabrík)tischler</orth></form></re>
           ......
     </entry>

```

If we want to be able to encode the original data structure we need to use `<lbl>`. While within `<entry>`, `<lbl>` is allowed in `<form>` and `<etym>`, unless we do something like `<form><lbl><form>` in order to place it in therein, it would have to be embedded within the first of a list of `<form>`’s which are all equal in status. This is not a useful option as the label no more belongs to the first `<form>` element than the ones that follow. Additionally, `<lbl>` is not allowed within `<sense>` so there is not even that option in that case. 

Thus, with the exception of `<etym>`, and maybe some hacks, tag abuse and/or customization, there is literally no way to encode labels in `<entry>`, which, as is the case with `<pc>`, means that the only option is to use `<entryFree>`. Needless to say, encoding punctuation and labels (two non-lexical contents) should not be a reason to have to resort to `<entryFree>`, which is, and should remain generally seen as a secondary option for cases where the encoding is extremely deviant from typical dictionary encoding structural norms. 

In the larger picture, if not resolved, this problem may contribute (or likely continue contributing) to a divergence in encoding structures in TEI dictionaries between retro-digitized and born digital dictionaries, as in the latter, there is usually no reason to include these explicit features (_or for which there exist other options to encode them using schemas such as CSS without having to markup them up in the TEI directly_). Thus born-digital sources are likely to be more free to use `<entry>`, whereas those who are constrained to adhere to the original markup of print dictionaries are more likely to use `<entryFree>`.

Therefore, it is requested that both `<pc>` and `<lbl>` be made part of **model.entryPart.top** so that we can avoid these unnecessary complications to encoding these very common dictionary contents.

**Comment by bansp** [comment]
I think about `<pc>` and `<lbl>` in this context as _house-cleaning_ elements. Having them available under `<entry>` makes it possible to maintain rigid structure of the important elements, encapsulating/isolating the bits that, as Jack noted, stand out in the comparison of digitized and born-digital dictionaries. Having punctuation and labels as elements rather than character sequences may also make it easier to convert between the machine-readable and human-readable views (yes, nitpicks are possible on this last statement, but my point here is that it would be possible to point at  `<pc>` and `<lbl>`, provide parametrized rendition information for them, etc.). The absence of the two under `<entry>` feels like omission rather than design.

**Comment by laurentromary** [comment]
Oh what a good initiative! Constantly having this argument that one should use `<entryFree>` just because a couple of essential elements are missing in `<entry>` is a real annoyance. So I am 100% in favor.

**Comment by martinascholger** [comment]
@iljackb proposal seems reasonable to me

**Comment by ttasovac** [comment]
I'd just like to mention that this is an initiative that came out of the work we did within the European Network for e-Lexicography (ENeL) and more specifically the WG "Retrodigitized Dictionaries". Also, we'll be picking up the issue of the TEI best-practice guidelines for lexicography in the context of the forthcoming H2020-funded European Network for Lexicography (ELEXIS).  We have seen a large number of cases in which the absence of `<pc>` and `<lbl>` was literally the _only_ reason why projects would opt for `<entryFree>` instead of `<entry>` and we'd really like to see more projects benefit from the stricter constraints of `<entry>` as we move forward.

**Comment by MedKhem** [comment]
From a computational point of vue, the acceptance of this proposal would definitely make automatically captured punctuation marks within a lexical entry in digitized dictionaries much easier to encode. 

> change such a major element for such a minor issue is ultimately detrimental to the mission of standardization, causing needless divergence in the use of the TEI

 says everything. [Grobid-Dictionaries](https://github.com/MedKhem/grobid-dictionaries) supports such initiative!

**Comment by martinascholger** [comment]
After response from @emylonas to my email request I set this to green.

**Comment by kdepuydt** [comment]
From the perspective of the Dutch Language Institute (Instituut voor de Nederlandse Taal), this ticket makes perfect sense. We've discussed these issues before and would love to see this change implemented.

**Comment by xlhrld** [comment]
@iljackb: Your suggesting an important feature in this ticket. Field separators have long been a cumbersome issue for digitized dictionaries at the DWDS project (at the Berlin-Brandenburg Academy of Sciences and Humanities), especially for `<pc>`. You can of course consider punctuation serving as field separators to be a typographical peculiarity and shift the burden of retaining it to `@rend` or `@rendition`. However, from a data modeling perspective it would be so much cleaner to have all character data physically existing on a printed page represented as element content. Together with cleanly separated lexical data, this would be possible only when allowing `<pc>` as a child of `<entry` (and as a child of `<sense>` which is legal already). Your argument for `<lbl>` is equivalent to the `<pc>` case – so I'd strongly support the inclusion of both in `model.entryPart.top`.

@martinascholger: I'm curious to see the arguments speaking against the implementation of this proposal which seem to be implied by you tagging this with "needs discussion".

**Comment by jamescummings** [comment]
This seems like a reasonable suggestion to me with broad support. I can't see any reason to not implement it. 

(Don't worry about the switch to 'Needs Discussion' ... we often do this in the TEI council to force us to review a ticket where no one else from council has looked at it.  It isn't necessarily an indication of there being any problems... just need for confirmation. Hopefully my message might confirm that Council should have no objection to this.)

**Comment by martinascholger** [comment]
I made `<lbl>` a member of model.entryPart.top .  This didn't work for `<pc>`, since I got an ambiguous content model. So I added elementRef pc to the content model of `<hom>` and `<entry>`.

**Comment by martinascholger** [comment]
Closing this with 6bc78db and 1f6bd01

**Comment by iljackb** [comment]
The guidelines haven't been updated to reflect this change on `<pc>`, it still doesn't have `<entry> `as a possible container for `<pc>`

**Comment by martinascholger** [comment]
@iljackb - I'm a bit confused that I cannot see your comment that you left in this ticket on October 23, but I found it in my mailbox... You said that "The guidelines haven't been updated to reflect this change on `<pc>`, it still doesn't have `<entry>` as a possible container for `<pc>`". Is this still an issue? I tested it and it works for me.

**Comment by iljackb** [comment]
Yes, that was my fault, I missed it the first time I looked at it and then
deleted it pretty quickly afterwards.

Sorry for the confusion.
