### ISSUE TITLE
adding (not replacing) ODD examples

### ISSUE THREAD

**Issue by djbpitt** [TEIC/TEI#1703]
When I change an element in my ODD and add one or more new examples, they replace the original TEI examples. I'd like to keep the TEI examples, but add my own below them. I work around this by manually copying the TEI examples into my ODD before my additions, but being able to choose whether a new **&lt;exemplum&gt;** is in "add" or "replace" mode would be welcome. Unless I've overlooked something, currently the **@mode** attribute does not appear to be valid on **&lt;exemplum&gt;** (perhaps because it would not be clear whether the intent was to modify the inventory of examples or any particular existing **&lt;exemplum&gt;** element).

**Comment by lb42** [comment]
This is a plausible requirement but also a can of worms.  Would you want to keep *all* the existing examples? If not, since exemplum elements don't have an identifier, and are not grouped within an element which does, how would you say which? And how about the ones in different languages? (I am agreeing with your parenthetical conclusion)

**Comment by djbpitt** [comment]
Complete agreement about the worms. If I had time enough, I would want to retain or exclude the existing TEI elements selectively, based on whether they are applicable to my project customization. And where my customization narrows the possibilities, I would prefer not to include an original TEI example of a usage that my project prohibits. But in my case it's also common that, for example, I've modified an existing TEI element by adding it to **att.typed** to allow a **@type** attribute on it, and in that case I want to retain the original TEI examples, to which I'll add my own illustration of how my project uses typing. Is there a minimally wormy compromise for which a path to implementation is clear?

**Comment by jamescummings** [comment]
Maybe individual exemplums ought to be identifiable? I've certainly found myself wanting to change one example for an element with multiple examples.

**Comment by ebeshero** [comment]
‘@add’ vs ‘@replace’ behavior has been much a matter of discussion lately. ‘@replace’ has meant replace everything in the TEI with my new version, but if we were able to apply it selectively, I wonder if that would be helpful in more ways than this, about ‘exemplum’?

**Comment by martinascholger** [comment]
#1713

**Comment by scstanley7** [comment]
This will be implemented along with #1713.

**Comment by ebeshero** [comment]
Oops--reset this back to the 3.7 release milestone on re-reading the tickets. I think this is ready to close, right @raffazizzi and @martinascholger ?

**Comment by ebeshero** [comment]
Was this, in fact, implemented with #1713, which is now closed? @raffazizzi Let's take a look just in case there's anything missing here. I'm not sure why the ticket is still open.
