### ISSUE TITLE
links in documentation generated from ODD?

### ISSUE THREAD

**Issue by djbpitt** [TEIC/TEI#1704]
When I create a new element in my own namespace, it is listed properly in the content models of other elements in the documentation that I generate (using the stylesheets in &lt;oXygen/&gt; 19.1), but unlike native TEI elements, it is not a clickable link that will take me to its definition in the generated documentation. It _is_ a clickable link in the list of elements at the top of the generated documentation, and also where referenced within the **&lt;div&gt;** I create as a general introduction before my **&lt;schemaSpec&gt;** elements, but not in the "Contained by" and "May contain" sections of the actual element documentation. Because my custom elements have limited scope (occur only in one context, and in a particular ordered location within that context), instead of adding them to classes, I have been incorporating them into my content models using **&lt;elementRef&gt;**, and perhaps this is the source of the different behavior. In any case, is there a natural way to coax the stylesheets to create links for these elements everywhere their name appears?

**Comment by lb42** [comment]
Looks like a stylesheet bug. Though  in the general case, if you reference an element in (say) the SVG namespace in a content model, you wouldn't expect that go find the SVG specification for that element would you?

**Comment by djbpitt** [comment]
I agree that we would not want to create links to arbitrary elements in arbitrary namespaces, such as the SVG elements you mention. But if we create links only for elements defined in an ODD (whether the official TEI ODDs upon which I build the customization or my own **&lt;elementSpec&gt;** in my own ODD), we should be able to distinguish the two cases.

**Comment by jamescummings** [comment]
I agree that this is a http://github.com/TEIC/Stylesheets bug and should be posted there.  (I can't find a way in GitHub to move issues between repositories?)

**Comment by sydb** [comment]
Assigning @alex-bia for the purpose of moving this ticket from here to Stylesheets. IF there is a clever way to move it, great. If not, just create a new ticket in Stylesheets that points here, and then close this one.

**Comment by alex-bia** [comment]
Moved to Stylesheets

**Comment by alex-bia** [comment]
Moved to [https://github.com/TEIC/Stylesheets/](https://github.com/TEIC/Stylesheets/) - issue: [#313](https://github.com/TEIC/Stylesheets/issues/313)

Copy-pasted... the best I could...
