### ISSUE TITLE
Description of <move> is misleading

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#1705]
`<move>` is currently defined like so "(movement) marks the actual entrance or exit of one or more characters on stage" (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-move.html), but has suggested `@type` values of "entrance," "exit," and "onStage." Would "marks the actual movement of one or more characters on stage" be a more accurate definition?

**Comment by jamescummings** [comment]
I see what you are saying and this seems like a corrigible bug to me.  I've marked it as 'Needs Discussion' just to gather some consensus. I would also point out that not all stage directions are given in performance texts that presuppose stage-based production and thus not all actual movement of performers is easily divisible into these three categories. (e.g. "Here Erode ragis in the pagond and in the strete also" from the Coventry Shearmen and Taylor's Corpus Christi Play). Maybe we should have an offStage suggested value as well?

However, for the matter of this issue, proposal of options of rephrasing:
a) "marks the actual movement of one or more characters on stage"
b) "marks the entrance, exit, or other actual movement of one or more characters on stage"
c) "marks the actual movement of one or more characters" (i.e. removing 'on stage')
d) "marks the entrance, exit, or other actual movement of one or more characters"  (i.e. removing 'on stage')
e) Something else?

Opinions?

**Comment by joeytakeda** [comment]
I agree with removing "on stage" as well, so I vote for option c.

**Comment by raffazizzi** [comment]
F2F subgroup says yes to (c)
