### ISSUE TITLE
front and back should allow listBibl

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1712]
Currently front and back don't allow listBibl directly. body does. I think front and back should allow listBibl, they allow listEvent, listPerson, listPlace, etc. etc.

**Comment by martinascholger** [comment]
listBibl ist already allowed in front and back

**Comment by jamescummings** [comment]
Whoops, this seems to have changed recently and my TEI Framework wasn't updated. Mea Culpa.

**Comment by martinascholger** [comment]
changed in release 3.1.0
