### ISSUE TITLE
Create Jenkins job to back up GitHub issues

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1714]
James suggests this:

https://gist.github.com/rodw/3073987#file-backup-github-sh

The idea would be to have a job that runs every week and makes a backup of all the issues on all the TEIC repos, and keeps the last three copies of them. Should not require authentication, but if it does, create a user with no privileges for it.

**Comment by martindholmes** [comment]
Now working. The new job is configured in the Jenkins repo, not this one, as jobs/backup-issues.

**Comment by ebeshero** [comment]
Huzzah!

**Comment by joeytakeda** [comment]
The Jenkins script no longer works, I think -- a number of years ago I wrote a script that did some of this backing up (and converted into CMC). 

https://github.com/joeytakeda/issue-backup

**Comment by peterstadler** [comment]
I just checked and the backup jobs works – in principle, I believe, see https://jenkins.tei-c.org/job/backup-issues/441/artifact/jobs/backup-issues/github-backups/. Yet some repositories are not backed up properly due to rate limits:
```json
{
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```
That needs to be fixed, indeed!

**Comment by martindholmes** [comment]
@joeytakeda any idea how to work around this? Or should we just designate someone on Council once a month to do a manual backup to somewhere?
