### ISSUE TITLE
Improve description of att.lexicographic

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1720]
The att.lexicographic attribute class could use a more thoughtful description than  "provides a set of attributes common to all elements in the dictionary module". That seems a little too simple, and perhaps we ought to be describing these attributes as distinguishing among different options, and normalizing values--in other words, of use for purposes *in addition* to the elements in the dictionary module. The context for opening this ticket is the discussion in #1707 .

**Comment by jamescummings** [comment]
One option might be to put attributes like `@norm` in a separate class (defined in the tei module) which att.lexicographic picks up as well. I'm not sure there is anything wrong in principle with a class being semantically related to a specific module, but just that we want to use some of these attributes elsewhere.  (I'm not arguing that the description couldn't be improved though....)

**Comment by emylonas** [comment]
rephrase, for ex as 
`att.lexicographic` provides as set of attributes used for specifiying standard values, and is common to all elements in the dictionary module as well as elsewhere"

**Comment by ebeshero** [comment]
NOTE: this isn't sufficient, because some of these attributes are not about specifying standard values--see `@split` for example. The original context was wanting to use `@norm` in non-dictionary contexts.

**Comment by ebeshero** [comment]
Marked as "go" to work on revised language, but don't close the ticket until we've discussed it.

**Comment by ebeshero** [comment]
How about this for a more broadly applicable and representative description of att.lexicographic?   
provides a set of attributes for specifying standard and normalized values, grammatical functions, alternate or equivalent forms, and information about composite parts.

**Comment by laurentromary** [comment]
That sounds good for me.

**Comment by emylonas** [comment]
This suggestion is clearer and more specific that tne original +1

**Comment by martinascholger** [comment]
Sounds good to me too. I think I prefer the conjunction.

**Comment by martindholmes** [comment]
+1 for conjunction. Don't want to give the impression that you have to choose between mutually exclusive things.

**Comment by ebeshero** [comment]
Now "go" for implementation after Tokyo F2F.
