### ISSUE TITLE
Warnings in Jenkins based on TEI_to_odd4odds.xslt

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1722]
When Jenkins builds TEI-dev it gives a couple of warnings:

~~~~
isoschematron:
     [echo] XSLT generate ISO schematron tei_customization.isosch from compiled ODD 
     [xslt] Processing /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.odd.processed to /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.isosch
     [xslt] Loading stylesheet /var/lib/jenkins/jobs/Stylesheets-dev/lastSuccessful/archive/dist/xml/tei/stylesheet/odds/extract-isosch.xsl
     [xslt] WARNING: constraint for @xml:id of the att.global class does not have a context=. Resulting rule is applied to *all* occurences of @xml:id.
     [xslt] Processing /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.isosch to /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.xsl
     [xslt] Loading stylesheet /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Utilities/iso_schematron_message_xslt2.xsl

validateschematron:
     [echo] Validate using Schematron
     [xslt] Processing /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.tei to /dev/null
     [xslt] Loading stylesheet /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.xsl
     [xslt] /var/lib/jenkins/jobs/TEIP5-dev/workspace/P5/Exemplars/tei_customization.xsl:1470:1: Warning! The child axis starting at an attribute node will never select anything
~~~~

Which, if I've followed them back correctly, refer to the schematron rule surrounding `@xml:id` needing to be unique in the document for the tei_customization ODD. This is generated by 
https://github.com/TEIC/TEI/blob/dev/P5/Utilities/TEI_to_odd4odds.xslt#L1397
and it is complaining because of its lack of specific context. 

Is there:
a) A way to fix this so the schematron doesn't complain?
b) A way for Jenkins to be told to ignore it?
c) A real need for this? Doesn't any normal xml schema validation also do xml:id uniqueness testing?

**Comment by martindholmes** [comment]
Jenkins can be told to ignore it, but that should only happen if we're sure it's the right thing to do.

**Comment by jamescummings** [comment]
I'm not sure it is, hence assigning @sydb since I think the XSLT producing this schematron is his.

**Comment by ebeshero** [comment]
We think this might not be an issue any more, but @sydb will check more closely.

**Comment by sydb** [comment]
No warnings noticed in latest TEI-dev build on Jenkins. (Given that TEI_to_odd4odds is now TEI-to-tei_customization …)
