### ISSUE TITLE
Feature request related to Event

### ISSUE THREAD

**Issue by ssagyt** [TEIC/TEI#1723]
Hello,

I would like to use an element similar to Event but independent of name or place.  The need for this has been raised a few times on the TEI Listserv in prior years.  I am working with historical documents in which I need to tag occasions such as religious ceremonies or hunting expeditions; the event itself is what is of interest, not where it occurred or what it is called. I realize Event is taken, so perhaps Occasion or Happening :-) or Activity might work.  I envision something such as `<Occasion type = "Ceremonial dance">`. I think this would be commonly used if it were implemented.

Thank you.

Toby G.

**Comment by jamescummings** [comment]
Hi @ssagyt 

I think I'm confused about this. Can you explain to me what you mean by an event that is independent of name (I assume you mean `<person>`) or `<place>`?  That is, can you tell me why you think this isn't already allowed?  The `<listEvent>` element is available a variety of places, see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-listEvent.html so there is no problem having something like the following in the body of the text:

~~~~~xml
<body>
   <listEvent>
      <event when="2015-07-01" type="huntingParty" xml:id="WP-HP">
         <label>The killing of Cecil the lion</label>
         <note>
            <p>Cecil (c. <date notBefore="2002" notAfter="2002">2002</date> – <date
                  when="2015-07-01">1 July 2015</date>) was a Southern African lion that lived
               primarily in the Hwange National Park in Matabeleland North, Zimbabwe. He was a
               major attraction at the park and was being studied and tracked by the
               University of Oxford as part of a larger study. </p>
            <p>Cecil was initially wounded with an arrow by Walter Palmer, an American
               recreational big-game hunter, then tracked, and reportedly killed with a rifle
               approximately 40 hours later on 1 July 2015. Palmer says that Cecil was killed
               with a bow and arrow in much less than 40 hours after the lion was first
               wounded. Cecil was 13 years old when killed. Palmer had a permit and was not
               charged with any crime. Authorities in Zimbabwe have said he is free to visit
               the country as a tourist but not as a hunter.</p>
         </note>
      </event>
      <event type="religiousCeremony" when="1922-03-18" xml:id="JKBM">
         <label>The Bat Mitzvah of Judith Kaplan</label>
         <note>
            <p> Judith Kaplan (<date from="1909-09-10" to="1996-02-14">September 10, 1909 –
                  February 14, 1996</date>) was a musician, theologian and the first person to
               celebrate a Bat Mitzvah publicly which she did on <date when="1922-03-18">March
                  18, 1922</date>, aged 12. </p><p>The bat mitzvah was created to address the
               gender imbalance and is the female equivalent of a boy’s bar mitzvah,
               signifying entrance into religious majority. Judith was the oldest daughter of
               Rabbi Mordecai Kaplan, the founder of the Reconstructionist branch of Judaism,
               her bat mitzvah was the first time that a woman led the congregation[4] as such
               it represents a significant shift for Conservative Judaism in America. Until
               this time women did not engage in public reading of the Torah and a Jewish
               girl's transition from child to adult was not reflected synagogue
               ceremonies.</p>
         </note>
      </event>
   </listEvent>
</body>
~~~~~

Unless what you mean is that when you encounter the name of an event in the text and you want reference the event metadata from the body of the text.  In that case I'd suggest just using `<name>` maybe something like:

~~~~~xml
<p>And the media has been filled 
with reports of <name type="event" ref="#WP-HP">Cecil's death</name>.</p>
~~~~~

Or you could use `<ref>` instead.

Or if it is that `<listEvent>` isn't allowed somewhere that you think it should be, let us know where that is, and it would be much better to allow it there than create a whole new element.

Hope that helps!

**Comment by lb42** [comment]
I share James' uncertainty about your use case. I had assumed that the requirement was to represent in some way a generic activity "hunting expedition", "ritual dance" etc. rather than a specific one ("the hunting expedition which did for Cecil the lion"),  which might really be considered as a way of classifying or analysing something else, but it's not entirely clear from your request. Would the existing `<activity>` element suit, with some obvious extensions perhaps. Requests for a new element need good examples to make them persuasive!

**Comment by ssagyt** [comment]
Thank you for the prompt and thoughtful replies.  This would be a generic event - a way of querying the multiple instances of ritual dances, for example.  I'm rather new to TEI, so correct me if I'm wrong, but I believe that if I enclose the entire paragraph in event, I can only annotate the contents of that paragraph with the attributes for event. Is there any other nesting allowed for Event?



Thank you, again.



Toby


---- On Mon, 04 Dec 2017 06:48:16 -0700 Lou &lt;notifications@github.com&gt; wrote ----




I share James' uncertainty about your use case. I had assumed that the requirement was to represent in some way a generic activity "hunting expedition", "ritual dance" etc. rather than a specific one ("the hunting expedition which did for Cecil the lion"), which might really be considered as a way of classifying or analysing something else, but it's not entirely clear from your request. Would the existing &lt;activity&gt; element suit, with some obvious extensions perhaps. Requests for a new element need good examples to make them persuasive!

**Comment by jamescummings** [comment]
Hi Toby @ssagyt, 

The `<event>` element is metadata so the equivalent to stored information about a `<person>` where the thing that appears in running text that you might transcribe is an instance of a `<name>`.   While many things are allowed inside event (see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-event.html for a full list) this is limited because it is structured metadata and not transcription. If transcribing and encountering bits of text which refer to ritual dances, then I'd mark those and point all to the same thing.  If it is just the _category_ of ritual dances being mentioned multiple times rather than multiple mentions of a specific individual event, then I would probably instead be pointing to a nested category in a taxonomy. See the second example at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-taxonomy.html for one method.  

@lb42 I like your idea of extended `<activity>` to make it more general though, I can think of other potential uses for that.

**Comment by ssagyt** [comment]
Thank you. I will give it some thought. I will also be interested in your ideas about extending 'event'.

Toby


---- On Mon, 04 Dec 2017 09:02:38 -0700 notifications@github.com wrote ----

Hi Toby @ssagyt,

The <event> element is metadata so the equivalent to stored information about a <person> where the thing that appears in running text that you might transcribe is an instance of a <name>. While many things are allowed inside event (see http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-event.html for a full list) this is limited because it is structured metadata and not transcription. If transcribing and encountering bits of text which refer to ritual dances, then I'd mark those and point all to the same thing. If it is just the category of ritual dances being mentioned multiple times rather than multiple mentions of a specific individual event, then I would probably instead be pointing to a nested category in a taxonomy. See the second example at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-taxonomy.html for one method.

@lb42 I like your idea of extended <activity> to make it more general though, I can think of other potential uses for that.
