### ISSUE TITLE
linkGrp: reword Note to reflect content model

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#1725]
In http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-linkGrp.html, there is currently an inconsistency between the Note ("May contain one or more link elements only, optionally with interspersed pointer elements.") and the content model:
```

<content>
 <alternate minOccurs="1"
  maxOccurs="unbounded">
  <elementRef key="link"/>
  <elementRef key="ptr"/>
 </alternate>
</content>
```

I suggest to  resolve this conflict by changing the Note into: "May contain one or more link or pointer elements only."

**Comment by jamescummings** [comment]
I think this is a corrigible error. Just correcting right away. Correcting the English and French versions to:
~~~~~xml
<remarks versionDate="2017-12-06" xml:lang="en">
    <p rend="dataDesc">May contain one or more <gi>link</gi> or <gi>ptr</gi> elements.</p>
    <p>A web or link group is an administrative convenience, which should be used to collect a set of links together for any purpose, not simply to supply a default value for the <att>type</att> attribute.</p>
  </remarks>
  <remarks xml:lang="fr" versionDate="2017-12-06">
    <p rend="dataDesc">Ne peut contenir qu’un ou plusieurs éléments <gi>link</gi> ou <gi>ptr</gi>.</p>
    <p> Un groupe de liens facilite les opérations de gestion de ces liens ; on devrait l'utiliser pour regrouper un ensemble de liens dans un but précis, et non pas simplement pour donner une valeur par défaut à l'attribut <att>type</att>.</p>
  </remarks>
~~~~~
Let me know if that looks wrong. I can't do the Japanese, that will have to wait until an i18n revision by someone.

**Comment by martindholmes** [comment]
What's that word "web" doing there? What's a "web group"?
