### ISSUE TITLE
Feature request related to fsdDecl

### ISSUE THREAD

**Issue by bgaiffe** [TEIC/TEI#1726]
The element fsdDecl is dedicated to declaring feature structures (fsDecl) and  feature structure declaration links (fsdLink). However, in order to declare fsDecl, it is very convenient to use on ore more fLib and/or fvLib and there is no dedicated place to do so. I thing fsdDecl could be the place for such things.

**Comment by laurentromary** [comment]
Thank you for the initiative. I had been minding this for a while. The current content model of `<fsdDecl>` is `( fsDecl | fsdLink )+` and it would be an opportunity to introduce a model class here (model.fsdDeclPart ?) and simply add fLib and fsLib there.

**Comment by bansp** [comment]
Oh yes, I recall bumping against this at least once. 
In modelling terms, it would often make a lot of sense to place the libraries high up at the root, where they dominate (or shall we say, c-command...) the particular feature declarations that reference them. Good catch, Bertrand! Thumbs up from me.
It's a bit ironic that these library declarations can be nearly anywhere _except_ where one might expect to find them, at the root of fsdDecl.

**Comment by laurentromary** [comment]
Je plussoie (I second both statements by @bgaiffe and @bansp).

**Comment by sydb** [comment]
Council has reviewed this, and thinks @peterstadler should go ahead and implement unless @lb42 raises an objection, in which we’d need to consider it first.

**Comment by lb42** [comment]
No objection from me. The only reason fLib and fvLib are not already available in fsdDecl is because they were defined later, as part of the ISO revision of feature **structure** representation; sfaik we are still waiting for the ISO view on how (or if)  feature **system** declarations should be represented. The proposed implementation makes good sense.

**Comment by peterstadler** [comment]
Just checked the [development schema](https://jenkins-paderborn.tei-c.org/view/TEI%20dev/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/custom/schema/relaxng/tei_all.rng) after the merge of #1748 and all looks good. 
Hence closing the ticket.
