### ISSUE TITLE
Why no note in witness?

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1728]
I find, to my dismay, that I can't put a `<note>` inside `<witness>`. Is there some reason for this, or just an oversight?

**Comment by lb42** [comment]
Two possible explanations: one &lt;witDetail> is to be preferred for a note about a witness (or witnesses) ; two the definition of model.limited.phrase needs a second look. Neither very satisfactory, I agree.

**Comment by hcayless** [comment]
It can't contain `witDetail>` either. I have the (slightly unusual, but hardly crazy) case where one of the entries in a *conspectus siglorum* has a footnote. Would anyone object if I added `<note>` to model.limitedPhrase?

**Comment by lb42** [comment]
withDetail is meant to point to the witness/es it is annotating, so it's a sibling of witness, not a child.

**Comment by hcayless** [comment]
witDetail can't appear in listWit either. As far as I know, its only use is in `<app>`, to annotate a reading (e.g. to note that the reading from a particular MS occurs in the margin, or is the result of a correction).

**Comment by raffazizzi** [comment]
Hm. Isn't it perhaps the case that `macro.limitedContent` should include `note`? Given that it contains `floatingText` and many other not-so-limited content elements?

**Comment by lb42** [comment]
Like I said,  the class needs looking at again. But just watch out for ambiguous content models.

**Comment by emylonas** [comment]
sounds as if adding  `<note>` inside `<witness>` is not a problem. But the question is where, does it go? `macro.limitedContent` contains `desc` `fDescr` `figDesc` `fsDescr` `meeting` `rendition` `tagUsage` `witness` so adding there would add it to all these other elements where it may not make sense.
Another suggestion is adding `model.noteLike` to the content of `<witness>` because it affects the fewest other elements.

**Comment by emylonas** [comment]
F2F recommends adding `<note>` to the content model directly. That eliminates the problem of adding `<witDetail>` as well, which is in `model.noteLike` but emphatically doesn't belong in `<witness>`

**Comment by emylonas** [comment]
closed with 996cde4
