### ISSUE TITLE
inconsistency in reason attribute definition for gap and unclear

### ISSUE THREAD

**Issue by emylonas** [TEIC/TEI#1729]
`gap/@reason` is defined as data.enumerated, but `unclear/@reason` is defined as data.word. Both are optional. The former has a list of suggested values. The latter is just defined as "occurrences of teidata.word separated by whitespace"

It seems that they should both be `teidata.enumerated` and the change in definition is unlikely to break anything. The suggested list of values is not requred on `teidata.enumerated`

**Comment by sydb** [comment]
So what @emylonas means, above, is that `unclear/@reason` should be defined as teidata.enumerated, but should be a `semi` list (as is `gap/@reason`).

**Comment by peterstadler** [comment]
seems like a corrigible error to me

**Comment by martinascholger** [comment]
Agreed, it makes sense to me that both are teidata.enumerated

**Comment by emylonas** [comment]
Had to also add some values for semi closed list. Used relevant values from `<gap>` and added most from the existing note in `<unclear>`. Values are 

- illegible
- inaudible
- faded
- background_noise
- eccentric_ductus

The last 3 could be deleted if too specialized.  didn't include "passing truck" as that is an agent, not a reason.

closed with 3652fee

**Comment by sydb** [comment]
If nothing else, `"eccentric_ductus"` probably needs a `<desc>`. @martindholmes tells me it is the strokes and speed with which a character is written.

**Comment by ebeshero** [comment]
Council F2F thinks there should be brief descriptions of each of these attribute values.

**Comment by sydb** [comment]
@MegJBrown and I used “indicates illegibility due to an unusual, awkward, or incompetent execution of a glyph or glyphs” as the description of `"eccentric_ductus"`. (We got the idea from the [DHARMA Encoding Guide for Diplomatic Editions](https://halshs.archives-ouvertes.fr/halshs-02888186/document), and gave them credit in a comment. Could we use `@source` on `<desc>`?)

**Comment by martinascholger** [comment]
In general I would say yes. But I think the question is also how to process the `@source` attribute on `<desc>` (e.g. in the HTML version of the GLs). Currently, examples and bibliographies have a link to the source displayed in a tooltip. We would have to consider that for `<desc>` as well, right?

**Comment by sydb** [comment]
Well, for now the attribution to DHARMA is recorded for posterity in a comment in the `<desc>`. Closing **this** ticket. We are free to open another one if we really want to use the `@source` of `<desc>` for this.
