### ISSUE TITLE
Error in prose of g example

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#1730]
The 2nd example in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-g.html says, "The medieval brevigraph per could similarly be considered as an individual glyph, defined in a glyph element with the identifier per like the following", but the @xml:id shown in the example is actually "per-glyph", not just "per".

**Comment by lb42** [comment]
Fixed!
