### ISSUE TITLE
occurences of <content>

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1735]
In an `<elementSpec>`, the `<content>` element is optional. Seems to me, at least in tei_customization, and maybe in P5 in general, it should be
 * required if the `@mode` is "add" or "replace"
 * optional if the `@mode` is "change"
 * not allowed if the `@mode` is "delete" (along with any other children)

Does that sound right, or am I being too hasty, here?

Furthermore, `<content>` is (deliberately) allowed 0 or more times in the content of both `<dataSpec>` and `<macroSpec>`. At first blush, this seems like a mistake to me. What does a 2nd (or 3rd or 4th or 40th) `<content>` _mean_?

**Comment by raffazizzi** [comment]
I'm all in favor of tightening these rules. I imagine you're suggesting to implement this with schematron?

Re your observations about `<dataSpec>` and `<macroSpec>`, I don't know, and P5 doesn't seem to have any with more than one `<content>`. But, I see that the content model for both has:

```
<alternate minOccurs="0" maxOccurs="unbounded">
   <elementRef key="content"/>
   <elementRef key="valList"/>
</alternate>
```

So, while in `<elemnetSpec>` both `<content>` and `<valList>` are allowed, they are mutually exclusive in this case. I wonder the one above is the only way of expressing this, at the expense of allowing unnecessary multiple `<content>`s?

But: why would one need multiple `<valList>`s anyway? Actually, what's the use of `<valList>` within anything but an `<attList>` or a `<content>`?

**Comment by sydb** [comment]
Yes, @raffazizzi, Schematron does seem like the way to go. (While this kind of co-occurrence constraint is easy to do in RELAX NG and _can_ be done in ODD, it is probably not something to exemplify.) I have just added
~~~~~xml
<constraintSpec scheme="schematron" ident="content_when_adding">
  <constraint>
    <sch:rule context="tei:elementSpec[@mode = ('add','replace')]">
      <sch:assert test="tei:content">When adding a new element (whether replacing an old one or not), a content model must be specified; but this ＜elementSpec＞ does not have a ＜content＞ child.</sch:assert>
    </sch:rule>
  </constraint>
</constraintSpec>
<constraintSpec scheme="schematron" ident="empty_when_deleting">
  <constraint>
    <sch:rule context="tei:elementSpec[ @mode eq 'delete']">
      <sch:report test="*">When used to delete an element from your schema, the ＜elementSpec＞ should be empty</sch:report>
    </sch:rule>
  </constraint>
</constraintSpec>
~~~~~
to Utilities/TEI_to_odd4odds.xslt (the routine that reads in p5subset.xml and generates Exemplars/tei_customization.odd) at 6668d67.

**Comment by sydb** [comment]
Now, to address @raffazizzi’s excellent points about `<content>` and `<valList>` in `<dataSpec>` and `<macroSpec>`.

Yeah, I don’t entirely know what to make of that either. Here is the content model @raffazizzi and I are discussing (or complaining about):
~~~~~
(
      ( model.glossLike | model.descLike )*,
      ( content | valList )*,
      constraintSpec*,
      exemplum*,
      remarks*,
      listRef*
   )
~~~~~
My complaint is with the `*` after `( content | valList )`. That asterisk allows zero or more of whichever one you pick.

I do not see the point of having either a `<dataSpec>` or a `<macroSpec>` that has neither `<content>` nor `<valList>` (and perhaps nothing), unless either its `@mode` is "delete" or "change", or (maybe) it is a `<macroSpec>` that defines a constraint using `<constraintSpec>`.

As for 2 or more of ’em, I do not know what an ODD processor is supposed to do with more than one, whether they are `<content>`s or `<valList>`s; or even if a combination thereof were allowed, I wouldn’t know what to do with a `<content>` and a `<valList>` (let alone 2 `<content>`s and 6 `<valList>`s).

My instinct, unless someone can explain the purpose and meaning of multiples, is that the `*` should be a `?`, and a Schematron rule should require one `<content>` or `<valList>` whenever the `@mode` is "add" or "replace".

And then there is the question of why both `<content>` and `<valList>` are allowed as sibling children of `<elementSpec>`. I just tried putting both in a little test ODD, and the `<valList>` was ignored (which I expected) even when the `<content>` contained `<dataRef key="teidata.enumerated"/>` (which I did not expect). But at least it is consistent: the `<valList>` is ignored even when there is no `<content>`. Sigh. IIRC, there is even already a ticket already on this (that `<valList>` does not work).

**Comment by jamescummings** [comment]
Breakout group at Face to Face in Cologne 2018-02-24 suggests adopting the constraints (as schematron rules likely).

**Comment by sydb** [comment]
Despite @jamescummings’ comment above (which mirrors what little the minutes from Köln), I don’t know exactly what constraints are GO and whether or not they should be deprecated first. So for this upcoming release I have instituted the following constraints in tei_customization (if we like them there, we can move them to P5 with or without deprecation):
1. Schematron rule added [Jan 22](https://github.com/TEIC/TEI/issues/1735#issuecomment-359545120) that requires or disallows `<content>` in `<elementSpec>` based on `@mode`.
1. Restricted content models of `<dataSpec>` and `<macroSpec>` to at most 1 of either `<content>` or `<valList>`

**Comment by sydb** [comment]
SVF2F makes green, GO, without deprecation.

**Comment by peterstadler** [comment]
Council suggests to copy the current constraints (regarding `<content>` from the [comment above](https://github.com/TEIC/TEI/issues/1735#issuecomment-406457215)) from  "tei_customization"  to the TEI specs.

**Comment by sydb** [comment]
BTW, some of the conversation above is discussing `( content | valList )*` as if it were `( content* | valList* )`, but it does not matter, the same complaints apply, and it has now been fixed.
