### ISSUE TITLE
regularize suggested values of unit= attribute

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1740]
We have quite a few occurrences of `@unit`: att.citing, att.dimensions, att.measurement, att.milestoneUnit, pc,  timeline, and when. In all cases the “suggested values include” values are singular, **except** "lines" and "chars" of att.dimensions. (`<pc>` does not have a value list.)

I am far less concerned about it, but in some cases the gloss or description is singular, in others plural. I did not see any cases where this occurred within a single value list, so it does not seem like much of a problem.

**Comment by scstanley7** [comment]
@sydb so you think that "lines" and "chars" should be switched over to "line" and "char" (along with the glosses)? Do you also think that the glosses for "cm,"  "mm," and "in" should be switched to "centimeter," "millimeter," and "inch" on the English glosses for att.dimensions?

**Comment by sydb** [comment]
Well, yes, that is what I was saying: "lines" should be "line" and "chars" should be "char" (or perhaps "character") just for consistency.

But if someone wants to argue that because "mm", "cm", and "in" are often thought of in the plural (and indeed are glossed here in att.dimensions as plural), that these should stay, I can probably be convinced.

However that does beg the question of "line" and "page" in the list for att.citing (which uses the plural in the description of `@unit`).

**Comment by lb42** [comment]
A measurement  far more frequently involves more than one "unit" (whatever the unit is) than it does a single one. So I'd say make em all plural, Or if consistency is so important,  why not change the attribute name to "units" ? (And I'd still like you to bring back "pp" and "ll" as units)

**Comment by martindholmes** [comment]
We shouldn't confuse the value with the gloss. It's perfectly OK for the value to be singular and the gloss plural. And @lb42 please let's not give people more than one option for pages and lines. We should at least nod in the direction of interoperability.

**Comment by sydb** [comment]
Forgot to reply to this:
@scstanley7> Do you also think that the glosses for "cm," "mm," and "in" should be switched to "centimeter," "millimeter," and "inch" on the English glosses for att.dimensions?

Not for "cm" and "mm", which are not abbreviations but symbols. (Which stand, BTW, for “centimetre” and “millimetre”, although the American English variants are acceptable; see [SI](https://en.wikipedia.org/wiki/International_System_of_Units).)
