### ISSUE TITLE
jTEI schema should permit <biblFull> inside <sourceDesc>

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1746]
I wrote my slides for the TEI MM in Victoria in TEI (of course). Now I’m fleshing out that slideset into a paper for jTEI. It seems to me the best way to describe the source of the jTEI file I am writing is to put a `<biblFull>` inside the `<sourceDesc>`, and then copy the contents of the `<fileDesc>` of my original slides into it (and tweak a few typos)-:.

But the jTEI schema does not permit `<biblFull>` inside `<sourceDesc>`, only `<bibl>`, `<list>`, `<listBibl>`, `<listPerson>`, `<p>`, and `<table>`.

**Comment by martindholmes** [comment]
I would argue against this. We really want to keep the jTEI schema as simple as possible, with only one way of doing each particular thing; with `<bibl>` we have maximum simplicity and flexibility. Is there some info you can encode in `<biblFull>` that you can't encode in `<bibl>`?

**Comment by sydb** [comment]
Yes, although perhaps not information you would deem particularly important. Things like:
* `<authority>` or `<distributor>` instead of `<publisher>`
* `<extent>`
*  availability and license of the source

I'm sure I could convert most everything to `<bibl>`, but it just seems this is the way TEI is supposed to work. You don’t really do any processing of stuff in the `<sourceDesc>`, do you?

**Comment by rvdb** [comment]
> You don’t really do any processing of stuff in the `<sourceDesc>`, do you?

Fair enough, but how could `<biblStruct>` be allowed inside `//sourceDesc` (and probably `//sourceDesc/listBibl`, for that matter), but not inside `//back/div[type='bibliography']/listBibl`?

Of course, Schematron could come to the rescue for some context-specific constraints, but then we'd have `<biblStruct>` all over the generated ODD documentation, which would likely raise false expectations for people who want to use `<biblStruct>` anywhere.

**Comment by lb42** [comment]
I think Syd's request was for `<biblFull>`, not for `<biblStruct>`. However, I agree with you that neither would be appropriate for  jTEI. If you want  a better solution to the OP would it not be be to permit these additional elements (authority, distributor, availability etc.),  and then add the to model.biblPart, either directly or via an appropriate subclass thereof, e.g. model.imprintPart, so that they could appear inside `<bibl>`?

**Comment by sydb** [comment]
@lb42 is correct I was asking for `<biblFull>`, but not really so much because I want `<authority>` or whatever, but because I want it to be easy to cut the (contents of) `<fileDesc>` out of one TEI document and plop it into the (`<biblFull>` inside the) `<sourceDesc>` of the jTEI article. This is what (I imagine) `<biblFull>` was, in part, intended for.

So if we’re not going to permit this change to make it really easy, I don’t think there is any reason to worry about it. (I.e., `<authority>` and `<distributor>` are already permitted inside `<bibl>`, albeit w/o the specific semantics you get inside `<publicationStmt>`.)

**Comment by rvdb** [comment]
Sorry for my careless reading/writing, of course that should have been `<biblFull>` in my reply. But still, I think it's a) heavy for jTEI, and b) a bit problematic to allow (complex) elements while not providing any processing for them. Of course, that's just my personal opinion.

**Comment by martindholmes** [comment]
I agree with @rvdb here. The jTEI schema is designed to be as simple as possible so that its processing is predictable and reliable (as it has to be, because it creates the output we use on the Journal site). @sydb, if you're not expecting these elements to be processed in any way, there's no need to include them, surely? Just include the information as text inside a `<bibl>`.

**Comment by sydb** [comment]
Right, but to be fair I’m not expecting the contents of `<sourceDesc>` to be processed by the jTEI publication system whether they are stored as a `<bibl>`, `<biblFull>`, or something else. I just think it is simpler (from the authors point of view) to copy-and-paste that information rather than to have to think about how to include said same information directly in a `<bibl>`.

**Comment by lb42** [comment]
You could copy paste it inside an XML comment!

**Comment by sydb** [comment]
Snif! The jTEI editors do not want to implement this.
