### ISSUE TITLE
Roma problem: double @rendition

### ISSUE THREAD

**Issue by schassan** [TEIC/TEI#1749]
I just generated a new set of schema files using Roma. In all schema languages I encountered error messages for the elements `<space>`, `<hi>`, `<msDesc>`, and `<scriptNote>` because the attribute @rendition has been added twice:

TEI_att.global.attribute.rendition
TEI_att.global.rendition.attribute.rendition

**Comment by peterstadler** [comment]
Do you get the result from the Webservice (http://www.tei-c.org/Roma/) or from the command line roma tool?
Additionally, could you please post the steps you took (within Roma) and/or the corresponding ODD file?

**Comment by schassan** [comment]
I used the Webservice, uploaded the attached ODD, hit "Save" once, changed nothing but only went to generate the different schemata (rng, rnc, xsd, sch, dtd)
[tei-transcript.txt](https://github.com/TEIC/TEI/files/1794793/tei-transcript.txt)

**Comment by peterstadler** [comment]
I believe the error stems from line 789 of your ODD file:

```xml
<classSpec ident="att.global" type="atts" mode="change" module="tei">
  <attList>
    <attDef ident="rendition" mode="delete"/>
  </attList>
</classSpec>
```

The attribute `@rendition` was moved out of the `att.global` class into the new `att.global.rendition` class back in release 2.8.0 (see http://www.tei-c.org/release/doc/tei-p5-doc/readme-2.8.0.html). So, changing the `@ident` in line 789 from `att.global` to `att.global.rendition` should do the trick!

**Comment by raffazizzi** [comment]
@schassan can we close this?
