### ISSUE TITLE
Additional prose and documentation fixes for att.linguistic

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1754]
This is to deliver on the promise given in ticket #1670, concerning the documentation of the freshly added class att.linguistic. I attempted to intervene inside chapter 14 only minimally and put most of the prose into a subsection (14.4.2). Modified the individual specs a bit as well.

The proposed changes can be inspected at LingSIG Jenkins pages:
- [new section, 14.4.2](http://jenkins-paderborn.tei-c.org/view/LingSIG/job/TEIP5-LingSIG-linguistic-documentation/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/AI.html#AILALW)
- [att.linguistic](http://jenkins-paderborn.tei-c.org/view/LingSIG/job/TEIP5-LingSIG-linguistic-documentation/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-att.linguistic.html)
- [pc spec](http://jenkins-paderborn.tei-c.org/view/LingSIG/job/TEIP5-LingSIG-linguistic-documentation/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-pc.html)
- [w spec](http://jenkins-paderborn.tei-c.org/view/LingSIG/job/TEIP5-LingSIG-linguistic-documentation/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-w.html)
- [diff of the pull request](https://github.com/TEIC/TEI/pull/1753/files) (it should mention 4 modified files; if the number is greater, please ping Piotr for a repository sync)

**Comment by peterstadler** [comment]
Just read through it with great pleasure, many thanks @bansp 

Just spotted two tiny typos which I'll fix in a subsequent commit.

**Comment by bansp** [comment]
Thank you very much, Peter!
