### ISSUE TITLE
All translations of `<zone>` definition are wrong

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1758]
I just noticed this in the spec for `<zone>`:

~~~~~
  <desc versionDate="2011-11-20" xml:lang="en">defines any two-dimensional area within a <gi>surface</gi>
element.</desc>
  <desc versionDate="2007-12-20" xml:lang="ko"><gi>surface</gi> 요소 내에 포함된 직사각형 영역을 정의한다.</desc>
  <desc versionDate="2008-04-06" xml:lang="es">define el área rectangular de la <gi>superficie</gi>.</desc>
  <desc versionDate="2008-04-05" xml:lang="ja">要素<gi>surface</gi>にある表面上の矩形範囲を定義する．</desc>
  <desc versionDate="2008-03-30" xml:lang="fr">définit une zone rectangulaire contenue dans un élément <gi>surface</gi>.</desc>
  <desc versionDate="2007-11-06" xml:lang="it">definisce un'area rettangolare contenuta all'interno di un lemento surface</desc>
~~~~~

Whereas `<zone>` has allowed non-rectangular polygons for at least seven years, every single translation of the `<desc>` is insisting that it's rectangular. This needs fixing as soon as possible.

**Comment by martindholmes** [comment]
@raffazizzi could you do the Italian?
@lb42 could you do the French?
@peterstadler could you do the German?

**Comment by lb42** [comment]
<desc versionDate="2018-04-30" xml:lang="fr">définit une surface planaire de tout type par rapport à un élément <gi>surface</gi>.</desc>

Note that this translation makes clearer than the English that a zone is not necessarily contained within its parent surface:
