### ISSUE TITLE
Banner Link on Guidelines section of website

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1760]
The banner link on the Guidelines section of website should be a link back to the home page of the TEI website.

The stylesheets produce:
~~~~html
<div id="banner">
  <img alt="Text Encoding Initiative logo and banner" 
src="/system/modules/org.tei.www/_common/images/banner.jpg"> 
</div>
~~~~

And I'm suggesting they should produce:
~~~~html
<div id="banner">
  <a href="/"><img alt="Text Encoding Initiative logo and banner" 
src="/system/modules/org.tei.www/_common/images/banner.jpg"></a> 
</div>
~~~~

I recognise this is a stylesheet change but I'm posting the issue here because it is about the Guidelines presentation (the stylesheet change is trivial).

Assuming no arguments I might just go do the change myself.

**Comment by peterstadler** [comment]
I totally agree. But:
During the build process of the TEI web Guidelines, the index.xml from the TEI website is scraped, see
https://github.com/TEIC/TEI/blob/014e15b6761a6a6c434ead878ff04235fe425cef/P5/Makefile#L87

This (html version of the) index.xml *itself* does not have any link back to the home page, so we don't inherit it. In fact, the new version will have this link, so I do not think we need to act now.

**Comment by peterstadler** [comment]
I spoke too soon …

The inclusion of the banner image is in fact hard coded in https://github.com/TEIC/TEI/blob/014e15b6761a6a6c434ead878ff04235fe425cef/P5/Utilities/guidelines.xsl.model#L668

A few lines later another issue surfaces, the lacking top navigation (since version 3.0.0): 
https://github.com/TEIC/TEI/blob/014e15b6761a6a6c434ead878ff04235fe425cef/P5/Utilities/guidelines.xsl.model#L677

That's a namespace issue which could be remedied by replacing the html namespace prefix with a wildcard `*:ul[@id='udm']`.

**Comment by peterstadler** [comment]
My proposal would be to wait for the deployment of the new pages and then change `TEI/P5/Utilities/guidelines.xsl.model` to simply include the `<header id="banner" >` from the new start page. This will include the image with link and the top navigation.

NB: at the current index page the banner image and the navigation are sibling elements.

**Comment by kshawkin** [comment]
Note that on the new website (driven by WordPress), the homepage will no longer be at http://www.tei-c.org/index.xml .  I suggest changing the code to refer to simply http://www.tei-c.org/ since that should be the stable location of the homepage.

**Comment by peterstadler** [comment]
Ok, just changed the Makefile to refer to http://www.tei-c.org/ in https://github.com/TEIC/TEI/commit/57383ec6bf5f584e1f618b6bc712ce5729d8dfcb. 
But I still think that the new Wordpress page should have a redirection for http://www.tei-c.org/index.xml since it's at present the canonical start page.

**Comment by jamescummings** [comment]
I think @peterstadler did what was necessary for this issues? Anything outstanding... should we close it?

**Comment by peterstadler** [comment]
Hmm, it's not in place, see https://jenkins.tei-c.org/job/TEIP5/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/index.html

But it's probably a bad time right now for debugging since the TEI website is down.
