### ISSUE TITLE
Add figure to att.written

### ISSUE THREAD

**Issue by StefanDumont** [TEIC/TEI#1765]
In the ["edition humboldt digital"](https://edition-humboldt.de) we sometimes have the case that someone other than the author inserts drawings in a manuscript (e.g. the recipient of a letter). This should, of course, be indicated. The attribute `@hand` (att.written) would be suitable, but it is not allowed in `figure` and its definition currently explicitly refers to "textual content". Nevertheless, it seems to me to make sense to define `figure` here as a class member. What does the TEI community think about it?

**Comment by lb42** [comment]
You could use @resp I suppose

**Comment by StefanDumont** [comment]
As far as I understand (correctly?) the [documentation](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHHR), `@resp` is to encode the responsibility for the mark-up itself. That's how we used `@resp` already...

**Comment by martindholmes** [comment]
+1 from me. Make `<figure>` a member of att.written, and tweak the definition of `@hand` so that it allows for drawing etc. as well as just writing.

**Comment by sydb** [comment]
I like the idea, and my instinct is it should be implemented. I’d like to give someone who knows more about use of `<handNote>` in actual mss description the chance to object, first.

**Comment by scstanley7** [comment]
@sydb are you thinking that the definition of `<handNote>` would need to be similarly modified if this change were implemented? I wouldn't want `<handNote>` to be an impediment to this solution!

**Comment by StefanDumont** [comment]
@sydb Do you know somebody with `<handnote>` knwoledge, who can have a look on this issue? This would be great. And then, what are the next steps? I would be pleased to provide a pull request with the changes ...

**Comment by lb42** [comment]
The desc of handNote doesn't preclude the use for @hand proposed here. I think the only change needed is to the desc for att.wrtten, which currently reads "provides an attribute to indicate the hand in which the textual content of an element was written in the source being transcribed". Delete the word "textual", make figure a member of att.written,  and you're all set.

**Comment by sydb** [comment]
@scstanley7 — Yes, I suppose the definition of `<handNote>` should be tweaked to make this use explicit. This would probably mean a bit of added prose in [10.7.2 Writing, Decoration, and Other Notations](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#msph2), and to the definition of the element. But whether that latter should go in `<desc>` or in `<remarks>` is not clear to me at the moment.

@StefanDumont — Yes, I was hoping someone like Brett Barney, @gabrielbodard, Elena Pierazzo, @hcayless, Malte Rehbein, @jamescummings, Amanda Galley, @PFSchaffner, Hilde Bøe, @fotisj, Federico Meschini, @jeffreycwitt, Brett Barney, @CLKCrompton, John Bryant, @jeasterly, or David Birnbaum might take a look and either give a thumbs up or post an objection.

**Comment by jeffreycwitt** [comment]
I think I'd be ok with the change, though it depends on whether handNote is meant to identify 1) a particular script (gothic cursive, intertexualis, etc) present in the manuscript or 2) the hand of a particular scribe (the description of this scribe's handwriting being a substitute for the scribe's name.)

The example somewhat suggests the former option (1): 

"Written in insular phase II half-uncial with interlinear Old English gloss in an Anglo-Saxon pointed minuscule. "

If the former (1), would a description like this really be appropriate to a figure, even if the figure was drawn by the same scribe. I mean the figure isn't drawn in "insular phase II half-uncial". That is a description that only applies to text. 

But if the latter (2) and if the description is an attempt to identify an anonymous scribe through the characteristics of their writing, then I think `@hand` could be applied to the figure. What would be meant by this connection is that the same scribe responsible for the "insular script" is the same scribe that drew the figure. 

I think the latter (2) is more inline with how I currently use handNote and so I'd be happy to see `@hand' extended to the figure, but I think the documentation should be updated to clarify this use.

**Comment by sydb** [comment]
@jeffreycwitt — Thanks for your (prompt) thoughts! Good point. I think it would remain (as always) incumbent on the encoder to either have a `<handNote>` that was vague enough to cover both the handwriting and the drawn figure, or, better yet, use two `<handNote>`s. I think we should have an example in the _Guidelines_ that demonstrates the latter.

**Comment by sydb** [comment]
Here is a completely fictitious encoding of a real letter that demonstrates a somewhat lame use of multiple `<handNote>s`.
~~~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>You are the Best Author in Human History</title>
        <title type="sub">a transcription of letter from Joshua Chamberlain to Alan Moore,
          2013</title>
        <author xml:id="JChamberl.vvz">
          <persName>Joshua Chamberlain</persName>
        </author>
      </titleStmt>
      <publicationStmt>
        <ab>Unpublished example of TEI encoding</ab>
      </publicationStmt>
      <sourceDesc>
        <ab>http://www.lettersofnote.com/2016/07/you-are-best-author-in-human-history.html</ab>
      </sourceDesc>
    </fileDesc>
    <profileDesc>
      <handNotes>
        <handNote medium="blue_ink" scope="sole" scribeRef="#JChamberl.vvz"> The entire textual
          content of the letter is written in Josh’s handwriting using blue pen. The handwriting
          uses almost completely vertical cursive lowercase letters with block capitals. </handNote>
        <handNote medium="brown_pencil" scope="minor" scribeRef="#JChamberl.vvz"> An image of Guy
          Fawlks mask worn by the protagonist of <title>V for Vendetta</title> is drawn in brown
          pencil, presumably also by Josh. </handNote>
        <handNote medium="red_crayon" scope="minor" scribeRef="#JChamberl.vvz"> A circled
            <mentioned>V</mentioned> icon for <title>V for Vendetta</title> is drawn next to the Guy
          Fawks mask in red crayon, presumably also by Josh. </handNote>
      </handNotes>
    </profileDesc>
  </teiHeader>
  <text facs="https://c1.staticflickr.com/9/8870/27818055123_eae82fee80_b.jpg">
    <body>
      <opener>
        <salute>Dear Alan Moore</salute>
      </opener>
      <p>I am writing because I want to know more about your comics including V for Vendetta,
        Watchmen, League of Extraordinary Gentlemen and Swamp Thing. I also want to say thank you
        for making such amazing graphic novels and how did you make such wonderful things?</p>
      <p>The first book I saw was V for Vendetta which has a brilliant storyline and is very cool
        when he blows up Parliament. I also love his awesome mask. Watchmen was the second, so far
        the best book I have ever seen - Rorschach is my favourite character, then Dr. Manhattan,
        lastly the Comedian. I like the way he uses a flamethrower as a cigar lighter and a smiley
        face for a badge. My third favourite was the League of Extraordinary Gentlemen. I like the
        way it’s more like a book because it has lots of writing in it and I also like the things
        that they have collected. All in all you are the best author in human history. Please write
        back.</p>
      <closer>
        <signed>Joshua</signed>
      </closer>
    </body>
  </text>
</TEI>
~~~~~

**Comment by StefanDumont** [comment]
To give it a little push, I took the liberty of making a pull request (based on James' suggestion). Feedback is of course more than welcome!

**Comment by StefanDumont** [comment]
Thanks @martinascholger and @jamescummings! I think we can close this issue now, since the pull request in #1777 was merged into the dev branch.

**Comment by martinascholger** [comment]
Thanks @StefanDumont for the pull request
