### ISSUE TITLE
mis-match in number in note of <surface>

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1767]
The note (or `<remarks>`) in the tagdoc for `<surface>` says (among other things):
“Where it is useful or meaningful to do so, any grouping of multiple <gi>surface</gi> elements may be indicated using the `<gi>`surfaceGrp`</gi>` elements. ”

That should end in either “using the `<gi>`surfaceGrp`</gi>` element.” or “using `<gi>`surfaceGrp`</gi>` elements.”.

The only reason I’m not just fixing this myself right now is in case someone has a strong preference for (or better yet, argument in favor of) one over the other.

**Comment by martinascholger** [comment]
I prefer version 1 (no strong preference)

**Comment by lb42** [comment]
I prefer version 1 too. Not just because Martina does, though not only.  Option two could be read as suggesting you always need to have multiple surfaceGrp elements.

**Comment by jamescummings** [comment]
+1 for option 1

**Comment by martinascholger** [comment]
resolved with e852dc2
