### ISSUE TITLE
GLs seem wrong about commonness of co-occurrence 

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1770]
Chapter TD states “… the attribute <att>passive</att> may be supplied only if the attribute <att>active</att> is supplied.</q>. Few schema language support co-occurence constraints such as the latter.”

Few? Probably technically true given how many schema languages are in existence, but since 3 of the big 4 (RELAX NG, Schematron, XSD > 1.0) **do** support it, it seems a bit of an odd thing to say.

**Comment by martinascholger** [comment]
How about a rewording like (instead of "Few schema language support co-occurence constraints such as the latter"):

"The schema languages RELAX NG, Schematron and XML Schema 1.1 support co-occurence constraints such as the latter."

**Comment by ebeshero** [comment]
Is the sentence about schema validation of this even necessary here?

**Comment by raffazizzi** [comment]
F2F subgroup agrees with @ebeshero that the sentence should just be cut.
