### ISSUE TITLE
make publisher member of att.canonical

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#1775]
The `<publisher>` element is defined as providing ["the name of the organization responsible for the publication or distribution of a bibliographic item."](http://www.tei-c.org/Vault/P5/3.3.0/doc/tei-p5-doc/en/html/ref-publisher.html) Thus, it is the *name* of an organisation that is to be encoded and it is common practice that names are linked to some canonical forms.

It is technically possible to nest `<orgName>` (or `<name>`) within `<publisher>` but that seems like  redundant encoding, so I propose to provide  `att.canonical` on `<publisher>` directly. This would enable me to easily link the publishers within bibliographic entries to my central index of people and organisations.

**Comment by martinascholger** [comment]
+1. In this case, shouldn't the elements `<distributor>` and `<authority>` be considered too?

**Comment by martindholmes** [comment]
+1 from me too. `<sponsor>` and `<funder>` are already in att.canonical, so surely `<distributor>` and `<authority>` should be too.

**Comment by martinascholger** [comment]
There seems to be no objection. Status Go?

**Comment by ebeshero** [comment]
Just reading it now--In addition to Peter, it'll be helpful to me and others working on coordinating prosopography with bibliography. Definitely plus 1 from me.

**Comment by jamescummings** [comment]
+1 from me.

**Comment by emylonas** [comment]
makes sense and simplifies <publisher> et al.

[Elli Mylonas
 Director, Center for Digital Scholarship
 University Library
 Brown University
 library.brown.edu/cds]

**Comment by martinascholger** [comment]
implemented with 1c8efa6
