### ISSUE TITLE
Make <trailer> a member of att.placement and att.written

### ISSUE THREAD

**Issue by paulbroyles** [TEIC/TEI#1778]
`<head>` is a member of `att.placement` and `att.written`, but `<trailer>` is not. The two elements seem as though they should be homologous, particularly given that [Guidelines 4.2.1](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSHD) describes `<trailer>` as "used to mark any heading-like feature" at the end of a division. I therefore propose that `<trailer>` be added to `att.placement` and `att.written`.

I'd like to be able to use `@place` on `<trailer>` to mark that an explicit in a manuscript occurs in a margin, just as I might with `<head>` for a marginal incipit. `@hand` is also clearly equally applicable to `<trailer>` and `<head>`, since both might be provided in a different hand from the main text.

I brought this up on TEI-L about a week ago and received no responses, so I thought I'd go ahead and open an issue.

**Comment by martinascholger** [comment]
It sounds reasonable to me to make `<trailer>` a member of `att.placement` and `att.written`. Or is there a reason why it shouldn't be?

**Comment by lb42** [comment]
Head and trailer should have the same attributes, certainly.

**Comment by martinascholger** [comment]
Open Council Session Tokyo: Go

**Comment by emylonas** [comment]
closed with 4fc51499d
