### ISSUE TITLE
XPointer scheme ambiguity

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1779]
The signatures of the [`left()`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSin), [`right()`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSR), [`string-index()`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSSI), [`range()`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSRN), [`string-range()`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSSR), and [`match()`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SATSMA) XPointer schemes (that is to say, all but `xpath()`) each include an alternation of XPATH and IDREF as their first argument. (And `range()` allows other things, too.)

An [IDREF](https://www.w3.org/TR/2008/REC-xml-20081126/#idref) is always just an XML Name; i.e., it does not start with a '#'. So we have an ambiguity problem: When software comes across `left( duck )`, how does it know whether the point being addressed is the point immediately before the element that has `xml:id="duck"` or the point immediately before the current element‘s child `<duck>`?

**Comment by hcayless** [comment]
There's no ambiguity because XPointers can occur only affixed to URLs (even if it's just `#`), meaning their context is always a resource and they have to start at the top of that resource. So you can't have a relative XPointer and therefore any XPath must be absolute, starting with a `/`.

**Comment by sydb** [comment]
OK, makes some sense. (We’re presuming XPointers cannot be used in sequence, which I believe to be the case, but I have not looked it up.) But if that’s the case, why don’t the _Guidelines_ say that?
