### ISSUE TITLE
Inviting translation of descs, glosses, remarks: workflow

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1780]
TEI Stylesheets group proposes that we consider a workflow for inviting translations that involves creating a special e-mail account, something like `tei-translations@tei-c.org`. This would appear on the page where the translation occurs on potentially out-of-date translations. Members of council would need to be monitoring this if we set it up, and we would need to organize a workflow to review incoming material.

**Comment by ebeshero** [comment]
Assigning to @martinascholger , since we need to consider creating a special account and means to review submitted translations.

**Comment by sydb** [comment]
Per Council VF2F, since we now have a group dedicated to this topic, we no longer need this particular ticket.
