### ISSUE TITLE
Mysterious schematron constraint in simplePrint

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1781]
I just fell over the following schematron constraint in the simplePrint ODD 
~~~~
<constraintSpec ident="pbposition" scheme="schematron">
 <constraint>
   <report xmlns="http://purl.oclc.org/dsdl/schematron"
  test="parent::*/text() and not  (preceding-sibling::text() and following-sibling::text())"
 >please make sure pb elements are not at the start or end of mixed content
</report></constraint>
 </constraintSpec>
~~~~
The message, though polite, is uninformative. In particular it does not explain clearly why the following perfectly reasonable encoding 
~~~~
</div><pb n="148"/>
<div type="chapter"><head >Chapter Thirty-One</head>
~~~~
is not acceptable, while the following is
~~~~
</div>
<pb n="148"/>
<div type="chapter"><head >Chapter Thirty-One</head>
~~~~
What did the originators of this constraint intend to achieve by it?

**Comment by PFSchaffner** [comment]
Interpreting the prose, rather than the constraint, I imagine an attempt to disallow "`end of par<pb/></p><p>`" and "`</p><p><pb/>beginning of para`" while enforcing this: "`end of para</p><pb/><p>beginning of para`" and allowing this: "`end of <pb/> paragraph</p><p>beginning of paragraph`" and this: "`end of paragraph</p><p>beginning <pb/> of paragraph`"  No? I.e., the opposite of what Martin just said?

**Comment by lb42** [comment]
I disclaim any responsibility for adding this constraint, whatever git blame says. And while Paul's interpretation makes good sense, it isn't supported by the actual code, any more than Martin's is!

**Comment by martindholmes** [comment]
The reason I jumped to my conclusion is that we're just working on a project which involves splitting a large text automatically into sections which will be separate files, and for that reason we've been writing constraints that force pbs to be inside divs rather than between them. But let's go back to the original simple repo to find out the history of it...

**Comment by sydb** [comment]
I think @PFSchaffner probably has the right rationale, but I cannot claim any knowledge; ’tis just a guess. That said, the following test does a better job (written as a Schematron schema to make testing easy):
~~~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"
  xmlns:sqf="http://www.schematron-quickfix.com/validator/process">
  
  <sch:ns uri="http://www.tei-c.org/ns/1.0" prefix="tei"/>
  <sch:pattern>
    <sch:rule context="tei:pb">
      <sch:report test="parent::*/text()[ not( normalize-space(.) eq '') ]
        and
        not(
           preceding-sibling::text()[ not( normalize-space(.) eq '') ]
           and
           following-sibling::text()[ not( normalize-space(.) eq '') ]
           )"
        >(<sch:value-of select="../@n"/>): please make sure pb elements are not at the start or end of mixed content</sch:report>   </sch:rule>
  </sch:pattern>
  
</sch:schema>
~~~~~
I tested this on the following teeny TEI file, and indeed it does what I think the original meant to do, but (as demonstrated by paras 16–20), does not do all that it perhaps could to find this “error”.
~~~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>Title</title>
      </titleStmt>
      <publicationStmt>
        <p>Publication Information</p>
      </publicationStmt>
      <sourceDesc>
        <p>Information about the source</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p n="1">Some text here.</p>
      <p n="2"><pb/>Some text here.</p>
      <p n="3">Some <pb/>text here.</p>
      <p n="4">Some text here.<pb/></p>
      <p n="5"><anchor/><anchor/></p>
      <p n="6"><pb/><anchor/><anchor/></p>
      <p n="7"><anchor/><pb/><anchor/></p>
      <p n="8">
        <anchor/>
        <anchor/>
        <pb/>
      </p>
      <p n="9">
        <anchor/>
        <anchor/>
      </p>
      <p n="10">
        <pb/>
        <anchor/>
        <anchor/>
      </p>
      <p n="11">
        <anchor/>
        <pb/>
        <anchor/>
      </p>
      <p n="12">
        <anchor/>
        <anchor/>
        <pb/>
      </p>
      <p n="13"><seg>duck</seg><seg>duck</seg></p>
      <p n="14"><pb/><seg>duck</seg><seg>duck</seg></p>
      <p n="15"><seg>duck</seg><pb/><seg>duck</seg></p>
      <p n="16">
        <seg>duck</seg>
        <seg>duck</seg>
        <pb/>
      </p>
      <p n="17">
        <seg>duck</seg>
        <seg>duck</seg>
      </p>
      <p n="18">
        <pb/>
        <seg>duck</seg>
        <seg>duck</seg>
      </p>
      <p n="19">
        <seg>duck</seg>
        <pb/>
        <seg>duck</seg>
      </p>
      <p n="20">
        <seg>duck</seg>
        <seg>duck</seg>
        <pb/>
      </p>
    </body>
  </text>
</TEI>
~~~~~

**Comment by martindholmes** [comment]
The constraint was added by Sebastian in May 2015, and edited by James in October the same year.

**Comment by lb42** [comment]
Does Syd's revision correctly handle the case I quoted above?

**Comment by ebeshero** [comment]
I'm assigning @sydb and @jamescummings to review this together, though James will have to dredge up some distant memories on this. :-)

**Comment by jamescummings** [comment]
My first reaction was "I did **what**?! I never edited this schematron constraint!"

The editing that @martindholmes is referring to is merely whitespace reformatting from having format-and-indented it in oXygen. 
See https://github.com/TEIC/TEI-Simple/commit/fb1024baedccd33538c1fad1b1c2e5168c00f04f#diff-2a9ef9d0770916a205c05e03d0fb5116L972 for the precise change.

I've no idea what this might have been doing, except what people have suggested here. I'm assuming this might have been related to wanting simple page-by-page navigation based on processpb.xsl or equivalent but no memory of that. @tuurma Do you have any recollection of this schematron constraint?

**Comment by sydb** [comment]
At Council VF2F we agreed to simply remove the entire constraint — both @jamescummings and @tuurma believe it is no longer useful at all (if it ever was).

**Comment by sydb** [comment]
Commit 2edf8c4ca661694448e2760265bce5a7d892ed80 fixed this. Ticket remaining open as build is broken due to #1993. Thus this is needlessly blocked, but since that ticket should be resolved soon, no particular work has to be done here and now.
