### ISSUE TITLE
`bibl` as loose model is not loose enough

### ISSUE THREAD

**Issue by GVogeler** [TEIC/TEI#1784]
The specification of `bibl` in the current specification is considered an element for any loosely-structured bibliographic description. For this reason it takes several msDesc and biblFull subelements as possible content. It excludes elements like `incipit` or `decoNote`. As incipits can replace titles and the physical features of a bibliographic entity are more than just dimensions I would suggest to extend the biblPart model by these (and maybe further) elements.

**Comment by ebeshero** [comment]
@GVogeler Are you thinking that we should extend 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.biblPart.html to include 
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.msItemPart.html  ? Or does this go too far?

**Comment by GVogeler** [comment]
@ebeshero yes, this seems sensible to me.

**Comment by jamescummings** [comment]
I'm not adverse to that. A more flexible `<bibl>` element is always desirable for me.

Of course it isn't possible just to have model.biblPart include model.msItemPart since they both some some of the same elements we'd end up with ambiguous content models, I think? We might have to refactor things into intermediate classes. It would seem a bit weird to have both msIdentifier and msItem together there to me, but I'm not that worried.

**Comment by lb42** [comment]
I otoh am decidely averse to the idea of recklessly adding everything in msItemPart into msBiblPart. . For example, model.msItemPart includes msItem, so msItems can self-nest. Which bibls most definitely cannot. (Cue long boring argument about biblipraphic standards)  By all means make a principled selection of members of the former which could also be in the latter, though

**Comment by scstanley7** [comment]
Besides `<incipit>` and `<decoNote>`, do we have a sense of what other elements would need to be? model.respLike is already a member of model.biblPart and it sounds like we want to leave out model.biblLike to avoid nested `<bibl>`s. 

Is there any reason we shouldn't do model.msQuoteLike and a freestanding `<decoNote>` or does that leave out something crucial to resolving the issue raised in the ticket?

**Comment by GVogeler** [comment]
I can imagine quoteLike (consider a text on a biblical quotation) and filiation (consider a text identified as the copy/translation of another text) as well.

**Comment by GVogeler** [comment]
@scstanley7 @lb42 considering references of review articles which use the bibliography of the reviewed item as a core identification element I don't see why the `bibl/bibl`-nesting allowed by already by model.biblPart should create a semantical special risk.

**Comment by GVogeler** [comment]
@scstanley7 @lb42 considering references of review articles which use the bibliography of the reviewed item as a core identification element I don't see why the `bibl/bibl`-nesting allowed by already by model.biblPart should create a semantical special risk.

**Comment by GVogeler** [comment]
I don't want to put brakes into the implementation of already any small extension to `bibl.Part` but I would at least like to point out that any `msDesc` could be considered a strict version of a loosely-structured bibliographic description as long as you accept that a frbr:item can be described by `bibl`. This would lead for instance to include model.phyDescPart into model.biblPart. Just for future considerations on `bibl` ...

**Comment by holfordm** [comment]
In medieval/manuscript studies there are a very large number of existing bibliographical tools that contain incipits (often many) and often explicits, as a way of exactly identifying the text cited (which may or may not have a title or titles). Stegmueller's Repertories of Biblical texts and Sentence commentaries, the Bibliotheca Hagiographica Latina, etc,  are just a few examples. I think `incipit` and `explicit` would both be useful additions for anyone who wanted to convert these or similar resources to TEI or create similar resources in TEI.

**Comment by scstanley7** [comment]
Council agrees to (directly) add `<incipit>`, `<decoNote>` and `<explicit>` to the content model of `<bibl>` (via model.biblPart).

**Comment by jamescummings** [comment]
Fixed by https://github.com/TEIC/TEI/commit/65d514e442ed266e6f6434b3bac45103155befef and tested.
