### ISSUE TITLE
improve module descriptions

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1786]
## xml:lang=en

TD = “Documentation of TEI modules”; should be something like “Documentation of XML markup languages, including TEI” or some such, no?

CE = “Certainty and uncertainty”; should be more like the title, “Certainty, Precision, and Responsibility”, I think

SA = “Linking, segmentation and alignment”, but should have the Oxford comma, no?

## xml:lang=zh-TW

SA = is obviously wrong, as the first 35 chars are the English version (the latter 8 chars are CJK).

**Comment by martinascholger** [comment]
Council at F2F agrees with the proposed improvement of descriptions

**Comment by sydb** [comment]
Made changes to the three English descriptions in d83fa42.

**Comment by sydb** [comment]
What to do with this ticket? It is ¾ completed, and I am not qualified to address the last quarter.
Recommendation:

1. Remove Guidelines 3.7.0 label, or switch to 3.8.0
2. Council chair (@martinascholger) reaches out to a speaker of Taiwanese (suggestions: @acmuller, @mbingenheimer, or Christian Wittern)
3. Either it gets fixed or nuked for 3.8.0

**Comment by sydb** [comment]
Last translation added (with thanks to @mbingenheimer) at 61c0cf6.
Change passes my 'make validate' on my local system.
