### ISSUE TITLE
Clarify description of @points in att.coordinated

### ISSUE THREAD

**Issue by martinascholger** [TEIC/TEI#1789]
This issue came up in the course of @martindholmes `<path>` proposal (#1764) when having a closer look at the `@points` attribute in `att.coordinated`. 
`@points` is defined as "identifies a two dimensional area within the bounding box specified by the other attributes by means of a series of pairs of numbers, each of which gives the x,y coordinates of a point on a line enclosing the area." 
Since the shape may cover areas outside the bounding box the following rewording is proposed by @martindholmes and me: "identifies a two dimensional area by means of a series of pairs of numbers, each of which gives the x,y coordinates of a point on a line enclosing the area."

**Comment by raffazizzi** [comment]
The rewording looks good to me

**Comment by ebeshero** [comment]
Council agrees with this rewording, after a little discussion about whether we want to keep the phrase, "specified by the other attributes" from the original description to describe the area. But the new wording seems to cover how to define the area, so we think this new wording is fine.
