### ISSUE TITLE
Language of Schematron messages where @role="nonfatal" and @role="warning"

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1795]
In reviewing our Schematron `<constraintSpec>`s for ticket #1621, I took special note of the 9 that are marked with `@role="nonfatal"` and the one and only one marked `@role="warning"`. The one marked as "warning" sounds appropriately like a warning, but the others marked as "nonfatal" mostly sound as if they're outright validation errors. Here's an example:

```
 <constraintSpec xmlns:sch="http://purl.oclc.org/dsdl/schematron"
                   ident="att-datable-w3c-when"
                   scheme="schematron">
      <constraint>
         <sch:rule context="tei:*[@when]">
            <sch:report test="@notBefore|@notAfter|@from|@to" role="nonfatal">The @when attribute cannot be used with any other att.datable.w3c attributes.</sch:report>
         </sch:rule>
      </constraint>
  </constraintSpec>
```

If we do intend to convey that a particular usage is not valid with the TEI scheme, we should remove `@role="nonfatal"` from rules like these, or revisit why we've set this `@role` attribute: what does it mean? Can we review these nine rules and make sure what we intend in each case?

**Comment by sydb** [comment]
The Schematron spec (ISO 19757-3) does not define the values of `@role`. To be honest, I do not know where the value "nonfatal" comes from. (Which is a bit embarrassing, as I think I wrote that rule.) The values that oXygen uses are: "information" (or "info"), "warning" (or "warn"), "error", and "fatal". A value other than these (e.g., "nonfatal") is treated as "error".

Although we are in no way bound by the whims of SyncRO soft, it is the editor the vast majority of TEI users use, and it is a sensible system.

**Comment by ebeshero** [comment]
@sydb I use oXygen and write Schematron (and ODDs) there, and I haven't felt compelled to use an `@role` attribute on my rules and patterns, so I don't understand the context of your comment about Syncrosoft. But I take it that we didn't intend anything specific by role="nonfatal". Does that mean that we don't intend for these to be gentle advisory warnings but rather to signal full-blown validation errors?

**Comment by sydb** [comment]
@ebeshero: I was simply pointing out that oXygen provides a controlled vocabulary for `@role` that we may wish to take advantage of. There are plenty of others in the world, of course (e.g., the one used by [syslog](https://en.wikipedia.org/wiki/Syslog#Severity_level) or [kiwi](http://www.kiwisyslog.com/help/syslog/index.html?protocol_levels.htm)), or we could make up our own (which I think would be silly). Personally, I grew up with the IBM VM/370 nomenclature:  I (Informational), W (Warning), E (Error), S (Sever error), and T (Terminating error).

However, I don’t know (or at least don’t recall) what we meant by "nonfatal". But I doubt we meant it as a gentle advisory warning, or we would have said "warn" or "warning". I think we meant something more like "error" or perhaps between "warning" and "error", but certainly not "terminating error". (For a TEI processor that can’t figure out what you mean by some bizarre combination of dating attrs can surely still process the rest of your document; it need not terminate.) But I am not sure.

**Comment by martindholmes** [comment]
As Syd knows, I have one project which purposely violates the rule against mixing other dating attributes with `@when`. It predated the rule, but I still believe the rule is misguided and shouldn't be there. :-) Nevertheless, I don't think there should be any role for a TEI constraint which does not invalidate a file unless and until there is a formal definition of what such a thing could mean in relation to conformance. And actually I don't think such a definition should be created -- sort-of-valid or more-or-less-valid or nearly-valid or a-bit-naughty are not helpful for the encoding community. The only worthwhile exception would be deprecation warnings.

**Comment by martindholmes** [comment]
@ebeshero Assuming nothing on #1621 is connected with the broken Jenkins build. :-)

**Comment by ebeshero** [comment]
@martindholmes Yikes...Looks like there's something breaking Jenkins there...I'll investigate!

**Comment by martinascholger** [comment]
Council decides to use Syncro vocab. Non-fatal error msg should be changed to Warning or Error as needed. Update TCW24 to reflect this decision.

**Comment by ebeshero** [comment]
Resolved, I think, with https://github.com/TEIC/Documentation/commit/3004d078df9e7f36883f07b0969aa329fd32409b where I have now added a mini-tutorial on the `@role` attribute.

**Comment by ebeshero** [comment]
Added a tiny commit to correct a typo in TCW20 in the new material on the `@role` attribute: https://github.com/TEIC/Documentation/commit/6aad72aa0d36a53d7a1354c64dce9ddcf56626ae
