### ISSUE TITLE
More examples of `<path>` needed

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1797]
In issue #1453, I completed the basic work, but @martinascholger and @lb42 suggested some good example page-images worth including, and I didn't get around to doing that before the merge was done for the latest release. This ticket is for me to follow up after the release and do a better job of the examples.

**Comment by martindholmes** [comment]
Working on an example based on the Sterne page now; I think that should be enough. I'm waiting for permission to use part of an image from Cambridge U as the example.

**Comment by martindholmes** [comment]
New branch mdh_issue_1797 with a more complicated example now created. Pull request coming.

**Comment by peterstadler** [comment]
Pull request merged, closing the ticket.
Thanks @martindholmes !
