### ISSUE TITLE
<egXML> not allowed in <egXML>?

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#1798]
Sorry for spamming all the TEI channels with stuff about `<egXML>`! I'm trying to compile an ODD file into a set of documentation for publication on a project; we want our documentation to have the same look and feel as the rest of the site and thus run through our own TEI-->HTML transformation. So, the pipeline for my odd (myodd.odd) is:

```
myodd.odd --(odd2odd.xsl)--> myodd_compiled.odd --(odd2lite.xsl)--> myodd_lite.xml --(myTei2Html.xsl)--> myodd.html
```

(I'm using the stylesheets from the Master branch of the stylesheet repo.) 

One issue I'm running into is that myodd_lite.xml won't validate against my schema, tei_odds.rng (https://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng), or tei_all.rng since `<egXML>` is not allowed in `<egXML>`, but the `<exemplum>` for `<egXML>` includes it:

```
<exemplum xml:lang="en">
    <egXML xmlns="http://www.tei-c.org/ns/Examples">
<egXML>
<div>
    <head>A slide about <gi>egXML</gi></head>
    <list>
     <item><gi>egXML</gi> can be used to give XML examples in the TEI
Examples namespace</item>
     <item>Attributes values for <att>valid</att>:
      <list rend="collapsed">
      <item><val rend="green">true</val>: intended to be fully
valid</item>
      <item><val rend="amber">feasible</val>: valid if missing nodes
provided</item>
      <item><val rend="red">false</val>: not intended to be valid</item>
      </list>
      </item>
      <item>The <att>rend</att>  attribute in the TEI namespace can be
used for recording how parts of the example was rendered.</item>
      </list>
</div>
</egXML>

  </egXML>
  </exemplum>
```

From what I can tell, `<egXML>` can contain any XML so long as it's not `<teix:egXML>` or in the TEI namespace. I've been trying to find where that decision was made, but I haven't been able to; the closest I can find is this comment from @lb42 (https://github.com/TEIC/TEI/issues/1373#issuecomment-162677475):

> Yes, the current definition for macro.anyXML excludes the <teix:egXML> element itself, and any element from the TEI namespace. I cannot remember why egXMLs cannot nest, except that it makes my head hurt thinking about how you'd validate that, and my proposed <anyXML> element wouldn't address this issue. It does however address the other requirement rather tidily. As for the alternative solutions proposed: my recollection is that we did discuss both of them at the FTF, and rejected them on the grounds that they introduced too much reliance on schematron, and removed something (ID/IDREF validation) clearly of importance to many TEI users.

(Having now spent some time trawling through the discussions surrounding `<egXML>`, I too can feel the headache @lb42 mentions.) But can it be the case that `<egXML>` can't nest if it does so in the Guidelines?

**Comment by joeytakeda** [comment]
In order to give a more concise example, I've attached a minimal ODD (with only egXML) and the invalid, compiled ODD (compiled using https://raw.githubusercontent.com/TEIC/Stylesheets/master/odds/odd2odd.xsl):
[egXMLTest.zip](https://github.com/TEIC/TEI/files/2242627/egXMLTest.zip)

**Comment by martindholmes** [comment]
I would avoid nesting egXMLs at all costs. It's already hard to process their contents into something pretty; if they nest, you're going to spend the rest of your life writing the rendering code.

Believe me, you don't need to do this. Life is too short. The restriction on nesting is there to save you from falling down a very deep hole, I think.

**Comment by joeytakeda** [comment]
Just to clarify this slightly: some of my introductory text above is a bit of red herring. My apologies for not being very clear. The issue here is that the egXML `<elementSpec>` produces an invalid compiled ODD because of the nested `<egXML>`s in the source.

**Comment by raffazizzi** [comment]
F2F Washington: nesting egXMLs are actually valid, but tei_all.rng is not able to validate it for some reason. You can validate it with https://tei-c.org/Vault/P5/current/xml/tei/odd/p5valid.nvdl
 
We're closing this issue as the compiled ODD is technically valid. We will investigate separately how to relaxng to perform the validation correctly.
