### ISSUE TITLE
[question] altIdent swallows primary ident on ODD compilation

### ISSUE THREAD

**Issue by duncdrum** [TEIC/TEI#1806]
While playing with closed lists in odd, something made my head scratch.

Given the following list of options in odd:

```xml
<content>
  <valList type='closed'>
    <valItem ident="XID_Start">
      <altIdent>XIDS</altIdent>
    </valItem>
    <valItem ident="kAccountingNumeric"/>
  </valList>
</content>
```

will become the following in the compiled rng:
```xml
<choice>
  <value>XIDS</value>
  <value>kAccountingNumeric</value>
</choice>
```
so `@ident` on the first item is dropped. 
I would have expected

```xml
<choice>
  <value>XID_Start</value>
  <value>XIDS</value>
  <value>kAccountingNumeric</value>
</choice>
```

Is this due to my own ignorance and WAI, or a bug?

**Comment by lb42** [comment]
More likely due to underspecification of how altIdent should be processed.

**Comment by duncdrum** [comment]
@lb42 mind pointing me towards where the processing instructions are, I haven't fully come to terms with what happens where across here and stylesheets.

**Comment by lb42** [comment]
You probably need to sign up for the council's stylesheet awareness club!

**Comment by duncdrum** [comment]
actually stumbled across a line that states this is on purpose, so ignorance after all.
