### ISSUE TITLE
Make <xr> member of att.typed

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1810]
While discussing which kinds of value we would want for xr/@type (and possibly @subtype), we see that `<xr>` is not a member of att.typed. In our shared community attempt to make the guidelines more coherent, could we have a quick implementation of this? Thanks!

**Comment by iljackb** [comment]
I think there are uses for @subtype, specifically in distinguishing types of meronymies (semantic relations).

 Meronymy (part-whole relations) can be distinguished in numerous subtypes for example [Eagles ontology vocabulary which distinguishes 6 types of meronymy](http://www.ilc.cnr.it/EAGLES96/rep2/node7.html). 

- component / integral object : there is a clear structural and functional relation between the whole and its parts, e.g. handle/cup, phonology/linguistics.

- member / set or group : parts do not necessarily have a structural or functional relation with respect to the whole, parts are distinct from each other. In this class fall for example tree/forest, student/class.

- portion / mass : There is a complete similarity between the parts and between parts and the whole. Limits between parts are arbitrary and parts do not have any specific function a priori with respect to the whole. We have in this class for example: slice/bread, centimeter/meter. This subrelation is often called a mereology.

- object / material : This type of relation describes the materials from which an object is constructed or created, or the constitutive elements of an object, e.g. alcohol/wine, steel/car.

- subactivity / activity or process : describes the different subactivities that form an activity in a structured way, for example in a temporally organized way. Into this class fall examples such as : pay/buy, give exams/teach.

- precise place / area : parts do not really contribute to the whole in a functional way. This subrelation expresses spatiality, as in : oasis/desert, Alps/Europe.

So where we use `<xr type="meronymy">` (`<xr type="meronym">`, or `<xr type="meronymyOf">` or however we write it..) someone might want to be able to have `<xr type="meronym" subtype="portionMass">`

**Comment by ebeshero** [comment]
Council agrees this is a good idea.

**Comment by emylonas** [comment]
closed with fix to #386 in commit eb69071
