### ISSUE TITLE
Add `<respStmt>` and `<resp>` to jTEI

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1812]
Following issue #1693, this is a follow-up ticket to request the addition of these elements for use in the teiHeader rather than in the body  (hence no processing required). We could constrain their use to the header through Schematron.

**Comment by rvdb** [comment]
I've added both elements in https://github.com/TEIC/TEI/pull/1814. Note, this doesn't make `<respStmt>` available in `<titleStmt>`, since that has a simplified content model in jTEI (only allowing `<title>` and `<author>`). Should it be included there, too?

**Comment by martindholmes** [comment]
The original request was only for sourceDesc/bibl, so there's no reason (yet) to  add it to titleStmt. I also wonder if we should constrain it so that it can only appear in sourceDesc, so that it doesn't end up being used in (e.g.) bibls in the bibliography, where we'd have to decide how to process it. What do you think?

**Comment by martindholmes** [comment]
Added a constraint in commit #c70f41ce6. If nothing breaks, I think we can close the ticket.

**Comment by martindholmes** [comment]
Tested, all good, closing ticket.
