### ISSUE TITLE
Guidelines: customized ODD examples based on teiCorpus? 

### ISSUE THREAD

**Issue by vbigot-juloux** [TEIC/TEI#1824]
Since cuneiform (but not only) can be very specific, I think it would be helpful to add a few examples regarding customized ODD based on `<teiCorpus>`. This concern is based on my question on [stackoverflow](https://stackoverflow.com/questions/50161914/oxygenxml-add-an-ad-hoc-attribute-to-teicorpus-framework) and the kind answer of [Piotr on TEI-L](https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1805&L=TEI-L&P=R339&X=D1AD8354F09EAC1CB7&Y=vanessajuloux%40me.com)--I have then decided to work on a customized ODD--for beginners, ODD is not easy indeed thus it can discourage a few beginners/average level TEI/ODD practitioners.

**Comment by tuurma** [comment]
Thanks @vbigot-juloux, could you please clarify if you'd like to see 1. examples of already existing ODD files which customise TEI for the purpose of specific project or 2. tutorials how to create an ODD customisation? 

If you don't mind I will assign this as your first issue for clarification, welcome on the Council :-)

**Comment by vbigot-juloux** [comment]
> Thanks @vbigot-juloux, could you please clarify if you'd like to see 1. examples of already existing ODD files which customise TEI for the purpose of specific project or 2. tutorials how to create an ODD customisation?

Both. What I suggest is:
1. A list of questions that an Assyriologist can ask to him/herself: i.e. “How can I do for...?”
2. Afterward, the list of answers: for each, either a link to a section of a current ODD section (+ TEI guidelines section) or a short tutorial on how to create an ODD customisation for this specific need.

I propose two subsections (maybe more but at least these two subsections are the most important for now) which will include questions/answers:
1. Cuneiform tablets/artefact
2. Philological analyses

**Comment by ebeshero** [comment]
This is a great idea, and maybe this needs to be part of a tutorial for the Assyriology community. Also, if you have some examples encoded, @vbigot-juloux and colleagues these could make great examples to diversify the Guidelines.

**Comment by tuurma** [comment]
Also, @vbigot-juloux, while Guidelines are not really a place to highlight a particular customisation, TEI Publisher likely would be interested to incorporate an example if it's of interest to epigraphic community.

**Comment by martinascholger** [comment]
@vbigot-juloux I'm closing this for now. Please feel free to re-open.
