### ISSUE TITLE
PM for list in tei_simplePrint.odd only lets item through

### ISSUE THREAD

**Issue by joewiz** [TEIC/TEI#1829]
When using tei_simplePrint.odd's processing model, the model for `<list>` contains a `content` parameter whose value is the list's child `<item>` elements. See:

https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_simplePrint.odd#L4478-L4485

Unfortunately, this prevents elements that are permitted inside `<list>`, such as `<pb>` and `<milestone>`, from being processed. Effectively, anything that isn't an `<item>` element is stripped from the output.

I would propose removing the `content` parameter, which will allow processing of all child nodes of a `<list>` element, not just `<item>` elements. Without an explicit `content` parameter, the default processing will take place - as described in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDPMMB:

> This parameter [`content`] is not strictly necessary, since by default the whole content of the element being processed is always available to a processor...

I'm happy to submit a PR to this effect, if this would help facilitate the process?

**Comment by tuurma** [comment]
@joewiz please go ahead. I agree entirely with your proposal.

**Comment by tuurma** [comment]
Other kinds of lists (namely list, listBibl, castGrp and castList) have been similarly unnecessarily constrained, now fixed.

**Comment by joewiz** [comment]
@tuurma Thank you!
