### ISSUE TITLE
Any API to get element / attribute definition ? In JSON ?

### ISSUE THREAD

**Issue by pitrackster** [TEIC/TEI#1831]
Hi there !

For a project we need to dynamically get elements and attributes definition in french and english.
For this purpose I am looking for an API that I could request to get those information (probably one request per language).

Does this kind of API exists ? If yes where ?

I could achieve what I need using (here for the list element and french data) : 
http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-list.html

But I am wondering if this url is normalized... For instance could I always find the data for any element / attribute like below  ?

http://www.tei-c.org/release/doc/tei-p5-doc/my_language_key/html/ref-my_element_or_attribute.html

Thanks !

**Comment by peterstadler** [comment]
Yes, exactly, those are stable and canonical URLs. Even more stable when you point at the Vault, like `http://www.tei-c.org/Vault/P5/2.9.0/doc/tei-p5-doc/en/html/ref-damageSpan.html`; the current version being `http://www.tei-c.org/Vault/P5/current/doc/tei-p5-doc/en/html/ref-damageSpan.html`.

NB: The translations are fluid, i.e. there might exist only partial translations of descriptions, glosses or remarks for a given specification file. The HTML processing will fallback to outputting the english version and a 200 response status. (so you're client won't be able to really tell whether it's e.g. German, see http://www.tei-c.org/Vault/P5/current/doc/tei-p5-doc/de/html/ref-damageSpan.html)

**Comment by StefanDumont** [comment]
Just a hint, @pitrackster : Perhaps https://github.com/hou2zi0/tei-doc-link might be of interest to you?

**Comment by pitrackster** [comment]
Thanks both of you for your answers !
I think I'll go with the Vault URLs since I have to do the work inside a PHP script. As it is stable it is quite perfect for my needs.

> so you're client won't be able to really tell whether it's e.g. German

I see, but we can deal with it... and maybe get involved to translate what is missing ;-)

Thanks again for your answers !

**Comment by peterstadler** [comment]
Would be great to see pull requests related to translations :-) 

Thanks for getting involved!
