### ISSUE TITLE
Guidelines page links broken

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1834]
On this page:

https://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/REF-ELEMENTS.html

the list of alphabetical links is broken; the link href is only a hash with no id, and the call to JavaScript hideallExcept() appears to do nothing:

~~~~~
<a onclick="hideallExcept('element-a');" href="#">a</a>
~~~~~

Ditto for attribute classes and possibly other appendix pages. Should be a straightforward fix.

**Comment by peterstadler** [comment]
Well, it does work on the main Jenkins: https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/REF-ELEMENTS.html

I guess it's an issue with the [Content Security Policy settings](https://github.com/TEIC/Jenkins#content-security-policy-csp) on your Jenkins?

**Comment by martindholmes** [comment]
Could be, but the main issue is that it doesn't fail gracefully; those `@href` attributes should point to the relevant sections so that if JS does fail or is turned off, the links do something.

**Comment by sydb** [comment]
Note: assigned to myself to help usher this through (here or Stylesheets or both), not necessarily to do the fix myself, as I may not be able to as I don’t speak Javascript.

**Comment by hcayless** [comment]
This is a Jenkins thing. See: https://stackoverflow.com/questions/34315723/jenkins-error-blocked-script-execution-in-url-because-the-documents-frame

**Comment by jamescummings** [comment]
Works only on the paderborn jenkins ... so @martindholmes needs to fix locally.

**Comment by martindholmes** [comment]
Fixed locally. I still think it should fail more gracefully, but if nobody else does, no worries. Closing.
