### ISSUE TITLE
Request for `<desc>` in `<listBibl>`

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1841]
Although `<listBibl>` allows `<head>`, that's not really appropriate for a more detailed description of the contents. I think it would be useful to add model.descLike to the content model, following model.headLike, to allow for more detailed encoded description of what a collection contains.

**Comment by joeytakeda** [comment]
I have made a similar request in #1771 . Perhaps these can be fused?

**Comment by martindholmes** [comment]
I agree. I'd forgotten about the other ticket, but you're right that they're not the same thing because of the model.listLike issue. But why is listBibl not a member of model.listLike? That makes no sense to me.

**Comment by sydb** [comment]
1) I think adding `model.descLike*` to the content model of `<listBibl>` after model.headLike makes sense.

2) Why on earth is model.milestoneLike in the content of `<listBibl>`? Surely it should either not be there (if transcribed stuff is not allowed in a `<listBibl>`) or should be model.global instead, no?

3) @martindholmes asks above “why is `<listBibl>` not a member of model.listLike?”. Seems like the wrong question to me. I wonder why `<listApp>` and `<list>` and `<listPerson>`, three things that seem to have absolutely nothing in common (except that each has a sequence of children), are in the same class. The “Like” part of a class name is supposed to mean “behaves like, i.e. can go in similar places in the hierarchy”, not “is structured like”.

**Comment by martindholmes** [comment]
@sydb On Q2, my guess is that there are people in the world who transcribe actual bibliographies from books, or books containing actual bibliographies. If you were doing that, you would certainly need to be able to put milestones in.

On Q3, I would say that most of these lists are similar in that (outside of the scenario above) they tend to be linked-data-block type authority lists, with similar requirements for descriptive elements and child components. I would love to be able to put them all in the same place (i.e. in `<ldb>`).

**Comment by sydb** [comment]
@martindholmes :

On Q2, then you would vote for my 2nd option, using model.global instead of model.milestoneLike, yes?

On Q3, I guess I would not mind if the class were called model.linkedDataStuff or model.authorityLists. But model.listLike really means “goes where a `<list>` can go”.

**Comment by martindholmes** [comment]
@sydb you're right; model.global makes more sense.

On Q3, I've always found the naming of such things utterly confusing. "list-like" literally means "like a list", not "appearing in places a list would appear", and in any case, the latter is just weird; you shouldn't describe a context by means of the things that might appear in it, because the whole point of describing a context is in order to be able to specify the things that can appear in it. And in any case, I think things should be appearing in the same context because they are similar types of thing. `<milestone>` can appear in the same places as `<list>`; does that make it list-like?

In my dream of P6 there's none of this nonsense. Things can appear wherever they want. :-)

**Comment by peterstadler** [comment]
moving to #1771 , closing here
