### ISSUE TITLE
Remove @type from att.interpLike and use att.typed

### ISSUE THREAD

**Issue by laurentromary** [TEIC/TEI#1844]
I come across the definition of att.interpLike which is one of the few remaining place where we have an ad hoc definition of `@type`, which could be nicely replaced by adding all members of att.interpLike (`<interp>`, `<interpGrp>`, `<span>` and `<spanGrp>`) to att.typed. This is all the more easy that I don't have the feelings that the four values suggested for `@type` in att.interpLike (image, character, theme, allusion) are either exhaustive nor really relevant.

**Comment by sydb** [comment]
Part of #386.

**Comment by scstanley7** [comment]
Council is good with this. Remove `@type` from att.interpLike. Instead add `<interp>`, `<interpGrp>`, `<span>` and `<spanGrp>` to att.typed.

**Comment by martinascholger** [comment]
implemented and tested, a83fbc3
