### ISSUE TITLE
correction in an example for <secl>

### ISSUE THREAD

**Issue by s8stchro** [TEIC/TEI#1846]
For the element `<secl>` the following example is provided:

```xml
<rdg source="#Pescani">
  <secl>
    <l n="15" xml:id="l15">Alphesiboea suos ulta est pro coniuge fratres,</l>
    <l n="16" xml:id="l16">sanguinis et cari vincula rupit amor.</l>
  </secl>
</rdg>
<wit>secl. Pescani</wit>
```

As far as I can tell, the content of `<wit>` is not correct. It should have been only "Pescani".

**Comment by hcayless** [comment]
I don't agree that editorial comments can't occur in `<wit>`, but in the light of subsequent experience, I think it should probably be changed to a `<note>` instead. I will do so.
