### ISSUE TITLE
move free-standing minOccurs= and maxOccurs on elements to class?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1847]
An egregious sub-part of #386:

The attributes `@minOccurs` and `@maxOccurs` exist in only two places: `<datatype>` and att.repeatable. Is there any reason not to just put `<datatype>` into att.repeatable? The only difference is a small difference in the description, which I daresay makes the descriptions of these attrs on `<datatype>` ambiguous, anyway. (Not harmfully so, but “specification” _could_ mean the definition of the attribute value, not an instance of it.)

**Comment by martindholmes** [comment]
I would put it into the class, then override to make the definitions more precise.

**Comment by sydb** [comment]
`@minOccurs` and `@maxOccurs` now inherited by `<datatype>` from att.repeatable, and overridden for more precise wording of descriptions.
