### ISSUE TITLE
Allow titlePage and other block-level elements in rdg

### ISSUE THREAD

**Issue by frederik-elwert** [TEIC/TEI#1848]
Here’s the original rationale:

I am currently working on a digital edition based on two Arabic
manuscripts. I am using the multi-witness approach with `app`/`rdg` to
record differences between the manuscripts.

Except for minor, phrase-level variants, there are two parts with larger
differences: The title pages and the colophons.

Since `rdg` may now contain `div`, I can express the different colophons
using an `app`:

    <back>
      <app>
        <rdg wit="#alif">
          <div type="colophon">
            …
          </div>
        </rdg>
        <rdg wit="#ba">
          <div type="colophon">
            …
          </div>
        </rdg>
      </app>
    </back>

However, this approach does not work for the title pages, since `rdg` may
not contain `titlePage`. This element (and potentially other block-level elements) should be allowed as a child of `rdg`.

**Comment by hcayless** [comment]
I don't see any reason not to do this.

**Comment by ebeshero** [comment]
Council thinks this is good, and also wants to make this available for elements inside `<titlePage>`.

**Comment by ebeshero** [comment]
There is a release-blocking problem: this may not have the right effect on schema generation for oddbyexample on Stylesheets  https://github.com/TEIC/Stylesheets/issues/454 . It's not about this ticket, but about the implementation of `@except` in the Specs.

**Comment by sydb** [comment]
Reopening to (temporarily) fix in some other way than with `<classRef except="blah"/>`, until such time as [the bug](https://github.com/TEIC/Stylesheets/issues/454) processing it is resolved.

**Comment by hcayless** [comment]
We should close this because the original issue is resolved. I've added a note in TEIC/Stylesheets#454 to come back and deal with the content models.
