### ISSUE TITLE
Height/Width/Depth: loosen descriptions

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1850]
While going through the elements instantiated by the manuscript description module I reminded myself that dimensions, dim, height, width, and depth are all instantiated by this module even though I believe they are used by people not doing manuscript descriptions. 

I believe it might be worth revisiting their descriptions and consider moving them to the core module or similar at some point.  

One of the things that I noticed is that the descriptions of height, width, and depth are specific to text-bearing objects. So without change, for example, I could not provide the height, width, depth of an object that has not got any text on it. The descriptions are:

> `<depth>` contains a measurement measured across the spine of a book or codex, or (for other text-bearing objects) perpendicular to the measurement given by the width element.
> `<height>` contains a measurement measured along the axis at right angles to the bottom of the written surface, i.e. parallel to the spine for a codex or book.
> `<width>` contains a measurement measured along the axis parallel to the bottom of the written surface, i.e. perpendicular to the spine of a book or codex.
> 

A potential generalising rewording might be:

> `<depth>` contains a measurement from the front to the back of an object, perpendicular to the measurement given by the `<width>` element.
> `<height>` contains a measurement measured along the axis at a right angle to the bottom of the object.
> `<width>` contains a measurement of an object along the axis parallel to its bottom, e.g. perpendicular to the spine of a book or codex.
>

**Comment by ebeshero** [comment]
F2F approves this new wording.

**Comment by martinascholger** [comment]
Council at F2F agrees with the proposed rewording
