### ISSUE TITLE
<altIdent> should never be empty

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1859]
See also [Stylesheets#362](https://github.com/TEIC/Stylesheets/issues/362).

One (quite reasonable) solution to the bug above is to not allow an empty `<altIdent>`.

**Comment by sydb** [comment]
P.S. I don’t believe (off the top of my head) that this can be done in PureODD. Requires RELAX NG (or Schematron):
~~~~~xml
      <rng:data type="NCName">
	<rng:param name="minLength">1</rng:param>
      </rng:data>
~~~~~
Problem is, this definition (which makes perfect sense for use in `<attDef>`, `<classSpec>`, and `<elementSpec>`) is too restrictive for use in `<category>`, `<taxonomy>`, and `<joinGrp>`.

**Comment by lb42** [comment]
In pure ODD, you'd  invent a dataSpec for "nonzerolengthNCname" (come to think of it, how can you have a  zero length NCName anyway?), and then use <dataRef> within <content> for the relevant elementSpecs  ... dunno whether the stylesheets would do the right thing with it, but that's a minor implementation issue.

**Comment by sydb** [comment]
Well, yes, a `<dataSpec>`, for sure. I actually had tested the code above as the `<content>` of a `<dataSpec>` named "localdata.atLeastOneChar"; originally it was xs:string.

Much more importantly, I like your point that a 0 character long string isn’t much of an NCName so much that I just tested it. Turns out you don’t need the `<param>` at all, a 0-length string is invalid as an NCName raw. Yay!

**Comment by sydb** [comment]
However, the brilliant idea above (to just change content of `<altIdent>` from `<textNode>` to `<dataRef key="teidata.xmlName"/>`) has a **huge** problem that I have to admit, I did not notice months ago.

The `<altIdent>` element is used in the _Guidelines_ (and perhaps occasionally in someone’s ODD, whether for customization or for making up one’s own markup language) to hold the human-readable name of a module in the defining `<moduleSpec>`. Those uses of `<altIdent>` cannot be limited to an XML Name, as they are phrases in a natural language (like “Default Text Structure”).

**Comment by sydb** [comment]
Plese see #2049 instead.
