### ISSUE TITLE
Feature Request: Expand the content model of <catDesc>

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#1864]
This ticket arises from the discussion from the TEI-ListServ thread here: https://listserv.brown.edu/cgi-bin/wa?A2=TEI-L;d81ab4ec.1903. Increasingly, taxonomies and their nested categories are become central to TEI projects, with the descriptions of these categories necessarily outgrowing the limited content model that they currently have.

@martindholmes suggested that `<div>` be added to `<catDesc>` since category descriptions often require the full structure of a `<div>` with multiple paragraphs et cetera.

@jamescummings suggested the following (https://listserv.brown.edu/cgi-bin/wa?A2=TEI-L;3d5e43c9.1903)

> 1) allow an alternate of either the current model.limitedPhrase or one-or-more paragraphs (i.e. either just some text with a bit of markup or as many paragraphs as you want). That works but having more alternates between phrase and paragraph never sparks joy. ;-)
> 
> 2) Include note as a member of category's content model to enable long, detailed structured notes where needed. 
> 
> 3) Add att.canonical to category specifically to point to more detailed notes or sources of information with @ref. Precisely the way some of us might use corresp to do. 
> 

Personally, I think Martin's solution or James' (2) solution are equally good, with Martin's, while a more robust solution to the problem, a bit more radical, since it would be a backwards breaking change (unless it was an alternate between `<div>` or model.limitedPhrase).

**Comment by scstanley7** [comment]
Council subgroup discussed this, and thinks that solution 3 works best, especially since it allows you to point out to external descriptions like ones on wikipedia.
