### ISSUE TITLE
ODD spec elements should have their own source attribute

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1869]
@martindholmes and I are somewhat uncomfortable with the idea that the `@source` attribute has **entirely different** semantics when it is on “elements describing schema components” vs all other elements. (And I even think we should tighten up the definition of global `@source`, at that.) In addition, it is probably a bad idea to allow multiple values on the `@source` of, say, `<schemaSpec>` or `<elementRef>` (at least, until such time as we know what multiples would _mean_.)

The two obvious solutions are:
1. Separate out the two attributes, so that they have different properties and definitions,  even if the same name.
2. Invent a new attribute (e.g., `@oddSource` or `@schemaSource`) to be used on the ODD elements, so that they can still have the regular global `@source`, too.

**Comment by lb42** [comment]
I don't understand how solution #1 can work -- how can you separate them out if they have the same name? 
I can just about  imagine a situation where you'd want to document the source from which an ODD component was derived (global @source) as distinct from specifying the set of declarations with which it should be combined by a processor (local @source) , though it seems quite a stretch. So I suppose I support solution 2. In my teaching I've found people understand better what the thing variously called a P5 subset or a compiled ODD is if I say it's a kind of library. So how about @lib for this new attribute?

**Comment by martindholmes** [comment]
@lb42 in solution 1, you can override the definition and the datatype, constraining the latter to allow only one pointer.

**Comment by ebeshero** [comment]
Council F2F thinks we could create a new attribute, either called `@lib` or `@specSource`. Processing will have to support both `@source` and the new attribute when pointing to an ODD source. Note: We don't know what elements get the special new attribute yet, so we need to explore this, and maybe assign this to a Stylesheets Group.

**Comment by sydb** [comment]
And, just decided at today’s F2F, the new attribute should be **required** on `<schemaSpec>`.

**Comment by ebeshero** [comment]
Council discussion of 12 May 2020 rethinks this, considering #1604 as a related ticket. We now want to keep `@source`, and change the description to indicate that `@source` should behave differently on `schemaSpec` and related elements, and add a Schematron rule. And then we can close both of them.

**Comment by sydb** [comment]
Council VF2F add-on meeting thinks that changing a name is too severe a violation of backwards compatability. Thus the current decision is to retain `@source` in att.global.source, but to
1. Re-word the tagdoc prose to make the distinction more obvious, and
1. To add a constraint such that when used for ODD, only one ptr is permitted in value.

**Comment by sydb** [comment]
See #2156.
