### ISSUE TITLE
template for customization for authoring ODD bug

### ISSUE THREAD

**Issue by ChristianeFritze** [TEIC/TEI#1874]
In https://roma2.tei-c.org/ under the menu "Create a new customization starting from a template" is a template for authoring ODD. If one generates a schema starting from this template the schema is corrupt: "<error msg="to RNG then Trang to make RNC failed: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; systemId: http://www.tei-c.org/release/xml/tei/Exemplars/relaxng.rng; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>"." exclass="class java.io.IOException" >java.io.IOException: to RNG then Trang to make RNC failed: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; systemId: http://www.tei-c.org/release/xml/tei/Exemplars/relaxng.rng; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:306)
	at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:154)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)
</error>"

Martina proposes that the line "`<moduleRef url="http://www.tei-c.org/release/xml/tei/Exemplars/relaxng.rng"/>`" in the customization should be deleted.

**Comment by sydb** [comment]
Well, yes, deleting that line will stop the error. But perhaps we should figure out why that URL is returning a Google search page instead?

**Comment by lb42** [comment]
Because the URL is broken. Because website.

**Comment by martindholmes** [comment]
It isn't broken for me; I can retrieve it OK. Could you try again, @lb42 ?

**Comment by sydb** [comment]
I tried roughly the same time of my previous post. I could load that file indirectly via Firefox (Firefox did not just show me the file as expected, but asked if I wanted to save the file or open it in Firefox); when I tried `wget` I got a Google search page.

**Comment by martindholmes** [comment]
I think I see the problem: it's redirecting to https. I think we decided to update all our schema location URLs to https, didn't we? If so, perhaps whatever is handling the moduleRef should silently replace http://www.tei-c.org with https://www.tei-c.org. But there are a lot of files and systems out there pointing at http://www.tei-c.org, so perhaps we should also make schemas etc. available on plain http and not redirect them.

**Comment by peterstadler** [comment]
That hit me too. Luis set up the server to redirect all requests without a proper user agent header to Google. That’s why wget is failing and Firefox works. Took me a while ...

**Comment by raffazizzi** [comment]
Assigned to @martinascholger and @hcayless - I suggest they follow up with Luis / the board.
Alternatively these URLs could be changed in https://github.com/TEIC/Roma ?

**Comment by peterstadler** [comment]
The actual fix (changing http to https) was already applied in bb1afc3cfb54f54815ae54ad53d672fb2fbb7934. Yet Roma is running with the released version of the sources (and Stylesheets) so the error still surfaces. 

possible solutions:
* set up a Roma dev version (i.e. with current dev version of the TEI sources)
* create a hot fix release 3.5.1
* wait for the next scheduled release 3.6.0

**Comment by martinascholger** [comment]
This should be fixed with release 3.6.0. I'm closing the ticket.
