### ISSUE TITLE
att.pointing and att.scoping overlap

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1876]
(Note that issue #470 also deals with a similar one attr in multiple classes type problem.)

~~~
att.pointing = @target, @targetLang, @evaluate
att.scoping = @target, @match
~~~

I’m not sure why we went with `@match` instead of, say, `target="#xpath(../@reason)"`, but given that we did, wouldn’t it be reasonable for someone to want `@match` on most any pointer, let alone any `@target`? Certainly more precise pointing is a good thing, but as it stands you (the ODD author) can’t easily get both `@targetLang` & `@evaluate` **and** `@match`.

My initial instinct is that we should add `@match` to att.pointing, and drop att.scoping.

**Comment by lb42** [comment]
The simplest solution to this mess would be to make att.scoping a subclass of att.pointing, and suppress its definition of @ target

**Comment by martindholmes** [comment]
F2F Graz thinks all simple solutions are worse than leaving this well alone, so this is closed-won't-fix.
