### ISSUE TITLE
FR for new `<elision>` element

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1877]
The TEI-L discussion here:

https://listserv.brown.edu/cgi-bin/wa?A2=ind1904&L=TEI-L&P=62275

culminates in a consensus that there is a need either for a new element tentatively called `<elision>` or for a clear recommendation for encoding the phenomenon whereby the primary source being encoded has quoted or included another source, but omitted part of it. Some people use `<gap>` for this despite the fact that the description of `<gap>` strongly suggests that it should only be for cases where the encoder creating the digital edition is omitting material from the source text for some reason. 

The three components of the phenomenon which would need to be encodable are:

1. The fact of the elision.
2. The signal (if any) of the elision in the original text.
3. The omitted text.

My suggested encoding would look something like this:

~~~~~
<elision resp="#editorFrom1880">
   <metamark function="elisionSignalMultiline"> *  *  *  * </metamark>
   <note resp="#editorFrom1966">Three lines omitted</note>
   <supplied resp="#teiPerson2019" source="#msFrom1860">
     <l>line one....</l>
     <l>line two....</l>
     <l>line three....</l>
   </supplied>

</elision>
~~~~~

Given the array of possibilities for the signal, a fairly rich content model might be required.

**Comment by martindholmes** [comment]
Pinging Council -- any progress likely on this?

**Comment by ebeshero** [comment]
I think we lost track of this one recently, but we should make a priority of it. I like the idea of including inside the elision the material that is omitted and I suspect that will come in handy for people who may have had to use something less precise like `<note>` for this. In connection with #1945 it does suggest a need to give `<lg>` a little more flexibility for content, but `<elision>` should be expected to occur in any kind of text, of course, not just verse. I think we'll have some work to do to hammer out the content model--might be a good one to tackle with a group in a face-to-face meeting?

**Comment by hcayless** [comment]
I don't like the name "elision", as it risks confusion with the linguistic phenomenon of elision (syllable dropped or not pronounced), which is something you might certainly want to mark, but is a completely different thing. 

I'd prefer a name like "omission" or "omitted", which could be paired with `<supplied reason="omitted">` when the editor wants to put back the bits that were cut.

**Comment by ebeshero** [comment]
@hcayless I agree that `<omitted>` is clearer and doesn't suggest by itself a reason or category of omission (as in an elision of a syllable).

**Comment by wujastyk** [comment]
@hcayless @ebeshero  In the context of transcribing a manuscript, "elision" seems perfectly clear to me,  Since the context ("name space")  is distinct from linguistic analysis, I think we're going to be all right.  It will surely be rare to be transcribing a manuscript in which it is desired to mark linguistic elision, and such marginal cases can be dealt with intelligently, I'm sure.

Scribal elision is very common in pre-modern manuscripts, and all the scholars I know call the phenomenon "elision."  It's a common term of art.

"Putting back the bits omitted" and <supplied> are not really a proper option when transcribing manuscripts.  I am currently transcribing nine manuscripts of a very muddled transmission.  When one of the scribes skips a verse, I can't just supply that verse from another MS because I don't know what the scribe _would_ have written.  And the "same" verse has all sorts of variations in the other manuscripts. My critical edition isn't done, so I can't substitute a critical text either; nor would I want to.  I just want to record that the scribe elided an expected verse (or text chunk) at this point in his transcription.  I don't want to put something imagined into my transcription and mark it as "omitted."

Using the language of "omitted" or "elided" does presume an idea in my mind of what I expect the text to say, at least roughly.  But maybe my scribe was copying an older version of the text and the verse was added in the other eight manuscripts.  At the transcription stage, before one has an idea of the history of the stemma, one shouldn't presume too much.  MSS should be weighed not counted.  Nevertheless, it certainly looks like omission, an impression only strengthened when one sees initial or final fragments of text that look like parts of what is present in the other MSS.

I hope we can resolve this soon.  I need a tag now.

**Comment by hcayless** [comment]
I think the question of whether the editor wants to attempt to restore omitted text or not is a bit of a red herring. `<supplied>` is available for doing that. The main question is whether we need a new element to signal omitted text. Paul Schaffner in the thread linked above notes several types of example, and @martindholmes summarized the situation as the need to deal with

1. The signal of an elision (e.g. an ellipsis ...)
2. The act of elision
3. The omitted content

I think it would be worth taking a look at how [EpiDoc](http://www.stoa.org/epidoc/gl/latest/app-alltrans.html) deals with this sort of thing using `<gap>` before introducing a new element. In the thread, Michael Sperberg-McQueen made the point in the thread that there's no conceptual difference between a previous editor having omitted material and the current editor doing so. It's the same sort of act. Some examples:

* [Possible illegible lines](http://www.stoa.org/epidoc/gl/latest/trans-possiblyillegible.html)
* [Lost lines, quantity known](http://www.stoa.org/epidoc/gl/latest/trans-lostlineknown.html)
* [Lost lines, quantity unknown](http://www.stoa.org/epidoc/gl/latest/trans-lostlineunknown.html)
* [Lines possibly lost / text possibly breaks](http://www.stoa.org/epidoc/gl/latest/trans-possiblylost.html)
* [Text not completed (omission not restored)](http://www.stoa.org/epidoc/gl/latest/trans-textnotcompleted.html)
* [Incompletely restored text](http://www.stoa.org/epidoc/gl/latest/trans-restoredincomplete.html)
* [Words omitted by editor](http://www.stoa.org/epidoc/gl/latest/trans-ellipsis.html)

Looking at Martin's formulation, for 1) we have `<metamark>`, for 2) `<gap>`, and for 3) we have `<supplied>`. The only new thing this proposed element does is to enclose the other elements. Do we need that?

@wujastyk I would use `<gap reason="lost"/>` or `<gap reason="omitted"/>` in the cases you describe. I don't think you need a new tag.

**Comment by martindholmes** [comment]
If we don't need a new tag, then we do need to revise the content model of `<lg>` (and possibly some other elements for similar reasons); issue https://github.com/TEIC/TEI/issues/1945 takes over from this one, in effect, because we need to allow for situations in which (for example) a line-group has a head, a metamark and a gap, but no lines. Similar situations may pertain for paragraphs, lists, and other containers.

**Comment by sydb** [comment]
Sorry, I have not followed this conversation, and probably won’t for another few days. But it may be worth mentioning that we (the WWP) already have an [`<elision>`](https://wwp.northeastern.edu/wwo/source/schema/wwp-store.html#elision) element. Not sure if it’s for exactly the same thing being discussed here or not.

**Comment by wujastyk** [comment]
@hcayless Thanks, Hugh, for this clarification.
I would echo an objection about  `<gap>` that was raised back in the April conversation, namely that there is no gap in the MS I'm trying to encode.  One verse follows smoothly on from another.  No physical gap, no spaces.  In the mind of the scribe, I'm guessing, there was also no gap, in the sense that the omission or elision is unconscious or accidental.  I'm presuming the scribe suffered a saut-du-même-au-même. P5 [says](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html) that `<gap>`, "signals the editors decision to omit or inability to transcribe a span of text."   Neither of those conditions is met.

@sydb, that's interesting.  The WWP description "`<elision>` marks cases in which material is excerpted in a quotation or other textual representation within the source text." isn't clear to me.  But the example, where `<elision>` encloses asterisks, means that the tag is for marking a place where an author explicitly expresses elision.  Not where a scribe silently omits or skips something from his transcription.

@martindholmes I think this is a promising approach, though perhaps not an obvious one to transcribers who are not TEI experts.  But yes, I think if I could tag a line or line group (etc.) as being `@empty` and give a `@reason` why, that might meet the case nicely.  Can't think of a downside right now.

**Comment by hcayless** [comment]
@wujastyk `<gap>` indicates a disjuncture in the text, not necessarily a physical gap or vacat. So (e.g.) a line omitted because of homeoteleuton is a notional gap in the text, even though it isn't signaled in any way. The scribe was an editor too. If their omission of a line is an `<elision>` and your decision not to include a line is a `<gap>` (perhaps you think its a spurious bit of text that has crept in from a marginal note mistaken for a correction, e.g.), then when the next editor comes along, do they have to turn your `<gap>` into an `<elision>`? I think it's all the same thing.

Since the documentation of `<gap>` is causing this confusion though, I do think we should improve it.

**Comment by sydb** [comment]
Yes, @wujastyk, an `<elision>` is for when the source explicitly indicates “there is stuff missing here”. And yes, that is not particularly well described in the schema. It’s a little more clear in the [documentation](https://wwp.northeastern.edu/research/publications/documentation/internal/#!/entry/elision_element), but still not explicit. I will raise this issue with our staff.

**Comment by ebeshero** [comment]
VF2F: Council favors `<ellipsis>` for the name, approves the content model here. This is similar to `<mod>` and `<subst>` and `<gap>`. We need to research in what model this goes in. Documentation should make clear that this ellipsis is not the same as aposiopesis (where ellipsis points are used to indicate trailing off and not that something has been deliberately omitted).

**Comment by wujastyk** [comment]
As a working editor of early manuscripts (not a big reader of theory),
"ellipsis" and "elision" are two quite different things to me.  If a scribe
himself marked a missing passage I would tag it as "ellipsis".  If the
scribe silently missed a word from the exemplar, I would mark it as
"elision".  The latter case involves some editorial judgment on my part,
i.e., knowing what I would expect at that point in the text.

Best,
Dominik


--
Professor Dominik Wujastyk
<https://www.ualberta.ca/arts/about/people-collection/dominik-wujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History and Classics <http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.


South Asia at the U of A:

sas.ualberta.ca

**Comment by ebeshero** [comment]
@wujastyk Indeed, that's what Council wanted to be very explicit about. That is, we decided on `<ellipsis>` because we want to convey that this element is for purposeful indication in the source document that a passage has been omitted.

**Comment by wujastyk** [comment]
👍

**Comment by ebeshero** [comment]
@martinascholger Here's a ticket that has been sidetracked but I believe is ready for experimental implementation: Council worked out a good name and description for a new element, and we need to figure out where to put it. I'm going to see if I can put in a PR for the new element and place in the Guidelines so we can take a look at it this month.

**Comment by ebeshero** [comment]
I'll try a PR setting the new element `<ellipsis>` in [3.5.3](https://tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COEDADD) as part of model.global.edit. Let's see how this goes...

**Comment by ebeshero** [comment]
I'm working on an exemplum for this...I'm adapting the example that Martin provides on this ticket, but @wujastyk and @martindholmes, do either of you have a ready example from a source text that we can point to in the Guidelines Bibliography?

**Comment by martindholmes** [comment]
@ebeshero The original discussion started fron a genuine example:

https://listserv.brown.edu/cgi-bin/wa?A2=ind1904&L=TEI-L&P=62275

There's a page-image too.

**Comment by ebeshero** [comment]
Thanks, @martindholmes ! I was just thinking of refrains in song lyrics...

**Comment by JanelleJenstad** [comment]
FWIW, WWP is already using an <elision> element. https://wwp.northeastern.edu/wwo/source/schema/wwp-store.html#elision.

**Comment by wujastyk** [comment]
Glad to see this coming to life. If you would still like me to find an example, @ebeshero,  I'll do so.  Or perhaps the e.g. pointed to by @martindholmes will do.

**Comment by ebeshero** [comment]
@wujastyk I would love for you to contribute an example! Just a note about timing: I'm hoping we'll get this into the next release of the Guidelines (if my colleagues on Council agree), and that's coming up in mid-August...so, if you could contribute something in the next two or three weeks, that would be timely!

**Comment by wujastyk** [comment]
will do.

**Comment by ebeshero** [comment]
I think I've got it worked out now. @HelenaSabel sent me an interesting example that helped make the model of our new element a little more flexible than at first. I've got it passing tests now, so I'll ask Council to take a look at it with a PR. Thanks Helena, @wujastyk , and @martindholmes !

**Comment by ebeshero** [comment]
@martinascholger @HelenaSabel Would you review the pull request associated with this feature request and make sure it looks okay / merge it in for the next release?

**Comment by sydb** [comment]
I have just tested (see details below), and every use of `<wwp:elision>` can be trivially converted to `<tei:ellipsis>` (with a child `<tei:metamark>`).

## test
Read in entire textbase, extract any element that has a child `<elision>`; take the element, tuck into a `<div>` that gives some contextual information on its `@n`, and:

1. convert `<elision>XXX</elision>` to `<ellipsis><metamark>XXX</metamark></ellispsis>`
2. convert other WWP elements that do not match TEI element names to closest match (mw→fw, mcr→hi, regMe→reg)
3. output is in TEI (not WWP) namespace
4. validate against tei_all
### code
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:wwp="http://www.wwp.northeastern.edu/ns/textbase"
  xmlns="http://www.tei-c.org/ns/1.0"
  xpath-default-namespace="http://www.wwp.northeastern.edu/ns/textbase"
  exclude-result-prefixes="#all"
  version="3.0">

  <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
  <!-- [variables $distribution and $under_construction set here] -->
  <xsl:variable name="TB" select="( collection($distribution), collection($under_construction) )" as="document-node()+"/>
  
  <xsl:template match="/">
    <TEI>
      <teiHeader>
        <fileDesc>
          <titleStmt>
            <title>test of wwp:elision -> tei:ellipsis</title>
          </titleStmt>
          <publicationStmt>
            <p>not published</p>
          </publicationStmt>
          <sourceDesc>
            <p>generated from XSLT run over WWP textbase</p>
          </sourceDesc>
        </fileDesc>
      </teiHeader>
      <text>
        <body>
          <xsl:apply-templates select="$TB/wwp:TEI/wwp:text//wwp:*[ wwp:elision ]"/>
        </body>
      </text>
    </TEI>
  </xsl:template>

  <xsl:template match="@*">
    <xsl:copy/>
  </xsl:template>
  
  <xsl:template match="*">
    <xsl:variable name="svnid"
      select="ancestor::wwp:TEI/../comment()[contains(.,'$Id:')]"/>
    <div n="{$svnid}">
      <xsl:apply-templates select="." mode="convert"/>
    </div>
  </xsl:template>

  <xsl:template match="wwp:elision" mode="convert">
    <xsl:element name="ellipsis" namespace="http://www.tei-c.org/ns/1.0">
      <xsl:apply-templates select="@*"/>
      <metamark><xsl:apply-templates select="node()" mode="#current"/></metamark>
    </xsl:element>
  </xsl:template>

  <xsl:template match="*" mode="convert">
    <xsl:element name="{local-name(.)}" namespace="http://www.tei-c.org/ns/1.0">
      <xsl:apply-templates select="@*"/>
      <xsl:apply-templates select="node()" mode="#current"/>
    </xsl:element>
  </xsl:template>
  
  <xsl:template match="mw" mode="convert">
    <xsl:element name="fw" namespace="http://www.tei-c.org/ns/1.0">
      <xsl:apply-templates select="@*|node()" mode="#current"/>
    </xsl:element>
  </xsl:template>
  
  <xsl:template match="mcr" mode="convert">
    <xsl:element name="hi" namespace="http://www.tei-c.org/ns/1.0">
      <xsl:apply-templates select="@*|node()" mode="#current"/>
    </xsl:element>
  </xsl:template>
  
  <xsl:template match="regMe" mode="convert">
    <xsl:element name="reg" namespace="http://www.tei-c.org/ns/1.0">
      <xsl:apply-templates select="@*|node()" mode="#current"/>
    </xsl:element>
  </xsl:template>
  
</xsl:stylesheet>
~~~
