### ISSUE TITLE
Link to materials in ODD chaining broken

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#1882]
The reference to the little set of example files ("chainingTuto.zip") is broken:

https://github.com/TEIC/TEI/blob/7fbbc7c5c2ba533dc70f561b27101dbfa7f519a0/Documents/pureODD/howtoChain.xml#L281-L286

I think all that needs to be done is add the zip to the /TEIC/TEI/Documents/pureODD directory.

**Comment by lb42** [comment]
Apologies: I had uploaded the files, but not as a zip. Now fixed.
