### ISSUE TITLE
xenodata

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1884]
All of the examples we provide for `<xenoData>` at https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-xenoData.html are embedding XML versions of external data standards. It might be useful to create one which demonstrated using a different non-XML format. (That happened not to break any XML rules.)  e.g. maybe an extracted CSV list of EXIF data? Or something else?

**Comment by martindholmes** [comment]
GeoJSON would be a very plausible use-case.

**Comment by sydb** [comment]
As one who was against allowing `<xenoData>` to contain non-XML data, don’t expect me to jump on this bandwagon. :-)
