### ISSUE TITLE
Extend the content model of cit to include model.segLike

### ISSUE THREAD

**Issue by ttasovac** [TEIC/TEI#1891]
We have argued previously (#1702) that `<pc>` is needed in entry-like elements because various punctuation characters (colons, semicolons, commas, brackets etc.) are often used as structural dividers between various dictionary objects (lemmas and inflected forms, forms and etymologies etc.) The Council accepted our argumentation.

(By the way, I am definitely _not_ using the _pluralis maiestatis_ here but referring to a number of individuals affiliated with the TEI Lex-0 initiative. :)

The same line of thought should be applied to the content model of `<cit>`. For instance:

```xml
<sense n="1" xml:id="JDJ.RLS.obduco.1">
    <lbl>1)</lbl>
    <def xml:lang="sr">повести што на што или против чега</def>
    <pc>:</pc>
    <cit type="example">
        <quote>о. exercitum ad oppidum</quote>
    </cit>
    <pc>;</pc>
    <cit type="example">
        <quote>о. Curium</quote>
        <pc>,</pc><!--  currently not allowed-->
        <cit type="translation" xml:lang="sr">
            <quote>поставити Курија као такмаца другим кандидатима</quote>
        </cit>
    </cit>
    <pc>.</pc>
    <lbl>Отуда</lbl>
    <cit type="example">
        <quote>о. posterum diem</quote>
        <pc>,</pc><!--  currently not allowed-->
        <cit type="translation">
            <quote>додати и други дан</quote>
        </cit>
    </cit>
    <pc>.</pc>
</sense>
```

As you can see above, `<pc>` is used as a delimiter within `sense` (between `def` and `cit`; and between various instances of `<cit type="example">` and that's all kosher. 

But the same use of `<pc>` is not allowed within `<cit>` where specifically `<pc>,</pc>` is used to separate the `<quote>` and the translation. This comma is just a delimiter. It would be wrong to make the comma part of either the quote or the translation because it belongs to neither of them.

We've already implemented this in TEI Lex-0 by extending the content model of `<cit>` to include `model.segLike`: 

```xml
<content>
 <alternate minOccurs="1"
  maxOccurs="unbounded">
  <classRef key="model.qLike"/>
  <classRef key="model.egLike"/>
  <classRef key="model.biblLike"/>
  <classRef key="model.ptrLike"/>
  <classRef key="model.global"/>
  <classRef key="model.entryPart"/>
  <classRef key="model.segLike"/> <!--  new -->
 </alternate>
</content>
```
It would be great if TEI did the same. The proposed change would make the use of `<pc>` for this purpose more consistent across the full hierarchy of dictionary entries in TEI.

**Comment by laurentromary** [comment]
As part of the "we", I joint my support to this proposal.

**Comment by sydb** [comment]
Council VF2F subgroup thinks `<pc>` makes sense inside `<cit>` (for the reasons OP gives), but are very dubious about allowing `<seg>`, `<cl>`, `<w>`, etc., to appear directly inside `<cit>`.
Some of us also worry that the examples here (and some in the _Guidelines_) do not align with the definition of `<cit>`, in that there are no citations within, just the quotations.

**Comment by sydb** [comment]
Per Council meeting, green for `<pc>` (not for whole of model.segLike).
