### ISSUE TITLE
How to develop guidelines locally?

### ISSUE THREAD

**Issue by duncdrum** [TEIC/TEI#1898]
The information for how to build the Guidelines locally is somewhat hidden, and potentially out of date. I have been using [http://teic.github.io/TCW/testing_and_building.html](http://teic.github.io/TCW/testing_and_building.html) as in the past. This basically works (*yay* for docker) but i noticed  some caveats.

-   Despite the volume mapping working as expected my new elements specs are not part of the Guidelines. This strikes me as odd, and i could have sworn is not what used to happen. A new ref in `P5/spec/` should also have a matching tagdoc page in the Guidelines, if more then `make html-web` is necessary this needs to be documented
-   The generated files are not on gitignore instantly spamming the user with thousands of untracked items in their gitstatus. I d suggest adding all generated files to the P5 gitginore, i.e.:
```
Schema/*
DTD/*
Guidelines-web/*

P5subset*
*.stamp
anything

p5.isosch*
p5.xml
p5attlist.txt

p5odds-examples.rn*
p5odds.isosch*
p5odds.rn*
p5odds.mess*

p5examples*
Utilities/guidelines.xsl
stripspace*
```

PS: The reason i m after this is some display issues related to #1805 

see #1808

**Comment by hcayless** [comment]
Adding the .gitignore rules is a good idea, but I don't think there's anything in the Docker setup that would cause your local changes not to be picked up. It's really just using whatever Guidelines and Stylesheets folders you give it.

**Comment by duncdrum** [comment]
something i don't quite understand using the `teidev-docker` image. running `make test` from the correct location gets me this with the most recent commits from `dev`
```

Validate XML file using Schematron
java -Xmx752m -jar ../Utilities/lib/saxon9he.jar -ext:on detest.xml detest.xsl > detest3.log 2>&1
grep "\[xslt\]" detest1.log | sed 's/Processing.*detest.odd//' | sed 's/Loading.*message.isosch.xsl//' > detest.log
sed 's/.*detest.xml:/detest.xml:/' detest2.log >> detest.log
sed 's/.*detest.xml:/detest.xml:/' detest3.log >> detest.log
diff detest.log expected-results/detest.log
rm -f detest1.log detest2.log detest3.log
make[1]: Leaving directory '/tei/TEI/P5/Test'
```

To me this reads as if the detest test has failed. Yet, travis is green. 
On my failing branches i get the same output of `make test`, but travis is red reporting errors. What tests is travis executing that `make test` isn't? Should I just switch images?

**Comment by hcayless** [comment]
Can you point me at the branch that's failing? That output looks correct to me. Detest deliberately generates errors and then checks that they are the expected errors.

**Comment by duncdrum** [comment]
[unihan-phase-2](https://github.com/duncdrum/TEI/tree/unihan-phase-2) is failing but it already started earlier, locally `make test` doesn't complain however

**Comment by hcayless** [comment]
On my copy, `make test` succeeds, but Jenkins at least runs `make validate test`, and the validate target fails for me. I think Travis is similarly configured.

**Comment by duncdrum** [comment]
ah `validate` thank you now i can reproduce the travis errors.

**Comment by hcayless** [comment]
I've added a bunch of build artifact patterns to the .gitignore, and it sounds like your other issue is resolved, so I'm closing this.
