### ISSUE TITLE
Add model.biblLike to model.entryPart.top

### ISSUE THREAD

**Issue by ttasovac** [TEIC/TEI#1902]
In our ongoing work on TEI Lex-0, we've [discovered](https://github.com/DARIAH-ERIC/lexicalresources/issues/33#issuecomment-499646686) that `<bibl>` was not allowed as a child of `<entry>`. This was preventing us from encoding bibliographic references that are offered in some lexical resources (especially the historical, etymological and dialectological dictionaries). See below a screenshot from the [Dictionary of Old Dutch](http://gtb.ivdnt.org/iWDB/search?actie=article&wdb=ONW&id=ID2424&lemmodern=god&domein=0&conc=true).

We have implemented this change in TEI Lex-0 by adding `model.bibl` to `model.entryPart.top`, but we think this change would be useful for TEI in general. 

![afbeelding](https://user-images.githubusercontent.com/14764143/59062844-0ff2d800-88a7-11e9-933e-ca06365ea838.png)

**Comment by xlhrld** [comment]
Another example with `<bibl>` on entry scope is Lokotsch (1927):

> 247. **Ar. barḳūḳ:**
[Aus dem lat. _praecocium_ ‛das Frühreife’ über gr. πραικόκκιον, πραικόκια, πρεκόκκια, βέρικοκκα, s. Lammens Fārūḳ S. 364 Anm.; das ar. Wort hat übrigens die Bedeutung ‛Pflaume’ erhalten, während die Aprikose _mišmaš_ (s. hier Nr. 1471) heißt]; hieraus sp. _albaricoque, albercoque_, pg. _albricoque, alboquorque_, prov. _aubricot_, frz. _abricot_, it. _albicocco, albercocco_, siz. _varcoccu_; engl. _apricot_, ndl. _abrikoos_, dtsch. _Aprikose_, schwed. _aprikos_; russ. _abrikos_, čech. _aprikoza_. — Ferner infolge Betonung der ersten Silbe mit romanischem Suffix sp. _albérchigo_, it. _albergese_ ‛Art Pfirsich oder Aprikose’ [dagegen DEFREMERY in JAs (1869) I, 531, wohl ohne Grund]. [Dozy Oost 1—4. DE 67/68. Hobson-Jobson 33. Devic DEt 2/3. ML 6712. Kluge 20.

The last part `[Dozy Oost 1—4. DE 67/68. Hobson-Jobson 33. Devic DEt 2/3. ML 6712. Kluge 20.` is related to the whole entry which is denoted by the missing closing bracket. Inline references in this dictionary come with paired brackets.

**Comment by scstanley7** [comment]
This seems reasonable. One question before we implement: Do you want `<bibl>` added by itself? Or would you prefer having `model.biblPart` or `model.biblLike`? Each of these will have consequences (i.e. adding biblLike will allow elements like `<msDesc>` and `<biblStruct>` and `biblPart` will add `<citedRange>` and `<edition>` as direct children). Just let me know which option would be best for your use case.

**Comment by laurentromary** [comment]
that was obviously `model.biblLike`: we don't want to clutter dictionary entries with elementary objects, but do want to be able to put in all kinds of bibliographical descriptions.

**Comment by scstanley7** [comment]
Thank you for the clarification.
