### ISSUE TITLE
Datatype example doesn’t do what prose implies it does

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1907]
Section 2.5.3.1 “Datatypes”, `#TD-datatypes` asserts that the use of a child `<dataFacet>` is particularly useful inside a `<dataRef>` that uses a `@name` attribute when the restriction you would like to express “cannot be imposed with a regular expression pattern”.
The example that immediately follows is
~~~~~xml
<dataRef name="decimal">
 <dataFacet name="maxInclusive" value="360.0"/>
 <dataFacet name="minInclusive" value="-360.0"/>
</dataRef>
~~~~~
which restriction could perfectly well be imposed by a regular expression:
~~~~~xml
<dataRef name="decimal"
         restriction="^-?0*(([0-9][0-9]?|[012][0-9][0-9]|3[0-5][0-9])(\.[0-9]*)?|360(.0*)?)$">
~~~~~
(I’m not sure whether the anchors are necessary nor not, and whether one needs to account for leading and trailing whitespace or not, but you get the idea.)

So I think either

1. We need to come up with an example that really cannot be imposed with a regular expression, or
1. We should change the wording to something like “This is particularly useful for restrictions that are difficult to impose with a regular expression pattern.”

**Comment by hcayless** [comment]
Sub-subgroup agrees that "cannot be imposed with a regular expression pattern" is wrong. I suggest that the updated wording might also point out that using dataFacet may make for vastly more readable restrictions.

**Comment by ebeshero** [comment]
I've revised the phrasing as requested with https://github.com/TEIC/TEI/commit/7558ea860f572960000cb5725ac536ba5af68ec6
