### ISSUE TITLE
non-formulaic formula

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1909]
In the tagdoc for the lovely new `<unitDef>` element, the example of `@formula` on `<conversion>` is `"24"`. It should be `"$fromUnit div 24"`, no?

**Comment by sydb** [comment]
Fixed in 56a09ea, pending Mr. Jenkins’ approval.

**Comment by ebeshero** [comment]
@sydb Thanks for catching that! I thought I'd corrected all of those, but evidently not...
