### ISSUE TITLE
material element should be in att.typed

### ISSUE THREAD

**Issue by holfordm** [TEIC/TEI#1911]
The current definition of material is as follows:
```
`<material>` contains a word or phrase describing the material of which the object being described is composed.
```

This seems to assume that an object is only composed of one material, although the example given on the definition page belies this:
```<physDesc>
 <p>
  <material>Parchment</material> leaves with a
 <material>sharkskin</material> binding.</p>
</physDesc>
```

In this example, of course, it would be better to encode the support and binding separately. But in describing bindings similar problems arise, for example, Merton College MS. 23, 'whitawed skin over oak boards'. Currently the best way to mark this up is using `<material>` elements but the `@type` attribute is needed to distinguish the covering from the board.
```
<binding>
<p><material type="cover">whitawed skin</material> over <material type="board">oak</material> boards</p>
</binding>
```
I expect there are also other examples of objects composed of multiple materials which lack custom elements for their description and would rely on `material`.

**Comment by hcayless** [comment]
This seems like a useful distinction to be able to make. I'm uneasy about the semantics of this, though, in that `@type` wouldn't really be "characterizing the element" (v. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.typed.html) but rather the application of the material. "Cover" isn't a category of material, it's a use of the material...

I wonder whether a mechanism for describing object components in fine detail might not need to be developed, and might be a better solution for this problem. Is what you really want a way to (e.g.) break out the components of the binding and describe the in finer detail than you can now? @jamescummings might have opinions about this.

**Comment by lb42** [comment]
An exactly analogous situation we've seen before is the desire to subclass names by the type of person they refer to e.g. <persName type="butler">Jeeves</persName> : in that case the attribute @role provides a much better way of doing this.  Adding the element <material> to att.canonical would provide @role, and would also you to reference an existing thesaurus of material types or other existing controlled vocabularies via @ref or @key. 

On the question of a more detailed vocabulary for describing historical bindings, I assume you are familiar with the Ligatus project (ligatus.org.uk) which has developed an ontology for this very purpose. I did try to persuade them to do it in TEI way back when, but ...

**Comment by holfordm** [comment]
Thanks - I do share these reservations about `@type`, and had considered `@role`, but my understanding (wrong?) was that `@role` belongs to att.naming, defined as 'attributes common to elements which refer to named persons, places, organizations', which didn't seem right for `<material>`. Perhaps the assumption there that only named entities can have roles should be reexamined? 
Material is already in att.canonical, usefully in terms of pointing to things like Ligatus. The long-term aim is indeed to enable some sort of mapping between TEI and Ligatus for binding descriptions...

**Comment by lb42** [comment]
Apologies -- you are quite right: @role is supplied by att.naming, not att.canonical. So the question is: should the definition for att.naming be reviewed?  Its other members include quite a few items which are hard to consider as "named persons, places, organizations" (e.g. climate, trait, terrain...). I suggest "named entities, such as persons, places, organizations,  materials etc."

**Comment by jamescummings** [comment]
@lb42's comment https://github.com/TEIC/TEI/issues/1911#issuecomment-519975392 seems reasonable (though technically a completely different feature request) though I'm not sure materials are named entities. To quote from https://en.wikipedia.org/wiki/Named_entity (which for these purposes I guess is as good as any other), 

 >a named entity is a real-world object, such as persons, locations, organizations, products, etc., that can be denoted with a proper name. 

I don't think 'oak' is really a _name_ in the sense meant by 'named entity'.I do take his point that there are quite a few items for which we might want to reference external vocabularies as a way of standardising their classification. (Could one do this with `@ana`?) 

In reference the the original topic of this issue. Although @hcayless is uneasy about the use exemplified by @holfordm, our standard rules for consideration of having an element claim membership of att.typed is that it is repeatable (it is) and that it is conceivable to think of a useful way they might be classified (there is). It seems to me reasonable to categorise them, as Hugh suggests, by _type_ of _material_ , skin, stone, metal, plastic, glass, etc.  So if people think that would be useful then adding att.typed seems a no-brainer. 

In terms of categorising the role or function of the material it seems more analogous to something like `@function` on `<metamark>`. What is the function of the thing being described by the element. So `<material function="cover" type="plastic">plastic filofax cover</material>` seems clear and descriptive in the markup to me.  

Does that differentiation between function and type seem clear?  Would adding a function (or at a press 'role' but I think that is less clear) attribute to material solve the initial request?

**Comment by holfordm** [comment]
re using `@function` - yes, that would address the initial request.

**Comment by jamescummings** [comment]
I've been thinking about this, and while I certainly don't think 'oak' or 'plastic' or 'parchment' is a name, I am second guessing myself and thinking @lb42 might be right that `@role` makes more sense than `@function` regardless if it is also provided through att.naming or separately.

I still think that `<material>` should become a member of att.typed, but the question is does it need `@role` (or similar) as well and if implementing this should I create the attribute anew because this isn't really a name or just have it claim membership of att.naming?

**Comment by schassan** [comment]
If you were about to assign a new attribute to <material> why not use @usage for this? Isn't that what is meant: The parchment is used as cover?! (OK, could be @usedAs as well?!)

@usage is defined already in two very different contexts with different kinds of values right now. If you consider something like this for @role, I think @usage would be semantically clearer.

What would example values of materuial/@type be? Metal, wood, leather? Would such an attribute be useful for any kind of search, clustering, or the like?

**Comment by sydb** [comment]
Council agrees to adding `<material>` to att.typed, but also thinks the original request is really for a `@role` or `@function`. We are leaning towards adding `@function`, but need to do further work on how this `@function` will align with the uses of `@function` on `<metamark>` and att.segLike.

**Comment by sydb** [comment]
I have added `<material>` to att.typed (in c7dbad9), and removed “Go” label, as (IIRC) that was that part that we all agreed was good to go.
Leaving label “needs discussion” for discussion about the actual attribute that should be used for this purpose. I think @schassan is on the right track. That is, something like `@usage`, `@usedAs`, `@of`, `@ofThe` should be seriously considered along with `@role` and `@function`.

**Comment by sydb** [comment]
After discussions (in both May and Oct), Council decides on adding a free-standing `@function` to `<material>`.

**Comment by sydb** [comment]
@MegJBrown and I added `@function` to `<material>`, including a sample values include list, examples of other such lists in the `<remarks>`, and adding it to some of the examples of `<material>` in the _Guidelines_.

Pending approval of Messrs. Jenkins and Travis, this ticket can be closed.
