### ISSUE TITLE
Add modelGraphic.Like to the content model of <cit> (allow <media> in <cit>)

### ISSUE THREAD

**Issue by iljackb** [TEIC/TEI#1914]
It is increasingly common and desirable to have media content within digital dictionaries for user/learner-friendly applications that allows linking to and (with appropriate application) playing of spoken language content to instantiate/demonstrate some language form, phrase, etc. In TEI the `<media>` element is of course the element used to encode sound files, etc.

In general, dictionaries will want to place this content:
 (a) with the lemma or phonetic transcriptions (embedded in `<form>` which is already allowed); and
 (b) with usage examples (embedded in `<cit>` which is not allowed)

(_see the example in which the sound file icon is placed to right of the lemma information for a prototypical example of what is desired here_: [https://www.dictionary.com/browse/example?s=t](url))

In some cases, a work around for (b) would be to place the `<media>` following the `<cit>` in `<sense>`e.g.
```
           <sense>
              <cit type="example">
                 <quote xml:lang="mix">Ka'an yu tsa'a Pedro</quote>
              </cit>     
              <media url="soundfiles-gen:S_speak_1s_on_behalf_of_Pedro_01_02_03_TS.wav" mimeType="audio/wav"/>
           </sense>
```
_(note the `@url` value in these examples is using a <prefixDef> "soundfiles-gen:" declared in the header)_

However, this is not possible in the case of multilingual dictionaries in which examples have embedded translations of the given example phrases. Given the need to keep the `<media>` right next to the content language  it is an instantiation of (in this case where `@xml:lang="mix"`), it cannot simply be placed outside of `<cit>`, e.g. in this example the media file would appear after the Spanish translation:

```
               <cit type="example">
                  <quote xml:lang="mix">Ka'an yu tsa'a Pedro.</quote>
                  <cit type="translation">
                     <quote xml:lang="en">I'm speaking on behalf of Pedro.</quote>
                  </cit>
                  <cit type="translation">
                     <quote xml:lang="es">Estoy hablando de parte de Pedro.</quote>
                  </cit>
               </cit>
               <media url="soundfiles-gen:S_speak_1s_on_behalf_of_Pedro_01_02_03_TS.wav" mimeType="audio/wav"/>
```     
The only other option within `<cit>` is to use pointers (either `<ptr>` or `<ref>`) to point to a file with an `@xml:id` declared in the header or in the project, which isn't desirable for numerous practical reasons, most immediately of which is that a pointer is not the same thing as the media itself.

So what needs to be allowed is for `<media>` to occur as a child of `<cit>` allowing for the following structure, to do this my proposal is to add `<cit>` to **modelGraphic.Like**:

```
               <cit type="example">
                  <quote xml:lang="mix">Ka'an yu tsa'a Pedro.</quote>
                  <media url="soundfiles-gen:S_speak_1s_on_behalf_of_Pedro_01_02_03_TS.wav" mimeType="audio/wav"/>
                  <cit type="translation">
                     <quote xml:lang="en">I'm speaking on behalf of Pedro.</quote>
                  </cit>
                  <cit type="translation">
                     <quote xml:lang="es">Estoy hablando de parte de Pedro.</quote>
                  </cit>
               </cit>
```

**Comment by laurentromary** [comment]
Shall we implement this together with #1891 and #1902 ?

**Comment by iljackb** [comment]
Do you mean in Lex-0? or do you mean link the issues in Github?

Either way it's fine, I agree with the need of the other two issues from
Toma

**Comment by emylonas** [comment]
assigned @hcayless because of related #1891

**Comment by sydb** [comment]
Council VF2F subgroup thinks that the desired result (adding model.graphicLike to the content of `<cit>`) is fine.

**Comment by hcayless** [comment]
We will implement this by adding model.graphicLike with an example of its usage.
