### ISSUE TITLE
Guidelines "XML  syntax" button is broken

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1917]
On spec pages, there's a button that should switch from the Pure ODD to the RNG version of the content model. It's currently not working. It's dependent on JQuery, but it doesn't need to be; I suggest rewriting it in a clean and simple way so it has no dependencies and will work.

**Comment by rvdb** [comment]
@martindholmes Do you see Pure ODD at all? The button is working in my Firefox browser, but only switches between compact and XML RelaxNG syntax, no trace of Pure ODD...

**Comment by martindholmes** [comment]
@rvdb The content model above shows Pure ODD, doesn't it? But it only shows it for the content element, not for the attribute-related stuff.

**Comment by rvdb** [comment]
@martindholmes Ah, that's progress (for the button). Yet, I think the current display is a missed opportunity for being didactic about Pure ODD and customizing TEI. While all information is displayed in the other rows, I would rather like to see a unified "ODD declaration" row, that just gives the Pure ODD content of the definition element. At least, the real definition parts (`<classes>`, `<content>`, `<attList>`, maybe still others?), so it isn't cluttered with documentation elements and examples. 

In fact, a Pure ODD representation of what's now being shown in the "Schema Declaration" row. This would be much more informative than the current "Content" and "Schema Declaration" rows.

I don't know if this is being discussed anywhere already, or worth raising in a new isse?

**Comment by martindholmes** [comment]
@rvdb The problem would be deciding how much and what to include in that row. The simplest approach would just be to link to the spec file, but we don't include the spec files in the release. Perhaps we should?

**Comment by rvdb** [comment]
@martindholmes Both would just be perfect :-):
- providing at least access to the bare spec files would be essential, IMO. Right now, it requires deep digging to get to the actual source of the TEI specification. If that would be available from the HTML spec pages, it would help a lot for increasing the understanding of TEI internals.
- if the essential elements from the spec files could be identified (I'm suggesting this without any knowledge of how complex this really is), it would be even better if the HTML pages could provide a rendition of the Pure ODD essentials. If those could be enhanced with documentation cross-links (as is the case with the current RelaxNG rendition), that would lift navigation of the the shortwave of TEI to a whole new level!

**Comment by sydb** [comment]
Council VF2F subgroup thinks we can close this particular issue. That said, @martindholmes is probably right, we should not be using JQuery anymore. And someone (@martindholmes?) may well want to open another ticket suggesting that the “Content model” portion of the tagdoc page have information about attributes, too.
