### ISSUE TITLE
Investigate changing the class membership of <q>

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1918]
At Council F2F in Graz, we noted a large number of issues wanting `<q>` to be able to appear in more places. We want to investigate possibly changing class memberships but we need to investigate the consequences of this and what kinds of things could break if, for example, we moved `<q>` into `model.hiLike`.

**Comment by peterstadler** [comment]
A first list of issues related to the present one:

* `<q> should be allowed in <byline>` #1858 
* `<q> should be allowed in <span>` #1658 
* `<said>, <q>: att classes and behavior in context of Overlapping Hierarchies` #1691 
* `Make <q> a member of att.fragmentable` #1750 
* `rs should contain q and quote` #1531 
* `incipit should be able to contain quote (and/or q?) and probably also cit` #1755 
* `Allow q/quote/cit in u` #563 
* `Allow <foreign> to contain <q>` #443 
* `<lg> cannot contain <q>, <seg>, etc.` #571

**Comment by ebeshero** [comment]
Council agrees that @peterstadler and @sydb need to research the class membership issues here, if model.qlike makes sense.

**Comment by peterstadler** [comment]
@syd and I took a look at this issue today and did some experiments:

1. replace `<q>`'s class membership of `model.qLike` with `model.hiLike`:
Result: quite nice, i.e. it 'solves' most of the above issues but it introduces a regression in disallowing `<q>` from appearing in the model.inter contexts.

2. add class membership of `model.hiLike` to `<q>` (in addition to `model.qLike`)
Result: a lot of ambiguous content models since `macro.phraseSeq` features both `model.qLike` (directly) and `model.hiLike` (via `model.phrase`).

ToDos:
* if we remove `<q>` from `model.qLike` we would need to rename that class to avoid confusion 
* investigate whether it's better to 
** split `model.phraseSeq` into `model.phraseSeq` and `model.phraseSeqWithoutQ`, or
** remove `model.qLike` from `<q>` and manually add it to the additional contexts (e.g. `<cit>`, `<sp>`)

**Comment by peterstadler** [comment]
Next meeting, next (crazy) idea:
* remove `model.qLike` completely and move its members to `model.hiLike`. Except for `<floatingText>` which semantically never fitted there.

**Comment by sydb** [comment]
Possible names for model.qLike if `<q>` has been removed from it:
- model.attributed — because the text in these elements is attributed to someone (perhaps a character)
- model.nonNarratorial — because the text in these elements is asserted as being attributed to someone other than the narrator.

**Comment by ebeshero** [comment]
Thinking about the proposed renaming, I don’t like  the name model.nonNarratorial for this remodeled class because it takes an idea from a kind of storytelling (some narrative theory? whose?) and presupposes that texts, regardless of genre, have a single narrator. I don’t think narration by one or another speaking voice is an accurate description of the elements bundled in model.qLike. We’re talking about:

model.quoteLike [cit quote] floatingText said

`floatingText` isn’t necessarily associated with a change of narrator. Its definition is more general: “contains a single text of any kind, whether unitary or composite, which interrupts the text containing it at any point and after which the surrounding text resumes.”

`said` simply indicates a spoken expression—it isn’t just about a change to a different speaker from a narrator. 

`cit`, and `quote` apply to some agency outside the text—these are the ones about attribution, but the other elements are not necessarily attributing ideas to other people or documents.  More to my point, `cit` and `quote` don’t necessarily imply a move to another narrator.

So I don’t recommend we use `model.nonNarratorial` for the renamed class.

 I am not sure model.attributable is quite right either, though it might be a better name for model.quoteLike (the class of just `cit` and `quote`).

**Comment by ebeshero** [comment]
What about `model.attributable` instead of `model.attributed`? Maybe that is a little more flexible and inclusive—would it work for all the elements involved? A passage, thought, or spoken expression could be attributable to anyone, including the author or narrator of the current document. 

Hope this is helpful—and thanks for working on this @peterstadler and @sydb !

**Comment by peterstadler** [comment]
changed class membership of `<q>`   in #2008
