### ISSUE TITLE
category, taxonomy, and joinGrp should not have model.glossLike in their content models

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1919]
Elements category, taxonomy, and joinGrp have model.glossLike in their content model which gets them silly things like altIdent (rather than say altIdentifier). I think this is an accidental error confusing with wanting to provide the ability to gloss things in these elements with model.glossLike which is used in ODD writing. 

I think that taxonomy, category, and joinGrp should have model.descLike, gloss, and possibly equiv, but not altIdent. Optionally, one might want to consider providing altIdentifier on taxonomy and category to provide additional idno elements.

**Comment by sydb** [comment]
Council VF2F subgroup thinks that removing `<altIdent>` from the content of those three non-TD elements is probably a good idea. Not high priority, as it only affects those using the TD module. However, we are not sure that the model changes @jamescummings suggests is the right way to do this. (Nor that it is the wrong way.) For example, it might be better to make a new class for “things that can go at the start of TD specification elements”, and reserve use of model.glossLike for transcription elements.
Note also that there are some TD elements that probably should not have `<altIdent>`, either; `<modelGrp>`, e.g.

**Comment by martinascholger** [comment]
@sydb - can we close the issue?

**Comment by sydb** [comment]
Well, no one (including Mr. Jenkins) has complained, so I guess so.

**Comment by sydb** [comment]
What?
No, we can’t close this issue, the commit mentioned above (e13a62f) was made to special-purpose branch, not to dev.
I will issue a pull request as soon as I’ve merged current dev into it and tested it locally.

**Comment by sydb** [comment]
OK, passed my local tests and awaiting on Mr. Travis. Please see PR #2032, and close this once that has been approved and merged in.

**Comment by sydb** [comment]
Associated PR merged.
