### ISSUE TITLE
front.xml has bad language tags

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1926]
We follow BCP 47 in our use of IANA language subtags, but there are a few persistent errors in our source. Most of these are trivial to fix, but front.xml has a couple of instances of `xml:lang="gr"`, and I don't know whether they should be "el" (modern Greek) or "grc" (ancient Greek). Assigning this to folks who will know.

**Comment by martindholmes** [comment]
Another one occurs in respons.xml, where we have `xml:lang="heb"`; this could be "hbo" (ancient Hebrew) or "he" (Hebrew).

**Comment by hcayless** [comment]
That’s ancient, so ‘grc’. And I think one of the diacritics might be wrong—have to look at it not on a phone.

**Comment by martindholmes** [comment]
Thanks @hcayless. I've fixed that one in commit 15d1ef813. I think  I know who to ask about the Hebrew...

**Comment by emylonas** [comment]
I may be able to find out the Hebrew info tomorrow.

**Comment by emylonas** [comment]
My informant says about the Hebrew:
"the example is not particularly helpful in this respect, because that
particular expression would be the same in modern Hebrew as well --
although I doubt many would use it instead of "qaytz", "summer" (which is
that particular time of the year)."

**Comment by martindholmes** [comment]
I guess that means we want "hbo", then?

**Comment by hcayless** [comment]
Given that the Greek in the example is ancient, that seems a good bet.

**Comment by martindholmes** [comment]
Done, fixed, closing.
