### ISSUE TITLE
Feedback link broken

### ISSUE THREAD

**Issue by Arithmeticus** [TEIC/TEI#1936]
At the footer of tei-c.org pages is "feedback" hyperlinked to https://tei-c.org/About/contact.xml, which returns page not found.

**Comment by tuurma** [comment]
Thanks for the report, atm I cannot reproduce the issue, will keep it open for a day or two in case anyone else chimes in...

**Comment by emylonas** [comment]
It's broken on  https://www.tei-c.org/release/doc/tei-p5-doc/en/html/index.html , not on the rest of the site. Guidelines pages go back to an older link. The website has been updated. Haven't checked further. Also on other Guidelines pages, so could be problem in Guidelines generation code, not website. I haven't checked exhaustively.

**Comment by ebeshero** [comment]
So this case reminds us that the Guidelines build process is not checking the links in footers out to the main site.

**Comment by tuurma** [comment]
This is where the issue surfaces 
![image](https://user-images.githubusercontent.com/449468/66995680-b362bd80-f0cf-11e9-89a3-e7486cef6597.png)
