### ISSUE TITLE
Allow <bibl> in <label>

### ISSUE THREAD

**Issue by sarcanon** [TEIC/TEI#1943]
I have a use case that requires bibliographical references in `<label>`, but for some reason `<bibl>` is not allowed. Seems arbitrary given the number/types of other items allowed in `<label>`. Thank you.

**Comment by ebeshero** [comment]
@sarcanon `<label>` is permitted to contain `<cit>` for a cited quotation, and in that a `<bibl>` may go. Would that suit your use case?
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cit.html  
Of course your use case may not be a quotation with a source citation going inside a label. Can you share a little more about your use case? Thanks!

**Comment by ebeshero** [comment]
@sarcanon Also `<desc>` can go inside `<label>` and `<desc>` may contain `<bibl>`. That might be more broadly applicable to label-like matters. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-desc.html Would that work?

**Comment by sarcanon** [comment]
Thanks for your reply.

I have several lists of long bibliographical references, where I was
intending to have the reference in the <label> element and the citation in
the <item> element, which to me seemed to make perfectly good sense
semantically. But, for expediency's sake, I can make it a <list> of <cit>
elements in <item>s. So, thank you for that suggestion.

But I still don't understand why <bibl> is not permitted in <label>. And
why do I always feel like I'm fighting with the TEI schema? :-)

**Comment by lb42** [comment]
I am curious about why you would want to put a `<bibl>` (which contains a bibliographic description) inside a `<label>` (which contains a label for the corresponding item).  Could you maybe show an example? If the label actually is a bibliographic description, why tag it as a label? (Note that there is also a `<listBibl>` element for lists of citations, which might be yet another solution).

**Comment by hcayless** [comment]
@sarcanon, Council is reviewing issues as part of our (not) Face-to-face meeting. We'd really like to see the example you are (or were) looking at here. Could you post a picture or something? Thanks!

**Comment by peterstadler** [comment]
Council reviewed the issue again during its virtual F2F in October 2020 and decided to close it for the time being since no examples (or other input) have been provided. 
Please feel free to reopen anytime when you find the time to elaborate on this request.
