### ISSUE TITLE
Two more values for teidata.certainty

### ISSUE THREAD

**Issue by michalkozak** [TEIC/TEI#1947]
According to specification of [teidata.certainty](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.certainty.html), which is used among others in the `@cert` attribute of `<certainty>`, only 4 values are currently supported:
- high
- medium
- low
- unknown

In the PROVIDEDH project (http://providedh.eu) we would like to add the possibility of using additional 2 values:
- very low
- very high

Can we ask for these 2 values to be added to the specification or for the closed list to be changed to semi-open?

**Comment by lb42** [comment]
Nothing to stop you making such a change in your ODD, but it should be noted that the view of Council at the time was that providing more than these values would give a spurious air of precision to this attribute, which was intended only to provide a broad brush characterisation. It was suggested that more fine grained characterisations should be expressed using the &lt;certainty> and &lt;precision> elements.

**Comment by sydb** [comment]
Council VF2F subgroup thinks @lb42’s point seems on target, and thus suggests this ticket be closed unless OP (@michalkozak or other PROVIDEDHer) objects.

**Comment by michalkozak** [comment]
Yes, we've created our own ODD. Therefore, I close the issue.
