### ISSUE TITLE
Wrong article?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1951]
By my count there are 13 elements that start with the letter ‘f’ but are not pronouncable as words, namely `<f>`, `<fDecl>`, `<fDescr>`, `<fLib>`, `<fs>`, `<fsConstraints>`, `<fsdDecl>`, `<fsDecl>`, `<fsDescr>`, `<fsdLink>`, `<fvLib>`, and `<fw>`.

When being mentioned in prose encoded with `<gi>` and immediately preceded by an indefinite article, I count 17 that are preceded by “an” and 4 by “a”. (Using attached little XSLT pgm.)

I think all 4 “a” are in [FS](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/FS.html), and should be changed to “an”. The only reason I haven’t just fixed these as a bunch of typos already is in case someone wants to argue here that some of the others should be ‘a’, e.g. because “fsDecl” should be pronounced like “fis dek el” as opposed to “eff ess dek el”.

XSLT pgm (with “.txt” appended to name so GitHub will accept):
[what_indefinite_article_precedes_f_GIs.xslt](https://github.com/TEIC/TEI/files/3970430/what_indefinite_article_precedes_f_GIs.xslt.txt)
I ran it on the entirety of p5.xml; I suppose you could run it on the source files individually if you wanted.

**Comment by MegJBrown** [comment]
Fixed the 4 instances of a <gi>fs in FS-FeatureStructure to an <gi>fs

**Comment by lujessica** [comment]
@MegJBrown what was the need for reopening this ticket? do we need to revisit these following your update/fix on 22 July 2020?

**Comment by MegJBrown** [comment]
My update on 22 July didn't fix all the problematic articles. Syd created a check sheet, and I reopened the ticket to acknowledge that I had not whacked all the moles.

**Comment by lujessica** [comment]
> My update on 22 July didn't fix all the problematic articles. Syd created a check sheet, and I reopened the ticket to acknowledge that I had not whacked all the moles.

got it. might it be that @sydb's checklist ( #2015 ) was inspired by this ticket, but that this ticket is specific to these 4 instances that you took care of? maybe i'm reading SB's writing incorrectly on #2015 , but i don't think this issue is included there/is necessary to keeping the other ticket open and in progress.

**Comment by MegJBrown** [comment]
Ah, I had thought this ticket was a blanket _all_ problematic articles, we can close this if you think that's appropriate
