### ISSUE TITLE
Broken/misdirecting links

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1956]
Broken links on the page I get for  https://tei-c.org/guidelines/customization/  
- https://tei-c.org/tools/roma/
- https://tei-c.org/guidelines/customization/use_roma.xml
- link to TEI Simple is missing 
- something wrong in the formatting of the table following text "The following customizations use features which are not available in the DTD and XSD schema formats."
- http://wiki.tei-c.org/index.php/Category:Customization 

The page https://tei-c.org/guidelines/getting-involved/ which I clicked to for a link to submit this bug report, still says "The TEI conducts the active development of the TEI Guidelines at its SourceForge site, " with a link to the sf site.

**Comment by sydb** [comment]
Council VF2F subgroup notes that

1. 1–5 all seem to have been fixed
1. Except maybe the formatting of the table (4). Looks OK, if not pretty, to us.
1. The “get involved” page still refers to SourceForge, and should definitely be fixed.

We suggest this not only be set to GREEN for @martinascholger to fix the reference to SourceForge, but also be set to a medium priority.

**Comment by martinascholger** [comment]
Fixed the links on "customization" page and changed reference on "get involved" page to GitHub.
