### ISSUE TITLE
Modification to static files isn't applied to the ones other than the English ver.

### ISSUE THREAD

**Issue by muranamihdk** [TEIC/TEI#1960]
popupFootnotes.js was modified with 4c75657, but it has been only applied to the English version of the TEI Guidelines. It isn't applied to the Guidelines for seven other languages. Specifically, https://www.tei-c.org/release/doc/tei-p5-doc/[de|es|it|fr|ja|ko|zh-TW]/html/popupFootnotes.js are not modified yet. This causes not only JS error of footnotes but also disabling expansion icons in the table of contents in these languages (ref. #1941).

**Comment by peterstadler** [comment]
the fix in the repo will only be applied to the online version at https://www.tei-c.org/release during the next release. Someone altered the en/html/popupFootnotes.js file on the server manually and I now updated the respective files in the other directories.

**Comment by muranamihdk** [comment]
Thanks for your prompt attention!
