### ISSUE TITLE
Make Licensing explicit in repo

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#1962]
We have a licensing statement at https://tei-c.org/guidelines/licensing-and-citation/, but there isn't an explicit license at the root of the TEIC/TEI repo, and I think there should be one. There is a license in https://github.com/TEIC/TEI/tree/dev/P5/Legal, but the commit message makes me think it only applies to TEI Tite (which should be made explicit). Plus, it's a different license from the GLs, which is fine, I guess, but confusing as currently set out.

**Comment by ebeshero** [comment]
Council VF2F: We should add the license files to the top level of the GitHub repo. AND remove (or make more explicit) what the current license at  https://github.com/TEIC/TEI/tree/dev/P5/Legal is about.
