### ISSUE TITLE
WD should refer folks to the Script Encoding Initiative

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1963]
The prose in WD says

> If the character is determined to be missing from the Unicode Standard, it would be helpful to submit the new character for inclusion (see `<ptr target="http://unicode.org/pending/proposals.html"/>`).

We should refer folks to the [Script Encoding Initiative](http://linguistics.berkeley.edu/sei/) instead or in addition, I think.

**Comment by sydb** [comment]
Suggested wording (from Deb Anderson herself):

> For assistance on writing or submitting a proposal, potential proposers can contact the UC Berkeley Script Encoding Initiative for help (see `<ptr target="http://linguistics.berkeley.edu/sei/"/>`).

@raffazizzi: what about this needs discussion, do you think? (Seems pretty open-and-shut to me, but I may be biased or missing something.)

**Comment by lb42** [comment]
"for assistance" and "for help" seems a bit repetitious. I would suggest something such as:

"If the character is determined to be missing from the Unicode Standard, a formal proposal to include it can be submitted (see <ptr target="http://unicode.org/pending/proposals.html"/>). Agencies such as the UC Berkeley Script Encoding Initiative (http://linguistics.berkeley.edu/sei/) may be able to help in the preparation of such proposals. "

**Comment by sydb** [comment]
@lb42: I agree, the “for assistance … for help” is repetitious. That said, I prefer the tone of Deb’s wording: more, well, forceful. Since the Script Encoding Initiative exists for pretty much the sole purpose of helping folks get characters into Unicode, seems no need for the equivocating. So I’m inclined to go with

> For assistance on writing or submitting a proposal, potential proposers can contact the UC Berkeley Script Encoding Initiative (URL).

**Comment by sydb** [comment]
Council VF2F subgroup thinks this should be GREEN for @sydb to word as per Feb 06 comment.

**Comment by sydb** [comment]
Ignore 9d8c573, which was just a screw-up on my part. 02eb639 addresses this issue. Ticket should be closed if Mr. Jenkins is happy with it.
