### ISSUE TITLE
example will scare people

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1964]
As much as **I** really liked it, the `<egXML>` for the `@type` of `<desc>` should probably be changed _before_ the next release.

**Comment by lb42** [comment]
It should be burned with fire. I must have missed the memo about deprecating teiCorpus though I dont think I am alone in that. If ever there was a P6 change, this is it.

**Comment by sydb** [comment]
Well that’s part of the point. `<teiCorpus>` is **not** being deprecated. So to have an example that suggests it is …

**Comment by ebeshero** [comment]
@sydb What can we think of immediately that really is deprecated? (I have the file open right now and thought I might just do an edit...) The problem with an example with deprecation information in it is that it will always become dated if it's a real example from the TEI that gets really deprecated and goes away...

**Comment by ebeshero** [comment]
To be fair, you *do* have a validUntil date of 2027-10-20! That's a whole seven years away!

**Comment by laurentromary** [comment]
Than let's put 3030 as a year. That will be optimal :-)

**Comment by ebeshero** [comment]
@sydb Here's a relativelly recent deprecation notice (advising people to use `<empty>` in `<content>`.--Should we just use this? https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DEPRECATIONS.html

**Comment by sydb** [comment]
I don’t like that one, @ebeshero, because not everyone writes ODDs or can wrap their heads around the idea that the `<content>` element is declaring the allowable content of its the element being declared by its parent `<elementSpec>`.

So we should look back a bit further (which was trivial in Subversion and can’t be that difficult in Git), or perhaps just make up a fanciful one?

~~~~~xml
<desc type="deprecationInfo">The <gi>GB</gi> element will
  no longer be allowed inside the <gi>EU</gi> element
  as of <subst>
    <del><date when="2019-03-29">29 Mar 19</date></del>
    <add><date when="2020-01-31">31 Jan 20</date></add>
  </subst>. Instead use either the <gi>deal</gi> or <gi>noDeal</gi>
  element.</desc>
~~~~~

Hmmm … alright, looking back into the _Guidelines_ a bit further is probably a good idea.

**Comment by lb42** [comment]
The point about examples is that, as far as possible, they should either represent real existing data, or make clear that they do not. The problem with the current example is that it does not do either, and just extending the deprecation date while an amusing joke for the inner circle of cognoscenti will just confuse anyone else. Syd's jokey Brexit example would be OK (I have no objection to humour), but for me at least it is in really bad taste.  But surely to goodness it's not hard to find/invent a plausible and inoffensive one?

**Comment by lb42** [comment]
Current examples you could consider:
quotation/@form
shift/@new 
teiHeader/@type

**Comment by sydb** [comment]
The problem with `quotation/@form` and `teiHeader/@type` is they do not actually have a `<desc type="deprecationInfo">`. (That’s because those deprecations happened before we invented "deprecationInfo".) And I don’t see a current deprecation of `shift/@new`.

We could certainly use one of them as the basis for an example, but that runs the risk of running afoul of @lb42’s useful distinction that examples should be real or obviously not.

So either someone has to come up with a better fanciful example than my Brexit one (which I never intended be actually used, BTW), or someone should search through recent previous releases for examples of `desc[@type="deprecationInfo"]`. Any volunteers?

**Comment by sydb** [comment]
Well, not surprisingly (since `deprecationInfo` is so new) I only found two. The aforementioned `<empty/>` one and this:
~~~~~xml
    <desc type="deprecationInfo" versionDate="2018-09-14"
    xml:lang="en">Several standards bodies, including NIST in the USA,
    strongly recommend against ending the representation of a number
    with a decimal point. So instead of <q>3.</q> use either <q>3</q>
    or <q>3.0</q>.</desc>
~~~~~

**Comment by ebeshero** [comment]
@sydb That's an improvement--quite clear and neither divisive nor baffling! Maybe it will do for this example?

**Comment by sydb** [comment]
I don’t really like it much, but I like it a **lot** better than what we have now. :-) And you’re right, it’s clear and not scary. So unless someone comes up with something better soon, I think we go for it. Thanks @lb42 and @ebeshero !
@raffazizzi has not assigned this ticket to anyone yet, but if no one has done this by this Sat 01 Feb, I will assign it to myself and just do it.

**Comment by ebeshero** [comment]
@sydb It's easier than the ticket I'm staring at, so I might just do this one instead this evening. . .

**Comment by ebeshero** [comment]
I'm working on this one right now...

**Comment by ebeshero** [comment]
@sydb I've updated the example--if it looks okay, let's close this.
