### ISSUE TITLE
paragraph in TS just lies

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1965]
Per the anonymous Council reviewer of the `<standOff>` changes in TS:

> > (for example, the org attribute on the text element may take the value compos to specify that the components of the text are discrete) 

> Err, there is no `@org` attribute on `<text>`

Note that this statement has been around since at least P2.

The entire (current) paragraph is reproduced here just to make it easier to find and discuss: 
`````xml
<p>Defining the bounds of a spoken text is frequently a matter of
arbitrary convention or convenience.  In public or semi-public contexts,
a text may be regarded as synonymous with, for example, a <term rend="noindex">lecture</term>, a <term rend="noindex">broadcast item</term>,
a <term rend="noindex">meeting</term>, etc.  In informal or private
contexts, a text may be simply a conversation involving a specific group
of participants.  Alternatively, researchers may elect to define spoken
texts solely in terms of their duration in time or length in words.  By
default, these Guidelines assume of a text only that:
<list rend="bulleted">
<item>it is internally cohesive,</item>
<item>it is describable by a single header, and</item>
<item>it represents a single stretch of time with no significant
discontinuities.</item></list>
Deviation from these assumptions may be specified (for example, the
<att>org</att> attribute on the <gi>text</gi> element may take the value
<val>compos</val> to specify that the components of the
text are discrete) but is not recommended.
 </p>
`````

**Comment by lb42** [comment]
I would suggest simply deleting the sentence beginning "Deviation..."

**Comment by MegJBrown** [comment]
Deleting the sentence beginning 'Deviation' as Lou suggests makes sense to me. How much discussion is needed?

**Comment by sydb** [comment]
I think @lb42’s suggestion is just fine. Might prefer “Any deviation from these assumptions should be made explicit either in the encoding itself or in the TEI header.” or some such.

But, @MegJBrown, another year or two of discussion is probably in order. :-)

Seriously, with something small and straightforward like this, I would just post your plan here, and then give it a couple of days so anyone who disagrees has a good chance to object, and then (barring objection) just go do it.

P.S. I am not sure why this gets the “needs discussion” label.

**Comment by ebeshero** [comment]
Agreed, especially since there's actual misinformation to remove here. It would be a good ticket to resolve for the upcoming release.

**Comment by ebeshero** [comment]
If you don't get to it before the release, just remove the tidy milestone I just added...

**Comment by martinascholger** [comment]
see commit bdcc320
