### ISSUE TITLE
<linkGrp> needs <head> and <desc>

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1967]
The only components allowed in `<linkGrp>` right now are `<ptr>` and `<link>`, so there is no easy way to provide a heading or a description for a `<linkGrp>`, explaining what's being linked and why. You can do this of course by wrapping the `<linkGrp>` in a `<div>`, but with the new `<standOff>` element that's not possible, because `<div>` is not allowed in `<standoff>`. I think it makes sense to allow `<desc>` in `<linkGrp>`, and preferably `<head>` too.

Another option would be to insist that `<linkGrp>` be included in `<standOff>` as a child of `<list>`/`<item>`, allowing more content to be nested along with it inside the `<item>`, but given that `<linkGrp>` is allowed as a child of `<standOff>`, I think it would be better to allow descriptive info to go along with the links.

**Comment by sydb** [comment]
I am strongly in favor of allowing model.headLike and model.descLike as (initial) children of `<linkGrp>`, `<altGrp>`, `<joinGrp>`, `<spanGrp>`, and `<interpGrp>`. (And I think @martindholmes’s other work-arounds are hacks that should be avoided.)

**Comment by sydb** [comment]
Council VF2F subgroup thinks whole Council needs to discuss this. Should there really be prosey stuff like a heading in a `<linkGrp>`, or should a group of links that need a heading or prose description be wrapped in a `<div>` to provide that stuff?

**Comment by sydb** [comment]
Full Council VF2F thinks model.descLike as 1st optional (and repeatable) child of  `<linkGrp>`, `<altGrp>`, `<joinGrp>`, `<spanGrp>`, and `<interpGrp>` is a good idea, although we will need to change formal description of `<desc>` somewhat. (Already need to do that anyway.)
We do not think model.headLike is a good idea. (On the principle, essentially, that it is “too prosey”.)

**Comment by ebeshero** [comment]
See related ticket on `<desc>`: https://github.com/TEIC/TEI/issues/1994
