### ISSUE TITLE
dubious example for  <said>

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1968]
The second example for `<said>` looks like this
~~~~
<p> Tantripp had brought a card, and said that there was a gentleman waiting in the lobby.
 The courier had told him that <said direct="false">only Mrs. Casaubon was at home</said>,
 but he said <said direct="false">he was a relation of Mr. Casaubon's: would she see him?</said>
</p>
~~~~
Why is the clause "there was a gentleman waiting in the lobby" not marked as indirect speech?
How does it differ from "only Mrs. Casaubon was at home" in the next sentence?

**Comment by martindholmes** [comment]
I think that's a corrigible error. Two examples in the same short text is a really good thing, especially since one has "that" and one doesn't.

**Comment by martinascholger** [comment]
Any objections?

**Comment by sydb** [comment]
None here.

**Comment by martinascholger** [comment]
closing with af0a44e
