### ISSUE TITLE
interleave

### ISSUE THREAD

**Issue by axelberndt** [TEIC/TEI#1970]
Hi, I know this has been discussed several times and in several contexts but it seems like the core problem was never really tackled. How can I get the functionality of RNG's `<interleave>` in TEI ODD? My specific case is as follows. In the content definition of an element I have some `<elementRef>`s and/or `<classRef>`s. Each element is allowed at a certain cardinality and in any order.

I tried `<sequence preserverOrder="false" minOccurs="1" maxOccurs="1">` but it does not work.

Here are two examples that show how I do it istead:
```
<tei:content>
  <rng:interleave>
    <tei:classRef key="model.mapLike" expand="sequenceOptional" minOccurs="1" maxOccurs="1"/>
  </rng:interleave>
</tei:content>
```
```
<tei:content>
  <rng:interleave>
    <tei:elementRef key="global" minOccurs="1" maxOccurs="1"/>
    <tei:elementRef key="part" minOccurs="0" maxOccurs="unbounded"/>
  </rng:interleave>
</tei:content>
```
Both are invalid TEI-wise but the RNG works. The latter can also be written this way:
```
<tei:content>
  <rng:interleave>
    <rng:ref name="mpm.global"/>
    <rng:zeroOrMore>
      <relaxng:ref name="mpm.part"/>
    </relaxng:zeroOrMore>
  </rng:interleave>
</tei:content>
```
This is valid TEI but in the XHTML transformation/documentation the element is said to be empty which renders this solution impractical.

Is there a way to make the former solution valid?
Or, feature request: Could you either add `<interleave>` to TEI or implement @preserveOrder the way it is described in the guidelines?

**Comment by sydb** [comment]
This is Stylesheets issue [#241](https://github.com/TEIC/Stylesheets/issues/241).

You should post there saying “please make this a higher priority, I need it!”. (Or better yet, provide a fix! :-)

**Comment by axelberndt** [comment]
Well, issue #241 is only about @preserveOrder. What about `<interleave>`?
