### ISSUE TITLE
example has redundant equiv elements

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1971]
A couple of examples in USE have empty `<equiv/>` elements. I cannot for the life of me imagine what these are meant to mean, nor why they are present, since there is no discussion of them in the text. I deleted them from my local copy, but have not checked in the change yet since I assume there is a freeze going on.

**Comment by ebeshero** [comment]
Thanks @lb42 ! Indeed, there is a freeze just now, so thanks for waiting a bit.

**Comment by sydb** [comment]
There was a time, @lb42, when _every_ `<*Spec>` in the _Guidelines_ had an empty `<equiv>`, wasn’t there? I bet these examples are from that era.

You should feel free to check in your improvements (to dev), BTW.

**Comment by lb42** [comment]
Closing as the vacuous equivs have vanished like the morning dew
