### ISSUE TITLE
(request-slash-question) how can I accommodate groups of <seg> and <w>+<pc> under standOff?

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#1976]
(I promise to change the title and re-edit whatever I can -- or just kill this issue -- once it becomes clear whether this is a feature request or just a question that doesn't belong here)

I would like to try using &lt;standOff> for linguistic purposes. The core application of standoff annotation in corpus modelling is not to disrupt the original (base) text, but rather to build an annotation hierarchy parallel to and pointing into the base text. That hierarchy will typically begin with segmentation at the lowest level (tokenization), and then build on that, either with larger segmentations (possibly conflicting hence situated in parallel to each other and pointing at the tokenization level) or with annotation 'boxes' attached to the segments of various sizes (or with various types of relations among them). 

Some of us use the term "foundry" (it's not firmly established) for the purpose of referring to tight groupings of annotations, based on the same tokenization.
I would like to consider modelling a foundry as a single standOff element. For some corpora, we need several foundries for a single base text, because we use different tools to first tokenize the text (and each tool likes to do it in its own way, hence e.g. "don't", "do+n't", and also "don+'+t" are all possible tokenizations of _don't_), then to label/annotate the tokens and group or relate them in various ways. This means several standOff elements, and the current edition of the TEI can support that, which is great.

However, within a foundry, I need to separate groups of annotations. For my own minimalistic needs, I would be happy with just being able to have several groupings of &lt;seg> elements, but it already looks like &lt;seg> alone is not enough, since ISO MAF uses &lt;w> and &lt;pc> elements for many variants of tokenization. So I am looking for an element that is a child of &lt;standOff> and that has &lt;seg>, and preferably at least also &lt;w> and &lt;pc> as children. Does an element like that exist?
I recall that Laurent has suggested &lt;listAnnotation>, which was at least able to hold &lt;seg>s. But it appears (maybe I should remember why, but I don't) that that element was not acceptable. Should I be looking for an element that the Council would accept for such groupings, or is there such an element there already and I missed it, or... you tell me, please. Thanks in advance!

**Comment by sydb** [comment]
@bansp: can you post a short sample encoding of something you’d like to do, invalid though it may be?

**Comment by bansp** [comment]
Hi @sydb , sure, after I'm back from vacation. But I was kind of hoping to be explicit enough even without a literal example -- have I failed again? ;-/
Crucially, I realise that I can use one &lt;seg> to nest a sequence of &lt;seg>s, but, under the modelling requirements, I would consider that a kludge (the outer &lt;seg> need not be a segment, and no such modelling claim is made). I also realise that I cascade TEI/standOff only to make each standOff nest a sequence of &lt;seg>s (though not &lt;w>s), but I also consider that a kludge, because then the 'lower' standOffs do not encode separate standoff annotations but are used only because there is no suitable grouping element available, such as something like &lt;listAnnotation> (which in my head is rather annotationList or annotationSeq, but I understand there is a well-established naming tradition to follow). Cheers!

**Comment by laurentromary** [comment]
Looking back at the minutes from the decisional meeting we had in Graz: https://tei-c.org/activities/council/meetings/tei-technical-council-f2f-graz-2019-09-14-16/ the implementation, is not complete yet and there should be `<listAnnotation>` as decided there (plus `<annotation>` to be finalized, but one can be done without the other). I would suggest not to try to have yet another naming discussion and move ahead with `<listAnnotation>` for the next release. Meanwhile, I am customizing the thing locally.

**Comment by bansp** [comment]
Ah, I should have dug up those minutes and checked, thank you, @laurentromary !
I guess the best course of action would be to close this one and open another one for `<listAnnotation>` and friends, then. 
Closing. It's going to take a while before I open the other one, though.
