### ISSUE TITLE
content of `<transpose>` should be purer

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1979]
Strikes me that the content model of `<transpose>` should be
~~~~~xml
  <elementRef key="ptr" minOccurs="2" maxOccurs="unbounded"/>
~~~~~
rather than the current model, obviously a direct cognate to RELAX NG:
~~~~~xml
<sequence>
  <elementRef key="ptr"/>
  <elementRef key="ptr" minOccurs="1" maxOccurs="unbounded"/>
</sequence>
~~~~~
Planning to assign to Nicholas Cole as soon as we get his GitHub account straightened out.

**Comment by npcole** [comment]
Address with commit c2a526d02

**Comment by sydb** [comment]
Closing, as @npcole has successfully implemented this in the _Guidelines_. However, in so doing he found it is not processed correctly. Thus see [Stylesheets issue 425](https://github.com/TEIC/Stylesheets/issues/425).
