### ISSUE TITLE
Wrong org definition reference to the guidelines

### ISSUE THREAD

**Issue by TomazErjavec** [TEIC/TEI#1980]
In the element defintions text for org (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-org.html) the reference to the guidelines is to "[13.2.2 Organizational Names]". This is wrong, as there orgName is defined, not org. Rather, it should be to "[13.3.3 Organizational Data]" i.e. https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#ND-org.

**Comment by sydb** [comment]
Waiting for Mr. Jenkins to approve before closing.
