### ISSUE TITLE
Guidelines TOC page should use HTML5 summary/details elements instead of JS

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1984]
This arises out of issue #1941.

The way the little expando-icon things (the plus icons beside headings that expand to show sub-items) are handled in the Guidelines TOC page relies on JQuery. Need I say more.

HTML5 has a perfectly functional element-based solution to this that doesn't involve JavaScript at all, using the `<summary>` and `<details>` elements (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). They're nicely stylable, and they remove one of our dependencies on JS, as well as solving the silly problem that JS gives us, which is documented in issue #1941 .

So rather than "fixing" the JavaScript, I propose that we switch to a using the HTML5 elements instead.

**Comment by martindholmes** [comment]
Here's another good reason for getting rid of JQuery:

https://github.com/advisories/GHSA-gxr4-xjj5-5px2

**Comment by sydb** [comment]
And in case anyone needed more convincing, GitHub thinks TEI [is vulnerable](https://github.com/TEIC/TEI/network/alerts).

**Comment by hcayless** [comment]
So the vulnerabilities are taken care of, but this prompts a much larger question: When do we redo the design of the Guidelines, in which all sorts of little horrors lurk. I've tried to get this discussion going before, but Council had no enthusiasm for it :-).

**Comment by martindholmes** [comment]
@hcayless I think any redesign of the Guidelines will be able to take advantage of so many recent enhancements to CSS and HTML that things will become much simpler. We would start by getting rid of all JavaScript, and then only at the end adding back enhancements such as turning footnote links into popups; each of those little features can be added dynamically on load, and be in its own little modular library, so maintenance is much easier.

**Comment by hcayless** [comment]
I'm going to close this one and open a GLs redesign issue.
