### ISSUE TITLE
Need to get rid of urchin tracker in Guidelines site

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1985]
The Guidelines home page contains this:

`<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>`

which has been failing for ages because it's http instead of https, so any browser that is even bothering to try to load it (ad blockers block it anyway) will refuse:

~~~~~
index.html:1 Mixed Content: The page at 'https://www.tei-c.org/release/doc/tei-p5-doc/en/html/index.html' was loaded over HTTPS, but requested an insecure script 'http://www.google-analytics.com/urchin.js'. This request has been blocked; the content must be served over HTTPS.
~~~~~

Since it hasn't been working for ages, we obviously don't need it, so let's get rid of it.

**Comment by hcayless** [comment]
This seems actually to be a Stylesheets issue. I've dealt with it [there](https://github.com/TEIC/Stylesheets/commit/fec23117724718edf72bbc48ad44cd9d1b161dec).
