### ISSUE TITLE
add altIdentifier to att.datable

### ISSUE THREAD

**Issue by schassan** [TEIC/TEI#1986]
`<altIdentifier>` carries information about other identifications, especially valuable if these are former shelfmarks. Now, these former shelfmarks may have been in use for a certain, known time. Thus it would be good to have a possibility to store this information in TEI.

I would like to propose to add `<altIdentifier>` to att.datable.

`<idno>` as the most probable and common child of `<altIdentifier>` is already member of this attribute group but as `<altIdentifier>` groups together information beyond `<idno>` I think it is still necessary to be able to attach the dating information to this container element. `<altIdentifier>` works in that way as `<provenance>`, `<acquisition>`, or `<binding>` do.

**Comment by sydb** [comment]
Sounds quite reasonable to me. But would this mean that `<msIdentifier>` need also be a member of att.datable?

**Comment by jamescummings** [comment]
While it makes sense on altIdentifier to be able to say from - to or notBefore/After. What does that mean on a mandatory element like msIdentifier?

Not against it, just want to make sure we're clear on the semantics if extending this FR.

**Comment by schassan** [comment]
I wouldn't have asked for it as <msIdentifier> most of all carries the information about the status-quo. 

And, apart from that I consider two scenarios:
- The object has been in the same place from the beginning and not changed its name or way of identification. Then any information about dating would be the same as given in <origDate>.
- The object actually has changed its place, owner, identification. If you knew the date of the latest change (and that's what is represented in <msIdentifier>) e.g. the acquisition or the assingment of the current shelfmark you probably know something about the time before as well; which then could be expressed using the <altIdentifier>.

Thus I would be reluctant to make <msIdentifier> a member of att.datable. (Or even ask for it.)

**Comment by martindholmes** [comment]
@schassan @sydb Since time moves on, and whatever is msIdentifier at the time of creating the file will not eventually be the msIdentifier, I think it makes sense to allow for:

~~~~~
<msIdentifier notBefore="2019-01-05"...
~~~~~

**Comment by sydb** [comment]
Council thinks this is a GO for `<altIdentifier>`, but we will hold off on `<msIdentifier>` on the theory that if the main identifier of a manuscript changes from A to B, then the new `<msIdentifier>` is B, and A becomes an `<altIdentifier>`.
