### ISSUE TITLE
'May Contain' and 'Contained By' on html element reference pages should be sortable.

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#1990]
The content of the lists provided by 'May Contain' or 'Contained By' on the element reference pages should be sortable. Currently it is grouped by module (then alphabetically inside that). What I think would help user interaction with the element reference pages is that this should come up as it does now but have a button akin to the one in the Schema Declaration section which says 'XML syntax'. But instead this would say something like 'Sort alphabetically'. When clicked the content would not be grouped by module but all in one group but sorted alphabetically (perhaps with alphabetical dividers?).  The button would change to 'Sort by module' or similar. 

To do this the Guidelines XSL would need to duplicate the list but just sort it, and then provide the javascript hook to show/hide this in the html page creation.

**Comment by martindholmes** [comment]
JS could actually do the sorting -- might be simpler to add this as a little JS extension.

**Comment by jamescummings** [comment]
@martindholmes I realise that is possible. Since we're already passing through XSLT, it would seem better to me to keep the sorting there. i.e. at worst if everything breaks you just get two lists or something. (Well, maybe not, I assume CSS would still hide the 'other' one.) I know we already use bits of javascript here and there, I'm only suggesting keeping the heavy (well not too heavy) lifting of it in the main technology to avoid proliferation of things. 

But, an argument for doing it in JS would be for _any_ list of things we produce if we started producing them _all_ in the same way and then provided a set of standard ways to sort them.... if we were doing that then the XSLT change would be to make all list come out with the magic info needed in the same format, and then the JS extension would be a better way.  ;-) 

In the end, I don't really care but I had one of those brain melts where I was looking for an element in a 'May Contains' and didn't see it because I was stupidly looking in the wrong module. My suggestion is let's find a way to help people less familiar with the guidelines than me avoid the same situation. ;-)

**Comment by martindholmes** [comment]
There is always Control + f, though. Are you perhaps over-thinking this?

**Comment by jamescummings** [comment]
@martindholmes I could be... but control-f type the name of the element which may or may not be there, which I may or may not remember is camelCased.... vs click one button and look.

But well, it is just a suggestion.

**Comment by sydb** [comment]
My 2¢

It is a really good idea to have the list of elements sortable by module (as we have now), alphabetically, and by class. I can even imagine the alphabetical list having two forms, one with all those that start with A on line line, B on the next; and another that is a long list of one element per line that includes the element gloss & description (in the proper language). That said, given how many things are actually broken, and that CTL-F does work, it is hard for me to describe how low a priority this is.

**Comment by sydb** [comment]
This is now [Stylesheets#446](https://github.com/TEIC/Stylesheets/issues/446).
