### ISSUE TITLE
permit multiple seriesStmts in the TEI header

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1998]
Connected to #1870, Council recognizes that it would be helpful to permit multiple `<seriesStmt>`s in the TEI header, for cases where an item belongs to multiple series. We invite discussion here in case people have use cases, examples, or concerns.

**Comment by martindholmes** [comment]
In our LEMDO project, we are planning for a situation in which the same edited play is published in multiple anthologies managed by different teams -- one default LEMDO anthology and at least one other specialist anthology, such as a Shakespeare-focused collection -- and also as a print publication. It would be really useful to have multiple `<seriesStmt>` elements for this.

**Comment by sydb** [comment]
Main concern is whether or not `<seriesStmt>` should become a member of att.declarable, too, then. (In the use case we have imagined — this TEI document is a member of multiple different series — it is not necessary or even helpful to have `@default`. But many (if not most) other repeatable elements in the header are members of att.declarable so that different bits of the TEI document or corpus can say “that is the part of the header that applies to me”. So I am wondering if we allow multiple `<seriesStmt>s`, won’t people expect it to be usable the same way? … I can already hear @hcayless saying “maybe, but no one has asked for it”. : - )

**Comment by ebeshero** [comment]
I think I can implement this one for our next release. A question for @martinascholger and @sydb : `<seriesStmt>` (zero or one) is permitted in `<biblFull>` and `<fileDesc>`. I think this ticket is *only* to address the `<seriesStmt>` contained by `<fileDesc>` , correct?

**Comment by ebeshero** [comment]
Or, shall we permit multiple `<seriesStmt>` elements in `<biblFull>` as well?

**Comment by martindholmes** [comment]
I think biblFull should mirror teiHeader, shouldn't it?

**Comment by ebeshero** [comment]
@martindholmes Yes, I tend to agree, especially since the examples we've been discussing might easily be encoded as biblFull in the teiHeader. I'm also thinking @sydb 's idea above to give seriesStmt membership in [att.declarable](https://tei-c.org/release/doc/tei-p5-doc/en/html//ref-att.declarable.html) might make sense while I'm addressing the ticket. Reading about declarable and declaring attributes at https://tei-c.org/release/doc/tei-p5-doc/en/html//CC.html#CCAS2 , `seriesStmt` seems to fit with the group of elements discussed there. If for example a `<div>` in the text is associated with one particular series publication rather than another (for example an editorial forward), I think we'd want the capacity to indicate which seriesStmt was associated with it. I have a use-case for this in some of the plays we're editing for the Digital Mitford project, where the author's preface only appears in some editions and not in others. It would be handy for us to have multiple seriesStmts, as well as capacity to reference them. So I guess, @sydb , I'll be the one requesting this feature! :-)

 Now, as for implementing it, I'll work on it in a PR and see if it is manageable for this release.  If I can't do this first piece by this weekend, I'll remove the release milestone from this ticket. I don't have the bandwidth right now to finish up #1870, but finishing this ticket will help toward that one.

**Comment by martindholmes** [comment]
Agreed on att.declarable.

**Comment by ebeshero** [comment]
I think I've resolved this ticket: Take a look at my Pull Request and let me know if you see anything amiss.

**Comment by martinascholger** [comment]
Implemented by @ebeshero , I'm closing this.
