### ISSUE TITLE
why is <graphic> not a member of att.typed?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1999]
The example we have of `<graphic>` in the tagdoc is a bit, well, lame:
```xml
 <surfaceGrp n="leaf1">
  <surface>
   <graphic url="page1.png"/>
  </surface>
  <surface>
   <graphic url="page2-highRes.png"/>
   <graphic url="page2-lowRes.png"/>
  </surface>
 </surfaceGrp>
```
Seems to me one might want to differentiate high from low resolution images **without** examining the URL, as it may not contain that information, or not in an easily parsable way. (Heck, that’s what **I** want to do, which is what led me to discover there is no `@type` on `<graphic>`.) The `<graphic>` element certainly meets @jamescummings’s criteria: it is repeatable and categorizable.

If it were a member of att.typed, a contrived example might be:
```xml
<facsimile>
  <surfaceGrp n="leaf 1" xml:id="spi001">
    <surface xml:id="spi001r">
      <graphic type="normal" subtype="thumbnail" url="./rscrs/kfo49740720.jpg"/>
      <graphic type="normal" subtype="low-res" url="./rscrs/kfo49740352.jpg"/>
      <graphic type="normal" subtype="high-res" url="./rscrs/kfo49739952.jpg"/>
      <graphic type="high-contrast" subtype="low-res" url="./rscrs/kfo49739616.jpg"/>
      <graphic type="high-contrast" subtype="high-res" url="./rscrs/kfo49739488.jpg"/>
    </surface>
    <surface xml:id="spi001v">
      <graphic type="normal" subtype="thumbnail" url="./rscrs/kfo49739360.jpg"/>
      <graphic type="normal" subtype="low-res" url="./rscrs/kfo49739232.jpg"/>
      <graphic type="normal" subtype="high-res" url="./rscrs/kfo49739056.jpg"/>
      <graphic type="high-contrast" subtype="low-res" url="./rscrs/kfo49738800.jpg"/>
      <graphic type="high-contrast" subtype="high-res" url="./rscrs/kfo49738640.jpg"/>
      <zone xml:id="spi001v_detail01">
	<graphic type="normal" subtype="thumbnail" url="./rscrs/kfo46397008.jpg"/>
	<graphic type="normal" subtype="low-res" url="./rscrs/kfo46396832.jpg"/>
	<graphic type="normal" subtype="high-res" url="./rscrs/kfo46396304.jpg"/>
	<graphic type="high-contrast" subtype="low-res" url="./rscrs/kfo46396176.jpg"/>
	<graphic type="high-contrast" subtype="high-res" url="./rscrs/kfo46396048.jpg"/>
      </zone>
    </surface>
  </surfaceGrp>
</facsimile>
```

**Comment by martinascholger** [comment]
Interestingly, I asked myself exactly the same question when I was looking at a project today. So I'm in favour of making `<graphic>` a member of att.typed.

**Comment by ebeshero** [comment]
I'd agree, too. Of course IIIF URLs do make it clear with values like pct:10 or pct:50 in the URL how to render an image at a given resolution. But not everyone immediately understands this from the URL, and not every image call will be expressed in IIIF, so I think it's smart to allow for att.typed to help supply more information about resolution or anything else important for a project (whether it's about resolution or something else).

**Comment by martinascholger** [comment]
VF2F agrees to greenlight and improve the example.

**Comment by ebeshero** [comment]
Closing with merge of #2256

**Comment by Martin-de-la-Iglesia** [comment]
When I click on "bibliography", I get "Undetermined":

![tei](https://user-images.githubusercontent.com/5310837/164176301-d97b4437-b7df-4b35-8481-af5c0a829a30.png)

(This occurs also on the previous example, `<facsimile> <surfaceGrp n="leaf1">` etc.)
