### ISSUE TITLE
Prosopography module

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#2]
At present, the elements you need to record information 
about real people in a P5 document are scattered across 
several modules.

The Corpora module defines &lt;partic&gt; and &lt;particDesc&gt; 
for participants in a transcribed text. These allow for 
any number of so-called "demographic" subelements, 
such as &lt;birth&gt;, &lt;occupation&gt;, &lt;residence&gt; etc.

The Names and Dates module defines &lt;persName&gt; and 
various subcomponents for names of people, but 
resolutely eschews any attempt to describe reality: it's 
onomastic, rather than prosopographic, by design.

The new Manuscript Description module defines a 
&lt;listPerson&gt; elementand a &lt;person&gt; element to fill it. 
This  contains some of the same elements as &lt;partic&gt; 
but also adds some. For example, &lt;birth&gt; is in the 
corpora module, but &lt;death&gt; is in the MS one. (Not 
really surprising, since the people manuscript describers 
are interested in are usually dead, whereas the people 
corpus encoders are concerned with usually aren't)

We could resolve this confusion  by creating a new 
standalone module, or by groiuping all related elements 
in one place. More precisely:

(a) we could define an entirely new module concerned 
with prosopographic information, defining &lt;listPerson&gt; 
and &lt;person&gt; and their children, and remove &lt;partic&gt; 
and &lt;particDesc&gt; from the corpora module

(b) we could do essentially  the same but add the new 
elements to the core module

(c) we could do essentially the same, but add the new 
elements to the names and dates module

The reactions to this proposal on TEI-L (9-10 may 04) 
so far suggest that option (c) is preferred.

Original comment by: @lb42

**Comment by linuxlovell** [comment]
thanks www.movied.org
