### ISSUE TITLE
FR: <surfaceGrp> should contain model.graphicLike

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#2003]
For a project, we want to be able to describe sections of a large PDF document (but not individual pages); however, since `<surfaceGrp>` does not have `model.graphicLike` in its content model, we cannot truthfully point to that representation—we can only point to individual pages as individual files using individual `<surface>` elements.

Adding `model.graphicLike` to `<surfaceGrp>` seems like a broadly useful thing to me: there are many instances where a digital edition may want to point to a single PDF of a chapter of a facsimile as well as, or instead of, a single image of a single page. I also note that it is the only element in the sequence `facsimile`, `surfaceGrp`, `surface`, `zone` that does not have model.graphicLike in its content model.

**Comment by ebeshero** [comment]
Council VF2F: We discussed this, and noted that `<facsimile>` was designed exactly for this use to present a large document in graphical terms, and it contains `model.graphicLike`. The `<facsimile>` element can hold a set of images to describe multi-surface portions of a document graphically. We don’t want to introduce confusion with apparently permitting graphical representation of page surfaces in `<surfaceGrp>` that should be handled in `<surface>` elements, so we think it is better to keep graphical info about larger groupings in the `<facsimile>` element.

**Comment by ebeshero** [comment]
(Updated my last post to add more explantation from Council discussion.)
