### ISSUE TITLE
Proposal: new element <persPronouns>

### ISSUE THREAD

**Issue by amclark42** [TEIC/TEI#2010]
I propose a new element to contain personal pronouns. In my own ODD customization, I've called this element `<persPronouns>`, and closely modeled it after `<sex>`.

## Why do this?

In email signatures and biographies, people will often include their preferred personal pronouns along with their name or handle. For example: `J. Doe (she/they)`. This pattern is a means for transgender and gender variant people to express how they wish to be identified, without having to share their gender identity (though some do). Cisgender people have also adopted the practice, which normalizes the idea that a person's personal pronouns should not be inferred by their name, sex, gender, or gender presentation. While a recent phenomenon, the statement of one's personal pronouns fits well alongside other phenomena identified in the TEI Guidelines.

So `<persPronouns>` has a place in the record of a document, but it also has a place in supplementary lists of persons, such as characters, authors, encoders and transcribers. In the spirit of separating gender from pronouns, using `<sex>` or `@sex` alone can be insufficient or presumptive.

Consider an anthology of fictional stories celebrating queer identities. You wish to create a list of contributors to the volume, so you flip to the short biographies in the back. Some of these biographies include gender identity or sexual orientation. For example:

* "J. Doe is a trans woman and activist."
* "J. Doe is a loud and proud arospec lesbian."
* "J. Doe currently identifies as gender questioning."

Initially, my customization used "persPronouns" as an attribute on `<sex>` rather than as a separate element. However, some biographies don't put a label on the contributor's identity, but _do_ use a third-person pronoun. For example:

* "E lives with eir pet dog, Spot."
* "Her work has been praised by..."
* "Contact them at..."
* "J. Doe (she/they) wants to thank..."

If you can presume that the biographies have been provided by the contributors themselves, then you have their preferred personal pronouns but _not_ their gender identity. On `<sex>`, `@evidence` helps establish a degree of certainty about the subject's gender. For the case where a person's personal pronouns are confirmed but gender identity is not, `@evidence` is _also_ needed for "persPronouns"—and so it is desirable to capture that data in a separate element. For example:

    <sex value="female" evidence="conjecture"/>
    <persPronouns value="she/her/hers" evidence="self-identification"/>

Using "persPronouns" as an element has additional benefits. As previously stated, an element can be used to encode the pattern of listing one's personal pronouns in signatures and personal biographies. My favorite part, though, is the fact that `<persPronouns>` can be used with a machine-readable `@value` _and_ a human-readable text node. One can have the ability to pull statistics, but also the ability to describe the subject's lived reality. It is, to my delight, a queer solution.

    <persPronouns value="she/her/hers" evidence="self-identification">Prefers she/her/hers. Comfortable with 
      they/them/theirs.</persPronouns>

## Notes on implementation

I suggest that the TEI recommend the use of `@evidence`, which makes it easier to determine when personal pronouns are confirmed by the subject. For my own implementation, I used a semi-open list, with "conjecture" and "self-identification". @sydb suggested an additional value of "trusted third party", for cases like SUE's below. (I haven't actually gotten around to adding this value to my ODD.)

I also suggest a semi-open list for the contents of `@value`, including, at the very least, "he/him/his", "she/her/hers", and "they/them/theirs". `@value` should be able to accommodate more than one set of pronouns.

Here are some examples of biographical usage:

    <person>
      <persName>
        <forename>Miss Major</forename>
        <surname>Griffin-Gracy</surname>
      </persName>
      <birth when="1940-10-25"/>
      <sex value="trans female" evidence="self-identification">trans woman</sex>
      <persPronouns value="she/her/hers" evidence="self-identification"/>
      <note>
        <p>Veteran of the Stonewall Riots. Founder of the Griffin-Gracy Educational Retreat and 
          Historical Center (the House of GG). Activist and advocate for transgender and 
          gender-nonconforming people of color.</p>
      </note>
    </person>

    <person>
      <persName>The Public Universal Friend</persName>
      <birth when="1752-11-29">
        <placeName>Cumberland, Rhode Island</placeName>
      </birth>
      <death when="1819-07-01">
        <placeName>Jerusalem, New York</placeName>
      </death>
      <faith>Universal Friends</faith>
      <sex from="1776-10" evidence="self-identification">genderless</sex>
      <persPronouns  from="1776-10" evidence="self-identification">No gendered pronouns (use “the Friend” 
         or “P.U.F.”)</persPronouns>
    </person>

    <person>
      <persName>
        <forename>SUE</forename>
        <addName>the T. rex</addName>
      </persName>
      <residence>The Field Museum. Chicago, Illinois, United States.</residence>
      <sex value="0"/>
      <persPronouns value="they/them/theirs">they/them</persPronouns>
      <note>
        <cit>
          <quote>Specimen FMNH PR 2081. Legendary Fossil. Apex Predator. National Treasure. 
            <emph style="text-transform:uppercase; letter-spacing:0.25rem;">Murderbird.</emph></quote>
          <bibl>SUEtheTrex, Twitter biography. <ptr target="https://twitter.com/SUEtheTrex"/>. 
            Accessed <date when="2020-03-25">March 25th, 2020</date>.</bibl>
        </cit>
      </note>
    </person>

My own usage (again, biography-oriented) can be seen in [a list of authors I've read](https://github.com/amclark42/a-life-in-lists/blob/master/authors_3.0.xml). (The changelog serves as a narrative of my own thinking on gender and personal pronouns.)

I include an excerpt from my ODD below, in case it helps with implementation. Shoutout to @sydb, who helped immensely by hammering out rough edges. The full ODD can be found on [GitHub](https://github.com/amclark42/perspectography/blob/master/schema/perspectography.odd).

    <elementSpec ident="persPronouns" mode="add">
      <desc>lists personal pronouns.</desc>
      <classes>
        <memberOf key="att.global"/>
        <memberOf key="att.editLike"/>
        <memberOf key="att.datable"/>
        <memberOf key="att.typed"/>
        <memberOf key="model.persStateLike"/>
      </classes>
      <content>
        <macroRef key="macro.phraseSeq"/>
      </content>
      <attList>
        <attDef ident="instant" mode="delete"/>
        <attDef ident="evidence" mode="replace" usage="rec">
          <desc>indicates support for the listed personal pronouns. The default value 
            is "conjecture."</desc>
          <datatype>
            <dataRef key="teidata.enumerated"/>
          </datatype>
          <defaultVal>conjecture</defaultVal>
          <valList type="semi">
            <valItem ident="conjecture">
              <desc>The given value was likely selected due to assumptions by someone 
                besides the person in question. As a result, the value may be 
                erroneous and presumptive.</desc>
            </valItem>
            <valItem ident="self-identification">
              <desc>The given value has been explicitly stated or confirmed by the 
                person to whom this classification applies.</desc>
            </valItem>
          </valList>
        </attDef>
        <attDef ident="value" usage="rec">
          <desc>supplies a regularized value for personal pronouns.</desc>
          <datatype minOccurs="1" maxOccurs="unbounded">
            <dataRef key="teidata.enumerated"/>
          </datatype>
          <valList type="semi">
            <valItem ident="e/em/eirs"/>
            <valItem ident="he/him/his"/>
            <valItem ident="she/her/hers"/>
            <valItem ident="they/them/theirs"/>
          </valList>
        </attDef>
      </attList>
    </elementSpec>

**Comment by martindholmes** [comment]
Since pronouns are language-specific, I don't know whether we should provide suggested values in English; I think it would make more sense to provide examples of implementations for English and non-English projects/person elements.

**Comment by amclark42** [comment]
@martindholmes That makes sense to me!

**Comment by ebeshero** [comment]
I like the idea of this for personography listings, and I like your concept for the `@evidence` attribute on the `<sex>` and `<persPronouns>` . But I would caution against using spaces in suggested singular values, as in `evidence="trusted third party"` because we’re used to spaces signaling a sequence of values, and we need a way to indicate multiple sources of evidence, just as we need multiple pronouns.

On similar grounds, for the sequence of pronouns in the `@value` attribute, I’d recommend separating them with a space rather than a forward slash.

**Comment by amclark42** [comment]
@ebeshero Good point! I just pulled up the conversation, and @sydb did indeed suggest "trusted-third-party", rather than a version with spaces.

Since there's no need to implement a semi-open list of space-separated tokens, `@value`'s contents can be implemented on the project level, depending on how the attribute will be processed.

Possibilities:

- `value="she her hers"`
- `value="she they"`
- `value="she-hers they-theirs"`
- `value="she/her/hers they/them/theirs"`

I chose the version with slashes because it lets me get at cases where a person is equally fine with two or more variants.

**Comment by ebeshero** [comment]
@amclark42 The hyphenated value certainly helps for `@evidence`, yes. 

As for the `@value` for the pronouns, I wonder if its necessary to include all the cases of the pronoun? I know that's what people do in their email signatures and conference badges, but I wonder if simply the nominative case of the pronoun might be sufficient? 

This way you could have:

`value="she they"`

We could go further and point to standard pronoun cases in a given language...

**Comment by jamescummings** [comment]
One of the questions that will be asked is why should this not just be done with the existing elements like trait or state? (I'm not arguing against this element but use trait/state is what we've said for other proposals for new elements inside person/place.) If we can flesh out its justification in advance it will certainly not hurt.

**Comment by amclark42** [comment]
@ebeshero Yes, you're absolutely right. The nominative case alone would work well, and presents fewer challenges for suggested values in translation.

@jamescummings This is an interesting question. Personal pronouns are not a trait, as they can change over time. `<state>` is potentially appropriate, as it is datable, allowed in both `<person>` and `<signed>`, and it has `@evidence`. It appears that `<state>` is missing `@value`, however, which makes it harder to perform computational analysis. `@key` is a possible stand-in, but it doesn't require space-separated tokens.

`<state>` also puts a heavier burden of implementation on individual projects. A well-documented element would go a long way toward uptake.

From a non-technical standpoint, I see this element as an important counterpoint to `<sex>`. First, personal pronouns should not be assumed from sex or gender identity. Second, where `<sex>` cannot or will not be determined, personal pronouns may be helpful for both representation and computational analysis.

I'm currently rethinking my comfort level with recording gender identity at all. The kinds of analysis I want to do can be done just as easily with tokens representing personal pronouns, and it doesn't put me in the position of maintaining that kind of data on living people. This is the kind of use case that I expect would be an outlier in the broader TEI community, but it is a case that can be easily supported by using `<persPronouns>` without `<sex>`.

**Comment by martinascholger** [comment]
Council at VF2F agrees that this is a great proposal. We think that an open list of space separated values (for the `@value` attribute) is probably the right solution. @sydb and @MegJBrown will work on the issue and discuss certain parts with Council as required.

**Comment by MegJBrown** [comment]
Questions for council:

1. Can we cite a ticket in the bibliography (_this ticket_, specifically)?
2. Does anyone know of a good source for transcribed examples that might feature indicated personal pronouns?
3. Does anyone want to check my elementary French?

**Comment by sydb** [comment]
@martindholmes points out with respect to question (1), above, that GitHub might be a pretty ephemeral resource.

But this does raise the big issue of how many layers through the onion should `egXML/@source` point? We took the SUEtheTrex example from the OP’s post on the ticket. She made it up (by transcribing the Twitter source she points to) for that ticket. Part of me says we should just use `#NONE`, for although the example was not made up _for the Guidelines_, it was made up _for the TEI_, and that’s close enough.

**Comment by ebeshero** [comment]
@sydb Wait a minute. Why wouldn’t we want to cite this fictive dinosaur entity’s real social media existence, since it gave rise to the example? Does a text need to be transcribed in order to be cited? In this case, the Twitter source gave rise to metadata encoding, and I’d argue that gives the Twitter bio the legitimacy of a source. 

Would this be a first for the TEI Bib to cite a social media feed? (There are guidelines for citing Twitter feeds that we could readily adapt for the bibliography purposes of the Guidelines. See for example https://blog.apastyle.org/apastyle/twitter/ ). 

I am reminded of discussions not so long ago of personography lists of fictional or made up identities. Maybe we could return to SUEtheTrex again, or maybe Twitter will serve as a basis for more examples than this one.

**Comment by sydb** [comment]
@ebeshero :
I _think_ you are asking why not cite the bio itself. I am certainly not objecting to that. I am only wondering aloud if that is appropriate given that the more proximate thingy cited was @amclark42’s encoding thereof.

**Comment by sydb** [comment]
(And realizing that the coward’s way out is to cite neither. Which, because the encoding was made up for being an example on this ticket, isn’t _wrong_.)

**Comment by ebeshero** [comment]
@sydb Yes, that is what I suggest, to cite the bio that gave rise to the example.

**Comment by amclark42** [comment]
@sydb I confess that I saw that commit go through when it happened, and I was looking forward to having my name in the TEI Bibliography. I’m also honored that y’all consider my work alongside your own: encoding that goes uncredited, but in the service of furthering the TEI’s mission. I won’t be happy to lose credit, but I will understand.

I have to point out, however, that y’all may need to start up another GitHub issue re: the permanence of the online resources you might cite, because there will be other cases like this one.  If I had a personal blog and had posted this on there, would that be more or less ephemeral than this issue? I could stop paying for the site, or take down the post, or change the link. If I had added my examples to my own ODD, would you consider that a more stable resource even though it is, itself, hosted on GitHub? Would I really have to have published this in a print medium for it to be citable?

Again, I’ve got an ego boost on the line here. That said, the fact that you’re adopting `<persPronouns>` at all is a huge win to me. :smiling_face_with_three_hearts: So I’ll quit leaving comments on this thread and let y’all work things out.
