### ISSUE TITLE
<place> should be allowed to contain <address> as a child.

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#2016]
It seem strange to be that `<place>` is not allowed to contain `<address>` as a child. One can indeed embed it in `<location>` and similar elements, but wanting to have an address directly inside a `<place>` element seems reasonable for more abbreviated places.

**Comment by raffazizzi** [comment]
Council VF2F thinks `<location>` serves to signal `<address>` as a specific location just like a geo-coordinate reference, and does not think we should allow `<place>` to contain `<address>` as a direct child. 

See the guidelines: 13.3.4 “Places” defines place as having a name and a location.  "Country, region, and settlement are all specializations of the generic placeName element and are therefore allowed as children of place". Address is not semantic sugar for placeName so it should remain in `<location>`.
