### ISSUE TITLE
author - birth - death in teiHeader

### ISSUE THREAD

**Issue by AnasGhrab** [TEIC/TEI#2017]
Hi,

I'm doing a critical edition of a text. How to put the birth and the death dates of the author in the teiHeader ?

Thank !

--
Anas

**Comment by laurentromary** [comment]
This reminds me of an old debate regarding putting more stuff in authors' descriptions, cf. https://github.com/TEIC/TEI/issues/542. Shall we reopen the debate?

**Comment by martindholmes** [comment]
I think this ought to be an email to the TEI-L list rather  than a GitHub issue. @AnasGhrab Could  you join TEI-L (https://listserv.brown.edu/cgi-bin/wa?A0=TEI-L) and send it there?
