### ISSUE TITLE
ptr element should allow desc child

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#2019]
In dealing with a large list of `<ptr/>` elements I have occasionally wanted to be able to provide a `<desc>` child to a pointer giving a description of the pointer. This would enable having descriptive text available for that pointer regardless of whether the target(s) are able to be found.

```xml
<ptr target="http://foo.com/examples.xml/persName-example.xml#abc123/>

vs

<ptr target="http://foo.com/examples.xml/persName-example.xml#abc123>
  <desc>An example provided by foo.com of a persName element</desc>
</ptr>
```

**Comment by lb42** [comment]
If you used ref instead of ptr you wouldn't need to do this.

**Comment by jamescummings** [comment]
@lb42 our examples of ref would lead one to believe that the text inside is akin to text inside an html:a, forming link text. Yes, I could just use ref with solely a desc inside, but that somehow seems more incorrect to me. As if the reason one would choose ref is to be able to provide the text which is itself the reference. I'm using ptr specifically because I don't have that. I recognise that the description of ref certainly allows this -- but if not to make this distinction why have ptr at all?

**Comment by lb42** [comment]
Sfaicr the only reason for having both ptr and ref was to have a point in ng element which would be reliably empty. Your proposal screws that up for no very good reason. It seems like splitting hairs to distinguish the stuff you might put in a desc from the stuff you might want displayed as the reference itself.

**Comment by raffazizzi** [comment]
VF2F subgroup thinks <location> serves to signal <address> as a specific location just like a geo-coordinate reference, and does not think we should allow <place> to contain <address> as a direct child. 

See the guidelines: 13.3.4 “Places” defines place as having a name and a location.  "Country, region, and settlement are all specializations of the generic placeName element and are therefore allowed as children of place". Address is not semantic sugar for placeName so it should remain in <location>.

**Comment by raffazizzi** [comment]
CLOSED THE WRONG TICKET! Re-opening

**Comment by sydb** [comment]
Council agrees with @lb42 (and me) that `<ptr>` exists for the purpose of having a definitionally empty pointer element; `<ref>` can be used for @jamescummings use case (the idea being that `<desc>` is what indicates “this is a description of the pointer” as opposed to link text).

Thus we do not think it appropriate to allow `<desc>` as a child of `<ptr>`.
