### ISSUE TITLE
`<pron>` should be a member of att.typed

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2020]
This discussion on TEI-L:

http://tei-l.970651.n3.nabble.com/lt-pron-gt-and-phonemic-phonetic-td4032814.html

makes the case for `<pron>` as a member of att.typed, on the basis that it's repeatable and can be categorized in many ways (broad/narrow or phonemic/phonetic transcription, for example). No other appropriate way of encoding such distinctions has been suggested in the discussion, and other TEI users have already made this customization in their own projects.

**Comment by lb42** [comment]
Seems like a no rainier to me.

**Comment by martindholmes** [comment]
@lb42 Typo or subtle joke I'm too dim to get?

**Comment by lb42** [comment]
Sorry. Predictive text fail : I meant no brainer. No monagesque reference intended.

**Comment by laurentromary** [comment]
I agree with  @lb42 , it could not be any sunnier. Let's have `<pron>` be typed.

**Comment by peterstadler** [comment]
Since so many Ex Council members voted in favor of this I took the liberty to push this to dev without further triage by current Council.
