### ISSUE TITLE
data. →teidata. leftovers

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2025]
A quick grep search says there are still ~37 occurrences of “data.” that should almost certainly be “teidata.” in the P5/Source/Guidelines/en/ and P5/Source/Specs/. (The regexp I used was `[^i]data\.[A-Za-z_]`.)

**Comment by sydb** [comment]
Of the ~37 occurrences I had found, most were problems and have been fixed at 3e53959. The following cases were not problematic either because they were false positives (not references to datatypes, but rather the same string occurring in a URL, e.g.) or are commented out:
P5/Source/Guidelines/en/BIB-Bibliography.xml, 1 OK
P5/Source/Guidelines/en/ST-Infrastructure.xml, 1 OK (1 fixed)
P5/Source/Specs/climate.xml, 1 OK
P5/Source/Specs/dataFacet.xml, 1 OK
P5/Source/Specs/dataRef.xml, 1 OK
P5/Source/Specs/measureGrp.xml, 1 OK
P5/Source/Specs/pc.xml, 2 OK
P5/Source/Specs/quotation.xml, 1 OK
P5/Source/Specs/recording.xml, 2 OK
P5/Source/Specs/relation.xml, 1 OK
P5/Source/Specs/teidata.certainty.xml, 1 OK (1 fixed)
 

Also, the entire section STDD is no longer correct, so I removed it.

**Comment by peterstadler** [comment]
Thank you @sydb – do you consider this fixed then? Can we close the issue?
