### ISSUE TITLE
various concerns with 13.3.7 Dates and Times

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2033]
The ID of the section in question is `NDDATE`. I had reason to scan it, and found several items that strike me as potentially problematic.

- [x] The second paragraph starts with “The current module **namesdates** provides a mechanism …”, with “namesdates” encoded as an `<ident>`. Even so, I think there should be some punctuation offsetting it. Either commas, parens, or em dashes.
- [x]  The final phrase of the 1st paragraph of 13.3.7.1 _Relative Dates and Times_ (`NDDATER`) is a parenthetical listing some example offset words: “(e.g. ‘of’ implying after, ‘before’, ‘after’)”. I think that would be easier to read if the complex one were put at the end: “(e.g. ‘before’, ‘after’, or ‘of’ implying after)”.
- [x] The final sentence of the next paragraph (2nd of 13.3.7.1) is “This allows for deeply nested structures such as ‘the third Sunday after the first Monday before Lammastide in the fifth year of the King's second marriage ... ’ but so does natural language.”. This seems problematic, or at least clumsy, to me. It boils down to “This allows for deeply nested structures such as [natural language example] but so does natural language.”. The problem of calling a natural language representation a deeply nested structure in opposition to natural language could be fixed by replacing the example with an actual XML structure. (E.g. “This allows for deeply nested structures such as ‘`<date when="1800-08-17">the third Sunday <offset>after</offset>
          <date when="1800-07-28">the first Monday <offset>before</offset>
            <date when="--08-01">Lammastide</date> in the <date when="1800">fifth year
                <offset>of</offset> the King's second marriage</date></date></date>`’ but so does natural language.”) But this still leaves the sentence sounding apologetic, which I don’t like. My suggestion would be something like “This allows for unambiguous representation of complexly nested dates that can be found in natural language, such as ‘the third Sunday after the first Monday before Lammastide in the fifth year of the King's second marriage ...’.
- [x] Further, it would be good to have a citation for that Lammastide quote.
- [x] The 2nd example in 13.3.7.2 _Absolute Dates and Times_ (`NDDATEA`) has a bibliographic citation that says it is from a headline in the 26 Oct 1775 edition of _The Independent_. While I suppose this is _possible_, it is awfully suspicious. Certainly no headline in an 18th century periodical would have just a 20th century date, would it? So if this is correct (which I kinda doubt), there must be more to the headline, and we should have the whole headline in the example. Furthermore, [Wikipedia](https://en.wikipedia.org/wiki/The_Independent_(disambiguation)) does not list any _The Independent_ that was being published as far back as 1775.

**Comment by sydb** [comment]
- [x] Another ND problem: search for “between "Tony" and "Antony"”. I claim those quote marks should be `<mentioned>`.

**Comment by sydb** [comment]
- [ ] What? The entire structure of this chapter is messed up. (All date & time sections are subsections of 13.3, “Biographical and Prosopographical Data”, when they should be their own section.) Probably a mis-placed `</div>` or some such.

**Comment by lb42** [comment]
No. The entire structure of the chapter is not messed up. 13.2 is all about names. 13.3 is all about named entities. This is a pretty fundamental distinction which the chapter structure is trying to reinforce.
Your other corrections are fine though. The "Independent" example is clearly a typo. There's no source for the Lammastide example because I made it up. The awkward phrasing of "The current module namesDates..." would be better improved by removing the "current" (what does it mean anyway?) -> "The namesDates module..."

**Comment by sydb** [comment]
OK, minor issues fixed. As for the structure, just making sure we’re talking about the same thing, here, @lb42 …

Here is the structure of the chapter:
~~~
| 13       | Names, Dates, People, and Places            (=ND)
| 13.1     |    Attribute Classes Defined by This Module (=NDATTS)
| 13.1.1   |       Linking Names and Their Referents     (=NDATTSnr)
| 13.1.2   |       Dating Attributes                     (=NDATTSda)
| 13.2     |    Names                                    (=NDNA)
| 13.2.1   |       Personal Names                        (=NDPER)
| 13.2.2   |       Organizational Names                  (=NDORG)
| 13.2.3   |       Place Names                           (=NDPLAC)
| 13.2.3.1 |          Geo-political Place Names          (=NDPLGU)
| 13.2.3.2 |          Geographic Names                   (=NDPLGF)
| 13.2.3.3 |          Relative Place Names               (=NDPLR)
| 13.2.4   |       Object Names                          (=NDOBJN)
| 13.3     |    Biographical and Prosopographical Data   (=NDPERS)
| 13.3.1   |       Basic Principles                      (=NDPERSbp)
| 13.3.2   |       The Person Element                    (=NDPERSE)
| 13.3.2.1 |          Personal Characteristics           (=NDPERSEpc)
| 13.3.2.2 |          Personal Events                    (=NDPERSEpe)
| 13.3.2.3 |          Personal Relationships             (=NDPERSREL)
| 13.3.3   |       Organizational Data                   (=ND-org)
| 13.3.4   |       Places                                (=NDGEOG)
| 13.3.4.1 |          Varieties of Location              (=NDGEOGva)
| 13.3.4.2 |          Multiple Places                    (=NDGEOGmp)
| 13.3.4.3 |          States, Traits, and Events         (=NDGEOGste)
| 13.3.4.4 |          Relations Between Places           (=place-rel)
| 13.3.5   |       Objects                               (=NDOBJ)
| 13.3.6   |       Names and Nyms                        (=NDNYM)
| 13.3.7   |       Dates and Times                       (=NDDATE)
| 13.3.7.1 |          Relative Dates and Times           (=NDDATER)
| 13.3.7.2 |          Absolute Dates and Times           (=NDDATEA)
| 13.3.7.3 |          More Expressive Normalizations     (=NDDATEISO)
| 13.3.7.4 |          Using Non-Gregorian Calendars      (=NDDATECUSTOM)
| 13.4     |    Module for Names and Dates
~~~
With “Dates and Times” a subsection of “Biographical and Prosopographical Data”. With obvious exceptions (“September 11th”) I do not see dates or times as named entities myself. Certainly not in the same way as a person, place, or organization.

**Comment by lb42** [comment]
The statement "The entire structure of this chapter is messed up" is a little hyperbolic tjough I agree that section NDDATE doesn't have any very obvious good home. It used to be much smaller, before all this guff about nonGregorian normalization was added, and could get away with being a subsection of NDPERS, but I take your point that now it has been so substantially enriched it should be a section in its own right e.g. a new 13.4 or even 13.2 --  The trouble is that an understanding of 13.3 does require an understanding of the dating attributes, which are used passim without much explanation.

**Comment by duncdrum** [comment]
i take it `guff` is short for `good stuff`? but yes +1 for making it its own section, historical calendars are hard enough as it is.

**Comment by sydb** [comment]
OK. Going to close this ticket, then, and open a new one with suggestion that NDDATE become a direct child of ND. (Personally I think placing it as a new 13.2 is probably the way to go.)
