### ISSUE TITLE
Element/@ident without English glosses or descs

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#2037]
This seems like a bit of a bug. Take the valItem "cancelled" from `@reason` on `<gap>`:

```xml
<valItem ident="cancelled">
  <gloss versionDate="2017-02-06" xml:lang="de">abgebrochen</gloss>
  <gloss versionDate="2017-02-06" xml:lang="it">cancellato</gloss>
  <gloss versionDate="2017-02-06" xml:lang="es">cancelado</gloss>
  <gloss versionDate="2017-02-06" xml:lang="fr">biffé</gloss>
</valItem>
```
This has various glosses in different languages, which are translating the `@ident` on the valItem. There is no English gloss. What this means is that the method we use for checking translation staleness cannot work. If we changed the `@ident` here, there would be no way of knowing the glosses needed to be updated.

Possible solutions:
1. For any desc or gloss not in `@xml:lang="en"`, require there be an English version.
2. Allow a `@versionDate` on the valItem that applies to its `@ident`.
Choice 1 might result in redundant-looking displays in the Guidelines, like 

**cancelled** (cancelled)

for the English version.

**Comment by hcayless** [comment]
Actually, this happens with `@ident`s for elements as well.

**Comment by lb42** [comment]
These bare glosses are indeed confusing. They can't be used as @idents themselves (if they could, they'd be @altIdents) so all they are really doing is providing a language specific bit of explanation for the @ident value. Why then are they not part of a  (language-specific) `<desc>` ?

**Comment by hcayless** [comment]
I did wonder about that, but doesn't resolve the question of how you'd know what it's translating so you can check its staleness. Does it?

**Comment by lb42** [comment]
No: it's a separate issue.

**Comment by hcayless** [comment]
Some stats:

`<elementSpec>` without an English gloss, but with glosses
```
de     39
es     6
fr     172
it     6
ko     5
zh-TW  5
```
`<valItem>` without an English gloss, but with glosses
```
de     43
es     11
fr     12
it     10
ko     4
zh-TW  1

**Comment by sydb** [comment]
[Note: TEI Council is considering adding `<gloss xml:lang="en">` even when the value of the gloss matches the `@ident` of its parent element.]

Of course, if we follow this route blindly, the 444 `<valItem>`s and ~442 `<attDef>`s that do not have any glosses now get just 1, a useless English gloss. Do we want to have constructs like
~~~xml
<valItem ident="draft">
  <gloss xml:lang="en" ident="draft"/>
</valItem>
~~~
just to be consistent, or would we be happy leaving a *Spec element that has no _other_ gloss empty, i.e. without an English gloss?

This would mean we lose the “schema can require a gloss” advantage, but I think it is probably worth it. The above is both ugly and stupid, IMHO.

**Comment by hcayless** [comment]
@sydb Are things that way because with no gloss, there’s nothing showing up as translatable though?

**Comment by sydb** [comment]
@hcayless — Sorry, I don’t understand the question.

**Comment by hcayless** [comment]
My understanding of the way the translation workflow goes is that a CSV export is generated looking at untranslated content of gloss/desc/etc. or content where the English version has a later date than the translation. If there's no English version, does the original `@ident` itself with no glosses in other languages signal the  need for a translation? I don't know the answer, but my question is whether there are no non-English glosses for `@ident="draft"` _because_ it never got flagged for translation.

**Comment by lb42** [comment]
It would make no sense to supply a translation for an *ident* ... You might perhaps supply an altIdentifier or a gloss, but idents are in teispeak like attribute names and gis. They just look like they are in English sort of.

**Comment by sydb** [comment]
@hcayless: Well, that’s an easy one to answer, because the answer is “I have no clue”. :-(

**Comment by lb42** [comment]
Note also that some projects supply additional ident values which look like they come from other languages

**Comment by martindholmes** [comment]
I think we should just add English glosses and be done with it; make them mandatory with Schematron.

**Comment by ebeshero** [comment]
Council VF2F: @sydb should proceed with requiring English glosses.

**Comment by martinascholger** [comment]
We should not forget to change the style guides for writing Guidelines.

**Comment by sydb** [comment]
So I am proceeding with making `<gloss xml:lang="en">` a required child of the following elements iff there is already a `<gloss>` child at all. I am doing this _in the **p5odds** schema_. Thus this change does not effect the ODD language as defined **by** the _Guidelines_, but rather only the ODD language as we use it **in** the _Guidelines_.

###### Specification elements that will get this treatment, listed with how many occurrences in p5.xml already have a `<gloss>` child and how many do not:

| element     | # with | # without |
| ----------- | --- | --- |
| valItem     | 180 | 818 |
| elementSpec | 503 |  79 |
| attDef      | 115 | 404 |
| classSpec   |   3 | 198 |
| dataSpec    |   1 |  32 |
| macroSpec   |   6 |   0 |

The next step will to be to go ahead and generate the `<gloss xml:lang="en">` elements for those elements listed above that already have a `<gloss>` child, but not one with `xml:lang="en"`.

I will be doing this in a separate branch. (“sydb-2037” or some such.)

**Comment by sydb** [comment]
PR has been merged
