### ISSUE TITLE
remove directory "genetic"

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#2043]
the current [security warning about some outdated jQuery dependency](https://github.com/TEIC/TEI/pull/2039) makes us (TEI Council during its F2F) think that we should get rid of that directory completely. Its purpose was to facilitate the work of the "Genetic Encoding" working group and is not needed anymore.

**Comment by peterstadler** [comment]
@TEIC/tei-technical-council anyone against labeling this as "green" and "go"?!

**Comment by sydb** [comment]
I’m not only not against, I’m in favor of doing so, and of actually deleting the directory. (Keeping in mind that this is a revision control system, and we can go back and get that information if we need it makes this a pretty easy call for me. Could be useful, though, to leave here on the ticket the git command necessary to get it back.)

**Comment by peterstadler** [comment]
for the record (and since @sydb asked): If you want to the deleted directory back, you'll need to checkout the parent of  the above commit 0f543a9 like 

```sh
git checkout 782a496c22cc01950054cac61858885cb27e2272
```

**Comment by sydb** [comment]
Thank you, @peterstadler !
