### ISSUE TITLE
reports in jTEI

### ISSUE THREAD

**Issue by PietroLiuzzo** [TEIC/TEI#2046]
As discussed with @rvdb I would like to propose in a PR to follow some changes to error messages in the [jTEI ODD](https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_jtei.odd) like, e.g. 

````xml
 <sch:rule context="tei:quote">
     <sch:assert test="id(substring-after(@source, '#'))/(self::tei:ref[@type eq 'bibl']|self::tei:bibl[ancestor::tei:body])">
         <sch:name/> must be accompanied by a bibliographic reference (ref[@type="bibl"]) or a bibliographic description in the running text.
    </sch:assert>
</sch:rule>
````

This is so that, even when disjunct from the documentation (e.g. while editing in Oxygen) they are a bit more explicit in telling to the user how to sort out the issue. 
In this case, the report will tell the user to use `@source` in `<quote>` for example.

I would like also to add links to the documentation as well, but I am not sure how to best do that. Ideally in this example I would like that the report points to https://tei-c.org/release/doc/tei-p5-exemplars/html/tei_jtei.doc.html#quotations

**Comment by rvdb** [comment]
Hi @PietroLiuzzo ,

> I would like also to add links to the documentation as well, but I am not sure how to best do that. Ideally in this example I would like that the report points to https://tei-c.org/release/doc/tei-p5-exemplars/html/tei_jtei.doc.html#quotations

Good point! Even better: apparently, there's an attribute for that: `@see`, which can occur on `<sch:report>` and  `<sch:assert>`. 

So, this could be done as:

    <sch:rule context="tei:quote">
      <sch:assert test="id(substring-after(@source, '#'))/(self::tei:ref[@type eq 'bibl']|self::tei:bibl[ancestor::tei:body])" see="https://tei-c.org/release/doc/tei-p5-exemplars/html/tei_jtei.doc.html#quotations">
        <sch:name/> must be accompanied by a bibliographic reference (ref[@type="bibl"]) or a bibliographic description in the running text.
      </sch:assert>
    </sch:rule>

Oxygen supports this by providing a link to that URL alongside the error report.

**Comment by ebeshero** [comment]
Closing, belatedly! :-) @PietroLiuzzo 's and @sydb's now-merged PR resolves this ticket.
