### ISSUE TITLE
tei_all.dtd broken

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#2047]
@sydb's [recent reordering of moduleRefs](https://github.com/TEIC/TEI/commit/48e6110f7dc5e301896298ab9f1e26e4fdca6e37) broke  tei_all.dtd  because now in the resulting version `%att.lexicographic.normalized.attributes`  is referenced before it is declared. 

Jenkins just issues the warning ```tei_all.dtd:1318: parser warning : PEReference: %att.lexicographic.normalized.attributes; not found``` but does not flag the build as 'broken', only as 'invalid'.

I can see at least three options to deal with this:
* simply undo the changes from 48e6110f7dc5e301896298ab9f1e26e4fdca6e37 to `tei_all.odd`
  * a minimal fix might be to move the import of the `analysis` module (where `att.lexicographic.normalized` is defined) before the `dictionaries` module (where the referencing `att.lexicographic` is defined).
* fix the processing from `tei_all.odd` to `tei_all.dtd`. Then this issue should probably be transferred to the Stylesheets repo
* get rid of DTD support (muhaha)

**Comment by sydb** [comment]
Seems to me your options are listed exactly in reverse order of preference. (That is, the last one is the best, the first the worst :-)

I don’t like the “undo all changes” option, but the minimal fix, if it works, is probably a really good idea because we would also need to add documentation to explain _why_ the modules are referenced out of order, which we should have.

A side question is why didn’t this get caught when I ran `make test` on my local system?

**Comment by peterstadler** [comment]
> A side question is why didn’t this get caught when I ran make test on my local system?

I think it only surfaces when you run `make exemplars`; and the warning is rather hidden since the build is not stopped and flagged as broken.

**Comment by peterstadler** [comment]
Just tested the 'minimal fix' locally and pushing up the `analysis` module does help :) 

```xml
<schemaSpec ident="tei_all" start="TEI teiCorpus">
  <moduleRef n="01" key="tei"/>
  <moduleRef n="02" key="header"/>
  <moduleRef n="03" key="core"/>
  <moduleRef n="04" key="textstructure"/>
  <moduleRef n="05" key="gaiji"/>
  <moduleRef n="06" key="verse"/>
  <moduleRef n="07" key="drama"/>
  <moduleRef n="08" key="spoken"/>
  <moduleRef n="17" key="analysis"/>
  <moduleRef n="09" key="dictionaries"/>
  <moduleRef n="10" key="msdescription"/>
  <moduleRef n="11" key="transcr"/>
  <moduleRef n="12" key="textcrit"/>
  <moduleRef n="13" key="namesdates"/>
  <moduleRef n="14" key="figures"/>
  <moduleRef n="15" key="corpus"/>
  <moduleRef n="16" key="linking"/>
  <moduleRef n="18" key="iso-fs"/>
  <moduleRef n="19" key="nets"/>
  <moduleRef n="21" key="certainty"/>
  <moduleRef n="22" key="tagdocs"/>
</schemaSpec>
```

**Comment by sydb** [comment]
Thanks for testing.
(But I **did** run make exemplars.)-:
I will try to write up some prose to explain the new order tonight.

**Comment by sydb** [comment]
Minimal fix pushed; hope Mr. Jenkins likes this one. If he does, I am inclined to close this issue and open a new one that ponders why att.lexicographic.normalized is declared in analysis rather than dictionaries.
