### ISSUE TITLE
@who for <span>

### ISSUE THREAD

**Issue by berndmoos** [TEIC/TEI#2048]
In our work with the TEI versions of spoken language transcripts (following https://www.iso.org/standard/37338.html), we've come across a need to give `<span>` a `@who` attribute. The reason is that `@from` and `@to` alone do not always fully specify the reference of a `<span>` annotation. For example, we have cases like so:

```
1 A: Hello B!
2 B: I'm not listening.
3 A: How are you doing?
```

And we want `<span from="1" to="3" who="A">Greeting</span>` in order to exclude 2. Since the annotation stretches across several `<annotationBlock>` elements, we cannot, in this case, make the speaker reference explicit by putting `<spanGrp><span>` underneath `<annotationBlock>`.

As per the TEI guidelines, `@who` is currently not a permissible attribute for `<span>`. We'd like to suggest to make it so.

**Comment by iljackb** [comment]
I second this proposal. I personally use it (with an ODD schema) when attributing the contents of `<span>` annotations to a particular annotator or language consultant.

**Comment by lb42** [comment]
@iljackb : why don't you use @resp which is available already and is intended specifically for this purpose?

**Comment by iljackb** [comment]
Hmm.. @lb42 looking at my data, I do actually use `@resp` not @who! (It's been a few months since I've worked on my corpus, sorry for the confusion!!). `@who` is used at a higher level in the actual text or spoken language data to attribute the speaker in an utterance or dialogue

**Comment by laurentromary** [comment]
@berndmoos Would it not be a possibility to point to the corresponding utterances selectively?
`<span target="#u1 #u3">Greeting</span>`

**Comment by berndmoos** [comment]
> @berndmoos Would it not be a possibility to point to the corresponding utterances selectively?
> `<span target="#u1 #u3">Greeting</span>`

@laurentromary: Yes, and we do that for cases where the target is as simple as my example was simplified. The cases we would prefer an alternative solution is where `@start` is some token in one utterance and `@end` some token in another utterance (sometimes much) further on. We would have to put all the intervening token IDs into the target, and there can be very many of them, like so:

`<span target="#w2 #w3 #w5 #w6 ... #w27 ... #w111 #w112/>` (well, much longer, but you see what I mean)

Also, the indexing mechanism (MTAS) we use for making the data queryable would remain much clearer if we could use `@who` as a 'filter' for the tokens between `#w2` and `#w112`.

**Comment by sydb** [comment]
Council SVF2F sub-group feels (pretty strongly) that

1. finding a way to select a subset of the stuff pointed at by `@target` or between `@from` and `@to` is a very reasonable request, and 
2. that a `@who` attribute that selects them based on who is speaking is way too special-purpose a solution.

Thus we plan to close _this_ ticket “won’t fix” with the caveat that if OP (or anyone else) thinks it important to have such a mechanism, another ticket should be open for a more general-purpose mechanism. For example, adding the `@match` of att.scoping might be just the ticket.
