### ISSUE TITLE
label for Exemplars?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2051]
In creating #2050 I had expected their to be a label for “exemplars” (or some such). I could almost swear we created such a category this past summer.

I am not sure whether it should be "TEI: Exemplars" or just "Exemplars", but I, for one, am pretty convinced it should exist. Soon.

Assigning to @ebeshero and @martinascholger, as they were part of the “re-organize labels” task force this summer, IIRC.

**Comment by martinascholger** [comment]
I've added the new label "TEI: Exemplars"
