### ISSUE TITLE
attDef/@ns still has the wrong default value

### ISSUE THREAD

**Issue by dmj** [TEIC/TEI#2058]
The discussion in #606 ended in the decision to remove the default value from attDef/@ns. But the guidelines still define a defaultVal for this attribute:

https://github.com/TEIC/TEI/blob/9e6d7fb88717edf3befe52f83aceb315ec8298a7/P5/Source/Specs/attDef.xml#L142

**Comment by sydb** [comment]
I do not think this needs deprecation or discussion, myself. I think @dmj is right, that `<defaultVal>` should simply be removed. (Some might argue in favor of `<defaultVal/>`, but I would argue against.)
