### ISSUE TITLE
Prose in "Element and Attribute Descriptions" (TDphraseEA) refers to non-existent <ptr> in example

### ISSUE THREAD

**Issue by dmj** [TEIC/TEI#2060]
https://github.com/TEIC/TEI/blob/9e6d7fb88717edf3befe52f83aceb315ec8298a7/P5/Source/Guidelines/en/TD-DocumentationElements.xml#L156

The prose below the example starts with "When formatting the <gi>ptr</gi> element in this example..." but the example does not contain a &lt;ptr> element.

**Comment by GusRiva** [comment]
I was able to track down where that `ptr` was in the example. This is the original formulation:

```
<egXML xmlns="http://www.tei-c.org/ns/Examples"><div3><head>Element and attribute descriptions</head>
<p>Within the body of a document using this module, the following
elements may be used to reference parts of the specification elements
discussed in section <ptr target="#TDcrystals"/>, in particular the
brief prose descriptions these provide for elements and attributes.
<specList>
<specDesc key="specList"/>
<specDesc key="specDesc"/>
</specList></p>
<p>TEI practice requires that a <gi>specList</gi> listing the elements
...
</p><!-- ... --></div3>
</egXML>
```

Which was changed to the current:
```
 <egXML xmlns="http://www.tei-c.org/ns/Examples" source="#SELF">
          <div>
            <head>Element and Attribute Descriptions</head>
            <p>Within the body of a document using this module, the … the brief prose descriptions these provide for elements and attributes.
              <specList>
                <specDesc key="specList"/>
                <specDesc key="specDesc" atts="atts"/>
              </specList></p>
            <p>TEI practice recommends that a <gi>specList</gi> listing the elements under … </p>
            <!-- ... -->
          </div>
        </egXML>
```

I can't find the exact commit where this was changed.

**Comment by sydb** [comment]
While the addition of `@source` (to `<egXML>`) and changing `<div3>` to `<div>` were obviously appropriate changes, eliding “following elements may be used to reference parts of the specification elements discussed in section &lt;ptr target="#TDcrystals"/>, in particular” was obviously a mistake because it drops the `<ptr>`. I think it should be just tucked back in, leaving the rest as-is.
