### ISSUE TITLE
specDesc does not only point to element or class specification elements

### ISSUE THREAD

**Issue by dmj** [TEIC/TEI#2061]
The definition of specDesc reads:

> indicates that a description of the specified element or class should be included at this point within a document. ... @key supplies the identifier of the documentary element or class for which a description is to be obtained.

But the specDescs in the guidelines chapter 1.4 Macros point to macroSpec elements.

The definition thus should read:

indicates that a description of the specified **element, class, or macro** should be included at this point within a document. ... @key supplies the identifier of the documentary **element, class, or macro** for which a description is to be obtained.

**Comment by dmj** [comment]
Addendum: Running the following XQuery on p5.xml shows that specDesc refers to other specification elements as well:

```xquery
declare namespace tei="http://www.tei-c.org/ns/1.0";

//tei:*[@ident = //tei:specDesc/@key]/name() => distinct-values() => sort()
```

```
attDef classSpec constraintSpec dataSpec elementSpec macroSpec moduleSpec paramSpec valItem
```

**Comment by sydb** [comment]
I used two different mechanism to determine the list, and I get the exact same result as @dmj, and think the wording should indeed be updated.

But I think the wording in this tagdoc is even worse than @dmj points out: nowhere does it say that the `@key` refers to a specification (or “documentary” — do we like that word?) element by its `@ident`.

My suggested wordings: 

> indicates that a description of the specified construct should be included at this point within a document.

> supplies the identifier of the (documentary|specification) element for which a description is to be obtained.

And, add a `<remarks>` (of the `@key` attribute) that says something like “The value should match the `@ident` of a documentary element (i.e., a member of `att.identified`).”


(HOWEVER, I have a sidetrack concern. When I looked for the elements that `<specDesc>` refers to I did not put them through distinct-values(), but rather spit them all out and counted them. I am somewhat concerned that my 2 different mechanisms resulted in different counts; but at least the three lists — @dmj’s and my two — are the same.)

**Comment by JanelleJenstad** [comment]
@ebeshero and I are looking at this and may try to make a branch for this ticket, and start by addressing the simple wording in a pull request. As @sydb suggests, there may be some larger issues here that we might address at the F2F next weekend.

**Comment by JanelleJenstad** [comment]
@ebeshero and I recommend that we consider merging this branch into dev for the next release and defer dealing with @sydb's deeper dive until after the release. We request discussion at F2F. We'll leave the branch for future work, keeping in mind that it will need to be updated.

**Comment by sydb** [comment]
Seems reasonable to me (to do only the original request now, defer my added suggestions until later). It looks to me like only ½ the original request has been done in [the PR](#2088) so far.  It addresses the description of `<specDesc>`, but not of the description of `@key` of `<specDesc>`.

**Comment by JanelleJenstad** [comment]
@sydb: We'll revisit this on Thursday. We've just had a 3.5-hour training session!

**Comment by ebeshero** [comment]
@sydb For some reason I decided this would be just the right place to get @JanelleJenstad started with her first ticket...:-) Seemed like a good way to introduce working in a branch. If you'd like to contribute by addressing the description of `@key` before this Thursday, that would be splendid, but if not, we'll see about that when we meet a day before the F2F. :-)

**Comment by lb42** [comment]
It would be a good idea always to use the same term for those things which are variously called "components" or "specification elements" or "*Spec" elements. Providing a list of them every time they are referenced seems somewhat verbose.

**Comment by ebeshero** [comment]
@sydb @JanelleJenstad I believe I've addressed the immediate call for remarks on the `@key` for `<specDesc>` in this commit: https://github.com/TEIC/TEI/pull/2088/commits/dc7fb701684c0ee82e610c8374c10e7c212c96bf

**Comment by ebeshero** [comment]
VF2F @raffazizzi is adding an Italian translation, and then we'll merge this in and close the ticket.
