### ISSUE TITLE
specDesc/@key should be required

### ISSUE THREAD

**Issue by dmj** [TEIC/TEI#2062]
The specDesc element ndicates that a description of the specified element or class should be included at this point within a document. Its @key attribute supplies the identifier of the documentary element or class for which a description is to be obtained.

The attribute is defined to be optional but should be required.

**Comment by sydb** [comment]
I agree, and think this is a corrigible error.

P.S. There are no instances of `<specDesc>` in the Guidelines sources that do not have `@key`, and (unlike, say `<dataRef>`) there is no other mechanism for indicating which  specification’s description is to be grabbed.

**Comment by sydb** [comment]
P.S. I think this issue should be “Status GO”, except for the question of whether deprecation is required or not, which needs discussion. I do not think deprecation is required at all.

**Comment by tuurma** [comment]
I don't think deprecation is required, anyone who does use this would have the @key already.
