### ISSUE TITLE
Create script for listing assigned tickets by Council Member

### ISSUE THREAD

**Issue by npcole** [TEIC/TEI#2063]
Just to help with management, and suggested by @sydb , create a small script to list tickets assigned to each council member.

**Comment by sydb** [comment]
@npcole, my recollection is that you already did this, but I don’t remember where you put the script. If you did, can you remind us where it is and close the ticket?

**Comment by sydb** [comment]
The answer to my above question, BTW, is in [Nick’s TEI Utilities repo](https://github.com/npcole/teiutils). See the README.md there for how to install & use.
