### ISSUE TITLE
promote “Dates and Times”

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2066]
Per discussion on a [related ticket](https://github.com/TEIC/TEI/issues/2033), the subsection “Dates and Times” should be promoted to a section of the chapter “Names, Dates, People, and Places” (rather than a subsection of “Biographical and Prosopographical Data”). That is, NDDATE should be a child of ND, not of NDPERS.

**Comment by tuurma** [comment]
f2f agrees and suggests to put it as a new section 13.4 *Dates*, before existing Module for *Names and Dates*, so the TOC structure would be as follows

* Attribute Classes Defined by This Module
* Names
* Biographical and Prosopographical Data
* Dates
* Module for Names and Dates

**Comment by MegJBrown** [comment]
Promoted "Dates and Times" to "Dates" as 13.4
