### ISSUE TITLE
description of "URI" in idno/@type

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2071]
The description of the "URI" value of the `@type` attribute of `<idno>` leaves a lot to be desired, like grammar (missing an article before “indication”), specificity (that indication is called a scheme), and accuracy (it is _not_ a filepath).

**Comment by hcayless** [comment]
Suggest replacing this with something like "a value following the syntax described in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986)."

**Comment by sydb** [comment]
@bleekere’s fix looks fine. We might want to think about whether to mention anything about spaces-in-URIs here. My instinct is “no”, it is not necessary to mention spaces in a brief description of a suggested value. But others may disagree. (In which case, they should open a new ticket, not comment here.)
