### ISSUE TITLE
att.citing: gloss contains a description

### ISSUE THREAD

**Issue by martinascholger** [TEIC/TEI#2074]
The Spanish `<gloss>` elements for the suggested values 'volume' and 'page' of the `@unit` attribute in att.citing.xml contain a description instead of a gloss. We need to add a gloss and to check the descriptions (`<desc>` elements).

**Comment by sydb** [comment]
Will be assigned to Helena Bermúdez Sabel as soon as I figure out her GitHub user name :-)

**Comment by HelenaSabel** [comment]
Here I am :)

**Comment by HelenaSabel** [comment]
Closed with commit 050441a97
