### ISSUE TITLE
problems with match= (part of att.scoping)

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2078]
The `@match` attribute is defined as part of att.scoping.
1. The remarks are written as if it were defined in `<certainty>`.
2. It is defined as an XPath _expression_, but it should really only be a _pattern_ (v. 2) or _selection pattern_ (v. 3). (See below.)
3. Its definition refers to XPath v. 2.0. I’m thinking it should refer to [XSLT 3.0](https://www.w3.org/TR/xslt-30/#patterns) **selection pattern** instead.

#### below
From _XSLT 2.0 and XPath 2.0_ by @michaelhkay, 4th ed., pp. 681–2:

> A pattern is used in XSLT to define a condition that a node must satisfy in order to be selected.
>  … every pattern is a valid XPath expression, but not every XPath expression is a valid pattern. It wouldn’t make any sense to use the expression `2+2` as a pattern, for example — which nodes would it match? 

Note that patterns are defined by XSLT, not by XPath. (Used by other specs, too, though; in particular XProc and Schematron, I think.)

**Comment by peterstadler** [comment]
@sydb is your point 2 ("defined as an XPath expression") also applicable to `teidata.xpath`? Is that also about _patterns_ not _expressions_?

**Comment by ebeshero** [comment]
@peterstadler @sydb If I remember correctly, we worked with `teidata.xpath` on the `unitDecl`, unit and measure tickets, and I believe there we want to keep the XPath options a little more open to being expressions or patterns.

**Comment by ebeshero** [comment]
VF2F: I will try to implement the small changes recommended here in time for upcoming release.

**Comment by ebeshero** [comment]
With this pull request: https://github.com/TEIC/TEI/pull/2099 , I think I've addressed all the requested changes in this ticket.

**Comment by sydb** [comment]
@peterstadler:
No, at the very least `@value` of `<param>` and `@formula` of att.formula (which @ebeshero alluded to) require full XPath expressions.
But if you are poking at the idea that teidata.xpath should be divided into teidata.xpath and teidata.selectionPattern (or whatever), seems reasonable to me.
