### ISSUE TITLE
Translation mistake in <bindingDesc> definition

### ISSUE THREAD

**Issue by arojascastro** [TEIC/TEI#2082]
Hello, 

I would like to report a possible translation mistake found here: https://tei-c.org/release/doc/tei-p5-doc/es/html/ref-bindingDesc.html

The translation into Spanish of the definition seems erroneous to me: "(descripción obligatoria)" is a literal translation of *binding* which may have two possible translations: 1. "obligatoria" or 2. "encuadernación". 

I believe the right translation should be *(descripción de la encuadernación)* instead. More info: https://www.wordreference.com/es/translation.asp?tranword=binding

So the change should be quite simple:

(descripción obligatoria) --> (descripción de la encuadernación)

Thanks.

**Comment by sydb** [comment]
Thanks. Ticket accepted and will be assigned to Helena Bermúdez Sabel as soon as I figure out her GitHub user name :-)

**Comment by HelenaSabel** [comment]
Closed with commit df6897c0f

**Comment by tuurma** [comment]
@HelenaSabel 
I think there's a typo, superfluous *r* in encua**r**dernación

**Comment by HelenaSabel** [comment]
Thank you, @tuurma! 

Closed with 08c385a85
