### ISSUE TITLE
uber-ticket for SATS

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2086]
This is just an index page, as it were, for 3 tickets I am opening today for addressing problems in section 16.2.4, TEI XPointer Schemes. They are:

- #2083 which is intended for minor tweaks and typos. I do not think much, if any, discussion will be required, and anyone who knows how to edit the _Guidelines_ should be able to handle these. 
- #2084, which is intended for either changes in how something is described or significant clarification. Some may require discussion, others may not. I am suspicious that these should be handled by someone familiar with at least XPointer if not the TEI XPointer schemes.
- #2085, which is intended for issues that require discussion, and may require an actual change to the semantics of a scheme. I am suspicious that these should be addressed by at least someone well-versed in the TEI XPointer schemes.

This all came about because @bwbohl noticed a suspected typo in SATS and sent in [PR#2075](https://github.com/TEIC/TEI/pull/2075), and I was asked to review that PR. In so doing I noticed some additional problems and concerns.

**Comment by hcayless** [comment]
Closing after review.
