### ISSUE TITLE
outdated internal (unencoded) reference

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2100]
The 2nd sentence of the 1st paragraph of [17.4 Linguistic Annotation](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/AI.html#AILA) says

~~~xml
The structural properties of any TEI-conformant text
should be represented using the structural elements
discussed elsewhere in this chapter and in chapters
<ptr target="#CO"/>, <ptr target="#DS"/>, and the
various chapters of Part III.
~~~

The reader is left wondering where and what is **Part III**. (Versions P2–P4 of the _Guidelines_ were divided into parts, the 3rd of which was on base tag sets.)

**Comment by lb42** [comment]
Good catch! This sentence isn't really doing much useful work is it? All it says is that "structural" properties should be represented by "structural" elements, which are described elsewhere than this chapter.

**Comment by sydb** [comment]
Indeed. One possibility would be to replace the entire 2nd part of the sentence:

> The structural properties of any TEI-conformant text should be represented using the structural elements discussed elsewhere in these _Guidelines_.

Another might be to ditch the sentence entirely.

Or, we could list all the chapters:

> The structural properties of any TEI-conformant text should be represented using the structural elements discussed elsewhere in this chapter and in chapters 3, 4, 6, 7, 8, 9, and 15.

(I think I have that list right, but have not spent a lot of time on it.)

**Comment by sydb** [comment]
@MegJBrown and I discussed this and came up with a replacement sentence (pretty close to the 2nd one I suggested above).
Change checked in (df6680e4a), but leaving this ticket open for a week or two to allow others to disagree with our wording.

**Comment by MegJBrown** [comment]
Syd means it was pretty close to his second sentence, with links.

**Comment by MegJBrown** [comment]
Since no one has objected to the wording, we hereby close this ticket.
