### ISSUE TITLE
Suggestion of improvement in the Spanish definition of element <subst>

### ISSUE THREAD

**Issue by arojascastro** [TEIC/TEI#2101]
Hola amigos, 

I just found this casually when browsing the Guidelines to prepare some teaching materials in Spanish: 

> <subst> (substitución) agrupa una o más cancelaciones con una o más adiciones cuando la combinación *riguarda* a una sola intervención en el texto.

https://www.tei-c.org/release/doc/tei-p5-doc/es/html/ref-subst.html

The word "riguarda" is Italian - ops! 

Could you correct it perhaps? I suggest: 

> agrupa una o más cancelaciones con una o más adiciones cuando la combinación *se considera* como una única intervención en el texto.

¡Gracias!

**Comment by HelenaSabel** [comment]
Gracias, Antonio!

Corrected in 8ccbd4f08
