### ISSUE TITLE
Ruby: Add new example with `@hand`

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2107]
@knagasaki provides the following example which should go into the prose, or possibly become one of the examples for the `<rt>` spec page:

> I found an example of a book annotated with handwritten ruby
> by a famous novel writer, Ogai Mori.
> So, I encoded the attached image like below:
> 
> example 1:
>   `<ruby><rb>蘝蔓</rb><rt hand="#森鴎外" style="color: red;">ヤブカラシ</rt></ruby>于野`
> 
> The value of @hand can be replaced with "#OhgaiMor" or something like that.
> He has a VIAF URI: http://viaf.org/viaf/15096
> 
> The image was cropped from the URL below:
> https://iiif.dl.itc.u-tokyo.ac.jp/repo/s/ogai/document/49d0907b-d949-4d14-8aeb-bc1dea9a3ad1?fbclid=IwAR1UgB9NnSfO9AqkLbq-Ym4fsGj8fEIm9gZGt7AwHE65eE-Nq6Bcb78jcxQ#?c=0&m=0&s=0&cv=14&xywh=3462%2C639%2C1315%2C784

![スクリーンショット 2021-02-12 025408](https://user-images.githubusercontent.com/2412617/107684074-2f82fc00-6c57-11eb-92b4-93550afbdb12.png)

This should be added after the upcoming release.

**Comment by martindholmes** [comment]
@MegJBrown, @martinascholger, @hcayless and I say this should simply go ahead, and the example should be added at the end of section 3.4.2 (currently) before the final paragraph of that section. Then another ticket should be raised on the issue of whether `<ruby>` and/or `<rb>` should be members of att.transcriptional or att.written (to allow `@hand`).

**Comment by martindholmes** [comment]
@knagasaki @MegJBrown @martinascholger @hcayless Could you take a look at the new example at the end of 3.4.2, below this egXML: 
https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/CO.html#index-egXML-d52e31842

If it looks good to you, we can close this ticket.

**Comment by knagasaki** [comment]
@martindholmes It looks nice to me. Thank you so much!

**Comment by martinascholger** [comment]
Thanks @martindholmes, looks good! Should there be a reference to the schema spec of `att.written` (as with att.placement)? At the beginning of the chapter, directly after att.placement.

**Comment by martindholmes** [comment]
@martinascholger You're absolutely right; I'll try to work that in.

**Comment by martindholmes** [comment]
Done in commit #a16f45067. When the next build round is finished we can look again.

**Comment by martindholmes** [comment]
I've just moved the captions below the graphics too; I think they look better like that.

**Comment by martinascholger** [comment]
Thanks @martindholmes!
