### ISSUE TITLE
Obsolete email address in every Guidelines page

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2112]
The Guidelines HTML pages contain this:

~~~~~
<meta property="DC.Creator.Address" content="tei@oucs.ox.ac.uk"/>
~~~~~

I doubt that email even works any more, but even if it does, surely there's a better one we could choose?

**Comment by martindholmes** [comment]
The decision on what email to use should be made here, but it turns out the current one is hard-coded in Stylesheets/odds/guidelines.xsl, so I'll raise a bug there.

**Comment by hcayless** [comment]
Unless I hear any objections, I propose to just kill it.

**Comment by peterstadler** [comment]
I have no problems with killing it, I just think it should be delayed until after the release.

**Comment by hcayless** [comment]
I don't feel particularly strongly about it (other than it's an error), but I also see it as the code equivalent of a typo, so I'm not sure why we should be bothered about when it happens.

**Comment by npcole** [comment]
With release manager hat on: can we kill it now? There is no value in printing an address nobody is monitoring in the guidelines.

**Comment by JanelleJenstad** [comment]
Looks like this one is done. We are closing it.

**Comment by ebeshero** [comment]
Council VF2F notes that we've resolved this issue, so we're closing it.
