### ISSUE TITLE
TCW 22 needs updating to cover Oxygen plugin release

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2116]
The release of the Oxygen plugin is part-automated (build and SourceForge release) and part-manual (GitHub tag/release and pushing the updateSite.oxygen file to the TEI server). We need to document that process thoroughly so the release tech can do it along with the rest of the release process. This may also require having a docker container that has Java 8 so that the plugin can build successfully.

**Comment by martindholmes** [comment]
@hcayless I think we completed this immediately after doing the release, didn't we? Is there anything left to do? Or am I looking at old instructions that should be updated?

**Comment by martinascholger** [comment]
I'm closing this issue. @martindholmes wrote an email to the Council's mailing list on 2021-04-19 that the documentation is updated. Thanks @hcayless and @martindholmes !
