### ISSUE TITLE
Typo in 3.6.2: "tel" isn't a namespace

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEI#2133]
In 3.6.2, the prose states:

> A telephone number (normally outside of the address element) might be tagged with an addrLine and ref, with the number itself appearing in the tel: namespace

Source:

https://github.com/TEIC/TEI/blob/a1c3b9aea03755878f8dfaf4f3eb282e59f89c2f/P5/Source/Guidelines/en/CO-CoreElements.xml#L1992-L1996

I don't think "namespace" is right here, since "tel" is a URI scheme (https://tools.ietf.org/html/rfc3966). So maybe something like:

```
might be tagged with an <gi>addrLine</gi> and <gi>ref</gi> that points to the phone number using the <code>tel</code> URI scheme:
```

**Comment by martindholmes** [comment]
@joeytakeda I don't think it's a URI scheme; it's the tel: protocol:

https://davidwalsh.name/phone-link-protocol

So that's what the change should be, IMHO; `s/namespace/protocol/`.

**Comment by lb42** [comment]
"in the tel: protocol"??? sounds like gibberish to me

**Comment by joeytakeda** [comment]
I think Walsh has it wrong there; as far as I can tell, schemes = prefix; protocol = method:

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax
https://stackoverflow.com/questions/48953298/whats-the-difference-between-a-scheme-and-a-protocol-in-a-url

Plus IANA lists it as a "scheme": https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by martindholmes** [comment]
I stand corrected. :-)

**Comment by ebeshero** [comment]
Council SVF2F thinks @joeytakeda 's initial suggestion is absolutely correct.

**Comment by JanelleJenstad** [comment]
Thanks for noticing this problem, @joeytakeda!
