### ISSUE TITLE
Use PureODD inside attribute lists

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2136]
[See TEIC/Stylesheets#144, of which this is a logical extension.]

When ODD was originally invented, we intended the capability to group `<attDef>` elements inside an attribute list as either a group which were all being defined as available to the user (`<attList org="group">`), or as a set being defined of which the user could only choose one (`<attList org="choice">`).

(BTW, this has been implemented and works for `<attList>`s that are inside an element definition, but the Stylesheets fail when it is inside a class definition.)

However, in the modern PureODD age, `<alternate>` would be the correct way to indicate a choice. Reasonable enough. But what would we use to indicate the opposite? `<sequence>` (which indicates the opposite inside a content model) is a bit misleading because, by definition, attributes are unordered (and thus have no sequence). `<group>` makes a lot of sense, but we already have a `<group>` element with entirely different semantics.

Once we have figured out what we want to do, we will need to generate the new element usage (and maybe a new element) here on this ticket, and open a Stylesheets ticket to make it work.

**Comment by lb42** [comment]
This is surely just a stylesheet bug? Attlists should behave in the same way whether they are in a classspec or an elementspec. I see no need to change the use of @org justbecause its function now happens to be expressible in another way .

**Comment by sydb** [comment]
Council decides

1. To keep `<attList org="choice">`, at least for the foreseeable future
2. To fix the Stylesheets so it works (see TEIC/Stylesheets#144 for discussion of the problem)
3. To re-visit this issue (changing to `<alternate>` and either introduce a `<bag>` or `<set>` or use `<group>` or `<sequence>` or something) in the future.
