### ISSUE TITLE
Another example for langKnown

### ISSUE THREAD

**Issue by stuartyeates** [TEIC/TEI#2139]
As suggested on the mailing list, here is a proposed new example for langKnown https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-langKnown.html  The example is from https://raw.githubusercontent.com/iljackb/Mixtepec_Mixtec/master/MIX-People.xml  Note that I have removed all the personally-identifying information from the example. I've forgotten everything I ever knew about bibls, so that bit's pretty much guesswork.

...TEI\P5\Source\Specs\langKnown.xml 

<exemplum xml:lang="en">
<egXML xmlns="http://www.tei-c.org/ns/Examples" source="#Mixtepec_Mixtec">

            <person xml:id="TS" sex="m" role="speaker, collaborator">
                  
                 <langKnowledge>
                    <langKnown tag="mix">Mixtepec-Mixtec</langKnown>
                    <langKnown tag="en">English</langKnown>
                    <langKnown tag="es">Spanish</langKnown>
                 </langKnowledge>
              </person>

</egXML>
</exemplum>

...\TEI\P5\Source\Guidelines\en\BIB-Bibliography.xml

 <bibl xml:id="Mixtepec_Mixtec">
   <author>Jack Bowers</author>.  <title level="a">Mixtepec Mixtec</title>. <date>2021</date>.  
 <ref target="https://github.com/iljackb/Mixtepec_Mixtec">https://github.com/iljackb/Mixtepec_Mixtec</ref>. 
 </bibl>

-

**Comment by sydb** [comment]
Note: this issue has a corresponding [pull request](https://github.com/TEIC/TEI/pull/2143).
