### ISSUE TITLE
wrong attribution for example

### ISSUE THREAD

**Issue by stuartyeates** [TEIC/TEI#2144]
The first example for @key in https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.canonical.html is attributed to 'No source, made up for these Guidelines.'  but the id number and name are suspiciously similar to http://nzetc.victoria.ac.nz/tm/scholarly/name-427308.html so I'm pretty sure the example comes from there.

@Conal-Tuohy may have some memory of how this came about; I certainly don't.

**Comment by lb42** [comment]
Wherever it comes from, I find the usage of an identifier with a space in  it here rather upsetting. Yes, it is permitted by the datatype. But the second example already shows (and motivates) that usage. So the first one should be different, surely. Or at least include some discussion of why in general putting spaces in key values might be better avoided. To say nothing of the fact that this actually distorts the source -- if it is the source -- which has a hyphen!

**Comment by stuartyeates** [comment]
I'm not in any way attached to this example; finding a new one with known attribution is a convenient solution to the attribution problem.

**Comment by tuurma** [comment]
VF2F subgroup suggests:

* change the value of `key` in the existing example to `@key="name-427308`
* add *another* example which uses the same scenario but `@ref="http://nzetc.victoria.ac.nz/tm/scholarly/name-427308.html"` instead of `@key` to illustrate the difference between use of *magic token* like `@key` vs *proper reference* one can actually resolve

**Comment by sydb** [comment]
Perhaps 3 or 4 examples (in addition the the Victor Hugo example):

1. `key="name-427308"`
2. `ref="http://nzetc.victoria.ac.nz/tm/scholarly/name-427308.html"`
3. `ref="nzvn:427308"`
4. `ref="./named_entities.xml#o427308"`

And personally, I think the language denigrating `@key` should be toned down. The main problem with a magic token is not that “there is no way of ensuring that the values used by one project are distinct from those used by another”. After all, that is true of relative or private-use URIs, too. The problem with a magic token is that it is useless unless you send along the documentation about how to resolve it along with the TEI document. With `@ref` you don’t have to write that documentation, and the recipient of your TEI file doesn’t have to read it and write code to follow it, you both just silently agree to use the well-established URI resolution protocols. (In either case, you _may_ have to send the entire database along with the TEI file, but using `@key` it is probably more likely.)

**Comment by sydb** [comment]
So would @stuartyeates or @Conal-Tuohy be able to provide another example with citation in the near future? (Just the information to make an example is sufficient; would be happy to make into actual TEI example and Bibliography example.)

**Comment by stuartyeates** [comment]
My suggested replacement is:

```
<author>
   <name key="name-427308" type="organisation">New Zealand. Parliament. Legislative Council.</name>
</author>
```

Taken from https://nzetc.victoria.ac.nz/tei-source/BIM1388Piti.xml / https://nzetc.victoria.ac.nz/tm/scholarly/tei-BIM1388Piti.html which has all the bib stuff you should need.

**Comment by ebeshero** [comment]
Council F2F Newcastle: @sydb should come up with improved examples.

**Comment by sabineseifert** [comment]
I could offer following examples

`<persName key="A002068">Carl von Weber</persName>`
source:
Complete Works of Carl Maria von Weber. Digital Edition, http://weber-gesamtausgabe.de/A040051 ([Version 4.6.1 of September 30, 2022](https://weber-gesamtausgabe.de/en/A009000/News/A050239.html))
Last change of this document on October 25, 2021

`<persName ref="http://d-nb.info/gnd/115674667">Kunth</persName>`
source: 
Alexander von Humboldt an Johann Moritz Rugendas. [Paris], Sonnabend, [22. Oktober 1825], ed. by Ulrich Päßler in collaboration with Lisa Poggel and Florian Schnee. In: edition humboldt digital, ed. by Ottmar Ette. Berlin-Brandenburgische Akademie der Wissenschaften, Berlin. Version 8 of 11.05.2022. URL: https://edition-humboldt.de/v8/H0017851 
(XML file here: https://edition-humboldt.de/H0017851.xml)

Or what exactly was needed for improved examples?

**Comment by sabineseifert** [comment]
Updated current example and drafted a pull request. Now waiting for @sydb to provide further examples.
(I did not include my offered examples from Oct 15.)
