### ISSUE TITLE
ref/@type should be ref/@target in example

### ISSUE THREAD

**Issue by stuartyeates** [TEIC/TEI#2145]
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#index-egXML-d53e45300  has:

    <ref type="url">http://xml.coverpages.org/coombs.html</ref>

My reading is that this should be:

    <ref target="http://xml.coverpages.org/coombs.html">http://xml.coverpages.org/coombs.html</ref>

There's a very similar one in https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#index-egXML-d53e49326

    <ref type="url">http://www.dlib.org/dlib/january02/sukovic/01sukovic.html</ref>

cheers
stuart

**Comment by hcayless** [comment]
Or maybe just `<ptr target="http://xml.coverpages.org/coombs.html"/>`?

I suppose `<ref>SOME URI</ref>` is fine. I guess I might use it if I _didn't_ want whatever processor I'm using to produce a link in the output...

**Comment by lb42** [comment]
That scenario isn't as unlikely as you might suppose. I have just reviewed a grant proposal in which most of the embedded links were non actionable (because the document had been through some lame PDF conversion). The ones in which the links were *also* visible (but non actionable) in the text were rather useful, since I could cut and paste them into a browser...

**Comment by stuartyeates** [comment]
Shouldn't the primary measure of examples in the standard be "what markup are we trying to encourage, exemplify and model" not "what markup are do we allow in weird corner cases (which we will refrain from mentioning are weird corner cases)" ?

**Comment by hcayless** [comment]
Indeed. I think best practice with a bare URL is probably to use `<ptr target=“...”>`.

**Comment by lb42** [comment]
The `<ptr>` vs `<ref>` (to say nothing of the empty `<ref>`) issue is not germane to the OP's original point though, which concerns the use of @type : I think we'd all agree that supplying @target if there a real URL is available would be much the preferred practice. The use of @type might however be appropriate if there were other kinds of pointer to encode.

**Comment by hcayless** [comment]
Of course it's germane if the solution is to use ptr with target! And yes, there is a tangential and large discussion to be had on when to use one or the other, but I don't want to have that on this ticket, for which there is a simple fix.
