### ISSUE TITLE
allow <schemaSpec> in <front> and <back>

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2149]
In ticket #1921 we are removing `<schemaSpec>` from a variety of silly places (like `<figure>`, `<license>`, and `<scriptNote>`), and we now explicitly recommend “It should be a child of front, body, back, encodingDesc, div, div1, …, or div7.”.
HOWEVER, `<schemaSpec>` is not allowed as a child of `<front>` or `<back>`.
This, I think is a corrigible schema error that should just be fixed.
Alternatively, of course, we could remove the explicit recommendation that it go in `<front>` or `<back>`.

**Comment by lb42** [comment]
I dont think it should be anywhere except inside encodingDesc, or elsewhere in the header. It's metadata.

**Comment by sydb** [comment]
Well, there certainly is an example of `<schemaSpec>` as a child of `<encodingDesc>` in the Guidelines. But only one. In all other cases in our two repos it is a child of `<body>`, `<div>`, `<p>`, or (of course) `<x:egXML>`:
-  81 tei:body
-  77 x:egXML
-  27 tei:div
-  07 tei:p
-  02 x:div
-  01 x:body
-  01 x:encodingDesc

(These results are slightly skewed, because each chapter other than HD is incorrectly counted twice, once in /en/ and once in /fr/.)

So there is little doubt in my mind that (at least for now) it needs to stay in `<body>`, `<encodingDesc>`, `<div>`, and the numbered division elements. I think the only questions are

1. Whether or not it should be allowed in `<front>` and `<back>` (my vote is a strong “yes”, as that is what the prose already says), and
2. Whether it should be added to `<p>`, where it is not currently valid but is used 7 times. (Once each in in TEI/Documents/oldODDmanual/teidoc.odd, TEI/Extensions/Lampeter/lampext.xml, TEI/Extensions/Lite/teilite.xml, TEI/Extensions/Menota/menota.odd, TEI/Extensions/ProtestantCemetery/cem.odd, TEI/Extensions/Test/test.xml, and TEI/I18N/teilite-es.xml.)

I am not sure what my opinion is about `<schemaSpec>` in `<p>` (although I am leaning against) and do not plan to think about it until I have had some dessert!

**Comment by lb42** [comment]
Ah, sorry, my mistake:  my comment was meant to apply only to schemaRef elements. Clearly a `<schemaSpec>` has to be legal in the `<body>` of an ODD somewhere: and I don't really mind where. Though like you, I don't think it should be allowed inside `<p>` -- the use cases you cite are all pretty ancient. Hope you enjoyed your dessert.

**Comment by sydb** [comment]
Yes, dessert was delicious, thank you. And yes, `<schemaRef>` should continue on as just a child of `<encodingDesc>`.
And I think you are right: we should keep `<schemaSpec>` out of small `<p>`-sized things.

**Comment by ebeshero** [comment]
@sydb It’s pretty clear this ticket follows up on #1921 where we already had some discussion about allowing `<schemaSpec>` in `<front>` and `<back>`, the upshot of which is already written up in a Schematron deprecation warning (explicitly saying that it’s only going to be allowed in certain elements, including `<front>` and `<back>`). I think we have to follow through on what we promised here, or rewrite the Schematron warning AND prose in the Guidelines, too. So yes, I think we should proceed and fix this corrigible error.
