### ISSUE TITLE
Multiple nested objects

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#2152]
@martinascholger recently asked me if it was the intention for `<object>` only to allow one `<object>` child. This was clearly not the intention and I really thought I had tested it. But testing it now I only seem to have a single nested `<object>` child rather than a number of sibilings.

I believe the line at fault is this: 
https://github.com/TEIC/TEI/blob/7d590a8a11918a34174fd03e12589b84683f5b38/P5/Source/Specs/object.xml#L39
which perhaps should have a `@maxOccurs="unbounded"` on it. I think? That will mean it is allowed multiple times there right?

I believe that this is a corrigible error of omission since it is clear that an object which contains another 'sub-object' may indeed be made up of multiple sibling sub-objects. 

Happy to implement it by adding that if someone can confirm the ODD logic that this will indeed make multiple nested `<object>` elements available. (My local build system is broken atm.)

**Comment by martindholmes** [comment]
@jamescummings I think you're correct. The default value of `@maxOccurs` is 1, so that's what's in force at the moment. Clearly a corrigible error, and also has no implications for backwards-compatibility.

**Comment by martinascholger** [comment]
Thanks @jamescummings for opening the issue. I also confirm that `@maxOccurs` should be `unbounded`. Thumbs up for implementing this?
