### ISSUE TITLE
Tagging error in guidelines

### ISSUE THREAD

**Issue by djbpitt** [TEIC/TEI#2159]
There's a header inside https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/ that reads:

The basic structure of a &lt;gi>schemaSpec>

This looks as if it may be a markup error, that is, as if the start-tag intended to tag a GI is being rendered literally instead.

**Comment by ebeshero** [comment]
Thanks, @djbpitt ! By the way, this is on the TEI Website rather than within the Guidelines themselves (despite the link URL, I know). Because it's being served up on the TEI Wordpress site it may take a moment for us to correct...

**Comment by ebeshero** [comment]
Okay, I dredged up my TEI Wordpress login and I believe I've repaired it. Take a look again at https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/
