### ISSUE TITLE
Broken link in 'Getting Started with P5 ODDs'

### ISSUE THREAD

**Issue by gabikeane** [TEIC/TEI#2160]
At the end of the Introduction paragraph, the link to "the TEI web site" 404s.

[URL of page with error](https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/)

[URL that 404s](https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/index.xml)

**Comment by ebeshero** [comment]
Hi @gabikeane ! Looks like the link needs to point up to the parent directory at https://tei-c.org/guidelines/customization/ 

I know there are some link pointing issues from the TEI website, and not sure where we are with resolving them. Thanks for the heads up!

**Comment by ebeshero** [comment]
Okay! I think I've repaired it. Take a look again at https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/ 
Cheers!
