### ISSUE TITLE
TEI Lite ODD on TEI site does not validate in <oXygen/>

### ISSUE THREAD

**Issue by djbpitt** [TEIC/TEI#2162]
If I download tei_lite.odd from https://tei-c.org/guidelines/customization/ and open it in \<oXygen/>, the following snippet:

```xml
<elementSpec module="header" ident="editorialDecl" mode="change">
  <content>
    <alternate minOccurs="1" maxOccurs="unbounded">
      <classRef key="model.pLike"/>
    </alternate>
  </content>
  <!-- examples removed -->
</elementSpec>
```

raises the following Schematron error:

```text
The alternate element must have at least two child elements
```

**Comment by lb42** [comment]
This appears to be the work of Martin Holmes!  
~~~~
  <change when="2014-11-19" who="MH">changing the content model 
      and simplifying the examples in editorialDecl</change>
~~~~
Presumably he meant to write
~~~~
<content>
       <classRef key="model.pLike" minOccurs="1" maxOccurs="unbounded">
  </content>
~~~~
Though I thought it had been agreed that TEI Lite should be retained as an archaelogical curiosity, and not modified.

**Comment by martindholmes** [comment]
@lb42 @djbpitt I can't remember the context for that change, but you're right that it should have been as you suggest. I'll fix it now, since it's a corrigible error.

**Comment by martindholmes** [comment]
Actually, now I check with git blame, those lines seem to have been changed by @sydb in 2019, but that may just have been a whitespace thing. Anyroadup, I've fixed it in commit 9385a2586.

On the issue of an ODD file never being modified, that's not always going to be practical; changes to P5 will result in possibly unwanted changes to the effect of a downstream ODD,

**Comment by lb42** [comment]
... which is why we have and recommend a @source attribute

**Comment by martindholmes** [comment]
I don't remember any decision to freeze the TEI Lite schema, and there isn't an `@source` on the schemaSpec, so as far as I know it's still supposed to be current. It's also part of the Oxygen plugin as an option for creating new TEI files. I think if there were a serious intention to archive and mothball it, then it should have `@source` and should be removed from the plugin (and possibly even the Exemplars), to avoid confusion.

**Comment by lb42** [comment]
Well, I might be mistaken, but I think this was one of the decisions 
taken around the time council was arguing what to call the schema now 
known as tei simple print. But that was in another country, and besides 
the wench is dead.
