### ISSUE TITLE
The .htaccess should have Options +Indexes inside Vault

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#2167]
I happened to go to https://tei-c.org/Vault/MembersMeetings/ the other day and realised that one can't see the index of this directory. Navigation in and around the Vault would be better if we could see directory indexes. (Especially since files there aren't always linked.) This would enable users to navigate (and google find) files related to members meetings without relying on the external members.tei-c.org site. e.g. https://tei-c.org/Vault/MembersMeetings/2017-info/  ... But this is just an example and I think it should be set generally throughout the Vault since the purpose is to make those files available.

This should be checked and .htaccess or whatever should have Options +Indexes or equivalent to enable directory index browsing.

**Comment by peterstadler** [comment]
Just had a look and I think the directory listing setting is already active, see e.g. https://tei-c.org/Vault/P5/.
Problem with the path mentioned above  ist that there is an index.html: https://tei-c.org/Vault/MembersMeetings/index.html with barely any content. My proposed solution would be to delete this file?!

**Comment by jamescummings** [comment]
@peterstadler If indexes is on, then that should work.  (The other option being to add content to the file, a unordered list with items pointing to each of the subdirectories, but then that makes additional work every year... so if deleting it works, then that is better.)


(For the record, I swear when I went there, the index.html file didn't exist and it was just stopping me browsing directories. ;-)  Either I'm mistaken or maybe something changed since july.)

**Comment by peterstadler** [comment]
renamed the file to index.bak and now there's a nice directory listing. Closing the issue :)
