### ISSUE TITLE
minor typo in TD

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#2178]
The string "(or, in RELAX NG compact syntax, (hi,it,bo)*)" is wrong, as indeed is the immediately preceding string 
"(or, in RELAX NG compact syntax, (hi|itIbo)*)."
No @minOccurs or @maxOccurs being supplied for either the `<sequence>` or `<alternate>`  expression which these strings are supposedly equivalent to, they should not contain a star.
Sorry, I only just noticed this fallout from the change made yonks ago to the default values for @*Occurs,

**Comment by sydb** [comment]
Right. Do you think the PureODD should be changed to show `@maxOccurs` (after all, it was introduced well before this), or the RELAX NG snippets should lose the asterisk?

**Comment by sydb** [comment]
Nevermind, that is a dumb question. For at least 1 of the 2, there is no `@maxOccurs` because expansion of `"sequence"` does not produce one, so of course the RNC should be changed.
