### ISSUE TITLE
punctuation in title/@level descriptions

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#2183]
The description for value "a" ("the title applies to an analytic item, such as an article, poem, or other work published as part of a larger item.") ends with a full stop but the others don't.

**Comment by sydb** [comment]
Well spotted!
This is part of a much larger problem: looking at only the 1053 attribute descriptions that are in English I find that 656 end with period (and thus 397 don’t).
However, there is already another issue (#2093, assigned to @JanelleJenstad) for this problem writ large, so we do not need to keep this particular one.
See [descs.txt](https://github.com/TEIC/TEI/files/7168898/descs.txt) for the complete list.
