### ISSUE TITLE
macro.component -> model.common in 4.2.4?

### ISSUE THREAD

**Issue by knagasaki** [TEIC/TEI#2191]
In the 4.2.4,
https://tei-c.org/Vault/P5/4.3.0/doc/tei-p5-doc/en/html/DS.html#DSCO

Other than elements from the model.divWrapper, model.divTop, or model.divBottom classes, every textual division (numbered or un-numbered) consists of a sequence of ungrouped macro.component elements (see 1.3 The TEI Class System)

"macro.component" can not be found in 1.3 The Class System.

According to the past changes:
https://github.com/TEIC/TEI/commit/b542fc4c0c8abc4338604364e278594838797a45

"macro.component" might be changed to "model.common"?

**Comment by sydb** [comment]
Yes, I think you have diagnosed this problem exactly.
Thank you!

**Comment by sydb** [comment]
Fixed in (or is it “at”?) a8229752c.
