### ISSUE TITLE
phrase-level encoding of macros

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2192]
### Impetus and main result
Sparked on by @knagasaki’s catch of a “macro.component” that should have been a “model.common” I decided to check that there were no other references to macro.component in the _Guidelines_. The good news is I did not find any. 

### Findings
The bad news is I found we are inconsistent about how we encode the names of macros. In one case it is (IMHO) clearly wrong, too. Here they are, as found in the source files:[1]
~~~xml
1) <cell>macro.*</cell>                                          (Source/Guidelines/en/AB-About.xml)
2) <cell>macro.paraContent</cell>                                (Source/Guidelines/en/AB-About.xml)
3) <ident type="macro">macro.specialPara</ident>                 (Source/Guidelines/en/PrefatoryNote.xml)
4) <ref target="ref-macro.phraseSeq.html">macro.phraseSeq</ref>  (Source/Guidelines/en/SG-GentleIntroduction.xml)
5) <ident type="macro">macro.xText</ident>                       (Source/Guidelines/en/TD-DocumentationElements.xml)
6) <ident type="macro">macro.phraseSeq</ident>                   (Source/Guidelines/en/USE.xml)
7) <ident type="pe">macro.phraseSeq</ident>                      (Source/Guidelines/en/USE.xml)
~~~
### Discussion
(1) & (2) Make sense in context. They are in a table showing how various components are named, and thus are not actually referring to the components.
(3) Seems fine.
(4) Looks really off to me. I am guessing that the author either did not know how we normally encode macro names, or really wanted it to be a link and did not want to change the Stylesheets. But I think they [should be changed](https://github.com/TEIC/Stylesheets/issues/526).
(5) Seems fine.
(6) & (7) The use of `"macro"` for one `<ident>` and `"pe"` for another with identical content in USE is actually correct. For (6) the prose is referring to the TEI macro, for (7) it is referring to the parameter entity generated from that macro in the DTD output.  
### Suggestion
My first thought is that (4) should be changed to `<ident type="macro">` to match our other encoding. Also the Stylesheets should be updated to create a link from the name of the macro. (See /TEIC/Stylesheets#526.)

### Notes
[1] Interesting to note that the file P5/p5.xml has 6 extra hits, all `<cell>` elements, one for each of the macros we have: limitedContent, paraContent, phraseSeq.limited, phraseSeq, specialPara, and xtext. My educated guess (without actually looking) is that they are generated by an `<?insert?>` PI.

**Comment by peterstadler** [comment]
Hi @sydb, just a quick question that came up during triage: why is this blocked? Is there any other ticket that needs to be tackled first?

**Comment by sydb** [comment]
Oh boy. I honestly don’t remember, but my bet would be I did not want to change (4) until the [Stylesheets were fixed](/TEIC/Stylesheets/issues/526), but they have been, at least for the XHTML. (Apparently @martindholmes is going to check on the ePub and PDF before closing that ticket.) So let’s unblock.

**Comment by sydb** [comment]
Re-open if Mr. Jenkins complains.
