### ISSUE TITLE
Add <stage> to att.written

### ISSUE THREAD

**Issue by JanelleJenstad** [TEIC/TEI#2197]
The @hand attribute (att.written) is intended to "indicate the hand in which the content of an element was written in the source being transcribed." For transcriptions [originally, I wrote "sourceDoc-like transcriptions," which was misleading] members of att.written include att.transcriptional elements such as `add`, `del`, `subst` and so on; for correspondence, structural elements such as `postscript`, `salute`, and `signed` are members. But although manuscripts of dramatic texts are often the work of multiple scribes, none of the elements commonly used in drama encoding are members of att.written. We would like to see at least `stage`added to att.written to handle the most straightforward cases of MS dramas written in multiple hands. (We would welcome use cases of `sp`, `speaker`, `head`, `lg` and `l` being written in a second hand but haven't stumbled across any examples in the corpus yet.)

It would be useful generally (not just to us) to have the hand attribute on `stage` in particular because stage directions are frequently added in another hand: by the bookkeeper using an authorial ms as a prompt copy, by a copyist after seeing a play in performance, by a director making notes, and by stage managers who record actual performance actions. In other words, `stage` is a structural element that often functions in a stand-off sort of way.

USE CASE 1:
The Douai Manuscript MS787 is described by Line Cottegnies, the lead of the Douai Shakespeare project, in the journal of la Société Française Shakespeare (SFS): https://journals.openedition.org/shakespeare/4289.

See especially the image at https://journals.openedition.org/shakespeare/docannexe/image/4289/img-2.jpg, where one can see the stage direction [Enter Romeo written in the right margin in a different hand.

USE CASE 2:
In this leaf from the ms of Sir Thomas More, a play written in at least four different hands by different authors (including Shakespeare), the stage direction "Enter Fishmonger" is written in a different hand and enclosed in a rhomboid.

![STM_SD](https://user-images.githubusercontent.com/5943608/137219133-051a2136-ecc8-4e5e-9591-d849ec7f07c3.png)

![Douai_RomSD](https://user-images.githubusercontent.com/5943608/137219152-8e357f70-2cdb-433c-94e8-b5b1b846abcc.jpg)

.

**Comment by sydb** [comment]
I find the “stage operates in a stand-offish way” argument all but completely compelling. This argument suggests that in some cases use of the current `<handShift>` method can be confusing, at least if used without extreme care.
But even without that argument, the convenience argument (that stage directions are obvious logical structures that are often in a different hand — This argument says essentially that yes, these _can_ be encoded with the current `<handShift>` method, but use of `@hand` is a lot easier on encoders) is enough to make me agree that this is a good idea.
So barring a good argument against, I am solidly in favor.

**Comment by lb42** [comment]
If they are logical structures, which I believe indeed they are, then `stage` has no place within a `<sourceDoc>` encoding, imffho. Otherwise you are opening the door to all sorts of madness.

**Comment by ebeshero** [comment]
Here's the trouble, @lb42 : `<handShift/>` as a milestone element is clumsy for the application @JanelleJenstad describes. from the note posted on the `<handShift/>` spec: "Like other milestone elements, it should appear at the point of transition from some other state to the state which it describes." So, it makes sense when you've got a situation when there's a clear moment of transition. The issue described here is also likely shared for lots of documents, like, for example a pile of forms/ account books, as well as drama manuscripts--I think we want to be thinking a little more expansively even than the drama. Think of situations in which a particular hand is assigned to make a sweeping *sequence* of edits to a large and complicated document.

`att.written` is applied to `<opener>`, `<closer>`, `<head>`, `<salute>`, I notice. I think the application Janelle describes is consistent with these semantically--but I suspect we will also want to add some other elements from the drama to `att.written` as well. What about `<sp>`? I don't mean that to stall this ticket, by the way--jsut that it seems odd that att.written is applied at the moment in epistolary contexts only when we've clearly got other applications for it.

**Comment by ebeshero** [comment]
Here's the trouble, @lb42 : `<handShift/>` as a milestone element is clumsy for the application @JanelleJenstad presents. From the note posted on the `<handShift/>` spec: "Like other milestone elements, it should appear at the point of transition from some other state to the state which it describes." So, `<handShift/>` makes sense when you've got a situation when there's a clear moment of transition. The issue described here is a lot bigger: It would be easier for processing to pick up all the elements that share an `@hand` value than to go digging for child:: or sibling:: or descendant::handShift elements. 

I think @JanelleJenstad's scenario is also likely shared for lots of documents, like, for example a pile of forms/ account books, as well as drama manuscripts--I think we want to be thinking a little more expansively even than the drama. Think of situations in which a particular hand is assigned to make a sweeping *sequence* of edits to a large and complicated document.

`att.written` is applied to `<opener>`, `<closer>`, `<head>`, `<salute>`, I notice. I think the application Janelle describes is consistent with these semantically--but I suspect we will also want to add some other elements from the drama to `att.written` as well. What about `<sp>`? I don't mean that to stall this ticket, by the way--just that it seems odd that att.written is applied at the moment in epistolary contexts only when we've clearly got other applications for it.

**Comment by lb42** [comment]
Here's the trouble @ebeshero: deciding that some stretch of writing is a stage direction rather than (say) a different speech, or an unrelated gloss, or anything else, really,  -- all belongs to a different interpretive level from that for which sourceDoc is conceived: lines and blocks of writing. However, if the proposal is simply to allow for @hand on (say) `<line>` or `<zone>` I have no objection at all.

**Comment by martindholmes** [comment]
@lb42 @sydb I agree that there are many other elements which should plausibly belong to att.written, but generally we act on feature requests like this based on the real examples presented, and wait for other requests to appear in future with real use-cases. It might be worth raising another ticket for a group of people to survey the community and put together a list of candidates, but meanwhile I think we should just deal with this specific case. (Full disclosure: I do have a vested interest -- we have documents which aren't valid against tei_all until this goes through.)

**Comment by martindholmes** [comment]
And @lb42 : Our documents are not using sourceDoc, they're using text elements.

**Comment by lb42** [comment]
In which case, @martindholmes, you don't have any problem at all (but why not, btw, use @resp ?).

**Comment by ebeshero** [comment]
Yikes, @lb42 I don't think we want to exemplifying `@resp` in that way, when it's designed to indicate the responsibility of the encoding editor. See https://tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHHR .

**Comment by lb42** [comment]
Hmm, @ebeshero, the very first example I see when following that link shows @resp being used to indicate that Fredson Bowers (that well known encoder) is responsible for a reading...

**Comment by ebeshero** [comment]
...but that's still not the situation described here, in which we see evidence of a persistent hand encoding a big set of stage directions. The person who hand wrote the stage directions wasn't making an editorial decision that the document they were reading contains a stage direction at this point.

**Comment by lb42** [comment]
No, if this is a `<sourceDoc>`, what we see is evidence of a persistent hand writing some parts (lines/zones), and (I assume) another hand writing the other bits.  
Just add zone and line to att.written and the original usecase is satisfied methinks. Or stop using sourceDoc to encode interpretative structures.

**Comment by ebeshero** [comment]
`<zone>` and `<line>` are members of att.written, which now *also* contains so much more than `<sourceDoc>` elements that it doesn't really make much sense not to add `<stage>` alongside `<text>`, `<div>`, `<p>`, `<ab>`, and `<closer>` among others.

**Comment by martindholmes** [comment]
@lb42 I don't know why you're fixated on sourceDoc. This is regular manuscript, encoded in a text element, where multiple hands participated and one in particular wrote in the stage directions. It was an original contributor to the source, not a modern editor, and `@resp` is completely inappropriate. We want to "point to a handNote element describing the hand considered responsible for the content of the element concerned," that being the purpose of `@hand`.

**Comment by lb42** [comment]
I don't think I am fixated, but I may well have been paying too much attention to the phrase "For sourceDoc-type transcriptions...." in the OP, which I took to mean that use of sourceDoc was being proposed. If it's not, I'll go back to sleep happily.

**Comment by martindholmes** [comment]
The full sentence was "For sourceDoc-type transcriptions, members of att.written include att.transcriptional elements such as add, del, subst and so on; for correspondence, structural elements such as postscript, salute, and signed are members." I think @JanelleJenstad was just setting the stage generally before going on to talk about drama, and in particular the stage element, which is at issue here, and most likely would never be used in sourceDoc.

**Comment by lb42** [comment]
zzzzz

**Comment by JanelleJenstad** [comment]
To confirm (not that I want to wake a sleeping @lb42), the editors are definitely not using `<sourceDoc>`.  My apologies for my misleading scene-setting! 

> att.written is applied to `<opener>`, `<closer>`, `<head>`, `<salute>`, I notice. I think the application Janelle describes is consistent with these semantically--but I suspect we will also want to add some other elements from the drama to att.written as well. What about `<sp>`? I don't mean that to stall this ticket, by the way--just that it seems odd that att.written is applied at the moment in epistolary contexts only when we've clearly got other applications for it.

I'm very much in agreement with @ebeshero that it's weird that epistolary tags are members of att.written. I'd like to extend the logic of the folks who saw the need for `@hand` on epistolary tags.

(BTW, Fredson Bowers would have loved TEI.)

**Comment by martindholmes** [comment]
@JanelleJenstad @ebeshero Any sign of progress on this ticket? It says "needs discussion" but it's had heavy discussion above, and I don't think there's any serious objection to it; @lb42's objection was based on a misunderstanding about what was being proposed. If there is a real objection, could we hear it, and if not, could this ticket just be completed?

**Comment by JanelleJenstad** [comment]
I'm going to do the work for this ticket this weekend, unless there are objections.

**Comment by ebeshero** [comment]
@JanelleJenstad I'm going through tickets for the milestone since we're about to go into Refrigeration. We can try to knock this out today, but if we run into complications in testing/building, we'll punt to the next release, okay? I think we can get this through, though.
