### ISSUE TITLE
LoC IDNO out of date in Author example

### ISSUE THREAD

**Issue by MegJBrown** [TEIC/TEI#2198]
In the examples for <gi>author</gi>, the URL for the LoC Name Authority File leads to a dead link and should be fixed?

  Erroneous link: http://id.loc.gov/authorites/names/n50012763.html

**Comment by sydb** [comment]
Assigning to @bleekere, as soon as she is eligible.

**Comment by joewiz** [comment]
The URL contains a typo - `authorites` should be `authorities`. The correct link is:

https://id.loc.gov/authorities/names/n50012763.html
