### ISSUE TITLE
Left references to Sourceforge

### ISSUE THREAD

**Issue by rettinghaus** [TEIC/TEI#2206]
There are some outdated references to Sourceforge left in the Guidelines files, e.g. 
https://github.com/TEIC/TEI/blob/25fb6349bc072924fd6f9c53f44edbf1d1a52e5f/P5/Source/Guidelines/index.xml#L21

I think these should be removed completely and/or replaced by the proper links to the GitHub repo.

**Comment by sydb** [comment]
Good catch.

**Comment by bleekere** [comment]
Removed reference to Sourceforge in [TEI/P5/Source/Guidelines/index.xml](https://github.com/TEIC/TEI/blob/25fb6349bc072924fd6f9c53f44edbf1d1a52e5f/P5/Source/Guidelines/index.xml#L21) and updated the file with references to the TEI Github repo. See #d72e7f4ac. The other references to Sourceforge in the Guidelines files are in comments; after consultation with @sydb and @HelenaSabel we decided to leave these references in the comments.
