### ISSUE TITLE
inconsistencies between `<ptr>` and `<ref>`

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2210]
The specification for `<ptr>` has `<remarks>` that are not mirrored in `<ref>` (either they both should have the remarks, or neither should).
The `<sch:report>`s in the two elements are there for identical reasons, but their content is not identical. (It should be.)

**Comment by sabineseifert** [comment]
Do I understand correctly that there are only these two changes needed, @sydb?

1. Just add the `note` from `ref` to `ptr` ("The target and cRef attributes are mutually exclusive.")
2. Correct in `ref` the content of `sch:report` from "Only one of the attributes @target' and @cRef' ..." to "Only one of the attributes @target and @cRef ..."

**Comment by sydb** [comment]
Yes.
1. The `<remarks>` (aka “note”) should be copied from `<ref>` to `<ptr>`.
2. The `<sch:report>` should (IMHO) be copied from `<ptr>` to `<ref>`.

(Well, lots of other changes _may_ be needed, but none for _this_ ticket! :smile: )
