### ISSUE TITLE
figure element in model.titlepagePart class?

### ISSUE THREAD

**Issue by nakagawanatuko** [TEIC/TEI#2228]
Hi,

We are translating the guideline (chapter 4) into Japanese and got a question.
In the following description from 4.6, it is inferrable that the figure element is included in the model.titlepagePart class, which apparently is not the case.

Together with the [figure](https://tei-c.org/release/doc/tei-p5-doc/ja/html/ref-figure.html) element described in chapter [14 Tables, Formulæ, Graphics, and Notated Music](https://tei-c.org/release/doc/tei-p5-doc/ja/html/FT.html), these elements constitute the [model.titlepagePart](https://tei-c.org/release/doc/tei-p5-doc/ja/html/ref-model.titlepagePart.html) class.

Do we miss something?
Thanks in advance.

-Natsuko

**Comment by raffazizzi** [comment]
@nakagawanatuko that is correct, neither `figure` or `titlePage` are members of `model.titlepagePart`. We will need to update the Guidelines to rectify this error. Thank you for letting us know!

**Comment by nakagawanatuko** [comment]
@raffazizzi Thank you! We will fix the Japanese translation.
