### ISSUE TITLE
Recent change is breaking deletion of constraintSpecs

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2231]
We have this in our ODD file, allowing us to nest ab elements:

~~~~~
<!--MAJOR DEPARTURE: NESTED AB-->
                  <elementSpec ident="ab" mode="change" module="linking">
                     <desc xml:lang="en" versionDate="2021-07-21">(anonymous block) contains any arbitrary component-level unit of text, acting as an anonymous container for phrase or inter level elements analogous to, but without the semantic baggage of, a paragraph.</desc>
                     <content autoPrefix="true">
                        <alternate minOccurs="1" maxOccurs="unbounded">
                           <macroRef key="macro.paraContent"/>
                           <elementRef key="ab" minOccurs="1" maxOccurs="1"/>
                        </alternate>
                     </content>
                     <constraintSpec ident="abstractModel-structure-ab"
                                     scheme="schematron"
                                     mode="delete"/>
                  </elementSpec>
~~~~~

The Schematron rule was successfully being deleted prior to recent changes relating to unique ids. The id of the constraintSpec has not changed, but the deletion no longer works. Assigning this to @sydb because he made the changes and will probably be able to figure out immediately what's happening. This is using the bleeding-edge plugin latest build, which is Stylesheets-dev plus TEI-dev.

**Comment by sydb** [comment]
Not only can I not figure out immediately what is happening, I cannot even reproduce what is happening.
You are using Stylesheets dev branch and TEI dev branch to convert your ODD into what output format? (I am guessing RELAX NG, since there is no built-in transformation in oXygen to convert to Schematron.)
Can we talk (with screen share) sometime soon, @martindholmes ?

**Comment by sydb** [comment]
[Test file](https://github.com/TEIC/TEI/files/8092752/MH.odd.txt) with “.txt” appended to appease GitHub.

**Comment by martindholmes** [comment]
@sydb We transform to RNG and extract the Schematron and generate XSLT from it. It's been working fine for a couple of years, but with the latest update to the Oxygen bleeding-edge plugin, the constraintSpec stopped being deleted so our files because invalid. Heading into a meeting now, unfortunately.

**Comment by sydb** [comment]
Check. (I did not mean “soon” as in minutes to hours, but rather hours to days. :-)

**Comment by martindholmes** [comment]
I wonder if the p5subset.xml in the Stylesheets got updated after the merge of the constraintSpec changes...

**Comment by martindholmes** [comment]
With @sydb figured this out: the ident had changed. Now deleting both the old and the new ident so that it'll work whether a brand new p5subset is used or not.
