### ISSUE TITLE
pb, lb, cb gloss/desc not updated in all languages

### ISSUE THREAD

**Issue by matgille** [TEIC/TEI#2241]
[Related to #1529]

In #1529 a modification has been suggested for the gloss of [`pb`](https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/pb.xml), [`cb`](https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/cb.xml) and [`lb`](https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/lb.xml) elements to make clear those elements indicate the *beginning* of new objects (page, line, column, gathering). Commit 5386faec1ef08f6b78 rephrases the english glosses accordingly, changing `break` to `beggining` where it is needed. 

However, this modification has not been made in all translations (for French and Spanish, the ones I speak). To sum up: 

### Gloss
- in the specs `pb.xml` reads  `<gloss versionDate="2009-01-06" xml:lang="fr">saut de page</gloss>`; I suggest `début de page`
- `cb.xml` reads `<gloss versionDate="2009-01-06" xml:lang="fr">saut de colonne</gloss>`; item: `début de colonne`
- `lb.xml` reads `<gloss versionDate="2009-01-06" xml:lang="fr">saut de ligne</gloss>`; item: `début de ligne`

### Desc
Nothing to change. 

### Gloss
Gloss elements have to be updated for the three elements. I can suggest something later in the week

### Desc
Desc element have to be updated for `cb` and `pb` elements. Same. 

## Italian translation

I reckon the glosses of the three elements and desc for two of them (`cb` and `pb`) have to be changed too, but I don't speak Italian and it needs confirmation. 

---

There is no translation for tei:gb elements. I can open another issue and suggest translations in French and Spanish !

Best,

Matthias

**Comment by sabineseifert** [comment]
Created branch and PR with updated glosses in French as suggested above.

@matgille Thank you for the suggestions! Please provide Spanish translations for glosses and also translations for `gb`.

**Comment by ebeshero** [comment]
@sabineseifert I suspect that @HelenaSabel can quickly provide the Spanish translations here! And @raffazizzi can supply the Italian!

**Comment by HelenaSabel** [comment]
Thanks for the mention, @ebeshero !

The glosses can be translated into Spanish as follows:

- `pb` = inicio de página
- `cb` = inicio de columna
- `lb` = inicio de línea

@sabineseifert When you do the PR of this, can you add me as a reviewer? I could take a look at the `<desc>` elements then to suggest an improvement/update of the Spanish translation.

**Comment by sabineseifert** [comment]
Thanks, @HelenaSabel, for the translations. I just added them to the PR #2288.

It would be great if you could have a look at the Spanish descriptions.
And @raffazizzi, it would be great if you could have a look at the Italian glosses and descriptions.

**Comment by sabineseifert** [comment]
Updated glosses and descriptions for French, Spanish and Italian for `lb`, `cb`, `pb`. Did not modify other languages.
