### ISSUE TITLE
textLang should be able to contain bibl

### ISSUE THREAD

**Issue by schassan** [TEIC/TEI#2248]
Unlike e.g. `<bibl>` and `<decoNote>`, `<textLang>` cannot contain `<bibl>` right now. But it is very reasonable that a cataloguer may want to add bibliographical references to the description of the languages used in an object.

I would like to ask to add `<bibl>` to the content model of `<textLang>`, maybe by adding it to `model.biblLike`?

**Comment by martinascholger** [comment]
Council F2F decides to widen the content model to macro.specialPara (like other header elements)
