### ISSUE TITLE
links to `att.interpLike` are broken

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#2270]
in fact, the page is missing in both the current release: https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.interpLike.html 
and the current dev version: https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-att.interpLike.html

Various links are broken, e.g. on the pages:
*  https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/REF-CLASSES-ATTS.html
*  https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/USE.html
*  https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-span.html

That might well be a Stylesheets issue, haven't investigated further.

**Comment by sydb** [comment]
Have you checked for any other missing files, @peterstadler?
The `<classSpec>` and the 4 `<memeberOf>`s that refer to it all make it into p5subset.xml.

I have to step away from computer for ½–2 hours now, but will continue to look at this when I can.

**Comment by peterstadler** [comment]
No, I haven't found any other missing files

**Comment by ebeshero** [comment]
Reviewing [the history of att.interpLike](https://github.com/TEIC/TEI/commits/dev/P5/Source/Specs/att.interpLike.xml), I’m wondering which modification led to it not being processed as a spec page in the build?

**Comment by ebeshero** [comment]
att.interpLike provides `@inst`, and on a quick test, it's available for use in a TEI All file in oXygen, so it's in the schema, but its spec page doesn't get built in the Guidelines.

**Comment by martinascholger** [comment]
It last worked in release [4.1.0](https://tei-c.org/Vault/P5/4.1.0/doc/tei-p5-doc/en/html/ref-att.interpLike.html)

**Comment by martinascholger** [comment]
It has to do with the membership of att.interpLike to att.typed 
```
<classes>
    <memberOf key="att.typed"/>
</classes>
```

**Comment by martinascholger** [comment]
https://github.com/TEIC/TEI/pull/2053

**Comment by martinascholger** [comment]
See also PR https://github.com/TEIC/TEI/pull/2053

**Comment by sydb** [comment]
There are 4 members of att.interpLike: `<(interp|span)(Grp)?>`.
I have tested by removing att.interpLike from att.typed, removing all 4 local-overide definitions of `@type`, and adding all 4 of those elements directly to att.typed.

The good news is that this works: it puts ref-att.interpLike.html back. The bad news is that, of course, it leaves #1844 and #2012 back to square 1.

**Comment by sydb** [comment]
I have no doubt that, despite leaving #1844 and #2012 out to pasture, this is what we should do for the upcoming release. (I am not sure how we word such a regression in the release notes, though. :-)
The question is, do we try to a) do the clever (and probably more correct) process of figuring out how to use git to back out those specific changes, or b) do I just check in what I have already done by hand (after adding a bunch of comments)?

**Comment by sydb** [comment]
My plan is to start working on (b) in a new branch. If someone can figure out how to do it git-wise, we don’t have to merge in my new branch.

**Comment by ebeshero** [comment]
It seems to me that b) is probably less error prone. Yeah, we're reverting a couple of things, but I don't know that we'd want to remove all record that we tried them. We'll probably want to alert people on the original tickets that we needed to undo those changes.

**Comment by JanelleJenstad** [comment]
The original #1844 pointed out that att.interplike had ad hoc definitions of `@type`. Is the plan to revert to the ad hoc definitions? 
I agree that b) is probably the wise path.

**Comment by sydb** [comment]
@JanelleJenstad — I have not tried putting the ad hoc definitions back, yet. (Very busy around here: WWP web server keeps going down.) I am going to try to put them in and kick off a build before dinner (so it can build while I cook :-)

**Comment by sydb** [comment]
@ebeshero — Not as though the information would be completely lost; after all, git is a version control system. But it would be lost _to me_, because I am not that facile with git. But given that 2 of us now lean towards (b), I am going at it …

**Comment by sydb** [comment]
I have pushed _a_ solution to the new 'issue_2270_revert_2012_1844' branch. I have not issued a PR yet, as I may want to try a few tweaks, first. In the meantime, anyone and everyone should please check this branch out, make sure the build works, and check that the 5 involved tagdocs (`att.interpLike`, `<interp>`, `<interpGrp>`, `<span>`, and `<spanGrp>`) look right.

**Comment by martinascholger** [comment]
looks good to me

**Comment by sydb** [comment]
Thanks, @martinascholger. I am planning to work on this more (and probably submit PR) later this morning.
