### ISSUE TITLE
Nabble TEI-L Archive No Longer Exists

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#2275]
Vanished in a puff of server costs, the Nabble TEI-L archive no longer exists. 

This is mentioned on https://tei-c.org/support/#tei-l and should be removed. There is also a separate mirror on MarkMail at https://markmail.org/list/edu.brown.listserv.tei-l which presumably will break if/when the TEI-L mailing list moves to lists.tei-c.org but might be worth recording there instead of the Nabble one.

**Comment by sydb** [comment]
@bleekere and I have assigned to @martinascholger to get this into the hands of the webmaster.

**Comment by martinascholger** [comment]
Fixed
