### ISSUE TITLE
simplePrint needs to be updated for missing charName and glyphName

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2283]
The simplePrint documentation:

https://tei-c.org/release/doc/tei-p5-exemplars/html/tei_simplePrint.doc.html

shows 

```
UNKNOWN ELEMENT charName
UNKNOWN ELEMENT glyphName
```

presumably because the ODD file hasn't been fully updated to take account of the removal of those two elements in the 4.4.0 release.

**Comment by bleekere** [comment]
Removed the charName and glyphName elements from the charDecl in the tei_simplePrint odd file, cf. #2313
