### ISSUE TITLE
jTEI ODD invalidity

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2289]
Validating the file P5/Exemplars/tei_jtei.odd yields the following error.

> The @ident of 'constraintSpec' should be unique; this one (jtei.sch-att) is the same as that of a previous 'constraintSpec'.

I am pretty confident the `@ident` on [line 3066](https://github.com/TEIC/TEI/blob/94a2bcbee4b339759d394838622e0c7be26968f4/P5/Exemplars/tei_jtei.odd#L3066) should be "jtei.sch-val" (instead of "jtei.sch-att").

**Comment by martindholmes** [comment]
@sydb Definitely -- just change the ident to jtei.sch-val.
