### ISSUE TITLE
Manuscript encoding

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#23]
Henrik Ibsen's Writings has made several changes and 
additions to the TEI DTDs regarding the encoding of 
manuscript changes and manuscript phenomena. In the 
following we wish to present some of the modifications 
and encourage the inclusion of these themes in the P5 
revision discussion. 

\- &lt;clarification&gt;

We've created a new element to record the clarification 
phenomenon in manuscripts. Ibsen and his copyists some 
times clarify words or letters either writing upon the 
already written word/letters or by repeating the 
word/letters offline. We encode these instances of 
repeating the same for the purpose of clarification, like 
this:

&lt;clarification hand="HI" 
place="inline"&gt;Henrik&lt;/clarification&gt;
&lt;clarification hand="HI" 
place="offline"&gt;Henrik&lt;/clarification&gt;

We believe this is a well known phenomenon for 
manuscript transcribers, and we think it would be a 
useful addition in a revised chapter on "Transcription of 
Primary Sources".

\- TEI elements for manuscript changes

We've made it possible to include almost all kinds of 
elements in &lt;app&gt; (i.e. in &lt;lem&gt;/&lt;rdg&gt; of course), 
&lt;add&gt;, &lt;del&gt; etc. and to use &lt;app&gt;, &lt;add&gt;, &lt;del&gt;, 
&lt;gap/&gt; etc. almost globally in our manuscript 
transcriptions in order to record manuscript changes in a 
way that reflects our view of the changes. E.g. we allow 
&lt;div&gt; inside &lt;add&gt; and &lt;del&gt; to make possible the 
inclusion or deletion of a complete scene, thus reflecting 
the change in the document structure more clearly.

\- The hand attribute

We have allowed the hand attribute in &lt;app&gt;, &lt;hi&gt; and 
&lt;emph&gt;. Including hand in &lt;app&gt; makes it unnecessary 
to use hand both in &lt;add&gt; and &lt;del&gt; when another 
hand has revised the text of the manuscript. Using the 
hand attribute in &lt;hi&gt; (and similarly in &lt;emph&gt;) allows 
us to record e.g. the red pencil underlining throughout a 
manuscript otherwise written in black ink.

\- A new element for substitutions/revision of the &lt;app&gt; 
element

The last years there have been discussions on the TEI-L 
and elsewhere of the need to modify and revise the 
&lt;app&gt; element to make it more useful for manuscript 
changes. Several alternatives have been discussed. At 
Henrik Ibsen's Writings we have also discussed this, and 
although we have managed to use the excisting &lt;app&gt; 
element for the manuscript changes in our material 
(though with some modifications of what &lt;lem&gt; and 
&lt;rdg&gt; can contain and the inclusion of some attributes), 
we would like to encourage the expansion of this part of 
the chapter on "Transcription of Primary Sources", at 
least an element for encoding substitutions should be 
included. We dislike the double role of the &lt;app&gt; 
structure, and would feel better having one structure for 
manuscript changes and one for the critical apparatus. 
Our use of the &lt;app&gt; element for manuscript changes 
has resulted in us constructing a new element, &lt;tcApp&gt;, 
for our critical apparatus and text critical notes.

Please contact Hilde Bře (hilde.boe@ibsen.uio.no) at 
Henrik Ibsen's Writings, if you have any questions or 
remarks.

Original comment by: sf_user_hildeboe

**Comment by cthomasdta** [comment]
> 3. make the `@hand` attribute available on `<app>`, `<hi>`, and `<emph>`

This seems not to have happened, at least in [`<emph>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-emph.html) `@hand` is not allowed. Will I open a new issue? (I stumbled upon this while checking if an issue "Allow `@hand` in `<emph>`" does already exist).
