### ISSUE TITLE
Reference to the nabble TEI-L web archives fails (dead link)

### ISSUE THREAD

**Issue by bansp** [TEIC/TEI#2304]
Wanted to browse the list archives, went to https://tei-c.org/support/#tei-l and tried to go to http://tei-l.970651.n3.nabble.com/ (labelled "in the Nabble archive]"), but failed to resolve the link.

**Comment by GVogeler** [comment]
To be replaced by https://tei-l.markmail.org ?

**Comment by GVogeler** [comment]
duplicate to #2275

**Comment by raffazizzi** [comment]
Closing as duplicate
