### ISSUE TITLE
teidata.unboundedInt should be named teidata.unboundedCount

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2327]
The datatype for a counting number (i.e., a non-negative integer) is teidata.count. The datatype for a counting number that could also have the value "unbounded" is teidata.unboundedInt.

- Whereas it is not an xs:Int plus "unbounded", as xs:Ints are limited to a max value of ±2^31;
- Whereas it is not an xs:integer plus "unbounded", because it cannot be negative;
- Whereas it **is** an xs:nonNegativeInteger plus "unbounded";
- And whereas we already call an xs:nonNegativeInteger a teidata.count;
- Henceforth we should refer to it as a teidata.unboundedCount.

Note that this datatype is only used in the definition of `@maxOccurs`.

**Comment by martinascholger** [comment]
Release team thinks this is done and can be closed. @sydb please feel free to reopen if this is not the case.
