### ISSUE TITLE
relationship of `@hand` and `<handShift>` should be explicit

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2338]
Council feels that the language in 11.3.2.1 “Document Hands” should be made clearer, particularly to guide users who want to express the “most of this is in hand A, but this bit is in hand B”, and folks writing processors that might encounter both `@hand` and `<handShift/>`.

**Comment by raffazizzi** [comment]
```xml
<p hand="#one">
This paragraph is mostly in hand "one", but I ran out of ink and <handShift hand="#two"/> finished with a different pen.
</p>
```
