### ISSUE TITLE
someway of recording the identity of the person who created the transcription

### ISSUE THREAD

**Issue by casglur** [TEIC/TEI#2349]
Our project wants to recognise and record the contribution of the staff who were involved in creating transcriptions of manuscript material. The current TEI editor tag does not seem to fit this use and we don't want to abuse its use. Is there a way to record the details of the person who created the XML transcript, if not could we perhaps add a new tag?

<transcriber>Joe Bloggs</transcriber>

Best wishes
Alexander

**Comment by lb42** [comment]
RespStmt is what most people use

**Comment by casglur** [comment]
Fantastic, thanks for the quick reply.

Best wishes
Alexander
