### ISSUE TITLE
"quoted" not reflected in Guidelines

### ISSUE THREAD

**Issue by rettinghaus** [TEIC/TEI#2356]
In `teidata.language` we use `<quote rend="quoted">` which is not (visually) reflected in the Guidelines. 

I'd propose to either add rules for `.quoted` in the CSS or drop the single appearance of this `@rend` attribute.

**Comment by trishaoconnor** [comment]
With @sydb, fixed issue by deleting `@rend` from `<quote>` in teidata.language.
