### ISSUE TITLE
Watermarks reference

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#2372]
At https://tei-c.org/release/doc/tei-p5-doc/ja/html/MS.html#msph1sup and elsewhere there is an example which makes reference to an example watermark "Moschin, Anchor N 1680". This is almost certainly meant to be a reference to  a tome catalogued in the Bodleian as  follows:

Mošin, Vladimir A. Anchor Watermarks. Amsterdam: Paper Publications Society (Labarre Foundation), 1973. Print. Monumenta Chartæ Papyraceæ Historiam Illustrantia ; 13.

The present romanisation is unnecessary, and needlessly confuses the reader. At the least, it should be changed to "Mošin".

**Comment by ebeshero** [comment]
I'm self-assigning to update this quickly today. :-)

**Comment by ebeshero** [comment]
Completed with https://github.com/TEIC/TEI/commit/0e38e3bc43d34a5f5650209aacc1b67fc09caaed .
