### ISSUE TITLE
classRef/@include and classRef/@except should be mutual exclusive

### ISSUE THREAD

**Issue by dmj** [TEIC/TEI#2379]
A classRef element may have an @‍include attribute that supplies a list of class members which are to be included in the schema being defined. 

A classRef element may have an @‍except attribute supplies that a list of class members which are to be excluded from the schema being defined. 

I think they should be mutual exclusive just like the same attributes on moduleRef.

**Comment by sydb** [comment]
They are.

**Comment by dmj** [comment]
Right, they are. Misread the content model. Sorry for the noise.

**Comment by sydb** [comment]
No worries!
