### ISSUE TITLE
Consideration of eventName element?

### ISSUE THREAD

**Issue by djakacki** [TEIC/TEI#2382]
Respectfully, I would like to ask the Council to consider the value of creating the eventName element. Increasingly, the work I'm doing on historical performance and business events (sorry ...) calls out for an eventName tag that would provide parity with named people, places, organization as connected together in a time or time span through a named occurrence. I hope I'm not the only one (and suspect I'm not).

In 2021 there was a back-and-forth on the listserv about its value: 

- https://listserv.brown.edu/cgi-bin/wa?A2=ind2103&L=TEI-L&P=R8274
- https://listserv.brown.edu/cgi-bin/wa?A2=ind1706&L=TEI-L&P=R20066

Note that in one of Torsten Schassan's contributions to that thread he calls upon us "for the sake of completeness and in analogy to other cases, there might be the need to introduce another element to the TEI, <eventName>." and then goes on to provide considerations.

Here is a (particularly gnarly and complex) example (but indicative of the kind of work that I think would benefit from the addition of eventName):
@JanelleJenstad may be happy to see this excerpt from Stow - it's from REED London and sitting in LEAF-Writer, so I've stripped out the @refs for readability sake (and with apologies in advance for tag abuse). In this particular case there are three named events within the text: the marriage, the feast, and the masque. 

`<ab>The <date when="1613-12-26" cert="high">26. of December, 1613</date> <persName key="Carr, Robert" cert="high" type="real">Robert earle of Somerset</persName> married the lady
            <persName key="Howard, Frances" cert="high" type="real">Francis Howard</persName> daughter to ye <persName key="Howard, Thomas" cert="high" type="real">earle of Suffolke</persName> <gap reason="omitted"/> &amp; vpon <date when="1614-01-04" cert="high">Tewsday the 4. of
               Ianuary</date>, the Bride, &amp; Bridegroome, being accompanied w<ex>i</ex>t<ex>h</ex> the <persName key="Stuart, Esmé" cert="high" type="real">duke of Lenox</persName>,
            the <persName key="Howard, Henry" cert="high" type="real">Lord priuie Seale</persName>, the <persName key="Howard, Thomas" cert="high" type="real">lord Chamberlayne</persName>, the <persName key="Somerset, Edward" cert="high" type="real">earles of Worcester</persName>, <persName key="Herbert, William" cert="high" type="real">Pembroke</persName>,
            <persName key="Herbert, Philip" cert="high" type="real">Montgomery</persName>, &amp; others, and with many honorable Barons, knights, &amp; gentlemen
            of qualitie, came to <placeName key="Merchant Taylors’ Hall" role="placeEntertainment" type="hall" cert="high">marchant-taylers hall</placeName>, where the Lord Maior, &amp;
            Aldermenne, of London, in their Scarlet robes, entertayned them with hearty
            welcome, &amp; feasted them with all magnificence: <gap reason="omitted"/> &amp; about 3. a clock in
            the morning they returned to <placeName key="Whitehall Palace" role="placeEntertainment" type="palace" cert="high">white hall,</placeName> and vppon twelfe night there was a maske
            of gentlemen of Grayes Inne<gap reason="omitted"/>.</ab>
`

Thank you for your consideration!

**Comment by JanelleJenstad** [comment]
Thanks for making a ticket @djakacki. The TEI-L discussions point out the obvious parallels with `<persName>` and cognate elements. All but one contributor to the threads were in favour of creating `<eventName>`. 
Council: Can we get this done for the next release?

**Comment by sydb** [comment]
I daresay no, @JanelleJenstad, we cannot do even a halfway decent job before upcoming release, especially as this is still flagged “needs discussion”. But if we want to get it into the Fall release, we should start poking at this soon.

I am not remotely convinced that `<eventName>` is a good idea (nor am I convinced it is a bad idea),[1] but there seems to be enough support for it that we may as well start moving along. (I.e., I expect that if I end up against the idea, I would be outvoted anyway.)

So the steps involved, at first blush, would be:

- Figuring out where in chapter 13 we would introduce & discuss this new element,  
- and write the new prose, including an example.
- Figure out what other parts of ND need to be re-written,
- and alter them.
- Write new tagdoc for `<eventName>`, including an example,
- and remember to include it (via `<xi:include>`) in ND.
- Change content model of `<event>` so that `<eventName>` can appear.
- Find places that exemplify other encoding that would now use `<eventName>`, including examples of `event/head` and `event/label`, and consider changing them. 

@djakacki — as I am close to illiterate, let alone an English scholar, I am afraid it is not clear to me what words or passages in that quotation would be marked `<eventName>` if there were such an element.

**Notes**
[1] On the pro side, I think Torsten Schassan’s 2017-06-07 analysis is spot on. On the con side, `<name type="event">` _does_ fill that “missing” role, and I disagree with Eduard Drenth’s assertion that use of a generic element complicates things, or at least that it complicates them much.

**Comment by skurzinz** [comment]
Many thanks @djakacki for bringing this up (again)!

> [1] On the pro side, I think Torsten Schassan’s 2017-06-07 analysis is spot on. On the con side, `<name type="event">` _does_ fill that “missing” role, and I disagree with Eduard Drenth’s assertion that use of a generic element complicates things, or at least that it complicates them much.

@sydb This is only true for in-text encoding, and not for a `standOff/listEvent/event/` *ography* setting. 

So in an attempt to align `<event>` with `<person>`, `<org>`, `<place>` I would once more argue in favour of `<eventName>`, much in line with what @ChristianeFritze, @helmutwklug, Christoph Steindl and I suggested at TEI 2019 in Graz (https://zenodo.org/record/3447298). 

I sat down and once more went through the `event`-related issues here and my notes from our discussion. Should we create a separate meta-issue for the discussion or is this the right place?

**Comment by skurzinz** [comment]
> In this particular case there are three named events within the text: the marriage, the feast, and the masque.

@djakacki like @sydb I struggled to find the named events in the example (`<eventName>maske</eventName>`?). 

A made-up example: 

```
<text><body><p>
     On <date when="1719-03-19">Monday</date>, <rs type="person">she</rs> was writing about the 
<eventName ref="#SecondDefPrague">1618 Defenestration of Prague</eventName> which initiated the 
<rs type="event" ref="#ThirtyYearsWar">Thirty Years’ War</rs>.
  </p></body></text>
   <standOff>
      <listEvent>
         <event when="1618-05-23" xml:id="SecondDefPrague">
            <eventName>1618 Defenestration of Prague</eventName>
            <idno>https://www.wikidata.org/wiki/Q13365740</idno>
         </event>
         <event from="1618" to="1648" xml:id="ThirtyYearsWar">
            <eventName>Thirty Years’ War</eventName>
            <idno>https://www.wikidata.org/wiki/Q2487</idno>
               <event when="1623" xml:id="SomeSubevent">
                  <eventName>The Battle of X</eventName>
               </event>
         </event>
      </listEvent>
      <listPerson>
         <personGrp/>
         <!-- the personnage who was defenestrated, linked or ptr to -->
      </listPerson>
   </standOff>
```

**Comment by skurzinz** [comment]
Reviewing ND it becomes clear that we have to differenciate between what an `<eventName>` is as compared to a `<head>` or `<label>`. 

My intuition is that `<head>` or `<label>` are pointing to an editorial act, while examples e.g. following https://github.com/TEIC/TEI/blob/bec660a72ce0b288c76daba9d0346717e3abb85a/P5/Source/Guidelines/en/ND-NamesDates.xml#L1922 (where the head/label could be replaced by `eventName`[1]) are more canonical points of reference (which might even have an authority file entry or the like). 

Also, inviting @schassan to join the discussion.

**Note**  
[1] The event-iness of treaties in the examples linked above is debatable, though. Signing-of-treaty *is* an event, with probable preceding discussing-passage-n-of-treaty events, but that’s another story…

**Comment by skurzinz** [comment]
Just to clarify: @ChristianeFritze and I will be meeting on Thursday to discuss my preliminary changes in https://github.com/TEIC/TEI/compare/dev...skurzinz:TEI:dev and draft discussion for TEI-l, hence not yet a pull request.

**Comment by skurzinz** [comment]
Just for reference I am adding the follow-up issue #2499
