### ISSUE TITLE
attr specification in description?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2387]
While working on #2298 @trishaoconnor and I noticed that the descriptions of the `@org` attribute of the `<attList>` element each contain the strings “(org="group")” and “(org="choice")”. (Except that the Korean has only 1 of them.)

1. They should not be plain text. We encode such things.
2. Quite incorrectly (IMHO), some translations include translation of the "group" and "choice"  _values_ of `@org`.
4. More importantly, they should not be there at all: in no other `<desc>` in the _Guidlines_ do we show an attribute-value pair like that.
3. Furthermore, the use of `<desc>` vs use of `<gloss>` for the _values_ of `@org` need to be reconsidered.

**Comment by martinascholger** [comment]
I think no discussion is needed here - I greenlight this. Is this something for the mentoring session, @trishaoconnor and @sydb? Feel free to re-assign.

**Comment by trishaoconnor** [comment]
Change approved and translations updated by @HelenaSabel and @raffazizzi
