### ISSUE TITLE
Why can't I change an attribute defintion to have an open or semi list?

### ISSUE THREAD

**Issue by hcayless** [TEIC/TEI#2391]
Scenario: I'm working on a project encoding texts and adding placeName, orgName, and persName references. We're developing a set of `@type`s for placeNames and orgNames (e.g. type="building" or "street", etc.). We do not yet have an exhaustive list of the types we want. If redefine `@type` on placeName to be a semi-open list, with the values we've got so far, so encoders will get sensible suggestions for the value of `@type`, I get an error because of the first Schematron rule in https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-attDef.html.

But surely I should be able to do this. It produces a perfectly sensible RNG Schema, which does what I want. Why should this be an error?

**Comment by ebeshero** [comment]
This is mystifying, because the context on one of the Schematron rules sets a context limiting to `@type ` with a closed valList...Is it a different rule causing this problem?

**Comment by hcayless** [comment]
Never mind. I think I was doing something wrong. I was assuming mode should be "replace".
