### ISSUE TITLE
make `<calendar>` a member of att.typed?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2396]
The `<calendar>` element is (obviously) repeatable. And I, for one, can imagine categorizations thereof.
The first that jumps to mind is "fictional" vs "actual" (or some such). But my current use case would be dividing calendar systems up into those that can easily be converted to (proleptic) Gregorian, those that cannot be converted to (proleptic) Gregorian, and those that _might_ be convertable to (proleptic) Gregorian.
I cannot, at the moment, see any reason that `@type` should not be allowed on `<calendar>`.

**Comment by trishaoconnor** [comment]
The att.typed membership is merged into dev. 

Council suggests adding a description in the prose to clarify the purpose of `@type` in `<calendar>`.
@sydb proposes the following description for inclusion into the prose:

```
A <gi>calendar</gi> element may also have a <att>type</att> (and
  <att>subtype</att>) attribute in order to categorize the calendar in
  any convenient way. In the following example, <att>type</att> is
  used to differentiate real calendar systems in actual use from those
  used in a fictional environment.
```

**Comment by sydb** [comment]
I not only suggested it (at @martinascholger’s suggestion on the PR), I committed it to the branch. Thus that prose is already in dev.
