### ISSUE TITLE
Footer on TEI P5 Guidelines where it mentions Version should include text 'P5'

### ISSUE THREAD

**Issue by jamescummings** [TEIC/TEI#2413]
The current footer for TEI Guidelines generated material on the website says: 

> TEI Guidelines [Version](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/AB.html#ABTEI4) [4.6.0](https://www.tei-c.org/release/doc/tei-p5-doc/readme-4.6.0.html). Last updated on 4th April 2023, revision [f18deffba](https://github.com/TEIC/TEI/commit/f18deffba). This page generated on 2023-04-04T17:24:46Z.

With the word 'Version' being a link to information about versions, the version number 4.6.0 being a link to the release note and the revision number being a link to the GitHub Release. 

I suggest that the first bit of text here should be 'TEI P5 Guidelines' for clarity.  

> TEI **P5** Guidelines [Version](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/AB.html#ABTEI4) [4.6.0](https://www.tei-c.org/release/doc/tei-p5-doc/readme-4.6.0.html). Last updated on 4th April 2023, revision [f18deffba](https://github.com/TEIC/TEI/commit/f18deffba). This page generated on 2023-04-04T17:24:46Z.

**Comment by lb42** [comment]
Hoorah! a suggestion for change which I can (a) totally understand (b) totally agree with. 
Make it so, Mr Spock.

**Comment by sydb** [comment]
Pinging @jamescummings or @lb42 (or both) for a review of #2417.
