### ISSUE TITLE
Tite: encoding of lists underspecified; syntactic sugar?

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#242]
Tite gives little guidance on encoding lists that do not include labels and glosses -- that is, ordinary lists using bullets, numbers, or letters.  It says to refer to the TEI Guidelines, but the Guidelines give `@type`='ordered' for both numbered and lettered lists.  It seems uncharacteristic of Tite not to specify a way to distinguish these two different renderings.  Perhaps `@rend` should be recommended?

Since Tite uses &lt;b&gt; and &lt;i&gt; as syntactic sugar to save keystrokes, perhaps the same should be done for &lt;ol&gt; and &lt;ul&gt;?  We would just need to decide how these map to the values of list@type.

Original comment by: @kshawkin

**Comment by kshawkin** [comment]
Oh gosh, I just haven't gotten made time to look at how the TEI does this and see how to accommodate in Tite.  This, along with other tickets, was on hold till I reconciled DTDs with Apex in December 2014 (see [history](http://wiki.tei-c.org/index.php/User:Kshawkin/My_Council_obligations/Plan_for_TEI_Tite)), so in a sense it's only a year and a half old.

**Comment by lb42** [comment]
Please feel free to reopen tjhe ticket when you have a specific proposal to make
