### ISSUE TITLE
roll Tite into TEI P5

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#243]
Lou and Sebastian think it would be a good idea to roll Tite-specific elements into the TEI namespace.  Kevin thinks this would have the extra benefit of not having the TEI maintain two namespaces, which leads those using a Tite schema to need to invent at least one namespace prefix in order to tell the validator where to find the elements.

Original comment by: @kshawkin

**Comment by hcayless** [comment]
Close. Won't Fix.
