### ISSUE TITLE
Prose and elementSpec in contradiction

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2456]
The Dictionaries chapter says this:

"the [re](https://www.tei-c.org/Vault/P5/4.6.0/doc/tei-p5-doc/en/html/ref-re.html) element is defined to contain the same elements as an [entry](https://www.tei-c.org/Vault/P5/4.6.0/doc/tei-p5-doc/en/html/ref-entry.html) element, with the exception that it may not contain any nested [re](https://www.tei-c.org/Vault/P5/4.6.0/doc/tei-p5-doc/en/html/ref-re.html) elements."
https://www.tei-c.org/Vault/P5/4.6.0/doc/tei-p5-doc/en/html/DI.html#DITPRE

But the schema allows nested re elements.

**Comment by laurentromary** [comment]
In the context of [TEI lex 0](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html), we are not using `<re>` anymore but only the (now) recursive `<entry>`. We probably need to align `<re>` in documenting that it can be recursive indeed.

**Comment by sydb** [comment]
Given that `<entry>` is recursive, is `<re>` needed at all anymore; i.e., is it just syntactic sugar for `<entry type="related">`? (It would mean allowing `<entry>` in the content models of `<cit>`, `<dictScrap>`, `<entryFree>`, and `<nym>`, which currently allow `<superEntry>` and `<re>`, but not `<entry>`.

**Comment by laurentromary** [comment]
there is quite some legacy usage of `<re>` and I would not drop it too quickly. But yes, step by step the TEI guidelines could align with TEI Lex 0 and recommend the systematic usage of <entry> (which for us also replaces `<superEntry>`). BTW, we use `type="relatedEntry"`.

**Comment by sydb** [comment]
So my suggested steps are:

1. On this ticket we just fix the prose in #DITPRE, and do nothing else
2. Open a new ticket to depricate then remove `<re>`, with the suggestion that the value "relatedEntry" be used on `<entry>`. (@laurentromary suggests the deprecation period should be a long one, and I see no reason to try to make it short)
3. Open a new ticket to consider depricating `<superEntry>`, too.

**Comment by trishaoconnor** [comment]
- [x] Step 1: Updated the prose in #DITPRE to delete the latter part of the sentence "...with the exception that it may not contain any nested [`<re>`](https://www.tei-c.org/Vault/P5/4.6.0/doc/tei-p5-doc/en/html/ref-re.html) elements." Changes saved directly to dev since it is minor editorial change.
- [x] Step 2: Open a new ticket to depricate then remove `<re>`. (See issue #2487).
- [x] Step 3: Open a new ticket to consider depricating `<superEntry>`, too. (See issue #2488).
