### ISSUE TITLE
Missing text in value description 'MGRS' of geoDecl/@datum

### ISSUE THREAD

**Issue by martinascholger** [TEIC/TEI#2464]
A part of the description for the value 'MGRS' of `@datum` on  `<geoDecl>` (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-geoDecl.html) is missing. 

Currently, it says "(Military Grid Reference System) the values supplied are geospatial entity object codes, based on" 

this should be 

"(Military Grid Reference System) the values supplied are geospatial entity object codes, based on the [UTM](https://www.bluemarblegeo.com/knowledgebase/calculator-2023/Universal_Transverse_Mercator_Special_Coordinate_System.htm) (between 80°S and 84°N latitudes) and UPS (Universal Polar Stereographic) systems."

**Comment by ebeshero** [comment]
@torstenroeder Just marking this ticket "go"! Can probably be completed quickly, yes?

**Comment by ebeshero** [comment]
Looking up the MGRS system, it seems intended to be a lot more precise than degrees of latitute and longitude. It's a combination of letters and numbers based on dividing the planet into a grid of metric squares , or rather that's just where it starts. MGRS divides the planet in 100,000 square meters, and then subdivides with increasing precision... like what we see in this example: https://mgrs-data.org/about/ 

An example MGRS datum (from that example) looks like this: 17RMP1234567890 

So I think we had better not give the degree ranges here. That's for a different geocoordinate system.

**Comment by ebeshero** [comment]
After reading considerably about this, I'm amending the description to read, "values supplied follow the Military Grid Reference System, which designates grid zones in a string of letters and numbers that distinctly indicate each square meter on the planet."
