### ISSUE TITLE
update Junicode font

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#2472]
The [Junicode font](https://github.com/psb1558/Junicode-font) is used in the PDF build of the Guidelines and we use in our Debian based build systems the package "fonts-junicode" to include it. Yet, with the new stable release "Bookworm", the [junicode package](https://packages.debian.org/bookworm/all/fonts-junicode/filelist) includes Junicode v2 where the font name has changed to "Junicode Two Beta".

We could try to stick with the old name and map it via some `fontconfig` to the new name or we'd alter the name in (the only occurrence!) at https://github.com/TEIC/TEI/blob/dcfee0087066d4e5e8b507499280460565c30370/P5/Utilities/guidelines-latex.xsl#L233 

This is more or less urgent since the main Jenkins server was already updated to Bookworm, thus PDF builds will currently fail there.

**Comment by raffazizzi** [comment]
@peterstadler, would altering the name in line 233 to `Junicode Two Beta` cause our package to not work with older Debian builds? If yes, should we care?

**Comment by peterstadler** [comment]
Hmm, I believe at least @hcayless's Docker image as well as @martindholmes's Jenkins server would need to be updated. And I do not know what people are using out there in the wild …

I mean, we need to move forward, somehow, so I'm all for doing this change but it need to be documented

**Comment by martindholmes** [comment]
My server is running Ubuntu 22.04, and this is what's included in the package and installed:

https://packages.ubuntu.com/jammy/all/fonts-junicode/filelist

The October release of Ubuntu will adopt the Debian change:

https://packages.ubuntu.com/kinetic/all/fonts-junicode/filelist

but this won't make it into an Ubuntu LTS until 24.04, and I won't upgrade my server until 24.04.1, which will be around June next year.

**Comment by martindholmes** [comment]
We could try a manual install of the new fonts somehow. But I'm already not keen on the fact that these new fonts have filenames with "Beta" in them. That presumably means they're going to change again at some point. Wouldn't it be better to install the old Junicode fonts on the Bookworm server?

**Comment by martindholmes** [comment]
I see also that the current [release](https://github.com/psb1558/Junicode-font/releases) on the repo does not have the "Beta" in the filenames. So I think Debian is rather out of step with the developer(s?) here, and has shipped with a package that seems rather unstable; and Debian unstable (trixie) has non-beta font names:

https://packages.debian.org/trixie/all/fonts-junicode/filelist

So I would call out Bookworm here; shipping a non-stable or interim release with what amounts to a beta package (as Ubuntu 23.10 is doing, inheriting from Debian) is one thing, but including it in a stable release seems weird.

**Comment by peterstadler** [comment]
I agree with @martindholmes to call out Bookworm here.
A fix has been implemented in the Jenkins Docker image to update Junicode fonts from the newer Debian Trixie, and no further action is needed for the TEI repo. Hence closing the issue
