### ISSUE TITLE
Feature request: <listPerson> as bullet list

### ISSUE THREAD

**Issue by nquenouille** [TEIC/TEI#2475]
If I want to have a nice bullet point list of persons and a valid TEI document, I can do this:

```
<div type="persons">
		    <list rend="bulleted">
		        <item>
		            <listPerson>
                               <person xml:id="p1">
                                   <persName>John Doe</persName>
                               </person>
                           </listPerson>
                       </item>
                       <item>
                         <listPerson>
                            <person xml:id="p2">
                               <persName>Jane Doe</persName>
                           </person>
                       </listPerson>
                     </item>
               </list>
</div>
```

But this is ugly, since listPerson should already provide a list (without having to wrap it into a list and item element). How could this be done? I tried to give the listPers the attribute rend="bulleted" or type="bulleted", but neither worked, and if I insert a bullet concatenating it with persName, I have still the issue of having a list in a row and not one person under the other. Any advise (or maybe a new feature) is appreciated.

**Comment by hcayless** [comment]
[listPerson](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-listPerson.html) has `att.global.rendition` and `att.typed` out of the box, so this ought to work unless your local customization disallows it for some reason. So
```xml
<listPerson rend="bulleted">
  ...
</listPerson>
```
should be fine. Or are you asking about how it's rendered? I don't know that the Stylesheets (for example) would handle that without some customization...

**Comment by nquenouille** [comment]
Hi Hugh,
nice to read you. :-)
I am working with the TEI Publisher and tested it on the LEAF Writer, too. I do not see anything in the customization that could prevent it from rendering as bullet list. A normal "list"-Element is rendered as bullet list, though, even without rend="bulleted".

**Comment by hcayless** [comment]
You too! This sounds like a TEI Publisher / LEAF Writer styling issue then. It's probably something that can be handled with a bit of CSS, but it's not within our (TEI Council's) purview. You'll need to ask the Publisher / LEAF folks. I'm going to go ahead and close this because we can't fix it ourselves, but you'll still be able to reference it in communication with them if you need to.

**Comment by nquenouille** [comment]
Many thanks!
It worked by manipulating the ODD.
