### ISSUE TITLE
French description inconsistencies

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2486]
Of the 503 `//elementSpec/desc[@xml:lang eq 'fr']` elements in the _Guidelines_, 17 start with a capital letter and 22 start with whitespace. I do not know that these are all mistakes, but it sure looks suspicious. Someone who actually speaks French should take a look at those 39.

**Comment by sydb** [comment]
(And someday I will look at the `<desc>` elements for other languages. :-)
Note-to-self: `xsel -t -m "//t:elementSpec/t:desc[@xml:lang='fr']" -v "concat( substring( normalize-space( concat('|', .,'|') ), 1, 4 ), '|')" -n p5.xml | rank`

**Comment by lb42** [comment]
That's a pretty obscure command line... my linux says it's never heard of "rank".  Anyway, applying the xpath
`//elementSpec/desc[@xml:lang='fr'][not(matches(.,'^[a-z]'))]` I get 39 cases, of which 17 begin with a capital letter. I had a quick look and I cannot see anything wrong with any of them. Presumably someone didn't get the memo about starting with a lower case letter and eschewing whitespace. Want me to fix them? I would probably break something so maybe I'll leave it to you.

**Comment by sydb** [comment]
My only hesitation is that I don’t know French. If there is nothing to be messed up by changing to lower case and normalizing space, I am happy to make the change. If either such changes could be significant in French or you want to make the changes, please go right ahead. (The only thing it might break is the Stylesheets’ test procedure, which I will mop up afterwards.)

**Comment by lb42** [comment]
FWIW there are 35 desc elements, by no means all of them French,  whose content starts with a blank irrespective of language. Why is this an issue?

**Comment by ebeshero** [comment]
@sydb Do you want to leave this ticket open? I'm not sure we'll correct more inconsistencies before this next release of the Guidelines...

**Comment by sydb** [comment]
No, I meant to close it — thanks for the poke!
(That said, these are easy fixes to make, and not particularly hard to find.)
