### ISSUE TITLE
Deprecate and then remove `<re>` for `#2456`

### ISSUE THREAD

**Issue by trishaoconnor** [TEIC/TEI#2487]
While working with @sydb on #2456, the discussion with @laurentromary highlighted that `<re>` is no longer used in the context of [TEI Lex 0](https://dariah-eric.github.io/lexicalresources/pages/TEILex0/TEILex0.html) and may no longer be needed at all anymore. 

Given that `<entry>` is recursive, the proposal is to implement a long deprecation period for `<re>` (to facilitate legacy usage of `<re>`) with the suggestion that the value `"relatedEntry"` be used on `<entry>`.

**Comment by ebeshero** [comment]
Appears related to #2488, so I'm adding the same ticket assignees as we sprint to the 4.7 release...
