### ISSUE TITLE
time to update header comments?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2514]
I was getting annoyed at seeing old Subversion keywords not being substituted in our header comments. And then I noticed someone had (in a few files) put them all on one line. How much better!

**Comment by joeytakeda** [comment]
Any reason why those SVN keywords can't just be removed entirely?

**Comment by sydb** [comment]
No, @joeytakeda no reason not to remove them entirely. (That was the plan.)

Back in December I tried fixing this (in a branch[1]). But using an XML tool on our source files is a bit problematic, because at times there are whitespace consequences we would like to avoid. So the results are _almost_ right, but not quite, and merging that branch now would be a big headache.

So today I took another look. First, I checked and verified that the comments we are interested in replacing are _always_ a child of the document node, and _never_ have any preceding siblings (i.e., are always the 1st child of the document node); furthermore _none_ of them contain any of the characters `>`, `!`, `@`, `#`, `%` or TAB (U+0009).

I then wrote a C program (which I will attach later if anyone is interested[2]) to read in a TEI file and write out the same file with the whitespace of the 1st comment regularized. It regularized newline to `!`, carriage return to `@`, and compresses strings of blanks. (I never ended up using `#` or `%`.) It does not really matter what regularization it performed, it just had to make sure the 1st comment was all on one line, so it could be easily processed. In truth it has a bug. It outputs `-->-->` at the end of the comment instead of just `-->`. I started to debug it and then thought “What am I doing? It does not matter at all what it ends in, I am just going to replace it (using Perl), anyway.”.

So I ran the C program on all 877 source files, and then used a Perl one-liner to replace all the initial comments to a new copyright comment. Both of these processes were _very_ fast, < 2 s each. Which is a good thing, because I had to repeat the process when I realized I had spelled “licenses” wrong. The new copyright comment is “&lt;!-- © TEI Consortium. Dual-licensed under CC-by and BSD2 licenses; see the file COPYING.txt for details. -->”.

In retrospect, this was probably a pretty silly way to do this. In Perl you can reset the character used to separate records (by default it is LF in GNU/Linux, CR on MacOS, and CR-LF in Windows, or whatever). So if I had reset that character to `%` I could just have made the change in 1 step. E.g., I think `perl -p -i -e 'BEGIN{$/="="} s,<!--[^>]*Copyr[^>]+-->,<!-- © TEI Consortium. Dual-licensed under CC-by and BSD2 licenses; see the file COPYING.txt for details. -->,;'  Guidelines/en/*.xml Guidelines/fr/HD-Header.xml Specs/*.xml` would have done the job alone. (Because there are no comments that contain the string “Copyr” except those that are the ones we want to change.)

In any case, the result passed all the usual tests locally. I took a quick look at a few of the files that had other comments as direct children of the document node (all by Martin Holmes, I think), and they looked fine, too.

**Notes-to-self**
[1] In my TEI_gitHub/ dir, branch `sydb_2514_header_comments`, which I never checked in, and would be a royal pain to merge now. 
[2] albus:/home/syd/Documents/tei-work/normalize-space-of-first-comment.c.

**Comment by ebeshero** [comment]
That's some fancy string-work! (Applause)
