### ISSUE TITLE
content models of `<event>` and `<listEvent>` miss chance at appropriate self-abstraction

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2524]
The model class model.eventLike has two members: `<event>` and `<listEvent>`.

The content models of `<event>` and `<listEvent>` each have a clause that refers to the union of those two elements:  `( event | listEvent )*` and `( event | listEvent )+`, respectively.

They should not. They should refer to the class. (That is, `model.eventLike*` and `model.eventLike+`, respectively.)

A search through tei_all.rng[1] says these are the only 2 such cases.

**Note**
[1] Using `//r:choice[ child::r:ref[@name='event'] and child::r:ref[@name='listEvent'] ]`.

**Comment by ebeshero** [comment]
Note related ticket: https://github.com/TEIC/TEI/issues/2523

**Comment by ebeshero** [comment]
Completed with https://github.com/TEIC/TEI/pull/2525
