### ISSUE TITLE
how to encode indexes in Tite

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#254]
Tite mentions use of &lt;divN type="index"&gt; \(where N is an integer from 1 to 7 inclusive\) but does not give any guidance on encoding the contents of an index.

Original comment by: @kshawkin

**Comment by kshawkin** [comment]
Oh gosh, I just haven't gotten made time to look at how the TEI does this and see how to accommodate in Tite.  This, along with other tickets, was on hold till I reconciled DTDs with Apex in December 2014 (see [history](http://wiki.tei-c.org/index.php/User:Kshawkin/My_Council_obligations/Plan_for_TEI_Tite)), so in a sense it's only a year and a half old.

**Comment by lb42** [comment]
Feel free to reopen when you have a proposal to make.
