### ISSUE TITLE
Create new attribute class att.indentation, connected to CMC chapter

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#2554]
At the SVF2F session on 2024-04-27, Council decided to create a new attribute class, `att.indentation` connected with work on the new CMC chapter. The `att.indentation` class would host a new attribute, `@indentLevel`, for use in describing a level of indentation found in CMC posts and replies, that may partly but imperfectly convey hierarchical structure. While this is primarily intended for representing indentation in CMC platforms, we should try to define the concept of `@indentLevel` as broadly as we can for use with other ambiguous representations of hierarchy.

**Comment by ebeshero** [comment]
We should do this work on the CMC branch as part of https://github.com/TEIC/TEI/pull/2537

**Comment by sydb** [comment]
This work has already been done on #2537, and should be closed if & when that PR is merged.
