### ISSUE TITLE
constrain `@source` on tagdoc elements to allow only 1 value

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#2588]
The `<remarks>` for `@source` of att.global.source says quite clearly that the `@source` of  `<classRef>`, `<dataRef>`, `<elementRef>`, `<macroRef>`, `<moduleRef>`, or `<schemaSpec>` should have only 1 value (i.e., should not have any spaces). This should be schema-constrained.

**Comment by sydb** [comment]
As far as I am concerned, this is a GO for creation of the constraint with possible further discussion on the PR.

**Comment by sydb** [comment]
Except that it was already done years ago (PR #2156 addressing #1869).

**Comment by ebeshero** [comment]
We should remove the 4.9 release milestone then, yes?
