### ISSUE TITLE
RNG files not downloadable using wget or curl

### ISSUE THREAD

**Issue by eamonnkenny** [TEIC/TEI#2590]
I'm attempting to download python requests, curl or wget for:

https://tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng

and receive back read errors. 

Examples of errors:
(18) transfer closed with 1105939 bytes remaining to read
2024-09-09 12:23:00 (166 MB/s) - Read error at byte 32287/1150509 (Error decoding the received TLS packet.). Retrying.

**Comment by peterstadler** [comment]
I can confirm the error. A simple `curl  https://tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng`
returns
```shell
   [...]
   <define name="att.pointing.group.attribute.domains">
      <optional>
         <attribute name="domains">
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

This is most probably an error with the new web server @hcayless ?
For the time being, you can use https://vault.tei-c.org/P5/current/xml/tei/custom/schema/relaxng/tei_all.rng  which is served by a different server.

**Comment by hcayless** [comment]
This is fixed.
