### ISSUE TITLE
Add @xml:lang to every `<constraintSpec>`

### ISSUE THREAD

**Issue by HelenaSabel** [TEIC/TEI#2608]
The fix for https://github.com/TEIC/Stylesheets/issues/702 made us realise that we should always have a `@xml:lang`  in every `<constraintSpec>`

**Comment by sydb** [comment]
This ticket requires two changes:

1. Update p5odds.odd so that `@xml:lang` is required on `<constraintSpec>`
2. Actually add `@xml:lang` on those `<constraintSpec>`s that do not have it

**Comment by sydb** [comment]
This was completed with #2610.
