### ISSUE TITLE
Bug in example for del

### ISSUE THREAD

**Issue by TomazErjavec** [TEIC/TEI#2613]
[One of the examples for del element](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#index-egXML-d54e35651) uses the `@type` attribute (with value `overstrike`), however:
* this is the only place where `@type` is used with `del`
* the immediately preceding example has `@rend="overstrike"`

which makes me think the `@type` attibute here should actually be `@rend`.

**Comment by sydb** [comment]
Well spotted!

Indeed, the fact that the preceding line says “The rend= attribute may be used …” strikes a nail in this `@type`s coffin. It should be `@rend`.
