### ISSUE TITLE
altIdentifier in msPart

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#263]
Coming back to a discussion within ms-sig \(http://listserv.brown.edu/archives/cgi-bin/wa?A2=ind0907&L=TEI-MS-SIG&P=R34\) I would like to ask for revision of &lt;altIdentifier&gt; as child of &lt;msPart&gt;: &lt;altIdentifier&gt; cannot have &lt;altIdentifier&gt; as children which might be needed if a part of a manuscript has its own name. Example for this are the catalogues of E.A. Lowe \(CLA\) which list msParts as separate catalogue entries. The catalogue numbers would have to be encoded using &lt;altIdentifier type="catalog"&gt;. Thus, &lt;altIdentifier&gt; should be available at least as child within &lt;altIdentifier&gt;?

I think it would even better --though I know that I ask for "breaking documents"-- to rename &lt;altIdentifier&gt; as child of &lt;msPart&gt; into something like &lt;msPartIdentifier&gt; in analogy to &lt;msIdentifier&gt;\!? 

Original comment by: @schassan

**Comment by jamescummings** [comment]
Closing since implemented, additional examples to Guidelines always nice but there are some.
