### ISSUE TITLE
add <add> and <del> for encoding of manuscripts

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#268]
Tite is missing both &lt;add&gt; and &lt;del&gt;.  These are needed to support encoding of handwritten source material.  The member survey that led to Tite detected a desire for vendor encoding of manuscripts, and it was an oversight not to include this in Tite.

In addition to adding them to the schema, some prose documentation will need to be written and inserted into the prose at an appropriate location.

Original comment by: @kshawkin

**Comment by sydb** [comment]
Sub-group thinks that since no one has added a request for `<addSpan>` or `<delSpan>` since 2011-01. Thus this ticket should be closed. If and when a TIte user wants these elements, she or he will have to open a new ticket (i.e., issue).

**Comment by kshawkin** [comment]
Oh gosh, I just haven't gotten made time to look at how the TEI does this and see how to accommodate in Tite.  This, along with other tickets, was on hold till I reconciled DTDs with Apex in December 2014 (see [history](http://wiki.tei-c.org/index.php/User:Kshawkin/My_Council_obligations/Plan_for_TEI_Tite)), so in a sense it's only a year and a half old.

**Comment by lb42** [comment]
Please feel free to reopen the ticket when you've had time to consider this issue.
