### ISSUE TITLE
att.canonical for model.persTraitLike 

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#290]
In a recent ticket it was decided that 'faith' was a good candidate to have att.canonical added to it.

Similarly all the other members of model.persTraitLike should probably have this added.  This consists of:

age faith langKnowledge nationality sex socecStatus trait

In most of these a use-case could be made for wanting to point out to, say, a taxonomy or authority file of some sort.

Possibly other things that can appear inside 'person' should be reconsidered at the same time.

-James

Original comment by: @jamescummings

**Comment by jamescummings** [comment]
Just closing since it has been overtaken by other tickets.
