### ISSUE TITLE
add SourceForge feeds to http://www.tei-c.org/Activities/

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#293]
Per Council discussion on tei-council and at lunch on 2011-04-13, we decided that we would like two iframes at the bottom of http://www.tei-c.org/Activities/ : one for the most recent items in http://sourceforge.net/api/artifact/index/tracker-id/644062/limit/1000/rss and another for those in http://sourceforge.net/api/artifact/index/tracker-id/644065/limit/1000/rss .  This will demonstrate to casual visitors to www.tei-c.org that there is a lot of activity happening on SourceForge.

Original comment by: @kshawkin

**Comment by jamescummings** [comment]
Should we just close this ticket and re-open whenever we have a new website?

**Comment by bansp** [comment]
The more so that SF is now a zombie at best -- they've killed it, then reassembled it back into some sorry shape, and now it's being killed again. I think it's better to abandon that ship altogether.

**Comment by jamescummings** [comment]
Closing Issue.
