### ISSUE TITLE
Need for tag documentation

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#3]
I am familiar with TEI lite.

When the standard is converted to a Schema, I strongly 
recommend that you provide a very detailed tag library.  
Schemas are very difficult to read and interpret.  A good 
model for documentation would be the EAD tag library at
http://www.loc.gov/ead/tglib/index.html.

Each tag is defined, and possible parent and child tags 
for the given tag are listed.  Examples are also provided.

The EAD Tag Library also has a good explanation of 
linking tags and attributes.

The DTD for P4 was relatively easy to search and 
interpret.

The Schema and DTD for P5 are much more difficult.

I also would suggest that you provide detailed 
information about what schema validators will work, 
provide detailed information on how to install and 
configure them and provide information on where they 
can be obtained.

Thanks

Original comment by: sf_user_*anonymous

**Comment by linuxlovell** [comment]
thanks www.movied.org
