### ISSUE TITLE
Encoding of Standoff annotations

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#374]
The annotation of documents using standoff annotations is a very useful and flexible methodology. Nevertheless, TEI does not have any specific elements for encoding this information.
In most of cases, the standoff annotations are stored as external TEI files linked to the text being annotated. Nevertheless, this way of storing the standoff annotations is very rigid and presents numerous problems, for example, for indexing or searching the corpus of documents using the information of the annotations. In these cases, it would be very useful to have the standoff annotations INSIDE the TEI documents being annotated (!!!). 

Therefore, it is suggested to include define a new set of TEI elements specifically dedicated to the encoding of the standoff annotations.

The idea would be to store the standoff annotations between the &lt;teiHeader&gt; and the &lt;text&gt;, following the same philosophy as used for the &lt;facsimile&gt; and for &lt;sourceDoc&gt; (in some way these two elements could also be considered as a "type" of annotation).

For the standoff annotation, the structure could be:

&lt;TEI&gt;
&lt;teiHeader&gt;
...
&lt;/texHeader&gt;
&lt;standoff&gt;
[information of the annotations]
&lt;/standoff&gt;
&lt;text&gt;
...
&lt;/text&gt;
&lt;/TEI&gt;

This structure would provide the extra advantage of allowing to annotate the information at different TEI levels in a natural manner. So for more complicated TEI documents having different hierarchical levels, the standoff annotations could be encoded as follows:

&lt;teiCorpus&gt;
&lt;teiHeader&gt;
...
&lt;/teiHeader&gt;
&lt;TEI&gt;
&lt;teiHeader&gt;
...
&lt;/texHeader&gt;
&lt;standoff&gt;
...
&lt;/standoff&gt;
&lt;text&gt;
...
&lt;/text&gt;
&lt;/TEI&gt;
&lt;TEI&gt;
&lt;teiHeader&gt;
...
&lt;/texHeader&gt;
&lt;standoff&gt;
...
&lt;/standoff&gt;
&lt;text&gt;
...
&lt;/text&gt;
&lt;/TEI&gt;
&lt;/teiCorpus&gt;

This structure would also provide the extra advantage of allowing to annotate, not only the text of the document, but also the metadata of the different hierarchical levels of the TEI document.

The specific encoding of the annotations inside &lt;standoff&gt; could be as follows:

&lt;standoff&gt;
&lt;annotation type="..." subtype="..."&gt;
&lt;author&gt;...&lt;/author&gt;
&lt;date&gt;...&lt;/date&gt;
&lt;ptr&gt;...&lt;/ptr&gt;
[other data needed]
&lt;/annotation&gt;
&lt;/standoff&gt;

As a last remark it is also suggested to allow inside the &lt;annotation&gt; the TEI element &lt;figure&gt; in order to facilitate the annotation not only of textual information, but also of images and formulas.

Conclusion: the proposed structure for the encoding of standoff annotations in TEI provides the following advantages:

\- allows to encode standoff annotations under TEI in a natural manner, which is not the case at the moment
- allows to store the standoff annotations INSIDE the TEI document being annotated in a specific location, facilitating the     process of indexing and  
searching said documents
- it is naturally integrated in the hierarchical structure of the TEI (&lt;teiCorpus&gt;, &lt;TEI&gt;)
- allows to annotate both, the textual and not textual information, and also the metadata of the &lt;teiHeader&gt;
- facilitates the exchange of annotations because they are already stored in the original TEI document being annotated

Remark: this idea has been already suggested by Piotr Bański in his article "Why TEI stand-off annotation doesn't quite work and why you might want to use it nevertheless", in http://www.balisage.net/Proceedings/vol5/html/Banski01/BalisageVol5-Banski01.html 

Original comment by: sf_user_posejavier

**Comment by sydb** [comment]
Council suggests @laurentromary and @peterstadler continue work on this, and to keep #539 in mind as they do to make sure these two proposals are not duplicating one another.

**Comment by laurentromary** [comment]
Indeed: annotationBlock must be the elementary unit of representation in standOff annotations.

**Comment by ebeshero** [comment]
F2F (Victoria, 2017) Council agrees that @peterstadler and @laurentromary should go ahead with working on this.

**Comment by ebeshero** [comment]
F2F (Victoria 2017): we need to move forward with implementing LinkDataBlock.

**Comment by peterstadler** [comment]
@laurentromary and I just had a conf call discussing this issue and the further roadmap. He made a strong point about *not* merging the standoff proposal with a 'linkDataBlock' proposal, because the first is about annotating some text (thus pointing *into* the text) whereas the second is about adding editorial content to some text (and to which is pointed *from* the text).  There has been some confusion about these distinctions (including myself), so I hope Laurent will elaborate on this!

### Next steps:
1. Laurent will prepare a short paper based on his talk during the TEI conference 2016 in Vienna (see https://hal.inria.fr/hal-01374102) 
2. I will try to arrange for a dedicated Council conf call with Laurent in January 2018.

**Comment by peterstadler** [comment]
Just stumbled across https://github.com/one-step-beyond/tei-standoff (but didn't take a closer look)
Anyone familiar with this?

**Comment by lb42** [comment]
Apparently a Turska-Spadini production. Don't you TEI councillors talk to each other any more?

**Comment by laurentromary** [comment]
Maybe we should start discussing the creation of elements. We have 2 to create: <standOff> (name agree upon by council at Ann Arbor) and <listAnnotation> and one to adapt <annotationU>. The council has had implementation proposal after we compiled the scenario document on the Ann Arbour branch.

**Comment by laurentromary** [comment]
I am also in Tokyo from Tuesday to Friday of the TEI conference. If a group from the council is ready to make a move towards implementation, we could simply have an operational session there.

**Comment by tuurma** [comment]
@peterstadler an attempt I was considering with Elena Spadini back in the day, virtually dead now, though some of that thinking was incorporated in an approach we used later for earlyPrint (namely using existing TEI elements as the body of the annotation)

**Comment by tuurma** [comment]
@laurentromary would be great to have a session in Tokyo! So far we have agreed to get our act together in a small group to get back to Council

**Comment by peterstadler** [comment]
A wrapper `<standOff>`  element has been created in 565fc72caec15d3569e496b5e71fb05ca772b158 and will be available in the upcoming release 3.7.0.

There is probably more to be fleshed out concerning the content of `<standOff>` but this qualifies dedicated tickets, so closing this one here.
