### ISSUE TITLE
Letters/memos module

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#4]
The elements currently available to encode 
correspondence are insufficient and require workarounds 
that make the encoding of a simple postscript a major 
chore.

The ways in which letters are written vary fairly 
significantly over time and across cultures.  Modern 
business letters require the ability to encode letterhead, 
addresses, attention lines, subjects, reference lines, 
persons copied, and enclosures (this list come off the 
top of my head, if it were developed systematically it 
might be quite a bit longer).  

I am currently working on a 19th century book of 
anecdotes that incorporates letters quite frequently as 
part of an ongoing narrative.  I would appreciate 
elements that would isolate the addressee in an opening 
&lt;salute&gt; and that would indicate the sender in the 
closing one.  I would like a way to indicate the position 
held by either of these parties, without getting involved 
in the depths of names&dates.

Memoranda are also rather difficult to encode.  I used to 
work with United Nations human rights documents that 
included large amounts of memoranda in the immense 
bureaucratic morasses they called reports.

Original comment by: sf_user_finkend

**Comment by linuxlovell** [comment]
thanks www.movied.org
