### ISSUE TITLE
a place for metadata that you can't fit into existing header elements

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#453]
People sometimes want to attach metadata to a TEI document that doesn't fit into an existing header element.  For example, you might want to attach Dublin Core metadata, or you might want to include Cataloguing-in-Publication data for the TEI document.  It would be good to have a place for such metadata.

We might create a new optional child of `<teiHeader>` called something like `<containerForOtherMetadata>`.  In it you could put elements from another namespace (like `<dc:title>`), or you might create your own elements (like `<cip>`).  I'm not sure what the content model for `<containerForOtherMetadata>` should be in order to allow for these things.  Maybe it actually requires that `<containerForOtherMetadata>` be in a different namespace.

(It's possible that before this ticket is resolved we will have added a new element for CIP data as a child of `<publicationStmt>`.  That idea is also being considered on TEI-L as I write this.)

Original comment by: @kshawkin

**Comment by kshawkin** [comment]
xenoData was included in P5 2.9.1: http://www.tei-c.org/release/doc/tei-p5-doc/readme-2.9.1.html .  Is there anything left to implement on this ticket, or should it now be closed?

**Comment by hcayless** [comment]
It's done, but there's some followup needed, so we haven't closed it yet.

**Comment by hcayless** [comment]
Closing, and opening a followup ticket, #1346, to address possible attributes for `<xenoData>`.

**Comment by khering23** [comment]
Does anyone have an example of a TEI header where Dublin Core (in RDF/XML) metadata is included in the <xenoData> element? Thank you.

**Comment by sydb** [comment]
Other than those in the [`<xenoData>` tagdoc](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-xenoData.html)? No, I don‘t have one on hand, but could whip up a fake one quite quickly if that would be helpful.

**Comment by khering23** [comment]
Dear Syd: Thank you for your prompt response. Yes, I used the one from the <xenoData> tagdoc as a model, but when I used the TEI schema in Oxygen, it failed to validate the <xenoData> element. I am grateful for any suggestions! 
 
Best, Katja

**Comment by lb42** [comment]
You need to use a TEI schema that includes the xenoData element: what schema were you using? and could you post your sample file here? it should work!

**Comment by khering23** [comment]
Hi Lou:
 
Many thanks. Yes, I will definitely need to use a schema that includes the xeno element -- I was using TEI p 5 bare and it didn’t recognize the xeno element:
 
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_bare.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_bare.rng" type="application/xml"
            schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Title of publication</title>
         </titleStmt>
         <publicationStmt>
            <p>publication name</p>
         </publicationStmt>
         <sourceDesc>
            <p>Description of source</p>
         </sourceDesc>
         <xenoData>
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
               xmlns:dc="http://purl.org/dc/elements/1.1/">
               <rdf:Description rdf:about="http://www.worldcat.org/oclc/954441819">
                  <dc:title>Title of publication</dc:title>
                  <dc:creator>Creator</dc:creator>
                  <dc:date>1851</dc:date>
                  <dc:identifier>oclc/954441819</dc:identifier>
                  <dc:subject>subject</dc:subject>
               </rdf:Description>
               </rdf:RDF>
         </xenoData>
      </fileDesc>
   </teiHeader>

Grateful for any advice…
