### ISSUE TITLE
Adding the @place attribute to <head> and <seg>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#479]
While the elements included in att.placement cover most of the things commonly occurring in margins or otherwise displaced from the normal textual flow, I wonder whether it would be completely inappropriate to also add &lt;head&gt; and the generic &lt;seg&gt; element to this class? Working with medieval recipe manuscripts, I frequently encounter recipe headings which are placed in the margin, as well as cases where the last few words of a recipe are placed in the margin (or some other place deviating from the general flow of the text) due to lack of space, and would like to be able to indicate this in a TEI-compliant way. 

I realize the &lt;label&gt; element is intended to be used for marginal headings, but it has the problem of not being allowed within the &lt;front&gt; of a text. My theoretical approach involves viewing recipe collections as discourse colonies and individual recipes as independent texts, and since the title of the recipe thus logically goes to the &lt;front&gt; (along with a possible recipe number and any reference markers), the &lt;label&gt; element (which, by the way, seems to be rather sparsely defined and documented at the moment) does not currently work.

As to the annotation of stray bits of text that have been shoved into all kinds of available spaces, this is by no means an uncommon practice in mediaeval manuscripts. While my annotation is intended primarily for use as linguistic corpus material and I thus really cannot adopt the purely visual encoding developed for genetic editing (as much as it does appeal to me), one of my central concerns is also the annotation of visual paratext, including layout. For this purpose I have developed a simple system based on the use of `@place`, `@rendition` and `@rend`; the only problem at the moment is that I have no TEI-sanctioned way of indicating the displacement of individual segments of text (and headings) from the textual stream, for which the most logical solution would be to allow `@place` on the &lt;seg&gt; element.

Original comment by: sf_user_vmarttil

**Comment by dariok** [comment]
I'd like to pull this request back up and vote to reopen it.

In my opinion, the council's suggestion
> that out-of-sequence `<head>` and `<seg>` (which is what we suggest `@place` conveys) does not make sense

is plain wrong. In early prints and manuscripts, placing a heading in the margin is quite common. Especially in eraly prints, even alternating freely between a free head, an inline heading and a heading in the margin is entirely possible. 

If you kindly consider [this page](http://diglib.hab.de/show_image.php?dir=drucke/ed000364&pointer=34), you'll see that the first text functioning as a heading (_Prima Conclusio_) is placed inline, while the other (_Secunda Conclusio_) is placed in the margin.
(I chose this example as both inline and marginal placement are visible here. There are other instances in this and other texts making it clear that these information indeed serve to indicate a regular partitioning of the text, in this case between different _opiniones_ and _resolutiones_).

Now there's two possibilities.
1) I maintain that these two are heading, tag them as `<head>` and either 1a) have to completely discard the information about the actual placement of the text or 1b) have to resort to `@rend`, which in my mind is not the right attribute as I'd like to argue that rendition and placement are two completely distinct phenomena.
2) I want to encode the placement, for which `@place` gives me the right vocabulary. Then, I have to resort to `<label>` which I indeed find a very unfortunate solution as the guidelines say that a `<label>` is attached to a paragraph »not treated as a structural division« (and indeed is defined in section 3.7, **Lists!**) which here is not the case (see my comment above).

As both solutions are unsatisfactory and do not reflect the reality of early prints and manuscripts, I move to reopen and reconsider this request as far as it regards `<head>`.

Best,
Dario
