### ISSUE TITLE
Adding the @hand attribute to all (or most) text-containing elements

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#481]
While the documentation of manucript hands in the header is currently well-supported, the assignment of these hands to individual stretches of text in the trasncription is much less so, as the `@hand` attribute is allowed only on a very limited number of elements, mostly limited to describing what could be called 'special cases' (att.transcriptional) or to specific editorial methods (att.textCritical). In addition, in the case of some of these elements, namely &lt;gap&gt; and &lt;damage&gt;, the `@hand` attribute does not really make sense in terms of the element itself but rather serves as a shorthand, implying the existence of an associated &lt;del&gt; element.

In order to be able to consistently indicate the hand responsible for every stretch of transcribed text, I would like to see the `@hand` attribute added (possibly via a new attribute class) to all text-containing elements on each level of the textual hierarchy. This would allow us to indicate the hands used in a document in a cascading fashion, indicating the principal scribe (if one exists) on the root &lt;text&gt; element and then indicating all deviations from this on the appropriate container element. This would mean that it would be trivial to determine the hand of any text node by simply finding the first ancestor that has the `@hand` attribute (and is not a &lt;del&gt; element*). 

While the ideal, most consistent solution would be to provide the attribute on not only &lt;text&gt;, &lt;div&gt;, &lt;p&gt;, and &lt;seg&gt;, but also on all of their more specialised parallels, its provision on these basic elements and the relatively common &lt;head&gt;, &lt;fw&gt; and &lt;note&gt; elements would most likely cover the majoríty of cases. This would allow the `@hand` attribute to be used properly for the purpose which it was intended according to the guidelines, which sadly is currently not possible. 

The &lt;handShift/&gt; element is not really a solution, since many of the textual items written in different hands (but still as a part of the original production process, excluding them from additions) are things like headings, forme work (folio numbers, signatures, catchwords), and notes, which are not a part of the textual flow and would make it very awkward to shift back and forth using the milestone element. Additionally, it does not allow for the cascaded indication of hand and would add unnecessary milestone elements where none are actually needed.

*) On the &lt;del&gt; element the attribute does not refer to the hand responsible for the textual content, but to the one responsible for the action indicated by the annotation, making &lt;del&gt; something of an anomaly; this could be seen as a reason for using a different attribute than `@hand` to indicate responsibility for a deletion. I would also very much like to see the `@hand` attribute removed from &lt;gap&gt; and &lt;damage&gt; elements in the favour of using a surrounding &lt;del&gt; element which not only is much more transparent semantically, but also allows the properties of the deletion and the ensuing damage or loss to be annotated separately.

Original comment by: sf_user_vmarttil

**Comment by sydb** [comment]
We should perhaps also add <signed> to the group of elements in `att.written`. After all, it is usually handwriting. (Suggested by Martha Gardener at a workshop.)

**Comment by lb42** [comment]
@jamescummings : what is your reason for thinking &lt;gap> shouldnt have @hand? Removing it would break Birnbaum, and the use case cited in the spec seems plausible to me. Would you also remove it from &lt;unclear?

**Comment by lb42** [comment]
Have now re-read this ticket more carefully, and see that removing @hand from gap and unclear forms part of the original proposal. This would risk making existing documents invalid, so should be handled as a deprecation in the first instance. 

So, I am now planning to implement the new class with the following members 
- existing members of att.transcriptional, att.textCritical, and (possibly) att.damaged
-    text div p ab note lg
-    seg head fw label hi
-    opener, closer, salute, signed
-    zone line
Local definitions will of course be removed where needed, except that I propose to retain the local definition for @hand on  <gap> and <unclear> to facilitate  deprecation

**Comment by lb42** [comment]
Implemented at commit  9d3c4b8

**Comment by sydb** [comment]
Just noticed that `<signed>` had not, in fact, been added to list. Added to `att.written` in b169c03.
