### ISSUE TITLE
deprecating members of a content model

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#486]
As discussed in November 2013 Council meeting ( http://www.tei-c.org/Activities/Council/Meetings/tcm56.xml#body.1_div.3_div.1_div.1_div.1 ), there are three tickets involving deprecation that can't be solved with the current mechanisms:

* https://sourceforge.net/p/tei/feature-requests/294/#5737
* https://sourceforge.net/p/tei/feature-requests/383/?limit=10&page=1#bbe8
* https://sourceforge.net/p/tei/bugs/288/?limit=10&page=3#99f0

We need a way to deprecate members of a content model.  As agreed in Oxford, these three tickets should be solved using a Schematron warning.  We also need to add `@validUntil` on constraintSpec.

Original comment by: @kshawkin

**Comment by lb42** [comment]
All dependencies fixed
