### ISSUE TITLE
Allow bibl inside app

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#492]
[Note: this ticket was originally two tickets, 491 and 492. Merged by MDH 2014-07-30.]

FIRST:

The content model for `<app>` allows `<wit>` inside it to permit the encoding of sigla in a print apparatus. This corresponds to the machine-actionable references to witnesses using ``@wit``. The next release of the Guidelines will allow ``@source`` on `<rdg>` (see [feature-requests:#465]), so it seems reasonable also to permit `<bibl>` inside `<app>` to allow bibliographic citations of sources in apparatus to be encoded properly.

For example in the following bit of apparatus:

**9** latebit *FTX*		**11** gelidas…oras *Eutyches, G. L. K. v.* 475
**12** suo *BP Eutyches*	**14** n. n.] verba canina (carina *Zamoscianus*)
*FTX cod. Zamoscianus* **etc.**

"*G. L. K. v.* 475" cites page 475 of [Keil's Grammatici Latini](https://archive.org/stream/grammaticilatini05keil#page/474/mode/2up), so it would be reasonable to put it in a `<bibl>`, something like:

~~~~~

<app><ref target="#l11">11</ref> <rdg source="#GLK">gelidas...oras</rdg> 
<wit>Eutyches, </wit><bibl>G. L. K. v. 475</bibl></app>

~~~~~

SECOND:

Printed apparatus critici often include a reference to the line number in the text that the apparatus entry applies to. This seems like it really ought to be encoded as a `<ref>`. For example, if I want to encode a print apparatus looking like:

**9** latebit *FTX*		**11** gelidas…oras *Eutyches, G. L. K. v.* 475
**12** suo *BP Eutyches*	**14** n. n.] verba canina (carina *Zamoscianus*)
*FTX cod. Zamoscianus* **etc.**

(from the first page of Owen's edition of Ovid's *Ibis*) I might want to treat the line numbers as references to the line, but I can't use `<ref>` inside `<app>`. I want to be able to do something like:

~~~~~

<app><ref="#l9">9</ref><rdg wit="#F #T #X>latebit</rdg> <wit>FTX</wit></app>

~~~~~
to represent the line refs in the app.

Note: see also [feature-requests:#521].

Original comment by: @hcayless

**Comment by jamescummings** [comment]
When I asked @hcayless about this on 2015-10-01 he said "I'm coming around to the opinion that these sorts of things ought to be in `<note>`s..." (and presumably bibliographic things inside a `<bibl>` inside that).  Changing status back to amber.

**Comment by hcayless** [comment]
Closing. I think now that specific citations like this belong in `<note>`s in the app.
