### ISSUE TITLE
Permit new <persona> as a child of <person>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#498]
Feature request

Summary or proposal: Add a &lt;persona&gt; element as a child of &lt;person&gt;, with the same content model as &lt;person&gt;.

The problem: A TEI &lt;person&gt; may appear in disguise, a situation that is currently difficult to express in a TEI personography.  

Here are two distinct cases, the second of which is naturally modeled with the proposed &lt;persona&gt; child of &lt;person&gt;:

Case 1) Daniel Day Lewis is disguised as Abraham Lincoln. Both Lewis and Lincoln are persons &lt;person&gt;, with distinct DNA. 

Case 2) Barry Humphreys is disguised as Dame Edna Everage. Not the same as Lewis and Lincoln because there are not two persons, with distinct DNA. Projecting from the real to the fictional, the same is true of Jeckyll and Hyde (that is, in their fictional world they have the same DNA).

The focus of this proposal is on Case 2, where the relationship is not between two human beings, but between two personae assumed by a single (real or fictional) human being. This proposal makes no recommendation about encoding Case 1.

A natural representation of Case 2 would involve permitting a new element, &lt;persona&gt;, as a child of &lt;person&gt;. &lt;persona&gt; would have the same content model as &lt;person&gt;. The XML parent/child relationship is a natural way to express that a single human being may operate in multiple guises, perhaps with some inherited information, but potentially with completely different (assumed or natural) names, traits, and statuses.

To use `@sameAs` to link two &lt;person&gt; elements in Case 2 would elevate an identity (or persona) to the status of person. As the Chair of the Personography Working Group wrote on TEI-L, 2014-02-20: "someone disguising him- or herself as someone else does not become a different physical person -- certainly not in the way we intended the &lt;person&gt; element to be used, to 'provide information about an identifiable individual'."

The proposal is intended to address the Case 2 situation described above. Discussion of the proposal should not be distracted by Case 1, or by edge cases, such as triune divine hypostases; it is not intended to address those situations. It should also not be distracted by the distinction between real and fictional persons. Finally nothing in this proposal would prohibit a project from deciding that, in local use, Humphreys and Everage and Jeckyll and Hyde are all different persons, and therefore different &lt;person&gt; elements, and that the relationship among them should be expressed using `@sameAs` or &lt;relation&gt;. What the proposal would do is permit someone who views Humphreys and Everage as different personae of the same person (likewise for Jeckyll and Hyde) to encode them in a way that captures the fact that at the most fundamental level they are the same identifiable individual.

Original comment by: @djbpitt

**Comment by lb42** [comment]
I've added a new &lt;persona> element, but some discussion/examples still needed

**Comment by ebeshero** [comment]
Suggestions:
* Orlando
* Tiresias

**Comment by lb42** [comment]
Added  spec for persona, and some prose explaining what it's for at commit bd8e804
