### ISSUE TITLE
metadata element for header

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#5]
I would like to suggest adding a metadata element to
the header (maybe under profileDesc?) This element
would have a series of keys and values; e.g.,

&lt;profileDesc&gt;
&lt;metadata&gt;
&lt;metadataItem&gt;
&lt;key&gt;Provenance&lt;/key&gt;
&lt;value&gt;Oxyrhynchus&lt;/value&gt;
&lt;/metadataItem&gt;
&lt;metadataItem&gt;
&lt;key&gt;Location&lt;/key&gt;
&lt;value&gt;Sackler Library&lt;/value&gt;
&lt;/metadataItem&gt;
&lt;/metadata&gt;
&lt;/profileDesc&gt;

This would allow people to use their inhouse scheme,
which may not always be compatible with what TEI
already has, or extensions like MASTER.

I attach a file (a work in progress) which is an
attempt to encode a Graeco-Roman papyrus manuscript.
You will see at the bottom of the file my &lt;div
type="metadata"&gt; hack to include metadata that I need
for the digital library system I am using (Greenstone).
It seems to me that this data should be in the header.
I did try using the existing conventions, but gave up.

Tim Finney

Original comment by: @tfinney

**Comment by linuxlovell** [comment]
thanks www.movied.org
