### ISSUE TITLE
Redefine <msPart>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#505]
I would like to request that the TEI consider redefining the usage and description of `<msPart>` in the guidelines.  The wording right now here http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msPart.html and here http://www.tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#mspt sounds as though the encoding encoding a manuscript or text-bearing object from the perspective of the documenting the *current* composite.  There are encoding projects that are encoding from the perspective of an original manuscript or text-bearing object that is now in pieces in different places.  

To encode the now dismembered original we need an element to provide information about all of the parts and their different catalogue numbers, current repository locations, histories, publication history, etc.  Using altIdentifier is one possibility, but it does not provide as much opportunity for rich annotations about each part.  It is also not as elegant, and there is some debate about whether this is the appropriate element according to the guidelines, as well.  Adding a whole new tag is possible, but there are disadvantages to proliferating the tagset.

Here is some possible new language for the guidelines:
The msPart element may be used in cases where what were originally physically separate manuscripts or parts of manuscripts have been bound together and/or share the same call number or in cases where an original manuscript manuscript now exists in distinct parts in different repositories and/or with distinct call numbers.  msPart may be used for other text-bearing objects, such as inscriptions.
	•	msPart (manuscript part) contains information about an originally distinct manuscript or part of a manuscript, now forming part of a composite manuscript.  In this case, the existing composite manuscript is being encoded.
	•	msPart (manuscript part) contains information about one part of a larger original manuscript whose distinct parts may reside in different repositories or contain different call numbers.  In this case, the original manuscript is being encoded with msPart used to provide information about the dispersed parts, or one distinct part is being encoded.

(Examples of the first case are a portmanteau type manuscript or collection of manuscript pages that have been bound together as a composite in one library or museum.  msPart documents the different parts within this composite.  Examples of the second case might be: a manuscript or codex composed previously as a unified object whose pages now reside in different libraries/museums or in different bound volumes or under different catalogue numbers in the same repository; an inscription on a stone in which part of the text-bearing object remains in situ and another part has been relocated to a museum.)

Please also see the discussion on the EpiDoc Markup list (under the "multiple repository" subject line, for example here http://lsv.uky.edu/scripts/wa.exe?A2=ind1403&L=MARKUP&P=R2591&D=1&I=-3&O=D). 

An example of a project already using msPart to describe one part of what used to be a larger original manuscript is Coptic Scriptorium (see the TEI files at http://coptic.pacific.edu).

Original comment by: @ctschroeder

**Comment by martindholmes** [comment]
Stephanie has created the msFrag branch for this. I've just done some edits of the MS chapter prose on that branch (mainly language tweaks). I was able to build the Guidelines HTML successfully on this branch.

**Comment by stefaniegehrke** [comment]
Happy to hear that, Martin !

See you tomorrow
Stefanie

2015-10-27 21:11 GMT+01:00 Martin Holmes <notifications@github.com>:

> Stephanie has created the msFrag branch for this. I've just done some
> edits of the MS chapter prose on that branch (mainly language tweaks). I
> was able to build the Guidelines HTML successfully on this branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/TEI/issues/505#issuecomment-151628667>.
>



-- 
Stefanie Gehrke
Coordinatrice Données Equipex Biblissima
stefanie.gehrke@biblissima-condorcet.fr <prenom.nom@biblissima-condorcet.fr>
+33 (0)1 55 93 93 86 <%2B33%20%280%291%2055%2093%2093%2090>

Campus Condorcet
20 avenue George Sand
93210 La Plaine Saint-Denis
http://www.biblissima-condorcet.fr
@biblissima

**Comment by jamescummings** [comment]
Did this branch ever get merged in so msFrag entered dev? I had another request for it from manuscript cataloguers today.

**Comment by stefaniegehrke** [comment]
Hi James,

Yes - we definitely have to go ahead

Stefanie

2015-12-07 23:38 GMT+01:00 James Cummings <notifications@github.com>:

> Did this branch ever get merged in so msFrag entered dev? I had another
> request for it from manuscript cataloguers today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/TEI/issues/505#issuecomment-162691296>.
>



-- 
Stefanie Gehrke
Coordinatrice Données Equipex Biblissima
stefanie.gehrke@biblissima-condorcet.fr <prenom.nom@biblissima-condorcet.fr>
+33 (0)1 55 93 93 86 <%2B33%20%280%291%2055%2093%2093%2090>

Campus Condorcet
20 avenue George Sand
93210 La Plaine Saint-Denis
http://www.biblissima-condorcet.fr
@biblissima

**Comment by stefaniegehrke** [comment]
@Hugh : are you still planning to provide an example for msFrag deriving
from your data ?

thanks
Stefanie

2015-12-08 6:54 GMT+01:00 Stefanie Gehrke <
stefanie.gehrke@biblissima-condorcet.fr>:

> Hi James,
>
> Yes - we definitely have to go ahead
>
> Stefanie
>
> 2015-12-07 23:38 GMT+01:00 James Cummings <notifications@github.com>:
>
>> Did this branch ever get merged in so msFrag entered dev? I had another
>> request for it from manuscript cataloguers today.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TEIC/TEI/issues/505#issuecomment-162691296>.
>>
>
>
>
> --
> Stefanie Gehrke
> Coordinatrice Données Equipex Biblissima
> stefanie.gehrke@biblissima-condorcet.fr
> <prenom.nom@biblissima-condorcet.fr>
> +33 (0)1 55 93 93 86 <%2B33%20%280%291%2055%2093%2093%2090>
>
> Campus Condorcet
> 20 avenue George Sand
> 93210 La Plaine Saint-Denis
> http://www.biblissima-condorcet.fr
> @biblissima
>



-- 
Stefanie Gehrke
Coordinatrice Données Equipex Biblissima
stefanie.gehrke@biblissima-condorcet.fr <prenom.nom@biblissima-condorcet.fr>
+33 (0)1 55 93 93 86 <%2B33%20%280%291%2055%2093%2093%2090>

Campus Condorcet
20 avenue George Sand
93210 La Plaine Saint-Denis
http://www.biblissima-condorcet.fr
@biblissima

**Comment by hcayless** [comment]
@stefaniegehrke Yes I am. Sorry it took me so long to reply. Can this now be merged into dev, even if there are still a few things to be done? It would be nice to get it into the next release.

**Comment by stefaniegehrke** [comment]
did you already discuss dates for the next release, Hugh ?

Stefanie

2016-02-03 20:29 GMT+01:00 Hugh A. Cayless <notifications@github.com>:

> @stefaniegehrke <https://github.com/stefaniegehrke> Yes I am. Sorry it
> took me so long to reply. Can this now be merged into dev, even if there
> are still a few things to be done? It would be nice to get it into the next
> release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/TEI/issues/505#issuecomment-179416447>.
>



-- 
Stefanie Gehrke
Coordinatrice Données Equipex Biblissima
stefanie.gehrke@biblissima-condorcet.fr <prenom.nom@biblissima-condorcet.fr>
+33 (0)1 55 93 93 86 <%2B33%20%280%291%2055%2093%2093%2090>

Campus Condorcet
20 avenue George Sand
93210 La Plaine Saint-Denis
http://www.biblissima-condorcet.fr
@biblissima

**Comment by hcayless** [comment]
We're tentatively aiming to freeze on February 29th

**Comment by hcayless** [comment]
Merged in bf36089.
