### ISSUE TITLE
New element <transcriptionDesc> as a possible child of <encodingDesc>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#511]
[This is the first of a few tickets related to the TEI/ISO standard for transcriptions of spoken language]

Add a new element `<transcriptionDesc>` as a possible child of `<encodingDesc>`. This is the place to keep information about the transcription convention used. Such information may be crucial for automatic processing of the document.

    <encodingDesc>
      <appInfo>
         
         
         <application ident="EXMARaLDA" version="1.5.1"> 
           <label>EXMARaLDA Partitur-Editor</label>
           <desc>Transcription Tool providing a TEI Export</desc>
        </application>
     </appInfo>       
     
       <transcriptionDesc ident="HIAT" version="2004">
           <p>Orthographic transcription according to HIAT</p>
       </transcriptionDesc>
     </encodingDesc>

Original comment by: sf_user_thomas_schmidt

**Comment by martindholmes** [comment]
Update: in May, Thomas provided me with a preview unpublished version of the standard which we can examine during the FTF, although we can't publish it. I'll check with him to see if it's published yet.

**Comment by laurentromary** [comment]
The document has been registered as DIS in ISO, which is basically the final ballot before publication and Thomas has integrated all comments we received during the preceding phase. I attach the document here with the same restrictions concerning it being put on line. Note that according to the agreement that exists between the TEI consortium and ISO, the material can be published by the TEI, but without the ISO boilerplate. I guess we’ll deal with this at a later stage when we have a complete convergence.
A propos convergence, note that you’ll see there the annotationGrp, which also used to appear in the standOff proposal. I think it is unfortunate that the council has blended the two structural levels in the standOff proposal and renamed annotationGrp as listAnnotation. The semantic of the object (as child of standOff and at a lower level +grouping+ chuncks of annotations) are really different. Do your best during the meeting to make this evolve in the right direction.

**Comment by lb42** [comment]
Same comment as on issue #539 : happy to add a new &lt;transcriptionDesc> as child of &lt;encodingDesc ; need some examples

**Comment by laurentromary** [comment]
i'll liaise with Thomas Schmidt on both tickets.

**Comment by laurentromary** [comment]
I am sending to Hugh the ISO document which is under balloting and from which the council can take up examples. Come back to me and Thomas (now subscribed to both tickets) for any additional information.

**Comment by lb42** [comment]
Now added, so closing this ticket. More examples still needed though, so leaving the other ticket open for the moment.
