### ISSUE TITLE
transcription of quranic "end of ayah"-sign

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#517]
Dear Sir or Madam,

I have a request regarding the TEI Guidelines.

I am working at the project „Corpus Coranicum“ at the Berlin-Brandenburg Academy of Science and Humanities. The Corpus Coranicum is working on a documentation of the quran text and we want to use the standards provided by the TEI.

However, the Quran has an occurrence which is – as far as I know – not covered by the TEI Guidelines, namely the divider between verses or “Verstrenner”, Unicode: 06DD, ARABIC END OF AYAH
It is a special characteristic of the quranic text and is used throughout quranic codeces and manuscripts citing the Quran. As the name suggests, it divides the verses of the Quran and displays the verses number in it.

Since there is no such element designated, we thought about using the &lt;lb>- or &lt;w>-element, but that would be a makeshift solution, which doesn't really do justice to the subject. While &lt;lb> is usually used as a empty element for describing the meta-structure of a text, this end-of-ayah-sign is a part of the original text of the manuscript and thus needs to be transcribed as a part of the text itself. As any other “word” in a manuscript the markup of changes like correction, addition, deletion etc. and descriptive attributes like hand, numbering system [there are some different numbering systems of the quran] are required.
Thus we thought about using the &lt;w>-element, but we hesitate to use this as the TEI declares this element as “a grammatical (not necessarily orthographic) word“. And the end-of-ayah-sign is neither: it is kind of a structural markup written by the scribe itself and not necessarily used in a consistent way throughout the manuscript, nor across different manuscripts.

Therefore we would be glad if the TEI Guidelines would supply an element especially for this occurrence or if you could point us to a well-thought and coherent solution. Plese note that the attached example contains hypothetical annotation in the lines 1-3 of this special charakter, which is to seen on the scanned image as a pile of four or more dots.

With best regards

Tobias J. Jocham

Original comment by: sf_user_mondenkind77

**Comment by martindholmes** [comment]
If these are a sort of heading similar to "Chapter 5", then the verses could be wrapped in `<div>` elements with these numbers tagged as `<head>`. On the other hand, if the verses can be seen as a sort of list of items, then these could be tagged as `<label>`s. Another approach would be to use `<label>` independently of the list structure. A fourth option would be to use `<fw>` as an analogy with page numbers, but that seems rather inappropriate given the association of `<fw>` with early modern print page structures.

Perhaps there's an argument here for a milestone element that is not `<fw>` but which can contain markup. Before going there, though, it would be best to find out from the original submitter why none of the above approaches will work for their context.

**Comment by emylonas** [comment]
spoke with Tobias Jocham - they did some more research and are using `<pc>` to mark these characters (as also suggested by @raffazizzi). This allows them to treat the ayah character as an alphabetic item and use editorial markup. This is what they couldn't get if they were to use an element that represents a break. So they are happy with their solution, and I think it's the right one. I suggest we close the ticket.

**Comment by hcayless** [comment]
Agreed. Thanks Elli!
