### ISSUE TITLE
state (or model.*StateLike) should contain precision

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#518]
This bug report is a follow-up on the discussion found in <https://listserv.brown.edu/archives/cgi-bin/wa?A2=tei-l;fc2bf4f.1307>.

[Bug #585](https://sourceforge.net/p/tei/bugs/585/) contains a proposal to deal with fuzzy dates:

~~~~~
<state from="1382" to="1477">
   <precision match="`@from`" atLeast="1382" atMost="1430"/>
   <precision match="`@to`" atLeast="1444"  atMost="1477"/>
   <p>Catholicos-Patriarch of the Church of the East.</p> 
</state>
~~~~~

That report only covers the addition of `att.ranging` to `precision`. But in addition to implement that proposal, it is also necessary to allow `state` to contain `precision`. In order to cover all possible uses of state-like elements, I propose to add `precision` to all of `model.orgStateLike`, `model.persStateLike` and `model.placeStateLike`.

Original comment by: @frederik-elwert

**Comment by peterstadler** [comment]
already done, only forgot to close the issue
