### ISSUE TITLE
precision should be a member of att.datable*

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#519]
This bug report is a follow-up on the discussion found in https://listserv.brown.edu/archives/cgi-bin/wa?A2=tei-l;fc2bf4f.1307.

[Bug #585](https://sourceforge.net/p/tei/bugs/585/) contains a proposal to deal with fuzzy dates:

```
<state from="1382" to="1477">
   <precision match="`@from`" atLeast="1382" atMost="1430"/>
   <precision match="`@to`" atLeast="1444"  atMost="1477"/>
   <p>Catholicos-Patriarch of the Church of the East.</p> 
</state>
```

That report proposed the addition of `att.ranging` to `precision`. In an e-mail discussion, Thomas A. Carlson pointed out that this covers the case of full-year dates, but fails to model more precise date information since `att.ranging` has a data type of `data.numeric`. But it might also be desirable to encode something like this:

```
<state type="reign" from="0501" to="0503-06-15">
    <precision match="`@to`" notBefore="0503-05-17" notAfter="0503-07-12"/>
</state>
```

For this reason, I propose to add `att.datable*` to `precision`. This would allow to use `notBefore*` and `notAfter*` to encode precision of dates.

Original comment by: @frederik-elwert

**Comment by martindholmes** [comment]
I still agree with my comment in May: we should close the ticket without further action. But I'd like to see whether Syd thinks the Schematron could be safely added.

**Comment by jamescummings** [comment]
Since we didn't test or agree that it could be done safely, I'd err on the side of caution here. We can do the xpath as string to xpath with xsl:evaluate but this is either an extension or xslt3 if I recall correctly.

**Comment by martindholmes** [comment]
I'm closing this ticket since I don't believe the Schematron can be safely or effectively added.
