### ISSUE TITLE
Allow <lem/> to Contain Chunk-Level Markup

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#522]
In an edition I am currently porting from P4 to P5, variant readings have been tagged 
in parallel segmentation encoding on the chunk as well as on the phrase level.
The conversion has been facilitated by a project-specific customization of the P5-All
schema which changes the content model and/or class membership of <app/>, <lem/> and 
<rdg/>:

~~~~~
<elementSpec ident="app" module="textcrit" mode="change">
    <classes mode="change">
        <memberOf key="model.divLike"/>
        <memberOf key="model.pLike"/>
    </classes>
</elementSpec>
<elementSpec ident="lem" module="textcrit" mode="change">
    <content>
        <rng:zeroOrMore>
            <rng:choice>
                <rng:text/>
                <rng:ref name="model.divLike"/>
                <rng:ref name="model.divPart"/>
                <rng:ref name="model.gLike"/>
                <rng:ref name="model.phrase"/>
                <rng:ref name="model.inter"/>
                <rng:ref name="model.global"/>
                <rng:ref name="model.rdgPart"/>
            </rng:choice>
        </rng:zeroOrMore>
    </content>
</elementSpec>
<elementSpec ident="rdg" module="textcrit" mode="change">
    <content>
        <rng:zeroOrMore>
            <rng:choice>
                <rng:text/>
                <rng:ref name="model.divLike"/>
                <rng:ref name="model.divPart"/>
                <rng:ref name="model.gLike"/>
                <rng:ref name="model.phrase"/>
                <rng:ref name="model.inter"/>
                <rng:ref name="model.global"/>
                <rng:ref name="model.rdgPart"/>
            </rng:choice>
        </rng:zeroOrMore>
    </content>
</elementSpec> 
~~~~~

Please consider adopting this change in the next version of P5 as this seems to be a long-standing issue with the manual encoding of textual variance. For further information, see also the [specific section in the TEI Wiki page of the SIG Manuscripts](http://wiki.tei-c.org/index.php/Critical_Apparatus_Workgroup#Inclusion_of_structural_markup_in_the_apparatus) and its list of example use cases, e.g.

* http://tei.markmail.org/thread/tbzi2yj5xd4dto34
* http://tei.markmail.org/thread/jyezaqfycaldtdcv
* http://tei.markmail.org/thread/fbyuxyabbxq4rwbr
* http://tei.markmail.org/thread/vrwkl7kkruulyjzh
* http://tei.markmail.org/thread/x5agpwzn4hiwwwcx

While the elevation of <app/>, <lem/> and <rdg/> to the chunk-level will not solve
possible overlap issues, resulting e.g. from variance on the structural level of a
text, it would ease the encoding of larger chunks of variant text and provide collation
software with more flexibility in encoding its results.

Original comment by: @gremid

**Comment by hcayless** [comment]
Fixed in c39236ff46d54725bb5cac51e125c56db366bb7b.
