### ISSUE TITLE
a new ODD element for pointing at datatypes

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#530]
We have two sorts of macros in the TEI, for datatypes (eg data.sex, data.xText etc) and for
patterns (macro.paraContent). These are rather different beasts, differentiated by their "type" attribute. In the Pure ODD reformulation of the content model, it seems like a good time to give the datatypes their own high level <dataSpec> and <dataRef> elements, allowing us to think about deprecating the pattern macros which can confuse readers.

Original comment by: @sebastianrahtz

**Comment by lb42** [comment]
Implemented as described here in branch lb42-pureodd. Some stylesheet issues remain.

**Comment by lb42** [comment]
Closing  as this is now implemented in release 2.9.1
