### ISSUE TITLE
replace @key with @ref for the <resp> example

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#535]
At present the example reads `<resp key="com">compiler</resp>` 
I propose to get rid of the `@key` attribute and rather use the linked data approach: `<resp ref="http://id.loc.gov/vocabulary/relators/com.html">compiler</resp>`

Original comment by: @peterstadler

**Comment by Martin-de-la-Iglesia** [comment]
I noticed this change only now and, frankly, don't see the point. The Note still reads:

> ...by referring directly (using `@ref`) or indirectly (using `@key`) to a standardized list...

So `@key` isn't really deprecated. I understand that `@ref` is the preferred option here, but why do away with the `@key` example entirely? Why not keep both?

**Comment by jamescummings** [comment]
Hi Martin,

Perhaps we should change that note as well.  The council has several times made and confirmed the decision that use of `@ref` whether directly with URIs or using private URI schemes (documented with `<listPrefixDef>` are better practice than using ad hoc systems or magic numbers in `@key`.  However, there are plenty of people out there actively using `@key` and it was decided it should not be deprecated, but just de-emphasised. Hence, by removing it from examples what we are saying is "`@key` is not *wrong* but `@ref` is preferred."  Changing the note could also be a possibility.

**Comment by lb42** [comment]
Just for the record I disagree with the suggestion that @key should be deprecated. It is widely used for example to supply a preferred form for an author's name. This doesn't need to be an XML identifier nor a URL. You might wish people would use Uris for such thibgs but they don't always and we won't win friends by telling them they are naughty for not doing so.

**Comment by jamescummings** [comment]
Hi @lb42 I believe that argument was precisely why we steered away from deprecation.  It is too much of a backwards incompatibility step to do that since it has been in general use over multiple P versions of the guidelines. I think using it for preferrred form of an author's name seems wrong (I'd prefer a different attribute). But I'm not going to argue or tell people they are wrong. ;-)

**Comment by Martin-de-la-Iglesia** [comment]
OK, but still, if `@key` is a possible encoding mentioned in the Note, there should be an example of how to use it. Removing `@key` from the Note would also be fine with me.

**Comment by jamescummings** [comment]
Note modified at 909d370
