### ISSUE TITLE
Support for non-ISO schematron (1.4) should be removed

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#537]
The spec for constraintSpec/`@scheme` includes the value "schematron" (meaning the old 1.4) and "isoschematron" (the current version we all use). Council discussions 2014-11-19 propose that we remove the former (which we no longer use and no longer want to encourage), and change the latter value to simply "schematron" (meaning ISO Schematron). This involves:
1. Changing the spec.
2. Changing usage in the Guidelines.
3. Changing the Stylesheets.
4. ???

This has to be carefully planned and run past the community, of course.

Original comment by: @martindholmes

**Comment by hcayless** [comment]
Prod to @sydb to work on this.

**Comment by sydb** [comment]
Posted [query](https://listserv.brown.edu/?A2=TEI-L;6051e2c9.1607) to TEI-L 2016-07-29 ~03:39Z.

Checked-in 5f34622, which corrects the spelling of one or two “schematron” (to “Schematron”), and removes vestigal declarations of the Schematron 1.x namespace.

**Comment by sydb** [comment]
Council approves follwing (slightly non-backwards compatible) process:

1. change **semantics** of `"schematron"` to mean ISO Schematron
2. deprecate `"isoschematron"` as a value
3. at end of deprecation period remove `"isoschematron"`

**Comment by nathangibson** [comment]
Should the examples at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-constraintSpec.html be updated to show `@scheme="schematron"` instead of  `@scheme="isoschematron"` ?

**Comment by sydb** [comment]
As well as lots of others, @nathangibson . Fixed in b13a58b , pending Mr. Jenkin’s approval.

**Comment by nathangibson** [comment]
Thank you @sydb !

**Comment by Martin-de-la-Iglesia** [comment]
The current constraintSpec/@scheme definition (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-constraintSpec.html#tei_att.scheme) reads: "supplies the name of the language in which the constraints are defined Suggested values include: 1] schematron(ISO Schematron) ; 2] schematron(ISO Schematron)" - surely this isn't correct? (I'm referring to the duplicate values, not the missing full stop. Though the latter should be corrected too.)

**Comment by sydb** [comment]
Egads, @Martin-de-la-Iglesia ! You are right, of course. An error introduced by yours truly at b13a58b7649e70f12ff690ac069d6499f0cd9c26. I did not notice this post (as the ticket is closed) until just now, only because I was cleaning out my browser tabs. :-)

I will fix this toot sweet. Almost too little too late, of course, as there is only 1 more release scheduled before the whole thing goes away.

**Comment by sydb** [comment]
Fixed in 27c1707 (pending Mr. Jenkins’ approval).
