### ISSUE TITLE
Using `<zone>` for points and paths rather than shapes

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#541]
I'm working on the encoding of a historical map, and finding that I really need to be able to define paths on the map surface, not just closed shapes. `<zone>` is really constrained so that you cannot use it for paths; the `@points` attribute must have more than two points, so a straight line from one point to another cannot be captured with it, and the older `@ulx`, `@uly` and friends are intended to define a bounding rectangle.

I think the ability to encode both points and paths is a perfectly simple and reasonable requirement, so I'd like to propose several possible approaches:

1. The `<zone>` element could be designated the appropriate way to do this, and the current constraint on `@points` removed so that it can contain one or two points only. The definition of `@points` would have to be updated, removing an existing current ambiguity: at the moment, we don't say whether the initial coordinate needs to be repeated to close the shape. The new definition would say that if the initial coordinate is repeated at the end, the result is a closed shape, while if it is not, the result is a path.

+ The `<zone>` element could be provided with two additional attributes, one of which is `@point` (taking a single coordinate) and the other is `@path` (taking a sequence of two or more coordinates, which are understood not to be closed to form a shape).

+ One or two new elements might be created alongside `<zone>`: `<point>` and `<path>`. The latter could inherit `@points`, but with a different constraint, so that two coordinates would be allowed, and the former would need a different attribute (perhaps `@coords`).

I prefer the first solution myself, because it's simpler; the only real objection I see is that it stretches what some people might see as the actual meaning of the word "zone",

Original comment by: @martindholmes

**Comment by hcayless** [comment]
If Martin feels he needs a `<path>` element, then he should request one. `<zone>` is clearly defined as an area. Closing.
