### ISSUE TITLE
Make occupation part of the content model of author

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#542]
Whereas occupation can be a child of person by construction it cannot appear within the (very flat) content model of author. Still such information is needed when describing author information in publications when a little biographical description is provided as in:

~~~~~

<author>
	<persName>
                <forename type="first">Olivier</forename>
                <surname>Le Deuff</surname>
	</persName>
        <email>oledeuff@gmail.com</email>
        <occupation>
                <p>Docteur en sciences de l’information et de la communication, <hi rend="bold">Olivier Le Deuff</hi> a soutenu en 2009 une thèse sur <hi rend="italic">La culture de l’information en reformation</hi>. Il est chercheur au laboratoire PREFics (Plurilinguismes, Représentations, Expressions Francophones - information, communication, sociolinguistique), une composante du PRES Université européenne de Bretagne, Université Rennes 2. Il est également webmaster du Guide des égarés (<ref target="#www.guidedesegares.info"/>).</p>
        </occupation>
</author>

Behind this request there is also the subliminal message that author should be a little more aligned to person, but would not want to delay the decision on this ticket on the basis of a more general debate (unless the council thinks that this alignment is just obvious to have)

Original comment by: @laurentromary

**Comment by jamescummings** [comment]
Sure, people might not want to do it the right way, but I think us fundamentally changing the nature of an existing element to support that is bad practice.  If they don't want to start constructing a listPerson to begin with then let them use an intermediate editing schema that allows them to do all sorts of naughty non-TEI conformant things and then transform that into valid TEI for publication.  I still think Laurent's examples and use cases are confusing publication with encoding.

**Comment by laurentromary** [comment]
I agree with James that there is a deep ontological debate which we should cool down for the time being. Let us close this ticket and see when there is an opportunity to better identify the use cases and needs.

**Comment by fabio-ciotti** [comment]
So, shall I close reject?

**Comment by smjwsk** [comment]
I'd say so, yes
Am 28.10.2015 11:20 vorm. schrieb "Fabio Ciotti" <notifications@github.com>:

**Comment by lb42** [comment]
Please close, reject.

**Comment by fabio-ciotti** [comment]
The Council, given the general contrariness of members aknowledged by the proposer himself, decide to reject this FR and close the issue
