### ISSUE TITLE
align oVar/@type with the general taxonomy of grammatical features

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#544]
Request: bring the oVar/`@type` in line with the independently existing mechanism for referencing grammatical features.

When looking at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DI.html#DIHW , it seems awkward to me to use the `@type` on oVar for exclusively and purely grammatical information ("1] pt(past tense) ; 2] pp(past participle) ; 3] prp(present participle) ; 4] f(feminine) ; 5] pl(plural)"). 

We look here at a microsystem (indeed a tumor, I would say) of taxonomy with a corresponding set of arbitrary (even if common) abbreviations. I say "tumor" and "arbitrary", because in this same chapter, we introduce the gram and gramGrp, which can be given externally-anchored interpretations thanks to the DCR attributes. Using `@type` for this, and listing the values of `@type` as completely independent and dissociated from the gram(Grp) system, feels wro-o-ong.

Original comment by: @bansp

**Comment by sydb** [comment]
Council sub-group thinks we should ask @stefaniegehrke and @bansp to take a careful look at this (and #545) and make a concrete recommendation.

**Comment by sydb** [comment]
Actually, @laurentromary points out that once #545 is dealt with, this can be closed. @lb42 closed that one some time ago; thus …
