### ISSUE TITLE
Deprecate oVar and pVar, Revamp oRef and pRef

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#545]
The TEI dictionary chapter comprises four element for referring back to forms in dictionary entries (oRef, oVar, pRef, pVar), whose respective usage has never corresponded to clear-cut scenarios, especially because of the lack of clear set of use cases and examples. This has lead to a low usage of these elements in most TEI based dictionary projects but also in the absence of best practices for all the concrete cases (examples, etymology) where marking forms and associating them to (real or virtual) entries would help formalising lexical content in a systematic way. 

The main issue is that the difference between pRef and pVar (resp. oRef/oVar) does not match the logic of tagging form references in a dictionary entry: 
- pRef (resp. oRef) is limited (empty content) to the case where the form is exactly the one on the same entry, which is rarely the case (e.g. when orthographic variants exist)
- pVar is only intended to be used when there is a variation (e.g. inflected form) but contrary to pRef, but with its non empty content, it is often tempting to use it to mark all types of forms

It has also been pointed out that there are also issues related to the unsatisfactory  definition of `@type` and the absence of `@notation`.

Proposal: we suggest to drop oVar and pVar and extent both the scope and content model of pRef and oRef to offer a simple system for the annotation of forms (orthographic and phonetic) in dictionary entries, with a clear parallel to orth and pron in the description of forms.

The main changes would be:
- allow text in oRef and pRef; while keeping the possibility to leave them empty when necessary
- make them member of att.typed
- make them member of att.lexicographic to bring them in line with and enable full correspondence with linguistic/lexicographic usage of orth> and prone
- add `@notation` in pRef in order to bring it in line with pron (probably a good opportunity to make a class out of `@notation`); useful in cases where there are more than one notations being represented in pron
- from a semantic point of view, allow these elements to point to any dictionary entry not just the current entry’s head item (same dictionary or even other dictionaries in the case of the marking up of etymology)

Original comment by: @laurentromary

**Comment by stefaniegehrke** [comment]
seems like there are existing projects using '<oVar>', see the attached sample I recently looked at :

 <form type="full">
         <orth>
            <oVar>U</oVar>nion of <oVar>E</oVar>uropean <oVar>F</oVar>ootball <oVar>A</oVar>ssociations
         </orth>
      </form>

**Comment by laurentromary** [comment]
Stefanie: your message could not be read. I see two not incompatible strategies: a) deprecate the unwanted elements over a decent period (2 years); b) inform/consult the community concerning a possible transition. I gather there is a small group of concerned users in any case.

**Comment by stefaniegehrke** [comment]
thank you for the hint, Laurent 

so once again : seems like there are existing projects using `<oVar>`, see the attached sample I recently looked at :

`<form type="full"><orth><oVar>U</oVar>nion of <oVar>E</oVar>uropean <oVar>F</oVar>ootball <oVar>A</oVar>ssociations</orth></form>`

**Comment by laurentromary** [comment]
Trying to re-activate this. A first step could be to adapt oRef and pRef so that it bears the same content model as oVar and pVar, and add @notation to the two by the same token. We could indicate in the documentation of oVar and pVar as a remark that there is a presence to use oRef and pRef as main representation tool.

**Comment by lb42** [comment]
So, to summarize: the proposal is
a) deprecate use of oVar and pVar, recommending that oRef or pRef be used in preference
b) make the proposed list of values for @type a semi-closed one
c) add *Ref elements to the new att.notated class
d) change content model of *Ref to match that of corresponding *Var element, but with the option of being empty
All of that seems eminently simple and do-able. The ticket is with @stefaniegehrke to implement at present, but I can do it later this week if she asks me nicely!

**Comment by laurentromary** [comment]
That would be great!

**Comment by hcayless** [comment]
@lb42: @stefaniegehrke says go right ahead.

**Comment by lb42** [comment]
Implemented as above. The @type valList for oRef is already open and pRef doesn't have one.

**Comment by martindholmes** [comment]
Reopening this because the deprecation period is now over and the build is failing because of oVars.

**Comment by martindholmes** [comment]
Syd will do this while I do the Stylesheets problem.

**Comment by martindholmes** [comment]
Took a quick look at this and there are a lot of examples in other specs that use oVar, specifically in `<case>`, `<mood>`, `<per>` and `<tns>`. pVar is still being recommended in the Dictionaries chapter.

It rather looks like deprecation was added, but the additional steps of removing examples and references were not done. I see that the original request was for a two-year deprecation period. I think it might be a good idea to extend the deprecation for another six months or a year, and make sure there's at least one release that has fully-implemented deprecation (no examples or references) before actually removing these elements.

**Comment by bansp** [comment]
We might even consider raising Martin's proposal to the status of a principle.

**Comment by sydb** [comment]
I’m in favor of @martindholmes ’s proposal, too. I expect to start tackling this today, but he is right, there is quite a bit of work to be done. Unless I hear objections, I will change the `@validUntil` to mid-summer rather than actually remove `<oVar>` & `<pVar>`.

**Comment by martindholmes** [comment]
Forgive me for jumping in, but I've added a two-month extension to the deprecation of oVar and pVar in commit 1476d8d so that the build will go ahead on Jenkins and we can see if other commits are OK. Feel free to revert or override when a decision is made about how to proceed.

**Comment by sydb** [comment]
Since I got no response from [the question on TEI-LINGUISTICS](https://listserv.brown.edu/?A2=tei-linguistics;eeb87c24.1703), I went ahead and made the changes. Pending discussion there, we can change the one example I’m not sure of (in DI, an `<egXML>` that now has an `<oRef>` inside an `<oRef>`).

 Pushed at 2df3800.

**Comment by bansp** [comment]
Thanks, Syd. I missed that message, but I'd hesitate about how to reply because oRef is one of the hot topics of the TEI-Lex0 group now, and I wasn't much involved in the initial suggestions. Anyway, it's great to see things moving, thanks!

**Comment by sydb** [comment]
As far as I know, this issue is being kept open only because I am not confident about the encoding of the example “take … < was quite ~n with him >” in section DIHW (in chapter 9, Dictionaries). If someone more learned than I could confirm that it is OK, or suggest an improvement, that would be good.

**Comment by bansp** [comment]
We're meeting this Monday (whole day), and I will make sure to put this on the agenda.

**Comment by martindholmes** [comment]
The temporary extension on the expiry of oVar and pVar which I implemented in March has now expired, and the build is broken again. Should I extend it further, or are you ready to remove those elements?

**Comment by laurentromary** [comment]
I would definitely support this but we should make sure that there is an explicit remarks on oRef and pRef that these element are taking up the semantics of their counterparts.

**Comment by sydb** [comment]
OK. My plan is to remove these 2 elements this afternoon. Gives us ~2 months to reverse course if we don't like it.

**Comment by sydb** [comment]
So `<pVar>` and `<oVar>` are now gone as of be2ca61. If Mr. Jenkins is happy, will close this ticket.
