### ISSUE TITLE
<defaultVal> should be removed from all specs

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#546]
The &lt;defaultVal> element was provided for backwards compatibility in P5 ODD as a way of representing the default value for an attribute, i.e. that which should be assumed if the attribute is not specified. This was useful in the SGML world where tag minimization was an issue, but seems much less appropriate in XML, where its effect is to require a parser to assume the default value was supplied even if the attribute is unspecified. This is annoying if the user attempts to constrain the value by supplying a closed &lt;valList> : if they forget to remove the &lt;defaultVal at the same time, and the default value is not on the closed value list, then it becomes impossible to create a valid instance. It is also a nuisance for software like oddByExample which derives an ODD from document instances because occurrences of an attribute with a default value are indistinguishable from attributes for which a value is actually specified in the source document. 

In most cases, I think the intention of the element would be better subsumed into the attribute definition ("if this attribute is not specified then ...") rather than being magically created by the parser. We hate magic.  

However there are quite a lot of uses of this in P5 (72 to be exact, some of them in attribute classes), so removing them is not a trivial change.

Original comment by: @lb42

**Comment by martindholmes** [comment]
Council subgroup 2015-10-26: There is a philosophical disagreement about whether defaultVal (which to most people is unwanted magic causing them to have made assertions they never knew about) is simply wrong, and the position that defaultVal should have a more nuanced function which acts more as documentation (rather than finding its way into schemas).

**Comment by martindholmes** [comment]
Council 2015-10-26: Approach this from the bottom up: SB and MH to look at each individual defaultVal and decide if they can agree to remove it or not. What is left will then be the focus of a less complicated discussion on the abstract issue.

**Comment by martindholmes** [comment]
SB and MDH discussion: Our first candidates should be: atts with datatype of enumerated and no valList. We could generate a list of those (if they exist) to start from.

**Comment by lb42** [comment]
If there are any such they will not generate valid schemas

**Comment by martindholmes** [comment]
The only instance is the `@new` attribute on `<shift>`.

**Comment by martindholmes** [comment]
On the topic of `@new`, see this ticket also: 

https://github.com/TEIC/TEI/issues/512
