### ISSUE TITLE
Allow g in notatedMusic

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#547]
With the rise of SMuFL, or Standard Music Font Layout, it is becoming easier to properly use music notation characters in running text via a standardized Private Use Area in Unicode.

Peter Stadler has created a browser to look for symbols supported in SMuFL: http://edirom.de/smufl-browser/index.html
This system also gives you a suggested TEI encoding for every symbol using &lt;g/>.

I think it would be great to combine this use with <notatedMusic>, which currently does not allow &lt;g/> in its content model.

Consider for example this image and the corresponding (partial) encoding:

![Ex of music notation in running text](http://www.tei-c.org/SIG/Music/_a/images/examples/beethoven-ex1.jpg)

    <ab>
    beym 9ten Takt, wo die 
    <notatedMusic>
      <g ref="http://edirom.de/smufl-browser/accidentalWyschnegradsky6TwelfthsSharp.xml"/>
      <g ref="http://edirom.de/smufl-browser/accidentalWyschnegradsky6TwelfthsSharp.xml"/>
      <g ref="http://edirom.de/smufl-browser/accidentalWyschnegradsky6TwelfthsSharp.xml"/>
    </notatedMusic>
    sich in ...
    </ab>

Original comment by: @raffazizzi

**Comment by martindholmes** [comment]
Council subgroup 2015-10-26: We believe it makes no sense to have g where you can't have text; "do re mi" is arguably notatedMusic. So the content model should presumably include macro.xText.

**Comment by raffazizzi** [comment]
This should have been closed: see #557.

**Comment by martindholmes** [comment]
Council 2015-10-26: Close this ticket in favour of #557.
