### ISSUE TITLE
More flexible dateline for periodical edition tracking

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#549]
In order to facilitate edition tracking (and tracking reprints and information spread) it would be very useful to allow the dateline tag to be used directly within within body/p.  It would also be useful to be able to include not only date, but also source--that is, the previous named or alluded to publication in which the piece appeared.

For example:

We have recently received the following from <dateline date="1820-03-03" source="New York Advertiser">the Advertiser, dated the 3rd instant</dateline>, in which a very interesting account of....

Original comment by: @mhbeals

**Comment by lb42** [comment]
Closing this, as there has been no further discussion since May, when Council last agreed to close it.
