### ISSUE TITLE
guidance on use of @calendar and @datingMethod

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#554]
Could anyone provide better differentiation between the <date> attributes `@calendar` and `@datingMethod`? Ideally in the pages of the two attribute classes where each of them is defined, for clearer comparison of their use.

Original comment by: @simonastoyanova

**Comment by martindholmes** [comment]
Made a final tweak to the examples on att.datable.custom. I think we've covered this for the moment.
