### ISSUE TITLE
Allow a text-wrapper element (e.g. ab) in notatedMusic

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#557]
Extend the content model of notatedMusic to allow a text-wrapper element such as ab. This is useful in particular for identifying the presence of notation in running text. For example:
- tonic solfa notation (do, re, mi)
- other text-based notation (e.g. ancient greek notation)
- unicode music symbols (including SMuFL)

Original comment by: @raffazizzi

**Comment by raffazizzi** [comment]
Sounds good - restricting content model of `<ab>` seems unnecessary.

**Comment by smjwsk** [comment]
Council decision: macro.xtext mixed in to the current content model
