### ISSUE TITLE
tagUsage/@render should be deprecated

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#558]
Per FR 520:

https://sourceforge.net/p/tei/feature-requests/520/

we [will] now have a better way of providing default rendition declarations for elements. Syd suggests that we deprecate the existing tagUsage/`@render`, and provide a stylesheet for converting it to the equivalent rendition+`@selector` representation.

Original comment by: @martindholmes

**Comment by jamescummings** [comment]
I'd say deprecate this according to our deprecation mechanism policy.

**Comment by lb42** [comment]
Implemented at commit 0b7e98c100f09c44cde5fd25236ff2eb8c111973
