### ISSUE TITLE
show ODD declaration on the specs pages

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#559]
It would be nice to see the ODD declaration (instead of the RelaxNG declaration) when looking up the specs of a given element. That'd be especially useful to understand local redefinition of attributes, see e.g. http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-title.html

Original comment by: @peterstadler

**Comment by jamescummings** [comment]
I agree with @peterstadler's comment that the XML source spec file should be linked to from the footer on a ref-* page, but he will put in a separate issue for this in the Stylesheets repo.

**Comment by peterstadler** [comment]
moved to https://github.com/TEIC/Stylesheets/issues/125
