### ISSUE TITLE
@cert needs data.probability as well as data.certainty

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#560]
This arose as part of our work on the standoff proposal, but has more general utility:

Certainty expressed by a human judge is typically imprecise, hence the current values of `@cert`; but annotation in particular may be done be tools such as natural language parsers, which express their "judgements" regarding (for instance) a word's being a member of a grammatical category in the form of probability (values between 0 and 1). To support this, the `@cert` attribute should have a datatype which is a choice between data.certainty and data.probability.

Original comment by: @martindholmes

**Comment by jamescummings** [comment]
this looks like it has already been done. Why are we discussing it again?

**Comment by lb42** [comment]
if requirement is to express certainty as defined by an algorithm rather than by a human I think a different attribute might be a better choice. However since this seems to have been implemented anyway.,..

**Comment by laurentromary** [comment]
Is this implemented for the next release? I cannot see anything in the online version of the guidelines: http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-att.global.responsibility.html

**Comment by raffazizzi** [comment]
@laurentromary yes, this has *just* been implemented, so not released yet.

**Comment by laurentromary** [comment]
Excellent! Thanks.
