### ISSUE TITLE
Version of Appendix C for TEI Simple

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#566]
For the TEI Simple project it would be nice to have a version of the current Appendix C in the Guidelines that lists only the elements etc. that are valid in TEI Simple. I assume this is a relatively straightforward process, though I don't know how to do it. If somebody could do it or teach me how to do it I would be very grateful. I noticed that both jtei and TEI Lite have parts of Appendix C--i.e. the description of an element with examples but lack the summary table, which over the years I have found enormously useful. 

Original comment by: martinmueller

**Comment by hcayless** [comment]
Having a transformation that produces standalone documentation for an ODD in the form of Appendix C would be awesome, and is probably not too hard to do. Opening a Stylesheets Feature Request.

**Comment by hcayless** [comment]
Closing. Will implement in Stylesheets
