### ISSUE TITLE
Allow <relation> to occur intermittently within parent elements

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#567]
Currently in the guidelines, `<relation>` is allowed to occur within the following:

```
core: listBibl
namesdates: listEvent listNym listOrg listPerson listPlace listRelation
```

There are many uses for `<relation>` that enable users to define types of relationships between these given types of data. This tool is very useful for modeling data in ways that are consistent with ontological information and conversion to RDF.

However, even though `<relation>` is allowed to occur in any of the above elemental contexts, the way the content model is defined (below) it is not currently permitted to occur intermittently amongst the `<place>`, `<event>`, `<person>`, etc.  elements whose relationship to one another it is defining. Thus it is effectively only useable as a standoff element.

```

  (
     model.headLike*,
     ( model.placeLike | listPlace )+,
     ( relation | listRelation )*
  )

```

While use of `<relation>` as a standoff element may be acceptable for those using automated processes to gather and structure pre-existing data, it is not feasible for those who need to manually encode such data, as it requires a cumbersome and untenable process of scrolling back and forth between the different sections of a document.

While this may require added complexity in defining the content model, doing so would allow the element to reach its full functional potential and would almost definitely increase its usage.

What I propose is to change the model to allow for such uses of `<relation>` as in the following example:

```

         <listPlace>

            <place n="681" xml:id="Öst.">
               <placeName xml:lang="de">Österreich</placeName>
               <placeName xml:lang="de" full="abb">Öst.</placeName>
               <location>
                  <geo corresp="#gis_region_id-862"/>
               </location>              
            </place>

            <relation name="vaterregion" active="#Öst." passive="#Kä #OÖ #Bgl. #NÖ #Sa. #St. #Tir. #W. #Vlbg."/>

           <place n="181" xml:id="OÖ">
              <placeName xml:lang="de">Oberösterreich</placeName>
              <placeName xml:lang="de" full="abb">OÖ</placeName>
              <location>
                 <geo corresp="#gis_region_id-735"/>
              </location>
           </place>

            <place n="101" xml:id="Kä">
               <placeName xml:lang="de">Kärnten</placeName>
               <placeName xml:lang="de" full="abb">Kä</placeName>
               <location>
                  <geo corresp="#gis_region_id-708"/>
               </location>
            </place> 
            .....

```

Original comment by: @iljackb

**Comment by raffazizzi** [comment]
* relationships between places can be expressed by nesting (see [`<place>` examples](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-place.html))
* we think that `<relation>` stand-off elements are best grouped together in a `list*` element
* @iljackb suggested use of `<relation>` would aurguably simplify authoring, but that could still be done as an intermediate format (eg with a dedicated ODD) and move the elements to their proper place at a later step.

So we suggest no change.

**Comment by sydb** [comment]
My (current) suggestion:
(
     model.headLike*,
     ( model.placeLike | listPlace ),
     ( model.placeLike | listPlace | relation | listRelation )*
  )
Thus loosening the content of <listPlace> (and yes, same for <listPerson>, <listOrg>, etc.), and ALSO
move listRelation from model.biblPart to model.listLike, and change all examples in the Guidelines to demonstrate <relation> only in a <listRelation>, rather than as a child of <listPlace> et al.

I have not yet investigate what backwards-compatibility problems this might cause.

**Comment by ebeshero** [comment]
F2F (Victoria 2017) @sydb should go ahead and test this!

**Comment by sydb** [comment]
OK. The suggested changes of [2015-10-26](https://github.com/TEIC/TEI/issues/567#issuecomment-151117254) are in 3 parts:
 1. change content models
 2. remove `<listRelation>` from model.biblPart (already has been added to model.listLike, it seems)
3. Change examples

In order:

1. **change content models**
I made this change[1] in a local branch[2], and eye-balled for backwards compatibility problems as I went. I did not see any.
2. **remove `<listRelation>` from model.biblPart**
The (only) effect would be to remove `<listRelation>` as a possible child of `<bibl>`. That would obviously break backward compatibility. But `<bibl>`s can clearly have relations to at least other bibliographic items (n.b. `<relatedItem>`), if not people, places, and things. So maybe it should just stay there?
3. **Change examples** There are no examples of `<relation>` as a direct child of `<listSomething-other-than-relation>` to be changed.

If someone could remind me how to push this new branch of mine, I’d be happy to.

**Note**
[1] The model I proposed allows only 0 or 1 occurrence of `<relation>` or `<listRelation>` before the first `<place>` (or `<nym>` or `<person>`). I cannot at the moment come up with a good excuse for limiting it, and thus made it 0 or more.

**Note-to-self**
[2] On my laptop, named “sydb-567”.
