### ISSUE TITLE
inconsistent encoding of citations to sources of examples

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#576]
In section #ND-org, the example beginning "The TEI institutional hosts are:" contains an XML comment giving the source of the example.  However, this should be encoded using egXML@source as in others.

Syd has done some preliminary searching and found 365 XML comments inside egXML that aren't simply

`<!-- ... -->`

These need investigating.

Syd also noted that we've used ellipses inconsistently as well.  Perhaps worth normalizing these while we're at it.

Original comment by: @kshawkin

**Comment by martindholmes** [comment]
Council 2015-10-26: Close this ticket, but create another one that specifies that Editing the Guidelines should be updated to include instructions that plain ellipses in comments should be used to signify missing elements, while ellipses in square brackets should be used to signify PC Data ellided.
