### ISSUE TITLE
att.textCritical on witDetail

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#610]
In [12.1.2 Readings](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TC.html#TCAPLR), we find the following:
> The hand and resp attributes are intelligible only on an element recording a reading from a single witness, and should not be used if more than one witness is given on the same rdg or lem element. If more than one witness is given for the reading, they are undefined. To convey this information when the witness is one among several, the witDetail element should be used;

But witDetail can't take `@hand`, because it is not a member of att.textCritical. Seems like it should be...

Original comment by: @hcayless

**Comment by raffazizzi** [comment]
I'm not sure - it seems that `<witDetail>` can be used to explain in prose who intervened on the source and how. So the `@resp` on `<witDetail>` will be about the author of the `<witDetail>` prose and not about the the witness itself. If this is correct, then `@hand` would not be correct at this level because it would refer to the author of the prose in `<witDetail>`.

For more structured information on hands, then `<witDetail>` can be used within `<handNote>`

**Comment by hcayless** [comment]
Yeah, actually what we'd need is a local definition of `@hand` that complements `<witDetail>`'s definition of `@wit`. My contention is that `<witDetail>` needs to be able to refer to a particular hand in a particular witness.

**Comment by raffazizzi** [comment]
But wouldn't it be best to use `<witDetail>` in `<handNote>` in that case?

**Comment by jamescummings** [comment]
My suggestion was: <witDetail wit="#msA">This rdg added in another hand. See <ptr target="#hand24"/>

**Comment by sydb** [comment]
Council agrees that expanding the semantics of @hand here is not ideal, and points out that the desired information can be conveyed by pointing to the appropriate <handNote> from within the <witDetail>. So our current suggestion is that we create a new example that does that.

**Comment by raffazizzi** [comment]
Actually I'd like to re-open discussion on this before implementing... Currently one could extract programmatically all readings in a given hand, but only when there is one reading per source. Example:

```
//rdg[@hand='#hand1']
````

```xml
<app>
  <rdg wit="#A" hand="#hand1">moon</rdg>
  <rdg wit="#B">stars</rdg>
</app>
```

But if two sources agree the hand can't be specified and a `<witDetail>` is needed...

```xml
<app>
  <rdg wit="#A #C" >moon</rdg>
  <rdg wit="#B">stars</rdg>
  <witDetail wit="#A">The hand is <ptr target="#hand1"/></witDetail>
</app>
```

How could I extract that information automatically? Typing the `<ptr>` is a sub par solution. While I agree that having `@hand` may be confusing (is the witDetail in a certain hand?), I think it would be much more good than harm...

**Comment by raffazizzi** [comment]
Bump on this - unless we want to revisit it at the F2F

**Comment by raffazizzi** [comment]
Note for F2F discussion - possibly keep status quo and recommend a solution for the example above such as:

```xml
<app>
  <rdg wit="#A" hand="#hand1" >moon</rdg>
  <rdg wit="#C" >moon</rdg>
  <rdg wit="#B">stars</rdg>
</app>
```
or, to avoid duplication:
```xml
<app>
  <rdg wit="#A" xml:id="r1" hand="#hand1" >moon</rdg>
  <rdg wit="#C" sameAs="#r1"/>
  <rdg wit="#B">stars</rdg>
</app>
```

**Comment by hcayless** [comment]
Another solution is to treat hands as separate, like witnesses, and then there's no problem referring to a hand in a witDetail

```xml
<app>
  <rdg wit="#A1 #C">moon</rdg>
  <rdg wit="#B">stars</rdg>
  <witDetail wit="#A1">A1 corrects 'moan' to 'moon'</witDetail>
</app>
```
