### ISSUE TITLE
@expand example in att.lexicographic is incorrect.

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#618]
The reference page:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.lexicographic.html

Has an example for `@expand`

```
<gramGrp>
 <pos>n</pos>
</gramGrp>
```

This doesn't actually use the `@expand` attribute, thus is a silly example. 

Original comment by: @jamescummings

**Comment by hcayless** [comment]
Appears to have been done a year ago by @emylonas, so that's nice.
