### ISSUE TITLE
values of types of titles need to be harmonized

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#66]
The types of titles (or the sample values in the
documentation) need to be harmonized: the sample values
of title have subordinate, parallel and abbreviated,
the ones of titlePart have sub, alt and desc. Maybe
others differ as well, I haven't checked this.

If values are changed, Sebastian's stylesheets maybe
have to be updated as well.

Original comment by: @schassan

**Comment by linuxjackto1** [comment]
thanks www.movied.org
