### ISSUE TITLE
need to harmonize the datatypes of the attributes of layout

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#67]
I see the necessity to harmonize the definitions of
datatypes of the attributes columns and writtenLines of
the element layout with the datatype of the attribute
rulesLines.

Either all of them should be allowed to have a content
of the datatype: data.count | list { data.count,
data.count } or ruledLines shouldn't have it as well.
In the latter case the documentation has to state that
a separate layout element should be used for spans of
pages where these values differ.

I prefer to change the datatype of the attributes
columns and writtenLines.

Original comment by: @schassan

**Comment by linuxjackto1** [comment]
thanks www.movied.org

**Comment by lb42** [comment]
On 05/03/16 14:20, linuxjackto1 wrote:
>
> thanks www.movied.org <http://www.movied.org>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TEIC/TEI/issues/67#issuecomment-192656776>.
>
this is spam

**Comment by bansp** [comment]
Yes sir, and I deleted it and reported that account.

**Comment by lb42** [comment]
Ah, thanks. I was confused by not being able to find it when I came to delete it !
