### ISSUE TITLE
idno in msIdentifier obligatory?

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#68]
Why is it that idno isn't obligatory in msIdentifier?
Right now it is possible to describe (or refer to) a
manuscript only with settlement and repository but no
further identification.
Instead of the current definition

msIdentifier.content =
(
(
country?,
region?,
settlement,
institution?,
repository,
collection?,
idno?
)
| msName
),
( altIdentifier | msName )*

I would suggest to declare either this

msIdentifier.content =
(
(
country?,
region?,
settlement,
institution?,
repository,
collection?,
idno
)
| msName
),
( altIdentifier | msName )*

or this

msIdentifier.content =
(
(
country?,
region?,
settlement,
institution?,
repository,
collection?,
( idno | msName )
)
| msName
),
( altIdentifier | msName )*

Original comment by: @schassan

**Comment by linuxjackto1** [comment]
thanks www.movied.org
