### ISSUE TITLE
@type on listPerson

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#69]
Since inside &lt;profileDesc&gt; I am allowed multiple
&lt;listPerson&gt; elements, would it be possible to have
`@type` on &lt;listPerson&gt;?  

I'm suggesting people might want to classify in some
ways the rational for grouping &lt;person&gt;s in one
listPerson as opposed to another.  I suppose another
option could be to have a new child &lt;desc&gt;, but this
may be overkill.

-James

Original comment by: @jamescummings

**Comment by linuxjackto1** [comment]
thanks www.movied.org
