### ISSUE TITLE
name/orgName

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#781]
p. 446

Text: "`<name type="project">`Brown University Women Writers Project`</name>`"

Suggestion: "`<orgName type="project">`Brown University Women Writers Project`</orgName>`"

Original comment by: @jensopetersen

**Comment by lb42** [comment]
The status of the WWP as a host or otherwise really isn't relevant to this ticket. Jens' suggestion was simply that it would be more consistent with the other things in the list to use &lt;orgName>  here rather than  &lt;name> . Closing.
