### ISSUE TITLE
attDef/desc context disregarded

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#835]
I've noticed that in the following example, Roma reads &lt;desc&gt;manuscript folios&lt;/desc&gt; as the description for the attribute as a whole, rather than using the default TEI &lt;desc&gt;:

&lt;classSpec ident="att.dimensions" mode="change" module="tei" type="atts"&gt;
&lt;attList&gt;
&lt;attDef ident="unit" mode="change"&gt;
&lt;valList mode="replace" type="closed"&gt;
&lt;valItem ident="folios"&gt;
&lt;desc&gt;manuscript folios&lt;/desc&gt;
&lt;/valItem&gt;
&lt;valItem ident="lines"&gt;
&lt;desc&gt;lines of text&lt;/desc&gt;
&lt;/valItem&gt;
&lt;valItem ident="words"&gt;
&lt;desc&gt;words of text&lt;/desc&gt;
&lt;/valItem&gt;
&lt;valItem ident="chars"&gt;
&lt;desc&gt;characters of text&lt;/desc&gt;
&lt;/valItem&gt;
&lt;valItem ident="mm"&gt;
&lt;desc&gt;millimetres&lt;/desc&gt;
&lt;/valItem&gt;
&lt;/valList&gt;
&lt;/attDef&gt;
&lt;/attList&gt;
&lt;classSpec&gt;

Original comment by: sf_user_ianrons

**Comment by peterstadler** [comment]
moving to https://github.com/TEIC/Roma/issues/14, closing here
