### ISSUE TITLE
Namespaces in <exemplum>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#838]
Roma seems to be adding namespaces to &lt;exemplum&gt;s, e.g.
&lt;val&gt;20 × 30 mm&lt;/val&gt;
becomes
&lt;val xmlns:sch="http://purl.oclc.org/dsdl/schematron"
xmlns:ns182="http://www.tei-c.org/ns/1.0"&gt;20 × 30 mm&lt;/val&gt;

I've tried this with my own ODD and some of the templates, with the same result.

Original comment by: sf_user_ianrons

**Comment by peterstadler** [comment]
moved to https://github.com/TEIC/Roma/issues/15, closing here
