### ISSUE TITLE
Processing of <valList>

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#845]
As per
http://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1003&L=TEI-L&T=0&O=D&P=162
and
http://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1003&L=TEI-L&D=0&O=D&T=0&P=288
Roma exits with a fatal error when processing an ODD where &lt;valList&gt; contains unexpected text nodes \(i.e., whitespace\) instead of just &lt;valItem&gt;s.

Possible solutions might involve the use of getElementsByTagName\('valItem'\) or
if \($oChild-&gt;nodeName=='valItem'\) \{ ... \}

Original comment by: sf_user_ianrons

**Comment by peterstadler** [comment]
moved to https://github.com/TEIC/Roma/issues/16, closing here
