### ISSUE TITLE
deprecate use of gram except as a child of gramGrp

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#937]
&lt;gramGrp&gt; is allowed as a child of both &lt;form&gt; and &lt;sense&gt;, but &lt;gram&gt; is allowed only as a child of &lt;form&gt;.  I would like it added to &lt;sense&gt; as well in keeping with feature request 3266021 and in keeping with section 9.3.2, which implies that you can encode grammatical information either way.

Original comment by: @kshawkin

**Comment by lb42** [comment]
Looking at this again, I think the issue is with &lt;gram>s membership of model.morphLike. Moving it out of that class and putting it explicitly in the content models where it is required (inside gramGrp, entryFree, and dictScrap) would be pretty simple, if that's what's required.

**Comment by laurentromary** [comment]
It's more complex than this. I would not decouple `<gram>` from the other morphological descriptors. There are two issues that could help going in the good direction (discussed at length in this thread):
- change the content model of `<etym>` replacing model.morphLike by gramGrp
- do some class surgery (create one class) so that model.formPart (see its definition) only contains the set model.gramPart - model.morphLike (the complementary set of model.morphLike in  model.gramPart, i.e. the class to be created

**Comment by lb42** [comment]
At present:
model.formPart contains  [model.gramPart]  form hyph orth pron stress syll
   model.grampart contains  [model.morphLike]  colloc gramGrp lbl pos subc usg
        and model.morphLike contains case gen gram iType mood number per tns

Is your proposal : 
model.formPart contains [model.something]  form hyph orth pron stress syll
    model.something contains  colloc gramGrp lbl pos subc usg

?

If so, what should we call "model.something" ?

**Comment by laurentromary** [comment]
model.lexicalRefinement : lexical restriction that may occur at various levels of a lexical entry

**Comment by lb42** [comment]
so, just to check: colloc (for example) would be a member of both model.gramPart and the new model.lexicalRefinement class?

**Comment by lb42** [comment]
Made following changes 
- in content for etym, replace model.morphLike by gramGrp
- define new class model.lexicalRefinement as subclass of model.formPart, with members colloc gramGrp lbl pos subc usg

But this won't work: it makes model.formPart ambiguous (it gets one gramGrp from its child model.gramPart, and another from its child model.lexicalResources)

**Comment by laurentromary** [comment]
I cannot understand this problem. The current model is content for model.formPart combine:
- model.gramPart [model.morphLike [case gen gram iType mood number per tns] colloc gramGrp lbl pos subc usg] 
- form hyph orth pron stress syll (direct membership)
If you just group (colloc gramGrp lbl pos subc use ) under model.lexicalRefinement you d'ont add any additional path in the inheritance tree, just an additional level.

**Comment by laurentromary** [comment]
I see you question concerning colic as an example: colloc should not  be a direct member of model.gramPart, but  model.lexicalRefinement should. So the new situation should be for model.formPart:
model.gramPart [model.morphLike [case gen gram iType mood number per tns] model.lexicalRefinement [colloc gramGrp lbl pos subs usg]] form hyph orth pron stress syll

with model.gramPart being organized as two subclasses.
Good luck.

**Comment by lb42** [comment]
Aha... so all the elements that are added to model.lexicalRefinement should at the same time be removed from model.gramPart. That wasn't clear from your earlier comment, though now I think about it it's obvious enough.

**Comment by laurentromary** [comment]
You should see my hand-written class visualisor when I work on such things. Putting this in words in this non native *$£% language is another challenge.

**Comment by lb42** [comment]
i have to draw my own hand-drawn visualiser each time. (and you can always make your comments in the language of moliere and victor hugo if you prefer! )

**Comment by lb42** [comment]
... however we now have loads of examples in the text of the dictionary chapter which are invalid

**Comment by laurentromary** [comment]
I know. A specific ticket for this? I could give a hand over next month.

**Comment by lb42** [comment]
... because model.lexicalRefinement should be a memberOf model.gramPart, not model.formPart (as wrongly suggested above)

**Comment by laurentromary** [comment]
Indeed. That's what I have described right from the beginning.

**Comment by lb42** [comment]
(Well, you didn't correct me when I made the stupid suggestion)
This *is* the specific ticket for this!
The timetable for the next release (just announced) is to freeze source on 15 mars.

Content model is still ambiguous somewhere. Checking.

**Comment by lb42** [comment]
OK, nearly there. It's just generating invalid DTD now.

**Comment by laurentromary** [comment]
Consider the order in which class declaration are made. I remember coming across such problems recently.

**Comment by lb42** [comment]
Indeed. I think that's fixed it now. Test run did not complete but for an unrelated reason.

**Comment by lb42** [comment]
![grampart](https://cloud.githubusercontent.com/assets/660724/13378942/d74076b6-de0e-11e5-98cf-927b47193a11.png)

**Comment by lb42** [comment]
Implemented class mods at commit fae41d5f4dca78b310e304d60747483c28ba54b9
