### ISSUE TITLE
first <p> in ODD gets cut off

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#956]
Here's how you can reproduce the error:

1\. At http://www.tei-c.org/Roma/ , choose to create a customization based on Tite.  Click Start.

2\. Roma sends you to the Customize tab.  Click Save, even without making other changes.

3\. Click the Save Customization tab.

4\. Open the ODD file.  You will get this:

&lt;div type="section" xml:id="intro"&gt;
&lt;head&gt;Introduction&lt;/head&gt;
&lt;p&gt;&lt;ref target="http://www.tei-c.org/Roma/"&gt;Roma web tool&lt;/ref&gt;, can generate these. This
document specifies how TEI Tite should be applied. Its&amp;\#13; organizing model is roughly the

where all the text before

&lt;ref target="http://www.tei-c.org/Roma/"&gt;Roma web tool&lt;/ref&gt;

is lost.  This doesn't happen if you don't click Save in step 2.

Original comment by: @kshawkin

**Comment by peterstadler** [comment]
moving to https://github.com/TEIC/Roma/issues/17, closing here
